### ISSUE TITLE
The charts web music not working.

### ISSUE THREAD

**Issue by ChinmayJain1** [gnumdk/lollypop#1001]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.230
• Gtk Version: 3.18.9-lubuntu3.2
• Linux distribution: kde neon ubuntu 16.04 lts

< First of all, this is my favorite music player. I appreciate every bit of your work to make this, Thanks for this. I've been using this for a year now. 

Upgraded from 0.9.225 to v0.9.230: Tried fresh install and every other possible way. Still the following issues exist: 

1. The charts is not working & displaying any web music. 
2. Lollypop application closes automatically when trying to search for web music. 
>

**Comment by gnumdk** [comment]
Please paste command line output here!
