### ISSUE TITLE
Sync fails when computed file name contains certain characters

### ISSUE THREAD

**Issue by neckcen** [gnumdk/lollypop#1002]
Lollypop 0.9.230

MTP sync fails if the computed file name contains `\`:

     MtpSync::_retry(gi.FunctionInfo(move), (<File object at 0x7f6885f6edc8 (GDaemonFile at 0x3530700)>, <flags G_FILE_COPY_OVERWRITE of type GFileCopyFlags>, None, None)): g-io-error-quark: libmtp error:  Could not send object. (0)
    mtp://...Years%20Back%5CCome.mp3

MTP sync also fails if the computed file name contains `#`:

    MtpSync::_retry(gi.FunctionInfo(move), (<File object at 0x7f6894563c18 (GDaemonFile at 0x7f6868069b30)>, <flags G_FILE_COPY_OVERWRITE of type GFileCopyFlags>, None, None)): g-io-error-quark: The specified location is not mounted (16)
    mtp://...Motherf#ck.mp3

Flat file sync fails if the computed file name contains `\`:

    MtpSync::_retry(gi.FunctionInfo(move), (<File object at 0x7f1c6c4d8f30 (GLocalFile at 0x1a90b00)>, <flags G_FILE_COPY_OVERWRITE of type GFileCopyFlags>, None, None)): g-io-error-quark: Invalid filename (10)
    file://...Years%20Back%5CCome.mp3

I assume whether these error or not depend on the underlying filesystem, although `#` seems to mess with MTP only. It might be a good idea to replace [all potentially troublesome characters](https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words) (plus `#`, apparently).

**Comment by gnumdk** [comment]
Ok, escaping is not done for converted files.

**Comment by neckcen** [comment]
I believe [line 429](https://github.com/gnumdk/lollypop/blob/1036b921e94de7bab4a9130fa4fa7ba8f1bf33d0/src/sync_mtp.py#L429) needs escaping applied too.

**Comment by gnumdk** [comment]
@neckcen Thanks!

**Comment by neckcen** [comment]
As efficient as ever, thanks!
