### ISSUE TITLE
Hangs while trying to show edit menu in album context menu when tag editor is already open

### ISSUE THREAD

**Issue by dotreloaded** [gnumdk/lollypop#1004]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.9
• Linux distribution: Arch Linux

Steps to reproduce:
* Right click on an album cover to bring up its context menu and click "Modify information", this will spawn a tag editor
* Keep the tag editor open and right click on another album cover, lollypop now hangs

Eventually a timeout is reached and lollypop stops hanging:
`EditMenu::__init__(): g-io-error-quark: Timeout was reached (24)`

It gets stuck on this logic in `pop_menu.py`:
```
                proxy = Gio.DBusProxy.new_sync(
                                            bus, Gio.DBusProxyFlags.NONE, None,
                                            'org.gnome.Lollypop.Portal',
                                            '/org/gnome/LollypopPortal',
                                            'org.gnome.Lollypop.Portal', None)
```

On a related note, is there a way to specify which tag editor lollypop should open if you have multiple installed?

**Comment by gnumdk** [comment]
Yes, in dconf-editor

**Comment by gnumdk** [comment]
Ok, I know what is happenning... Lollypop needs a lot of rewrite to be full async.
