### ISSUE TITLE
Crashes when you love a radio song when loved songs playlist is open

### ISSUE THREAD

**Issue by dotreloaded** [gnumdk/lollypop#1007]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.9
• Linux distribution: Arch Linux

If you listen to a radio broadcast in lollypop, then navigate to the "loved tracks" playlist, and then press `l` to love the radio song, lollypop will crash. It always seems to reliably crash if you have the "loved tracks" playlist open, but it's not necessarily a requirement since when I was testing this it crashed on other views as well.

It doesn't make sense to love a radio song, so I think loving should be disabled if a radio is playing.

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/lollypop/view_playlists.py", line 212, in __on_playlist_add
    self.__playlists_widget.insert(track_id, pos)
  File "/usr/local/lib/python3.6/site-packages/lollypop/widgets_playlist.py", line 202, in insert
    self.__add_tracks([track_id], widget, pos)
  File "/usr/local/lib/python3.6/site-packages/lollypop/widgets_playlist.py", line 260, in __add_tracks
    track.album.id != previous_album_id)
  File "/usr/local/lib/python3.6/site-packages/lollypop/widgets_track.py", line 382, in __init__
    if self._track.album.artist_ids[0] != Type.COMPILATIONS:
IndexError: list index out of range
```

**Comment by dotreloaded** [comment]
It would very cool if, when you hear a radio song you like, lollypop could store the radio metadata for that song somewhere so you would have a note of it that you could use to explore and find that music later. This could be the replacement for the love functionality when a radio is being played.

**Comment by gnumdk** [comment]
Hard to debug as Lollypop can't play radios anymore here on ArchLinux :-/
