### ISSUE TITLE
Add a preference to hide notifications when song change

### ISSUE THREAD

**Issue by rafaelmardojai** [gnumdk/lollypop#1009]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.9
• Linux distribution: Fedora 25

Would be nice to have than feature ...

**Comment by gnumdk** [comment]
#686

**Comment by Vaesper** [comment]
Same issue here. Not a duplicate of #458 as the solution presented there also suppresses error notifications (which I'd still want to see).

**Comment by Vaesper** [comment]
Same issue here. Different from #458 as the solution presented there also suppresses error notifications (which I'd still want to see).

P.S. apparently calling something "not a duplicate of" makes github mark it as a duplicate, and I cannot undo this.

**Comment by gnumdk** [comment]
Will not add an option for that... Request a feature for GNOME Shell to add categories for notifications ("errors",  ...)

**Comment by rafaelmardojai** [comment]
Now I think these notifications became useless with built-in mpris controls. But that is another issue.

**Comment by gnumdk** [comment]
There are not for me... Lollypop only sends a notification:
- if user does not changed the track via MPRIS
- If Lollypop window is not focused
