### ISSUE TITLE
Crash when trying to open help

### ISSUE THREAD

**Issue by clofresh** [gnumdk/lollypop#101]
Hi, I'm running arch linux with awesomewm and no desktop environment. I'm getting a crash when I try to open the help menu. This is the log:

```
Apr 30 21:42:53 carlo-arch bash[2006]: Traceback (most recent call last):
Apr 30 21:42:53 carlo-arch bash[2006]: File "/usr/lib/python3.4/site-packages/lollypop/application.py", line 286, in _help
Apr 30 21:42:53 carlo-arch bash[2006]: Gtk.show_uri(None, "help:lollypop", Gtk.get_current_event_time())
Apr 30 21:42:53 carlo-arch bash[2006]: GLib.Error: g-io-error-quark: The specified location is not supported (15)
Apr 30 21:42:53 carlo-arch kernel: traps: python3[8122] general protection ip:7f307bbaf150 sp:7fff0b2d5978 error:0 in libpthread-2.21.so[7f307bb9d000+18000]
Apr 30 21:42:54 carlo-arch systemd-coredump[8139]: Process 8122 (python3) of user 1000 dumped core.
```

Not sure if it's trying to invoke a gnome-specific event or something like that

**Comment by prescott66** [comment]
For me too. Log from terminal:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/application.py", line 286, in _help
    Gtk.show_uri(None, "help:lollypop", Gtk.get_current_event_time())
GLib.Error: g-io-error-quark: Uvedené umiestnenie nie je podporované (15)

**Comment by gnumdk** [comment]
Gtk bug... Report this to GTK, gtk_show_uri() crash when yelp is not installed...
