### ISSUE TITLE
lyrics pop up is too slow to load and can't move slider while pop up is opened

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1010]
so...having a lyrics fetcher is great but unfortunately lyrics pop up really takes ages to show any results and even when clicking on a result is then quite slow to load...so often we end up having the song already started and lyrics not yet displayed...if you then try to move the slider the pop up disappear and you have to reload it...since i understand this maybe could not be made any faster it would be nice if we could at least move the slider while the pop up window is on...

**Comment by gnumdk** [comment]
Not possible

**Comment by gnumdk** [comment]
Just put lyrics in ID3 tags and it will not be slow.

**Comment by legacychimera247** [comment]
thanks for your suggestion...any way to do that?tried every tag editor but seems that no one has a lyric section in tags...only kid3 has text or synced lyrics but niether of them are working...

**Comment by gnumdk** [comment]
Seems broken, as code not changed, I think gstreamer is broken...
