### ISSUE TITLE
Library update error

### ISSUE THREAD

**Issue by ahloiscreamo** [gnumdk/lollypop#1012]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.2
• Linux distribution: Fedora 25

Hi there, i have some error when trying to update my library
terminal output-

```
lollypop
CollectionScanner::__scan() 'file:///mnt/1b5e6c70-f3fa-4e88-a91e-d5d00e69ad54/Music/Hiroyuki%20Sawano%20%5BnZk%5D%20-%20&Z%20%5B2015.02.04%5D%5B320kbps%5D/01%20&Z.mp3'
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
SpotifySearch::get_track 'album'
^C
 azrulFTW  ~  

```

**Comment by gnumdk** [comment]
Can you run the same test but offline? To be sure message comes from scanner.

**Comment by ahloiscreamo** [comment]
Ah yes,
It resulted the same so you are right that is coming from scanner
terminal output-
```

CollectionScanner::__scan() 'file:///mnt/1b5e6c70-f3fa-4e88-a91e-d5d00e69ad54/Music/Hiroyuki%20Sawano%20%5BnZk%5D%20-%20&Z%20%5B2015.02.04%5D%5B320kbps%5D/01%20&Z.mp3'
^C
 azrulFTW  ~ 
```

**Comment by gnumdk** [comment]
Yes but list index out of range is gone :)

**Comment by gnumdk** [comment]
Are you sure your gstreamer configuration is ok?

**Comment by ahloiscreamo** [comment]
I believe mine is good, so i just reset the database and they are working fine for now 👍 
Thank you sir for taking time to guide me, i will close this issue.

**Comment by FreddieChopin** [comment]
I may seem to have a similar issue, but I'm not sure... When I modify something in the configured folders and do "update music" nothing changes - for example the collection has files which were deleted (and they obviously cannot be played). To update anything I have to reset the entire database. What info should I provide to help in debugging this?

**Comment by gnumdk** [comment]
Test current master first as it may be fixed.

**Comment by gnumdk** [comment]
#986

**Comment by FreddieChopin** [comment]
It seems that indeed in current master the first issue seems to be gone.

But the second one seems to persist - if I reset the database, the process "ends" after some time (the progress bar reaches 100%), but in lollypop there are no artists/albums. The process however restarts automatically from the beginning (the progress bar is visible at the bottom of the main window). The behaviour may vary, I'm almost certain that during my first attempt lollypop just crashed and quit, but I did not manage to reproduce that particular behaviour.
