### ISSUE TITLE
Lollypop hangs and crashes after every action. Then fails to open out right.

### ISSUE THREAD

**Issue by MartianH** [gnumdk/lollypop#1013]
• Lollypop version: 0.9.230-1
• Gtk Version: 3.22.10
• Linux distribution: Arch Linux (kernel 4.10.3-1)
* window manager: BSPWM

Lollypop has been hanging and crashing on me as of late. At boot it opens up fine but when I click on an album it hangs and subsequently crashes. I tried debugging it with the resulting output:

```
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_arra
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash
  g_type = info.get_g_type()
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Lastfm::__on_password_lookup(): g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)

(lollypop:3794): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x2be02b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Downloader::_get_album_art_lastfm: Album not found [/Soundcloud Joints]
Downloader::_get_album_art_spotify: 'artists' [/Soundcloud Joints]
 # going through folders and all that nothign wrong here
file:///home/martialh/Music/The%20Cancel/Night%20Light not detected as a music file
file:///home/martialh/Music/Flamingosis/Pleasure%20Palette not detected as a music file
file:///home/martialh/Music/Flashworx/Futurisma not detected as a music file
...
```

Like I said before it opens up like normal but it hangs when I try to pick anything. After the whole thing is fone and I try to start it up again with *lollypop -d* after it crashes I only get this:

```
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_arra
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash
  g_type = info.get_g_type()
```

Lollypop seems to work after I wait for it but it is still a huge inconvenience.

Edit: Still hangs after picking a few songs. same symptoms. And other times it seems to just work fine.

**Comment by gnumdk** [comment]
No crash output here...

**Comment by MartianH** [comment]
I cannot seem to recreate it either. Must have been system related. Guess this can be closed now.

**Comment by bretter** [comment]
I am having a very similar problem. Hangs after clicking anything within the window. Never seems to recover.

`/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

(lollypop:27410): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x22a02c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Lastfm::__connect(): Authentication Failed - You do not have permissions to access the service
`
This is the output when I execute the program there is no new output between initialization and clicking something to cause the hang. This happens every time Lollypop is run.

I am also on Arch running a fully updated system.

Please let me know if there is any other debugging information I can supply that would be of use.

**Comment by MartianH** [comment]
> Update: Lollypop does eventually recover and becomes responsive again. It takes about 15 minutes and after that initial hang passes, Lollypop responds normally.

Had the same problem. It took 5-10 minutes before it recovered. Other times It went blank when I tried to close the window. Yet now it seems to be working fine. Are there some logs we missed?

**Comment by gnumdk** [comment]
For me it looks like a broken GNOME stack... Here ArchLinux and all is ok...

Run this, you should see what hangs...

$ dbus-monitor

**Comment by simonbcn** [comment]
I had same problem. Solution: delete `~/.cache/lollypop` and `~/.local/share/lollypop`, starts Lollypop again.

**Comment by MartianH** [comment]
Just deleted the folders. Lollypop had to re-fetch all the artists but everything seems to work fine. Not sure if it won't happen again, though. Will keep you posted. 

Also: dbus-monitor logs didn't indicate anything wrong. Furthermore, I never noticed it before but lollypop is much faster than gnome-music when it comes to populating all the artist. Props.

**Comment by gnumdk** [comment]
@bretter Please do not delete folder, do an archive and send it by email.

**Comment by nylki** [comment]
@gnumdk Got the same issue. Haven't yet deleted the cache or the `.local/share/lollypop` dir; do you still require debug info? I could send you the files if you tell me which ones you need.

**Comment by gnumdk** [comment]
Just send me ~/.cache/lollypop and ~/.local/share/lollypop zipped

**Comment by nylki** [comment]
@gnumdk done.

**Comment by nylki** [comment]
@gnumdk I sent you an GPG-encrypted mail at cedric.bellegarde@adishatz.org with the zips as links to my private webspace for you to download (because the files are too large for mail attachments).
I didn't get any errors send-errors. But I just send you the mail again.
