### ISSUE TITLE
'Append' doesn't work well when it isn't playing music.

### ISSUE THREAD

**Issue by simonbcn** [gnumdk/lollypop#1017]
```
Arch Linux 
GNOME Shell 3.22.3
gtk 3.22.10-1
lollypop-git 0.9.230.r9.g18ed4e90-1 (installed form AUR)
```

I open Lollypop and I press `+` button in several albums. It adds these albums to `Playing albums` list but `Play` is disabled. How can I play these albums?

**Comment by gnumdk** [comment]
- First solution: click on play for first album
- Second solution: Go to playlist popover and start playing what you want

**Comment by simonbcn** [comment]
What is `playlist popover`? https://webmshare.com/jQr61

Would not it be easier to start the playback when adding the first album?

**Comment by gnumdk** [comment]
You were in the popover, just open album and click a track.

Not it will not be easier because me (and others as previously reported) prefer to start creating a playlist without lollypop starting to play a track forced.
