### ISSUE TITLE
 Improper Grouping of Albums

### ISSUE THREAD

**Issue by Herodotean** [gnumdk/lollypop#1018]
• Lollypop version: 0.9.230
• Gtk Version: gtk2-2.24.31-2.fc25
• Linux distribution: Fedora 25 XFCE

Two different albums with the same name and which came out in the same year are improperly grouped as a "compilation" album, even though they're not the same. They do have different artist and albumartist tags.

**Comment by gnumdk** [comment]
Send me album by email

**Comment by Herodotean** [comment]
You want the music files? All of them, one from each?


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by gnumdk** [comment]
Just one broken album.

**Comment by Herodotean** [comment]
Using <albumartist> tag did not seem to work.

**Comment by gnumdk** [comment]
Ok, no issue here with your files... Use kid3-qt to edit tags, your files contain multiple tag frame (id3v1, id3v2 and APE)
