### ISSUE TITLE
DnD in next-to-play list

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1019]
I'm running 0.9.230 and in the next-to-play list, I cannot move songs or albums around. I sometimes see a drag mouse icon (the grabbing hand) or a note symbol, but I cannot alter the order.

**Comment by gnumdk** [comment]
What is next to play?

**Comment by fbruetting** [comment]
The queue list, I can add songs to by clicking the `+`-symbol.

**Comment by gnumdk** [comment]
Something is broken in your GNOME/GTK installation, works here on ArchLinux and Ubuntu.

Maybe related to wayland...
