### ISSUE TITLE
Yelp dependency

### ISSUE THREAD

**Issue by prescott66** [gnumdk/lollypop#102]
I think is needed to add Yelp as a dependency package to be installed with lollypop. to work lollypop without problems.

**Comment by gnumdk** [comment]
Why?

**Comment by prescott66** [comment]
Because without yelp is not working Help. or not?

**Comment by gnumdk** [comment]
Yes, but wm users may not want yelp on their system...
Gnome packages do not depend on yelp.

**Comment by prescott66** [comment]
ok.you know better :)

**Comment by ianbrunelli** [comment]
Why is `yelp-tools` a dependency?

I don't have `yelp` installed, and the `autogen.sh` was showing me this error, solved my installing the `yelp-tools` package (on Arch Linux):

```
Checking for required M4 macros...
  yelp.m4 not found
***Error***: some autoconf macros required to build lollypop
  were not found in your aclocal path, or some forbidden
  macros were found.  Perhaps you need to adjust your
  ACLOCAL_PATH?
```

**Comment by gnumdk** [comment]
Because it's needed autogen/automake
