### ISSUE TITLE
Halting after every single song if "do net repeat" is active

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1020]
I'm running 0.9.230 and when I select "do not repeat", I have to start every single song of my queue list, instead of having it running from start to the end. But when I select "continuous playback", the cue list is played from start to end (and repeats).

**Comment by gnumdk** [comment]
What is cue list? Is that have something to do with #257 ?

**Comment by gnumdk** [comment]
If yes, close this and comment #257

**Comment by fbruetting** [comment]
Sorry, I meant the next-to-play queue list (where I can add songs via the `+`-symbol). E.g. if I click on the `+`-sign of two songs, the second isn't played until I press "play" a second time. I expect that the second song gets played right after the first.

**Comment by gnumdk** [comment]
Do not happen here... :-(

**Comment by fbruetting** [comment]
Thanks! :)
