### ISSUE TITLE
Lollypop 0.9.229 doesn't launch on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1021]
Lollypop version: 0.9.229 (version 0.9.227 previously worked fine)
GTK version: 3.22.11

After installing lollypop + dependencies from the distro's repo, this is what happens when I try to launch it:

$ lollypop

(lollypop:24860): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lollypop:24860): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lollypop:24860): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
/usr/lib/python3.6/site-packages/lollypop/lio.py:13: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, Soup

(lollypop:24860): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(lollypop:24860): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(lollypop:24860): Gtk-WARNING **: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(lollypop:24860): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(lollypop:24860): Gtk-WARNING **: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lollypop/player_bin.py", line 512, in __on_bus_message_tag
    self._current_track.mtime != 0) and\
  File "/usr/lib/python3.6/site-packages/lollypop/objects.py", line 44, in __getattr__
    attr_value = getattr(self.db, "get_" + attr)(self.id)
  File "/usr/lib/python3.6/site-packages/lollypop/database_tracks.py", line 673, in get_mtime
    rowid=?", (track_id,))
sqlite3.OperationalError: no such column: mtime

**Comment by Pointedstick** [comment]
0.9.230 installed from home:gnumdk31 works. This is either a distro packaging error or a bug resolved in a later version. I;ve filed a new but with openSUSE: https://bugzilla.opensuse.org/show_bug.cgi?id=1031012

**Comment by gnumdk** [comment]
You can't run 0.9.230 and then go back to previous versions... That's not a bug!

**Comment by Pointedstick** [comment]
I didn't install 0.9.230 and then go back. I installed 0.9.229, and after seeing that it didn't work, I upgraded to 0.9.230.

**Comment by gnumdk** [comment]
Impossible, mtime upgrade is done by 0.9.230...
