### ISSUE TITLE
No lyrics search for songs from Internet radios

### ISSUE THREAD

**Issue by k-kirill** [gnumdk/lollypop#1026]
• Lollypop version: 0.9.229
• Gtk Version: gtk-3.22.11
• Linux distribution: openSUSE Tumbleweed 20170322

While listening to Internet radios it is impossible to search lyrics for the currently playing song, because the interface at the top of the player searches for other radios and stuff like that instead of lyrics like for playing local music.

I used to use Clementine and it supports this feature and I really miss it in Lollypop.

**Comment by gnumdk** [comment]
As internet radios tags are shit, don't see how it can work in clementine.

**Comment by k-kirill** [comment]
Thanks for implementing the feature. I checked it in Lollypop 0.9.231 and spotted a small issue: if you play a radio then there are only Lyrics and Search buttons always shown even if you have switched to a regular song (from a file) afterward. However, If you play a regular song first and switch to a radio then all the buttons are shown in both the cases.

**Comment by gnumdk** [comment]
What is strange is

**Comment by k-kirill** [comment]
Can you please clarify if the last commit means that the small issue about the list of buttons still exists in 0.9.233? https://github.com/gnumdk/lollypop/commit/3df88560aa6e962fa833ad62a2b4d35a8a5278da

**Comment by gnumdk** [comment]
No, it should not

**Comment by k-kirill** [comment]
Unfortunately that small issue is still reproducible in 0.9.233

**Comment by k-kirill** [comment]
I've checked it it 0.9.244 + https://github.com/gnumdk/lollypop/commit/ffa9bf95d8f7f515b23fc9551a5283ff40d2939a and found an even smaller issue:
the Wikipedia button is not shown for radios originally, but once you play a regular file and switch back to a radio, the button is shown. It's just for the record, because it's just a glitch. Thanks for the fix.

**Comment by k-kirill** [comment]
I checked the buttons in 0.9.237 and while the list of buttons is consistent in radio and regular song modes, the Wikipedia button is available only for radios. I suppose it should be available in both the modes.
