### ISSUE TITLE
Unlock device : can't play audio CD

### ISSUE THREAD

**Issue by Doctor-Who** [gnumdk/lollypop#1027]
Hi on my computer :

Lollypop : 0.9.206
GTK Version : 3.16
openSUSE Leap 42.1

When insert Audio CD and wanted to play it, software indicate to unlock device ? 
How can I unlock that device ? It work on other app like brasero and soundjuicer

Thx

PS : except that, it's a wonderfull program

**Comment by gnumdk** [comment]
Lollypop should not show CD, it's not supported and not planned...
Will fix it...
