### ISSUE TITLE
lollypop remote control

### ISSUE THREAD

**Issue by vivasteve** [gnumdk/lollypop#1028]
• Lollypop version: 0.9.230
• Gtk Version: 
• Linux distribution: Mint 18

Not a bug ... can't find anywhere to ask questions ...
Is there some way to control/monitor lollypop from a remote computer?
mpris or mpd for example?
Thanks

**Comment by gnumdk** [comment]
Duplicated

**Comment by vivasteve** [comment]
sorry, missed that!
