### ISSUE TITLE
Import/read playlists from Rhythmbox

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1029]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.11
• Linux distribution: openSUSE Tumbleweed

I'm guessing a lot of Lollypop users will be migrating from Rhythmbox, GNOME's _de facto_ default music player. It would be nice if Lollypop could read and/or import Rhythmbox playlists.

**Comment by gnumdk** [comment]
#144

**Comment by Pointedstick** [comment]
👍
