### ISSUE TITLE
A lot of albums gone with the last commits

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#103]
I see just small part from my albums.

Some output:
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/09 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05e6\u05d4\u05f4\u05dc \u05e6\u05d5\u05e2\u05d3.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/11 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05ea\u05db\u05dc\u05ea \u05dc\u05d1\u05df.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/10 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05e8\u05d1 \u05e1\u05de\u05dc \u05e9\u05d5\u05dc\u05d4.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/06 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05de\u05d0\u05e8\u05e9 \u05d7\u05d1\u05e8\u05d9\u05dd \u05dc\u05e0\u05e9\u05e7.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/12 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05d4\u05d3\u05d5\u05e8 \u05d4\u05e6\u05e2\u05d9\u05e8.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/01 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05d4\u05e6\u05d3\u05e2\u05d4 \u05dc\u05e9\u05dc\u05d5\u05dd.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/03 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05d6\u05de\u05e8 \u05d4\u05e4\u05dc\u05d5\u05d2\u05d5\u05ea.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/07 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05de\u05e8\u05d2\u05dc\u05d9\u05ea.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/04 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05db\u05ea\u05d4 \u05d0\u05dc\u05de\u05d5\u05e0\u05d9\u05ea.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/02 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05d6\u05d0\u05ea \u05d0\u05e8\u05e6\u05d9.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/05 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05de\u05d0\u05e8\u05e9 \u05e4\u05e8\u05d9\u05d3\u05d4.ogg'
CollectionScanner::_scan(): name '_' is not defined
'/home/yoseforb/\u05de\u05d5\u05e1\u05d9\u05e7\u05d4/\u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc \u2013 \u05de\u05de\u05dc\u05db\u05ea \u05d4\u05de\u05d0\u05e8\u05e9/08 - \u05ea\u05d6\u05de\u05d5\u05e8\u05ea \u05e6\u05d4\u05f4\u05dc - \u05e0\u05d1\u05e0\u05d4 \u05d0\u05e8\u05e6\u05e0\u05d5.ogg

Look like you did something wrong in the last commits.

Notes: I have a lot of music in Hebrew, but the most of them are shown even after the last commits, just about half is missing.

**Comment by gnumdk** [comment]
Can you test with last commit?
Or send me by mail a missing file ;)

**Comment by yoseforb** [comment]
Hmm, I think now to works correctly.

Just two examples for songs thes was igonre:
https://www.youtube.com/watch?v=DYfMuZVxnZY (I have this as ogg)
or all Meir Ariel's albums (https://www.youtube.com/watch?v=NkrhMwi2vRY or https://www.youtube.com/watch?v=c0z_KtUtIIQ).

I think the db was replaced in the meantime.

**Comment by gnumdk** [comment]
If there songs have empty genre/album/artist, it was the bug ;)

**Comment by yoseforb** [comment]
Look like there is a problem with the compilations, part of them are almos enpty.

**Comment by gnumdk** [comment]
Hmm, not here... Your db may be in a bad state...
Can you reset your db like this in dconf?
Reset db-version key.

**Comment by yoseforb** [comment]
I think all of them have album and aritst, and the most of them have genre too.

For genere, btw, I seperate different geners (for the same song) by ',' and lollypop think the ',' is part of the genere. (like "Rock, Pop" instead should be two differents geners).

**Comment by yoseforb** [comment]
OK, now it works as expected after reset gb-version key, thanks.

**Comment by gnumdk** [comment]
No, multiple genres/artist are broken

My fault removing code i didn't commented well...
