### ISSUE TITLE
Supporting formats other than MP3

### ISSUE THREAD

**Issue by bemeurer** [gnumdk/lollypop#1030]
Would it be possible to add other formats apart from MP3 for device syncing? I have my music in FLAC, but I need to convert it when transferring to my devices. MP3 is proprietary, and as such many people, me included, refuse to use it. An option for converting to something such as OGG would be dearly appreciated.

Is this on the works or of interest? I just think that limiting usability to MP3, specially on a project that is GPLv3 licensed, is not very nice.

**Comment by gnumdk** [comment]
option is here because most devices support only mp3

**Comment by bemeurer** [comment]
@gnumdk I get that, but would adding support for OGG be possible?

**Comment by gnumdk** [comment]
And MP3 licensing finish in 2017 so just wait :p

**Comment by palob** [comment]
@bemeurer By the way, MP3 isn't "proprietary", there are free implementations. The thing is, it is patent-encumbered.

**Comment by bemeurer** [comment]
@palob The MP3 standard belongs to Fraunhofer, which still holds the patents in the US. Even though, sure, it has a standard held by the ISO it's patents still hold in the US.

The device is a [Fiio X3 II](http://www.fiio.net/en/products/39), it can play pretty much anything you throw at it *except* Opus. I'd like to use OGG because I've used it before and it's developed by the same folks that work on FLAC.

**Comment by baimafeima** [comment]
> And MP3 licensing finish in 2017 so just wait :package: 

MP3 simply doesn't make sense anymore. It is an inferior standard of the past. I would very much like to see Opus support: https://opus-codec.org/comparison/

**Comment by bemeurer** [comment]
I think if we used an ffmpeg backend thus could all be made easy, just a couple command line arguments of difference between formats. Support could be extended to most formats available.

**Comment by gnumdk** [comment]
@baimafeima Lollypop is not an encoder, MP3 is the most supported format. Convertion is here only for this reason. If you love opus, encode your music with opus ;)

**Comment by gnumdk** [comment]
https://www.iis.fraunhofer.de/en/ff/amm/prod/audiocodec/audiocodecs/mp3.html

MP3 is now free, closing this bug report.
