### ISSUE TITLE
No GUI/Window opeiong with warning "Gtk-WARNING **: Failed to register client..."

### ISSUE THREAD

**Issue by AuzzieAsh** [gnumdk/lollypop#1031]
• Lollypop version: unknown
• Gtk Version: 3.18.9-1ubun/2.24.30-1ubu
• Linux distribution: Xubuntu 16.04

When launching Lollypop, it opens but doesn't create a window.
I get the following warning message in the terminal when attempting to launch Lollypop:
Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

I can still play music files by opening them with Lollypop from my file browser, still no window though.

**Comment by gnumdk** [comment]
No idea but your desktop looks broken but I may be wrong.

**Comment by keighrim** [comment]
I'm having a very similar issue since a week ago or two (no gui, blocking other applications that are below where the lollypop window is supposed to be placed) . But I'm getting a different message. 
```
Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
```
I'd been using this great music player for over a year, and everything was fine. I don't know which update or software installation caused. 
I'm on ubuntu gnome 16.10, having gtk 3.20.9 and 2.24.30. Lollypop is up to date through `gnumdk` ppa.

**Comment by lmfalconer** [comment]
I am getting the same as @keighrim

**Comment by gnumdk** [comment]
@lmfalconer Ubuntu?

**Comment by gnumdk** [comment]
Can someone do this: list lollypop packages files and look for application.py file.

Edit file as root and replace __listen_to_gnome_sm() code with:
def __listen_to_gnome_sm(self):
        """
            Connect to GNOME session manager
        """__listen_to_gnome_sm
        pass

**Comment by gnumdk** [comment]
Can you test current master, it may be fixed.

**Comment by AuzzieAsh** [comment]
@gnumdk I have a window/gui again and everything seems to be working fine.

I am still getting the same gtk warning though.
`Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files`
Though that could be an issue on my side.

**Comment by gnumdk** [comment]
Will release today ;)
