### ISSUE TITLE
Always show the  "Edit | Modify Information"  album menu item, and include easytag as a dependency or use packagekit to install it as needed

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1032]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.11-1.1
• Linux distribution: openSUSE Tumbleweed

I wasn't aware of lollypop's EasyTag integration until I searched for tag editing bugs here on github. This makes it a hidden feature that most users will never find.

I recommend that easytag be made a hard dependency to make sure it gets installed, or else always show the "Edit | Modify Information" menu item, but if easytag isn't installed, use packagekit to install it on-demand.

**Comment by gnumdk** [comment]
It should be down by packages as recommends.

**Comment by Pointedstick** [comment]
Ok, gotcha!

**Comment by Pointedstick** [comment]
RPM can handle Recommends:. I've filed https://bugzilla.opensuse.org/attachment.cgi?bugid=1033858&action=enter and submitted a patch.

**Comment by Pointedstick** [comment]
Fixed.
