### ISSUE TITLE
Lollypop is not using GNOME color theme global setting

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#1035]
### Specs
• Lollypop version: 0.9.230
• GTK version: GNOME 3.22/GTK+3.22
• Linux distribution: Fedora 25

### Enhancement proposal
Lollypop is not using GNOME color theme global setting.
My GNOME global theme setting is set to black and not grey.
Could Lollypop use the global setting?
I have to turn it black manually.

**Comment by gnumdk** [comment]
Screenshot?

**Comment by M5oul** [comment]
![black_theme](https://cloud.githubusercontent.com/assets/4758871/24993755/0aa4a304-2028-11e7-9da7-5e8f608f93f0.png)
