### ISSUE TITLE
Albums with files that have multiple file types show up as multiple-disc albums

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1036]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.11-1.1
• Linux distribution: openSUSE Tumbleweed

I have a few albums where half the songs are mp3 files, and the rest are .m4a. Lollypop displays these albums as if they are multi-disc albums, with all of the songs of each file format comprising a single disc. The files are all tagged properly, including track numbers (1/x) and CD number (1/1). Here's a screenshot showing the albums in lollypop and easytag:

![albums](https://cloud.githubusercontent.com/assets/1097249/25020257/d691b8ae-204a-11e7-89b3-69837a42214c.jpg)

**Comment by gnumdk** [comment]
Tag issue, use kid3-qt to edit tags.

**Comment by Pointedstick** [comment]
The tags look correct to me. What tag is wrong?

**Comment by gnumdk** [comment]
Send me files by email. (dropbox or else)

**Comment by Pointedstick** [comment]
Hmm, using MusicBrainz Pizard to auto-re--tag everything fixed the issue. So I guess it was a tag problem after all. Sorry for the bogus report!
