### ISSUE TITLE
No right-click menu for albums in Genre > Artist view

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1037]
• Lollypop version: 0.9.231
• Gtk Version: 3.22.11-1.1
• Linux distribution: openSUSE Tumbleweed

Steps to reproduce:
1. Select a genre
2. Select an artist
3. Right-click on an album in the album cover browser

Actual results:
No right-click menu appears, which is where the "Add to playlist" menu item is

However, you *can* right-click on an album in the album cover browser before you select an artist. This is problematic because 1) there may be a very large number of albums in view without an artist selected and 2) The ordering of the artists in the album cover browser is non-obvious, making it really hard to find the album you're looking for.

**Comment by gnumdk** [comment]
The add to playlist is in the button menu.

**Comment by Pointedstick** [comment]
What is the button menu? In the following screenshot, what should I click?

![screenshot_20170414_073636](https://cloud.githubusercontent.com/assets/1097249/25044676/25d564d4-20e5-11e7-86b7-dfee9b7a66da.png)

**Comment by gnumdk** [comment]
On the arrow next album title

**Comment by Pointedstick** [comment]
Oh. That works, But I didn't know that was clickable! It certainly doesn't look like a button, and its icon is medium gray on light gray. I thought it was just a static decoration. Let's keep this issue closed and track that issue in https://github.com/gnumdk/lollypop/issues/1038
