### ISSUE TITLE
Album button menu doesn't look like a clickable button

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1038]
• Lollypop version: 0.9.231
• Gtk Version: 3.22.11-1.1
• Linux distribution: openSUSE Tumbleweed

Follow-on from https://github.com/gnumdk/lollypop/issues/1037#issuecomment-294155004

Today I learned that the tiny right-pointing medium gray arrow next to the album name is actually a button! I didn't realize this because it doesn't look like a button: It doesn't have a button-like border or an icon with a symbol that's either recognizable or that might be encountered in other programs. If it looked more like a clickable button, the feature hiding behind it would be much more discoverable.

**Comment by gnumdk** [comment]
Wont fix, it's wanted.

**Comment by Pointedstick** [comment]
I want the button, too. I just want it to look like a button!

**Comment by gnumdk** [comment]
And I don't, there is many non-button in GNOME applications that are clickable.

**Comment by Pointedstick** [comment]
...Which is a clear user interface problem, especially for a Desktop Environment that's trying to target less-technical users.

**Comment by gnumdk** [comment]
You may need to report bug towards github too who provides many button without relief... And MacOSX too... And Windows too...

**Comment by rubenwardy** [comment]
If you're referring to the overflow list on the album view, what is the point of it? There's plenty of space for two buttons there, no need for an overflow list
