### ISSUE TITLE
No icon in Panel

### ISSUE THREAD

**Issue by leighss** [gnumdk/lollypop#1039]
• Lollypop version: 0.9.231
• Gtk Version: 3.18.9
• Linux distribution: Xubuntu 16.04.2

I have no Lollypop icon in the panel (its a generic rectangle)

I am using:
Style: Numix
icons: elementary Xfce darker
but changing either of these makes no difference

The same problem if I install via ppa or build from git (thanks gnumdk for basic instruction :) )

I do have the Lollypop icon in the menu

**Comment by gnumdk** [comment]
Bug un xfce or Ubuntu...

**Comment by Lukaboot** [comment]
linux bug , also my xcfe is working fine with lollypop

**Comment by leighss** [comment]
Yes, must be that I also have now realised that other apps have no icon on panel
Thanks
