### ISSUE TITLE
Support for keyboard play/pause forward and back buttons

### ISSUE THREAD

**Issue by yolo7398** [gnumdk/lollypop#1045]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.231
• Gtk Version: 3.22.11-0
• Linux distribution: Xubuntu 17.04

The keyboard play/pause forward and back buttons do not work in lollypop.

**Comment by gnumdk** [comment]
Any other Xubuntu user? XFCE user? BTW, as it can't be a lollypop issue. Closing. Try to get help on forums.

**Comment by yolo7398** [comment]
It is a lollypop issue. Works in other music players that I have used, specifically, rythmbox, amarok and clementine.

**Comment by gnumdk** [comment]
Lollypop just set shortcuts using GTK. As it works here on Ubuntu, ArchLinux and Fedora, it's not a Lollypop issue.

**Comment by gnumdk** [comment]
It's a bug in XFCE: https://bugzilla.xfce.org/show_bug.cgi?id=8588

**Comment by gnumdk** [comment]
BTW, you should be able to bind shortcuts in XFCE to lollypop commands/lollypop dbus calls.

**Comment by rubenwardy** [comment]
For future readers

* Settings -> Keyboard -> Application Shortcuts
* Add bindings:
    * `lollypop -t` on your pause play key
    * `lollypop -n` for next
    * `lollypop -p` for prev

Unfortunately, this will be mean the keys you assign will only work with Lollypop. Hopefully this will be fixed soon, by either party.

**Comment by yolo7398** [comment]
Thanks. I got it to work. Its not an issue for me because lollypop is the only music player I use.

**Comment by clerafel** [comment]
I also have this error in MATE desktop (Linux Mint 18.1)
