### ISSUE TITLE
Feature Request: Solution for songs without album ID3Tag 

### ISSUE THREAD

**Issue by lakano** [gnumdk/lollypop#105]
Hi !

Thanks for your project, it's really cool ! 

On the left side, I only see the list of the albums, but as the most part of my collection doesn't have an the album filled in ID3Tags, there is a lot of missing songs.

So, may be you could propose an option in Preferences to show the left list by Artist or by Album ?

Or, may be an option to permit to see on the left the Artist name if a song haven't set an Album name ?

thanks a lots & cocoriko ;-)

**Comment by gnumdk** [comment]
Songs with no album should have an "Unknown" album filled... Strange... Please send me your ~/.local/share/lollypop/lollypop.db by email.

**Comment by lakano** [comment]
Thanks for the quick answer, but I don't found your email, sorry ! 

About the "Unknown" album, I don't see it on the left side, but it's not the best way for me to choose the artists. Currently I see on the left side may be 30% of my collection.

Or may be the problem is a bug in the scan... I don't known ! :-/

Regards,

**Comment by gnumdk** [comment]
My email is in the about dialog.

**Comment by gnumdk** [comment]
Can you test?

**Comment by lakano** [comment]
I have cloned git repository, but I can't compile ( I have previously installed Lollipop from your PPA ) : 
```
checking for xmllint... xmllint
./configure: line 13104: syntax error near unexpected token `1.35.9'
./configure: line 13104: `GOBJECT_INTROSPECTION_REQUIRE(1.35.9)'
```
May be I need some -dev packages to compile ?

Thanks

**Comment by gnumdk** [comment]
install gobject-introspection package

**Comment by lakano** [comment]
I already have python gobject-introspection packages installed 
```
ii  python-gi                                   3.14.0-1                                             amd64        Python 2.x bindings for gobject-introspection libraries
ii  python3-gi                                  3.14.0-1                                             amd64        Python 3 bindings for gobject-introspection libraries
```

But under Ubuntu Vivid ( Gnome version ) I have a dependency problem with the package gobject-introspection : 
```
# LANG=C apt-get install gobject-introspection
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gobject-introspection : Depends: libgirepository-1.0-1 (= 1.42.0-2.2) but 1.44.0-0ubuntu1~vivid0 is to be installed
E: Unable to correct problems, you have held broken packages.
```

My libgirepository version : 
```
ii  libgirepository-1.0-1:amd64                 1.44.0-0ubuntu1~vivid0                               amd64        Library for handling GObject introspection data (runtime library)
```

I don't known how to sort this :-/ 
May be you could update your PPA to permit me to try your new patch ?

**Comment by gnumdk** [comment]
apt-cache policy gobject-introspection

**Comment by gnumdk** [comment]
1.44.0-0ubuntu1~vivid0 is gnome staging ppa, make sure you still have this ppa available

**Comment by lakano** [comment]
Well done !
My Gnome3 staging ppa was disabled since the last dist-upgrade.

Now, the package have been correctly installed and the compilation is ok, and the patch works fine, thanks a lots :)
