### ISSUE TITLE
Crash pour les albums à deux disques

### ISSUE THREAD

**Issue by Matthieu34** [gnumdk/lollypop#1052]
BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.231 compilé le 30 avril
• Linux distribution: Debian Jessie

Bonjour,
Depuis hier lorsque je clique sur un artiste pour voir ses albums lollypop crash si j'ai un album à deux cd.
Je leur donne toujours le même nom et je tague Cd 01/02 et 02/02.
Jusqu'à présent, ça fonctionnait très bien.

Le debug : 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album_detailed.py", line 532, in __on_size_allocate
    disc_names = self._album.disc_names(disc.number)
  File "/usr/local/lib/python3.4/site-packages/lollypop/objects.py", line 246, in disc_names
    return self.db.get_disc_names(self.id, disc)
  File "/usr/local/lib/python3.4/site-packages/lollypop/database_albums.py", line 676, in get_disc_names
    result = sql.execute(request, filters)
sqlite3.OperationalError: near "!=": syntax error

Merci et bon courage

**Comment by gnumdk** [comment]
Envoie moi ton lollypop.db par mail

**Comment by Matthieu34** [comment]
Envoyé, merci !

**Comment by gnumdk** [comment]
Ok, j'avais pas compris que tu avais la version de dev, ça le faisait chez moi aussi en fait :-)

J'ai fait un gros sed sur l'ensemble du code source la semaine dernière, j'espère qu'il n'y aura pas trop d'autres régressions. Je te laisse tester :)

**Comment by Matthieu34** [comment]
Ca fonctionne de nouveau, merci et bon courage. Je n'ai pas d'autres régressions pour l'instant
