### ISSUE TITLE
Disabled Network Access blocks playing radio

### ISSUE THREAD

**Issue by saivert** [gnumdk/lollypop#1053]
• Lollypop version: 0.9.231
• Gtk Version: 3.24
• Linux distribution: Arch

Currently if you disable Network Access in the application menu, trying to play radio just makes the scanning indicator at the bottom keep animating.

Would be helpful to warn users that they have Network Access currently turned off and radio playback will not work or remove the Radio section when Network Access is disabled.

This is confusing for users who assume playing radio will always work as it is user initiated anyways. IMO I wouldn't block radio playback in this case. Network Access should only apply to background tasks.

**Comment by gnumdk** [comment]
Network access should let you play radios.

**Comment by saivert** [comment]
Not according to source:
https://github.com/gnumdk/lollypop/blob/master/src/player_radio.py#L44

**Comment by Pointedstick** [comment]
> Network Access should only apply to background tasks.

+1

**Comment by gnumdk** [comment]
@saivert @Pointedstick Will be fixed.
