### ISSUE TITLE
Graphical glitches

### ISSUE THREAD

**Issue by Lukypie** [gnumdk/lollypop#1054]
BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.231 (built from git, also happens with the repo version)
• Gtk Version: GTK3, 3.22.10-1; GTK2, 2.24.31-1
• Linux distribution: Manjaro Linux

I've got two pc's that are running Manjaro Linux KDE, 
The first one is a laptop which runs an Intel integrated card, the second one has an NVIDIA GTX 1060 with the nvidia drivers, the same problem happens
Basically, there are graphical glitches (I don't know if that is the known issue listed above, if that is, sorry I will delete the issue) as you can see in the video and in this picture
I'm using X.org, kwin_x11 this happens also with compositing disabled
[2017-05-08 22-00-40.zip](https://github.com/gnumdk/lollypop/files/984715/2017-05-08.22-00-40.zip)
![screenshot_20170508_220933](https://cloud.githubusercontent.com/assets/7904559/25823069/2e629dd8-343b-11e7-9d6d-d6886fb3266b.png)

**Comment by gnumdk** [comment]
It's a GTK Bug... Check with another theme.

**Comment by gnumdk** [comment]
Can confirm, happen for me with breeze-gtk. Report to upstream KDE project.
