### ISSUE TITLE
Kept loaded lyrics pop-over

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#1056]
### Enhancement proposal
When reading lyrics and playing my songs, and If I close the pop-over I have to reload lyrics.
Can lyrics pop-over can stay loaded when clicking somewhere else?

---

- An other point, lyrics web page is reloaded when playing next song.

**Comment by gnumdk** [comment]
Reloading is because you activated auto re-loading (reload button)

**Comment by M5oul** [comment]
Thanks for the fix!
[I want to make a donation of Ğ1](https://framasphere.org/posts/3236882)
