### ISSUE TITLE
Go To Current Track action in Playing Albums dropdown.

### ISSUE THREAD

**Issue by DJTB** [gnumdk/lollypop#1058]
Ubuntu: 16.04
Lollypop: 0.9.231-1ppa1ubuntu1.2
GTK: 3.18.9-1ubuntu3.3

It's quite possible I don't understand what this button is meant to do, but when clicking Go To Current Track in the Playing Albums dropdown, nothing happens. 

For example, the main browsing panel is showing 'Album A' (while browsing through artists), a track from 'Album B' is currently playing, the Playing Albums dropdown shows 'Album B', 'Album C, 'Album D' (which were previously added with the + button).

Clicking on Go To Current Track, I assumed that the main browsing panel would redirect to show 'Album B'. 

Is this a bug? Or could you briefly explain what is meant to happen.

**Comment by DJTB** [comment]
I just realised that clicking on 'Album B' in the dropdown will expand the tracklist inside the dropdown. I'm now thinking that's the intended behaviour for the Go To Current Track button. I can confirm it's not performing that behaviour on my system either. Nothing whatsoever happens when I click it.

**Comment by DJTB** [comment]
Ok, I finally added 20 or so albums to the Playing Albums list, and discovered that if you scroll past the currently playing track's **album** then the button scrolls the list to that album when clicked.

**Comment by gnumdk** [comment]
Maybe "Scroll to current track"? But don't know how to translate this in my language :-1:

**Comment by DJTB** [comment]
I'm still getting used to the interface, so we can consider this as a problem between user and keyboard :)
