### ISSUE TITLE
Privacy respecting cover fetching

### ISSUE THREAD

**Issue by mray** [gnumdk/lollypop#1059]
• Lollypop version: 0.9.233
• Linux distribution: Ubuntu 17.04

---

### Thanks!!!
Thank you very much for putting up this nice music player. I'm using it only for half an hour and am surprised about how well it incorporates GNOMEs "music" with more advanced features. Awesome!!!

---

I noticed the Google API key thing that seems to enable "better" cover fetching. I'm interested in the opposite: how can I totally disable cover fetching, and only use embedded/local covers?
Scanning my music library covers is revealing my identity to any provider (a unique fingerprint) It would be great if Lollypop could have a default that makes sure no data gets revealed.

**Comment by bil-elmoussaoui** [comment]
Already possible
https://github.com/gnumdk/lollypop/blob/master/data/org.gnome.Lollypop.gschema.xml#L49
Just use this to disable it 
```bash
gsettings set org.gnome.Lollypop network-search false
```

**Comment by mray** [comment]
thanks for the quick feedback. I tried that, but after a restart and a "Reset database" it looks like Lollypop made its homework and stored them locally already. Where does Lollypop store its cached covers? (can't find it locally)

**Comment by gnumdk** [comment]
~/.cache/lollypop

**Comment by mray** [comment]
@bil-elmoussaoui your gsettings command worked! Is there a button in the GUI that triggers that, too?

**Comment by bil-elmoussaoui** [comment]
@mray Nop =) You can use DConf to modify the value if you want
