### ISSUE TITLE
Providing version information by CLI

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1060]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.2
• Linux distribution: Fedora 25

Please implement version information by `lollypop --version`. :)

**Comment by gnumdk** [comment]
Any reason?

**Comment by fbruetting** [comment]
Well, that's a quasi standard for getting version information, thought it'd be nice. ^_O
(`-V` is also often used)

**Comment by fbruetting** [comment]
Querying Lollypops version number now kills the program. ^_O
