### ISSUE TITLE
Replay of internet music isn't aborted by switching to another song

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1061]
• Lollypop version: 0.9.230
• Gtk Version: 3.22.2
• Linux distribution: Fedora 25

I tried to play `NOFX - The Separation Of Church And Skate` of which two of three versions cannot be played (i.e. load for endless times). Because of the alternating display of the cover image and a spinner, I wanted to switch to a local song, but this also wasn't possible, because then the cover of the local song was repeatedly exchanged by the spinner (of the internet track i assume). Had to restart Lollypop after all. Can the whole download/play action of internet media be completely aborted by selecting local media or another internet media (and maybe a cancel button, appearing while downloading)?

// Edit: I could abort it by clicking on the spinner, then on the "options" arrow of the song and then on the delete icon, but that seems to be a bit cumbersome.

**Comment by gnumdk** [comment]
Do you have an example, here NOFX - The Separation Of Church And Skate plays fine.

**Comment by gnumdk** [comment]
Can't you show me a screencast, can't get your behaviour ;)

**Comment by fbruetting** [comment]
Oh, I tried again and now all three versions work, so I can't reproduce it anymore, as it was the case before. :/ What happened was, that errors in the transmission lead to the behaviour, that I couldn't properly switch to another song, because the new song was repeatedly exchanged with the not loading song (in the left indicator of the header bar). Think you can close it, if it happens again, I'll make a screencast.

**Comment by fbruetting** [comment]
Tada! Now somehow I cannot play any internet song…

![lollypop](https://cloud.githubusercontent.com/assets/10520767/26226352/2311fe62-3c2c-11e7-9ca1-dfc6345dc5de.gif)
