### ISSUE TITLE
Add "Auto fetch covers from web" toggle

### ISSUE THREAD

**Issue by mray** [gnumdk/lollypop#1063]
As mentioned in #1059 a toggle like this would be a great privacy enhancement:

![image](https://cloud.githubusercontent.com/assets/164785/25970212/182f2108-3698-11e7-8d6f-efcfd52bb8b0.png)

This would also have to be the default. (Maybe with a first-run question to change it?) 
I see how this impacts UX, but the whole point is to intervene before you reveal your library.

*Sidenote:*
Everybody here certainly has a strong interest in not adding this kind of cruft, but I want to underline the importance of privacy here: If your music library does not make you uniquely identifiable - what does?

Thanks for your work on this awesome player!

**Comment by gnumdk** [comment]
This already exists in app menu. Will not add a different option. WIll not make it default.

**Comment by mray** [comment]
> This already exists in app menu.

What do you mean?

**Comment by gnumdk** [comment]
#1053

**Comment by mray** [comment]
#1107
