### ISSUE TITLE
"love album" icon inverted 

### ISSUE THREAD

**Issue by mray** [gnumdk/lollypop#1065]
• Lollypop version: 0.9.233
• Gtk Version: 3.22.11
• Linux distribution: Ubuntu 17.04

All albums that never were "loved" via the heart icon appear like this by default:
![image](https://cloud.githubusercontent.com/assets/164785/25986714/59b85398-36f1-11e7-9ca4-99cb27e894df.png)

They don't appear in the "loved albums" section, though.
When clicking on them they grey out, and they start working as expected again.

**Comment by gnumdk** [comment]
Does not happen here...

**Comment by gnumdk** [comment]
Send me lollypop.db by email for a check.

**Comment by mray** [comment]
Sent via email. The example db that Lollypop created (music collection 1 album) still contains the icon "error".

**Comment by gnumdk** [comment]
As a local fix:
sqlite ~/.local/share/lollypop/history.db
sqlite> update history set loved_album=0;

**Comment by mray** [comment]
SQL error: near "set": syntax error

**Comment by gnumdk** [comment]
sqlite3 sorry

**Comment by mray** [comment]
Even after restart no luck:

![image](https://cloud.githubusercontent.com/assets/164785/26033862/c1d182e2-38b3-11e7-831a-73e824569390.png)

**Comment by gnumdk** [comment]
You need to remove lollypop.db too ;)
