### ISSUE TITLE
Lollypop forever stuck on downloading online music

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [gnumdk/lollypop#1066]
• Lollypop version: 0.9.233 (latest)
• Gtk Version: 3.24 (latest)
• Linux distribution: Ubuntu 17.04 (latest)

If I use the PPA for Lollypop, install Lollypop, then try to search for some web music, say "305 approaching nirvana" the search list gets populated with many songs, but if i click on any of them, it (Lollypop) forever tries to "download" the song. and hence I am unable to use the Web music feature

**Comment by gnumdk** [comment]
You have an issue in youtube-dl or your network settings.
Any output? Any link to youtube video?

**Comment by gnumdk** [comment]
Are you able to download song?

**Comment by GNOME-IS-LIFE** [comment]
yes and no!! I got it to work to play and download the song! I ran
`lollypop` in the terminal and saw many logs in it stating
`$ sudo pip3 install beautifulsoup4` so i installed pip3 (python3-pip) then run this command, and rerun Lollypop, voila! Web music works! but now the problem is the app in command line repeatedly states "lollypop-portal not found" or something, and I don't know how to install that, but Web Music works. except for the facts that It needs online connectivity, ie it doesn't actually downlaod the song, & MANY songs it does not seem to find on YouTube, like "Trust Fund" by "Titanic Sinclair"

otherwise its awesome, but you should run a script in Lollypop that on first run (or in apt-get) installs these things i manually had to install for web to work ;)

**Comment by gnumdk** [comment]
You should use flatpak package ;)

**Comment by GNOME-IS-LIFE** [comment]
I tried to, but many errors came...
Will create another issue soon :wink:
