### ISSUE TITLE
Play album UI inconsistency

### ISSUE THREAD

**Issue by mray** [gnumdk/lollypop#1067]
It looks like an unnecessary inconsistency to have two different versions for the album overlay. Especially the *play* button position and size.

### in album by artist list
![selection_043](https://cloud.githubusercontent.com/assets/164785/26033391/9df3a4ac-38ab-11e7-91b3-0c423675f3f2.png)

### in love albums list
![selection_044](https://cloud.githubusercontent.com/assets/164785/26033401/ca89c460-38ab-11e7-8a09-b108454a2a98.png)

I suggest unifying the album cover overlay buttons.

**Comment by gnumdk** [comment]
Disagree, two differents widgets:
- First one is not clickable
- Second one is clickcable

**Comment by mray** [comment]
I guess I see your point:
* *Spacing* (a popup click needs space, the "PLAY" gets in the way)
* *Usage* ("PLAY" is most important when there is no popup)

There are basic UX problems anyway:
* *Different* representations for the *same* interaction on the *same* element.
* Second widget has a poor information-scent concerning its clickability

### consistent solutions could be:

1. Two different main interactions
![image](https://cloud.githubusercontent.com/assets/164785/26048154/3d2e0ea4-3956-11e7-93d6-c6dce6ecc177.png)

2. *or better*: consistent placement and different interactions
![image](https://cloud.githubusercontent.com/assets/164785/26048248/9402f096-3956-11e7-9fd8-b39ae3fe242e.png)

Btw: stretching the clickable area for the main interaction to the entire cover makes sense in any case imho.

**Comment by mray** [comment]
*also making sense in this issue:*

The play button could be a play/pause toggle:
![image](https://cloud.githubusercontent.com/assets/164785/26048662/61fb024e-3958-11e7-8f4f-4ac8eb0bda0c.png)

**Comment by gnumdk** [comment]
>also making sense in this issue
No, does not make sense for me, I may be listening to a song from this album and want to play all album by pushing play button

**Comment by mray** [comment]
Is this your point?:
*Track 3 of an album is playing, you want to play from track 1 and click the play button again?*

I can see how this can be used as a "shortcut". Usually pressing the play button twice controls the "play head" as a toggle. Including Lollypop main play button. You suggest having the *same* button resulting in playback of *different* tracks based on context. I'd recommend having only one assigned meaning.

A solution to still having a "shortcut" behavior could be to use a separate icon for "play from start" – would be a bit clunky though.

Since you closed the issue – what about the positioning proposal?

**Comment by mray** [comment]
Oh, I didn't notice the commit link.

**Comment by gnumdk** [comment]
This button is not a playback control

**Comment by mray** [comment]
Oh, not so fast! You have to bear with me and consider one more display of inconsistency:

A screenshot that shows *4* different play buttons and each of them starts different music:
![screenshot](https://cloud.githubusercontent.com/assets/164785/26116316/09420aec-3a63-11e7-9e17-cc7eb66249ab.png)

1. Un-pauses the currently paused track.
2. Starts the album from 1997.
3. Starts the album from 1999.
4. Adds the running track to the queue - clicking NEXT to it would start the current song from beginning.

If that does not raise eyebrows I really rest my case here.
