### ISSUE TITLE
Titlebar blocked by open popup

### ISSUE THREAD

**Issue by mray** [gnumdk/lollypop#1068]
• Lollypop version: 0.9.233
• Gtk Version: 3.22.11
• Linux distribution: Ubuntu 17.04

Not sure if this is related to the known bug:
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

Any interaction on the titlebar is blocked by the popup:
![peek 2017-05-15 10-33](https://cloud.githubusercontent.com/assets/164785/26049629/eee8ff5a-395b-11e7-86ed-e2360efe2f32.gif)

**Comment by gnumdk** [comment]
It's by design.
