### ISSUE TITLE
Radio streaming is periodically paused and resumed due to a small default for buffer-duration in playbin

### ISSUE THREAD

**Issue by gfidente** [gnumdk/lollypop#1069]
• Lollypop version: 0.9.231
• Gtk Version: 3.22.15
• Linux distribution: ArchLinux

gst playbin seems to default buffer-duration to 1s and estimate the buffer-size from the stream rate; the duration appears to be too short in many circumstances causing playback to be paused (to fill the buffer) and then resumed

This can be observed with:

  gst-launch-1.0 playbin uri=http://stream-dc1.radioparadise.com/rp_192m.ogg

By contrast playback remains stable by increasing the duration to 3s:

  gst-launch-1.0 playbin uri=http://stream-dc1.radioparadise.com/rp_192m.ogg buffer-duration=3000000000

**Comment by gnumdk** [comment]
See PR, buffer is already set to 10 seconds.

**Comment by gfidente** [comment]
hi, you can close the PR but I believe the issue isn't resolved and I don't have the same issue with other players based on gst (like totem or rhythmbox).

More specifically, it seems to me that if/when the buffer is empty the stream starts skipping with very short intervals and never returns stable unless I manually stop and start playback again.

If I read the code correctly the duration is to 10s and size to 5M but we don't PAUSE the pipeline on buffer-percentage messages (I assume that is to allow for refill). This is instead what seems to be suggested in the GST playbin guide. Could this be the real issue/fix?

**Comment by gnumdk** [comment]
Any documentation link? Form me buffer-percentage message is just here to show buffer status.

**Comment by gfidente** [comment]
I found it in the playbin reference; there is a Buffering section suggesting to listen for buffering messages, extract percentage and act on those. FWIW it appears in both the playbin2 and playbin3 pages. https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-playbin3.html
