### ISSUE TITLE
Web music doesn't download the song offline

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [gnumdk/lollypop#1071]
• Lollypop version: 0.9.233
• Gtk Version: 3.24
• Linux distribution: Ubuntu GNOME 17.04

In my last issue, Web music was not working, but I fixed that by running certain commands. Now the problem is when I click the "Save" button for web music, only the metadata (name, artwork) gets saved. The song doesn't, and needs internet for that, otherwise returns a ugly notifications saying something along the lines of  "web 404".

**Comment by gnumdk** [comment]
Non, and it will not... And lollypop will not show offline file if you are offline (and using network manager)

**Comment by GNOME-IS-LIFE** [comment]
why not??? any specific reason? This one feature has the ability to make this music player miles ahead of all the other ones!!
