### ISSUE TITLE
You are missing lollypop-portal...

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [gnumdk/lollypop#1072]
• Lollypop version: 0.9.233
• Gtk Version: 3.24
• Linux distribution: Ubuntu 17.04
after running many commands for web music to work on Lollypop, in the command line it (lollypop) repeatedly states "You are missing lollypop-portal: https://github.com/gnumdk/lollypop-portal" and that link takes me to a bunch of uncompiled files on github. so how do i install this "lollypop-portal"?

**Comment by gnumdk** [comment]
apt-get install lollypop-portal?

**Comment by GNOME-IS-LIFE** [comment]
how did i miss that ?? :man_facepalming: thank you!!
