### ISSUE TITLE
Many songs are not found in Web Music selection

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [gnumdk/lollypop#1073]
• Lollypop version: 0.9.233
• Gtk Version: 3.24
• Linux distribution: Ubuntu GNOME 17.04

many songs, like those of "Poppy", "Titanic Sinclair", & "Mars Argo" are not available. 
example - https://www.youtube.com/watch?v=BQQUUqcE-i0 
(Trust Fund - Titanic Sinclair Official Audio) 
This song is available legitamtely on YouTube, then why Lollypop's Web Music feature cannot track it down? where does Lollypops' Web Music feature index music on YouTube from? is it done by a few people, or automatically? Is there a way to contribute and add songs on it?

**Comment by gnumdk** [comment]
Lollypop is searching songs in itunes and spotify, youtube is only used for playback.

**Comment by GNOME-IS-LIFE** [comment]
I see. Is there any way for us to "manually" add a new online song which takes to a YouTube link? where does Lollypop store the list of the online songs? Is there any option to add our own manual online song?

**Comment by GNOME-IS-LIFE** [comment]
Or maybe an option which lets us search songs straight from YouTube? I know this way a lot of unwanted garbage will also come in the search, but atleast many more songs will be available!! 
please reopen, as I feel this topic is not closed yet
