### ISSUE TITLE
Flatpak web music error :No module named 'pkg_resources'

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [gnumdk/lollypop#1075]
• Lollypop version: 0.9.231
• Gtk Version: 3.24
• Linux distribution: Ubuntu 17.04
 I am using stock flatpak (might be a bit old version) installing lollypop from the flatpak file given on the website of Lollypop, installs fine, but when using the "Web music" feature, if i click on any song in the search results, they download and their artist even comes on the sidebar, but then the song gets stuck on loading and this nasty error pops up in the command line and in the notififcations
`WebYouTube::get_uri_content: Traceback (most recent call last):
  File "/app/bin/youtube-dl", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'`
and it hangs Flatpak Lollypop till i quit it.

**Comment by gnumdk** [comment]
Lollypop is now on flathub, check flatpak section on Lollypop web page.

**Comment by gnumdk** [comment]
You may need some times for package to build
