### ISSUE TITLE
Problem with cyrillic encoding in radio

### ISSUE THREAD

**Issue by edshevsky** [gnumdk/lollypop#1076]
• Lollypop version: 0.9.233
• Gtk Version: 3.24
• Linux distribution: Fedora 25

The problem with Cyrillic encoding in the Stream: _http://eradio.cc.colocall.com:8000/eradio_.
In Rhythmbox - same problem. But in Winamp on Windows 10 - Cyrillic tags displaying correctly.
Link to radiostream pulled from the official radio station's site. Moreover, its technical support claims that on their part there is no any problems.

![lollypop](https://cloud.githubusercontent.com/assets/12774629/26125116/a8177b7c-3a89-11e7-9290-21c1fcb8ca24.png)

![winamp](https://cloud.githubusercontent.com/assets/12774629/26125117/a81b3fdc-3a89-11e7-891d-30a23c5073c5.jpg)

**Comment by gnumdk** [comment]
The issue is simple, Winamp may embed an encoding detection tool.
Don't want this in Lollypop, the issue is in radio stream, we are in 2017, they need to use unicode!
