### ISSUE TITLE
Radio Stations wont play

### ISSUE THREAD

**Issue by vendforce** [gnumdk/lollypop#1081]
• Lollypop version: 0.9.231-2 
• Gtk Version: 3.24
• Linux distribution: arch x64

I cant play any radio stations on lollypop, after I add and press play  it just does nothing , Ive done many fresh installs over the last year and everytime I install lollypop I can never play any radio stations 

gst-libav is installed

Im currently using internet radio gnome extension and it works no problems , But I want to have lollypop as my main radio player

lollypop --debug

/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Lastfm::__connect(): Authentication Failed - You do not have permissions to access the service
SpotifyCharts::__update_for_url(): https://spotifycharts.com/regional/en/weekly/latest/download
Error playing: http://31.14.40.241:6184/
Toolbar::_on_current_changed
Error playing: http://31.14.40.241:6184/
Toolbar::_on_current_changed
Error playing: http://31.14.40.241:6184/
Toolbar::_on_current_changed
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
ViewContainer::__delayedclean_view(): <view_albums.AlbumsView object at 0x7f7c493913f0 (lollypop+view_albums+AlbumsView at 0x1d02b50)>
SpotifySearch::get_track 'album'
SpotifySearch::get_track 'album'
LastfmCharts::__update_for_url(): http://ws.audioscrobbler.com/2.0/?method=chart.gettoptracks&api_key=7a9619a850ccf7377c46cf233c51e3c6&format=json
LastfmCharts::__on_item_found(): HUMBLE. - ['Kendrick Lamar']
Lio.load_contents(): g-io-error-quark: Operation was cancelled (19)
LastfmCharts::__on_item_found(): DNA. - ['Kendrick Lamar']
Lio.load_contents(): g-io-error-quark: Operation was cancelled (19)
LastfmCharts::__on_item_found(): ELEMENT. - ['Kendrick Lamar']
Lio.load_contents(): g-io-error-quark: Operation was cancelled (19)
SpotifySearch::tracks(): 'collectionName'
LastfmCharts::__on_item_found(): Shape of You - ['Ed Sheeran']
Lio.load_contents(): g-io-error-quark: Operation was cancelled (19)
LastfmCharts::__on_item_found(): YAH. - ['Kendrick Lamar']
Lio.load_contents(): g-io-error-quark: Operation was cancelled (19)

**Comment by terencode** [comment]
I don't know if it's related but in addition to not play, radio station now crashes lollypop using the latest git version:
`Player::_on_stream_start(): http://broadcast.infomaniak.net/tsfjazz-high.mp3
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lollypop/mpris.py", line 392, in __on_current_changed
    self.__update_metadata()
  File "/usr/lib/python3.6/site-packages/lollypop/mpris.py", line 328, in __update_metadata
    track_id = randint(Gst.SECOND, 90000000)
  File "/usr/lib/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 198, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1000000000,90000001, -909999999)
`

**Comment by gnumdk** [comment]
Argh!!!

**Comment by gnumdk** [comment]
@terencode fixed

**Comment by terencode** [comment]
@gnumdk Merci ^^

**Comment by gnumdk** [comment]
mpv "http://31.14.40.241:6184/

Playing: http://31.14.40.241:6184/

[ytdl_hook] ERROR: Unsupported URL: http://31.14.40.241:6184/
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] http: HTTP error 404 Resource Not Found
Failed to open http://31.14.40.241:6184/

**Comment by gnumdk** [comment]
There is an hidden char in your URI. It works removing the last hidden char in Lollypop.

**Comment by gnumdk** [comment]
As you say it's never working, I think you are missing some gstreamer plugins.

**Comment by gnumdk** [comment]
And here it works on ArchLinux ;)

**Comment by vendforce** [comment]
it still wont play I give up on lollypop , It used to work so well.

ehhhh "As you say it's never working, I think you are missing some gstreamer plugins."

hmm well when I download the source file from aur and do makepkg -s .. isnt that what installs the nessasary packages ???? 



I give up, I'm going to dump lollypop and just use internet radio gnome extension it works fine


mpv http://31.14.40.241:6184/

Playing: http://31.14.40.241:6184/
[ytdl_hook] ERROR: Unsupported URL: http://31.14.40.241:6184/
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
File tags:
 icy-title: 
AO: [pulse] 44100Hz stereo 2ch s16
A: 00:00:03 Cache:  2s+8KB

**Comment by gnumdk** [comment]
Can't understand what's wrong as it works here with same stream and same distribution. "Error playing" message comes from gstreamer.
