### ISSUE TITLE
rising (showing) Lollypop from Media Player Extension

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#1083]
• Lollypop version: 0.9.224
• Gtk Version: 3.24.2
• Linux distribution: Fedora 26

Lollypop doesn't seem to behave like expected or like other players for the Gnome Media Player extension - when Lollypop window is open in the background and playing a song, in the Gnome Media Player extension you can click the text of the song under the album picture and Lollypop (the player) should rise but doesn't - Lollypop window stays in the background. When VLC or Rythmbox is playing with their windows in the background, when you click the the text under the album picture their windows rise up so you can use the player.

**Comment by gnumdk** [comment]
Wayland is broken, switch to Xorg. Known GTK issue.

**Comment by gnumdk** [comment]
It will save your life because it happens with all GTK applications when clicking a notification.

**Comment by corebots** [comment]
oh well sorry I should have noted that, I'm on xorg... (I would like to try wayland but I fail to set it up with my nvidia card :D )

**Comment by gnumdk** [comment]
Strange, testing ;)

**Comment by gnumdk** [comment]
Here it works :-/

**Comment by corebots** [comment]
thanks for testing. I have notifications for Lollypop switched off, because the Media Player extension displays the current song in the top bar.

**Comment by corebots** [comment]
I'll try to do a short screencast.

**Comment by gnumdk** [comment]
Here it works with Media Player Extension, window is raised.
Fedora 26 too.

**Comment by corebots** [comment]
But also if the window is open, but behind another window?

**Comment by gnumdk** [comment]
https://www.youtube.com/watch?v=p2TarY2qZgg&feature=youtu.be

**Comment by gnumdk** [comment]
And yes it works if window is behind others.

**Comment by gnumdk** [comment]
Do a screencast

**Comment by corebots** [comment]
https://www.dropbox.com/s/7suii4g66da4k4r/desktop2.mp4?dl=0 don't know if it's enough for you to see :)

**Comment by corebots** [comment]
it's done with vlc quickly, mouse is not visible. it's basically when i click on the text i get a notification that lollypop is ready, instead of when i click on vlc for example, it rises.

**Comment by corebots** [comment]
but sometimes the notification isn't even displayed just nothing happens, as if

**Comment by gnumdk** [comment]
Can you test with a fresh user and DEFAULT gnome configuration (no extensions)?

**Comment by corebots** [comment]
ok just a minute. but for you it works? because on your screencast lollypop window was closed, and i mean that the window is already open, just not focused

**Comment by gnumdk** [comment]
Yes, it works with window opened

**Comment by gnumdk** [comment]
Do you know how to build lollypop from source?

**Comment by gnumdk** [comment]
```
diff --git a/src/application.py b/src/application.py
index 5449b71a..fc00d721 100644
--- a/src/application.py
+++ b/src/application.py
@@ -438,7 +438,7 @@ class Application(Gtk.Application):
                 parser.connect("entry-parsed", self.__on_entry_parsed)
                 parser.parse_async(uri, True, None, None)
         elif self.window is not None and self.window.is_visible():
-            self.window.present()
+            self.window.present_with_time(Gtk.get_current_event_time())
         elif self.window is not None:
             # self.window.setup_window()
             # self.window.present()
diff --git a/src/mpris.py b/src/mpris.py
index b51d7914..b7aab1ff 100644
--- a/src/mpris.py
+++ b/src/mpris.py
@@ -14,7 +14,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 
-from gi.repository import Gio, Gst, GLib
+from gi.repository import Gio, Gst, GLib, Gtk
 
 from random import randint
 
@@ -177,7 +177,7 @@ class MPRIS(Server):
 
     def Raise(self):
         self.__app.window.setup_window()
-        self.__app.window.present()
+        self.__app.window.present_with_time(Gtk.get_current_event_time())
 
     def Quit(self):
         self.__app.quit()
```

**Comment by corebots** [comment]
I've tried another user, seems the same https://www.dropbox.com/s/6enpdsn9rwu45lw/desktop%20new%20user.mp4?dl=0

**Comment by corebots** [comment]
i can build lollypop from source, like download the main code and build, but the diff you posted above i don't know actually what to do with. i'll try to google :/

**Comment by gnumdk** [comment]
Save in a file. Say patch.diff

cd lollypop
patch -p1 < /path/to/patch.diff

**Comment by corebots** [comment]
:D looks like it's fixed. that was fast!!

**Comment by corebots** [comment]
i'll test a bit more, but thank you

**Comment by gnumdk** [comment]
Ok, strange it does not happen here
