### ISSUE TITLE
have unknowns artists to the top

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1086]
sometimes it happen i have not tagged my music and they appear as unknown (or in my case sconosciuto)...would be nice if unknown could be on the top of the artist list so you'll always know where you have untagged music...seen that in other media players and it's really handy...

**Comment by gnumdk** [comment]
From a performance point of view, I do not want that. Currently, sqlite use strcoll() from python as sort function. This function is written in C so it's fast but if I start to add python code...

What a bout an ( ! ) icon ?

**Comment by legacychimera247** [comment]
it would be ok to me :)
