### ISSUE TITLE
Feature Request : Port to QT!

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [gnumdk/lollypop#1089]
- Lollypop version: 0.9.237
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: KDE Neon

I have recently started using Plasma 5 (on KDE Neon) and am in love with it. Problem is, only this music player has all features I need (online, good music playback, clean interface) and since it's a GNOME app, it is very inconsistent with all other KDE apps (no global menu, csd). So is there any initiative to port this over to QT?

**Comment by gnumdk** [comment]
LOL! Just use Babe.

**Comment by GNOME-IS-LIFE** [comment]
but Babe is only available as source code, and no precompiled binary :cry:

**Comment by gnumdk** [comment]
Just wait him to finish it. But, Lollypop is build around GNOME technologie so a port is not possible.

**Comment by GNOME-IS-LIFE** [comment]
I see. thanks.

**Comment by trmdi** [comment]
Try cantata.
