### ISSUE TITLE
lollypop doesn't open in music browser interface; Unicode locale missing error...

### ISSUE THREAD

**Issue by disisdrsid** [gnumdk/lollypop#1090]
Lollypop doesn't open into the music browser interface; error message is "lollypop isn't designed to work without an Unicode locale. Please fix your system" on my KDE Neon dev git unstable....

BUG MAY BE REJECTED IF MISSING:

### Environement: KDE Plasma 5.9.90
- Lollypop version:?
- qt version: 5.7.1
KDE frameworks: 5.33.0
- GNU/Linux distribution: KDE neon

### Bug/Feature
<Describe your bug/feature here>

**Comment by gnumdk** [comment]
>the music browser interface

What this?

**Comment by gnumdk** [comment]
This message is not present in Lollypop anymore, you are using an old version

**Comment by gnumdk** [comment]
Upgrade lollypop!
