### ISSUE TITLE
lollypop stops even if the option to continue is selected

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1091]
if i play a song in lollypop and then the song finishes, lollypop goes to the next track but it suddenly pause it and i have to click on play again to make it start...tried selecting the repeat option and the continuous playback but with no result...i would allegate you what terminal says but seems that terminal only display

`Gtk-WARNING **: Allocating size to lollypop+window+Window 0x55eef98622c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
`

 i am using out of information, latest fedora 25 with latest lollypop version...

**Comment by gnumdk** [comment]
Every time?

**Comment by legacychimera247** [comment]
almost every time...it happened with 95% of songs...

**Comment by gnumdk** [comment]
Fixed
