### ISSUE TITLE
Real icon not shown when Alt-tabbing in KDE Plasma

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1092]
### Environment
• Lollypop version: 0.9.233
• Gtk Version: 3.22.11-1.1
• Linux distribution: openSUSE Tumbleweed
• Desktop environment: KDE Plasma 5.9.5

### Bug
The icon shown when Alt-tabbing isn't Lollypop's actual icon; it's some generic X11 icon:

![ugly icon](https://cloud.githubusercontent.com/assets/1097249/26309506/4f573540-3ecb-11e7-8e23-3f19e2968b60.jpg)

**Comment by gnumdk** [comment]
OpenSUSE issue or KDE issue. Report downstream.

**Comment by Pointedstick** [comment]
Gotcha. Reported as https://bugzilla.opensuse.org/show_bug.cgi?id=1040253

**Comment by Pointedstick** [comment]
https://bugzilla.suse.com/show_bug.cgi?id=1040253

**Comment by Pointedstick** [comment]
Plasma issue: https://bugs.kde.org/show_bug.cgi?id=380208

**Comment by davidedmundson** [comment]
It's not Plasma at fault:

Here's your xprop output:

There's no _NET_WM_ICON set and you have:
_NET_WM_ICON_NAME(UTF8_STRING) = "Lollypop"

whereas your icon appears to be:
org.gnome.Lollypop  which is what you have in your .desktop file

**Comment by gnumdk** [comment]
@davidedmundson @Pointedstick It's a GTK issue, _NET_WM_ICON_NAME is set to window title, report this to GTK devs... BTW Lollypop icon works on all Desktop Environnement except KDE.

**Comment by gnumdk** [comment]
https://www.bountysource.com/issues/1360827-window-and-icon-title-set-incorrectly

**Comment by Pointedstick** [comment]
No, this isn't a GTK problem; you've just chosen to name your icons in a manner that won't match the window title, thereby unnecessarily triggering an undesirable GTK behavior.

Looking in my `/usr/share/applications/` folder, your decision to name your icons "org.gnome.Lollypop.png" instead of something like "Lollypop.png" appears to be unique among everything I have installed:


```
grep -ri icon /usr/share/applications/
[...]
/usr/share/applications/gcr-prompter.desktop:Icon=security-medium
/usr/share/applications/YaST.desktop:Icon=yast
/usr/share/applications/org.kde.skanlite.desktop:Icon=scanner
/usr/share/applications/easytag.desktop:Icon=easytag
/usr/share/applications/dropbox.desktop:Icon=dropbox
/usr/share/applications/simplescreenrecorder.desktop:Icon=simplescreenrecorder
/usr/share/applications/SpiderOakONE.desktop:Icon=SpiderOakONE
/usr/share/applications/luckybackup-gnome-su.desktop:Icon=luckybackup.png
/usr/share/applications/luckybackup-kde-su.desktop:Icon=luckybackup.png
/usr/share/applications/luckybackup.desktop:Icon=luckybackup.png
/usr/share/applications/openscad.desktop:Icon=openscad
/usr/share/applications/gparted.desktop:Icon=gparted
/usr/share/applications/youtube-dl-gui.desktop:Icon=youtube-dl-gui
[...]
/usr/share/applications/org.gnome.Lollypop.desktop:Icon=org.gnome.Lollypop
```

If you change your icons to omit "org.gnome." from the beginning and then update the .desktop file accordingly, then this problem will be resolved.

**Comment by gnumdk** [comment]
>No, this isn't a GTK problem; you've just chosen to name your icons in a manner that won't match the 
>window title, thereby unnecessarily triggering…
@Pointedstick All GNOME applications do this.

**Comment by Pointedstick** [comment]
@gnumdk No, this isn't a GTK problem; you've just chosen to name your icons in a manner that won't match the window title, thereby unnecessarily triggering an undesirable GTK behavior.

Looking in my `/usr/share/applications/` folder, your decision to name your icons "org.gnome.Lollypop.png" instead of something like "Lollypop.png" appears to be unique among everything I have installed:


```
grep -ri icon /usr/share/applications/
[...]
/usr/share/applications/gcr-prompter.desktop:Icon=security-medium
/usr/share/applications/YaST.desktop:Icon=yast
/usr/share/applications/org.kde.skanlite.desktop:Icon=scanner
/usr/share/applications/easytag.desktop:Icon=easytag
/usr/share/applications/dropbox.desktop:Icon=dropbox
/usr/share/applications/simplescreenrecorder.desktop:Icon=simplescreenrecorder
/usr/share/applications/SpiderOakONE.desktop:Icon=SpiderOakONE
/usr/share/applications/luckybackup-gnome-su.desktop:Icon=luckybackup.png
/usr/share/applications/luckybackup-kde-su.desktop:Icon=luckybackup.png
/usr/share/applications/luckybackup.desktop:Icon=luckybackup.png
/usr/share/applications/openscad.desktop:Icon=openscad
/usr/share/applications/gparted.desktop:Icon=gparted
/usr/share/applications/youtube-dl-gui.desktop:Icon=youtube-dl-gui
[...]
/usr/share/applications/org.gnome.Lollypop.desktop:Icon=org.gnome.Lollypop
```

If you change your icons to omit "org.gnome." from the beginning and then update the .desktop file accordingly, then this problem will be resolved.

**Comment by gnumdk** [comment]
$ grep -ri "icon=org.gnome" /usr/share/applications/
/usr/share/applications/org.gnome.Nautilus.desktop:Icon=org.gnome.Nautilus
/usr/share/applications/org.gnome.Documents.desktop:Icon=org.gnome.Documents
/usr/share/applications/org.gnome.Epiphany.desktop:Icon=org.gnome.Epiphany
/usr/share/applications/org.gnome.Software.desktop:Icon=org.gnome.Software
/usr/share/applications/org.gnome.Maps.desktop:Icon=org.gnome.Maps
/usr/share/applications/org.gnome.Calendar.desktop:Icon=org.gnome.Calendar
/usr/share/applications/org.gnome.Cheese.desktop:Icon=org.gnome.Cheese
/usr/share/applications/org.gnome.Todo.desktop:Icon=org.gnome.Todo

**Comment by Pointedstick** [comment]
@gnumdk

> @Pointedstick All GNOME applications do this.

Wrong.

```
$ grep -r Icon /usr/share/applications/ | grep -i mines
/usr/share/applications/gnome-mines.desktop:Icon=gnome-mines

$ grep -r Icon /usr/share/applications/ | grep -i chess
/usr/share/applications/gnome-chess.desktop:Icon=gnome-chess

$ grep -r Icon /usr/share/applications/ | grep -i logs
/usr/share/applications/org.gnome.Logs.desktop:Icon=gnome-logs
```

And notably, all those programs have their icons show up correctly in KDE Plasma's alt-tab switcher.

**Comment by gnumdk** [comment]
Because this applications need to be updated. (And will be updated)

**Comment by gnumdk** [comment]
https://wiki.gnome.org/HowDoI/ChooseApplicationID

**Comment by Pointedstick** [comment]
```
$ grep -r Icon /usr/share/applications/ | grep -i evolution
/usr/share/applications/evolution.desktop:Icon=evolution
```

Why bother adhering to a convention that:
1. Doesn't yield any advantages whatsoever
2. Results in a worse user experience for users on KDE plasma
3. Many/most GNOME programs don't even adhere to

**Comment by gnumdk** [comment]
This work on all DE, report this bug to bugzilla.gnome.org if you think GNOME behaviour is wrong.

**Comment by Pointedstick** [comment]
> This work on all DE, report this bug to bugzilla.gnome.org if you think GNOME behaviour is wrong.

Pointless; The GTK and GNOME folks don't care about behaviors which negatively impact any DE but GNOME. If I can't convince you, I'll report it to KDE and ask them to work around this somehow, which is presumably what all other DEs do.

> https://wiki.gnome.org/HowDoI/ChooseApplicationID

According to those guidelines, you should not be using "org.gnome" because your project isn't hosted on gnome.org.

**Comment by Pointedstick** [comment]
I just realized something, @gnumdk: nobody's asking you to change your application ID. We're simply asking you to change the _icon filenames._ There's no cardinal rule that requires that your icon filenames to precisely match the application ID--and indeed, most GNOME programs that use reverse-DNS-style application IDs don't apply that convention to their icon names.

Is there a reason why you can't change the icon names to match what most of the rest of the GNOME programs do and fix this bug?

**Comment by gnumdk** [comment]
BTW The issue is not here, nautilus use org.gnome.Nautilus.png and it works...

**Comment by davidedmundson** [comment]
You don't need to rename anything. That's a weird suggestion.

I'm afriad I still think the issue is here . 

> _NET_WM_ICON_NAME is set to window title,

that's only partly true. It's set to the window title if it's not already explicitly set elsewhere.

Your code currently has in window.py:329
        self.set_default_icon_name("lollypop")

I think this should be: 
        self.set_default_icon_name("org.gnome.Lollypop")

**Comment by gnumdk** [comment]
@davidedmundson Thanks, it was the issue :-1:
