### ISSUE TITLE
Party mode only plays the first song

### ISSUE THREAD

**Issue by simonbcn** [gnumdk/lollypop#1094]
### Environment
- Lollypop version: lollypop-git 0.9.237.r2.g41765833-1 (_installed from AUR_)
- GNOME/GTK+ versions: GNOME Shell 3.24.2 / gtk3 3.22.15-1
- GNU/Linux distribution: Arch Linux

### Bug/Feature
I have set "_No shuffle_" and "_Do not repeat_".
When I click in _Party mode_ button, it plays the first song and then stop.

**Comment by gnumdk** [comment]
Seems mix feature is broken :-(
