### ISSUE TITLE
lollypop-portal remains opened when Lollypop is closed

### ISSUE THREAD

**Issue by simonbcn** [gnumdk/lollypop#1095]
### Environment
- Lollypop version: lollypop-git 0.9.237.r2.g41765833-1 (_installed from AUR_)
- GNOME/GTK+ versions: GNOME Shell 3.24.2 / gtk3 3.22.15-1
- GNU/Linux distribution: Arch Linux

### Bug/Feature
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
juan      9244 48.5  0.7 1453656 125864 tty1   SLl+ 10:15   0:00 /usr/bin/python /usr/bin/lollypop
juan      9255  4.5  0.1 320272 21856 ?        Sl   10:15   0:00 /usr/bin/python /usr/lib/lollypop/lollypop-portal
```

I close Lollypop with menu option `Quit` but:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
juan      9255  0.4  0.1 320272 21856 ?        Sl   10:15   0:00 /usr/bin/python /usr/lib/lollypop/lollypop-portal
```

**Comment by gnumdk** [comment]
It's normal, it's the same with others xdg portals. And I don't see any reason to stop it.

**Comment by simonbcn** [comment]
Perhaps because it is no longer necessary to remain open if Lollypop is closed?

**Comment by gnumdk** [comment]
Faster loading later

**Comment by gnumdk** [comment]
BTW, it's not an issue, portal does nothing if not used and you are using Linux, not Windows 98 ;)
