### ISSUE TITLE
Lyrics doesn't show the lyrics from the id3 tag

### ISSUE THREAD

**Issue by somas95** [gnumdk/lollypop#1096]
- Lollypop version: 0.9.231
- GNOME/GTK+ versions: 3.24.2
- GNU/Linux distribution: Archlinux

Reproducible: Always

Steps to reproduce: 

-Open lollypop
-Play a song with lyrics in the id3 lyrics tag
-Click on the lyrics panel
-Lollypop searches the lyrics on the internet, not in the id3 tag

Running Lollypop with the debug flag doesn't provide useful information: no error are displayed
Resetting the database don't work: the error persists

The issue happens if the lyrics are fetched by Beets automatically or if they are manually set with kid3 or any tag editor

**Comment by gnumdk** [comment]
Sens file by email

**Comment by somas95** [comment]
I sent you an email with the file
