### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by arielchuri** [gnumdk/lollypop#1097]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environement
- Lollypop version:
.9.238
- GNOME/GTK+ versions:
 libgtk-3-0:amd64             3.22.11-0ubuntu3  amd64        GTK+ graphical user interface library
- GNU/Linux distribution:
ariel@ariel-MacBookPro:~$ neofetch
            .-/+oossssoo+/-.               ariel@ariel-MacBookPro 
        `:+ssssssssssssssssss+:`           ---------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 17.04 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Model: MacBookPro9,1 1.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.10.0-21-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 day, 9 hours, 51 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2509 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.7 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1680x1050 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Budgie 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter(Budgie) 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Arc-Dark [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Papirus-Dark.foldercolor [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: tilix 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i7-3820QM (8) @ 3.7GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: Intel Integrated Graphics 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GT 650M Mac Edition 
      -+sssssssssssssssssyyyssss+-         Memory: 3411MiB / 7919MiB 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-.                                       

### Bug/Feature
The lollypop window is blank. Everything seems to work fine otherwise. The title bar is fine. I can play music from the search. It had been working fine and seemed to break for no particular reason. I tried purge/reinstall to no avail. I may have been trying out party mode at the time.

**Comment by gnumdk** [comment]
Send me ~/.local/share/lollypop/lollypop.db by email.

**Comment by gnumdk** [comment]
Tested with your db, here it works :-/

**Comment by gnumdk** [comment]
Any output on command line?

**Comment by arielchuri** [comment]
After the window shows these lines print and the last two a bit later.

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
SpotifySearch::get_track 'album'
SpotifySearch::get_track 'album'

**Comment by gnumdk** [comment]
A screencast to be sure I understand the issue?

**Comment by arielchuri** [comment]
Sent it via email.

**Comment by gnumdk** [comment]
Ok, it's really really strange, some widgets are missing :-(

**Comment by gnumdk** [comment]
Does it happen with a new user? Please tar ~/.local/share/lollypop ~/.cache/lollypop and send me view your cloud.

**Comment by arielchuri** [comment]
New user seems fine. I sent the folders.

**Comment by gnumdk** [comment]
Can't reproduce with folders. Here, I have access to your albums.

**Comment by arielchuri** [comment]
Not sure what you mean. How can I help you solve this?

**Comment by gnumdk** [comment]
It works here with all your files... So, what is next? Please reupload the screencast, do not have access to it anymore.

**Comment by gnumdk** [comment]
No response, closing...
