### ISSUE TITLE
Results with same title are combined in GNOME search results

### ISSUE THREAD

**Issue by Gert-dev** [gnumdk/lollypop#1102]
- Lollypop version: 0.9.238
- GNOME/GTK+ versions: 3.22.15
- GNU/Linux distribution: Arch Linux 64-bit

It appears that results that share the same title, e.g. an album that has the same name as a track that is on the album, are combined in the GNOME shell search results.

I tried a couple of these and usually selecting the item will start playing the album instead of the track, but in some cases it also preferred the track over the album. In all cases, only one of them was listed.

**Comment by gnumdk** [comment]
Can't reproduce here.
If search is bold, then it's a track. If artist is bold, then it's an album.

**Comment by Gert-dev** [comment]
Strange, it doesn't happen for you in the GNOME shell search results? The referenced commit only changed the Lollypop search results for me, but not the ones from the GNOME dash (i.e. the GNOME search provider).

I noticed that some search results are hidden behind a + icon in the GNOME shell search results, but I managed to find another match that only has one result whilst there should be two: the track and the album (which both have the same name). There also seems to be no way to disambiguate between the two via the GNOME dash (i.e. you can only type artist **or** title but not both), but that's a separate issue, I guess.

**Comment by gnumdk** [comment]
No, the fix is about GNOME dash.

**Comment by Gert-dev** [comment]
Ok, it seems to be fixed now. It took a while for the changes from the new Lollypop version to get through to the GNOME dash. There is only one case in which I can reproduce it now, but there are other matches as well and there is a small + next to the result in the GNOME dash, so that probably means that the other result is hidden because there are multiple matches.

Strange detail: sometimes I only see two matches in GNOME dash and there is a + icon, but I can see up to three matches with other search queries in the dash (also with a + icon). I also can't narrow down the results by entering the track artist next to the track title (only one of either works), should I create a separate issue about that?

**Comment by gnumdk** [comment]
Yes, but this is GNOME Shell behaviour, not Lollypop...
