### ISSUE TITLE
getting internal data stream error when trying to listen to online radio

### ISSUE THREAD

**Issue by thieryl** [gnumdk/lollypop#1104]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environement
- Lollypop version: 0.9.231
- GNOME/GTK+ versions: Fedoa 25 Cinnamon 
- GNU/Linux distribution: Fedora 

### Bug/Feature
<Describe your bug/feature here>
getting internal data stream error when trying to listen to online radio

**Comment by gnumdk** [comment]
Missing gstreamer package I guess, BTW not a lollypop issue...

**Comment by thieryl** [comment]
thanks for the answer 
was fixed by recompiling as instructed
