### ISSUE TITLE
Laggy playback

### ISSUE THREAD

**Issue by pciavald** [gnumdk/lollypop#1105]
## Environement
- Lollypop version: 0.9.239
- GTK+ versions: 2.24.31 / 3.22.15
- GNU/Linux distribution: Manjaro 17.0.1 / KDE 5.9.5 / Linux 4.9.30

### Bug/Feature

Laggy playback. Audio stops for like 0.5s, but the playing still continues as the audio resumes after where it stopped. Maybe an option for real-time playback like in VLC ?

Thank you very much for this player, this is exactly what I was looking for.

**Comment by gnumdk** [comment]
Never seen such issue but not a lollypop issue, somewhere in manjaro/pulseaudio/gstreamer

**Comment by pciavald** [comment]
Will look into it, thank you !
