### ISSUE TITLE
Requests made at first start

### ISSUE THREAD

**Issue by TgA22** [gnumdk/lollypop#1107]
At first start,  I have my music library in the default XDG folder. Lollypop will start indexing my music library. Can you provide a quick list of the data which will be transmitted to the tech giants? I noticed DNS lookups for Google, Apple, Deezer, Spotify, Audio scrobbler.

I just want to know if the full list of my songs has been transfered to them and if yes what information more precisely. I know that clicking on a song provokes a search for the cover on spotify, but is that all or is there more?

**Comment by gnumdk** [comment]
It's a good idea, as on first start Lollypop show an empty window, I can show a dialog allowing to enable network access.

**Comment by TgA22** [comment]
Thank you for responding. Can you tell me if the list of all my songs is transmitted to external servers (Google, Apple, Deezer, Spotify, Audio scrobbler, ...) or not?

**Comment by TgA22** [comment]
Why would you transmit the list of ALL the songs? I understand querying the cover when I click on a song, but transmitting the list of ALL my songs instantly at first start is far too harsh.

**Comment by gnumdk** [comment]
No, Lollypop just transmit album + artist when cover is missing and only when cover is missing (not in folder and not in tags) ;)
