### ISSUE TITLE
Sync playlists over network with syncthing

### ISSUE THREAD

**Issue by tepf** [gnumdk/lollypop#1109]
I saw that Lollypop supports syncing with Android over MTP. But I'm using syncthing to sync over the network automatically in the background. Is there a way add Lollypop playlists to the files that are being synced?

Right now playlists seem to be stored in a sqlite database. Would it be possible to have playlist files that will be automatically imported and exported on startup/edit? Or maybe sync the whole database (I don't know which database android uses)

**Comment by gnumdk** [comment]
Yes, you can emulate a device with -e option. Device is in /tmp/android, then mount --bind or ln -s this dir to your network device.

**Comment by gnumdk** [comment]
And this will export playlists ;)
