### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#111]
GEN    he/
Error: cannot open XML file C/index.page
Makefile:530: recipe for target 'sv/sv.po' failed
make[2]: *** [sv/sv.po] Error 1

**Comment by illwieckz** [comment]
I got the same bug this morning, to workaround that I removed the `help` directory name on the `SUBDIRS =` line of the generated `Makefile`:

```diff
< SUBDIRS = src data po help
> SUBDIRS = src data po
```

I don't know what is the problem but doing that allows to compile Lollypop before the bug is fixed. :wink:

**Comment by gnumdk** [comment]
Is this zone fixes?

**Comment by illwieckz** [comment]
last commit fixed that, thanks.
