### ISSUE TITLE
Playing stop with certains conditions

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#1110]
### Environment
- Lollypop version: 0.9.239
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Fedora 26 Alpha

### Bug
At first run, with non-random reading and non reiterations playing modes, if I click on a song on the album, the song is played then play is stopped.
This doesn't happen if I click on play button on the album: every songs are played.

**Comment by gnumdk** [comment]
Wanted behaviour with "No repeat" on.
