### ISSUE TITLE
Missing translatable="yes" for label in data/SettingsDialog.ui

### ISSUE THREAD

**Issue by chpii** [gnumdk/lollypop#1113]
[`<property name="label">Last.fm</property>`](https://github.com/gnumdk/lollypop/blob/e2c71ef103a485fced4e935e0448fb78cd509a2f/data/SettingsDialog.ui#L1017)
[`<property name="label">Web</property>`](https://github.com/gnumdk/lollypop/blob/e2c71ef103a485fced4e935e0448fb78cd509a2f/data/SettingsDialog.ui#L1127)

![issue 1113](https://user-images.githubusercontent.com/7461424/26987163-22a9d53e-4d53-11e7-8fc2-d1f8a5dc516f.png)

Only care for "Web". "Last.fm" can be made translatable too as one in [ArtistInfo.ui](https://github.com/gnumdk/lollypop/blob/e2c71ef103a485fced4e935e0448fb78cd509a2f/data/ArtistInfo.ui#L71) just in case.

**Comment by gnumdk** [comment]
Why Last.fm should be translatable, I do not translate this to "Dernière.fm" in french.
