### ISSUE TITLE
Select first lyrics song

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#1116]
### Feature
Lyrics panel display a list of possible songs.
I always select first song.
Can it be automatically done?

**Comment by Pointedstick** [comment]
Yes please.

**Comment by gnumdk** [comment]
It's not possible because direct access is broken for language with accent. I can fix it for French (as I know how it works) but not for all languages... So search is not an option.

**Comment by gnumdk** [comment]
Tried but fail. Works most of the time but for songs with strange char, it fails.

Sorry :-1:
