### ISSUE TITLE
Manual rating are not written into tags

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1117]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.22.11
- GNU/Linux distribution: Kubuntu 17.04

### Bug/Feature
Lollypop does not appear to write ratings into files' tags. I do have "Save changes to files" turned on.

I understand that this is probably deliberate, due to the lack of a standardized method of storing rating information. However, there is a rough _de facto_ standard using the Popularimeter tag: https://en.wikipedia.org/wiki/ID3#ID3v2_rating_tag_issue

I can't see what the problem would be in writing rating information into the Popularimeter tags. The worst thing to happen would be that ratings wouldn't show up in other players, which already happens today.

Stars could be written as described in the above Wikipedia link, and hearts could simply be written as five stars.

**Comment by gnumdk** [comment]
Rating is written to tags #775

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop-portal/issues/1

**Comment by gnumdk** [comment]
So you may be missing kid3-cli or lollypop-portal.

**Comment by Pointedstick** [comment]
Nope, I already have both of those packages installed:

```
$ sudo apt install kid3-cli lollypop-portal
[sudo] password for nate: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
kid3-cli is already the newest version (3.4.4-1).
lollypop-portal is already the newest version (0.9.1-1ppa1ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by gnumdk** [comment]
Can you test setting rate with kid3-cli ?
kid3-cli -c "set POPM 192"  /path/to/file

**Comment by Pointedstick** [comment]
Effect:
- On a song that I've manually rated with any combination of hearts and stars: no effect
- On a song that has an automatic star rating determined by Lollypop: the star count is reset to zero

So it's definitely doing something. I think the bug is that manually rating your songs with stars or hearts seems to be saved elsewhere rather than in the popularimeter tag.

**Comment by Pointedstick** [comment]
Hello?

**Comment by Pointedstick** [comment]
@gnumdk Hello?

**Comment by gnumdk** [comment]
Looking at code, it's not working with flatpak! I need to fix this by adding a function to lollypop-portal.

For your bug, will do some testing.

**Comment by Pointedstick** [comment]
Great, thanks! I'm not using the flatpak version though; I'm using your Ubuntu PPA.

**Comment by gnumdk** [comment]
Should be fixed, Lollypop is not checking anymore for kid3-cli and ask lollypop-portal.
You will have to wait next release ;)
