### ISSUE TITLE
The option "Quit" isn't showed in spanish menu

### ISSUE THREAD

**Issue by simonbcn** [gnumdk/lollypop#1118]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: GNOME Shell 3.24.2 / GTK+ 3.22.15-1
- GNU/Linux distribution: Arch

### Bug/Feature
The option "_Quit_" isn't showed in spanish menu, it should be "_Quitar_":

![salida](https://user-images.githubusercontent.com/428231/27252506-867d84e4-5360-11e7-9ec5-d6e155a4cc9d.jpg)

**Comment by gnumdk** [comment]
It's an issue in your GNOME Shell extension, it's translated Salir here... And you already have a Salir entry in this menu...

**Comment by simonbcn** [comment]
The right translation for "_Quit_" in Spanish is "_Quitar_".

**Comment by gnumdk** [comment]
Please contact spanish team on Transifex. Or just ask to be a contributor, will allow you to fix it.
