### ISSUE TITLE
current playing popover truncated at the main window size

### ISSUE THREAD

**Issue by illwieckz** [gnumdk/lollypop#112]
Hi, if the “current playing” popover is larger than the main window size, this popover is truncated:

Depending to the main window size, it truncates alternatively to the left or to the right

[![truncated popover](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_112/20150514-115632.lollypop.png)](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_112/20150514-115632.lollypop.png)

[![truncated popover](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_112/20150514-115647.lollypop.png)](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_112/20150514-115647.lollypop.png)

Perhaps it's not your fault and is a bug on GTK's side, but perhaps you can ensure all the text widgets can be truncated if they are too long to fit in the main window size.

**Comment by gnumdk** [comment]
Gtk bug fixed in gtk 3.16
