### ISSUE TITLE
Swap album title <-> album artist in cover view

### ISSUE THREAD

**Issue by mray** [gnumdk/lollypop#1120]
To me it makes sense to typographically support the visual order of albums.
A grid of album covers highlighting the *Album* while being sorted by *Artist* is harder to read as it makes it harder to group artists and their albums.
I also think both lines should get linked to the artist view as in #1100 .

Here is a small scale example from the "All artists" list:

![image](https://user-images.githubusercontent.com/164785/27255947-43238ccc-53a9-11e7-89ee-5e71e933b71e.png)

**Comment by gnumdk** [comment]
No it does not make sense for me. And for GNOME Music devs and Itunes devs ;)
