### ISSUE TITLE
Cinnamon Sound applet Time bar doesn't work

### ISSUE THREAD

**Issue by Vencorr** [gnumdk/lollypop#1121]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.18.9-1ubuntu3.3
- GNU/Linux distribution: Linux Mint 18.2
- Desktop Environment: Cinnamon 3.4

### Bug/Feature
When using the sound applet on Cinnamon, there is a music player built in which shows you the time using a bar, gives you options to control the music player, as well as allow you to close and bring up the music player from behind windows. The Time bar fails to work, and bringing up the window fails to work as well.
This is the cinnamon sound applet menu when playing music from Lollypop:
![b786d](https://user-images.githubusercontent.com/23224476/27264142-3d7e6a18-543e-11e7-9e06-feecdd023bea.png)
As you can see, the time bar shows that it is at the beginning of the song, however, it is actually in the middle, as you can see from this image:
![c3e12](https://user-images.githubusercontent.com/23224476/27264149-61f7b6b0-543e-11e7-8a74-794c33d30eb0.png)
It only seems to update sometimes when you play/pause it. This bug only happens most of the time. Sometimes, it works just fine and is perfectly fine updating the time bar.
Here is the command output when running lollypop in debug mode:
https://pastebin.com/1XhXc9d3
Do not judge my music taste, please.

Thank you and have a good day.

**Comment by gnumdk** [comment]
Bug is in applet as it works perfectly with Gnome shell applet.

**Comment by Vencorr** [comment]
But any other media player that works well with Gnome shell applet works fine with Cinnamon Sound applet. Sorry if I am wrong, but I don't think this has anything to do with the applet. Again, sorry if I am wrong. I don't mean to sound rude and put the blame on your application. I am just saying it doesn't seem plausible that it is the applet. I will run some tests however and come back with outputs and information if that helps. If it does appear to be the applets fault, I will submit a bug report to the Mint developers.

**Comment by gnumdk** [comment]
BTW, I do not have time to install cinnamon so if you get information or a patch, open a new issue.
