### ISSUE TITLE
Make full async DBus calls

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1123]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Fedora 25

### Bug/Feature
Sometimes the window creation is delayed by several seconds. This is for example cumbersome at system startup, when I switch from workspace to workspace and open associated programs. Then I have to wait about 5…10 seconds just for Lollypop popping up, so that I can switch to the next workspace. Could this be done earlier?

**Comment by gnumdk** [comment]
There  is no delay

**Comment by gnumdk** [comment]
I think that there is an issue somewhere in your session making DBus stalled.

I need to move code to full async DBus like I've done in Eolie.

**Comment by fbruetting** [comment]
I have no understandig of DBus, but this delay doesn't occur every time, just sometimes. Thanks for looking at it!

**Comment by gnumdk** [comment]
@fbruetting  All DBus calls are now fully async, can you test with current master?

**Comment by fbruetting** [comment]
Sorry for the delay, I’ll check this weekend!
