### ISSUE TITLE
Feature Request: Add separate section for audiobooks

### ISSUE THREAD

**Issue by ahahn94** [gnumdk/lollypop#1124]
Hi.
There are sections for popular or recently added albums.
Why not add a section for audiobooks?
At the moment, if you have audiobooks in your library, they will be included in party mixes and they will bloat up the "all artists" view.
So, maybe add the possibility to set a tag that indicates if an album is an audiobook in the album properties. Maybe just a small symbol like the star icon for the favourite albums.

Thank you in advance for any feedback on this request!
You are doing a great job and I love using lollypop on ubuntu.

**Comment by gnumdk** [comment]
Just put an Audiobook tag for genres?

**Comment by ahahn94** [comment]
Hi.
I did not know that there was an option to enable a list of genres in the main window.
At least for the moment, using Audiobook as the genre is a good workaround.
Thank you very much!
