### ISSUE TITLE
Picking a single track with the "+" button clears the playing queue

### ISSUE THREAD

**Issue by mjourdan** [gnumdk/lollypop#1125]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.238
- GNOME/GTK+ versions: 3.22
- GNU/Linux distribution: Fedora 25

#### Use case

I have 3 albums listed in the "playing now" dropdown. I want to add a single track to the list. So I select an artist in the left menu, and pick a track with the "+" button.

#### Expected behavior

The "playing now" list is expanded to list all the selected tracks (each one from the three first albums, and the one we just picked up).

#### Actual behavior

The list is cleared and replaced with the track I picked up.

**Comment by gnumdk** [comment]
By design

**Comment by mjourdan** [comment]
So, the user is supposed to know when she clicks "+", sometimes the queue will grow, sometimes the queue will flush?

Actually the queue is filled in with the "album" queue again while playing the added track. So I guess (correct me if I am wrong) your intent here is "+" could either mean "play this song right after" or "add this album to the end of the queue".

If I understood correctly, this is a useful feature set but the way it is offered to users is a bit confusing I think. Would you agree to take a look if I provided you with mockups aiming to provide easier handling of the queue?

**Comment by gnumdk** [comment]
You are doing a mistake. The "+" on album is not the queue!

Lollypop is designed for albums playback so it just add an album to current playlist. 

The "+" on track is the queue and it just bypass current playlist temporaly, It does not destroy it.
