### ISSUE TITLE
Prev/Next controls should relate to the playing queue, not to the album I am just browsing

### ISSUE THREAD

**Issue by mjourdan** [gnumdk/lollypop#1126]
### Environment
- Lollypop version: 0.9.238
- GNOME/GTK+ versions: 3.22
- GNU/Linux distribution: Fedora 25

#### Use case

This happens after #1125.
 
Trying to get back to the three album list in the "playing now" dropdown, it seems I made a mistake and the music switched abruptly to another track from an other album. I want to go back to the track I was listening, so I click "|<<".

#### Expected behavior

What I was listening is played again.

#### Actual behavior

A track from the current album is played.

**Comment by gnumdk** [comment]
By design
