### ISSUE TITLE
Clicking on the artist name in the "recently played" should lead to the full list of this artists' albums

### ISSUE THREAD

**Issue by mjourdan** [gnumdk/lollypop#1127]
### Environment
- Lollypop version: 0.9.238
- GNOME/GTK+ versions: 3.22
- GNU/Linux distribution: Fedora 25

#### Use case

This happens after #1126.

I look for a way to pursue the playing of the album I was listening. In the left panel, I select "playlist" then "recently played". I try to click both the artist name and album cover.

#### Expected behavior

I arrive to the full album view, as if I had directly picked up the artist in the left panel.

#### Actual behavior

The first track below the artist name si played but the view doesn't switch.

**Comment by gnumdk** [comment]
#1100 Will do the same for playlist view.
