### ISSUE TITLE
"all the artists" actually shows all the albums and asks to choose between "play now" and "play the albums"

### ISSUE THREAD

**Issue by mjourdan** [gnumdk/lollypop#1128]
### Environment
- Lollypop version: 0.9.238
- GNOME/GTK+ versions: 3.22
- GNU/Linux distribution: Fedora 25

#### Use case

In the left panel, I select "all the artists". A cover of all the albums appear. I hover a cover, which reveals control buttons.

#### Expected behavior 

Either:

1. the menu entry is called "all the albums" and simple controls to play immediately or add the album to a playlist for later.
2. the menu entry is called "all the artists". Photos of the artists are shown in the main view, instead of album covers.
3. the menu entry is called "all the artists". The list of artists names with photos is displayed in a second column.

#### Actual behavior

Having both "all the artists" and the actual list of all the artists in the left column feels weird. 

In the main panel, two buttons appear to do apparently the same thing: "play now" and "play the albums", which is confusing because it is not obvious what the other albums are when I pick up one from the grid.

**Comment by gnumdk** [comment]
The menu is called "All the album" if you disable genre browsing.

But for me it have to be "All the artist" because it show the artist view. Like when you click a genre, it shows all albums from genre, here it shows all albums from all artists.

BTW, by design.
