### ISSUE TITLE
It should be possible to append an album to a playlist or to the current queue in the same way

### ISSUE THREAD

**Issue by mjourdan** [gnumdk/lollypop#1129]
### Environment
- Lollypop version: 0.9.238
- GNOME/GTK+ versions: 3.22
- GNU/Linux distribution: Fedora 25

#### Use case

I wan't to add an album to a playlist. I click the "+" button.

#### Expected behavior

I can append the album to the current queue, to a saved playlist, or to a new playlist.

#### Actual behavior

I can append the album to the current queue.

**Comment by gnumdk** [comment]
Already implemented in album menu or in album sliding widget "<"
