### ISSUE TITLE
`artist_id` key from `albums` table` is not updated when the `Album/Performer` tag is removed from files

### ISSUE THREAD

**Issue by illwieckz** [gnumdk/lollypop#113]
Hi, if a file has a bad `Album/Performer` ¹ tag and was registered in the database with this wrong value, while deleting the bad tag, the Album still remains classified with this wrong `Album/Performer` tag.

It appears that the `artist_id` key from `albums` table is not updated when the `Album/Performer` tag is removed from files.
____
¹ The `Album/Performer` is not the Album name, not the Track's Performer name, the Album’s Performer name who could be different to the Track’s Performer name.

**Comment by gnumdk** [comment]
Strange, will give a look

**Comment by gnumdk** [comment]
Deleting this tag should create another album with track's performer as album artist or as a compilation's if another track exist with same album name and with no album artist.

Lollypop doesn't update tags, it removes the track and add it again.

**Comment by illwieckz** [comment]
Currently, I have a database with different metadata than in files, all wrong metadata are album artists metadata (from albums with wrong album artists metadata that are fixed now, or albums with incomplete album artists metadata (see #114) that are fixed now). I can read the sqlite db and read wrong metadata associations while I read the good metadata in the file at the same time.

**Comment by illwieckz** [comment]
The `tracks` and `track_artists` tables seems good, the `albums` table not. It seems that the previously written `artist_id` is not removed if a file from this album had this tag in the past but does not have this tag when the file is re-added after modification.

**Comment by illwieckz** [comment]
I agree that removing an album artist is more complex than adding a album artist, to add an album artist, only one track with album artist metadata is needed, but to remove an album artist, you must check all tracks from this album to check if no one have an album artist metadata anymore.

**Comment by gnumdk** [comment]
I don't think the bug is here.
Reset your db in dconf editor: db version key

After complete scan finish, if tags are correct, there is a bug...

If they are wrong, install puddletag and check you don't have more than one tag frame: id3, ape,...

**Comment by illwieckz** [comment]
OK, because I have another strange bug which is similar: after renaming an artist (from “_Erroll GARNER_” to “_Erroll Garner_” my album is now known as a compilation, but all the tags are ok:

[![compilation](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_113/20150514-174748.lollypop.png)](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_113/20150514-174748.lollypop.png)

```
$ for track in *.flac; do mediainfo "${track}" | grep 'Album\|Performer\|Track'; printf '\n'; done
Album                                    : Solitaire
Track name                               : I'll Never Smile Again
Track name/Position                      : 01
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : Then You've Never Been Blue
Track name/Position                      : 02
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : It's the Talk of the Town
Track name/Position                      : 03
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : Solitaire
Track name/Position                      : 04
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : A Cottage for Sale
Track name/Position                      : 05
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : That Old Feeling
Track name/Position                      : 06
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : Over the Rainbow
Track name/Position                      : 07
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : Yesterdays
Track name/Position                      : 08
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : Who?
Track name/Position                      : 09
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : When a Gypsy Makes His Violin Cry
Track name/Position                      : 10
Track name/Total                         : 11
Performer                                : Erroll Garner

Album                                    : Solitaire
Track name                               : Salud Segovia
Track name/Position                      : 11
Track name/Total                         : 11
Performer                                : Erroll Garner
```

I will try the dconf db reset, I will check the tag frames but my music is from CD I rip myself, so there is commonly only mistakes I do myself…

**Comment by illwieckz** [comment]
OK, resetting the db fixes the remaining album artist and the wrong compilation classification. Thanks for the tip.

**Comment by gnumdk** [comment]
So there is a bug ...
What version?

**Comment by illwieckz** [comment]
```
branch: master
commit: 3adb856dcd22f89375339e2fa52bde60dcef5c26
Date:   Thu May 14 09:18:24 2015 +0200
```

**Comment by gnumdk** [comment]
Can't reproduce this bug.

Can you give me more informations?

All tags before and after modification.

**Comment by gnumdk** [comment]
Reopen this one if you are able to reproduce the bug:
- Send me ~/.local/share/lollypop/lollypop.db by email
- Send me an exemple music file by email
