### ISSUE TITLE
Meaningless buttons make me feel I'm not in control

### ISSUE THREAD

**Issue by mjourdan** [gnumdk/lollypop#1130]
### Environment
- Lollypop version: 0.9.238
- GNOME/GTK+ versions: 3.22
- GNU/Linux distribution: Fedora 25

#### Use case

I click an artist in the left menu.

#### Expected behavior

I feel in control.

#### Actual behavior

Meaningless icons and no tooltip. I can guess the buttons to the left. For those to the right, I can click but I have no idea of what I'm doing here.

**Comment by gnumdk** [comment]
Oh yes, missing tooltips!

**Comment by gnumdk** [comment]
In fact, tooltips are here, it's a GTK bug. Issue between tooltips and Gtk.Overlay.

If you have time to report upstream, paste URI here and ping me, I will add more information to your bug report.

**Comment by mjourdan** [comment]
Indeed @gnumdk, it seems like there already is a couple of reports against gtk+:

- https://bugzilla.gnome.org/show_bug.cgi?id=730839
- https://bugzilla.gnome.org/show_bug.cgi?id=730839
