### ISSUE TITLE
Offer to play different albums instead of looping over the same one

### ISSUE THREAD

**Issue by mjourdan** [gnumdk/lollypop#1131]
### Environment
- Lollypop version: 0.9.238
- GNOME/GTK+ versions: 3.22
- GNU/Linux distribution: Fedora 25

#### Use case

An album has finished.

#### Expected behavior

Some other album starts to be played. The album should probably be of the same genre, and shouldn't have been played for too short.

#### Actual results

The same album is played again, which is annoying because it is unlikely I want to keep listening to the same thing.

**Comment by gnumdk** [comment]
Just  use the "play all albums" button and it will do this behaviour.

Will not implement this.
