### ISSUE TITLE
Debian and Ubuntu packages

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1133]
Debian 9 Stretch is now out with GTK 3.22 . Are there any remaining blockers to making Lollypop available in the Stretch repos?

It would be great to be able to get Lollypop available in Debian Stable and Ubuntu without a PPA.

**Comment by gnumdk** [comment]
Check with Debian maintainers...

**Comment by gnumdk** [comment]
And there was no blockers to make Lollypop available in Stretch... Debian and Ubuntu don't care about Lollypop for now. Only Fedora and OpenSUSE package it.

**Comment by LocutusOfBorg** [comment]
Debian developer here, if you want to provide packaging I can check/sponsor it :)

**Comment by gnumdk** [comment]
@LocutusOfBorg I do not have time (and skills) to provide packaging ;) My ppa package is just a simple and stupid package.

**Comment by LocutusOfBorg** [comment]
well, I can improve it if you want to maintain it officially in Debian
