### ISSUE TITLE
built-in id3 tag editor?

### ISSUE THREAD

**Issue by coxackie** [gnumdk/lollypop#1134]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Arch

### Bug/Feature

I installed Lollypop and find it a really great player for GNOME. I was wondering whether you are thinking of including a built-in id3 tag editor in the future, like what Rhythmbox has. Right now whenever I have to edit tags I have to go to EasyTag - if a built-in editor was available, especially in conjunction with the great artwork fetch system you have, EasyTag would be rendered obsolete for me. (By the way, why do you use kid3 for saving tags, since its UI is in Qt?)

 Thanks a lot for all your work!

**Comment by gnumdk** [comment]
I'm using kid3-cli and not kid3-qt.

And, if you install lollypop-portal, easytag will be available in Lollypop menus.

**Comment by gnumdk** [comment]
WONTFIX.

**Comment by coxackie** [comment]
OK- thanks a lot. I do have flatpak installed, and it does take me to easytag automatically, indeed. I was thinking of a more integrated way, but I can understand that this is not something you care to spend time at the moment.

**Comment by gnumdk** [comment]
>it does take me to easytag automatically
Because you need to install lollypop-portal
