### ISSUE TITLE
Confused about the API key

### ISSUE THREAD

**Issue by terzag** [gnumdk/lollypop#1137]
I've installed Lollypop on Ubuntu GNOME 17.04 with the PPA (Lollypop 0.9.240 / GNOME 3.24).

It seems to work well but whenever I open the preferences, I get a system notification saying that Google Web Services needs a custom API key. In the prefs → Web → Google, it's also mentioned that I need an API key or some quota will be reached quickly.

The thing is, there is *already* an API key set and it wasn't by me. So, I'm confused:
- if the current key (set by the developer?) is valid, why do I get this notification from GNOME Shell whenever I open the preferences window?
- do I need to setup and enter a personal API key for some reason (like the default one isn't supposed to be used by every Lollypop user and its quota is not infinite)?

Lollypop seems to display my album covers just fine, so I'm not sure if I need to do something.

**Comment by gnumdk** [comment]
No, it's not needed, by default Lollypop fallback to a manual method. But I prefer telling users to use Google API.

The API by default is not set in Gtk.Entry, it's just a placeholder.

**Comment by terzag** [comment]
> The API by default is not set in Gtk.Entry, it's just a placeholder.
Sorry, I'm still confused: do you mean that the key set by default is just a random string that is not a valid API key?

**Comment by gnumdk** [comment]
It's an example.

**Comment by terzag** [comment]
Ok, thanks for the confirmation.
