### ISSUE TITLE
High Memory Use

### ISSUE THREAD

**Issue by pschichtel** [gnumdk/lollypop#1138]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.24.2 on X11
- GNU/Linux distribution: Archlinux Testing

### Bug/Feature
I saw memory usage of over 1gig yesterday. My media collection contains around 12k songs, >95% of encoded as FLAC and all songs have an album cover embedded. The songs had already been imported way before I saw the high memory usage (with restarts in between). Starting Lollypop today did not have the effec (around 85mb, which seems reasonable by current standards).

**Comment by gnumdk** [comment]
Will give a look but i you load "All artist" view with many covers, it quite normal. Python release memory when it wants.

**Comment by gnumdk** [comment]
Ok, my collection contains 21k songs and when loading "all artists" view, I only get 120 Mio of used memory.

Will investigate, if you are able to reproduce with some steps ;)

**Comment by enaut** [comment]
Hey, just my stats: 158 Artists, 1420 albums, 15845 tracks

when I open the "all artists" view the memory is first relatively low, but it grows up to ~ 700MB by scrolling down I can see how many covers have already been loaded. 700MB is when all has been loaded

**Comment by gnumdk** [comment]
Yes, but it can depends on your cover size :-)

**Comment by jeims17** [comment]
I have 0.5tb tb of music, so when i put on all artists view (all the songs
have cover) it becomes too slow, ls the only reason why i don't use
Lollipop (too much), iTunes on Windows (😝) Is more efficiently than
Lollipop in this sense.

**Comment by enaut** [comment]
If I understand it correctly Lollypop loads all artist covers when showing the all artist view. For me this leads to a second freeze of lollypop when first loading that view.

What it should do:
- [ ] load only the ones displayed

I commented that my Lollypop is taking 700 M when looking at the all artists view - well that is only partially true. When the cover thumbnail cache is empty and it has to generate all the covers then it's using the huge amount of memory. However when everything has been generated it only uses 80 M.
I sometimes have really huge cover images like 10 to 30 M I guess that Lollypop fails to unload those after generating the small thumbnail. That theory seems to be consistent with @pschichtel OP problem.

Second problem:
 - [ ] unload media art after generating thumbnail

**Comment by gnumdk** [comment]
>load only the ones displayed

I hate this. The question is more about slow Lollypop when in this view, does not happen here :-1:

**Comment by gnumdk** [comment]
https://stackoverflow.com/a/45840340

**Comment by gnumdk** [comment]
@jeims17 Are you sure it's slow even if cache is builded (not on first load after music scan)?
