### ISSUE TITLE
Notifications: no artwork

### ISSUE THREAD

**Issue by Feichtmeier** [gnumdk/lollypop#1139]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: Lollypop 0.9.240
- GNOME/GTK+ versions: 3.20
- GNU/Linux distribution: Ubuntu 16.04

### Bug/Feature
The notifications work but no artwork is shown in the notifications only the lollypop logo
![screenshot from 2017-06-26 21-58-51](https://user-images.githubusercontent.com/15329494/27557673-af62cf3e-5aba-11e7-9bdb-4a06d5409581.png)

**Comment by gnumdk** [comment]
Gnome Shell does not use artwork.

**Comment by GuilloOme** [comment]
> Gnome Shell does not use artwork.
What do you mean? 
Notifications can have any type of image attach to it, so why not a artwork?

**Comment by gnumdk** [comment]
That Gnome Shell doesn't use artwork but application icon. There is no notification with artwork on Gnome.

**Comment by gnumdk** [comment]
Oh no, I remember, in GNOME 3.22 (3.24), icon is way to small for showing artwork so I disabled it. Here the real reason, but previous code was a hack as I was setting artwork as icon because Gnome Shell ignore artwork from spec.

**Comment by gnumdk** [comment]
On more, the code is only disabled for GNOME.

**Comment by Feichtmeier** [comment]
Oh okay, that is sad. Other applications have enabled "that" someone, like GPMDP 
![screenshot from 2017-06-29 13-33-56](https://user-images.githubusercontent.com/15329494/27685704-ae55d048-5ccf-11e7-84f2-c2cf35f9b3ad.png)
![screenshot from 2017-06-29 13-34-57](https://user-images.githubusercontent.com/15329494/27685721-c8496a00-5ccf-11e7-80bf-1e68d9e579aa.png)

**Comment by gnumdk** [comment]
Yes but it looks ugly with last GNOME release. Using a 16x16px icon.
