### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1140]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.22.2
- GNU/Linux distribution: Fedora 25

### Bug
Here Lollypop sometimes runs with ~2-3% of one core of my Skylake i7 when playing local or streaming music, but hits ~15% at at least 50% of the time. If I pause playback, Lollypop still produces >10% load.
 Would be nice if this could be fixed, so that my fan doesn't run as often and my battery lasts longer! :)

**Comment by gnumdk** [comment]
Does not happen here...

**Comment by gnumdk** [comment]
Are you sure Lollypop is not loading the current view while you see this?

**Comment by Pointedstick** [comment]
FWIW, I see totally normal-ish usage on my Kaby Lake i7 with 0.9.240: While playing, Lollypop uses 1%, and PulseAudio uses 1-2%. Total 2-3%, which seems reasonable.

**Comment by gnumdk** [comment]
@fbruetting Nividia drivers?

**Comment by Pointedstick** [comment]
Intel GPU + OSS drivers for me.

**Comment by gnumdk** [comment]
No more information, can't reproduce.

**Comment by fbruetting** [comment]
Got a second Nvidia GPU (Nouveau), but not running – just the Intel GPU is used. I’ll install Fedora 26 this weekend, and check this again.

**Comment by fbruetting** [comment]
### Environment (new)
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24.2
- GNU/Linux distribution: Fedora 26

Bug still occurrs, I basically did nothing else than a complete new installation of Fedora 26 and Lollypop from Flathub. I even didn't import my old DB folder.

Here some log while Lollypop should do nothing at all (after using it a few days):
```
$ top | grep python
 7459 frank     20   0 3657596 274476  50572 S  14,0  1,7   4:37.94 python3                                                                                                                                        
 7459 frank     20   0 3657340 274220  50572 S  13,3  1,7   4:38.34 python3                                                                                                                                        
 7459 frank     20   0 3657340 274220  50572 S  13,0  1,7   4:38.73 python3                                                                                                                                        
 7459 frank     20   0 3657340 274220  50572 S  12,3  1,7   4:39.10 python3                                                                                                                                        
 7459 frank     20   0 3657340 274220  50572 S   6,6  1,7   4:39.30 python3                                                                                                                                        
 7459 frank     20   0 3657340 274220  50572 S   0,3  1,7   4:39.31 python3                                                                                                                                        
 7459 frank     20   0 3657340 274220  50572 S   0,7  1,7   4:39.33 python3                                                                                                                                        
 7459 frank     20   0 3657084 273964  50572 S  20,5  1,7   4:39.95 python3                                                                                                                                        
 7459 frank     20   0 3657084 273964  50572 S  15,0  1,7   4:40.40 python3                                                                                                                                        
 7459 frank     20   0 3657084 274028  50572 S  12,0  1,7   4:40.76 python3                                                                                                                                        
 7459 frank     20   0 3658364 275312  50572 S  19,3  1,7   4:41.34 python3                                                                                                                                        
 7459 frank     20   0 3657852 274900  50572 S  18,3  1,7   4:41.89 python3                                                                                                                                        
 7459 frank     20   0 3657852 274900  50572 S   8,6  1,7   4:42.15 python3                                                                                                                                        
 7459 frank     20   0 3657852 274900  50572 S   1,7  1,7   4:42.20 python3                                                                                                                                        
 7459 frank     20   0 3657852 274964  50572 S  15,6  1,7   4:42.67 python3                                                                                                                                        
 7459 frank     20   0 3657852 274964  50572 S  16,9  1,7   4:43.18 python3                                                                                                                                        
 7459 frank     20   0 3657852 274964  50572 S  15,3  1,7   4:43.64 python3                                                                                                                                        
 7459 frank     20   0 3657852 274964  50572 S  15,6  1,7   4:44.11 python3
```
I then deleted ~/.var/app/org.gnome.Lollypop, then the CPU usage stays at 2…10 %. So it seems to me, that the load goes up with a more filled database, maybe.


The only thing that occurrs, is that I get a notification about a missing Opus GStreamer plugin is missing, but I don’t believe that this affects the CPU usage.

// htop lists Lollypop as `python3 /abb/bin/lollypop`, in top it’s just `python3` can this be changed to `Lollypop` somehow by the way?

**Comment by fbruetting** [comment]
Bug still present, Lollypop does absolutely nothing and is not even in the foreground and still produces a load of about 4-8 %.

**Comment by gnumdk** [comment]
Yes, but bug is not in Lollypop.

**Comment by gnumdk** [comment]
Or you have charts activated.

**Comment by fbruetting** [comment]
Hm ok… I wasn’t in the charts, just have internet search active. I’ll test it on Debian tomorrow (currently Fedora).

**Comment by gnumdk** [comment]
If you have charts activated, CPU usage is normal as Lollypop is updating charts and it's quite long...

**Comment by fbruetting** [comment]
To be sure, when you say „charts activated“ you mean being in the charts view, right? Because I couldn’t find anything about charts in the settings.

**Comment by fbruetting** [comment]
Ok you’re right – this was just due to having charts activated. But it’s suboptimal for laptop users to have this kind of load active by default. :/
