### ISSUE TITLE
improve cover art support

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1141]
as the title says, cover art support should be improved...sometimes cover arts get messed up or they are simply blank even if a cover is embedded...lot of time for example happens that if i have record A and record B and i download the cover for record A via lollypop, lollypop is showning me the cover on record B...so support should be improved since is a little pain to adjust covers with lollypop... :)

**Comment by gnumdk** [comment]
If record A and record B are is same folder and you set cover for A, then it will set a A.jpg image filename in folder. But as record B looks for first available image in folder, it will be shown for record B too. But if you set cover for record B, then it will add a B.jpg image file in folder and all is ok.

If the issue is that Lollypop search for first available image in folder, it will not be fixed. Just clean up your music collection to have separate folders.

**Comment by legacychimera247** [comment]
they are in the same folder like Artist folder A > album folder A - album folder B - album folder c > artist folder B > album folder A - album folder B and so on...

the issue is just lot of times covers are messed up, for example if i have a gary numan folder and inside 4 album folders, album 2 may have album 3 cover or sometimes be empty and so on
![schermata da 2017-07-03 08-54-24](https://user-images.githubusercontent.com/22254556/27781227-51dbe856-5fcd-11e7-8633-3c656b11a0b3.png) as you can see from the screen, i just set cover art for the album "club 2k" which is empty instead, and then set the cover for "absolute dance" which has club 2k cover...all the songs are in different folders...

**Comment by gnumdk** [comment]
Are the folders read only?

**Comment by gnumdk** [comment]
Send me your lollypop.db by email.

**Comment by legacychimera247** [comment]
read and write...and by the way...the last album, hit mania, is empty but prior to exit and reopen lollypop it had a cover...anyway will send you lollypop db :)

**Comment by gnumdk** [comment]
1383|Club 2K, Volume 2|0|2001|file:///home/luca247/Musica/jessica|0|0|0|0
sqlite> select * from albums where name like "%Absolute Dance%";
1411|Absolute Dance: Move Your Body! 2003|0|2003|file:///home/luca247/Musica/jessica|0|0|0|0

Looks like there are in the same folder.

**Comment by legacychimera247** [comment]
yes but as you may see there are other songs in different folders that have the same problem...

you said anway that if i have a folder with songs in it and i search for cover for track 1 then every song will get cover A, if i select the ntrack 2 then track 2 will get a cover B and so on...it's ok that way...simply lot of the time cover arts get messed up or blank...that's the problem...  for example if i set cover for track 2 suddenly cover for tracks A became blank...

**Comment by gnumdk** [comment]
You can't set cover for track, you wan to say album?

**Comment by legacychimera247** [comment]
yeah exactly :)

**Comment by gnumdk** [comment]
As it works perfectly here with your collection, I think I know what is happening :)
Is "save to  tags" on ?

**Comment by legacychimera247** [comment]
yes it's on

**Comment by gnumdk** [comment]
Ok, here the issue :)

**Comment by gnumdk** [comment]
Can you test with master?

**Comment by legacychimera247** [comment]
what do you mean by master?

**Comment by gnumdk** [comment]
Current dev version.

**Comment by legacychimera247** [comment]
sure...how to install it on fedora 25?need to follow the instructions on the git page?

**Comment by gnumdk** [comment]
Yes :)

**Comment by legacychimera247** [comment]
will do and report but it will take a little :)

**Comment by gnumdk** [comment]
Hmm, ok, so don't, I need to release now so...

**Comment by legacychimera247** [comment]
oh ok...

**Comment by gnumdk** [comment]
0.9.242 is out ;)

**Comment by legacychimera247** [comment]
thanks...will update it and report it over time :)

**Comment by legacychimera247** [comment]
update on the problem : now if cover are messed up and i download a new cover the old one will stay on top, meaning that i need to download a new cover, then on the cover menu, select delete cover and old one will delete and new one will appear...

**Comment by legacychimera247** [comment]
since this one should be opened, since now cover art support is not working anymore...if i select a new cover nothing happen...same if i delete a cover...

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/1169
