### ISSUE TITLE
Crashes on start - Linux Mint 18.2

### ISSUE THREAD

**Issue by kylebriffa7** [gnumdk/lollypop#1147]
### Environment
- Lollypop version:
- GNOME/GTK+ versions: 2.24.30-1ubuntu1
- GNU/Linux distribution: OS: Linux Mint 18.2 64bit
- Kernel: 4.8.0-58-generic

### Bug/Feature
On start on Lollypop, after 1-2 seconds it crashes. Installed via repository.

Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

**Comment by gnumdk** [comment]
Looks like a bug in Mint. Any more info, was it working in the past?

**Comment by kylebriffa7** [comment]
Hi @gnumdk. This was the first time I installed lollypop after reading about it in an article. I recently updated to the latest Linux mint version and the kernel which may have to do with the error and crash.

**Comment by laurentdinclaux** [comment]
Same on Ubuntu 16.04. The error is:

```
~  lollypop

(lollypop:14048): Gtk-WARNING **: Theme parsing error: gtk-contained.css:27:19: Missing name of pseudo-class

(lollypop:14048): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2762:55: Not a valid image

(lollypop:14048): Gtk-WARNING **: Theme parsing error: gtk-contained.css:27:19: Missing name of pseudo-class

(lollypop:14048): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2762:55: Not a valid image
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 79, in update_db
    self.__show_first_run()
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 335, in __show_first_run
    view = FirstRunView()
  File "/usr/lib/python3/dist-packages/lollypop/view_first_run.py", line 29, in __init__
    builder.add_from_resource("/org/gnome/Lollypop/FirstRunView.ui")
GLib.Error: gtk-builder-error-quark: .:3:50 Required gtk+ version 3.20, current version is 3.18 (7)
```

**Comment by gnumdk** [comment]
@laurentdinclaux Will release a fix today

**Comment by gnumdk** [comment]
@kylebriffa7 Any other output message?

**Comment by 750jan** [comment]
Got the same output like @laurentdinclaux after fresh installation of Linux Mint. Tried installing 3.20 but didn't found any real package I could apt-get out in the wild (just [this](https://launchpad.net/ubuntu/+source/gtk+3.0), which just says that latest upload is 3.22?).

**Comment by laurentdinclaux** [comment]
It looks like it requires Gnome 3.22 and Ubuntu 16.04 is on Gnome 3.20

**Comment by gnumdk** [comment]
Should be fixed by last release. And package fix.
