### ISSUE TITLE
Meson install dirs

### ISSUE THREAD

**Issue by Keepco** [gnumdk/lollypop#1149]
### Environment
- Lollypop version: 0.9.243
- GNU/Linux distribution: Exherbo

### Bug/Feature
Hello,
I understand that lollypop just started using meson, but it would be great if you could support options such as `bindir` and `libexecdir`, to allow installing them in directories other than prefix/libexec or prefix/bin.
Example:
`meson --prefix=/tmp/lollypop/usr/ --bindir=/tmp/lollypop/usr/x86_64-pc-linux-gnu/bin --libexecdir=/tmp/lollypop/usr/x86_64-pc-linux-gnu/libexec build` should result in the files being install accordingly, e.g. the lollypop binary in `/tmp/lollypop/usr/x86_64-pc-linux-gnu/bin/lollypop`

**Comment by bil-elmoussaoui** [comment]
Totally agree with you. @gnumdk I can take care of that if you wish :)
@Keepco What about the desktop file, appdata, icons & translations. Where should they be installed in this case?

**Comment by Keepco** [comment]
If they're not set they'd be installed in their default dirs ( e.g. /usr/share/applications for desktop files ). By default I use `meson --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/bin --libdir=/usr/x86_64-pc-linux-gnu/lib --libexecdir=/usr/x86_64-pc-linux-gnu/libexec --includedir=/usr/x86_64-pc-linux-gnu/include --sysconfdir=/etc --datadir=/usr/share --mandir=/usr/share/man` though, so that should cover everything :)

**Comment by badshah400** [comment]
I have a patch for libexecdir (we don't even have /usr/libexec on openSUSE, so this was necessary to get things building there). Other paths should follow similar definitions I suppose.

```diff
Index: lollypop-0.9.243/meson.build
===================================================================
--- lollypop-0.9.243.orig/meson.build
+++ lollypop-0.9.243/meson.build
@@ -13,7 +13,10 @@ dependency('gobject-introspection-1.0',
 dependency('gtk+-3.0', version :'>=3.14')
 
 python_dir = join_paths(get_option('prefix'), python.sysconfig_path('purelib'))
-LIBEXEC_DIR = join_paths(get_option('prefix'), 'libexec')
+LIBEXEC_DIR = get_option('libexecdir')
+if (LIBEXEC_DIR == '')
+  LIBEXEC_DIR = join_paths(get_option('prefix'), 'libexec')
+endif
 DATA_DIR = join_paths(get_option('prefix'), get_option('datadir'), meson.project_name())
 
 conf = configuration_data()
```

**Comment by gnumdk** [comment]
@bil-elmoussaoui go go go ;)

**Comment by gnumdk** [comment]
Already fixed thanks to ArchLinux packager.
