### ISSUE TITLE
lollypop displays wrong track numbers

### ISSUE THREAD

**Issue by illwieckz** [gnumdk/lollypop#115]
Hi, as said in #114 , if an album is incomplete, lollypop does not show the good track number.

See how there is only tracks 5 and 6 and they are numbered 1 and 2:

[![renumbering tracks](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_115/20150514-125716.lollypop.png)](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_115/20150514-125716.lollypop.png)

```
$ for track in *.flac; do mediainfo "${track}" | grep 'Album\|Performer\|Track'; printf '\n'; done
Album                                    : La Revancha Del Tango
Track name                               : Santa Maria
Track name/Position                      : 5
Performer                                : Gotan Project

Album                                    : La Revancha Del Tango
Track name                               : Una Musica Brutal
Track name/Position                      : 6
Performer                                : Gotan Project
```

See how the tracks 5, 6, 9, 12, and 17 are missing, but the whole album is renumbered from 1 to 13:

[![renumbering tracks](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_115/20150514-125931.lollypop.png)](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_115/20150514-125931.lollypop.png)

```
$ for track in *.flac; do mediainfo "${track}" | grep 'Album\|Performer\|Track'; printf '\n'; done
Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Á Sprengisandi
Track name/Position                      : 1
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Álfadans
Track name/Position                      : 2
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Sa eg spoa/Dyravisur
Track name/Position                      : 3
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Visur Vatnsenda-Rosu
Track name/Position                      : 4
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Sofðu unga ástin mín
Track name/Position                      : 7
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Þorraþræll
Track name/Position                      : 8
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Suðurnesjamenn
Track name/Position                      : 10
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Bí, bí og blaka
Track name/Position                      : 11
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Kvölda tekur
Track name/Position                      : 13
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Myndir frá Íslandi
Track name/Position                      : 14
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : O, min flaskan frida
Track name/Position                      : 15
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Björt mey og hrein
Track name/Position                      : 16
Performer                                : Vikivaki

Album                                    : Vikivaki Icelandic Folksongs
Track name                               : Lofsöngur
Track name/Position                      : 18
Performer                                : Vikivaki
```

**Comment by gnumdk** [comment]
It's not a bug for me.
If you have an incomplete album,why do you want to see album's track numbers?

**Comment by illwieckz** [comment]
if track numbers are not relevant, why displaying them ?

**Comment by gnumdk** [comment]
They are relevant for me as user may not understand how read tracks order as there is two columns...

**Comment by illwieckz** [comment]
Some people have the habit to listen CD in real world and knows their CD track numbers and have the habit to use them to find tracks or refers to… Currently Lollypop is displaying wrong information about track numbers, it's a real bug.

At work (I wrote for an FM radio station) I work with people who knows their CD track numbers and ask tracks for their program by track numbers, it's a real world use case and it's happen every week.

OK, since I don't use Lollypop at work, it's not a big issue for Lollypop, but if I’ve seen this bug after 20min after starting Lollypop for the first time, it means this bug is very noticeable and disturbing.

**Comment by illwieckz** [comment]
Sometime track numbers are the easiest way to identify tracks (I’m only able to read latin characters but some people not using latin character record music too and I can listen to their music), it’s why the numbering must be trustworthy:

[![numbering](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_115/20150516-072943.lollypop.png)](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/lollypop/issue_115/20150516-072943.lollypop.png)

**Comment by gnumdk** [comment]
I don't think people who don't have complete albums remember tracks numbering.

People with complete albums do not have bug.

People with badly tagged files do not have 'chaos tag numbering'

**Comment by gnumdk** [comment]
Will add a gsetting option for that but will not be the default... Tested on my collection and give weird results with broken tags... ( All tracks numbered with same number, ...)

**Comment by gnumdk** [comment]
Exemple of broken album:
![broken](https://cloud.githubusercontent.com/assets/3918824/7667915/e5acc674-fc1d-11e4-8973-530309ba3f50.png)
