### ISSUE TITLE
meson can't detect python3

### ISSUE THREAD

**Issue by jorgicio** [gnumdk/lollypop#1151]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.243
- GNOME/GTK+ versions: 3.22
- GNU/Linux distribution: Gentoo

### Bug/Feature
Hi!

I maintain a Gentoo overlay with lots of packages, including Lollypop. I noticed it uses Meson build system since 0.9.243.
However, I installed all dependencies (including meson) and when I try to build Lollypop, it can't find python3.

This happens:

hackenherr:lollypop-0.9.243# meson build --prefix=/usr --sysconfdir=/etc --buildtype=plain                                                                     [17:53:13]
The Meson build system
Version: 0.40.1
Source dir: /var/tmp/portage/media-sound/lollypop-0.9.243/work/lollypop-0.9.243
Build dir: /var/tmp/portage/media-sound/lollypop-0.9.243/work/lollypop-0.9.243/build
Build type: native build
Project name: lollypop
Build machine cpu family: x86_64
Build machine cpu: x86_64
Message: Looking for dependencies
Found pkg-config: /usr/bin/pkg-config (0.28)
Dependency python3 found: NO

Meson encountered an error in file meson.build, line 10, column 0:
Dependency "python3" not found

Tried with meson 0.40 and meson 0.41 (in fact, the meson.build file requires 0.40 minimum version and not 0.41), but it fails anyways.

Thanks.

**Comment by gillesgagniard** [comment]
I've got the same issue on Fedora. You need to install the python3 *development files* (which are kind of useless since lollypop doesn't contain any C modules AFAIK) because meson actually is looking for pkg-config files.
You will also need to install itstool which is not in README.md.

**Comment by jorgicio** [comment]
Well, I have all those files (the dev tools are included in the python package here in Gentoo) and itstool installed and the issue is still present.

**Comment by gnumdk** [comment]
@jorgicio you need python-pkconfig and python-devel

**Comment by jorgicio** [comment]
@gnumdk I just installed the python-pkgconfig and as I mentioned above, the devel tools are included in the Python package (I have already installed Python 3 FYI) and tried again and I got the same issue. Still can't detect python3 although already installed.

**Comment by blackjackshellac** [comment]
FWIW, it worked for me on fedora as documented in the README.md file.

I have python3-devel installed, maybe that's the issue.  I don't have a python related pkconfig file installed.

```
python3-devel-3.5.3-6.fc25.x86_64
python-devel-2.7.13-2.fc25.x86_64
```

**Comment by jorgicio** [comment]
I found a trick: editing the meson.build file and in the dependency line, changed "python3" for the version of Python 3 you have installed (in my case, it's 3.4, so i changed "python3" with "python-3.4") and now it works. However, the binaries are not given execution permissions, so the binaries generated cannot be run. Manually, I had to do some chmod +x to make it work.

**Comment by badshah400** [comment]
@gnumdk May be better to detect python using meson's [python3 module](http://mesonbuild.com/Python-3-module.html):

```diff
Index: lollypop-0.9.243/meson.build
===================================================================
--- lollypop-0.9.243.orig/meson.build
+++ lollypop-0.9.243/meson.build
@@ -7,7 +7,12 @@ python = import('python3')
 project_id = 'org.gnome.Lollypop'
 
 message('Looking for dependencies')
-dependency('python3')
+python_bin = python.find_python()
+if not python_bin.found()
+    error('No valid python3 binary found')
+else
+    message('Found python3 binary')
+endif
 dependency('glib-2.0')
 dependency('gobject-introspection-1.0', version: '>=1.35.9')
 dependency('gtk+-3.0', version :'>=3.14')
```

I have a (so far locally) forked repo of lollypop where I already do this, but I am also trying to fix the exec bit issue, which is still a sore thumb so far.

**Comment by jorgicio** [comment]
@badshah400 Your edit works! Thanks.
Now the issue is with the not-chmodded Lollypop binaries.

**Comment by gnumdk** [comment]
Thanks guys for help ;)

**Comment by badshah400** [comment]
Finally, this patch seems to set the right exec permissions. You can also just start with exec permissions for the lollypop.in, lollypop-cli.in and rhythmbox2lollypop.in files from the get go. But, regardless of whether you do that, this should work:

```diff
Index: lollypop-0.9.243/meson.build
===================================================================
--- lollypop-0.9.243.orig/meson.build
+++ lollypop-0.9.243/meson.build
@@ -39,6 +45,7 @@ install_subdir(
 )
 
 message('Preparing init file')
+run_command(['chmod', '+x', 'lollypop.in'])
 configure_file(
   input: 'lollypop.in',
   output: 'lollypop',
@@ -46,6 +53,7 @@ configure_file(
   install_dir: 'bin'
 )
 
+run_command(['chmod', '+x', 'lollypop-cli.in'])
 configure_file(
   input: 'lollypop-cli.in',
   output: 'lollypop-cli',
@@ -53,6 +61,7 @@ configure_file(
   install_dir: 'bin'
 )
 
+run_command(['chmod', '+x', 'rhythmbox2lollypop.in'])
 configure_file(
   input: 'rhythmbox2lollypop.in',
   output: 'rhythmbox2lollypop',
```

@gnumdk I will make a pull request tomorrow with the full patch. Want to see if there may be a neater way to set the exec mods before I do.

@jorgicio Let me know if the above patch works for you. It has to be applied after using the previous patch, which you have already confirmed worked for you; many thanks for that verification.

**Comment by bil-elmoussaoui** [comment]
@badshah400 Please mark the files as executable instead of running this command.

**Comment by jorgicio** [comment]
@badshah400 I confirm your patch is working fine. Before that, I made the ebuild mark those files manually as executable, but this patch works flawlessly.

**Comment by badshah400** [comment]
@bil-elmoussaoui Any particular reason the `run_command()` should not be used? Asking because I am very new to the meson build system.
