### ISSUE TITLE
Sort Radio Stations Alphabetically

### ISSUE THREAD

**Issue by sandman9988** [gnumdk/lollypop#1153]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.242
- GNOME/GTK+ versions: 3.24.3
- GNU/Linux distribution: Solus 2017.04.18.0 64-bit

### Bug/Feature
<Sort/display radio stations alphabetically according to name field to ensure consistent layout across multiple installations.>

Thank you for your consideration.

**Comment by gnumdk** [comment]
Radios are sorted by popularity, looks better for me, more users against this behaviour?

**Comment by gnumdk** [comment]
No, so closing
