### ISSUE TITLE
Album duplicates

### ISSUE THREAD

**Issue by sanyarnd** [gnumdk/lollypop#1155]
Hi. 

It'd be great if Lollypop could treat different album editions separately. 
I have 2 editions of the same album, with different tags (year, musicbrainz id, etc), except name. 
Is there any way to force lollypop to sort album on custom tags, or at least look for musicbrainz tags first?

**Comment by gnumdk** [comment]
Duplicates #1051

**Comment by gnumdk** [comment]
Yes, you can change the name of the album, just add remastered... Or wait for a solution for #1051
