### ISSUE TITLE
Album Art Problem

### ISSUE THREAD

**Issue by Rolegur** [gnumdk/lollypop#1157]
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.22.16
- GNU/Linux distribution: Arch

### Bug/Feature
Attempting to use the find Album Artwork browser fails. The popup window opens but "Low Quality Missing API key..." displays at top of window.

I have an Search API key. This feature did work at some point but lately has stopped (unsure if timing corresponded to an update of system or program). I have tried getting a new key but that did not fix the issue. I have also tried removing the API key and using the default but that did not fix the issue. Quiting/Rebooting attempted with no success. Really cool feature and hopefully can figure a way to get it working again.

**Comment by gnumdk** [comment]
Any error on console output?

**Comment by Rolegur** [comment]
Did a bit of isolation and reliably get this error only when I click on the Change Artwork button. 

Jul 10 01:18:52 Jarvis lollypop[28351]: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed

**Comment by gnumdk** [comment]
So no error :-(

**Comment by gnumdk** [comment]
Are you sure you are putting the good key?

**Comment by Rolegur** [comment]
Mostly sure. I even regenerated the key a few times. At some point it was working with no issue using the API key. It's the only API key I have/use.

**Comment by gnumdk** [comment]
And no quota error in Google console?

**Comment by Rolegur** [comment]
Sadly no error in the Google console. I went ahead and again created another key, starting from scratch (deleting the project etc). Same issue. Trying to install Lollypop on another machine to isolate whether it's something to do with my key or the OS. Having a bit of trouble with this as GalliumOS uses GTK+ 3.18 and hasn't been updated.

Another note about the API key. Not seeing any activity at all in the dashboard. Old and new key. No errors, no hits, nothing.

**Comment by gnumdk** [comment]
Can you send me your key by email?

**Comment by Rolegur** [comment]
Not sure if you got my email. I can send it again if you did not.

**Comment by gnumdk** [comment]
Bad news, it works with your key here...

**Comment by gnumdk** [comment]
So looks like a restriction due to your location/ip adresse...
