### ISSUE TITLE
lollypop completely empty

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1159]
after latest update lollypop reappeared again (hurra :P ) but this time is completely empty as you can se from the screen
![schermata da 2017-07-11 10-27-03](https://user-images.githubusercontent.com/22254556/28059292-0a5d4774-6624-11e7-85e5-9d6544c4c1b3.png)

if you need it this is what terminal says

`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/site-packages/lollypop/loader.py", line 49, in run
    result = self._target()
  File "/usr/lib/python3.5/site-packages/lollypop/container.py", line 625, in load
    items = Lp().albums.get_rated()
  File "/usr/lib/python3.5/site-packages/lollypop/database_albums.py", line 545, in get_rated
    result = sql.execute(request, filters)
sqlite3.OperationalError: no such column: rate

CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__del_from_db: no such column: rate
CollectionScanner::__scan(add): table albums has no column named rate file:///home/luca247/Musica/Alice%20Deejay/01%20-%20Alice%20Deejay%20-%20Better%20off%20alone%20(Radio%20edit).ogg
CollectionScanner::__scan(): 'OperationalError' object has no attribute 'message'
`

**Comment by gnumdk** [comment]
Because you played with different lollypop version?

**Comment by legacychimera247** [comment]
well when lollypop disappeared i simply unistalled it and reinstalled again via the fedora software center...this resulted in a lower version, so unistalled it again and installed it from command line and decided to wait for the update...is there a solution to that problem or i should do a clean install?

**Comment by legacychimera247** [comment]
removing my database and creating a new one solved the issue...think we can close this one...

**Comment by gnumdk** [comment]
Yes, will fix this by putting version in sqlite db like I've done with Eolie :-1:
