### ISSUE TITLE
Show the next track's name in the fullscree mode

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#116]
I wants to see the next track's name next to the album bane, with a separator before.

Some thing like this:
Arist - bold
Track's namr - bold
Album name - regular
----------------- (separator)
Next track's name

**Comment by gnumdk** [comment]
What is bane? Tooltip?

**Comment by yoseforb** [comment]
Typo, sorry. I mean name. (album name).

**Comment by gnumdk** [comment]
In the headerbar?

**Comment by yoseforb** [comment]
I'm talking on fullscreen mode (F11).

**Comment by gnumdk** [comment]
Ok, keep it for next release (0.9.30) as lolllypop need to pre calculate next track

**Comment by yoseforb** [comment]
Even I new you added the next track name in the fullscreen, it take me a few minutes
to find it out at the bottom of the screen.

I think it too much down so it came to be out of the user eyes.
To my opinion it better to put it where I asked to, with horizontal separator under the
current track's labels, at the middle of the screen.

![lollypop-next-track-fullscreen](https://cloud.githubusercontent.com/assets/2222697/7696941/8c21059e-fe0b-11e4-80f0-171ae460eb08.png)

**Comment by gnumdk** [comment]
Fullscreen purpose is about showing current track when away from computer... So next track need to be visible... I tested putting it under the current but found this confusing.

Regards,
