### ISSUE TITLE
Search Provider Not Working

### ISSUE THREAD

**Issue by RODNOTGOD** [gnumdk/lollypop#1164]
### Environment
- Lollypop version: 0.9.244-1ppa1ubuntu1.2
- GNOME/GTK+ versions: 3.22.11
- GNU/Linux distribution: Ubuntu Gnome 17.04

### Bug/Feature
Lollypop music no longer shows on the gnome search bar/provider

**Comment by gnumdk** [comment]
ls /usr/libexec/lollypop-sp  -lh

**Comment by RODNOTGOD** [comment]
It works again....
I just needed to restart my computer.
Sorry about the issue
