### ISSUE TITLE
Version in about box is not  current

### ISSUE THREAD

**Issue by blackjackshellac** [gnumdk/lollypop#1166]
- Lollypop version: 0.9.244 tag
- GNOME/GTK+ versions: 3.22.3
- GNU/Linux distribution: Fedora 25

### Bug/Feature
The version shown in the About box has not been updated, probably since the meson/ninja update.  On my system it still shows 0.9.242.  Running lollypop from the command line does show the updated version,

```
$ lollypop -V
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Lollypop 0.9.244
```
ObAside: should the app really start if the command-line version option has been selected?

**Comment by gnumdk** [comment]
Here it's ok... You need to re-run meson command I guess...
