### ISSUE TITLE
Some tags difference may lead to Lollypop creating two or more albums instead of one.

### ISSUE THREAD

**Issue by Porkepix** [gnumdk/lollypop#1167]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Archlinux

### Bug/Feature
Some tracks may be considered as coming from different albums if some tags *other than the album tag* differ.

Problem was noticed on a 17 tracks album where only one of the tracks had a "performer" tag set (the other 16 didn't had that tag at all). Lollypop did create two albums due to that with the exact same name. Once I removed the tag, albums were merged in a single one.

I didn't tested with other tags if problem could happen too, but I guess only the Album tag should be considered to know if that's the same album or not, even if I actually don't know if there are many albums with the same name.
Artist (more commonly set) and album combination could be used too, or through a kind of unique ID, if music have an equivalent to ISBN for books.

**Comment by gnumdk** [comment]
You are missing an "artist album", this is the only reason Lollypop create 2 albums.
