### ISSUE TITLE
Not able to read my music

### ISSUE THREAD

**Issue by PranjalMishra11** [gnumdk/lollypop#1168]
Whenever I open lollypop it dosen't shows any of my file.I tried updating music 5-6 times but nothing happens .Pls help .
I am new to lollypop.

**Comment by PranjalMishra11** [comment]
Here is an example..
![coldplay - fix you - lollypop_001](https://user-images.githubusercontent.com/30182454/28222199-03a03104-68e4-11e7-976a-c084148fa3f6.png)

**Comment by gnumdk** [comment]
Any message on command line?

**Comment by PranjalMishra11** [comment]
Here ......
![abc](https://user-images.githubusercontent.com/30182454/28271182-7b72e74c-6b25-11e7-8624-3c27d0bc2833.png)

**Comment by PranjalMishra11** [comment]
If i just play a single track from the search box it finds all of them(As in the first screenshot).

**Comment by PranjalMishra11** [comment]
And I am using Ubuntu 17.04 64bit and Gnome Environment.

**Comment by PranjalMishra11** [comment]
Gnome Shell 3.24.2 to be precise.

**Comment by gnumdk** [comment]
But where is lollypop panel? Try to get it from the left!

**Comment by PranjalMishra11** [comment]
![selection_001](https://user-images.githubusercontent.com/30182454/28275281-0b043edc-6b31-11e7-8e3e-832b7b8ba375.png)

**Comment by PranjalMishra11** [comment]
Is that what you were asking for exactly.

**Comment by gnumdk** [comment]
Look at Lollypop screenshots, there is a sidebar...

**Comment by PranjalMishra11** [comment]
okay i understood what you are asking.I tried but cannot pull a sidebar.

**Comment by PranjalMishra11** [comment]
I have reinstalled lollypop still it does not show up.

**Comment by PranjalMishra11** [comment]
How to open the sidebar ???I have tried everything reinstalled it two times and pulled at sides but no sidebar.It is just showing the same thing i took a screenshot of earlier.

**Comment by PranjalMishra11** [comment]
Wait it opened after 4th or 5th reinstall.

**Comment by PranjalMishra11** [comment]
It did show all albums but with same coverart....
![lollypop_001](https://user-images.githubusercontent.com/30182454/28306247-3618d0e8-6bbc-11e7-8598-60a9a6d76746.png)

**Comment by PranjalMishra11** [comment]
Do you need to reset album art always because not it works fine..After reseting each and every album art. 
![abc](https://user-images.githubusercontent.com/30182454/28306640-b81fb83a-6bbd-11e7-908b-7df58fef162b.png)

**Comment by PranjalMishra11** [comment]
Thanks for helping me out and wasting your time on a stupid bug hope u keep on creating more like lollypop.I am already loving it....

**Comment by gnumdk** [comment]
Not sure what happened for Eminem album art, but it's too late to search.

**Comment by gnumdk** [comment]
@PranjalMishra11 If you have time to check, I'm working on Eolie Web Browser ;)

But no new release for know as I have issue with flatpak and hunspell...

**Comment by PranjalMishra11** [comment]
Sure i will take a look at it.Lollypop is great by the way.
