### ISSUE TITLE
radio stream starts to crack after 10-20 minutes of listening

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#1170]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.244 (issue present for a while already)
- GNOME/GTK+ versions: 3.24 (was the same in 3.22 before)
- GNU/Linux distribution: Fedora 26 (was the same in Fedora25 before)

### Bug/Feature
when playing a radio, after approx. 10-20 minutes the audio stream starts to crack, periodically every half second and, not possible to enjoy/listen to it anymore; the crack increases over 5 minutes to a point that the radio stream stops altogether. 

This doesn't happen when i listen to the same radio stream over a web browser.

Thank you for checking.

**Comment by gnumdk** [comment]
This is a Gstreamer issue, report upstream...

**Comment by corebots** [comment]
ok thanks

**Comment by corebots** [comment]
please could you point me to the correct bug tracking this issue in gstreamer? i just can't seem to find one... thank you

**Comment by gnumdk** [comment]
First reproduce the issue with Totem ;)
