### ISSUE TITLE
displaying shared/network libraries

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#1171]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: F26

### Bug/Feature
please can lollypop display a shared music library? for example iTunes, or a samba share on NAS. I've just set ap a QNAP NAS on my network and i'lm looking for the best way how to everything work. For example, when i open Rhythmbox, i see 'shared iTunes library' in the left panel - can we access it from Lollypop? or what are the options to display shared music in Lollypop please? 

sorry if this is a stupid question, can't find sufficient info for it...

Thank you.

**Comment by gnumdk** [comment]
Sorry, don't want to support such feature because it will force me to handle broken tags from others player by adding hack in Lollypop code... But you can ask Lollypop to play from a remote smb:// directory.

**Comment by corebots** [comment]
Ok I understand... 

So I could simply specify the remote smb:// folder with music on the NAS as another music folder in Lollypop settings and it will be added to my collection? that simple?

**Comment by gnumdk** [comment]
Yes.

**Comment by corebots** [comment]
Thank you Cedric ;)
