### ISSUE TITLE
Automatically scroll main window to focus currently playing album

### ISSUE THREAD

**Issue by ZedPea** [gnumdk/lollypop#1172]
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24.2
- GNU/Linux distribution: Arch GNU/Linux

Hiya, just started using lollypop and really liking it,

When using the all albums view, is it possible to automatically scroll the window so the currently playing album is on the screen? I'm using album shuffle, and most of the time I'd have to scroll down to find the album which is playing.

It's handy to have the currently playing album viewable, so you can both see the nice album art, and access the features like seeing what track number you're on, making it easier to love the current song on LastFM, picking individual songs from the album, etc.

I'm not sure if this works better on a different mode like playlist, but I just like using my whole library, so all albums works for me.

Also, the skip current album keyboard shortcut doesn't appear to work for me, but I can make that a separate issue if you prefer.

**Comment by gnumdk** [comment]
>Also, the skip current album keyboard shortcut doesn't appear to work for me, but I can make that a separate 
>issue if you prefer.

Here it works, maybe you do not have more than two albums in your playlist or you are in shuffle by tracks mode?

**Comment by gnumdk** [comment]
For the access to current album, just click on track title in headerbar -> albums -> Jump to current album.
