### ISSUE TITLE
Support MPRIS LoopStatus and Shuffle

### ISSUE THREAD

**Issue by JasonLG1979** [gnumdk/lollypop#1173]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.24.2
- GNU/Linux distribution: Fedora 26

### Bug/Feature
<Describe your bug/feature here>

I recently added LoopStatus and Shuffle support to https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer

![screenshot from 2017-07-18 01-24-56](https://user-images.githubusercontent.com/6667703/28303307-1fcfdfde-6b58-11e7-901f-dfa509cb74fe.png)

It would be awesome if Lollypop had support for setting those props. Currently Shuffle always returns False and LoopStatus always returns "Playlist".

Shuffle is ofc a boolean but Lollypop has 3 shuffle modes "Shullfle albums",  "Shuffle tracks" and "No shuffle". My thought is that for the purpose of MPRIS Shuffle should just toggle between "No shuffle" and the last shuffle state.

For LoopStatus it seems to map pretty well to Lollpop's repeat modes. "None": "Do not repeat", "Track": "Repeat track", "Playlist": "Continuous playback".

**Comment by JasonLG1979** [comment]
https://github.com/gnumdk/lollypop/commit/1c5605d0748399a1e4ed228444588fc646155a3c

That doesn't fix the issue. That only makes it so that the props can be retrieved from Get and GetAll. It doesn't allow me to set them and it doesn't emit a prop changed signal when it's changed. Any time you change a prop with very few exceptions you should emit a prop changed signal. Otherwise how am I suppose to know it changed?

**Comment by JasonLG1979** [comment]
MPRIS done right unfortunately requires about a zillion signals and handlers,lol!!!

**Comment by gnumdk** [comment]
qdbus org.mpris.MediaPlayer2.Lollypop /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Shuffle
true

**Comment by gnumdk** [comment]
Ok, you want to set them!

**Comment by JasonLG1979** [comment]
I believe you. As I said that allows you to get the props with Get and GetAll. You need to emit a prop changed signal otherwise how am I suppose to know that they have changed when you change them?

**Comment by JasonLG1979** [comment]
With the interfaces you use with the exception of Position and CanControl EVERY TIME you change the value of a prop you MUST emit a prop changed signal for that prop.

**Comment by JasonLG1979** [comment]
You can batch emit signals if it makes sense to do so. If for example you're in a stopped state and you start playing. You can send the Metadata,  PlaybackStatus, and CanPause or whatever at the same time. You don't have to machine gun a bunch of props if you don't want to.

**Comment by gnumdk** [comment]
Should be better now... But totally untested.

**Comment by JasonLG1979** [comment]
Ok that's good but you still need to emit a prop changed signal for if it's not changed in the extension. The standard flow is: A MPRIS client calls a method or tries to set a prop and then waits for confirmation via a signal. The spec clearly says that 1. Clients should not assume anything actually happened and wait for a signal and that 2. you must emit prop change signals.

**Comment by JasonLG1979** [comment]
On the signals note. You also don't emit a signal like you should when the ratings are changed via the command line arg.

**Comment by gnumdk** [comment]
I'm emitting a PropertiesChanged, I need to do more?

**Comment by JasonLG1979** [comment]
Awesome!!! Looks good. I'll build and test it.

**Comment by JasonLG1979** [comment]
Thanks again. Works perfectly.

**Comment by gnumdk** [comment]
Thanks you! For forcing me to work on such things :-)

**Comment by JasonLG1979** [comment]
Now it's time to implement the PlayList and TrackList interfaces,lol!!! The TrackList interface in particular can be a pain...

**Comment by JasonLG1979** [comment]
And fix that not being able to set ratings to zero thing,lol!!!

**Comment by gnumdk** [comment]
>The TrackList interface in particular can be a pain...

It's quite impossible with Lollypop internals... 90% of the time, Lollypop only know previous tracks, current track and next track.

**Comment by JasonLG1979** [comment]
The track list would be the tracks in the current playlist or the currently playing album. Surely you know that? You display it in the player.

**Comment by gnumdk** [comment]
Yes, but if user is in Shuffle, party mode, I don't know...

**Comment by JasonLG1979** [comment]
Then set HasTrackList to False. Problem solved.

**Comment by JasonLG1979** [comment]
Shuffle doesn't matter really. The TrackList ordering is requested by the client. The client doesn't control the actual playback order just the order it's displayed in. In the case of my extension I default to Alphabetical or the 1st ordering in the array if Alphabetical is not an option. There are set orderings but they're strings so they really could be anything you want them to be. I don't check against the spec values. And really no matter what a client requests you can give it a list in what ever order you want.

**Comment by JasonLG1979** [comment]
I spoke too soon on the ratings. A signal is emitted if the ratings are changed in the UI but still not changed via the command line. No real hurry I can fake it for now though and just set it to whatever value I send.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/1615511e06b52c4647857bf74057d91408d8c6ee
