### ISSUE TITLE
Latest flatpak build crashes when opening preferences

### ISSUE THREAD

**Issue by Vaesper** [gnumdk/lollypop#1174]
Looks to be the same issue as #1143, opening a new one since this is more of a distribution question. Issue exists both in the Flathub version as well as the .flatpakref linked on the .github.io site.

**Comment by gnumdk** [comment]
What version is shown in about dialog?

**Comment by Vaesper** [comment]
Old version (0.9.241). But, proper solution would be to include lollypop-portal in the flatpak, no?

**Comment by gnumdk** [comment]
No, the portal is here because of the flatpak...

**Comment by gnumdk** [comment]
And 0.9.241 is not last release so there is an issue with my package on flathub.

**Comment by Vaesper** [comment]
Ah, sorry, new to flatpak, that makes sense. Lollypop-portal not available in my package manager unfortunately, but that's outside your control ;)

**Comment by gnumdk** [comment]
0.9.244 should be available now.

**Comment by Vaesper** [comment]
Thanks for the quick response :)
