### ISSUE TITLE
Audio cd support

### ISSUE THREAD

**Issue by glaubersm** [gnumdk/lollypop#1177]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24.2/3.22.16
- GNU/Linux distribution: Antergos

### Bug/Feature
<Describe your bug/feature here>
was audio cd support removed? I remember this feature was available some releases ago but it did not work. Can you add audio cd support please? Thanks.

**Comment by gnumdk** [comment]
No, it was never supported and will not.
