### ISSUE TITLE
add album play icon + album append button

### ISSUE THREAD

**Issue by mray** [gnumdk/lollypop#1178]
It would be nice to have a consistent control over all items in the album view:

![peek 2017-07-22 11-06](https://user-images.githubusercontent.com/164785/28490101-b200f380-6ed1-11e7-85c8-4b1b8350993d.gif)

###  click
- click on track title -> play track
- click on album title -> play album

### hover
- hover over track title -> show append icon
- hover over album title -> show append icon

### indicator
- play indicator for running track
- play indicator for running album

![image](https://user-images.githubusercontent.com/164785/28490163-45a4ed20-6ed3-11e7-89a5-85839aa857ed.png)

**Comment by gnumdk** [comment]
I disagree, indicator for running albums looks confusing.
And I prefer to let controls on album covers.
