### ISSUE TITLE
German translation issue?

### ISSUE THREAD

**Issue by sevachka** [gnumdk/lollypop#118]
Hello,
on the left sidebar, the second entry from top: "Zuletzt gehörte Alben" (eng: last listend to albums) should be translated into "zuletzt hinzugefügte Alben". Because it is showing the recently added albums. I love this feature, but the translation is wrong.

**Comment by gnumdk** [comment]
Contact german team on transifex:
https://www.transifex.com/projects/p/lollypop/resource/lollypop/

--
Cédric Bellegarde


Le sam. 16 mai 2015 à 11:41, sevachka <notifications@github.com> a 
écrit :

**Comment by gnumdk** [comment]
https://www.transifex.com/projects/p/lollypop/resource/lollypop/
