### ISSUE TITLE
Threading improvement.

### ISSUE THREAD

**Issue by JasonLG1979** [gnumdk/lollypop#1180]
I noticed you use a lot of naked python threads. This little handy adaptation of the GObjectWorker in Pithos should make threading easier for you.

```python
import threading
from gi.repository import GLib
import traceback


class GObjectWorker:

    def send(self, command, args=None, callback=None, errorback=None, user_data=None):
        def run(data):
            command, args, callback, errorback, user_data = data
            args = args or ()
            try:
                result = command(*args)
                if callback and user_data:
                    GLib.idle_add(lambda: callback(result, user_data=user_data))
                elif callback:
                    GLib.idle_add(callback, result)
            except Exception as e:
                e.traceback = traceback.format_exc()
                if errorback:
                    GLib.idle_add(errorback, e)
        if errorback is None:
            errorback = self._default_errorback
        data = command, args, callback, errorback, user_data
        thread = threading.Thread(target=run, args=(data,))
        thread.daemon = True
        thread.start()

    def _default_errorback(self, error):
        print("Unhandled exception in worker thread:\n{}".format(error.traceback))
```

It's pretty flexible. You can pass user_data along for the ride if you like and your callback function is called in the main thread context.

Useage:
```python
worker = GObjectWorker()

def some_long_running_task(*args):
    #Do stuff that takes a long time
    return stuff

def callback(results):
    #Do stuff in the main thread with stuff

args = (arg1, arg2, arg3)
worker.send(some_long_running_task, args, callback)
```

**Comment by gnumdk** [comment]
Cool stuff, adding a new helper in Eolie using this stuff, later for Lollypop (september I guess).

**Comment by JasonLG1979** [comment]
The above is async. If you need a synchronous(to it's self any way) worker thread you and add a threading queue.

**Comment by JasonLG1979** [comment]
The async version above spawns as many threads as you times you call send. The synchronous version would have 1 worker thread per object. Useful if you need A, B, C to happen in order in the background before anything is returned to the main thread. Wrapping your head around threads is a PITA!!!

**Comment by gnumdk** [comment]
After looking at code, it does not seem to fit my needs. Here the code is launching command in a thread and then pass result to callback using mainloop.

But in Lollypop and Eolie, most of the time, I need to callback mainloop from command() so all the callback stuff will not be used.

**Comment by JasonLG1979** [comment]
> I need to callback mainloop from command()

What do you mean?

**Comment by gnumdk** [comment]
That command() needs to send data to mainloop while running. Not at the end.

**Comment by JasonLG1979** [comment]
If you for example want to update a UI widget with information from say a network call you'll need to feed the results though GLib.idle_add otherwise you're trying to update a UI widget from outside the mainthread which is a big no-no. I may or may not work but it also has a good chance of crashing your UI.

**Comment by JasonLG1979** [comment]
And generally for the sake of data integrity you never want just want to bust into the mainthread from an outside thread. Even when not dealing with UI widgets it can crash your program and cause weird behavior.

**Comment by JasonLG1979** [comment]
When dealing with threads functions preformed in the thread should be a "pure" function it should not interact with data in the main thread and should just return something. Unless ofc you want to deal with thread locks and all that crap. Just pass in what you need and return the result to the callback and let the callback change things in the mainthread.

**Comment by gnumdk** [comment]
> it can crash your program and cause weird behavior.
Lollypop and Eolie call GLib.idle_add() from threads and I never see a crash.

> result to the callback and let the callback change things in the mainthread.

For a slow looking software, why not, but it's just not working:
- If thread take 30 seconds to return, user will wait 30 seconds before seeing any result
- GObjectWorker here will kill GTK while executing callback if you are adding 2000 items in a flowbox for example.

**Comment by JasonLG1979** [comment]
> Lollypop and Eolie call GLib.idle_add() from threads and I never see a crash.

You can call GLib.idle_add from an outside thread. That's one of it's purposes.

> If thread take 30 seconds to return, user will wait 30 seconds before seeing any result

If you have something that always pretty much takes 30 secs you should break it up in to smaller tasks if you can.



> GObjectWorker here will kill GTK while executing callback if you are adding 2000 items in a flowbox for example.

No worse than trying to brute force your way into the mainthread 2000 times...

**Comment by JasonLG1979** [comment]
You shouldn't be updating a Flowbox from an outside thread EVER.

**Comment by JasonLG1979** [comment]
Like I said you shouldn't interact with anything GLib from an outside thread unless it specifically says it's threadsafe. Most things are not.

**Comment by gnumdk** [comment]
I may be wrong, but Lollypop is not interacting with GLIb from an outside thread, it just calling GLib.idle_add() from an outside thread.

**Comment by gnumdk** [comment]
>No worse than trying to brute force your way into the mainthread 2000 times...

Lollypop is not, it is just calling GLib.idle_add() item by item.

My main issue with GObjectWorker is that is my thread is loading images on the web, it will only call callback when all images are loaded instead of calling it for each loaded image.

**Comment by JasonLG1979** [comment]
If it does you're lucky. somethings in Glib are kinda threadsafe even if not explicitly stated to be so.

**Comment by gnumdk** [comment]
From GLib documentation, GLib is thread safe but for performance reason, some data structure aren't.

But I do not use GLib data structure, only pure python data structure.

**Comment by JasonLG1979** [comment]
You can also ditch python threads altogether if you use asyc versions of GLib functions for example in Lio you can do something like this:

```python
        def load_contents_async(self, callback, cancellable=None):
            """
                Load uri with libsoup (better performance)
                @param callback as a function to return the results to
                @param cancellable as Gio.Cancellable
            """
            def on_soup_msg_finished(source, result):
                try:
                    msg = source.send_finish(result)
                    body = msg.get_property("response-body")
                    bytes = body.flatten().get_data()
                except Exception as e:
                    # FIXME Use debug, need to be moved outside utils.py
                    if Lp().debug:
                        print("Lio.load_contents_async():",  e)
                    callback(False, b"", "")
                else:
                    callback(True, bytes, "")

            def on_load_contents_finish(source, result):
                try:
                    bytes = source.load_contents_finish(result)[1];
                except Exception as e:
                    # FIXME Use debug, need to be moved outside utils.py
                    if Lp().debug:
                        print("Lio.load_contents_async():",  e)
                    callback(False, b"", "")
                else:
                    callback(True, bytes, "")

            try:
                uri = self.get_uri()
                if uri.startswith("http") or uri.startswith("https"):
                    session = Soup.Session.new()
                    msg = Soup.Message.new("GET", uri)
                    headers = msg.get_property("request-headers")
                    headers.append("Authorization",
                                       "Bearer %s" % self.__token)
                    session.send_async(msg, cancellable, on_soup_msg_finished)
                else:
                    Gio.File.load_contents(self, cancellable, on_load_contents_finish)
            except Exception as e:
                # FIXME Use debug, need to be moved outside utils.py
                if Lp().debug:
                    print("Lio.load_contents_async():",  e)
                callback(False, b"", "")
```

**Comment by JasonLG1979** [comment]
The above is totally untested, but you get the idea.

**Comment by JasonLG1979** [comment]
I use load_contents_async in my extension because it catches errors unlike just pooping the Gio.File into a Gio.Icon.

**Comment by gnumdk** [comment]
Done for Eolie: https://github.com/gnumdk/eolie/blob/master/src/helper_task.py

For Lollypop, will come later (in september I hope), code needs to be cleaned, was using Gio from the start but was buggy so moved to libsoup and add a wrapper for easy/fast fixing.

Today, this wrapper should be removed.

**Comment by gnumdk** [comment]
Done
