### ISSUE TITLE
MPRIS with flatpak

### ISSUE THREAD

**Issue by Maestroschan** [gnumdk/lollypop#1181]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: it's GNOME 3.22 on my system, but i don't know what runtime is actually used by flatpak
- GNU/Linux distribution: Debian 9

### Bug
When installed as a flatpak (from flathub, system-wide, i didn't test other possibilities), i don't have media player controls in the GNOME Shell's clock menu (however, i have notifications).

Also, keyboard's media control keys don't work.

**Comment by gnumdk** [comment]
Works with last package.
