### ISSUE TITLE
Feature Request: Allow ALSA output 

### ISSUE THREAD

**Issue by benjamindaines** [gnumdk/lollypop#1183]
For those of us who have spent too much money on fancy audio gear, yet want a music player with a great GUI it is a shame that Lollypop will only play via pulseaudio.  Please add and option to select ALSA hardware devices for playback.

**Comment by gnumdk** [comment]
Sorry, Lollypop is targetting GNOME and so pulseaudio.

**Comment by gnumdk** [comment]
https://wiki.archlinux.org/index.php/PulseAudio/Examples#PulseAudio_as_a_minimal_unintrusive_dumb_pipe_to_ALSA
