### ISSUE TITLE
allow adding radio station covers manually

### ISSUE THREAD

**Issue by jan-59** [gnumdk/lollypop#1184]
It's not a bug, its more like a feature request. I manually lookup the URLs of the radio stations I want to listen to. Sadly Lollypop cannot fetch the covers/logos by itself because the stations don't have one or don't include them. What I would really appreciate if I could manually add a cover so it does not feel so empty (my whole collection is full with album covers but the stations don't have any).

**Comment by k-kirill** [comment]
@jan-59, it's possible to select a local picture as a cover for radio:
Click "wrench" icon while hovering over radio -> Click "Modify" button -> Click "image" icon in the header
