### ISSUE TITLE
Lollypop crashes when 'hand2' cursor is not found in current cursor theme

### ISSUE THREAD

**Issue by robinkb** [gnumdk/lollypop#1185]
### Environment
- Lollypop version: 0.9.243
- GNOME version: 3.24.2
- GTK+ version: 3.22.17
- GNU/Linux distribution: Fedora 26 Workstation

### Bug

**Description:**

While using the [Paper cursor theme](https://github.com/snwh/paper-icon-theme), Lollypop will often crash with the following message in commandline:

```
Gdk-Message: Unable to load hand2 from the cursor theme
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lollypop/toolbar_info.py", line 96, in _on_eventbox_realize
    eventbox.get_window().set_cursor(Gdk.Cursor(Gdk.CursorType.HAND2))
  File "/usr/lib64/python3.6/site-packages/gi/overrides/Gdk.py", line 334, in __new__
    return cls.new(*args, **kwds)
TypeError: constructor returned NULL
```

**Reproducible:**

Always

**Steps to reproduce:**

1) Install Paper icon theme (to `~/.local/share/icons/`)
2) Set cursor theme to Paper with Gnome Tweak Tool
3) Launch Lollypop
4) Open the "All albums" view

**Actual results:**

Lollypop crashes.

**Expected results:**

I can select an album to listen to.

**Additional info:**

Switching back to the default cursor theme (Adwaita) resolves the issue.

This problem is probably caused by a missing cursor in the Paper icon theme, so the root issue is not with Lollypop. However, I think Lollypop should not crash because of a missing cursor.

**Comment by gnumdk** [comment]
Not sure, Gdk.CursorType.HAND2 is defined by API and so it should exist.

**Comment by d9h20f** [comment]
Maybe related to this GNOME bug that still isn't fixed: https://bugzilla.gnome.org/show_bug.cgi?id=709656

**Comment by gnumdk** [comment]
So, it's more about a broken Linux (missing fallback theme)
