### ISSUE TITLE
Spotify charts interface is always blank

### ISSUE THREAD

**Issue by k-kirill** [gnumdk/lollypop#1189]
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: gtk-3.22.16
- GNU/Linux distribution: openSUSE Tumbleweed 20170721

### Bug
Spotify charts interface is always blank.

One of the issues is that for the "en_US" locale it tries to download the chart for "en" instead of "us" region: https://spotifycharts.com/regional/en/weekly/latest/download

Another issue is that track requests like https://api.spotify.com/v1/tracks/0XLOf9LhyazPX9Ld8jPiUq got rejected with the "No token provided" error

**Comment by gnumdk** [comment]
Thinking about removing spotify/Itunes/youtube-dl, I do not use this and so my motivation to fix that is low... :-1:

**Comment by gnumdk** [comment]
Other issue is aleady fixed in last version.
