### ISSUE TITLE
Feature request : drag & drop

### ISSUE THREAD

**Issue by TuxJul** [gnumdk/lollypop#119]
Hi, 
What about drag & drop in Lollypop ?
Drag & drop to create playlists, to enqueue songs, ....

PS : I discover Lollypop, it's really a great job !

**Comment by gnumdk** [comment]
After reading GNOME HIG:
"Use drag and drop only where the user can reasonably guess what the effect might be."
Adding drag & drop here will be confusing, as user may guess it's for moving track in album widget.

On more, Gtk.ListBox doesn't support drag & drop
