### ISSUE TITLE
[Flatpak] Mutimedia controls don’t work

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1191]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24.2 / 3.22.17
- GNU/Linux distribution: Fedora 26

### Bug/Feature
I just installed Fedora 26 and then Lollypop from Flathub. Sadly, the mutimedia keys of my keyboard don’t work.

**Comment by gnumdk** [comment]
Yes, should be missing dbus bus... Strange because I start with Music json file so should be a bug in gnome-music too.

**Comment by JasonLG1979** [comment]
The bus name has changed from org.gnome.SettingsDaemon to org.gnome.SettingDaemon.MediaKeys in GNOME 24 if I remember correctly? We fixed it in Pithos. I'll put in a PR in a bit so media keys will work with all GNOME versions and Mate.

**Comment by JasonLG1979** [comment]
We'll also want to re-grab the keys when the widow is focused. Currently they're only grabbed once. So if another app grabs them after Lollypop, Lollypop looses the keys even if it's the most currently focused app.

**Comment by JasonLG1979** [comment]
https://github.com/gnumdk/lollypop/pull/1198/commits/1d8b2e02fc9005aabac37423514ed767eef7c08a

**Comment by Maestroschan** [comment]
> The bus name has changed from org.gnome.SettingsDaemon to org.gnome.SettingDaemon.MediaKeys in GNOME 24 if I remember correctly? We fixed it in Pithos. I'll put in a PR in a bit so media keys will work with all GNOME versions.

I previously opened [this issue](https://github.com/gnumdk/lollypop/issues/1181) (which is the same) but i'm using GNOME 3.22, not 3.24

**Comment by Vaesper** [comment]
Media keys worked for a little while but with latest flatpak build broke again.

**Comment by gnumdk** [comment]
Here it works with last flatpak package. Please report this issues to org.gnome.Lollypop project.

**Comment by fbruetting** [comment]
Now it works for me, too. Guess nothing to report anymore.
