### ISSUE TITLE
Gitter/Slack/IIRC channel

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#1193]
A lot of people(users/devs) might have few questions and might would like to discuss possible new features. Providing an easy way to do that would be really great.

Possible solutions:
- Gitter Channel /Slack channel : both got the best experience with Github!
- IIRC: a chat room on freenode server ?

**Comment by Sterrs** [comment]
Using matrix would mean that Gitter and IRC could be bridged. Slack is not appropriate for open source projects.

**Comment by gnumdk** [comment]
Gitter added to README.md ;)
