### ISSUE TITLE
lollypop crashes when change the picture folder

### ISSUE THREAD

**Issue by martinkg** [gnumdk/lollypop#1196]
BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: lollypop-0.9.243-2.fc26
- GNOME/GTK+ versions: 3.24
- GNU/Linux distribution: Fedora 26

### Bug/Feature
I was trying to change the folder picture of an album from Lollypop music library, and had
just moved the corresponding ~.jpg~ to the album directory. Then, Lollypop crashed.

Version-Release number of selected component:
lollypop-0.9.243-2.fc26

Additional info:
reporter:       libreport-2.9.1
cmdline:        /usr/bin/python3 /usr/bin/lollypop
crash_function: get_album_artworks
exception_type: GLib.GError
executable:     /usr/bin/lollypop
kernel:         4.11.11-300.fc26.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
art_album.py:133:get_album_artworks:GLib.GError: g-io-error-quark: Error opening directory '/home/louis/Musique/Arctic Monkeys/Arctic Monkeys-Favourite Worst Nightmare': No such file or directory (1)

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lollypop/widgets_album.py", line 240, in _on_artwork_press_event
    popover = CoversPopover(self._album)
  File "/usr/lib/python3.6/site-packages/lollypop/pop_artwork.py", line 76, in __init__
    self._widget.populate()
  File "/usr/lib/python3.6/site-packages/lollypop/art_widgets.py", line 101, in populate
    uris = Lp().art.get_album_artworks(self.__album)
  File "/usr/lib/python3.6/site-packages/lollypop/art_album.py", line 133, in get_album_artworks
    None)
GLib.GError: g-io-error-quark: Error opening directory '/home/louis/Musique/Arctic Monkeys/Arctic Monkeys-Favourite Worst Nightmare': No such file or directory (1)

Local variables in innermost frame:
f: <lio.File object at 0x7f652bd10090 (GLocalFile at 0x562112fb50e0)>
album: <lollypop.objects.Album object at 0x7f6528073fd0>
self: <art.Art object at 0x7f65435ec3f0 (lollypop+art+Art at 0x562112eafba0)>

**Comment by gnumdk** [comment]
Fixed
