### ISSUE TITLE
have a playlist for never listened albums

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1201]
as the title said it woud be nice to have a section which display records which have never been listened so we could listen to it...and maybe have a section with never played songs too...that would be very nice...

**Comment by mray** [comment]
To be mean: this sounds a bit like cluttering the menu with entries for unpopular music.
To be fair: I see the benefit, but wouldn't that be covered most of the time by "recently added music"?

**Comment by legacychimera247** [comment]
wait...as i see there's a "never listened tracks" section in playlist which was just the idea i had...now it would be nice to have a "never listened albums" sections where (for example) an album gets removed only when you listened it in it's entirety or at least 90%

and not lot of time they are not unpopular...simply you forget they are there...

**Comment by mray** [comment]
I support your idea of having a `"never listened albums" ` playlist.  
My definition for entries would be: contain any number of never listened tracks.
The name is just a bit misleading if you have heard half of the album already.

*Btw, you may correct the issue title to have a "playlist" for never listened albums...*

**Comment by legacychimera247** [comment]
well the album could be there if there are 70% of unheard tracks  or more...and delete from there when you reach 70% of the album, then you could have other tracks in the never listened tracks playlist...

**Comment by gnumdk** [comment]
>well the album could be there if there are 70% of unheard tracks or more...and delete from there when you 
>reach 70% of the album, then you could have other tracks in the never listened tracks playlist...

Tried but to slow as SQLite has to do calculation on all db entries.

So, it will be: Albums containing a non listened track and with less than 10 play count.

**Comment by legacychimera247** [comment]
nice...thank you...
