### ISSUE TITLE
Importing music and keeping library organized

### ISSUE THREAD

**Issue by AnnoyingTechnology** [gnumdk/lollypop#1202]
Hello,
Three questions.
Does Lollypop keep the library folder organised (Artist/Album/tracknumber - trackname) ?
How to you add new tracks to your music library ? 
I can't find a "My Music" view, or "all tracks" view to have a full listing of the tracks, where is it located ? All I can find is album view, or artist then albums view.

I launched Lollypop and it loaded the content of my ~/Music/Library folder 
but now that I have new tracks to add, I can't find any import button, and drag-dropping the files into lollypop's window doesn't do anything.

Thanks.

Debian 9 / Lollypop 0.9.244

**Comment by d9h20f** [comment]
Where are the tracks you want to add? Lollypop is an album player with some support for playlists (not a drag and drop player) and will look in all folders you configure in Preferences -> Behaviour. You can also tell it to automatically update your library, so you don't have to manually refresh.

You manually organise your files however you want, Lollypop bases its library on the tags, not the folder/filenames.

"All tracks" doesn't really make sense for an album player.

**Comment by AnnoyingTechnology** [comment]
Ok thank you.
I didn't get that it was an "album player". The tracks I want to add can come from ~/Downloads after buying them. Or ~/Downloads after after downloading them using torrents, or even any other folder after ripping them from a CD.
I often buy 50+ tracks at a time, (two to four tracks per albums, not whole albums), so managing myself folders would be a real struggle. I guess this player just isn't right for my needs.
A player that keeps the files properly organised in the filesystem while providing a decent front with all sorts of views is a must for me. Similar to iTunes actually, be not as bloated.

**Comment by bil-elmoussaoui** [comment]
@AnnoyingTechnology just copy the files to a Music directory and add that directory to Lollypop ;)

**Comment by AnnoyingTechnology** [comment]
That doesn't organize the files properly, it just stays there, totally messy.

**Comment by bil-elmoussaoui** [comment]
@AnnoyingTechnology  the idea of sorting the music files in different directories could be done pretty easily using a simple python script. If you can explain more which features you think they are needed i can take care of that.

**Comment by AnnoyingTechnology** [comment]
Thanks. I could script that too, I could also develop a whole player by myself. But it would be silly to do something that others must have already done. 
I'm just looking for an iTunes clone, or a "Shotwell for audio files". 
Those two softwares handle playlists, and and keep file organized just the right way. 
Shotwell even offers options for the directory structure.

**Comment by d9h20f** [comment]
Sounds like https://github.com/quodlibet/quodlibet is what you're looking for. You can tell it to rename files based on any pattern you want. You could use the following pattern on your entire collection:
~/Music/<artist>/<album>/<tracknumber> - <title>

**Comment by gnumdk** [comment]
For me this kind of system is just the perfect way to make your collection out of control. Is this that hard to use nautilus to create a folder?

The Itunes system is just the only way to be sure user has no idea where his music is located.

**Comment by AnnoyingTechnology** [comment]
It's not "a" folder.
When you buy 100 tracks at a time, it's 100 artists folder to create, or locate (you'd have to search for each artist, see if you already have tracks from that artist or if you have to create the folder) + 100 albums, assuming you buy "CD Singles". So you'd have to create in each artist folder another folder. 200 folders, plus the hassle to check if it exists already or not.
And that's not all, you may not have typed properly the artist name or album name, so the ID3 tag and folder names could mismatch, that's ugly. 
Also, depending on the sources where you buy your track, some are name 00000-SOMETHINGUPPERCASE, other TrackNumber-AllFirstInCaps Arists AllFirstIsCapName... Have a software that manages cleanly the library means that it will rename ALL tracks in exactly the same way. A way that you can define (for example in Shotwell).
And some other issues. You rename your albums from your player, because there's a typo in the name. If you manage manually the folders, you've got yourself a inconsistency between ID3 tags and folder structure. Good luck finding the files is you change the first letter or that artist name. 

Not having a filesystem abstraction layer in your music player is the best way to have a total-mess in your Music folder.  I've used iTunes for 10 years, migrating from system to system, a while back I've even developed a webplayer, that interfaces with itunes database (XML) and track files, no problem. I've always known where my files were, and they have always been wonderfully organised. To the point that now that I have trashed iTunes software, I have a perfectly organised Music folder that any player accepts. The only issues for me is finding one that will keep on keeping it organized.

```
julienlocal@Mespilus:/home/julienremote/Music/Library$ exa --tree Avis*
Avishai Cohen
├── Almah
│  ├── 01 Overture 'Noam', Op.1.m4a
│  ├── 02 Song For My Brother.m4a
│  ├── 03 On a Black Horse _ Linearity.m4a
│  ├── 04 A Child is Born.m4a
│  ├── 05 Arab Medley.m4a
│  ├── 06 Southern Lullaby.m4a
│  ├── 07 Hayo Hayta.m4a
│  ├── 08 Shlosre.m4a
│  ├── 09 Kefel.m4a
│  └── 10 Kumi Venetse Hasadeh.m4a
├── Almah (24bits)
│  ├── 02 Song For My Brother.m4a
│  ├── 03 On a Black Horse _ Linearity.m4a
│  └── 05 Arab Medley.m4a
├── At Home
│  ├── 01 Feediop.m4a
│  ├── 02 Madrid.m4a
│  ├── 03 Leh-Lah.m4a
│  ├── 04 Remembering.m4a
│  ├── 05 Renouf's Last Tooth.m4a
│  ├── 06 Gershon Beat.m4a
│  ├── 07 No Words.m4a
│  ├── 08 Punk (DJN).m4a
│  ├── 09 Mediterranean Sun.m4a
│  ├── 10 Saba.m4a
│  └── 11 Toledo.m4a
├── Aurora
│  ├── 01 Morenika.m4a
│  ├── 02 Interlude In C Minor.m4a
│  ├── 03 El Hatzipor.m4a
│  ├── 04 Leolam.m4a
│  ├── 05 Winter Song.m4a
│  ├── 06 Iit's Been So Long.m4a
│  ├── 07 Alon Basela.m4a
│  ├── 08 Still.m4a
│  ├── 09 Shir Preda.m4a
│  ├── 10 Aurora.m4a
│  ├── 11 Alfonsina Y El Mar.m4a
│  ├── 12 Noches Noches _ La Luz.m4a
│  └── 13 Shalom Aleichem.m4a
├── Continuo
│  ├── 01 Nu Nu.m4a
│  ├── 02 Elli.m4a
│  ├── 03 One for Mark.m4a
│  ├── 04 Ani Maamin.m4a
│  ├── 05 Samuel.m4a
│  ├── 06 •Emotional Storm.m4a
│  ├── 07 Calm.m4a
│  ├── 08 Arava.m4a
│  ├── 09 Smash.m4a
│  └── 10 Continuo.m4a
├── Duende
│  ├── 08 Calm.m4a
│  └── cover.jpg
├── Duende (24bits)
│  └── 01 Signature.m4a
├── Gently Disturbed
│  ├── 01 Seattle.m4a
│  ├── 03 Lo Baiom Velo Balyla.m4a
│  ├── 05 Puncha Puncha.m4a
│  └── 10 Umray.m4a
├── Seven Seas
│  ├── 01 Dreaming.m4a
│  ├── 02 About A Tree (_Oyfn Weg Shteyt a Boym_).m4a
│  ├── 03 Seven Seas.m4a
│  ├── 04 Halah.m4a
│  ├── 05 Staav.m4a
│  ├── 06 Ani Aff.m4a
│  ├── 07 Worksong.m4a
│  ├── 08 Hayo Hayta.m4a
│  ├── 09 Two Roses (_Shnei Shoshanim_).m4a
│  └── 10 Tres Hermanicas Eran.m4a
├── Seven Seas (24bits)
│  ├── 01 Dreaming.m4a
│  ├── 03 Seven Seas.m4a
│  └── 06 Ani Aff.m4a
├── Unknown Album
│  ├── Live At 30, Leverkusener Jazztage 2009.m4a
│  └── Live at Paleo Festival 2012.m4a
└── with strings
   └── Nancy Jazz Pulsations 2013.m4a
Avishai Cohen & Nitai Hershkovits
└── Duende
   ├── 01 Signature.m4a
   ├── 02 Criss Cross.m4a
   ├── 03 Four Verses _ Continuation.m4a
   ├── 04 Soof.m4a
   ├── 05 All Of You.m4a
   ├── 06 Central Park West.m4a
   ├── 07 Ann's Tune.m4a
   ├── 08 Calm.m4a
   └── 09 Ballad For An Unborn.m4a
Avishai Cohen Quartet
└── Unknown Album
   └── Live at The Montreux Jazz Festival 2013 HD (Full length concert).m4a
Avishai Cohen Trio
├── From Darkness
│  ├── 01 Beyond.m4a
│  ├── 01 Crazeology.mp3
│  ├── 02 Abie.m4a
│  ├── 03 Halelyah.m4a
│  ├── 04 C#-.m4a
│  ├── 05 Ballad For An Unborn.m4a
│  ├── 06 From Darkness.m4a
│  ├── 07 Lost Tribe.m4a
│  ├── 08 Almah Sleeping.m4a
│  ├── 09 Signature.m4a
│  ├── 10 Amethyst.m4a
│  └── 11 Smile.m4a
├── Gently Disturbed
│  ├── 02 Chutzpan.m4a
│  ├── 04 Pinzin Kinzin.m4a
│  ├── 06 Eleven Wives.m4a
│  ├── 07 Gently Disturbed.m4a
│  ├── 08 The Ever Evolving Etude.m4a
│  ├── 09 Variations In G Minor.m4a
│  └── 11 Stuctures In Emotion.m4a
├── Live
│  ├── Ma Li Vela (Live).m4a
│  ├── Seven Seas (Live).mp3
│  ├── Shalom Aleichem (Live).m4a
│  └── Shalom Aleichem (Live) 2.m4a
├── Live @BERLIIN
│  └── Shalom Aleichem (Live).m4a
├── Live @Nice Jazz 2011
│  └── Shalom Aleichem (Live).m4a
├── Live @PALEO 2012
│  ├── Arab Medley (Live).m4a
│  ├── One for Mark (Live).m4a
│  └── Seven Seas (Live).m4a
├── Live @TSF Jazz
│  └── Seven Seas (Live).m4a
├── Live @Visioninmusica 2015
│  └── Seven Seas (Live).m4a
└── Live @WDR 2007
   └── Nu Nu (Live).m4a

```
Clean, simple.

**Comment by d9h20f** [comment]
@AnnoyingTechnology, please read my previous comment. Lollypop is not the player you are looking for. Quod Libet is. Use Quod Libet.

**Comment by AnnoyingTechnology** [comment]
Sorry @d9h20f I didn't see your comment and was answering to the gnumdk.
Thank you for that link. I do agree that lollypop doesn't fit for me.

**Comment by gnumdk** [comment]
Yes, but you are a geek. My girlfriend has a Mac and Itunes, she has no idea where music is located...

BTW I'm not closing this one, maybe later... For, now, Lollypop code needs to be cleaned, it's my mission for september as working on Eolie shows me all wrong parts of Lollypop code.

**Comment by AnnoyingTechnology** [comment]
Interesting, I just asked my girlfriend (mac+itunes) where her music was, she answer "in iTunes".  She doesn't know either.
More generally, it's apple's strategy to remove all sense of responsibility to its users. Storing contacts, pictures and other stuff "somewhere" in their "cloud". Providing a unified search engine/speech recognition search engine, so that you don't have to structure and organize your data. This is an extremely bad thing IMHO, and it's one of the reasons that made me quit Apple ecosystem.
Ideally there should be a way to have "convenient" softwares/solutions, without loosing on privacy,  responsibility side. One that would be available to non-it people.

**Comment by enaut** [comment]
@AnnoyingTechnology I usually organize my music with Picard: https://picard.musicbrainz.org/ but probably also available in your distros repositories.

Picard is quite good at:
  * completing the tags and metainformation from the onlinedatabase musicbrainz.org
  * moving and renaming the music to any format you desire

Setting up picard is pretty easy:
Go to: options -> options -> file naming
There you can set your prefered way of formatting and also your music directory. My formatting string is: 
```
$if2(%albumartist%,%artist%)/%album%/$if($gt(%totaldiscs%,1),%discnumber%-,)$num(%tracknumber%,2)$if(%compilation%, %artist% -,) %title%
```

Workflow when getting new music is:
  1. drop the files into picard
  1. group them to albums (usually simply drag all files from unmatched to clusters)
  1. then rightclick on a cluster select lookup
  1. then usually the tracks go to the right pane with nice and well defined tagging.
  1. you then click on the albums/tracks on the right and select save.
  1. your music is saved and moved to your collection where Lollypop will happily detect it and make it available to you with all its glory
  
It sounds quite complicated but its actually not you can try it. And it really organizes you collection well.

**Comment by AnnoyingTechnology** [comment]
Thanks. It would seem to do the trick quite well. I'll keep that alternative in mind.
But you can't deny that having this exact feature implemented right in the music player would be quite more comfortable, uh ?
It's probably even very fairly simple to implement, has Picard is likely to have a command line interface, or an API. 

Anyways, Picard seems to be a very nice tool to have.

**Comment by enaut** [comment]
There are players that include those features -  but I usually prefer to do it outside of the player. I can organize my collection with one tool and have the player just play my music - you know the 'unix way' ;). I can switch from player to player without worrying about the consistency of my music collection. 
To get a new organizing player to use the old directory structure is really hard - I have been there. Example: "Beatles, The" and "The Beatles" for directory names.

**Comment by AnnoyingTechnology** [comment]
Good point... you might be converting me ^^
How about playlists ? I still have mine in XML format from iTunes, how do you migrate them between players ?

**Comment by enaut** [comment]
I'm sory but I never used any playlists. So no good recommends :(.
using google I found: https://blog.bartlweb.net/2017/03/itunes-musikbibliothek-per-skript-in-m3u-playlists-konvertieren/

**Comment by AnnoyingTechnology** [comment]
Alright; then I'll use the code from my iTunes Web Interface I coded a while back. It was able to read properly iTunes playlists, so migrating them is one step away.
I was just wondering if there was a "standard" way of migrating playlists between linux players.

**Comment by gnumdk** [comment]
@AnnoyingTechnology Lollypop currently does not support m3u playlists import... Due to bug #144 
Now Jessie is not last Debian, I need to implement this later.

**Comment by gnumdk** [comment]
Just drag & drop on Lollypop window.
