### ISSUE TITLE
Genius lyrics error

### ISSUE THREAD

**Issue by nicxxx** [gnumdk/lollypop#1204]
**Environment**
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24.2/3.22.16-1
- GNU/Linux distribution: Manjaro 64bit

**Bug/Feature**
When klicking on the "lyrics" button while playing a song, the genius webpage shows a blank loading icon. After a few minutes there is the message: "Error performing TLS handshake: An unexpected TLS packet was received."

**Comment by gnumdk** [comment]
It's a strange bug but in WebKitGTK, not in Lollypop... :-1: 
BTW I need to handle error message.

**Comment by Pointedstick** [comment]
What's the bug # tracking the issue in WebKitGTK?

**Comment by gnumdk** [comment]
No idea but I never seen this bug in Eolie... And Lollypop WebKit usage is very basic.

**Comment by k-kirill** [comment]
Commenting out this line in widgets_web.py fixes the issue for me
`        settings.set_property("enable-html5-local-storage", False)`

**Comment by gnumdk** [comment]
@k-kirill Cool :-)
