### ISSUE TITLE
GStreamer plugin for Opus files doen’t work

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1209]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24.2 / 3.22.17-2
- GNU/Linux distribution: Fedora 26

• Installed as Flatpak from Flathub

Every time I open Lollypop, I get displayed a notification about a missing GStreamer plugin for Opus files. They don’t get listet in the library, too. But I can play them with Gnome-MPV or Totem.

//
I wouldn’t have found this bug, if I had deactivated all Lollypop notifications, like I normally do (but this is a completely fresh OS installation and I’ve yet forgotten to do so). So once more the request to provide an option for deactivating all song-switching notifications – this way we don’t need to block everything and find out such misbehaviour.

**Comment by gnumdk** [comment]
Please find on the net where is OPUS support in gstreamer ;)

**Comment by fbruetting** [comment]
Sadly, I have no idea about Gstreamer, but does this help you?
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-opusdec.html

**Comment by gnumdk** [comment]
Ok, support is missing from org.gnome.Platform, please report issue to flatpak project.

**Comment by fbruetting** [comment]
Thanks! I’ll do.
