### ISSUE TITLE
Album shown twice 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#121]
Hello, 
Sometimes the albums/artists are shown twice or more 
This is in the list of Artists
![capture du 2015-05-20 14 39 30](https://cloud.githubusercontent.com/assets/7660997/7725803/1a0b35b2-fefe-11e4-90e7-7788a62b12aa.png)
And this in the list of Albums
![capture du 2015-05-20 14 39 55](https://cloud.githubusercontent.com/assets/7660997/7725809/282e208c-fefe-11e4-826c-8b417c8c1c80.png)

I guess that the album/artist name must be converted to lowercase to avoid this kind of issues.

Thanks for the great application!!

**Comment by gnumdk** [comment]
Can you send me your ~/.local/share/lollypop/lollypop.db by email?

My email is in about dialog

**Comment by bil-elmoussaoui** [comment]
Done

**Comment by gnumdk** [comment]
Some tracks have "Sia " as artist, others "Sia"
Some tracks have "Of Fear", others "of Fear"

Fix your tags...

**Comment by bil-elmoussaoui** [comment]
Well, it's not the case. I fixed them using Puddletag and i still have the same issue that's why i reported this

**Comment by bil-elmoussaoui** [comment]
I just checked this again, and those are my tags. I did updated my library on Lollypop 
![capture du 2015-05-20 17 26 57](https://cloud.githubusercontent.com/assets/7660997/7729509/85cef83a-ff15-11e4-8064-f921430afc75.png)

**Comment by gnumdk** [comment]
Puddletag doesn't update modification time by default... Check settings and write tags again.

**Comment by gnumdk** [comment]
If modification time is OK, there is a bug in updater

**Comment by gnumdk** [comment]
Reset your db in dconf editor: db version key.

If it fixes tags, their is a bug in tag updater

**Comment by gnumdk** [comment]
Can you send me the album by gdrive or else?

**Comment by bil-elmoussaoui** [comment]
Well this seems to be a puddletag issue. I used EasyTAG and everything works fine! Thank you for the fast answers.
