### ISSUE TITLE
Resetting the DB destroys the GUI

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1210]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24.2 / 3.22.17-2
- GNU/Linux distribution: Fedora 26
- Installed via Flatpak

The GUI then is completely blocked. Here’s a screencast:
![peek 2017-08-07 16-00](https://user-images.githubusercontent.com/10520767/29029934-a5c1e1be-7b89-11e7-8bb6-dc7d786594e3.gif)

This doesn't always happen like this – in the first occurrence, the main window was destroyed and just the settings window remained.

**Comment by gnumdk** [comment]
It's wanted.

**Comment by fbruetting** [comment]
But I can’t use or even close the program anymore…?!

// Oh, I now see a small progress bar on the bottom, thought it would reset the DB in a millisecond by just deleting the file…
