### ISSUE TITLE
lollypop-portal keep crashing with flatpak

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1211]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.20
- GNU/Linux distribution: fedora workstation 26

### Bug/Feature
simply lollypop-portal crashes lot of times if lollypop is installed in flatpak...if it's installed in rpm then everything works fine...

**Comment by gnumdk** [comment]
You should be able to find output with journalctl

**Comment by legacychimera247** [comment]
well don't know for journal but that's what terminal output says, maybe it's helpful `(lollypop:2): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Gtk-Message: Failed to load module "pk-gtk-module"
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%204th%20of%20July.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Let%20Me%20Drown.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Black%20Hole%20Sun.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Fell%20on%20Black%20Days.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Fresh%20Tendrils.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Half.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Head%20Down.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Superunknown.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Kickstand.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Like%20Suicide.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Limo%20Wreck.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Mailman.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20My%20Wave.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20Spoonman.wma
CollectionScanner::__scan(add): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12) file:///home/luca247/Musica/Soundgarden/Superunknown/Soundgarden-%20The%20Day%20I%20Tried%20to%20Live.wma
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lollypop/lastfm.py", line 129, in get_artist_info
    language=getdefaultlocale()[0][0:2])
  File "/app/lib/python3.5/site-packages/pylast/__init__.py", line 2129, in get_bio_content
    return self.get_bio("content", language)
  File "/app/lib/python3.5/site-packages/pylast/__init__.py", line 2117, in get_bio
    self.ws_prefix + ".getInfo", section, params)
  File "/app/lib/python3.5/site-packages/pylast/__init__.py", line 1426, in _extract_cdata_from_request
    tag_name)[0].firstChild.wholeText.strip()
AttributeError: 'NoneType' object has no attribute 'wholeText'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lollypop/downloader.py", line 320, in __cache_artists_info
    (url, content) = method(artist)
  File "/app/lib/python3.5/site-packages/lollypop/downloader.py", line 112, in _get_lastfm_artist_info
    return Lp().lastfm.get_artist_info(artist)
  File "/app/lib/python3.5/site-packages/lollypop/lastfm.py", line 131, in get_artist_info
    content = last_artist.get_bio_content()
  File "/app/lib/python3.5/site-packages/pylast/__init__.py", line 2129, in get_bio_content
    return self.get_bio("content", language)
  File "/app/lib/python3.5/site-packages/pylast/__init__.py", line 2117, in get_bio
    self.ws_prefix + ".getInfo", section, params)
  File "/app/lib/python3.5/site-packages/pylast/__init__.py", line 1426, in _extract_cdata_from_request
    tag_name)[0].firstChild.wholeText.strip()
AttributeError: 'NoneType' object has no attribute 'wholeText'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/python3.5/site-packages/lollypop/downloader.py", line 332, in __cache_artists_info
    print("Downloader::__cache_artists_info():", e, artist)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2010' in position 7: ordinal not in range(128)
`

**Comment by gnumdk** [comment]
This is not portal...

**Comment by gnumdk** [comment]
Looks like an issue in pylast :-(
I may need to update the package!

**Comment by gnumdk** [comment]
This is the kind of issue that let me guess: "Flatpak sucks by goal"

Because if I need to monitor all deps for updates, I prefer current RPM/Deb/Pacman way of life ;)

**Comment by legacychimera247** [comment]
ok thanks :)

**Comment by gnumdk** [comment]
Package is rebuilding ;)

**Comment by bil-elmoussaoui** [comment]
@gnumdk I don't agree with you :p Flatpak by far is the greatest packaging system ever created on Linux so far. It's not perfect, not complete, but honestly, it's really so awesome :) Thanks to flatpak, use could use the latest software without having to upgrade their system. I agree that managing the packages, with their latest versions is a pain. But Flatpak can't package everything in the world for you. 
It's the same case whatever OS you're creating a software for :) if you use a last.fm library in Android, you will have to upgrade it if there's a new version and recompile the application for the users...

**Comment by gnumdk** [comment]
Yes, but I do not manage pylast for Fedora/ArchLinux/Ubuntu, it's updated by distro ;)

**Comment by legacychimera247** [comment]
unistalled the rpm version and downloaded the flatpak one...portal is not crashing anymore...i'll close this one :)
