### ISSUE TITLE
wma codec not recognized in flatpak installation

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1212]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.20
- GNU/Linux distribution: fedora workstation 26

### Bug/Feature
simply as the title say, if i install lollypop via flatpak it won't recognize albums in wma and it will tell me the wma plugin is missing...if i install it via rpm everything works fine...

**Comment by gnumdk** [comment]
Please tell me what gst module provides wma ;)

**Comment by legacychimera247** [comment]
well as i installed them through the software center i don't know but i assume the right package is the gstreamer lbav one...is the only one in store that does not list which format is playing but it just tell it plays a big number of formats...

**Comment by legacychimera247** [comment]
i just triyed totem and rhythmbox as flatpak and they fails to recognize formats installed through a 2rd part repo...maybe the issue is with flatpak itself?

**Comment by gnumdk** [comment]
Yes, you need to tell me what gstreamer plugin gives wma support. So that I can include it in flatpak package. It's not libav as provided by my flatpak.

**Comment by d9h20f** [comment]
Probably gstreamer-ffmpeg.

**Comment by legacychimera247** [comment]
yes gstreamer-ffmpeg should contain the wma codec...i found on the net that "gstreamer0.10-ffmpeg" contains it so i assume gstreamer-ffmpeg have it too...

**Comment by gnumdk** [comment]
no it's not the case with gstreamer 1.0 I guess...

**Comment by legacychimera247** [comment]
well so it's gstreamer ffmpeg

**Comment by gnumdk** [comment]
No, gstreamer-ffmpeg == gstreamer-libav

**Comment by legacychimera247** [comment]
so i don't have a clue...went into gstreamer site and seems that no component is offering a wma codec...this while lollypop in rpm has no problems at all...tried even with tracker info but did not give me any hint...

**Comment by gnumdk** [comment]
Send me a wma file by email ;)

**Comment by gnumdk** [comment]
gst-plugins-ugly-1.12.2-1

**Comment by gnumdk** [comment]
Lollypop is building with wma support ;)

**Comment by legacychimera247** [comment]
oh great...in reality in 40 gib of music i just have one wma album, but i tought about reporting anyway, so it will get better and better :)
