### ISSUE TITLE
Visual glitches with Numix gtk theme

### ISSUE THREAD

**Issue by k-kirill** [gnumdk/lollypop#1214]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: gtk-3.22.16
- GNU/Linux distribution: openSUSE Tumbleweed 20170729

### Bug
There are some visual glitches with Numix gtk theme (https://github.com/numixproject/numix-gtk-theme)
1) The "play" symbol icon in the header has the wrong color, though, the "pause" icon has the correct bright color. The "play" icon is painted correctly also in the fullscreen mode when not in the header.
2) The right border around clip art is missing in Radios view, though, the border is shown in All artist view.
![glitches](https://user-images.githubusercontent.com/8539168/29230504-06075eb8-7eec-11e7-8bc6-0cb65840f4f2.png)

I cannot reproduce these two issues using Adwaita gtk theme.

**Comment by JasonLG1979** [comment]
Invalid. File a bug with the theme.

**Comment by k-kirill** [comment]
For the record, the defect for the GTK theme: https://github.com/numixproject/numix-gtk-theme/issues/683

**Comment by k-kirill** [comment]
@gnumdk 
Is it possible to show sensitive GtkImage (play_image) on the sensitive play button? Becuase for now even though the button is sensitive the image itself is insensitive and some themes define styles for insensitive GtkImage causing the issue.

**Comment by JasonLG1979** [comment]
I don't presume to speak for @gnumdk but.

1. Yes it's possible. I'm pretty sure the GtkImage will inherit sensitive from it's parent button. So setting the Gtkimage to sensitive shouldn't hurt anything.
2. The columns probably should be homogeneous anyway.

I'll play with it real quick and see what it does.

**Comment by k-kirill** [comment]
@JasonLG1979 have you had a chance to look into the issue?

**Comment by JasonLG1979** [comment]
Neither seemed to have any effect either way for me?
