### ISSUE TITLE
Using deprecated schema paths 

### ISSUE THREAD

**Issue by da2x** [gnumdk/lollypop#1215]
Installing new Schemas
    warning: Schema 'org.freedesktop.Telepathy.Logger' has path '/apps/telepathy-logger/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.freedesktop.gstreamer-0.10.default-elements' has path '/desktop/gstreamer/0.10/default-elements/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.freedesktop.ibus' has path '/desktop/ibus/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.freedesktop.ibus.general' has path '/desktop/ibus/general/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.freedesktop.ibus.general.hotkey' has path '/desktop/ibus/general/hotkey/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.freedesktop.ibus.panel' has path '/desktop/ibus/panel/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.freedesktop.ibus.panel.emoji' has path '/desktop/ibus/panel/emoji/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.crypto.cache' has path '/desktop/gnome/crypto/cache/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.crypto.pgp' has path '/desktop/gnome/crypto/pgp/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.seahorse' has path '/apps/seahorse/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.seahorse.manager' has path '/apps/seahorse/listing/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.seahorse.recipients' has path '/apps/seahorse/recipients/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.system.locale' has path '/system/locale/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.system.proxy' has path '/system/proxy/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.system.proxy.http' has path '/system/proxy/http/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.system.proxy.https' has path '/system/proxy/https/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.system.proxy.ftp' has path '/system/proxy/ftp/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.
    warning: Schema 'org.gnome.system.proxy.socks' has path '/system/proxy/socks/'.  Paths starting with '/apps/', '/desktop/' or '/system/' are deprecated.

**Comment by gnumdk** [comment]
Not related to Lollypop.
