### ISSUE TITLE
Can’t scrobble to both Last.fm and Libre.fm at the same time

### ISSUE THREAD

**Issue by da2x** [gnumdk/lollypop#1216]
Currently, the user interface only allow people to submit their played tracks (“scrobbling”) to one service or the other, and not both at the same time.

The “Last.fm” plugin should probably be split into two different plugins: Last.fm and Libre.fm.  That way users could configure separate credentials for each service, and use them at the same time.

**Comment by d9h20f** [comment]
Why? Who does that?

**Comment by da2x** [comment]
Anyone who prefer Last.fm but suspect that they can’t keep the service afloat much longer so they’re hedging their bets by scrubbing to two services? The two services already focus on different metrics, so some immediate value for scrubblling to both also.

Anyway, there is no need to limit what the client can do – and the current UI with the toggle switch between the two services is a bit clunky. It would be more intuitive for users of either (or both) services if they were split up.

**Comment by d9h20f** [comment]
Makes sense, and I agree the toggle is less than ideal.

**Comment by gnumdk** [comment]
@da2x Please test current master and track any regression in LastFM/LibreFM code ;)
