### ISSUE TITLE
Disable headerbar by default outside of a GNOME + Mutter environment

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1219]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: GTK 3.22.11
- GNU/Linux distribution: KDE Plasma 4.9.4 in Kubuntu 17.04

### Bug/Feature
Lollypop's headerbar looks great in GNOME under Mutter, but ...less great everywhere else, due to irregularities and varying interpretations in how other window managers support GTK client-side decorations.

Lollypop includes an option to turn off the headerbar, presumably for Lollypop users in other environments.

It would be very nice if Lollypop turned the headerbar off automatically on first run if it detects that it's not running in GNOME under Mutter. That way non-GNOME users wouldn't have to know about this hidden feature and manually apply it (probably 99.9% won't know about it).

**Comment by gnumdk** [comment]
Was the case in the paste but users report me to enable headerbar by default.

**Comment by Pointedstick** [comment]
Users not using GNOME? Even people using KDE Plasma? That's hard to believe. Headerbars look somewhere between terrible and tolerable outside of Mutter.

I'm not saying turn it off by by default; I'm saying turn it off if the window manager isn't Mutter.

**Comment by gnumdk** [comment]
But mutter is not the only one to use CSD...

**Comment by d9h20f** [comment]
I don't understand why you would want to use a music player built for GNOME with KDE, which has a million great music players already. Do you use Nautilus on KDE, too?

**Comment by gnumdk** [comment]
One more thing, disable-csd option was here because of Unity... But I may remove it in the future as no GNOME application allow this.

**Comment by Pointedstick** [comment]
> I don't understand why you would want to use a music player built for GNOME with KDE, which has a million great music players already. Do you use Nautilus on KDE, too?

I haven't found any that behave how I like and don't need to take up like half the screen to be usable. Here is my list of requirements:

- Column browser that goes Genre > Artist > Album
- Shows album art everywhere
- Shows only non-redundant info, rather than lazily presenting a table view
- UI is clean, uncluttered, and non-confusing
- Functions well with a small window (for quarter-tiling on a 1080p screen)
- Reads and writes metadata (play count, rating, lyrics, etc) to files, not a database
- Albums are or can be sorted by year
- Rating system can be love/un-love rather than stars
- Static playlists
- Supports songs tagged with multiple genres
- Automatic lyric downloading [Lollypop doesn't do this, boo]
