### ISSUE TITLE
Mini Music Player

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#122]
Hello, 
i would like to ask you if you can add a mini music player as on Itunes and almost every music player...
This might be helpful if you want to keep the music player on the screen while doing something else.

Thank you!!

**Comment by gnumdk** [comment]
Sorry, don't want this kind of feature in lollypop...

If you want to control player, just install an MPRIS applet.

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/commit/0f9961d5399e4338b556fafebb7500b9168d595b
;)
