### ISSUE TITLE
(flatpak) system language is not respected

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1221]
when using lollypop in flatpak the language is set to english even if the system is in italian...this while the rpm app works flawlessy

for the record i am using latest gtk with fedora workstation 26...

**Comment by gnumdk** [comment]
Here, it's respected (ArchLinux)

**Comment by legacychimera247** [comment]
so they need to update flatpak runtime files?anyway i think you can close this one if you can't fix it :)

**Comment by gnumdk** [comment]
No idea, please ask on #flatpak at irc.freenode.net

Here it works too on Fedora.

**Comment by legacychimera247** [comment]
dunno why but after a "flatpak update" command everything is solved and every app respect system language...
