### ISSUE TITLE
Can't add/scan network locations

### ISSUE THREAD

**Issue by sdfg2** [gnumdk/lollypop#1224]
### Environment
- Lollypop version: 0.9.244-2
- GNOME/GTK+ versions: gtk3-3.22.18-2
- GNU/Linux distribution: Arch

### Bug/Feature
I'm not able to add network locations under "Other locations".  I put the correct URI in (nfs://server/path/to/music) but the connect button remains grayed out.  I edited the path directly in dconf-editor and tried to rescan the music, and this error was in the debug output.

`CollectionScanner::__get_objects_for_uris(): g-io-error-quark: Operation not supported (15)`

I've gone through all the prerequisites and all are installed.  I've tried both the community and AUR (git) packages, same thing.  I'm guessing it's a dep that's not been listed somewhere, but I have no idea what one! :-)

**Comment by gnumdk** [comment]
>I edited the path directly in dconf-editor

Does this uri work in nautilus?

**Comment by gnumdk** [comment]
@sdfg2 ping?

**Comment by gnumdk** [comment]
No response.
