### ISSUE TITLE
Have an option to view the ID3 tags of a song in the right click menu?

### ISSUE THREAD

**Issue by kepoorhampond** [gnumdk/lollypop#1227]
I just discovered lollypop, and I'm liking it a lot! My only issue- if you can call it that- is that I have a lot of notes in most of my songs, so it would be nice if I had an option to view them when I right clicked on the song.

**Comment by gnumdk** [comment]
Go outside lollypop goal...
BTW you can script this using the tag-editor key in dconf.
Will launch your command with filepath when clicking "modify information"
