### ISSUE TITLE
Adding every artist/album to a playlist

### ISSUE THREAD

**Issue by xJota** [gnumdk/lollypop#1230]
Hi, I just found out about lollypop and I'm loving it so far, there's just one thing keeping me from moving away from Clementine:

I have a folder with my main music files, which I already imported into Lollypop. However I have another folder (which I haven't imported) with hundreds of albums and other music that I occasionally listen to.

Is there any way I can create a playlist and add every music in my 'Main' folder to it, or just select every artist/album imported so far and add it all to that playlist? The only way I can manage to do this is by going through each album individually and adding it one by one to the playlist (would take me a looong time).

I need to do this because as soon as I import my gigantic second folder, my 'main' songs will be lost in the middle of the song abyss.

**Comment by gnumdk** [comment]
IMO, the best solution is to add a genre tag to filter the main music.

Ex: Radiohead => actual genre tag: Rock
Just edit it with easytag and set genre tag to Rock;Main
