### ISSUE TITLE
Crash with negative track numbers

### ISSUE THREAD

**Issue by xJota** [gnumdk/lollypop#1231]
### Environment
- Lollypop version: 0.9.244

### Bug/Feature

For some reason I have songs with negative track_numbers and Lollypop is not correctly handling them and crashing when I try to play said song. The issue is at **[line 395 in lollypop/mpris.py](https://github.com/gnumdk/lollypop/blob/master/lollypop/mpris.py#L395)**

I've added a print(str(track_number)) so we can see what track_number is being extracted:

```
4294967295
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lollypop/mpris.py", line 395, in __on_current_changed
    self.__update_metadata()
  File "/usr/lib/python3.6/site-packages/lollypop/mpris.py", line 337, in __update_metadata
    track_number)
  File "/usr/lib64/python3.6/site-packages/gi/overrides/GLib.py", line 243, in __new__
    (v, rest_format, _) = creator._create(format_string, [value])
  File "/usr/lib64/python3.6/site-packages/gi/overrides/GLib.py", line 126, in _create
    v = constructor(args[0])
OverflowError: 4294967295 not in range -2147483648 to 2147483647
```

The actual track_number inside the file metadata is -1, but it is being extracted as 4294967295 (since 2^32 -1 = 4294967295)

**Comment by gnumdk** [comment]
Can you check with current master as MPRIS module has been rewritten by @JasonLG1979.

**Comment by JasonLG1979** [comment]
I have 2 questions:
@gnumdk, Why even include the track number in the metadata. I'm not really aware of any client that even does anything with the track number?

 @xJota, Why do your songs have negative track numbers? You should probably fix your tags?

But back to the issue at hand. @gnumdk, is ```Lp().player.current_track.number``` actually returning -1 if the metadata contains -1 for a track number? I ask because this works just fine for me:

```python

from gi.repository import GLib

try:
    x = GLib.Variant('i', -1)
except GLib.Error as e:
    print(e)
else:
    print(x.get_int32())

```

**Comment by xJota** [comment]
No, ```Lp().player.current_track.number``` returns 4294967295

I will fix my tags, but I still felt the need to report this, a crash is a crash :)

**Comment by JasonLG1979** [comment]
Then it sounds like a database and/or metadata parsing issue not a problem with mpris.py

**Comment by xJota** [comment]
Since I can't test this right now, could you please try that code with 4294967295 instead of -1 ?

**Comment by JasonLG1979** [comment]
I really don't have to. I know that would fail. 4294967295 > 2147483647 which is the largest value possible for a 32bit signed int.

**Comment by JasonLG1979** [comment]
The track number can be clamped to always be in range. Something like this:

```python

from gi.repository import GLib

x = 4294967295
y = min(max(GLib.MININT32, x), GLib.MAXINT32) 
try:
    z = GLib.Variant('i', y)
except GLib.Error as e:
    print(e)
else:
    print(z.get_int32())

```

That prints 2147483647

**Comment by JasonLG1979** [comment]
If you wanted to make sure that the track number was always greater than -1(at least zero or a positive number) in range of an gint32 you could do something like this:

```python

from gi.repository import GLib

x = -4294967295
y = min(x if x > -1 else abs(x), GLib.MAXINT32) 
try:
    z = GLib.Variant('i', y)
except GLib.Error as e:
    print(e)
else:
    print(z.get_int32())

```

**Comment by JasonLG1979** [comment]
In the above case no matter what wack a doo number positive or negative you make x, y will always be 0 to 2147483647.

**Comment by gnumdk** [comment]
>is Lp().player.current_track.number actually returning -1 if the metadata contains -1 for a track number?

Yes

**Comment by JasonLG1979** [comment]
I disagree. The problem doesn't seem to be mpris.py. I think it's reasonable to assume that the track number would be in the range of a signed int. The problem is that somehow -1 is getting turned into 4294967295 for some reason before it gets to mpris.py.

**Comment by gnumdk** [comment]
>The problem is that somehow -1 is getting turned into 4294967295

I think two value depends of what has read the tag (gstreamer vs ...)

**Comment by JasonLG1979** [comment]
> I think two value depends of what has read the tag (gstreamer vs ...)

I'm unfamiliar with how you read the tags?

**Comment by gnumdk** [comment]
I use Gst.Pbutils but often, for broken values, it returns different values than Easytag for example.
