### ISSUE TITLE
Volume control not working for 20 seconds at start

### ISSUE THREAD

**Issue by madtel** [gnumdk/lollypop#1233]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.22.11-0ubu
- GNU/Linux distribution: Ubuntu 17.04

### Bug/Feature
When starting Lollypop volume control doesn't work until 20 seconds have passed.
If I turn down or up the volume nothing happens. After 20 seconds everything is fine

**Comment by gnumdk** [comment]
Does not happen here, volume control works from the start.

**Comment by gnumdk** [comment]
Looks like an Ubuntu issue, any ubuntu user able to reproduce?

**Comment by gnumdk** [comment]
@madtel What are your crossfade settings?

**Comment by madtel** [comment]
Hi, 
crossfade = track mixing? it's off.
Anyway this happen to me when listening to the radio as well when playing local music

**Comment by gnumdk** [comment]
@alexskc Can you test this as you have an ubuntu :)

**Comment by alex285** [comment]
@gnumdk what is the volume control? if you mean that system volume doesn't work in Lollypop, i cannot reproduce, either with the Flatpak or the system installation

**Comment by gnumdk** [comment]
@alex285 Volume control is an hidden feature => Alt + v

**Comment by alex285** [comment]
@gnumdk nice one! nop i cant reproduce the issue!

**Comment by gnumdk** [comment]
Ok, so not an issue in Lollypop, sorry @madtel Looks like a pulseaudio and/or gstreamer issue.
