### ISSUE TITLE
Display information in radios

### ISSUE THREAD

**Issue by sphh** [gnumdk/lollypop#1234]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: libgtk2.0-0: 2.24.30-1ubuntu1.16.04.2, libgtk-3-0: 3.18.9-1ubuntu3.3
- GNU/Linux distribution: Linux Mint 18.2 Cinnamon 64-bit

### Feature request
Internet radio streams often have some information about the artist/title/stream embedded. It would be really neat, if lollypop could display them.

**Comment by gnumdk** [comment]
It does... Hmm It did... :-1:

**Comment by gnumdk** [comment]
It does, but most of radio tags as reported as "." here by gstreamer but VLC and MPV are unable to read tags. Bug I found a working station:
![capture du 2017-09-02 15-47-50](https://user-images.githubusercontent.com/3918824/29995982-3ea35a36-8ff6-11e7-9549-3bc3c1f85cec.png)

**Comment by gnumdk** [comment]
Do you have a stream uri with tags?

**Comment by sphh** [comment]
No, you are absolutely right: Lollypop displays title and artist. The problem was that the built-in search turned up a stream without this information and not the stream I am used to use (which ships this information).

Sorry.
