### ISSUE TITLE
Issue on streaming internet radio

### ISSUE THREAD

**Issue by Ste74** [gnumdk/lollypop#1235]
### Environment
- Lollypop version: 0.9.244-2
- GNOME/GTK+ versions: 3.24.3
- GNU/Linux distribution: Manjaro
:
### Bug/Feature
Hi there , when open lollypop in radio section and select a radio the app say : 
impossible resolve server
stream doesn't contain enought data
internal stream error

But the same internet radio on rhythmenbox work fine.

**Comment by gnumdk** [comment]
Would be better with the radio URI.

**Comment by Ste74** [comment]
Hi , you are right :p sorry [here](http://streaming.radiodancefloor.it:443/)

**Comment by gnumdk** [comment]
Here it works, but what you give me is not radio URI, here it is:
http://185.92.223.206:443/live-hq

**Comment by Ste74** [comment]
The link above i send you i have take from lollypop . When use the search function and add to my radio playlist is the link i see.. In rhythmenbox i have copied the above link and him change the url +/- with your link but if i copy and paste your link in lollypop again lollypop warning me to not streaming enought ..

Is there a way to debug or reset lollypop if is my installation wrong ?

**Comment by gnumdk** [comment]
Don't know how Rhythmbox does this, but neither VLC or MPV plays this link:

http://streaming.radiodancefloor.it:443/

**Comment by Ste74** [comment]
Hi sorry for delay , tried other radio and this is the result
```
~ >>> lollypop --debug                                                                             [130]
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Lastfm::__connect(): Authentication Failed - You do not have permissions to access the service
ViewContainer::__delayedclean_view(): <view_albums.AlbumsView object at 0x7fa2d79335a0 (lollypop+view_albums+AlbumsView at 0x560d1354c140)>
ViewContainer::__delayedclean_view(): <view_first_run.FirstRunView object at 0x7fa2d405c4c8 (lollypop+view_first_run+FirstRunView at 0x560d1354c870)>
Error playing: http://185.92.223.206:443/live-hq
Toolbar::_on_current_changed
Error playing: http://185.92.223.206:443/live-hq
Toolbar::_on_current_changed
Error playing: http://185.92.223.206:443/live-hq
Toolbar::_on_current_changed
Error playing: http://hyades.shoutca.st:9113
Toolbar::_on_current_changed
Error playing: http://hyades.shoutca.st:9113
Toolbar::_on_current_changed
Error playing: http://hyades.shoutca.st:9113
Toolbar::_on_current_changed
Error playing: http://178.32.139.184:8110/
Toolbar::_on_current_changed
Error playing: http://178.32.139.184:8110/
Toolbar::_on_current_changed
Error playing: http://178.32.139.184:8110/
Toolbar::_on_current_changed
Error playing: http://nr11.newradio.it:9208
Toolbar::_on_current_changed
Error playing: http://nr11.newradio.it:9208
Toolbar::_on_current_changed
Error playing: http://nr11.newradio.it:9208
Toolbar::_on_current_changed

```
Don't know if this can help you .. can you give me a internet radio wich work for you ?

**Comment by gnumdk** [comment]
You are missing gstreamer codecs I guess...

**Comment by gnumdk** [comment]
http://185.92.223.206:443/live-hq is working here in Lollypop

http://nr11.newradio.it:9208 and http://hyades.shoutca.st:9113 are not working neither with VLC or MPV.

I'm sure it's not the same internet radio in Rhythmbox.

**Comment by Ste74** [comment]
Sorry for delay , this http://185.92.223.206:443/live-hq work only in ff , i tried on lollypop but it advice me to impossibility of resolve the name server and after the stream not contain data enought .. so is my installation wrong ? I have removed all lollypop related file in my home folder and removed it via pacman , reinstall not solve the problem . Gstreamer is installed yes ( plugin ugly,bad, good and also base)

**Comment by gnumdk** [comment]
Are you sure there is not an hidden char in uri?

**Comment by gnumdk** [comment]
lollypop http://185.92.223.206:443/live-hq

If it works, your entry in radios view is wrong

**Comment by Ste74** [comment]
Not work .. This is the output..
```
~ >>> lollypop http://185.92.223.206:443/live-hq --debug                                           [130]
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Error playing: http://185.92.223.206:443/live-hq
Toolbar::_on_current_changed
Error playing: http://185.92.223.206:443/live-hq
Toolbar::_on_current_changed
Error playing: http://185.92.223.206:443/live-hq
Toolbar::_on_current_changed
Lastfm::__connect(): Authentication Failed - You do not have permissions to access the service
ViewContainer::__delayedclean_view(): <view_albums.AlbumsView object at 0x7f07b4682c60 (lollypop+view_albums+AlbumsView at 0x555a7442a140)>
```

**Comment by gnumdk** [comment]
Do you have gst-libav installed?

**Comment by gnumdk** [comment]
And please test flatpak package...

**Comment by Ste74** [comment]
This is very odd :( .. resetting the dconf settings solve the issue :p

**Comment by gnumdk** [comment]
Really strange...
