### ISSUE TITLE
[flatpak]tag programs not recognized

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1236]
as the title says lollypop in flatpak is not able to launch tag editors...i have musicbrainz picard in flatpak and is not recognized while the rpm version has no problems at all...maybe i should use rpm version for the tag editor or simply this function is not working yet?

**Comment by gnumdk** [comment]
Picard is a flatpak package? No it's not working and Nautilus too is unable to launch flatpak package if I remember well.

**Comment by legacychimera247** [comment]
so i can close this one for the moment...
