### ISSUE TITLE
Application menu backfalls on Ubuntu 17.10

### ISSUE THREAD

**Issue by alex285** [gnumdk/lollypop#1238]
reproduce both with Flatpak and from PPA (in screenshot)
Lollypop 0.9.244

![screenshot from 2017-09-06 13-47-51](https://user-images.githubusercontent.com/11244308/30108208-2a9d89f0-930a-11e7-8393-5f7cac37e723.png)

**Comment by gnumdk** [comment]
What is: $XDG_CURRENT_DESKTOP ?

**Comment by gnumdk** [comment]
I'm sure they renamed XDG_CURRENT DESKTOP just because they enabled 3 extensions :-1:

**Comment by alex285** [comment]
@gnumdk correct :)
```
echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME
```

**Comment by gnumdk** [comment]
Thanks ;)

**Comment by gnumdk** [comment]
@alex285 If you can test and close ;)

**Comment by alex285** [comment]
@gnumdk i dont build Lollypop from source, so you should push on your PPA or Flatpak so i can test! ..and basically Flatpak is now broken in Ubuntu ..so i have only the PPA :)

**Comment by gnumdk** [comment]
@alex285 Package updated, can you test ? :-)
