### ISSUE TITLE
Syntax error while building

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#124]
Hello, 
I wanted to update Lollypop to the last version using git and while building i got this issue : 
/configure: line 13848: syntax error near unexpected token `1.35.9'
./configure: line 13848: `GOBJECT_INTROSPECTION_REQUIRE(1.35.9)'

Hope this might help you to fix it

**Comment by gnumdk** [comment]
Please install the needed packages...

**Comment by bil-elmoussaoui** [comment]
well, i have installed all the packages that you mentioned in the readme file.
this is the whole message : http://pastebin.com/1MXXvu1P

**Comment by gnumdk** [comment]
python-gobject is gobject-introspection

**Comment by bil-elmoussaoui** [comment]
i'm using a newer version of gobject-introspection and the autogen.sh keeps asking for 1.0?

**Comment by gnumdk** [comment]
Please ask on your distribution forum. No idea.

**Comment by gnumdk** [comment]
What is your os?

**Comment by bil-elmoussaoui** [comment]
Ubuntu gnome 15.04 with gnome shell 3.16 and i installed gobject-introspection 1.44.0

**Comment by gnumdk** [comment]
apt-get build-dep lollypop

**Comment by bil-elmoussaoui** [comment]
this what i get : 
``` 
E: Unable to find a source package for lollypop
``` 
and i'm using your official ppa repo: ``` ppa:gnumdk/lollypop ```

**Comment by gnumdk** [comment]
You need to enable sources in your package manager

**Comment by bil-elmoussaoui** [comment]
@gnumdk Thank you so much!! this is working

**Comment by gnumdk** [comment]
The missing dependencies was?

**Comment by bil-elmoussaoui** [comment]
i had to install those : ```
debhelper dh-apparmor dh-translations gnome-doc-utils gnome-pkg-tools
  libatk-bridge2.0-dev libatk1.0-dev libatspi2.0-dev
  libcairo-script-interpreter2 libcairo2-dev libdbus-1-dev libdbus-glib-1-dev
  libdrm-dev libegl1-mesa-dev libepoxy-dev libexpat1-dev libffi-dev
  libfontconfig1-dev libfreetype6-dev libgdk-pixbuf2.0-dev
  libgirepository1.0-dev libglib2.0-dev libgtk-3-dev libharfbuzz-dev
  libharfbuzz-gobject0 libice-dev libmirclient-dev libmircommon-dev
  libpango1.0-dev libpcre3-dev libpixman-1-dev libpng12-dev libprotobuf-dev
  libprotobuf-lite9 libpthread-stubs0-dev libsm-dev libwayland-dev libx11-dev
  libx11-xcb-dev libxau-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev
  libxcb-present-dev libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev
  libxcb-shm0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb1-dev
  libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev
  libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbcommon-dev
  libxrandr-dev libxrender-dev libxshmfence-dev libxtst-dev libxxf86vm-dev
  po-debconf python-gi-dev python-scour x11proto-composite-dev
  x11proto-core-dev x11proto-damage-dev x11proto-dri2-dev x11proto-fixes-dev
  x11proto-gl-dev x11proto-input-dev x11proto-kb-dev x11proto-randr-dev
  x11proto-record-dev x11proto-render-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev x11proto-xinerama-dev xorg-sgml-doctools xtrans-dev
  zlib1g-dev
```
