### ISSUE TITLE
Seek backwards and forwards by holding down the Media Previous and Media Next keys

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1240]
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: 3.22.11
- GNU/Linux distribution: Kubuntu 17.04

### Bug/Feature
It would be really cool if you could seek backwards and forwards by holding down the Media Previous and Media Next keys on your keyboard (if they're present). This is something that iTunes does, and it's really nice.

**Comment by gnumdk** [comment]
Media keys DBus API does not allow this.

**Comment by Pointedstick** [comment]
MPRIS has a seek() method that would accomplish this: https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Method:Seek

`xev` shows that holding down the rewind media key on my keyboard sends a series of events. It seems that Lollypop could simply listen for rapidly repeated events, interpret that as a desire to rewind or fast-forward, and then issue a MPRIS seek() command.

Am I off-track here?

**Comment by gnumdk** [comment]
The issue is that DBus is async and it's not possible to use a default timeout for seek. But maybe I can use input events (will not work with all keyboards)

**Comment by gnumdk** [comment]
The input event method is not working (only if Lollypop has focus)

The DBus method is not working because I do not get release event from Gnome Settings.

The only solution is to get Gnome Settings to provide a seek method through the org.gnome.SettingsDaemon.MediaKeys DBus protocol. 

So report upstream.

**Comment by Pointedstick** [comment]
Would that request need to be made to GTK, GNOME, or Freedesktop?

**Comment by gnumdk** [comment]
GNOME settings daemon at bugzilla.gnome.org

**Comment by Pointedstick** [comment]
Cool.

https://bugzilla.gnome.org/show_bug.cgi?id=788412
