### ISSUE TITLE
Wrong metadata of radio stations in MPRIS export

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1244]
### Environment
- Lollypop version: Flatpak
- GNOME/GTK+ versions: 3.24.2
- GNU/Linux distribution: Fedora 26

### Bug/Feature
I use this ”media player indicator” extension for displaying artist meta data in the top panel. But the radio station name gets displayed in the artists field (`trackArtist`), while both artist and title together get displayed as the title (`trackTitle`). So instead of
  `<artist> – <title>`,
I get
  `<radio station> – <artist: title>`.
Correct me if I’m wrong – I think that this is due to the MPRIS meta data export of Lollypop. Can you do something about this?

**Comment by gnumdk** [comment]
No I can't, you have the same in Lollypop, radios do not report artist/title, only title containing artist - title or artist / title or artist title or ...
