### ISSUE TITLE
Searching Quickly crashes lollypop

### ISSUE THREAD

**Issue by PeterHindes** [gnumdk/lollypop#1246]
### Environment
- Lollypop version: Lollypop 0.9.244

- GNOME/GTK+ versions: 
Gnome Version 3.24.2
gtk2 64 and 32 bit version: 2.24.31-1
gtk3 version: 3.22.21-1
gtk3 32/bit version: 3.22.19-1

- GNU/Linux distribution:
$ uname -r
4.12.10-2-zen
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

### Bug
When you search to fast (at an average typing rate) lollypop will crash and if started form a terminal the following output is displayed:

$ lollypop
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

(lollypop:21738): Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
Segmentation fault (core dumped)

**Comment by PeterHindes** [comment]
note: built from github page

**Comment by PeterHindes** [comment]
Why was this closed? Has it been resolved?

**Comment by gnumdk** [comment]
Just click on the closed link...

**Comment by PeterHindes** [comment]
Oh, didn't know that, thanks :-)
