### ISSUE TITLE
Preview will still play when song is playing over it

### ISSUE THREAD

**Issue by PeterHindes** [gnumdk/lollypop#1247]
### Environment
- Lollypop version: Lollypop 0.9.244

- GNOME/GTK+ versions: 
Gnome Version 3.24.2
gtk2 64 and 32 bit version: 2.24.31-1
gtk3 version: 3.22.21-1
gtk3 32/bit version: 3.22.19-1

- GNU/Linux distribution:
$ uname -r
4.12.10-2-zen
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

### Bug/Feature
When a song is playing hovering over a song should not play a preview of the new song

**Comment by legacychimera247** [comment]
you need to go into settings >behaviour and deselect "preview tracks on"

**Comment by gnumdk** [comment]
Preview is designed for headphone usage... You can listen songs in your headphone while lollypop is playing current playlist on current output.

**Comment by PeterHindes** [comment]
it would be nice if it was an option, although i see now what it is designed for

**Comment by gnumdk** [comment]
You are at a party, lollypop plays music and you can listen tracks in a headphone, useful when you don't remember tracks title...

**Comment by PeterHindes** [comment]
Yes but if I was searching for a song it would also be useful, but if I am
already playing a song it would interrupt it and be anoying, not everyone's
at a party, there's party mode for that .
