### ISSUE TITLE
feature request: synchronize playcounts with last.fm

### ISSUE THREAD

**Issue by silberzwiebel** [gnumdk/lollypop#1250]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24.2
- GNU/Linux distribution: Fedora 26

### Feature Request
First, thanks for a great music player!
Actually, my feature request has two points:
1. I couldn't find any information regarding the number of times I've played a song / album. Could you add this?
2. It would be lovely if one could synchronize these playcounts with the history built over years from last.fm.

Keep up the good work!

**Comment by gnumdk** [comment]
2 => Lastfm API does not allow this

**Comment by gnumdk** [comment]
2 is not that hard to fix but I need to check some old code is always working before.

**Comment by gnumdk** [comment]
2 is not possible. Last.fm Library does not provide get_tracks() anymore :-1:

**Comment by gnumdk** [comment]
get_top_tracks()/get_top_albums() allow to get some tracks/albums playcount, but it's not user playcount, it's all users playcount :-1:

**Comment by silberzwiebel** [comment]
Hnmm, okay.
You are using pylast for last.fm, correct? Doesn't this function help then:

https://github.com/pylast/pylast/blob/d6281e382962adc73b0269faf1177e18d97e08dc/pylast/__init__.py#L1698

Coming back to my first point: Does lollypop show the local playcounts somewhere in the UI?

**Comment by gnumdk** [comment]
First point is fixed, see gnumdk added a commit that referenced this issue 5 days ago...

**Comment by silberzwiebel** [comment]
Oh, sorry, I didn't see that. Thanks for the quick fix!
