### ISSUE TITLE
Add pulse audio media.role to .desktop

### ISSUE THREAD

**Issue by pdefert** [gnumdk/lollypop#1251]
Hi,

is possible to add 
`X-PulseAudio-Properties=media.role=music`
to org.gnome.Lollypop.desktop

it is  useful to mute the music when we receive  a call

you can find more information here : [http://www.webupd8.org/2013/06/how-to-automatically-mute-music-when.html](http://www.webupd8.org/2013/06/how-to-automatically-mute-music-when.html)

i tested it  and it works pretty well, but at each  update i must add the line in org.gnome.Lollypop.desktop

Thanks

**Comment by gnumdk** [comment]
Strange, the property is set by ENV in code...
