### ISSUE TITLE
Settings button not showing in Opensuse Tumbleweed

### ISSUE THREAD

**Issue by cpharlok** [gnumdk/lollypop#1252]
### Environment
- Lollypop version: tested with 0.9.244-62.4 and 0.9.244-1.1
- GNOME/GTK+ versions: 3.26.0
- GNU/Linux distribution: OpenSuse Tumbleweed

### Bug/Feature
Settings button does not show, impossible to configure lollypop.

![screenshot from 2017-09-28 04-28-29](https://user-images.githubusercontent.com/32348882/30946646-852ab09e-a405-11e7-9d60-b771a913b21d.png)

**Comment by cpharlok** [comment]
Hi, I leave here the bug I found working with Opensuse Tumbleweed (virtualized). Fresh install, system updated.

Thank you for the hard work with Lollypop, the best player for linux.

**Comment by gnumdk** [comment]
In Gnome Shell?

**Comment by cpharlok** [comment]
Yes

**Comment by gnumdk** [comment]
The menu is in Gnome Shell top bar ;)

**Comment by cpharlok** [comment]
As you said that the menu is in top bar, I have found were the problem was: If you use this gnome extension:

Window List Mod

The Lollypop settings menu disappear due to that extension, that's why I could not see it. 
Solution: Just disable that extension.

Thank you!
