### ISSUE TITLE
Do not hang while using gvfs collections.

### ISSUE THREAD

**Issue by 38github** [gnumdk/lollypop#1253]
What I use Clementine for is its ability to stream from Google Drive account which I have full of opus music. I think this would be a very useful feature in Lollypop.

**Comment by gnumdk** [comment]
Use gvfs for this, Lollypop should scan all supported protocols...

**Comment by gnumdk** [comment]
Tested with gvfs-google, account added in GNOME and all works... But Lollypop hangs because of artwork lookup I guess. Will fix this.

**Comment by gnumdk** [comment]
After some more testing, once all is cached by Lollypop, it's not that slow.
So closing.
