### ISSUE TITLE
Crash on start (Ubuntu 16.04)

### ISSUE THREAD

**Issue by repsorp** [gnumdk/lollypop#1255]
### Environment
- Lollypop version: 0.9.300
- GNOME/GTK+ versions: 
GTK3: 3.18.9-1ubuntu3.3
GTK2: 2.24.30-1ubuntu1.16.04.2

- GNU/Linux distribution: Ubuntu 16.04

### Bug/Feature

Lollypop crashes on start with following message:

File "/usr/lib/python3.6/site-packages/lollypop/application.py", line 205, in do_startup     self.init()   
File "/usr/lib/python3.6/site-packages/lollypop/application.py", line 155, in init     cssProvider.load_from_file(cssProviderFile) 
GLib.Error: gtk-css-provider-error-quark: application.css:125:14'min-height'

**Comment by gnumdk** [comment]
You can downgrade from /var/cache/apt

**Comment by gnumdk** [comment]
WTF, application.css was not modified since 10 month! My package never worked on Ubuntu Xenial?

**Comment by repsorp** [comment]
Previous version was just doing fine
Update broke it

**Comment by gnumdk** [comment]
Can you check what was previous version? (in apt cache)

**Comment by repsorp** [comment]
0.9.244-1

**Comment by gnumdk** [comment]
Ok, I know :-1: 
Removed some code and was sure it was related to Debian Jessie.

**Comment by gnumdk** [comment]
Someone can test current master?

**Comment by gnumdk** [comment]
Should be fixed

**Comment by gnumdk** [comment]
No it's not good :-( Help is welcome, patches/fix_xenial.patch is not applied

**Comment by KOT040188** [comment]
It did not help

**Comment by gnumdk** [comment]
Ok, patched the archive, so here special 0.300.1 release for ubuntu ;)
Building

**Comment by gnumdk** [comment]
Should be fixed

**Comment by repsorp** [comment]
not yet..

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lollypop/application.py", line 205, in do_startup
    self.init()
  File "/usr/lib/python3.6/site-packages/lollypop/application.py", line 155, in init
    cssProvider.load_from_file(cssProviderFile)
GLib.Error: gtk-css-provider-error-quark: application.css:125:14'min-height' is not a valid property name (3)

**Comment by gnumdk** [comment]
Are you sure you have 0.9.300.1 installed?

**Comment by gnumdk** [comment]
because there is no such line 155 in the package.

**Comment by repsorp** [comment]
"sudo apt remove --purge lollypop"
then apt install
http://ppa.launchpad.net/gnumdk/lollypop/ubuntu xenial/main amd64 lollypop all 0.9.300-1ppa1ubuntu1.2

**Comment by gnumdk** [comment]
No, it's not 0.9.300... It's 0.9.300.1

**Comment by gnumdk** [comment]
apt-get update

**Comment by gnumdk** [comment]
Maybe you need to wait some internal ppa updates ;) Or just get package here:
https://launchpad.net/~gnumdk/+archive/ubuntu/lollypop/+packages

and dpkg -i lollypop-....deb

**Comment by repsorp** [comment]
sorry my bad
It' working now (forgot to apt update..)

**Comment by repsorp** [comment]
tthanks a bunch
keep up the good work

**Comment by KOT040188** [comment]
Now lollypop is running.
