### ISSUE TITLE
Bug with progress bar

### ISSUE THREAD

**Issue by KOT040188** [gnumdk/lollypop#1256]
I have installed linux mint kde 18.2. Previously, kubuntu was installed on 16.04. In both systems, there is a bug https://www.youtube.com/watch?v=veJiuXNNLso

**Comment by gnumdk** [comment]
Not happening here... Looks like a KDE...
@repsorp Does it happen for you ?

**Comment by repsorp** [comment]
nope... running smoothly here

**Comment by gnumdk** [comment]
So it's a KDE bug

**Comment by KOT040188** [comment]
I like lollypop. I do not want to switch to gnome.

**Comment by gnumdk** [comment]
Try removing the KWIN plugin doing the effect on click

**Comment by gnumdk** [comment]
What say the tooltip when you move cursor hover progress bar? It's not a Lollypop tooltip!

**Comment by KOT040188** [comment]
<<Try removing the KWIN plugin doing the effect on click>> — I turned it on only to demonstrate the click of a mouse. If you turn it off, nothing will change.

**Comment by KOT040188** [comment]
What says the tooltip when you move cursor hover progress bar? It's not a Lollypop tooltip!
I do not see any tooltip when hovering over this strip

**Comment by gnumdk** [comment]
In the video I see one...

**Comment by gnumdk** [comment]
![capture du 2017-10-05 16-34-28](https://user-images.githubusercontent.com/3918824/31232767-1574ff3e-a9eb-11e7-9b52-5a91511f4585.png)

**Comment by KOT040188** [comment]
https://youtu.be/Q4KTvMDpVuA

**Comment by gnumdk** [comment]
Why do you have window close button in panel, I'm sure you are using some strange buggy Plasma widgets...

**Comment by KOT040188** [comment]
This has nothing to do with lollypop, nor with the bug.

**Comment by gnumdk** [comment]
XDG_CURRENT_DESKTOP=Unity lollypop

If it works, it's a KDE bug...

**Comment by KOT040188** [comment]
https://youtu.be/wtnYCLf5nP8

**Comment by KOT040188** [comment]
XDG_CURRENT_DESKTOP=Unity lollypop — what it is?

**Comment by gnumdk** [comment]
To run on the command line.
BTW:
- Downloaded Kubuntu 16.04
- Installed Lollypop on it
- It works!

So the issue is somewhere in your configuration. Sure it will work with a new user.

**Comment by KOT040188** [comment]
XDG_CURRENT_DESKTOP=Unity lollypop did not help.

**Comment by gnumdk** [comment]
Create a new user, it will work. So there something broken in KDE.

Everytime you click on lollypop titlebar, screen flickers, it's not normal!

**Comment by KOT040188** [comment]
Everytime you click on lollypop titlebar, screen flickers, it's not normal!
This can be seen only on the record. I have built-in graphics intell. Apparently because of this, flickering occurs.

**Comment by d9h20f** [comment]
Have you tried using Lollypop as a different user?

**Comment by KOT040188** [comment]
No. I do not have time for this yet. Transferring all settings from one user to another is not part of my plans. But I'll try to figure out what settings kde causes such a bug. Although I doubt the success.

**Comment by d9h20f** [comment]
You don't have to transfer any settings (it would be counterproductive), just check if a clean new profile also has the bug, so you know if the problem is caused by something in your home folder or by a broken system file/configuration.

**Comment by KOT040188** [comment]
I found the cause of this bug. In this picture http://itmages.ru/image/view/6170276/09ed80c9 I underlined the setting in the parameters of the kde system (sorry, I do not have the English interface language). This setting was turned off from me and this led to a bug.. By default, it is enabled. I never touched her. I do not know why she was turned off from me.
