### ISSUE TITLE
Lollypop Flatpak Version crashing when trying to add a radio from search.

### ISSUE THREAD

**Issue by Empathetic** [gnumdk/lollypop#1257]
**Environment**
- Lollypop version:0.9.300
- GNOME/GTK+ versions:3.22.2
- GNU/Linux distribution:Debian 9 Stretch

**Bug/Feature**
The Lollypop Flatpak is crashing whenever I try to add a radio from the search option, it was previously crashing because it was looking for a dir in ./local/share/lollypop/radios, I manually created the directory and it stopped crashing when I click on Radios. Now it's crashing when I try to add a radio.
This is the output I'm getting from the terminal:
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
TuneinPopover::_add_radio: g-io-error-quark: Operation not supported (15)
TaskHelper::__on_soup_msg_finished(): g-io-error-quark: Operation was cancelled (19)
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lollypop/helper_task.py", line 165, in __on_request_send_async
    stream = source.send_finish(result)
GLib.Error: g-io-error-quark: Operation was cancelled (19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lollypop/helper_task.py", line 173, in __on_request_send_async
    callback(None, False, b"", *args)
  File "/app/lib/python3.5/site-packages/lollypop/pop_tunein.py", line 291, in __on_item_content
    self.__radios_manager.add(name.replace("/", "-"), uri)
  File "/app/lib/python3.5/site-packages/lollypop/radios.py", line 66, in add
    (name, url, 0))
sqlite3.IntegrityError: NOT NULL constraint failed: radios.url

**Comment by gnumdk** [comment]
Ok, this one is fixed in master but there is another bug only happening on flatpak :-(

**Comment by gnumdk** [comment]
Fixed.

**Comment by Empathetic** [comment]
Not getting any errors in Lollypop now except for:
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
TaskHelper::__on_soup_msg_finished(): g-io-error-quark: Operation was cancelled (19)
TaskHelper::__on_soup_msg_finished(): g-io-error-quark: Operation was cancelled (19)
TaskHelper::__on_soup_msg_finished(): g-io-error-quark: Operation was cancelled (19)

It no longer crashes when clicking on a radio station or adding one but it doesn't play any either.

**Comment by gnumdk** [comment]
Fixed in master, will release an update tomorrow ;)

**Comment by gnumdk** [comment]
Flatpak is building, can you confirm it's fixed?

**Comment by gnumdk** [comment]
So it's fixed? You removed your comment...

**Comment by gnumdk** [comment]
Ok, playback does not work for me too :-1: 
Flatpak is making me crazy...

**Comment by gnumdk** [comment]
Ok, looks like totem-plparser is broken in my flatpak...

I LOVE RPM, I LOVE DEB! Packaging to the distro!!!!

**Comment by gnumdk** [comment]
Ok, looks my totem-plparser build is not working and I can't find a solution to make it working... :-1:

**Comment by gnumdk** [comment]
Building, this time it's fixed.

**Comment by Empathetic** [comment]
I'm actually using the flatpak from flathub and it still hasn't been updated there yet, I'll let you know in a day or two. If you say the Flatpak is fixed then it probably is, especially if you tested it yourself and were able to reproduce my experience. I'll wait a day or two, don't have much time to test right now.

**Comment by gnumdk** [comment]
23:37 < gnumdk> seems flathub is not building anything anymore, locked by Adapta build
23:38 < TingPing> gnumdk, i believe the arm builders are being migrated or something so 
                  everything is blocked

So you will have to wait ;)

**Comment by Empathetic** [comment]
Yeah, I figured. They have been updating their Flatpaks though, as they did upgrade Lollypop to 0.9.303 a few days ago. I'll wait a couple of days and then give you an update.

**Comment by gnumdk** [comment]
@Empathetic Package has been updated on flathub!

**Comment by Empathetic** [comment]
Still getting the same error on startup in addition to those last two lines complaining about adding a music uri to dconf. I'm no longer using Gnome, I'm on KDE:
 /usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
You need to add a music uri to org.gnome.Lollypop in dconf
You need to add a music uri to org.gnome.Lollypop in dconf

I'm about to just use the Launchpad Deb package, I give up. About to test those packages to see if I have similar issues.

**Comment by gnumdk** [comment]
Donc see errors here...

**Comment by Empathetic** [comment]
Let me correct myself then, still getting the same python outputs in the terminal in addition to the new:  You need to add a music uri to org.gnome.Lollypop in dconf lines. I'm using the .deb package from launchpad and it's working flawlessly. I give up on flatpak builds for now. You can go ahead and close this if you want, it might be an issue with the flatpak build on kde as I don't have Gnome installed so I don't have dconf on my system. Your flatpak build might be depending on dconf, while your regular packges don't.

**Comment by gnumdk** [comment]
@fbruetting Does it works for you now?

**Comment by fbruetting** [comment]
Works!
