### ISSUE TITLE
Crash when click on an album from last commits

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#126]
$ lollypop -d
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/lollypop/pop_artist_infos.py:91: Warning: invalid cast from 'lollypop+pop_artist_infos+ArtistInfos' to 'GtkPopover'
  Gtk.Popover.do_show(self)
Bus error (core dumped)

**Comment by gnumdk** [comment]
Can reproduce, please wait a little  before reporting bug ;)

**Comment by gnumdk** [comment]
Fixed... Strange it doesn't crash here !
