### ISSUE TITLE
(flatpak) No track appear in the list

### ISSUE THREAD

**Issue by piotrlyonnevitch** [gnumdk/lollypop#1260]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.303
- GNOME/GTK+ versions: flatpak -> runtime/org.gnome.Platform/x86_64/3.26
- GNU/Linux distribution: debian 9

### Bug/Feature
Hi,

I do not know if this is the right place to declare this bug or if I should do it on flathub.

I installed Lollypop with flatpak via the flathub deposit because when I try with the org.gnome.Lollypop.flatpakref downloaded from the site I encounter the following error:

```
flatpak install Téléchargements/org.gnome.Lollypop.flatpakref 
Installing: org.gnome.Lollypop/x86_64/stable
Warning: Can't find dependencies: GPG signatures found, but none are in trusted keyring
Warning: Problem looking for related refs: GPG signatures found, but none are in trusted keyring
Installing: org.gnome.Lollypop/x86_64/stable from org.gnome.Lollypop-origin
error: GPG signatures found, but none are in trusted keyring
```

The installation works from flathub but when I run Lollypop, no songs appear in the interface. If I run Lollypop from the terminal emulator, I get the following errors:

```
flatpak run org.gnome.Lollypop
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/overrides/Gst.py:217: Warning: g_object_set: assertion 'G_IS_OBJECT (object)' failed
  return Gst.ElementFactory.make(factory_name, instance_name)

(lollypop:3): GStreamer-CRITICAL **: gst_bin_add: assertion 'GST_IS_ELEMENT (element)' failed

(lollypop:3): GStreamer-CRITICAL **: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed

(lollypop:3): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(lollypop:3): GStreamer-CRITICAL **: gst_bin_add: assertion 'GST_IS_ELEMENT (element)' failed

(lollypop:3): GStreamer-CRITICAL **: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed

(lollypop:3): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

** (lollypop:3): WARNING **: can't find typefind element, decodebin will not work

** (lollypop:3): WARNING **: can't find typefind element, decodebin will not work

** (lollypop:3): WARNING **: can't find typefind element, decodebin will not work
CollectionScanner::__scan(add): gst-core-error-quark: Il manque un greffon dans votre installation de GStreamer. (12) file:///home/piotr/Musique/Pan%20Sonic/2010%20-%20Pan%20Sonic%20-%20Gravitoni/02-Wanyugo.flac

** (lollypop:3): WARNING **: can't find typefind element, decodebin will not work
CollectionScanner::__scan(add): gst-core-error-quark: Il manque un greffon dans votre installation de GStreamer. (12) file:///home/piotr/Musique/Pan%20Sonic/2010%20-%20Pan%20Sonic%20-%20Gravitoni/06-Trepanointi__Trepanation.flac

... and then all tracks, in flac, ogg or mp3 ...
```

The version of the gnome runtime is:

```
flatpak info org.gnome.Platform
runtime/org.gnome.Platform/x86_64/3.26 gnome 2872a29cca0f85ae0cc24976ee8f8fb3caed8ecfdab6764d9021e636e886b8b8
```

It's probably me who missed something but I can not find it.

Thanx for your help and sorry if I'm wrong location.

Piotr

**Comment by gnumdk** [comment]
Ok, missing flac support, do you know with gstreamer package provides flac support?

**Comment by d9h20f** [comment]
Has to be gstreamer-plugins-good: https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-plugin-flac.html

**Comment by gnumdk** [comment]
Broken runtime :(

**Comment by gnumdk** [comment]
@piotrlyonnevitch Can you send me a file by email?

**Comment by piotrlyonnevitch** [comment]
> Ok, missing flac support, do you know which gstreamer package provides flac support?

It seems to be the same with mp3 or ogg files :
```
** (lollypop:3): WARNING **: can't find typefind element, decodebin will not work
CollectionScanner::__scan(add): gst-core-error-quark: Il manque un greffon dans votre installation de GStreamer. (12) file:///home/piotr/Musique/Katerine/Katerine,%20Fran%C3%A7is%20Et%20Ses%20Peintres%20-%2052%20Reprises%20Dans%20L'Espace./Katerine,%20Fran%C3%A7is%20Et%20Ses%20Peintres%20-%202010%20-%2052%20Reprises%20Dans%20L'Espace%20-%20CD3/Katerine,%20Fran%C3%A7is%20Et%20Ses%20Peintres%20-%2015%20-%20Rectangle.mp3
```


> Broken runtime :(

That's what I thought. Is it I who set it wrong ? Or is it a problem with the runtime itself ?

> Can you send me a file by email?

Some track ?

(by the way, I installed the app with ppa on debian : its work well and I love it ! Thank you for your work)

**Comment by d9h20f** [comment]
Ogg makes sense because it's also part of gstreamer-plugins-good. MP3 is part of gstreamer-plugins-ugly.

**Comment by gnumdk** [comment]
MP3 is provided in Lollypop by gst-libav.
So I really don't understand what is happening on @piotrlyonnevitch computer.

**Comment by piotrlyonnevitch** [comment]
When you say that the runtime is broken, you think it's broken on my computer or in general ? Does it work on your computer when you install Lollypop from flathub ? I may have missed something at installation... I don't know very well flatpak.

As I said above, I can't install the downloaded Flatpak package on the Lollypop website (GPG error) so I use Flathub.

If it can help, on my computer Flatpak remote depositories are :
```
▶ flatpak remote-list                                                                                                           
flathub
gnome  
```

**Comment by piotrlyonnevitch** [comment]
Do you think I need to go back to https://github.com/flathub/flathub/issues

**Comment by gnumdk** [comment]
No, I'm maintaining the flatpak build so we can continue here. What is strange is that my flatpak package provides gst-libav which provides MP3 support :-/

**Comment by gnumdk** [comment]
rm -f ~/.var/app/org.gnome.Lollypop/cache/gstreamer-1.0/registry.x86_64.bin

Does it fix the issue?

**Comment by gnumdk** [comment]
>Téléchargements/org.gnome.Lollypop.flatpakref 

Ah ok, t'es français, pour aller plus vite, on va continuer dans la langue de Molière. Ce fichier n'est pas un paquet mais un fichier de description du dépot, il doit quand tu clic dessus ouvrir Gnome Software et installer Lollypop.

Pour ton problème, j'avais mal regardé:
/usr/lib/python3.5/site-packages/gi/overrides/Gst.py:217: Warning: g_object_set: assertion 'G_IS_OBJECT (object)' failed
  return Gst.ElementFactory.make(factory_name, instance_name)

Ce message ne veut dire qu'une chose, quelque chose est cassé sur ta machine, gstreamer (du paquet org.gnome.Platform) ne trouve plus ses petits. Je ne sais pas comment tu as installé flathub.

Essaye de tout nettoyer en commençant par supprimer le paquet flatpak de ton système puis:
\# rm -fr /var/lib/flatpak /home/USER/.local/share/flatpak /home/USER/.var

et recommence depuis le début.

**Comment by bil-elmoussaoui** [comment]
Ou juste mets à jour flatpak, avec la commande flatpak update. Parfois y a des petites beugs dans Gnome/freedesktop platform qui peuvent être résolu avec une simple mise à jour

**Comment by gnumdk** [comment]
Pas de un bug dans lollypop.
