### ISSUE TITLE
Database deleted

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1261]
### Environment
- Lollypop version: 0.9.303
- GNOME/GTK+ versions: 3.24 & 3.26
- GNU/Linux distribution: Fedora 26 & 27

### Bug/Feature
I updated Lollypop yesterday and all my radio stations were deleted. I haven’t used stars since my database was corrupted several times some time ago, so I don’t know if the whole DB was trashed. Additionally, when I now add radio stations, I see their image – which wasn’t the case before – but I cannot get them to play. I also don’t get any error output when I try to open them. At adding a radio station, however, I get:
`TaskHelper::__on_soup_msg_finished(): g-io-error-quark: Operation aborted (19)`
I then upgraded to F27, but still occurring.

**Comment by gnumdk** [comment]
Radios database has not been updated since years... So I guess you moved from flatpak to RPM...

**Comment by gnumdk** [comment]
Will give a look in my FC27

**Comment by gnumdk** [comment]
@fbruetting Flatpak or RPM?

**Comment by fbruetting** [comment]
Flatpak. Had to be the update one or two days before, because I update my system almost every day.


Am 12.10.2017 11:14 schrieb Cédric Bellegarde <notifications@github.com>:

@fbruetting Flatpak or RPM?

**Comment by gnumdk** [comment]
Ok, so it's fixed and related to #1257
