### ISSUE TITLE
Un-star by second click

### ISSUE THREAD

**Issue by mray** [gnumdk/lollypop#1262]
In order to un-star an album you currently have to *click an invisible area* next to the first star.  
I propose to use a second click on the current star to un-star an album. 

In this scenario ![image](https://user-images.githubusercontent.com/164785/31361201-763dabc6-ad52-11e7-96a9-b061ba621a5c.png) a click on the fourth star would remove all stars.

**Comment by gnumdk** [comment]
Not sure to love this behaviour, clicking on the left seems familiar for me, am I wrong?

**Comment by mray** [comment]
I didn't research, but my experience is that this is a new take on using stars.  
An invisible interaction element is uncommon and very hard to discover. Next to visible elements it is even harder to find. A slider of some kind could allow for "over sliding", but the clear breakdown into distinct stars makes it very button-like.
