### ISSUE TITLE
Lyrics tag not read for some files

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1263]
### Environment
- Lollypop version: 0.9.301
- GNOME/GTK+ versions: 3.22.11
- GNU/Linux distribution: Kubuntu 17.04

### Bug/Feature
For the following file (downloaded from Amazon MP3), I have written the lyrics into the id3 Lyrics tag using Picard. But Lollypop doesn't see them, and instead searches the internet for lyrics.

[01 - Herr Mannelig.zip](https://github.com/gnumdk/lollypop/files/1370094/01.-.Herr.Mannelig.zip)

**Comment by gnumdk** [comment]
Please confirm I do not break others files ;)

**Comment by Pointedstick** [comment]
I'd love to build from source, but the version of Meson you're targeting is too new for my Kubuntu 17.04 machine! 17.04 only has 0.39

**Comment by bil-elmoussaoui** [comment]
You can upgrade meson using sudo pip3 install --update meson

**Comment by Pointedstick** [comment]
Fixed with 0.9.304, no fallout seen with other files.
