### ISSUE TITLE
Song preview shouldn't work when a music is already playing

### ISSUE THREAD

**Issue by terencode** [gnumdk/lollypop#1265]
At the moment, you will have both the music you are listening to and the preview at the same time.
Either mute the current song while the preview is playing or only allow previewing a music when nothing is being played.

**Comment by gnumdk** [comment]
It should, it's not designed to used without an headphone configured as ouput.

**Comment by terencode** [comment]
I'm using an headphone configured as output and I can hear it overlapping. Or didn't I understand what you mean?

**Comment by gnumdk** [comment]
Actually, it only works with bluetooth headphone, I don't know why pulseaudio does not give me headphone as a separate device.
