### ISSUE TITLE
Music on a partition that is not allways mounted gets removed and readded every time

### ISSUE THREAD

**Issue by enaut** [gnumdk/lollypop#1266]
### Environment
- Lollypop version: git
- GNU/Linux distribution: Fedora 26

### Bug/Feature

I have my Music on a separate partition that is not automatically mounted. When I start lollypop without the partition being mounted it starts to remove/disable the tracks in the database one by one.

As soon As I realize my failure I mount the partition and now lollypop will go through all the files and readd them one by one.

**Suggested Solution:** Whenever the basic Music directory is not existing ask the user about removing "the whole collection".

Do I miss something? My current workaround is to add the mount command to the lollypop.desktop file.

**Comment by gnumdk** [comment]
It should not, will give a look.

**Comment by d9h20f** [comment]
Disable automatic refreshing of the database.

**Comment by jeims17** [comment]
You could also configure to mount the partitions on boot, but the suggested
solution is a good idea to implement

**Comment by gnumdk** [comment]
Lollypop should not update music if a collection is empty...

**Comment by gnumdk** [comment]
Ok, fixed: was working on empty collection but failing on missing directory :-1:

**Comment by enaut** [comment]
Thank you! I was just going to ask if that was the case...
And thanks for the hyper fast response!
