### ISSUE TITLE
Empty playlist at startup

### ISSUE THREAD

**Issue by KOT040188** [gnumdk/lollypop#1269]
I set in the settings to restore the previous state at startup. But every time you start lollypop, the current playlist is empty. And I have to create it anew. This is normal?

**Comment by KOT040188** [comment]
I would like to hear the answer to the question ...

**Comment by d9h20f** [comment]
https://github.com/gnumdk/lollypop/commit/0cb9348b7ab3f2338d98b9fc5688023c2dc72843
