### ISSUE TITLE
consider local images for cover search

### ISSUE THREAD

**Issue by eppixx** [gnumdk/lollypop#127]
When opening the cover search, lollypop doesn't search locally for images, which should be usefull when the cover is allready in the folder (but lollypop hasn't picked the right one) or when there is no internet connection.

**Comment by gnumdk** [comment]
This will write the local cover to cover.jpg... 

Not sure this what you want...

Having this copied in cache will not work as cache is cleaned on collection update.

**Comment by bil-elmoussaoui** [comment]
I guess he asks you to add the possibility to look for images in the same folder as the album too.
