### ISSUE TITLE
Duplicated entries for songs.

### ISSUE THREAD

**Issue by 999gary** [gnumdk/lollypop#1270]
### Environment
- Lollypop version: 0.9.304-1ppa1ubuntu1.1
- GNOME/GTK+ versions: GNOME 3.18.2
- GNU/Linux distribution: Ubuntu 16.04.3

### Bug/Feature
Upon using the Update Music option, all songs get duplicated entries.

**Comment by gnumdk** [comment]
Cool! But without more information, I can only close this...

Send me ~/.local/share/lollypop/lollypop.db by email.

**Comment by gnumdk** [comment]
What is MEGA directory, a special mount, a synced directory?

**Comment by 999gary** [comment]
synced, mega is a file hosting service I use, mega.nz, also for some reason it just stopped doing it even though it did it after rebooting twice so

**Comment by gnumdk** [comment]
Synced by?

**Comment by enaut** [comment]
mega is like dropbox but end to end encrypted. You have a client that syncronizes a directory with the cloud.

**Comment by gnumdk** [comment]
@999gary No problem anymore?

**Comment by gnumdk** [comment]
No response, closing.
