### ISSUE TITLE
Radio won't play from stream link

### ISSUE THREAD

**Issue by lukeoftheaura** [gnumdk/lollypop#1271]
### Environment
- Lollypop version: 0.9.303.1-1
- GNU/Linux distribution:Antergos

### Bug/Feature
I have a stream link (http://chipstream.rainwave.cc:8000/chiptune.ogg) that I add to the "radios" tab in lollypop. However, it won't play. It seems to show a loading bar for a fraction of a second, then the stream doesn't load.

**Comment by gnumdk** [comment]
Does gst-play-1.0 works? If not, go to Antergos forum.

**Comment by lukeoftheaura** [comment]
gst-play-1.0 works.

**Comment by gnumdk** [comment]
Bad news, it should not :p

Tested on Fedora, Ubuntu and ArchLinux, it works.

**Comment by gnumdk** [comment]
Can you provide some command line output while playing a radio. But I'm sure it's a but in your distribution.

**Comment by lukeoftheaura** [comment]
no command line output.

**Comment by gnumdk** [comment]
Are you using a flatpak version?

**Comment by gnumdk** [comment]
Flatpak package is broken, do not use it until flathub is working again... Don't know when :-1:

**Comment by lukeoftheaura** [comment]
not using flatpack, using arch linux package.

**Comment by gnumdk** [comment]
Not archlinux one because it works on archlinux.

**Comment by gnumdk** [comment]
Can you test with last flatpak package ? 0.9.304?

**Comment by lukeoftheaura** [comment]
> Not archlinux one because it works on archlinux.

what do you mean? I'm sure I'm running the latest archlinux one.

**Comment by gnumdk** [comment]
I mean it works on ArchLinux with all my devices and using http://chipstream.rainwave.cc:8000/chiptune.ogg

**Comment by gnumdk** [comment]
Have you tested with my flatpak package?

**Comment by gnumdk** [comment]
ping

**Comment by lukeoftheaura** [comment]
unfortunately I cannot test on the flatpak as it doesn't seem to start.

**Comment by gnumdk** [comment]
flatpak run org.gnome.Lollypop ?
Any output?

**Comment by lukeoftheaura** [comment]
I don't understand, do I have to install from flatpak first?

**Comment by gnumdk** [comment]
Yes

**Comment by gnumdk** [comment]
ping?

**Comment by lukeoftheaura** [comment]
I cannot install the flatpak.

**Comment by gnumdk** [comment]
Any error?

**Comment by gnumdk** [comment]
$ pacman -Q|grep gst

**Comment by lukeoftheaura** [comment]
```
clutter-gst 3.0.24-1
gst-editing-services 1.12.3-1
gst-libav 1.12.3+1+ge87c20d-1
gst-plugins-bad 1.12.3-1
gst-plugins-base 1.12.3-1
gst-plugins-base-libs 1.12.3-1
gst-plugins-good 1.12.3-1
gst-plugins-ugly 1.12.3-1
gst-python 1.12.3-1
gst-transcoder 1.12.1-1
gstreamer 1.12.3-1
gstreamer-vaapi 1.12.3-1
phonon-qt4-gstreamer 4.9.0-3
phonon-qt5-gstreamer 4.9.0-3
synfigstudio 1.2.1-2
```

**Comment by gnumdk** [comment]
Same package than you, same distro, here it works...

**Comment by lukeoftheaura** [comment]
would it be possible to actually get a debug log from lollypop for this, instead of not being able to fix it as it "works on your machine?"

**Comment by gnumdk** [comment]
GST_DEBUG=LOG lollypop

**Comment by gnumdk** [comment]
@lukeoftheaura Please post logs, I have time to look into this.

**Comment by lukeoftheaura** [comment]
[gst.log](https://github.com/gnumdk/lollypop/files/1454396/gst.log)

**Comment by gnumdk** [comment]
So it confirms: your OS is broken:
souphttpsrc gstsouphttpsrc.c:1270:gst_soup_http_src_parse_status:<source>^[[00m error: Error resolving “”: Name or service not known (2), URL: http://chipstream.rainwave.cc:8000/chiptune.ogg, Redirect to: (NULL)
No DNS resolution... Really strange it works with gst-play-1.0 ...

**Comment by lukeoftheaura** [comment]
Any idea of a fix?

**Comment by gnumdk** [comment]
Do you have a sock proxy?

**Comment by lukeoftheaura** [comment]
a sock proxy?

**Comment by gnumdk** [comment]
ok, so no...

**Comment by gnumdk** [comment]
Maybe try to disable ipv6

**Comment by gnumdk** [comment]
But you should ask Antergos/ArchLinux forum (post this issue URL)
Closing.
