### ISSUE TITLE
Lollypop does not honor track numbers from tags

### ISSUE THREAD

**Issue by FriesischScott** [gnumdk/lollypop#1272]
### Environment
- Lollypop version: 0.9.303
- GNOME/GTK+ versions: 3.26.1/3.22.24
- GNU/Linux distribution: Solus

### Bug/Feature
Lollypop does not honor track numbers from tags. If tracks are missing or songs are tagged incorrectly, lollypop will sort the songs in the right order but label them in ascending order instead of showing the numbers set in the tags.

**Comment by gnumdk** [comment]
There is an hidden option in dconf-editor

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/115
