### ISSUE TITLE
First album of an artist is not shuffled

### ISSUE THREAD

**Issue by Vaesper** [gnumdk/lollypop#1274]
### Environment
- Lollypop version: 0.9.303.1
- GNOME/GTK+ versions: 3.26.1
- GNU/Linux distribution: Arch Linux

### Bug
When playback mode is set to "Shuffle albums" and you click the "play" button on an artist's page, the first album in the list is always played first, the rest are shuffled. I would prefer if the first album in the list was also shuffled.

**Comment by gnumdk** [comment]
:+1:
