### ISSUE TITLE
Lollypop stops responding to media keys after Epiphany steals focus

### ISSUE THREAD

**Issue by d9h20f** [gnumdk/lollypop#1275]
If Lollypop is playing and Totem is opened, Totem starts responding to the media keys, and when Totem is closed, Lollypop responds to the media keys again. However, if you open Epiphany (in my case YouTube as a webapp) instead of Totem, and then close Epiphany again, Lollypop doesn't respond to the media keys anymore.

**Comment by gnumdk** [comment]
Why do you removed bug report headers?
So: please add them again with your version/distro/...

**Comment by d9h20f** [comment]
openSUSE Tumbleweed, everything is up to date (GNOME 3.26.1, Lollypop 0.9.304, etc).

**Comment by gnumdk** [comment]
So looks like a bug in GNOME. I need to give a look but since GNOME 3.26, media keys are just send as MPRIS command by gnome-settings-daemon.

**Comment by gnumdk** [comment]
Tested on Fedora 27, no issue here... And epiphany does not support MPRIS so it's really strange.
Report downstream.

**Comment by gnumdk** [comment]
Tested on ArchLinux, can't reproduce too.

**Comment by gnumdk** [comment]
Just to be sure, does it do the same without app mode?

**Comment by d9h20f** [comment]
I can't reproduce the problem anymore by opening Epiphany. Lollypop didn't respond to the media keys even after restarting it, but now suddenly it responds again. I don't know what changed because I haven't restarted Lollypop for two days now. Either way it looks like the bug is not in Lollypop, but I'll get back to you if I find out why it's happening.
