### ISSUE TITLE
Problems about sorting artists

### ISSUE THREAD

**Issue by Yakuky** [gnumdk/lollypop#1276]
### Environment
- Lollypop version: 0.9.303.1-1
- GNOME/GTK+ versions: 3.26.1
- GNU/Linux distribution: Arch

### Bug
<Describe your bug>
It seems that lollypop sorts artists by the first latin letter but not the first letter?
I have a song whose artist is 富永TOMMY弘明, and its sorting id3 tag is とみながTommyひろあき.
This item is sorted after T not と.

By the way, how is Japanese alphabet ordered? I guess its neither aiueo order nor iroha order.

**Comment by gnumdk** [comment]
>By the way, how is Japanese alphabet ordered? 
It's ordered by python strcoll()

**Comment by Yakuky** [comment]
![lollypop-sorting-issue](https://user-images.githubusercontent.com/9464864/32026802-6ae10ec0-b9ab-11e7-946b-03a6c76313a3.png)
This is a screenshot and you can see this name is sorted according to T not the first character.

**Comment by gnumdk** [comment]
OK, I did not understand because I'm missing some fonts :-)

**Comment by gnumdk** [comment]
Can you send me the file by email? Here it seems to be correctly sorted (tested in a python terminal).


Maybe related to LC_COLLATE?

locale.strcoll(string1, string2)
Compares two strings according to the current LC_COLLATE setting. As any other compare function, returns a negative, or a positive value, or 0, depending on whether string1 collates before or after string2 or is equal to it.

**Comment by Yakuky** [comment]
Yes you're right!
I add LC_COLLATE=C to locale.conf and there is no problem anymore!
