### ISSUE TITLE
Lollypop crashs 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#128]
Hello, Today i switched my library to an other disk. and this is happening whenever i open the lollypop using terminal 
  ```bash

lollypop:15531): libnotify-WARNING **: Failed to connect to proxy
Unhandled exception in thread started by <bound method CollectionScanner._scan of <CollectionScanner object at 0x7f76bf79aab0 (lollypop+collectionscanner+CollectionScanner at 0x1be0240)>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/collectionscanner.py", line 189, in _scan
    (new_tracks, new_dirs, count) = self._get_objects_for_paths(paths)
  File "/usr/lib/python3/dist-packages/lollypop/collectionscanner.py", line 111, in _get_objects_for_paths
    f = Gio.File.new_for_path(filepath)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce9' in position 73: surrogates not allowed
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1296, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.4/threading.py", line 1019, in _delete
    del _active[get_ident()]
KeyError: 140147750483712
  ```

if i open it without root permissions, the applications just closes without any error message.

**Comment by lazka** [comment]
The UnicodeEncodeError is caused by https://bugzilla.gnome.org/show_bug.cgi?id=746564

**Comment by gnumdk** [comment]
Are you sure your disk is mounted with Unicode ?

**Comment by bil-elmoussaoui** [comment]
I used Gnome disks for that. I fixed this using Nautilus File name repair extension. You can close this, but i would really like if you can just ignore the files with a UnicodeEncodeError in their names and show a message about this to the user.. or any other way to better handle this

**Comment by gnumdk** [comment]
I will ignore the error and print a message. Hope print will not raise an exception...

**Comment by bil-elmoussaoui** [comment]
You mean to show a notification?
