### ISSUE TITLE
Compatibility with pylast 2.0.0

### ISSUE THREAD

**Issue by alucryd** [gnumdk/lollypop#1280]
It looks like pylast 2.0.0 reworked how errors are handled, BadAuthenticationError doesn't exist anymore.

On Arch Linux: 
  cannot import name 'BadAuthenticationError'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist information disabled

**Comment by gnumdk** [comment]
pfff :-1: So I need to maintain to code path :-1:

**Comment by gnumdk** [comment]
Not that bad :-)

**Comment by gnumdk** [comment]
Feel free to patch your package :-)

**Comment by alucryd** [comment]
That was quick, thx!!
