### ISSUE TITLE
Gjs-Message Invalid result meta returned from search provider org.gnome.Lollypop.desktop

### ISSUE THREAD

**Issue by fermulator** [gnumdk/lollypop#1281]
### Environment
- Lollypop version:
```
$ dpkg --list | grep lolly
ii  lollypop                                                    0.9.304-1ppa1ubuntu1.1                       all          Lollypop is a GNOME music playing application.
```
- GNOME/GTK+ versions:
```
ii  gnome-session                                               3.18.1.2-1ubuntu1.16.04.2                    all          GNOME Session Manager - GNOME 3 session

$ dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:amd64             3.18.9-1ubuntu3.3         amd64        GTK+ graphical user interface library
ii  libgtk-3-0:i386              3.18.9-1ubuntu3.3         i386         GTK+ graphical user interface library
ii  libgtk-3-bin                 3.18.9-1ubuntu3.3         amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common              3.18.9-1ubuntu3.3         all          common files for the GTK+ graphical user interface library
ii  libgtk-3-dev:amd64           3.18.9-1ubuntu3.3         amd64        development files for the GTK+ library
ii  libgtk2-appindicator-perl    0.15-1build3              amd64        Perl bindings for libappindicator
ii  libgtk2-ex-podviewer-perl    0.18-1                    all          Perl Gtk2 widget for displaying Plain Old Documentation (POD)
ii  libgtk2-ex-simple-list-perl  0.50-2                    all          simple interface to Gtk2's complex MVC list widget
ii  libgtk2-gladexml-perl        1.007-2build2             amd64        Perl interface to use user interfaces created with glade-2
ii  libgtk2-imageview-perl       0.05-2build2              amd64        Perl bindings for the GtkImageView image viewer widget
ii  libgtk2-perl                 2:1.2498-1                amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2-unique-perl          0.05-2ubuntu1             amd64        module for single instance applications
ii  libgtk2.0-0:amd64            2.24.30-1ubuntu1.16.04.2  amd64        GTK+ graphical user interface library
ii  libgtk2.0-0:i386             2.24.30-1ubuntu1.16.04.2  i386         GTK+ graphical user interface library
ii  libgtk2.0-bin                2.24.30-1ubuntu1.16.04.2  amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-cil                2.12.10-6                 amd64        CLI binding for the GTK+ toolkit 2.12
ii  libgtk2.0-common             2.24.30-1ubuntu1.16.04.2  all          common files for the GTK+ graphical user interface library
ii  libgtk2.0-dev                2.24.30-1ubuntu1.16.04.2  amd64        development files for the GTK+ library
```

- GNU/Linux distribution:
```
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l


$ uname -a
Linux <hostname> 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Bug/Feature

Was monitoring /var/log/syslog for unrelated reasons, and noticed this message (pseudo-error-ish) from gnome-session complaining about something invalid returned from org.gnome.Lollypop.desktop. (the app wasn't even open!)

`Nov  3 01:30:07 <user> gnome-session[9238]: Gjs-Message: JS LOG: Invalid result meta returned from search provider org.gnome.Lollypop.desktop`

Looks like _something_ is running though
```
$ ps wauxxx | grep -i lollypop
fermula+ 14304  0.0  0.2 1223436 85560 ?       Sl   01:05   0:00 /usr/bin/python3 /usr/libexec/lollypop-sp
```

The impact is not known at this time. I opened Lollypop and played a music file, the error did not come again.

Message as appeared only once ever
```
$ grep -rins Lolly /var/log/* | grep Invalid
/var/log/syslog:159670:Nov  3 01:30:07 <hostname> gnome-session[9238]: Gjs-Message: JS LOG: Invalid result meta returned from search provider org.gnome.Lollypop.desktop
```

**Comment by gnumdk** [comment]
It's normal, it's not the app but the Gnome Shell search provider, will give a look but hard to fix without more information from Gnome Shell :-1:

**Comment by fermulator** [comment]
Was thinking there was some sort of notification API we weren't pushing to correctly.  Presumably gnome-shell search has a defined API and we could confirm t hat we're sending the right or wrong stuff?

**Comment by gnumdk** [comment]
Yes, but lollypop-sp is returning arrays or empty arrays so the error is in content. I suspect an issue in Gnome Shell with some encoding.
BTW, without full dbus-monitor log of the issue.

You should be able to reproduce by searching in shell.

**Comment by fermulator** [comment]
Confirmed reproduction. A simple "search" operation for "lolly" in gnome-shell yields:
`Nov  4 22:58:50 fermmy gnome-session[9238]: Gjs-Message: JS LOG: Invalid result meta returned from search provider org.gnome.Lollypop.desktop`

**Comment by gnumdk** [comment]
Ok, so it's a Gnome Shell issue, can't reproduce here with Gnome Shell 3.24...

**Comment by fermulator** [comment]
Confirmed reproduction. A simple "search" operation for "lolly" in gnome-shell yields:
`Nov  4 22:58:50 fermmy gnome-session[9238]: Gjs-Message: JS LOG: Invalid result meta returned from search provider org.gnome.Lollypop.desktop`

**Comment by gnumdk** [comment]
@fermulator ? :-)

BTW, you need to reproduce with last GNOME release, 3.18 is outdated.

**Comment by fermulator** [comment]
Why; we should support backwards compatibility; with at least some key version players...
I'm on a Ubuntu LTS 16.04 release, they don't run "latest gnome shell" it's unstable

**Comment by fermulator** [comment]
F. Why can't I re-open a git issue?

**Comment by gnumdk** [comment]
Because I do not have time trying to fix something that is not a Lollypop bug and that seems already fixed in Gnome Shell.

**Comment by gnumdk** [comment]
And for information, LTS is about packages stability(no breakage, no deps issues, ...), not software stability. 
3.18 GNOME stack is full of bugs fixed in 3.24...

**Comment by fermulator** [comment]
LTS _is_ about software stability.

But anyway, if you confirmed its fixed on the latest gnome-shell. Fine.

**Comment by gnumdk** [comment]
No, you are wrong, LTS is about support, not stability.

Ubuntu 16.04 is full of bugs/crash/... already fixed in recent distributions, I will not be packaging patched package otherwise :p

**Comment by gnumdk** [comment]
Finnaly, got it, killed it ;)
