### ISSUE TITLE
Ability to disable the star rating/"popular albums" feature

### ISSUE THREAD

**Issue by lukeoftheaura** [gnumdk/lollypop#1282]
could you add an ability to disable the star rating/popular albums feature?

**Comment by d9h20f** [comment]
Why?

**Comment by lukeoftheaura** [comment]
I never use it, and it just gets in the way. It's the first tab that opens when I start the program and it's just empty because I never use it, and whenever I listen to an album it tries to add it there even if it's not an album I like. I see how it's a useful feature for something like a jukebox but it's useless for a music player only one person is using.

**Comment by d9h20f** [comment]
You could just not look at it. Lollypop opens on whichever page you were on when you closed it anyway.

**Comment by gnumdk** [comment]
@d9h20f If save state is on ;)

BTW, wont fix and no it's not only useful for a jukebox. It shows me my favorite albums without any action from me... But yes, if you don't use Lollypop for some month, it's useless.

**Comment by lukeoftheaura** [comment]
maybe I am misunderstanding the feature, but it seems to just add all the albums I listen to to this list.

**Comment by gnumdk** [comment]
It order albums by popularity, ie albums you listen the most
