### ISSUE TITLE
Running with parameter `--version` starts the program

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1284]
### Environment
- Lollypop version: 0.9.304 Flatpak
- GNOME/GTK+ versions: 3.26.1
- GNU/Linux distribution: Fedora 27b

### Bug
Querying `lollypop --version` should just output the version number, but instead it starts the application. When I tried this on a local install (in contrast to now using Flatpak) some time ago, the current instance (which played music at that time) even crashed after I invoced that command.

```
$ flatpak run org.gnome.Lollypop --version
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Lollypop 0.9.304
```

**Comment by gnumdk** [comment]
ok, some regression here :-1:
