### ISSUE TITLE
artist will not show up in the Artist column on the left if albumartist tag is present

### ISSUE THREAD

**Issue by monoton1** [gnumdk/lollypop#1287]
### Environment
- Lollypop version: 0.9.304
- GNOME/GTK+ versions: 3.18.5
- GNU/Linux distribution: Ubuntu 16.04 LTS

### Bug/Feature
File type: FLAC
Tag info:
title: Come Rain or Come Shine (live, unplugged)
artist: Don Henley
album: The Unplugged Collection Volume One
albumartist: Various Artists

The track will show up in the left column as Various Artists but not as Don Henley.
At time of testing I have 6 tracks with the albumartist tag and they will only be shown as Various Artists.

**Comment by gnumdk** [comment]
Wanted behaviour, just remove albumartist tag.

**Comment by gnumdk** [comment]
But it's a compilation so it will be moved to compilations...
