### ISSUE TITLE
No longer responds to media keys after upgrade to Kubuntu 17.10

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1289]
### Environment
- Lollypop version: 0.9.304
- GNOME/GTK+ versions: 3.22.24-0ubuntu2
- GNU/Linux distribution: Kubuntu 17.10

### Bug/Feature
I just upgraded from Kubuntu 17.04 to 17.10 and now Lollypop doesn't respond to my keyboard's media keys. This only happens with Lollypop; all other media players I had handy (Clementine, Amarok) continue to work just fine with the media keys. So there seems to be some adverse interaction only with Lollypop.

**Comment by gnumdk** [comment]
Will not work anymore until KDE add a kded plugin transforming media keys to MPRIS call.
Gnome 3.26 does like this now, it's really better and smarter but the bad side is that it's broken for others DE.

**Comment by Pointedstick** [comment]
I'm pretty sure Plasma already has MPRIS support and that the media keys emit MPRIS calls.

**Comment by d9h20f** [comment]
Maybe related to https://github.com/gnumdk/lollypop/issues/1275. Since then it has happened a couple more times, but I still haven't found what the real cause is.

**Comment by gnumdk** [comment]
No, unrelated, in previous GNOME version, media keys was a DBus service started on demand.
Since 3.26 it's just gsd that translate key events to MPRIS events.

@Pointedstick I'm quite sure KDE does not emit MPRIS call, it would work otherwise. In my mind, KDE does not provide any API for this and let applications listen to global key event via khotkeys.

But you can check with dbus-monitor to confirm.

**Comment by gnumdk** [comment]
@Pointedstick /usr/lib/gnome-settings-daemon/gsd-media-keys
Running this by hand should fix the issue.

**Comment by gnumdk** [comment]
But the better solution is to implement this in kded, this make sense for KDE too!

**Comment by Pointedstick** [comment]
Nope, running  /usr/lib/gnome-settings-daemon/gsd-media-keys doesn't help. It does howver print the following:
```

$ /usr/lib/gnome-settings-daemon/gsd-media-keys

(gsd-media-keys:20586): media-keys-plugin-WARNING **: Unable to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
```

**Comment by gnumdk** [comment]
Seems it needs gnome-session :-/
And about dbus-monitor on key-press?

**Comment by Pointedstick** [comment]
dbus-monitor shows events when I press the brightness keys, but not the media keys.

It would be a real shame if Lollypop starts straight-up requiring GNOME for full functionality, because I really love it but GNOME isn't my cop of tea.

**Comment by gnumdk** [comment]
https://github.com/pithos/pithos/issues/450
They say KDE use MPRIS too so it should work!

**Comment by gnumdk** [comment]
https://github.com/bastibe/KDE-Media-Keys

Seems to be a KDE issue, was working previously in GNOME by chance (you were using a GNOME services) but if KDE MPRIS support is not working, report a bug at bugs.kde.org ;)

**Comment by gnumdk** [comment]
But KDE-Media-Keys is a temp solution ;)

**Comment by Pointedstick** [comment]
I found the problem. For some bizarre reason, Pidgin was hogging the media keys. Quitting and re-opening it made it let go, and now Lollypop works with the media keys again. *shrugs*
