### ISSUE TITLE
The previous button dosn't work as expected

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#129]
The previous button always move the the start of the current song, not to the previous song.

**Comment by gnumdk** [comment]
Not here, give me more informations...

**Comment by gnumdk** [comment]
Hmm, ok, i see

**Comment by yoseforb** [comment]
Also, moving to the next song by type 'n' cause a crash:
$ lollypop 
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/window.py", line 306, in _on_player_action
    Lp.player.next(True)
TypeError: next() takes 1 positional argument but 2 were given

**Comment by yoseforb** [comment]
Thanks, it works now.

Btw, can you please push my Hebrew translation from transefix to the git tree?

**Comment by gnumdk** [comment]
I will update all translations soon ;)
