### ISSUE TITLE
launch crach

### ISSUE THREAD

**Issue by ryokubu** [gnumdk/lollypop#1290]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.304
- GNOME/GTK+ versions: 3.24.0/3.22.19
- GNU/Linux distribution: gentoo

### Bug/Feature
<Describe your bug/feature here>

While opening lollypop>0.9.3
traceback:
can use starred expression only as assignment target (lastfm.py, line 363)
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist information disabled
$ sudo pip3 install pylast
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/lib64/python3.4/site-packages/lollypop/application.py", line 36, in <module>
    from lollypop.utils import is_gnome, is_unity
  File "/usr/lib64/python3.4/site-packages/lollypop/utils.py", line 18, in <module>
    from lollypop.helper_task import TaskHelper
  File "/usr/lib64/python3.4/site-packages/lollypop/helper_task.py", line 48
    
                   ^
SyntaxError: can use starred expression only as assignment target

**Comment by ryokubu** [comment]
[Support for python 3.4](https://github.com/AnarchyTools/anarchy_sphinx/pull/3/commits/7c0329a628f19297bc3094890a5e1be10730a05d)
Similar solution may be valid.

**Comment by gnumdk** [comment]
Lollypop minimal version is python 3.5... (Only based on Debian stable).
