### ISSUE TITLE
Fullscreen mode: Make better use of screen real estate

### ISSUE THREAD

**Issue by palob** [gnumdk/lollypop#1291]
- Lollypop 0.9.304
- GNOME 3.26 - Xorg Session GTK+ 3.22.26
- Arch Linux

Some screenshots at different resolutions:

1366x768
![1366x768_2](https://user-images.githubusercontent.com/7050624/32984940-5047968e-ccb0-11e7-84ab-73ac689b0408.png)
![1366x768_3](https://user-images.githubusercontent.com/7050624/32984941-508f5eb0-ccb0-11e7-9e8d-f34dbf5cdaa3.png)

1680x1050
![1680x1050](https://user-images.githubusercontent.com/7050624/32984943-57be6a78-ccb0-11e7-9dfb-8e4784deb531.png)

3840x2160 (x2 scaling)
![3840x2160_x2](https://user-images.githubusercontent.com/7050624/32984982-77208bda-ccb0-11e7-9cb9-163076dc16bd.png)

3840x2160 (x3 scaling)
![3840x2160x3](https://user-images.githubusercontent.com/7050624/32985014-ef4c630e-ccb0-11e7-898f-cb714011c4f4.png)

Generally I think there is pretty much unused greyspace (or whatever the theme colour is).
I think those **...**-abbreviated artist/album/title names are really ugly. There should be line breaks instead (or maybe a smaller font).

Furthermore, how about showing the album art at a bigger size and decentering the playback controls such that it is justified with the artist/album/title description?

By the way, fullscreen mode doesn't work at all with the screen turned by 90 deg.
![bildschirmfoto vom 2017-11-18 22-46-00](https://user-images.githubusercontent.com/7050624/32985080-7237dcb6-ccb2-11e7-8cab-ab3e9c2b69fd.png)

**Comment by gnumdk** [comment]
Can you test with new layout?

**Comment by palob** [comment]
With pleasure, will do.

**Comment by palob** [comment]
Looks like this now.
![bildschirmfoto vom 2017-12-04 23-22-38](https://user-images.githubusercontent.com/7050624/33579418-14fc0a96-d94a-11e7-81b8-717819dfc40a.png)

More space for text and everything centred but the *next title* looks out of place.
Album cover size is unchanged, I take it?

**Comment by gnumdk** [comment]
Yes, I need to change the logical, cover size was calculated based on current width... No it should be on current height.

**Comment by gnumdk** [comment]
Should be better now, next widget is linked to next button.

**Comment by palob** [comment]
![bildschirmfoto vom 2017-12-05 09-18-02](https://user-images.githubusercontent.com/7050624/33596793-51640b52-d99d-11e7-984a-c477b8e14a0b.png)
Yep, doesn't overlap anymore.
