### ISSUE TITLE
Heavy stuttering at playback of CDs

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1292]
### Environment
- Lollypop version: Lollypop 0.9.304
- GNOME/GTK+ versions: 3.26 / 3.22.25
- GNU/Linux distribution: Fedora 27

### Bug/Feature
I use Lollypop/Flatpak. Whenever I try to play a CD, I have a repeated pattern of a few seconds music and then a few seconds hanging. I tried several CDs, all with the same result.

**Comment by gnumdk** [comment]
Lollypop is not designed to play CD... No idea how you managed to do that.

**Comment by fbruetting** [comment]
Right-click ⇒ Open with Lollypop? O_o xD

**Comment by gnumdk** [comment]
No, but should be cool to avoid Lollypop from playing that... Sure you are using a desktop gvfs/kio plugin converting cdda on the fly to ogg...

**Comment by fbruetting** [comment]
> Sure you are using a desktop gvfs/kio plugin converting cdda on the fly to ogg...

I am, or I should? Didn’t understand this sentence…?

But I don’t assume that WAV files get convertey while accessing them.

**Comment by gnumdk** [comment]
Playing a CD is not about playing WAV, there is a converter between cdda format and wav.

**Comment by fbruetting** [comment]
Ah ok, didn’t know that.

**Comment by gnumdk** [comment]
Closing as WONTFIX, not related to lollypop.
