### ISSUE TITLE
Feature request: Album ordering settings by view

### ISSUE THREAD

**Issue by tagniam** [gnumdk/lollypop#1293]
### Environment
- Lollypop version: 0.9.304
- GTK+ versions: 3.22.25
- GNU/Linux distribution: Xubuntu 17.10

### Bug/Feature
It would be nice if the `All artists` view and the artist view had different album ordering settings.

I'd like to order albums by name on the `All artists` view, but order albums by year on the artist view.

**Comment by gnumdk** [comment]
In artist view, albums are always sorted by years... no?

**Comment by gnumdk** [comment]
ok, no :-/

**Comment by gnumdk** [comment]
Fixed in master, was designed for album view. So no new option but your issue is fixed.

**Comment by tagniam** [comment]
Thanks!
