### ISSUE TITLE
Feature request: Choose startup view

### ISSUE THREAD

**Issue by tagniam** [gnumdk/lollypop#1294]
### Environment
- Lollypop version: 0.9.304
- GTK+ versions: 3.22.25
- GNU/Linux distribution: Xubuntu 17.10

### Bug/Feature
It would be great if there was a setting that lets the user choose which view will be displayed on startup, instead of defaulting to the `Popular artists` view every time.

**Comment by gnumdk** [comment]
Just save state and it will open at last view.

**Comment by tagniam** [comment]
Not really the same feature. With this feature Lollypop would start with the same view regardless of what view was opened last.

**Comment by tagniam** [comment]
@gnumdk If you think this would be a worthwhile feature I'd be happy to work on this.

**Comment by gnumdk** [comment]
My  main issue is that I don't know if I want such option in UI.

**Comment by tagniam** [comment]
My main issue is that I like to see all my albums on startup.

Alternate suggestion: the user can reorder the list of views by dragging them. If the user wants to see a specific view on startup then they can put that view first in the list.

It's intuitive and doesn't clutter up the UI with another option.

**Comment by gnumdk** [comment]
Right click on item to select it as default ;)

**Comment by tagniam** [comment]
That works too. Thanks! :)
