### ISSUE TITLE
Compilations that are not

### ISSUE THREAD

**Issue by DavidLeigh** [gnumdk/lollypop#1295]
Ubuntu 16.04 dual boot with Windows 7 Professional 
Ubuntu updated today.
Lollypop version current with today (v0.9.304)

First:  Lollypop is awesome, this is to help be more awesome.

I have two albums with the same name - Solace.  One is by Sarah McLaughlin the other is by Xavier Rudd.  Each is stored in my music library in a separate folder tree under genre then artist then album.  My library is in my Windows drive; Lollypop is reaching across to it from Ubuntu.  When I first loaded my library they appeared as a single "compilation" album titled "Solace" with two artists.  They are not, so it seems worth addressing to make Lollypop better.  

To resolve this, I changed the album title of the Rudd version, and updated the library within Lollypop. This placed the Rudd version where it should be, but left the McLaughlin version as a compilation with one artist.  Another oddity that seems worth addressing.  

I then removed both albums from my library, updated the library in Lollypop, returned both albums to my library, and updated the library in Lollypop -- all was as should be; two individual albums.  

I do not have Internet connection at home, so there may be time lags between my replying to this.  

Thanks for a delightful alternative to the standard players.  I hope this helps you make it even better.  I discovered another oddity that I will post separately.

Dave....

**Comment by gnumdk** [comment]
You are just missing an album artist tag matching your artist tag.

**Comment by DavidLeigh** [comment]
Yes, I am, with every track of every non-classical album that I have tagged.  It appeared to me to be redundant so I skipped it.  Thanks for clarifying.  Awesome player!  Thanks even more for sharing it!
