### ISSUE TITLE
play from youtube/web access

### ISSUE THREAD

**Issue by mugambikimathi** [gnumdk/lollypop#1298]
I have updated lollypop to version 0.9.304-85 however, I cant seem to have web access (browse youtube) in Lollypop. it doesn't recognize Enable Network access setting. I always have to enable on every restart of the app

OS: Solus

I have tried the following with no success.
1. reinstall
2. deleting cache
3. Upgrading youtube_dl
4. Compiling from source

Older version worked well
Am I missing something?
Any help or direction to resolve the above would be of great help?

**Comment by gnumdk** [comment]
>Am I missing something?

Looking at closed issues?

**Comment by iand** [comment]
#1278
