### ISSUE TITLE
all music files have been deleted!!!

### ISSUE THREAD

**Issue by ec1solutions** [gnumdk/lollypop#1299]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148

WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.304
- GNOME/GTK+ versions: 3.26.2
- GNU/Linux distribution: Fedora 27

### Bug/Feature
I have just installed Lollypop, music is stored on an external SSD. Lollypop appears to have deleted all my files. How can I get them back?

**Comment by gnumdk** [comment]
Do you have done a sync?

**Comment by ec1solutions** [comment]
yes

Seán Kimberley



*Tel: 0844 357 2833 N.B. NEW NUMBER*

**Comment by gnumdk** [comment]
Found only one way to make lollypop deleting all files (fixed in master):
- All music was in one folder
- You have modified favorite-cover dconf key to null

If your disk does not support trashing, your music has been deleted.

**Comment by gnumdk** [comment]
>yes
A sync to a phone?

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/638

**Comment by gnumdk** [comment]
@neckcen May add an hidden option (dconf) for this feature:
#978 deletes his collection so I add a warning infobar
#1299 deletes his collection even if a warning was displayed

So I think this must stay an hidden feature because new user may not understand what sync is about.

**Comment by gnumdk** [comment]
@ec1solutions If you do not have backups, you will hate Lollypop for the rest of your life :-/

**Comment by ec1solutions** [comment]
yes, I have lost 10,000 music files, I do indeed hate this software. It was
not made clear what the sync direction was, I thought I was syncing from my
SSD to Lollypop, as I could not access my files when I opened the software.
I saw the message about file deletion, but I did not think for one minute
it meant it would delete all my music files - the warning needs to be much
more explicit.

Seán Kimberley



*Tel: 0844 357 2833 N.B. NEW NUMBER*

**Comment by gnumdk** [comment]
The sync is not available anymore for USB Disks, you need to activate it in dconf.
Sorry for this unclear feature...

**Comment by d9h20f** [comment]
Depending on the filesystem of your disk, data recovery software such as TestDisk should be able to restore your files relatively easily. See http://www.cgsecurity.org/wiki/TestDisk

**Comment by neckcen** [comment]
@gnudk I think that's a good compromise as it's a really useful feature but admittedly dangerous. Thanks again for your continuous work on lollypop!
