### ISSUE TITLE
Feature request: jump to artist

### ISSUE THREAD

**Issue by realcomplex** [gnumdk/lollypop#1300]
### Environment
- Lollypop version: 0.9.304
Installed as flatpak:
```
~ > flatpak list
Ref                               Options     
org.gnome.Lollypop/x86_64/stable  user,current
org.gnome.Platform/x86_64/3.26    user,runtime
org.gnome.Sdk.Docs/x86_64/3.26    user,runtime
org.gnome.Sdk/x86_64/3.26         user,runtime
org.gtk.Gtk3theme.Arc/x86_64/3.22 user,runtime
```

### Bug/Feature
Hi! Just discovered this music player, and it look like what I have been looking for for a while, awesome work!

One thing that I'm missing a little is a quick way to jump to a particular artist. I have more than 300 unique album artists, so finding the one I'm looking for in the artist listing on the left can sometimes take a little while. Up to now, I have been using mpd + ncmpcpp, and in ncmpcpp, you can always start a search with `/`, and jump through search results with `.` and `,`. This way, I can navigate to a particular artist in the library view very quickly.

In Lollypop, there seem to be two search mechanisms:
 - The normal search function `Ctrl + F`. Here I can search for an artist, but as far as I can see, there is no way to then jump to the artists and view all their albums.
 - Typing the name of the artist, and jumping through the results by scrolling.
This is a very fast mechanism, but it has a couple of issues:
    - Doesn't work for all letters, since for example `n` and `p` are bound to next and previous track, `r` is bound to recent albums, etc. This leads to frustration when trying to search for a artist starting with `p`, but instead the music is interrupted.
    - This search feature only seems to match artists starting from the first letter, so cannot search for "Lucia" to find the artist "Paco Lucia", for example.
    - Lollypop sorts artists the _right_ way by default, using tags (?) to determine sort order. This means that for example "Frank Zappa" is sorted under "Z". So when I type `f` to search for artists starting with an "f", the selection will jump to "Fleetwood Mac", for example. When I scroll, the selection now jumps all the way down to "Frank Zappa", at the bottom of the list. I personally found this change in the scroll behavior rather confusion in the beginning, especially since there is no visual indication of being in a special "search" mode. Moreover, the fact that artists are sorted according to tags, but search just starts with the first character is inconsistent.

I am missing something, and there is actually a way to jump to artists quickly and reliably in Lollypop? Or is this something that might need some work?

**Comment by gnumdk** [comment]
>and there is actually a way to jump to artists quickly and reliably in Lollypop
Typing name after giving focus to artist list?

>Doesn't work for all letters, since for example n and p are bound to next and previous track
Not sure to understand where you have this bug. In search dialog?

**Comment by realcomplex** [comment]
Okay, I got some things wrong, sorry for the confusion.

Jumping to an artist actually works fine, as long as the artist list has focus every works as intended. However, I have some more concrete feedback now:
- Starting to type when the artist list has focus opens a small text field at the bottom of the artist list which shows you your search so far. However, this text field is **not visible** when the Lollypop window is maximized; the text field is "below" the screen.
- Searching the artist lists still only works from the start of the strings, so for example, I won't find "Fleetwood Mac" by searching for "Mac". Moreover, I won't find "Frank Zappa" by searching for "Zappa", even though "Frank Zappa" is (rightly) sorted under the "Z" (so it would seem natural to start a search for "Zappa").
- Behavior of Lollypop is somewhat inconsistent when the artist list does _not_ have focus. In this case, typing "f" starts a search in the artist list, for example, while "n" switches to the next track. This leads to confusion sometimes in particular because there is no visual indication of whether the artist list has focus or not. You have to "remember" if your last click was in the artist list or not to determine how Lollypop will react to your keypresses.

I hope this is making a little more sense. Consider the first point a bug, and the last two points at least food for thought :)

**Comment by d9h20f** [comment]
I agree with your feedback, and can reproduce the inline search box being mostly hidden when maximised. I never noticed it before.

**Comment by gnumdk** [comment]
@d9h20f @realcomplex Distro/Desktop? 

Does not happen here on Arch/Debian sid

**Comment by gnumdk** [comment]
BTW this widget is a GTK one, so the issue is not in Lollypop.

**Comment by gnumdk** [comment]
> I personally thing that the fade effects are cool,
Just disable GTK animations

**Comment by realcomplex** [comment]
> @d9h20f @realcomplex Distro/Desktop?
Debian Testing. Flatpak installation.

> BTW this widget is a GTK one, so the issue is not in Lollypop.
So I could try reporting this bug upsteam at GTK?

> Just disable GTK animations
I don't want to do that for the whole desktop, so I'll live with it :)

**Comment by gnumdk** [comment]
Just click the artist name in search dialog

**Comment by realcomplex** [comment]
Commit 9252e0e seems very useful, awesome! 

What about the invisible (little) text field for the "quick search"? I think you would be the best person to report this if you can reproduce the issue, but otherwise I'll be happy to submit a bug report myself with GTK. In that case, it would be great if you had some details (like the name of the widget, maybe reference to where it's used in code?)

Please do consider my other suggestions too, related to making the "quick search" function easier to use.

**Comment by gnumdk** [comment]
I can't reproduce the issue here on ArchLinux.

>"quick search" function easier to use.
Not possible, it's a GTK internal widget.

**Comment by realcomplex** [comment]
> Not possible, it's a GTK internal widget.

Okay, I understand now. I guess that negates some of my feedback about this feature, if you can't change much about it anyway.

Does it have a name? I can submit a bug report at GTK about the text field being drawn outside the screen when the window is maximized.

**Comment by gnumdk** [comment]
Are you sure it's not an ARC issue?

**Comment by realcomplex** [comment]
No, it also happens under the default Adwaita theme, if that was the question.

**Comment by d9h20f** [comment]
This is the bottom of the screen with Lollypop maximised using inline search, latest GTK, Adwaita, etc, on openSUSE Tumbleweed:

https://i.imgur.com/8MhOElP.png

It seems to be somewhat affected by font size, but not much.

**Comment by realcomplex** [comment]
That exactly what it looks like for me too.

**Comment by gnumdk** [comment]
Launch gtk3-demo, there is a treeview on the left with same filter widget, does it happens too?

**Comment by realcomplex** [comment]
Yeah, exactly the same thing happens there. I guess that means GTK is at fault. Any idea where the best place is to report this?

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org ;)

**Comment by gnumdk** [comment]
What is your GPU ?

**Comment by realcomplex** [comment]
Bug is submitted upstream: https://bugzilla.gnome.org/show_bug.cgi?id=791349. My GPU is just the Intel integrated stuff, 4th generation. I don't know the exact model.

**Comment by gnumdk** [comment]
Ok, I know why I was not able to reproduce, only happen on Wayland ;)

**Comment by realcomplex** [comment]
Ahhh, makes sense! I'll make sure to include this in the upstream bug report.
