### ISSUE TITLE
Header styling

### ISSUE THREAD

**Issue by pawelad** [gnumdk/lollypop#132]
Hi,

I don't know if that's the right place, but I haven't found anywhere better.
Anyway, I just moved to Lollypop as my main music player, and I love it. But as you can see on the screenshot the header looks way different (and worse) then from official screenshots. I'm guessing it's because of my configuration (packages?), but I was wondering if there's anything I could do to fix it. Thanks!

System: elementary os 0.3 Freya
Lollypop: 0.9.20
Installed from official ppa

![image](https://cloud.githubusercontent.com/assets/7062874/7824994/1d3d4b26-0408-11e5-82d7-20dd1c34fecd.png)
![zrzut ekranu z 2015-05-27 00 30 52](https://cloud.githubusercontent.com/assets/7062874/7824997/237698da-0408-11e5-84bd-05801757d43e.png)

**Comment by bil-elmoussaoui** [comment]
I've already used lollypop with Freya and it's due to the way the gtk3 components are handled. And the screenshot is from Gnome (Fedora or Ubuntu Gnome)

**Comment by pawelad** [comment]
I thought so. Is it possible to force it`s behavior?
27 maj 2015 00:49 "Bilal Elmoussaoui" <notifications@github.com> napisał(a):

**Comment by gnumdk** [comment]
2 solutions:
Install Ubuntu GNOME instead of freya
Use another theme
