### ISSUE TITLE
Radio next track fixes

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#133]
Hello, 
even when i listen to the radio i got the next track popup  
![screenshot from 2015-05-27 14-17-46](https://cloud.githubusercontent.com/assets/7660997/7835712/42c2fc60-047b-11e5-8bbb-178bb338f7f2.png)

+ the color font in the dark theme for the artists/albums and the radio name is not really visible

**Comment by gnumdk** [comment]
Can you confirm with last git?

For color font, use a non buggy theme :p

**Comment by bil-elmoussaoui** [comment]
I still have this issue

**Comment by gnumdk** [comment]
Strange, no problem here :-(

**Comment by bil-elmoussaoui** [comment]
Ah this is fixed now, i didn't know how to use this new option haha! thanks
