### ISSUE TITLE
Seek using arrow keys crashes lollypop.

### ISSUE THREAD

**Issue by MineyMe** [gnumdk/lollypop#134]
Hello

Using the arrow keys to seek crashes the latest Lollypop development version, the backtrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/window.py", line 290, in _on_seek_action
    self._toolbar.update_position(seek*60)
AttributeError: 'Toolbar' object has no attribute 'update_position'
```

PS: I was wondering if you would like me to continue to report issues for the development version of Lollypop. (Since it is a Git/development version, you may prefer only bug reporting for the last actual release.)

Thanks in advance

**Comment by gnumdk** [comment]
Keep reporting bugs but wait 2 hours before reporting, update git, if it fails, report :)
