### ISSUE TITLE
Crash when updating music collection on start

### ISSUE THREAD

**Issue by zorrivel** [gnumdk/lollypop#135]
I have an updated Archlinux system. This started to happen since version 0.9.20 and happens as well for the latest(?) git commit (AUR's lollypop-git). Before 0.9.20 it worked great. It doesn't seem to be the same message as in issue #128.

Lollypop returns the following message on the console:

Unhandled exception in thread started by <bound method CollectionScanner._scan of <CollectionScanner object at 0x7fbc5ffb7f30 (lollypop+collectionscanner+CollectionScanner at 0x7fbc76a93a80)>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 163, in _scan
    self._inotify.add_monitor(d)
  File "/usr/lib/python3.4/site-packages/lollypop/inotify.py", line 43, in add_monitor
    None)
GLib.Error: g-io-error-quark: Operation not supported by backend (15)
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1296, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.4/threading.py", line 1019, in _delete
    del _active[get_ident()]
KeyError: 140446887425792

Many thanks

**Comment by gnumdk** [comment]
What is your filesystem?

**Comment by gipawu** [comment]
I have the same problem when using a gvfs filesystem (remote destination)

**Comment by gnumdk** [comment]
Should be fixed

**Comment by gipawu** [comment]
Yes, it works fine now, thank you.
