### ISSUE TITLE
You forgot to mark some labels as use-markup

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#136]
In the last rewrite/cleanup/redesign the playlist tracks you forgot
to mark some labels as use-markup (use-markup as true).

**Comment by gnumdk** [comment]
Examples?

**Comment by yoseforb** [comment]
In the tracks list I see the arist name in a regular font (not bold), inside <b> and </b>.

**Comment by yoseforb** [comment]
I tried to write: "inside <‎b> </‎b‎>.
