### ISSUE TITLE
Notebook media keys not working after app closes

### ISSUE THREAD

**Issue by tdtmusic** [gnumdk/lollypop#139]
Hi there. I have a problem with Lollypop on my notebook, it's a Sony Vaio VGN-FW11S. The notebook media keys (volume, play/pause,etc.) work fine with the player, but after I close it they don't work with the OS again, unless I do a killall on lollypop. I thought I should mention it.

**Comment by gnumdk** [comment]
Do you have 'continue payback on quit' activated?

Does it work with gnome music?

**Comment by tdtmusic** [comment]
There is no playback after I quit the app, the sound stops normally. I didn't try gnome music, I'm on elementary OS Freya (64bit). I did try Audacious, and with it the keys work fine, both in the app and after I quit it.

**Comment by gnumdk** [comment]
If you run from the command line, no error message on quit?

**Comment by tdtmusic** [comment]
Just some gtk warnings about the theme at start and this after quit:

** (lollypop:22918): CRITICAL **: Unable to determine array length for 0x7f18a97530a0
Unrecognized image file format

I don't think it has anything to do with my problem.

**Comment by tdtmusic** [comment]
Update: after I closed it, this time the keys worked fine after. Did the same a few times to make sure, but at one point they didn't work again, so maybe this is a random thing after all...

**Comment by gnumdk** [comment]
from gi.repository import Gtk, Gio, GLib
import signal, sys

class Application(Gtk.Application):
    def __init__(self):
        Gtk.Application.__init__(self,
                                 application_id='org.gnome.Lollypop',
                                 flags=Gio.ApplicationFlags.FLAGS_NONE)
        
    def do_startup(self):
        Gtk.Application.do_startup(self)
        self.window = Gtk.Window()
        self.window.set_application(self)
        self.window.show()

    def do_activate(self):
        self.window.present()
        self.proxy = Gio.DBusProxy.new_sync(Gio.bus_get_sync(Gio.BusType.
                                                              SESSION, None),
                                         Gio.DBusProxyFlags.NONE,
                                         None,
                                         'org.gnome.SettingsDaemon',
                                         '/org/gnome/SettingsDaemon/'
                                         'MediaKeys',
                                         'org.gnome.SettingsDaemon.'
                                         'MediaKeys',
                                         None)
        self.proxy.connect('g-signal', self._handle_media_keys)
        self.proxy.call_sync('GrabMediaPlayerKeys',
                          GLib.Variant('(su)', ('Lollypop', 0)),
                          Gio.DBusCallFlags.NONE,
                          -1,
                          None)
        Gtk.Application.do_activate(self)

    def _handle_media_keys(self, proxy, sender, signal, parameters):
            print('multimedia key')
            return   
        
if __name__ == "__main__":
    app = Application()
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    exit_status = app.run(sys.argv)
    sys.exit(exit_status)

**Comment by gnumdk** [comment]
Save this to a file test.py

$ python3 test.py

Tell me if you can reproduce the bug...

**Comment by tdtmusic** [comment]
Here's what's happening after I run the script:

File "test.py", line 5
    def init(self):
      ^
IndentationError: expected an indented block

**Comment by gnumdk** [comment]
Hmm, make sure copying text without removing indentation.

**Comment by tdtmusic** [comment]
I'm not really sure what I'm supposed to see or do. There's a little window that pops-up and, in terminal, i get "multimedia key" when I press them (except the volume keys).

**Comment by gnumdk** [comment]
and when you close window, does the script exit?

**Comment by tdtmusic** [comment]
Yes. And the keys work fine.

**Comment by gnumdk** [comment]
Will try to find some times to install elementary on my test laptop ;)

Can you test with a new user?

**Comment by tdtmusic** [comment]
Yes, I have a second user too. Let's see.

**Comment by tdtmusic** [comment]
I tried a few times and I didn't get the bug with the second user. But, like I said, it's pretty random, so that doesn't mean it won't happen. My desktop PC has the same OS installed and also multimedia keys on the keyboard, but Lollypop works fine there, so I think this might be a problem with my notebook, somehow.

**Comment by gnumdk** [comment]
By the way lollypop doesn't really handle multimedia key, it's a dbus service...

What is strange is lollypop not quitting...

**Comment by gnumdk** [comment]
Do you know how to build lollypop from master?

**Comment by gnumdk** [comment]
Enable lollypop source in freya package sources manager

$ sudo apt-get update
$ sudo apt-get build-dep lollypop
$ sudo apt-get install gnome-common
$ git clone https://github.com/gnumdk/lollypop.git
$ git checkout mmkeys
$ ./autogen.sh
$ make
$ sudo make install

Run lollypop from terminal and show me output on quit.

To remove dev version:
$ sudo make uninstall

**Comment by tdtmusic** [comment]
For some reason, the ppa for lollypop doesn't show in that list. But I clearly added it, since I could install Lollypop, right? How do I enable the source code repo?

**Comment by gnumdk** [comment]
vi /etc/apt/source.list.d/lollypop.list or something like this

You should find a deb-src line commented with #

Remove the #

**Comment by tdtmusic** [comment]
Everything went fine, except launching lollypop after compiling. Here's the terminal output:

(lollypop:4918): Gtk-WARNING **: Theme parsing error: header-bar.css:162:26: 'none' is not a valid color name
ERROR:root:Could not find any typelib for Secret
cannot import name 'Secret'
Last.fm authentication disabled
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
ERROR:root:Could not find any typelib for Secret
ERROR:root:Could not find any typelib for Secret

(lollypop:4918): libnotify-WARNING **: Failed to connect to proxy

(lollypop:4918): Gtk-WARNING **: Theme parsing error: header-bar.css:162:26: 'none' is not a valid color name
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/application.py", line 136, in do_startup
    Lp.window.setup_menu(menu)
  File "/usr/local/lib/python3.4/site-packages/lollypop/window.py", line 58, in setup_menu
    self._toolbar.setup_menu_btn(menu)
AttributeError: 'Toolbar' object has no attribute 'setup_menu_btn'

**Comment by gnumdk** [comment]
You are launching lollypop as root, no?

**Comment by tdtmusic** [comment]
I tried as user and sudo too, it's the same thing.

**Comment by gnumdk** [comment]
can you retest?

Just run: git pull
in your lollypop directory

**Comment by tdtmusic** [comment]
Still throwing errors when attempting to launch...

(lollypop:23735): Gtk-WARNING **: Theme parsing error: header-bar.css:162:26: 'none' is not a valid color name
ERROR:root:Could not find any typelib for TotemPlParser
Traceback (most recent call last):
  File "/usr/local/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/local/lib/python3.4/site-packages/lollypop/application.py", line 14, in <module>
    from gi.repository import Gtk, Gio, GLib, Gdk, Notify, TotemPlParser
ImportError: cannot import name 'TotemPlParser'

**Comment by bil-elmoussaoui** [comment]
I have the same issue when i build from git in elementary OS

**Comment by gnumdk** [comment]
You need to install totem-plparser gir

**Comment by tdtmusic** [comment]
I installed the package and tried to run lollypop again. Another error:

(lollypop:11853): Gtk-WARNING **: Theme parsing error: header-bar.css:162:26: 'none' is not a valid color name
ERROR:root:Could not find any typelib for Secret
cannot import name 'Secret'
Last.fm authentication disabled
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
ERROR:root:Could not find any typelib for Secret
ERROR:root:Could not find any typelib for GstPbutils
Traceback (most recent call last):
  File "/usr/local/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/local/lib/python3.4/site-packages/lollypop/application.py", line 33, in <module>
    from lollypop.window import Window
  File "/usr/local/lib/python3.4/site-packages/lollypop/window.py", line 16, in <module>
    from lollypop.container import Container
  File "/usr/local/lib/python3.4/site-packages/lollypop/container.py", line 24, in <module>
    from lollypop.view_radios import RadiosView
  File "/usr/local/lib/python3.4/site-packages/lollypop/view_radios.py", line 17, in <module>
    from lollypop.widgets_radio import RadioWidget
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_radio.py", line 18, in <module>
    from lollypop.pop_radio import RadioPopover
  File "/usr/local/lib/python3.4/site-packages/lollypop/pop_radio.py", line 25, in <module>
    from lollypop.art import Art
  File "/usr/local/lib/python3.4/site-packages/lollypop/art.py", line 16, in <module>
    from lollypop.art_album import AlbumArt
  File "/usr/local/lib/python3.4/site-packages/lollypop/art_album.py", line 20, in <module>
    from lollypop.tagreader import TagReader
  File "/usr/local/lib/python3.4/site-packages/lollypop/tagreader.py", line 14, in <module>
    from gi.repository import GLib, Gst, GstPbutils
ImportError: cannot import name 'GstPbutils'

**Comment by bil-elmoussaoui** [comment]
Install pip3 using this : 
``` 
sudo apt-get install python3-pip
```
and then install pylast using pip
```
sudo pip3 install pylast
```

**Comment by tdtmusic** [comment]
Done. Exactly the same error as above.

**Comment by gnumdk** [comment]
Install lollypop package

**Comment by tdtmusic** [comment]
Ok, this time it launched fine. Here's the output after quit:

** (lollypop:18497): CRITICAL **: Unable to determine array length for 0x7fb6301e0130
Unrecognized image file format
prepare_to_exit 1
prepare_to_exit 5
prepare_to_exit 6
prepare_to_exit 7
prepare_to_exit 8
quit 1
quit 5
quit 6
quit 7
quit 8

**Comment by gnumdk** [comment]
$ git checkout master
$ git pull
$ make
$ sudo make install

lollypop should no exit everytimes

**Comment by gnumdk** [comment]
Is this one fixed?

**Comment by tdtmusic** [comment]
Seems so, I didn't experience that bug at all, so I guess everything is fine on my part :)
