### ISSUE TITLE
Crash while updating library

### ISSUE THREAD

**Issue by nitroflow** [gnumdk/lollypop#141]
Lollypop crashes while updating library with the following output:

    Unhandled exception in thread started by <bound method CollectionScanner._scan of <CollectionScanner object at 0x7fe2ee6b6cf0 (lollypop+collectionscanner+CollectionScanner at 0x1537ee0)>>
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 189, in _scan
        (new_tracks, new_dirs, count) = self._get_objects_for_paths(paths)
      File "/usr/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 111, in _get_objects_for_paths
        f = Gio.File.new_for_path(filepath)
    UnicodeEncodeError: 'utf-8' codec can't encode character '\udc81' in position 174: surrogates not allowed
    Exception ignored in: <module 'threading' from '/usr/lib64/python3.4/threading.py'>
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/threading.py", line 1296, in _shutdown
        _main_thread._delete()
      File "/usr/lib64/python3.4/threading.py", line 1019, in _delete
        del _active[get_ident()]
    KeyError: 140612563597056

Also, can you tell me where lollypop stores it's library paths so I can reset them and try to figure out which files are causing this problem until it's fixed?

**Comment by gnumdk** [comment]
This bug is already fixed in git...

**Comment by gnumdk** [comment]
#128

**Comment by gnumdk** [comment]
You can edit lollypop settings with dconf-editor => /org/gnome/lollypop

**Comment by nitroflow** [comment]
I had no idea, sry, I'm using 0.9.20.

**Comment by gnumdk** [comment]
No problem ;)

**Comment by gnumdk** [comment]
Read this comment and give a try to this nautilus extension ;)

https://github.com/gnumdk/lollypop/issues/128#issuecomment-105004745
