### ISSUE TITLE
Pixelated Covers

### ISSUE THREAD

**Issue by andresanemic** [gnumdk/lollypop#142]
Hi, I have a little problem with Lollypop and Antergos (also on an clean Arch machine). The covers of the albums look bad, just like this: 
[Covers](https://cloud.githubusercontent.com/assets/12744046/7979649/56767c44-0a77-11e5-906d-49fac97a9f6a.png)
I'm wondering if it's a bug or something else.

**Comment by gnumdk** [comment]
What is covers resolution. They are pixelised because they are too small i think.

**Comment by andresanemic** [comment]
All my music have at least covers with 300x000 px. In others players this does not happen. Also, the covers that Lollypop choose are from the internet, not from the tag, and I think there is the issue.

**Comment by gnumdk** [comment]
What version?

**Comment by andresanemic** [comment]
Te version is 0.9.20-1 (but the git version in Aur also have this problem). Now I'm using Gnome 3.16 with a 1360x768 resolution :/

**Comment by gnumdk** [comment]
Lollypop 0.9.20 doesn't download covers from the net... So it's not possible... It's only available since lastfm integration...

Covers in album directories?

**Comment by andresanemic** [comment]
Oh, you are right. The player choose the pictures there are in the album folders. My mistake. Now i have to delete a lot of files. Thanks :)

**Comment by gnumdk** [comment]
In 0.9.30, order will be:
- Folder
- Tags
- Lastfm
