### ISSUE TITLE
Added 'Pupular Songs' on the sidebar

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#143]
I have some albus thas I love only a few songs. I wants to see those songs
on a list, but I can't becouse there isn't enouth plays for the others songs in thos albums.

So, I would like to see 'Popular Songs' for this reason.

Btw, I wonder if the string 'Loved Albums' or 'Favorite Albums' it better label.
The first one (Loved) look right becouse of the heart-symbolic.

**Comment by gnumdk** [comment]
On my TODO list

**Comment by gnumdk** [comment]
After some reflection about how to implement this, i came to the conclusion that I will use playlist widget to show songs... Then, what about creating a "Loved songs" playlist?

**Comment by yoseforb** [comment]
Creating, you mean manually by the user?

**Comment by gnumdk** [comment]
No, love button add song to this playlist
You can add a song like for others playlist
On first init, lollypop populate the list with loved songs from lastfm

**Comment by MineyMe** [comment]
Would the love button be essentially the same as 'Add to list' -> 'My Favorites' (after creating the latter list)?

Also, I'm wondering, suppose I reinstall my distro for whatever reason in the future, and perhaps the location (base folder) of my music also changes, would it then be sufficient to backup lollypop.db and place it in the right location on the new computer? Will lollypop automatically match the newly imported tracks to the tracks from the old database and restore the favorites? This isn't really intended as a feature request if it doesn't, just curious :P

**Comment by gnumdk** [comment]
No, it will not work... On database reset, lollypop restore recents/populars based on path...

**Comment by gnumdk** [comment]
Available in love branch of lollypop

Please do not report bugs for this branch, it's work in progress and i will not work on this until monday ;)

**Comment by gnumdk** [comment]
Merged in master.
