### ISSUE TITLE
No stop signal sent to MPRIS when stop after current is used.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [gnumdk/lollypop#146]
Hello

Whenever stop after current is enabled and the track is allowed to end cleanly, Lollypop will correctly stop the track, but it will not notify MPRIS listeners that it has stopped playing. Using the GNOME shell MPRIS extension, the position will keep incrementing (e.g. it will go from 4:17 / 4:17 to 4:30 / 4.17 and beyond). According to the extension, Lollypop is still playing music and the pause button is still visible.

I thought this was a Lollypop issue, but my apologies if this in fact an issue in the extension.

Thanks in advance

**Comment by gnumdk** [comment]
No it's in lollypop...
