### ISSUE TITLE
Rendered artwork looks blurry on HiDPI displays

### ISSUE THREAD

**Issue by alexskc** [gnumdk/lollypop#148]
Currently, on HiDPI displays, album artwork is simply an upscaled version of "standard" resolution artwork, which is noticeably blurrier next to the well-rendered text and icons.

**Comment by alexskc** [comment]
This isn't going to work. If org.gnome.desktop.interface scaling-factor is set to 2, the width will be reported in "virtual pixels," not physical device pixels.

**Comment by gnumdk** [comment]
Can you give me more informations?
- Your resolution
- Reported resolution

**Comment by gnumdk** [comment]
Here, changing scaling-factor doesn't change reported resolution...

**Comment by alexskc** [comment]
Never mind, I'm a moron.

Still, there's no noticeable difference even with that commit, so I'm unsure what would be causing it. My display is 3200x1800, so it should be behaving as 1600x900.

Here's what it looks like with display scaling enabled
![display scaling](https://cloud.githubusercontent.com/assets/6933425/8060595/9c06813e-0ec6-11e5-9889-f3c679882db0.png)

Vs without it:
![no display scaling](https://cloud.githubusercontent.com/assets/6933425/8060638/cfefac1e-0ec6-11e5-905c-3d898605327a.png)

**Comment by gnumdk** [comment]
Can reproduce on my XPS 13... GTK is scaling images...

**Comment by gnumdk** [comment]
And can't reproduce anymore, seems to be random...
Do you tried logout/login ?

**Comment by gnumdk** [comment]
Can you test?

**Comment by alexskc** [comment]
Seems to have just gotten worse for me.

![yay](https://cloud.githubusercontent.com/assets/6933425/8063917/c56436be-0ed7-11e5-843f-97bf72b41ce3.png)

**Comment by gnumdk** [comment]
Should be ok now ;)

**Comment by gnumdk** [comment]
Toolbar not ok

**Comment by gnumdk** [comment]
All patch reverted, i need to work on this issue...

**Comment by gnumdk** [comment]
Can you test current git?

I don't find a solution for toolbar cover...

**Comment by alexskc** [comment]
Album artwork is the right size now, but it's still blurry. :/

**Comment by gnumdk** [comment]
You miss one commit :)

**Comment by alexskc** [comment]
Works great, now! :D
