### ISSUE TITLE
Playing unavailable radio stream causes crash.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [gnumdk/lollypop#149]
Hello

Playing a radio stream that is currently unavailable causes a crash. Seems to be a regressions in the Git master branch (it was fixed before). Backtrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/player_bin.py", line 238, in _on_bus_error
    Lp.notify.send(_("File doesn't exist: %s") %
AttributeError: 'NoneType' object has no attribute 'send'
```

Thanks in advance

**Comment by gnumdk** [comment]
Can you confirm you have disabled notifications?

**Comment by hotoiledgoblinsack** [comment]
Thanks, the issue seems to be fixed now. I do indeed have notifications disabled.
