### ISSUE TITLE
Distance from album artwork to left edge is constant.

### ISSUE THREAD

**Issue by alexskc** [gnumdk/lollypop#150]
The spacing between individual albums and their distance from the right edge depends on the size of the space. The distance from the left edge is always the same, though, which looks inconsistent.

**Comment by gnumdk** [comment]
It's wanted, GtkFlowBox behaviour looks horrible if centerer:

![capture du 2015-06-12 07-09-29](https://cloud.githubusercontent.com/assets/3918824/8124033/d66fa32c-10d4-11e5-9e15-7b2a4181ed06.png)

**Comment by gnumdk** [comment]
You can reproduce this bug in bijiben, evince start page, ...

Report a bug to GTK
