### ISSUE TITLE
Album artwork huge on HiDPI

### ISSUE THREAD

**Issue by alexskc** [gnumdk/lollypop#153]
Seems this commit: https://github.com/gnumdk/lollypop/commit/a5117e5be4891e0a4fd772594da6f4080f16c728 broke it.

**Comment by gnumdk** [comment]
Seems to work here, what is the bug? Screenshot?

**Comment by alexskc** [comment]
latest build: 
![largeartwork](https://cloud.githubusercontent.com/assets/6933425/8123769/9a2b242c-10cf-11e5-8fce-de370c281fca.png)

Checkout https://github.com/gnumdk/lollypop/commit/a5117e5be4891e0a4fd772594da6f4080f16c728:
![stilllarge](https://cloud.githubusercontent.com/assets/6933425/8123786/cb4fae24-10cf-11e5-8565-806cd1771f88.png)

Checkout https://github.com/gnumdk/lollypop/commit/b45f0ad7ca2f4e4daf47765fd1e168dff472ab7d:
![normalsize](https://cloud.githubusercontent.com/assets/6933425/8123796/f7018e0c-10cf-11e5-8f63-9ae7abe61027.png)

**Comment by gnumdk** [comment]
i revert the screenshot, something i do not understand in cairo vs pixbuf vs scale factor :(
