### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by DenzoNL** [gnumdk/lollypop#155]
Would it be possible to create a Windows build of Lollypop? I've tried myself by installing all of the dependencies on Windows but I'm left with a "No module named 'lollypop'" error. I've been enjoying the player on Arch Linux so much that I'm now favoring it over my foobar2000 install on my Windows machine.

**Comment by gnumdk** [comment]
I failed to make it running on macosx... So on windows, good luck ;)

Patches are welcome but I do not have time for this and no windows for working on it.

Regards,
