### ISSUE TITLE
splitted albumartist from FLAC files not showing

### ISSUE THREAD

**Issue by columna** [gnumdk/lollypop#156]
Hi,

the MP3 files with splitted albumartist displayed correct in the left panel,

but my FLAC files only show the first artist.

And a little question, is it possible to seperate the splitted artists with "," and "&" at last?

For example:

artist, artist, artist & artist
artist, artist, & artist
artist & artist

I really like your project. Keep up the good work :+1:

**Comment by gnumdk** [comment]
Send me an example...

**Comment by gnumdk** [comment]
In fact, since i drop mutagen, artist are splitted by gstreamer...

Album artist is never splitted...

**Comment by columna** [comment]
The splitted albumartists not displayed seperately but show all values from MP3's. They're not handled "splitted" but displayed correctly.
The splitted albumartists from FLAC files only display the first artist.

What do you mean with "about dialog". Where the version of lollypop is displayed?

I'm very newbish, sorry for that :)

**Comment by gnumdk** [comment]
In about dialog, you have my email.

Send me a file, i do not understand what is happening ;)

**Comment by gnumdk** [comment]
Should be ok
