### ISSUE TITLE
Last.fm scrobbling doesn't work

### ISSUE THREAD

**Issue by pawelad** [gnumdk/lollypop#157]
Hi,

I just installed the latest version from ppa, but the scrobbling feature doesn't work (testing username and password returns OK sign).
How can I debug it?

**Comment by gnumdk** [comment]
Elementary OS, Ubuntu Utopic, update python3-pylast or do: pip3 install pylast

**Comment by pawelad** [comment]
Elementary os, and I saw pylast installing via apt-get. Should I install it
with pip as well?
14 cze 2015 16:17 "Cédric Bellegarde" <notifications@github.com> napisał(a):

**Comment by gnumdk** [comment]
http://packages.ubuntu.com/vivid/python3-pylast

Install this one, should install under trusty

**Comment by pawelad** [comment]
Like I said, `python3-pylast` was installed automatically when updating.

**Comment by gnumdk** [comment]
python3-pylast is OUT OF DATE on trusty.

**Comment by pawelad** [comment]
Updated it via `pip` to `pylast 1.2.1` and still nothing.

**Comment by gnumdk** [comment]
pip is python2

pip3 is the good command

**Comment by pawelad** [comment]
That's what I meant:
```
pawel@xyz:~$ sudo pip3 install --upgrade pylast
Requirement already up-to-date: pylast in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: six in /usr/local/lib/python3.4/dist-packages (from pylast)
```

**Comment by gnumdk** [comment]
Do you removed python3-pylast?

**Comment by pawelad** [comment]
Yes

**Comment by gnumdk** [comment]
launch lollypop from a terminal, do you have an error when a track ends ?

**Comment by pawelad** [comment]
Yep. Tried to opem it from terminal before, but I though it scrobbles while the song is playing too.
Anyway:
```
pawel@xyz:~$ lollypop 

** (lollypop:9491): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-Q5IFaVGsMu: Połączenie odrzucone
LastFM::scrobble: list index out of range
```

**Comment by gnumdk** [comment]
Strange, here it's working with elementary OS.

And there is no list in lollypop code so exception comes from pylast...

**Comment by pawelad** [comment]
Do you need anymore information from me? I'm more then happy to help.

**Comment by gnumdk** [comment]
Is artist informations working ?
Can you add a track to love tacks, what happend in terminal?

**Comment by pawelad** [comment]
Adding track to favorites and artist info works... : )

**Comment by gnumdk** [comment]
what is : Utworzono nowe okno w istniejącej sesji przeglądarki. ?

**Comment by pawelad** [comment]
I clicked in last.fm link and it opened the website in the browser. Nothing important ; )

**Comment by gnumdk** [comment]
what is your username on lastfm ? Send me in private by email if you care about privacy ;)

**Comment by gnumdk** [comment]
Unhandled exception in thread started by <bound method LastFM._scrobble of pylast.LastFMNetwork('7a9619a850ccf7377c46cf233c51e3c6', '9254319364d73bec6c59ace485a95c98', '6612a4810c12853030b3637943178985', 'lollypop_gnome', '3f99090fb71ae66aa8946001fff99650')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/lastfm.py", line 215, in _scrobble
    timestamp=timestamp)
  File "/usr/lib/python3.4/site-packages/pylast/__init__.py", line 714, in scrobble
    "stream_id": stream_id, "context": context, "mbid": mbid},))
  File "/usr/lib/python3.4/site-packages/pylast/__init__.py", line 754, in scrobble_many
    _Request(self, "track.scrobble", params).execute()
  File "/usr/lib/python3.4/site-packages/pylast/__init__.py", line 1136, in execute
    response = self._download_response()
  File "/usr/lib/python3.4/site-packages/pylast/__init__.py", line 1127, in _download_response
    self._check_response_for_errors(response_text)
  File "/usr/lib/python3.4/site-packages/pylast/__init__.py", line 1148, in _check_response_for_errors
    e = doc.getElementsByTagName('lfm')[0]
IndexError: list index out of range
Exception ignored in: <module 'threading' from '/usr/lib64/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 1297, in _shutdown
    _main_thread._delete()
  File "/usr/lib64/python3.4/threading.py", line 1020, in _delete
    del _active[get_ident()]
KeyError: 139896578619136

**Comment by pawelad** [comment]
I'm guessing you found it? Should I report a bug to `pylast`? Do you still want my username?

**Comment by gnumdk** [comment]
No, i will report it. Just need to found if i'm not doing something wrong

**Comment by gnumdk** [comment]
I think i got it :)

Lollypop scrobbles next song with current song timestamp :-/ Works when current song duration < next song duration

**Comment by pawelad** [comment]
Cool, cool, cool : )
Waiting for the ppa then

**Comment by pawelad** [comment]
All good : )

One more great feature, don't know how hard to implement (although I think I saw appropriate function in `pylast`), would be giving currently played song as 'Now Playing' in last.fm.

Anyway, thanks for help. Lollypop FTW! : )

**Comment by pawelad** [comment]
Hey, sorry to bother you again but now it scrobbles the next track on the playlist, instead of the track that just finished.

**Comment by pawelad** [comment]
And now it stopped scrobbling at all:
```
pawel@xyz:~$ lollypop 

** (lollypop:5984): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-NsUqAnmmfF: Połączenie odrzucone
LastFM::scrobble: Invalid method signature supplied
** (lollypop:5984): CRITICAL **: Unable to determine array length for 0x7f89f00c7a90
LastFM::scrobble: Invalid method signature supplied
```

**Comment by gnumdk** [comment]
Here lastfm response, strange:
<html>Your request timed out.   Please retry the request.                                                                                                                                                                </html>

**Comment by gnumdk** [comment]
https://bitbucket.org/cs96and/rockscrobbler/issue/5/scrobbled-3-times

**Comment by gnumdk** [comment]
Can you try again, i add some code inspired by rockscrobbler bug report

**Comment by pawelad** [comment]
No errors with first song, but it scrobbled it as the next one on the playlist.
Second try:
```
pawel@xyz:~/Temp/lollypop$ lollypop 

** (lollypop:23413): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-NsUqAnmmfF: Połączenie odrzucone
LastFM::scrobble: NetworkError: [Errno -2] Ta nazwa lub usługa jest nieznana
```
Third try same as first - scrobbled the wrong track.

**Comment by gnumdk** [comment]
Ta nazwa lub usługa jest nieznana ?

**Comment by pawelad** [comment]
`Ta nazwa lub usługa jest nieznana` - > `This name or service is unknown`

Fourth try was like first and fourth. It's possible that the network error was accidental, but it still scrobbles the next track on the playlist, instead of the track that just ended.

**Comment by gnumdk** [comment]
Here, it doesn't scrobble the next track... More informations?

**Comment by gnumdk** [comment]
You are talking of 0.9.30 or of master? :)

**Comment by pawelad** [comment]
I figured you would notice that on your end... : )
What more can I say?

I'm on master. I'm playing the CD, and after the track `n` finishes, when I look on my last.fm I see track `n+1` scrobbled, the one that just started playing.

**Comment by pawelad** [comment]
Wait, I'm on master-1

**Comment by gnumdk** [comment]
Really strange...

**Comment by gnumdk** [comment]
Now playing added

**Comment by pawelad** [comment]
Okay now, weird things are happening. Deleted lollypop from ppa(to be sure), and installed latest mater.

When I click on first song on the album, in the header it shows the correct song, but the playinng icon is on the next song. In last.fm it shows correct `Now Playing`:
![zrzut ekranu z 2015-06-15 08 53 38](https://cloud.githubusercontent.com/assets/7062874/8154641/66f89b60-133c-11e5-992e-fee7e327f888.png)

When the song finishes, the play icon jumps to the next one (so always `n+1`), but on last.fm it shows that the scrobbled track was track 2, the one that just started playing
![zrzut ekranu z 2015-06-15 08 54 05](https://cloud.githubusercontent.com/assets/7062874/8154681/e5affdf4-133c-11e5-9a3b-a7ed89bccc20.png)

Same thing happend with third song - the play icon is wrong, header is good, now playing is good, but after the song finishes the next song is shown as scrobbled.
![zrzut ekranu z 2015-06-15 08 59 44](https://cloud.githubusercontent.com/assets/7062874/8154688/05044fe8-133d-11e5-8fd7-1f727c09b048.png)

**Comment by gnumdk** [comment]
The play icon is fixed, just a try in master for another bug.

**Comment by pawelad** [comment]
What about scrobbling the next song, instead of the one that just ended? Especially weird, because `Now playing` is correct...
Is it really OK at your end? Can't see a reason why it would be different... Maybe something to do with speed / order when the function gets the song name, it already jumped into the next one?
Can I run / compile it with some kind of debug flag?

**Comment by pawelad** [comment]
Hmm... Seems to be alright, except when song is really short - I think I saw you checking if time is greater then 30 seconds. Is that by design?

**Comment by pawelad** [comment]
Yeah, so far so good, except for short songs - they're visible as `Now Playing`  but then they disappear.

Also - I don't know what's the desired behavior in 'highlighting' the song, but shouldn't it go on with the playlist? Or not highlight anything, since the play icon covers current song.
![zrzut ekranu z 2015-06-15 12 45 08](https://cloud.githubusercontent.com/assets/7062874/8158343/9c3e016e-135c-11e5-8a3e-4be71504af84.png)

**Comment by gnumdk** [comment]
http://www.lastfm.fr/forum/21717/_/2200237/1

**Comment by gnumdk** [comment]
For the selection, the bug comes from your theme...
What is it?

**Comment by pawelad** [comment]
You sure? It would guess it's on the program side, but you probably know better : )
It's https://github.com/snwh/paper-gtk-theme

Also - I'm loving the app, and for I while I wanted to do a project with Python + GTK3. Do you need any help? From what I can see you do most of the commits, so maybe you prefer working alone.

**Comment by pawelad** [comment]
Also, got one of those:
```LastFM::_update_playing(): Malformed response from Last.fm. Underlying error: ''```
Stopped scrobbling, but all good after I changed the track.

**Comment by gnumdk** [comment]
Feel free to help me but tell me before working on a feature, i may not accept all features ;)

**Comment by gnumdk** [comment]
>Stopped scrobbling, but all good after I changed the track.

Should not stop, lollypop try five times to scrobble/set_as_playing a track.

**Comment by pawelad** [comment]
Do you have some kind of list To Do list though? Future goals, things you're currently working on.

**Comment by gnumdk** [comment]
Not before 1.0 is released... Just bug fixes before this version...

After, waiting for good ideas :)

**Comment by gnumdk** [comment]
Send me an email for more informations, i have a job for you :)

**Comment by pawelad** [comment]
One more bug I think I found - I went out and scrobbled tracks from Android, and when I got back scrobbling in Lollypop didin't work until i closed and reopened he program.
