### ISSUE TITLE
Missing artist from albums

### ISSUE THREAD

**Issue by gipawu** [gnumdk/lollypop#158]
With last Lollypop version, after collection scanning, for many albums the artist is not recognized.

EDIT: It seems that only FLAC files are affected by this problem, MP3s work fine.

**Comment by gnumdk** [comment]
Sens me an example by email

See about dialog

**Comment by gnumdk** [comment]
What is last?
0.9.31, if yes, did it work with 0.9.30?

**Comment by gipawu** [comment]
Yes, I talked about 0.9.31. With 0.9.30 it works fine.
I suspect it's a problem related to https://github.com/gnumdk/lollypop/commit/d1e63f7def39803f216a11d01967b7e47f212b0e

**Comment by gnumdk** [comment]
Ok, i'm releasing 0.9.32 fixing this bug...

Morality: always reset your database before releasing...

**Comment by gipawu** [comment]
Working fine now thank you :)
