### ISSUE TITLE
No module named 'pylast'

### ISSUE THREAD

**Issue by ballinger** [gnumdk/lollypop#159]
im on fedora 22 and have pylast installed..... what am i missing? i dont care for lastfm but would like to get the artist info..

No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast

**Comment by gnumdk** [comment]
Fedora doesn't prove pylast for python3

**Comment by ballinger** [comment]
dnf install pylast
dnf info pylast
Installed Packages
Name        : pylast
Arch        : noarch
Epoch       : 0
Version     : 0.5.11
Release     : 6.fc21
Size        : 268 k
Repo        : @System
From repo   : fedora
Summary     : A Python interface to Last.fm API compatible social networks
URL         : http://pypi.python.org/pypi/pylast
License     : ASL 2.0
Description : A Python interface to Last.fm (and other API compatible social networks)

ln -s /usr/lib/python2.7/site-packages/pylast.py /usr/lib/python3.4/site-packages/pylast.py <- did the trick, working fine now.
