### ISSUE TITLE
Allow playing all the search result as a group of songs/albums/arists

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#162]
In gnome-music it is possible to search for word, and to play all the songs on the search result.
I would like to be able to do so, and also to create new/full playlist from search reault.

**Comment by gnumdk** [comment]
Search on what? title? all?

**Comment by yoseforb** [comment]
All, I think, or just arist (in the list of the arists on the sidebar there is only albums-arists, some songs from other albums are missing).

**Comment by gnumdk** [comment]
In master

**Comment by yoseforb** [comment]
Thanks!

It qill be great to allow start playing not just from the start of the results.
I mean, maybe I wants to play from the middle of the list until the end, for example.
Now the only option is to listen to the whole result, and it already great!

**Comment by gnumdk** [comment]
Done
