### ISSUE TITLE
Troubles with external FLAC tracks

### ISSUE THREAD

**Issue by gipawu** [gnumdk/lollypop#163]
It seems there are some problems with external FLAC files.
For example, the Last.fm artist info fetching and seeking do not work correctly (the position cursor keeps jumping to 0:00 randomly).
MP3s work fine. I don't know if other file types are affected by that problem.

**Comment by gnumdk** [comment]
Gstreamer bug :(

**Comment by gipawu** [comment]
For the Last.fm fetching trouble, please change line 231 in ```src/player_bin.py``` from
```if self.current_track.aartist is None :```
to
```if self.current_track.aartist is None or self.current_track.aartist == '' :```

**Comment by gnumdk** [comment]
Done
