### ISSUE TITLE
Make the selected arist row's background on the sidebar blue

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#164]
On my screen it a little hard to see the selected row on the sidebar.
It would be great for selected row on the sidebar as blue, like in nautilus sidebar.

**Comment by gnumdk** [comment]
Not sure...

**Comment by gnumdk** [comment]
What theme?

**Comment by yoseforb** [comment]
The default one (Adwaita).

**Comment by gnumdk** [comment]
I set list grey because some widgets no use grey hover effect (search use a listbox).

**Comment by gnumdk** [comment]
Better?

**Comment by yoseforb** [comment]
As I see on gnome-control-center, for example, over effect for row is grey and selected row is blue.
Look at the Region & Language or the Users or the Online Accounts.
The same you can see on polari's sidebar and on geary's sidebar ofcourse.

**Comment by yoseforb** [comment]
Hmm, it look more clear, but still on the bottom of the screen it not clear enough (and I sure it less-clear on the morrning). my screen…

**Comment by yoseforb** [comment]
Just see how it look on the new sidebar in nautilus (pushed just two dayes ago to gtk+ master):
https://bytebucket.org/yoseforb/expand-header-bar/raw/10682460789a0bd86dc064df4d97f83785f91203/nautilus-new-bookmarks-sidebar-18-06-2015.webm

**Comment by gnumdk** [comment]
Hmm, Gtk.ListBox is blue on selected, i was wrong!
