### ISSUE TITLE
The over effect on albums does not work anymore

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#165]
The over effect on albums does not work anymore (it was bug #78).

**Comment by gnumdk** [comment]
Report this one to GTK devs...
Lollypop now set GtkImage with a cairo surface (needed for HiDPI)

Such images do not support "gtk-image-effect: highlight"

Post bug id here.

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=751076
