### ISSUE TITLE
Automatic cover art download

### ISSUE THREAD

**Issue by monreal** [gnumdk/lollypop#166]
It would be nice if lollypop would download some cover art my itself. I love how easy it is to manually pick a new cover art file in Lollipop but I am not looking forward to do it for 500+ albums.

**Comment by gnumdk** [comment]
Already available, install pylast

**Comment by monreal** [comment]
Thanks for the quick reply. However, even after installing pylast this does not seem to work for me. Is there anything more to do?

**Comment by gnumdk** [comment]
What is lollypop output?

**Comment by monreal** [comment]
Oh, strange:

$ lollypop 
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

But pylast is installed:

$ rpm -q pylast
pylast-0.5.11-6.fc21.noarch

This is on Fedora 22 btw using lollypop-0.9.32-1.noarch

**Comment by gnumdk** [comment]
This is pylast for python2, not python3

**Comment by gnumdk** [comment]
sudo pip3 install pylast

**Comment by monreal** [comment]
It's working now, thanks!
