### ISSUE TITLE
Proxy support for last.fm and tune.in?

### ISSUE THREAD

**Issue by wealth** [gnumdk/lollypop#167]
I'm not sure if there is a proxy support already, but having proxy set in gnome settings does nothing. Last.fm and Tune.in just spin infinitely, while radio stream added by hand works fine.

**Comment by gnumdk** [comment]
Can you test?

**Comment by gnumdk** [comment]
https://github.com/goldsmith/Wikipedia/issues/99

**Comment by gnumdk** [comment]
https://github.com/pylast/pylast/issues/133

**Comment by gnumdk** [comment]
Seems to work here.

Wikipedia support is disabled as python-wikipedia doesn't support proxies...

**Comment by wealth** [comment]
works fine, thank you
