### ISSUE TITLE
Rescan will not remove the last artist(s) from the list.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [gnumdk/lollypop#170]
Hello

Apparently, when you remove some folders from your music collection, they are all removed correctly when you update your music library through Lollypop. However, for some reason this doesn't happen when you delete the last folder from your music folder (i.e. when it becomes completely empty); the last artist will remain in the list with its original tracks, but the album cover will disappear and none of the tracks will be playable.

Thanks in advance

**Comment by gnumdk** [comment]
Not a bug, i do a test, if collection is empty, lollypop doesn't delete the tracks...

Just a safeguard for people doing a scan with hard disk unmounted.

Is this a problem? Why do you scan folders with no tracks?

**Comment by hotoiledgoblinsack** [comment]
I see, well it's really more of an artifact of how I use Lollypop: I sometimes bring a bit of music to listen to on the other system from my main system and then delete it after I'm done with it there. Lollypop then deletes most of the vanishing tracks but never the last ones, this does explain the reason for that. 

It doesn't really bother me that much, but I just thought I'd report it as it seemed like a bug.
