### ISSUE TITLE
Wiishlist: Show album as "Various artists"

### ISSUE THREAD

**Issue by ninovolador** [gnumdk/lollypop#172]
I stumbled upon this marvellous player. It is really gorgeous! The only thing preventing me from using it, is the lack of a way to explicitally mark an album as a "Various artists" album. Instead, i am left with several "albums" each one of every artist playing that song. This is specially true with movie OST

Regards,

**Comment by gnumdk** [comment]
Your files are badly tagged...

Make sure all tracks "album artist" tag is empty and they will be marked as compilation.
