### ISSUE TITLE
Freezes when updating music

### ISSUE THREAD

**Issue by cisoun** [gnumdk/lollypop#173]
Hi !

I've got about 43 Gb of musics and when Lollypop tries to update my library, it freezes (but the music continues to play, even sometimes in loop). While it's doing that, I can't do anything but wait til it's done.
Is the update threaded ?

Edit : Seems like it's happening only when I'm trying to play a song at the same time.

**Comment by gnumdk** [comment]
Does it freeze at the end (of the scan)

Yes, all is threaded.

**Comment by cisoun** [comment]
Nope. When the scan is done, everything's okay.

**Comment by gnumdk** [comment]
Yes, but is the progress at 100% during the freeze?

**Comment by cisoun** [comment]
Around 85%. Nothing interesting in the output by the way.

**Comment by gnumdk** [comment]
lollypop -d

**Comment by cisoun** [comment]
Nothing special too. It continues to scan but the UI is stuck after Player::_on_stream_start().

**Comment by gnumdk** [comment]
Should be ok.

**Comment by cisoun** [comment]
Yay ! Seems like everything's ok.
Thank you very much for the fast update !
