### ISSUE TITLE
Please add internet search for lyrics of music being played

### ISSUE THREAD

**Issue by entodoays** [gnumdk/lollypop#175]
I would appreciate if the player would search for the lyrics of what's being played and show them in a pane, maybe on the right hand side of the screen.

**Comment by gnumdk** [comment]
There is no API available to get lyrics... The old one is closed, only extract from lyrics:
http://lyrics.wikia.com/api.php?func=getSong&artist=Nirvana&song=Rape%20me&fmt=json

Don't want to add a hack in lollypop...

**Comment by entodoays** [comment]
Guayadeque has a nice lyrics finder. Don't know if this is at all helpful.

**Comment by gnumdk** [comment]
I think it use a big hack, will give a look

**Comment by gnumdk** [comment]
https://www.musixmatch.com/fr

**Comment by gnumdk** [comment]
Non free...

**Comment by entodoays** [comment]
Guayadeque uses many different sources. In the .guayadeque folder there's a lyrics_sources.xml file with the different sources. Github doesn't seem to allow attaching an xml file to a comment.

**Comment by gigitux** [comment]
Watch this https://github.com/clementine-player/Clementine/tree/master/tools/ultimate_lyrics_parser

**Comment by gnumdk** [comment]
I know but this is not legal, you need to display lyrics site content because of licencing.

http://lyrics.wikia.com/LyricWiki:Permission

It's the same issue with all lyrics site...

I'm not sure i wan't to put webkit in lollypop... Maybe using google cache...

**Comment by gigitux** [comment]
Look here https://docs.genius.com/

**Comment by gnumdk** [comment]
@gigitux Cool!

**Comment by gnumdk** [comment]
But can't find a way to get lyrics with API...

**Comment by gnumdk** [comment]
Except as expressly authorized by Genius in writing, you agree not to modify, copy, frame, scrape, rent, lease, loan, sell, distribute or create derivative works based on the Service or the Genius Content, in whole or in part, except that the foregoing does not apply to your own User Content (as defined above) that you legally upload to the Service. In connection with your use of the Service you shall not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods.

**Comment by gnumdk** [comment]
I really think webkit is the only way to have something legal

**Comment by gigitux** [comment]
My fault, sorry :/

Lollypop is a good player, but with lyrics is perfect :D

**Comment by gnumdk** [comment]
Just remove wikia support, was broken... :-(
