### ISSUE TITLE
Can't click tracks to play in loved playlist.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [gnumdk/lollypop#178]
Hello

I'm not sure if this is intended behavior as I only recently started actually using the loved playlist, but I can't seem to click any of the entries in the playlist to start playing them. If this is intended behavior, ignore this bug report ;-).

Thanks in advance

**Comment by gnumdk** [comment]
Here it works... Any more informations ?

**Comment by hotoiledgoblinsack** [comment]
Ah, nevermind, it was due to a custom one-liner patch that had unintended side effects here that I completely did not expect. Sorry fo rthe inconvenience.
