### ISSUE TITLE
Problem with diacritics

### ISSUE THREAD

**Issue by prescott66** [gnumdk/lollypop#179]
As you can see on the screenshot, diacritics is not correctly displayed at artist name "Horkýže Slíže".
I get this issue on every titles with diacritics.
My locale is Slovak.

![snimka obrazovky z 2015-06-26 11-28-41](https://cloud.githubusercontent.com/assets/735265/8374558/937aba02-1bf6-11e5-95cc-864ec8bd9c27.png)

**Comment by gnumdk** [comment]
For me it's a configuration problem... Missing char in font. No?

**Comment by gnumdk** [comment]
Or broken mp3 with invalid encoding... Have you tested rewriting tags with easytag?

**Comment by prescott66** [comment]
in clementine and rythmbox is diacritics fine with same mp3s

**Comment by gnumdk** [comment]
Here setting Horkýže Slíže as artist works as expected. Send me an exemple mp3.

**Comment by prescott66** [comment]
here is that mp3
https://drive.google.com/file/d/0B7IVEEF2578rVnAtTnhwMVl0X1U/view?usp=sharing

**Comment by gnumdk** [comment]
Here, opening this file in easytag show broken tags...

**Comment by prescott66** [comment]
really?? hmm strange...ok, my mistake. sorry for bothering you

**Comment by gnumdk** [comment]
I don't know for rhythmbox but clementine may have some old Amarok 1.4 code trying to detect broken encoding in tags.
