### ISSUE TITLE
Notification after closing Lollypop window

### ISSUE THREAD

**Issue by prescott66** [gnumdk/lollypop#180]
If you enable playback after closing Lollypop, Music is playing but no icon/notification is available.
It would be good if Lollypop icon will be visible in tray (In gnome 3.16 bottom left corner) or just notification with actually played song with buttons pause/stop/next/display lollypop window

**Comment by gnumdk** [comment]
The tray is deprecated in GNOME.

I will give a look for notifications.

**Comment by gnumdk** [comment]
Here i've got a notification when window is closed.

**Comment by gnumdk** [comment]
https://extensions.gnome.org/extension/55/media-player-indicator/
