### ISSUE TITLE
No album arts

### ISSUE THREAD

**Issue by prescott66** [gnumdk/lollypop#181]
I see album arts only on few, really few albums.
Can be added more services from which can lollypop fetch album arts?

**Comment by gnumdk** [comment]
When you click on cover, you don't find your album art?

**Comment by prescott66** [comment]
oh, i can see covers then. but i will die until i click on all albumx :smile: can be added function to fetch covers automatically? function to fetch missing album arts.

**Comment by gnumdk** [comment]
Do you have lastfm plugin installed? Is lastfm popular in your country?

**Comment by prescott66** [comment]
i have installed only package liblastfm...i think its not popular

**Comment by gnumdk** [comment]
pip3 install pylast

**Comment by prescott66** [comment]
can you give me package name in arch repo?

**Comment by gnumdk** [comment]
python-pylast

**Comment by gnumdk** [comment]
and if you want, python-wikipedia ;)

**Comment by prescott66** [comment]
ok i have installed. and what now? :-)

**Comment by gnumdk** [comment]
It should download covers automatically

**Comment by gnumdk** [comment]
Closing your bug as i don't know services other than lastfm... There is musicbrainz without easy API.
