### ISSUE TITLE
No MRPIS cover art and position slider for external tracks

### ISSUE THREAD

**Issue by gipawu** [gnumdk/lollypop#186]
As title.

EDIT: position slider does not even work.

**Comment by gnumdk** [comment]
Cover art is wanted... There is no cache for externals and mpris doesn't support pixbuf...

For slider, only mpris one?

**Comment by gipawu** [comment]
I think cover art handling is doable as many other players, cache should be not needed, just load cover art every time track is loaded.

For slider, yes, only mpris one.

**Comment by gnumdk** [comment]
External cover art is embedded in files. Mpris can' t read it. Others players put it in cache. Will with around this issue.

**Comment by gnumdk** [comment]
Slider bug is a bug in mpris gnome shell extension, lollypop send 'mpris:length'

signal sender=:1.130 -> dest=(null destination) serial=36 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.mpris.MediaPlayer2.Player"
   array [
      dict entry(
         string "Metadata"
         variant             array [
               dict entry(
                  string "xesam:title"
                  variant                      string "Bailame / de Los tigrillos / Con Proyecto G"
               )
               dict entry(
                  string "xesam:genre"
                  variant                      array [
                        string "bailame"
                     ]
               )
               dict entry(
                  string "xesam:url"
                  variant                      string "file:///home/gnumdk/02%20-%20Proyecto%20G%20-%20Bailame%20_%20de%20Los%20tigrillos%20_%20Con%20Proyecto%20G.mp3"
               )
               dict entry(
                  string "xesam:albumArtist"
                  variant                      array [
                        string "Proyecto G"
                     ]
               )
               dict entry(
                  string "xesam:trackNumber"
                  variant                      int32 0
               )
               dict entry(
                  string "xesam:album"
                  variant                      string " - Inconnu"
               )
               dict entry(
                  string "mpris:length"
                  variant                      int64 172956734
               )
               dict entry(
                  string "xesam:artist"
                  variant                      array [
                        string "Proyecto G"
                     ]
               )
            ]
      )
   ]
   array [
   ]

**Comment by gnumdk** [comment]
Lollypop sends two "PropertiesChanged", gnome extension only update title and artist the 2nd time.
