### ISSUE TITLE
Party mode change the theme to black

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#188]
When i use party mode in Lollypop the application change theme to black instead of white
![capture du 2015-07-02 15 36 18](https://cloud.githubusercontent.com/assets/7660997/8478201/1941e72c-20d0-11e5-81a4-9006865e7ec7.png)
If you can make it optional it would be better i guess

**Comment by gnumdk** [comment]
No, party is the dark side of lollypop :p

**Comment by gnumdk** [comment]
As a workaround, you can disable the dark version of your GTK theme.
https://ask.fedoraproject.org/en/question/10304/how-do-i-ban-apps-from-using-gnome-3-adwaita-dark-theme/
