### ISSUE TITLE
Lollypop instantly quits

### ISSUE THREAD

**Issue by tdtmusic** [gnumdk/lollypop#190]
This happens on my elementary OS Freya setup. Double clicking on ANY mp3 file opens Lollypop for half a second and it quits instantly. Opening Lollypop first and playing the files works fine. What is going on?!

**Comment by gnumdk** [comment]
Run it in a console and paste me output.

**Comment by tdtmusic** [comment]
** (lollypop:15794): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-mGpV3xB1Wm: Connection refused
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia

** (lollypop:15794): CRITICAL **: Unable to determine array length for 0x7fa47009e0a0
LastFM::_download_album_img: Album not found
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/toolbar.py", line 91, in _on_current_changed
    self._toolbar_infos.on_current_changed(player)
  File "/usr/lib/python3/dist-packages/lollypop/toolbar_infos.py", line 74, in on_current_changed
    False)
  File "/usr/lib/python3/dist-packages/lollypop/art_album.py", line 131, in get_cover_for_uri
    pixbuf = self._pixbuf_from_tags(GLib.filename_from_uri(uri)[0], size)
  File "/usr/lib/python3/dist-packages/lollypop/art_album.py", line 283, in _pixbuf_from_tags
    None)
gi._glib.GError: Unrecognized image file format

**Comment by gnumdk** [comment]
Does it happen with other files?

**Comment by tdtmusic** [comment]
You mean other file types? The output above is from a flac file, it's the same as with mp3 files.

**Comment by gnumdk** [comment]
Send me a file with bug by email

**Comment by tdtmusic** [comment]
Ok, what is your email?

**Comment by gnumdk** [comment]
About dialog

**Comment by tdtmusic** [comment]
Done.

**Comment by gnumdk** [comment]
Elementary OS bug.

Works on Ubuntu 15.04/Fedora/ArchLinux

But now lollypop doesn't quit ;)
