### ISSUE TITLE
Can't find any music - Codec problem

### ISSUE THREAD

**Issue by Mythique** [gnumdk/lollypop#191]
Hello, I've installed Lollypop on Archlinux (using Pacman), and it doesn't seem to be able to find and play any music. Lollypop is supposed to look in my folder "musics" with some mp3 in it, at the start he's searching for new music, and I end up with a message saying I need to install codecs and restart Lollypop.

I don't know what to install, I've tried to reinstall gstreamer and install lame and flac using Pacman, but it didn't change anything.

**Comment by gnumdk** [comment]
Install gnome software

**Comment by Mythique** [comment]
Thanks. Installing the "gnome-software" package wasn't enough, I had to install the "gnome" package, but now it works fine.
