### ISSUE TITLE
Radio codecs

### ISSUE THREAD

**Issue by bugalo** [gnumdk/lollypop#192]
I am running gentoo linux, and I have lollypop 0.9.38 installed with emerge. I have been using it for a couple of weeks, and mostly everything works very well. Today I tried to add some radio stations from Lollypop's search tool, and after adding any of them, they don't play and I get the following message:

"Restart lollypop after installing codecs"

I restart it, and I keep getting the same issue. I just went ahead and downloaded the source code for the version 0.9.39, compiled and installed it, and I keep getting the same error. I get it for any radio station that I add. 

Can anyone confirm if it is a issue with Lollypop or if I have to install any external codec and which one?

Thank you in advance.

**Comment by gnumdk** [comment]
Install gnome software
