### ISSUE TITLE
Local album cover (cover.jpg) not showing under album view

### ISSUE THREAD

**Issue by shihjay2** [gnumdk/lollypop#195]
Album directories where there is an exisiting album cover (cover.jpg), saved by another program (ie MusicBrainz PIcard) is not being recognized and updated into database so that it can be viewed on album view (album cover is being shown when song is playing in the upper bar, however).  I understood that locally stored album covers were being recognized (as addressed by issue #127 previously) but it doesn't appear to work even after I remove and update the music database and scanning directories.

**Comment by gnumdk** [comment]
Clicking on "update database" shoud clean the cache

**Comment by shihjay2** [comment]
Thank you; it worked after clicking "update music".
