### ISSUE TITLE
Unable to launch from PPA or compile source on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by pythoninthegrass** [gnumdk/lollypop#196]
Installed via *ppa:gnumdk/lollypop* on Linux Mint 17.2 (Ubuntu 14.04.1) and get the following when launching lollypop:

```
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3/dist-packages/lollypop/application.py", line 44, in <module>
    from lollypop.window import Window
  File "/usr/lib/python3/dist-packages/lollypop/window.py", line 16, in <module>
    from lollypop.container import Container
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 20, in <module>
    from lollypop.selectionlist import SelectionList
  File "/usr/lib/python3/dist-packages/lollypop/selectionlist.py", line 22, in <module>
    class SelectionPopover(Gtk.Popover):
  File "/usr/lib/python3/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Popover'
```

If I try to compile it by hand:

```
./autogen.sh: 1: ./autogen.sh: autoconf: not found
**Warning**: I am going to run `configure' with no arguments.
If you wish to pass any to it, please specify them on the
`./autogen.sh' command line.`
`+ aclocal --install
./autogen.sh: 21: ./autogen.sh: aclocal: not found
+ exit 1
```

Which then leads to *make* failing as well:
```
make: *** No targets specified and no makefile found.  Stop.
```

Any ideas?

**Comment by bil-elmoussaoui** [comment]
Well , it's just not possible. Lollypop is not made for ubuntu 14.04, the version in ppa is for elementary OS freya 0.3 based on Ubuntu 14.04. This is due to the GTK version. The only solution is to update your system

**Comment by pythoninthegrass** [comment]
When you say update my system, do you mean install elementary OS or is there a way to update to the correct GTK (3.0?)?

**Comment by bil-elmoussaoui** [comment]
There's no need to install elementary OS. You just need a system that has a newer GTK version (3.14 or newer). You can install whatever DE you want. And you can't update GTK without updating the OS (it's might be possible but complicated and it's might broke something in your desktop)

**Comment by pythoninthegrass** [comment]
OK! Looks like until 15.04 officially drops, then GTK 3.14 is a no-go. Thanks for the timely responses bil-elmoussaoui! I'll go ahead and close this thread ;)

**Comment by kenden** [comment]
Related:
Lollypop does NOT support Ubuntu 14.04 / Linux Mint 17 (that's a pretty large user base, pity).
https://github.com/gnumdk/lollypop/issues/274
https://github.com/gnumdk/lollypop/issues/248

**Comment by gnumdk** [comment]
Ubuntu 14.04 doesn't support GtkPopover and Lollypop is build around this widget.

**Comment by gnumdk** [comment]
You may test with this ppa:
https://launchpad.net/~elementary-os/+archive/ubuntu/os-patches

May break your Ubuntu, do this if you know how to get back.
