### ISSUE TITLE
save Coverart in file as id3tag

### ISSUE THREAD

**Issue by HeaDBanGer84** [gnumdk/lollypop#197]
Can you implement an option to store downloaded cover art in the corresponding music-Files?
by the way: great work, i love the handling

**Comment by gnumdk** [comment]
After 1.0 released, will give a look.

**Comment by alexskc** [comment]
I'd personally be against this. To me, embedded artwork is a huge waste of space that has to be duplicated across every song for little benefit.

**Comment by gnumdk** [comment]
Will not be default as i agree with you ;)

**Comment by HeaDBanGer84** [comment]
I agree. But this feature is really useful, if you have a centralized music collection and use various programs to access (mediaserver/lollipop/vlc...).
If you use eyeD3 it is pretty easy to store the imageFile:

tag.addImage(eyeD3.ImageFrame.FRONT_COVER, coverFile)
tag.update()

**Comment by gnumdk** [comment]
If you find the same code example with gstreamer ;)

**Comment by coconutlulz** [comment]
Does gi allow you to call any gstreamer functions? https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gst-plugins-base-libs-0.10/gst-plugins-base-libs-gsttagid3.html#gst-tag-list-add-id3-image

**Comment by gnumdk** [comment]
@coconutlulz Will give a look at this. If you know how to write a GstTagList back to a file ;)

BTW, will be an hidden option in dconf. As I agree with @alexskc

**Comment by coconutlulz** [comment]
@gnumdk I can take a look at this in the meantime, if you like. It would be nice to be able to make a commit to a project that I use so much.

**Comment by gnumdk** [comment]
@coconutlulz What are you doing?

This bug report is about saving covers in files (id3 tags), not in sqlite db.

**Comment by coconutlulz** [comment]
@gnumdk Yeah, I understand. I didn't realise until today that Lollypop already reads images from tags. Going to revert what I've done so far.

**Comment by coconutlulz** [comment]
So, the kind people at gstreamer have told me that the file needs to be re-muxed to write tags back to it. They suggested encodebin: https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-encodebin.html

In my opinion, gst should be foregone for tagging.

MusicBrainz Picard uses Mutagen for tag handling; in my opinion, this would work well. But, do you want to add another dependency just for one feature?

https://mutagen.readthedocs.org/en/latest/

Let me know what you think.

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/commit/64847821209b178ae1bfb0ef6565918440ca0318

**Comment by gnumdk** [comment]
So no, do not want mutagen...

**Comment by gnumdk** [comment]
But if you find 3 command line tools able to add a picture to mp3/ogg/mp4, you can do this:
- Add a save button  to CoversPopover when commands are installed
- Launch command with Gio async

So no direct dependency.

**Comment by gnumdk** [comment]
Exemple how I launch tag editor in lollypop:
https://github.com/gnumdk/lollypop/blob/master/src/pop_menu.py#L415

**Comment by gnumdk** [comment]
Seems only  kid3 allow this from command line https://hydrogenaud.io/index.php/topic,96808.0.html

Will work on this tomorrow... Add an option to save covers to files...

**Comment by gnacho** [comment]
Don't let me change the option to write artwork in files. Any idea? 
![seleccion_001](https://cloud.githubusercontent.com/assets/10582292/18783226/f9f87c92-818a-11e6-8abf-ea573067365b.png)
