### ISSUE TITLE
Scrobbler scrobbles the same song multiple times

### ISSUE THREAD

**Issue by ConstruKction** [gnumdk/lollypop#205]
Sometimes the built-in scrobbler will send the same track multiple times to last.fm. 
The result looks as following:

![image](https://cloud.githubusercontent.com/assets/10813906/8708200/eb34c0e6-2b3a-11e5-8e34-14660b7baeed.png)

**Comment by gnumdk** [comment]
http://www.lastfm.fr/user/lollypop_gnome

Can reproduce :) Seems lastfm return errors when everything was ok :-(

**Comment by gnumdk** [comment]
LastFM::_now_playing(): There was an internal error. Please retry your request.

**Comment by gnumdk** [comment]
Can you run lollypop -d

and show me output when bug happen?

**Comment by ConstruKction** [comment]
The scrobbler's been doing an outstanding job ever since I submitted this issue. A couple of internal errors you've had, but no track multiplying. Sigh.

I'll keep monitoring my last.fm and make sure to send you the output when the bug occurs.

**Comment by ConstruKction** [comment]
Aha! Got it!

https://gist.github.com/ConstruKction/1d303ff3db908d5ff3a1

As you can see, on line 1 I'm playing a song.
On line 4, it scrobbles the song.
On line 7, it says it fails to scrobble the next song (from line 6), but it actually does.
And on line 9, for some reason, it scrobbles the song from line 4 for some reason again.

Aaaand, here is the duplicate.

![image](https://cloud.githubusercontent.com/assets/10813906/8711844/ea148082-2b55-11e5-87dd-d65793b6191a.png)

**Comment by gnumdk** [comment]
Should be fixed in git.

**Comment by gnumdk** [comment]
Can you test?

**Comment by gnumdk** [comment]
Ok, sure it's fixed ;)

**Comment by gnumdk** [comment]
You may need to report this to Lastfm:

Updating now playing sometimes fail with this message: "There was an internal error. Please retry your request."

Lollypop give a second try but no more.

**Comment by ConstruKction** [comment]
So far, so good. No problems whatsoever.
