### ISSUE TITLE
Lollypop use too much from my CPU

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#206]
In gnome-system-monitor I see lollypop use the mose of the time something like
8%-9% from my CPU.

It a lot because I have 8 CPU (i7-3770 CPU), so just when I compile something big
I see thos uses from my CPU.

**Comment by gnumdk** [comment]
Full usage of your CPU is 800%, it's how linux works. 100% per core.

And as python can't use more than one core, be sure it's not using 9% of your 8 cores ;)

Here, on I7-4510U with 4 cores, lollypop is at 2%

**Comment by yoseforb** [comment]
You know the voice you haer from your CPU when you build huge lib like webkit? I hear almost the same when I start lollypop and not hear this voice anymore from the second I quit lollypop.

On the screenshot, the first row is lollypop (python3 /usr/bin/lollypop).

![lollypop-gnome-sysmtem-monitor](https://cloud.githubusercontent.com/assets/2222697/8765950/4e62410c-2e2e-11e5-9fe6-7c2805eee141.png)

**Comment by gnumdk** [comment]
Is lollypop playing?

**Comment by yoseforb** [comment]
Yes, lollypop is playing and works nice, it just use too much CPU.

**Comment by gnumdk** [comment]
10% off an 8 core CPU is 1.25% of total CPU, can't call this too much CPU usage.

One more, it's more a gstreamer issue if you really think it's too much.

**Comment by yoseforb** [comment]
IIRC, the first time I have seen this it was right before my screen die (three weeks ago), before this
lollypop used just 1% of my CPU, so I'm sure it something here in lollypop thas cause this to happen.

And why it is gstreamer issue? It sound more related to the db, my suggest.

**Comment by gnumdk** [comment]
Lollypop only access the db on actions, not while playing.

**Comment by yoseforb** [comment]
I not see any different in lollypop's cpu use, if it playing or not.

**Comment by gnumdk** [comment]
Is lollypop scanning? Happen with all views?

**Comment by yoseforb** [comment]
It happen all the way from the moment I start lollypop to the moment I closed it.

**Comment by gnumdk** [comment]
Don't happen with others gtk apps?
What graphic card?

**Comment by yoseforb** [comment]
Maybe it realte to GTK+? I have GTK+ from git master.

It not happen in another GTK+ apps.

**Comment by lazka** [comment]
bisected to https://git.gnome.org/browse/gtk+/commit/?id=fe51ac273c8045279a222c22a52d297d5ede4169

**Comment by gnumdk** [comment]
Thanks for bisect.
For me it's a gtk bug, I only use style context to add custom css, will give a look but looks like a gtk bug.

**Comment by gnumdk** [comment]
Does last commit fix issue?

**Comment by lazka** [comment]
No, still the same.

**Comment by gnumdk** [comment]
Can  reproduce with gnome-devel archlinux repo.

And here, lollypop use 60% of CPU!

**Comment by lazka** [comment]
Nice catch, filed here: https://bugzilla.gnome.org/show_bug.cgi?id=752695

**Comment by yoseforb** [comment]
Thaks, come back lollypop :-)
