### ISSUE TITLE
"lollypop" is not responding.

### ISSUE THREAD

**Issue by BPaden** [gnumdk/lollypop#207]
This message is popping up constantly on GNOME 3.16 while listening to Radio Paradise, though the music doesn't actually stop. I also have a ton (as in 45000+ lines in a couple of hours) of messages like this in my journal:

Jul 16 15:39:06 aaron-tower1 lollypop.desktop[16142]: (lollypop:16142): Gtk-CRITICAL **: gtk_widget_get_visible: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by BPaden** [comment]
Ok, looks like while gstreamer is still running, the UI **is** blocked.

**Comment by gnumdk** [comment]
More informations on how reproduce the bug?
Just playing a radio?
What URL?

**Comment by BPaden** [comment]
http://www.radioparadise.com/m3u/aac-64.m3u

Unfortunately, I haven't reproduced this yet and I don't know if it's related to the stream or not. Any idea how this error message could be triggered? At first I thought maybe it was related to CPU usage, just because of the nature of the error and because my computer happened to be busy at the time. Looks like it was just a coincidence, though. :/

**Comment by gnumdk** [comment]
Distro?

**Comment by BPaden** [comment]
Arch x64

**Comment by gnumdk** [comment]
I close this one, reopen it if you reproduce it again.

I think it has been fixed recently by another bug fix.
