### ISSUE TITLE
Cannot play mms radio

### ISSUE THREAD

**Issue by sunng87** [gnumdk/lollypop#208]
I just added some TuneIn radio channels but when I click the radio art nothing happened.

I thought it was a codec issue, but I can play the radio if I paste the mms url into Totem.  Then I looked into the code, I found in player_radio.py, the signal `entry-parsed` is never triggered. Then I tried to use the synchronous call `parser.parse` and got `TOTEM_PL_PARSER_RESULT_UNHANDLED`.

I'm on Archlinux and have most dependencies update to date. I have no idea why the playlist cannot be parsed. This might not a lollypop issue, but it will be appreciate if you could help me to figure out the root cause. Thanks!

**Comment by gnumdk** [comment]
Please give me an url as example.

**Comment by sunng87** [comment]
Thanks! Please try:

mms://live.njgb.com/fm981
and
mms://alive.rbc.cn/fm1006

**Comment by gnumdk** [comment]
[bellegardec@arch ~]$ mpv mms://live.njgb.com/fm981
Playing: mms://live.njgb.com/fm981
[ffmpeg] http: HTTP error 404 Not Found
Failed to open mms://live.njgb.com/fm981.


Exiting... (Errors when loading file)

**Comment by sunng87** [comment]
Have you tried vlc?

I can't play it with mpv either, but vlc works.
![screenshot from 2015-07-17 15-55-01](https://cloud.githubusercontent.com/assets/221942/8742890/4cd85d50-2c9c-11e5-9bad-186550ad4c95.png)

**Comment by sunng87** [comment]
Thanks for the fix!
