### ISSUE TITLE
Radio validaton

### ISSUE THREAD

**Issue by BPaden** [gnumdk/lollypop#209]
If you get the entries backwards and put the url in the name entry, lollypop will silently fail. Similarly, if your address entry doesn't have a valid url, it will still allow you to add the radio–clicking on it will have no effect. Probably some kind of input validation would be useful here.

**Comment by gnumdk** [comment]
Silently fail is fixed in git: Names with /

Input validation is hard, what protocols? Don't know...

**Comment by BPaden** [comment]
> Silently fail is fixed in git:

Oh, cool. Sorry for the noise.

> Input validation is hard, what protocols? Don't know...

Well the behaviour is different if the address contains an invalid url (clicking on it does nothing), and a valid url that does not point to a valid stream (lollypop will try to connect and fail with a suggestion that you install some codecs), so some kind of validation is happening at some level.

It might be good if you could check for this earlier, but the most likely case for this is probably when you get the entries backwards and put the url in the name entry, so if you check for this already in the git version, it's probably not important.
