### ISSUE TITLE
Suggestion - Option not to consume songs in queue

### ISSUE THREAD

**Issue by rolf1304** [gnumdk/lollypop#21]
Hey,

First of all, thanks for this absolutely beautiful music player. The code is also really clean, and for now it looks like it handles my large library fine (unlike GNOME Music).

I have a suggestion though: Songs in the queue are automatically consumed (they disappear from the queue once they start playing). Please provide an option to turn off this behavior.

**Comment by gnumdk** [comment]
I close this one because user playlists are now available in git.
