### ISSUE TITLE
Ability to blacklist/remove folders/tracks from library

### ISSUE THREAD

**Issue by deuill** [gnumdk/lollypop#211]
Hi and thanks for this excellent piece of software! In a very short time, it has become more feature-rich and usable (not to mention faster) than most other music players with good GNOME integration.

My only request would be adding the ability to blacklist or remove folders and tracks from the library... for instance, my music library is fairly well-organized, but within certain folders exist tracks that are either randomly added or have bad metadata, and which should ideally not appear in the library (especially since there is no way of grouping said "bad" tracks).

Right now I explicitly added all folders that I would like to index, but with over 200 folders and more being added from time to time, it would be much better if I could specify one or more folders to index (as is currently possible), and a separate list of folders to skip when indexing. It would also be nice to be able to remove a track, album or artist from the index (or any kind of grouping, if possible).

Again, thank you for this amazing music player!

**Comment by gnumdk** [comment]
https://github.com/clementine-player/clementine/issues/3011

I really don't want Lollypop to be unmaintainable adding options and options...

On more I don't want to add options because your music management is broken ;)

Here how i do:
~/Music/Collection
~/Music/Tmp

Tmp is where i put badly tagged tracks.

**Comment by deuill** [comment]
Cool, I appreciate the reply (and the sentiment)! ;)

**Comment by medicamin** [comment]
it's not really an "option". you could just add a function that Lollypop excludes folders which has a .nomedia file. Just like Android. without any option in the user front end.
