### ISSUE TITLE
error on sidebar scrolling with gtk+ trunk

### ISSUE THREAD

**Issue by lazka** [gnumdk/lollypop#212]
```
Traceback (most recent call last):
  File ".../lib/python3.4/site-packages/lollypop/selectionlist.py", line 418, in _on_scroll
    self._popover.set_pointing_to(r)
TypeError: argument rect: Expected Gdk.Rectangle, but got gi.repository.cairo.RectangleInt
```

You probably want to use Gdk.Rectangle instead of cairo.RectangleInt which should work with old and new gtk/pygobject versions. See https://git.gnome.org/browse/pygobject/commit/?id=7a3bb6971f22accd25e987496d377e1879f6e1ba

**Comment by gnumdk** [comment]
Using Gdk.Rectangle() give me the same error.

**Comment by lazka** [comment]
So, did it work or not? (the above commit is by me, and I'm wondering if I missed something..)

**Comment by gnumdk** [comment]
It's working... Was just using Gtk 3.17 without upgraded introspection.

**Comment by lazka** [comment]
ok, thanks :)
