### ISSUE TITLE
Build issue in Ubuntu 15.04

### ISSUE THREAD

**Issue by slugbalancer** [gnumdk/lollypop#214]
Newbie question no doubt but ... 

When I run 'make' I get this at the end;

'Making all in help
make[2]: Entering directory '/home/tim/lollypop/help'
Makefile:473: *** missing separator (did you mean TAB instead of 8 spaces?). Stop.
make[2]: Leaving directory '/home/tim/lollypop/help'
Makefile:526: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/tim/lollypop'
Makefile:422: recipe for target 'all' failed
make: *** [all] Error 2' 

Any ideas please?  thx.

**Comment by gnumdk** [comment]
Install my ppa and do this:
- Activate source code for ppa in ubuntu software properties
- sudo apt-get build-dep lollypop

**Comment by slugbalancer** [comment]
thx so much for the quick reply. 
I didn't understand your reply but I did; 

sudo add-apt-repository ppa:gnumdk/lollypop
sudo apt-get update
sudo apt-get install lollypop

and it seems to be working and it seems to be the latest version too (0.9.42 ???). 

(One day I'll build something successfully from the source if it's the last thing I do :)  )
