### ISSUE TITLE
Not finding some album art

### ISSUE THREAD

**Issue by monreal** [gnumdk/lollypop#217]
I noticed that Lollypop seems to have much trouble finding album art for albums with "( )" in the album name. I noticed because most of my multi-disc albums have "(disc 1 of 2)" and are missing album art. Not sure how the string matching works here, maybe it would help to cut just the "( )" characters or maybe the whole part in between, too?

**Comment by gnumdk** [comment]
Won't fix.

There is a disc tag, fix your tags...
