### ISSUE TITLE
Tags of recently added music don't refresh after editing

### ISSUE THREAD

**Issue by nooknooknook** [gnumdk/lollypop#219]
After adding a lot of music I changed the tags (once or twice) via the Modify Information option, through EasyTag. Other players (Rhythmbox, mpd) recognize the change but not lollypop. Any way to force this, preferably without losing the list of Recently Added albums?

For example a two track album was missing track numbers so lollypop ordered them from filename and gave them 1 and 2 within the program. But even after changing it (ie. reversing the track order) the track numbers won't update. Same problem with album names, I get two albums as if it picked up that some tracks' album name changed but not others.

Using the latest version of lollypop-git from aur and files are in mp3

**Comment by gnumdk** [comment]
$ gsettings set org.gnome.Lollypop db-version 0

If it fix the issue, then there is an issue in lollypop, otherwise, there are mutliple frames in your mp3, use puddletag (and remove option about preserving mtime in puddletag).

**Comment by gnumdk** [comment]
I can confirm the issue for album name

**Comment by gnumdk** [comment]
No, i do not confirm, issue was about multiple mp3 frame (APEv2 vs id3 tags)

**Comment by nooknooknook** [comment]
Resetting the database worked. Anything I can do to help you find/solve the issue?

**Comment by gnumdk** [comment]
OK, will try to reproduce from my side.
I close, reopen it if it happens again.
