### ISSUE TITLE
Lollypop does not import all the songs

### ISSUE THREAD

**Issue by cristobaltapia** [gnumdk/lollypop#224]
I have a very large collection of music in my computer (according to Rhythmbox in total there are 21541 songs), but when Lollypop imports the music into its database not every song is added. There are lots of missing albums or albums with just one song.

**Comment by gnumdk** [comment]
$ rm -f ~/.local/share/lollypop/lollypop.db
$ lollypop -d

**Comment by cristobaltapia** [comment]
Hi gnumdk,
I did what you wrote, and the result is the same. I think that the files that are not being imported are *.mp4. But I thought that this format was supported.

**Comment by gnumdk** [comment]
I need lollypop -d output...

**Comment by cristobaltapia** [comment]
This is the problem:

/home/tapia/Music/Javiera & Los Imposibles/La Suerte/06. Dulce Veneno.mp4 not detected as a music file
/home/tapia/Music/Javiera & Los Imposibles/Corte en tramite/09. Esto.mp4 not detected as a music file
/home/tapia/Music/Javiera & Los Imposibles/Corte en tramite/01. Me voy.mp4 not detected as a music file
/home/tapia/Music/Javiera & Los Imposibles/Corte en tramite/06. Tumba sin flores.mp4 not detected as a music file

... and so on.
They are not being detected as music files (as the output say)

**Comment by gnumdk** [comment]
Ok, what is mime type?

**Comment by cristobaltapia** [comment]
audio/x-m4a

**Comment by gnumdk** [comment]
Can you send me a file by email? My email is in about dialog.

**Comment by gnumdk** [comment]
Thanks ;)

**Comment by cristobaltapia** [comment]
That was a quick answer!

**Comment by gnumdk** [comment]
video/mp4

**Comment by cristobaltapia** [comment]
strange... I did this:
file --mime-type file.mp4 
and got
audio/x-m4a

**Comment by cristobaltapia** [comment]
Well, good to know it should work now.

**Comment by gnumdk** [comment]
Should be an issue in glib...

**Comment by cristobaltapia** [comment]
Just compiled the latest git version and every song is being imported now ;)
Good night!
