### ISSUE TITLE
Visualization while playing a radio station

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#226]
When you listen to a radio station in the Lollypop, there is a lot of empty space in the interface. 

![Image of current radio window](http://www.dodaj.rs/f/1E/hJ/XTRJyIx/---2015-08-09-11-11-46.png)

Maybe there should be some kind of visualization (think of old school Winamp)? What do you think about this?

**Comment by region51** [comment]
@kostich опа, опередил, я тоже хотел на днях задать такой вопрос.

**Comment by kostich** [comment]
@region51
Sorry, I do not speak Russian(?). But if Google Translator was correct, then yea, it would really be nice to fill this space with something a bit more eye pleasing.

**Comment by gnumdk** [comment]
There is no empty space, this is where lollypop show saved radios.

For visualization, use mproject-pulseaudio.

**Comment by kostich** [comment]
I didn't know that. Maybe there should be some kind of visual clue that this space will be populated with saved radio stations. I didn't even know that you could save radio stations in Lollypop. :(

**Comment by gnumdk** [comment]
Will add a default string in widget.
