### ISSUE TITLE
IndexError: list index out of range when playing specific mp3 from library

### ISSUE THREAD

**Issue by kelvan** [gnumdk/lollypop#232]
I'm using lollypop 0.9.42

I have a specific file that crashes lollypop everytime when played using Genre -> Artist.
It plays fine if "opened with".
It's also ok if played from search or added to queue and played afterwards.
Only thing special about this file is, that is has a unique genre.

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 243, in _on_stream_start
    self.set_next()
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 229, in set_next
    self.next_track = LinearPlayer.next(self)
  File "/usr/lib/python3.4/site-packages/lollypop/player_linear.py", line 51, in next
    track_id = tracks[0]
IndexError: list index out of range

**Comment by gnumdk** [comment]
Unique track from album with this genre? Or other tracks have this genre + one other?

**Comment by gnumdk** [comment]
Please send me ~/.local/share/lollypop/lollypop.db by email

And with a gdrive/dropbox zip with album ;)

**Comment by gnumdk** [comment]
email in about dialog

**Comment by gnumdk** [comment]
Ok, I think i know what is happening: is shuffle by artist active?

**Comment by kelvan** [comment]
I think so, have to check it when I'm back home.
The track has the (strange) genre "Dream", it is in an album with other genres and there is no other track with this genre in the db.

**Comment by gnumdk** [comment]
And can you check with current git too? :)

**Comment by kelvan** [comment]
Checked with current master and the bug seems to be gone, thx :)
