### ISSUE TITLE
[ OT ] Theming question

### ISSUE THREAD

**Issue by msx** [gnumdk/lollypop#234]
Hi,

This question is somewhat unrelated to Lollypop itself (btw, I love it) but it has been melting my brains for a while now...

I'm running Fedora 22 w/ GNOME 3.16.2. Now, the default Adwaita theme has a HUGE title frame for the GTK3 apps. However, I see in the screenshots of Lollypop that the top window frame is much more smaller than the default Adwaita theme... so my question is: does anybody know how to reproduce that?

Thanks.

**Comment by gnumdk** [comment]
The top window frame is Adwaita one in screenshot.

**Comment by msx** [comment]
Thank you for your quick reply Cédric!
I wonder why on my system Adwaita so, so huge: https://i.imgur.com/Ntw9RFP.png.

Loving Lollypop so far.

**Comment by gnumdk** [comment]
![ntw9rfp](https://cloud.githubusercontent.com/assets/3918824/9269790/0e4b89cc-426d-11e5-98e3-fb957c9661f5.png)

It's your eyes :p

**Comment by msx** [comment]
Hats off my friend: http://goo.gl/KcTBwu
