### ISSUE TITLE
A better website

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#235]
The application is so great and deserves a better website! 
Maybe someone can help you to redesign it? Or do you have any plans on doing that in the near future ;)

**Comment by gnumdk** [comment]
Not me :)

**Comment by bil-elmoussaoui** [comment]
I think sharing this with your google+ followers might help you find a designer to work on it ;)

**Comment by gnumdk** [comment]
https://plus.google.com/+RedaLazri/posts/jFQ1ie3Pp6d

**Comment by bil-elmoussaoui** [comment]
If you've already the icons, i might help doing the CSS/HTML part ;)

**Comment by gnumdk** [comment]
https://raw.githubusercontent.com/gnumdk/lollypop/master/data/icons/hicolor/256x256/apps/lollypop.png

**Comment by gnumdk** [comment]
HTML is in gh-pages branch of lollypop

Datas are here: https://github.com/gnumdk/lollypop-data

**Comment by bil-elmoussaoui** [comment]
i will start working on it as soon as possible

**Comment by quassy** [comment]
Ping me if you need help @bil-elmoussaoui, I'd be glad to help out.

**Comment by wi1d5ky** [comment]
I'd like to help!

**Comment by bil-elmoussaoui** [comment]
i have something to do this week. i will start as soon as i can; if anyone wants to start i will be happy to contribute ;)

**Comment by wi1d5ky** [comment]
okay, here is the first step!
preview: http://wi1d5ky.github.io/lollypop.github.io/
repo: http://github.com/wi1d5ky/lollypop.github.io/

**Comment by gnumdk** [comment]
It looks good :)

**Comment by gnumdk** [comment]
Should be cool to the same gradient effect around lollypop screenshot.

I'm not fan of the blended background from original mockup.

**Comment by wi1d5ky** [comment]
I want the background effect, but I don't have the image.
Making gradient might be easy, I will try it. today :)

**Comment by gnumdk** [comment]
The image is a screenshot of lollypop.

**Comment by gnumdk** [comment]
Any news on this ? :) I back from hollydays!

**Comment by bil-elmoussaoui** [comment]
I started school this week, it will be hard for me to fix issues and improve the website. The website is so far better and looks nice than before;) i will keep an eye on this and i will do what i can as soon as possible

**Comment by gnumdk** [comment]
Merged in main site:
- I removed google fonts because i hate web site not using user fonts ;)
- I removed versionning until we have a cool way to see changelog
- I add a package entry opening a new page, not perfect;

Clone this version and send me pull request.

And put your copyright somewhere in the site ;)

**Comment by gnumdk** [comment]
Ok, i created a new repository since gh-pages was making lollypop repository to fat.

You are contributors, no pull request needed, just commit ;)

**Comment by wi1d5ky** [comment]
okay, thx!
I will transfer old commit history to that repo.
