### ISSUE TITLE
[ USABILITY IMPROVEMENT ] Make the main window draggable from the time bar when the song is paused

### ISSUE THREAD

**Issue by msx** [gnumdk/lollypop#237]
Hi,
I don't know if this is possible or not but it would be handy to be able to drag the window even from the time bar when no song is played.
I know, this is a very minor tweak but hey, polishing small details sometimes makes a difference :)
Cheers.

**Comment by gnumdk** [comment]
This is handled by GTK.
Try to report a bug to GTK devs. Inactive widgets in header bar.
