### ISSUE TITLE
Compilations not detected as compilations

### ISSUE THREAD

**Issue by eonpatapon** [gnumdk/lollypop#238]
I have a bunch of compilations in my library that have "Various Artists" in the album artist tag. And now I have a "Various Artists" in the artiist DB.

How and where the detection is made ?

**Comment by gnumdk** [comment]
Like in Clementine and Amarok.

Compilations are albums with multple artists and without an album artist tag.

**Comment by eonpatapon** [comment]
FYI theses compilations are correctly detected in Clementine. Didn't check in Amarok.
