### ISSUE TITLE
Crash on doubleclick in the queue list

### ISSUE THREAD

**Issue by SnouF** [gnumdk/lollypop#24]
Pour reproduire le bug :
- Ajoutez quelque morceaux dans le liste d'attente
- Double-cliquez dans la liste d'attente

To reproduce the bug:
- Add some pieces in the queue list
- Double-click in the queue list

lollypop version : 0.8.19
error : Erreur de segmentation

**Comment by gnumdk** [comment]
Can't reproduce here, Ubuntu?

**Comment by SnouF** [comment]
aptosid (debian unstable)
Gtk version is 3.14.5
no backtrace (in shell I have "Erreur de segmentation")

**Comment by gnumdk** [comment]
Maybe using coredumpctl?

**Comment by SnouF** [comment]
I do not know to use "coredumpctl" (and I can not find a package containing coredumpctl. In root commands coredumpctl systemd-coredumpctl does not exist :()

**Comment by gnumdk** [comment]
So not using systemd ;)

Will try to debootstrap debian sid to test this...

**Comment by SnouF** [comment]
Sorry, but Cella gets a little too complicated for me.

**Comment by gnumdk** [comment]
I will try ;)

**Comment by gnumdk** [comment]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `python3 /usr/local/bin/lollypop'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f41ff66604b in g_sequence_iter_get_sequence ()
   from /lib64/libglib-2.0.so.0
Missing separate debuginfos, use: debuginfo-install python3-3.4.1-16.fc21.x86_64
(gdb) backtrace
#0  0x00007f41ff66604b in g_sequence_iter_get_sequence ()
    at /lib64/libglib-2.0.so.0
#1  0x00007f41fd17c2e1 in iter_is_valid () at /lib64/libgtk-3.so.0
#2  0x00007f41fd17c507 in gtk_list_store_get_value () at /lib64/libgtk-3.so.0
#3  0x00007f41ff3ffd60 in ffi_call_unix64 () at /lib64/libffi.so.6
#4  0x00007f41ff3ff7d1 in ffi_call () at /lib64/libffi.so.6
#5  0x00007f41fffedad4 in pygi_invoke_c_callable ()
    at /usr/lib64/python3.4/site-packages/gi/_gi.cpython-34m.so
#6  0x00007f41fffef3d8 in pygi_function_cache_invoke ()
    at /usr/lib64/python3.4/site-packages/gi/_gi.cpython-34m.so
#7  0x00007f41fffe35ae in _callable_info_call ()
    at /usr/lib64/python3.4/site-packages/gi/_gi.cpython-34m.so
#8  0x00007f420799dea1 in PyObject_Call () at /lib64/libpython3.4m.so.1.0
#9  0x00007f4207a4f96d in PyEval_EvalFrameEx () at /lib64/libpython3.4m.so.1.0
#10 0x00007f4207a5493f in PyEval_EvalCodeEx () at /lib64/libpython3.4m.so.1.0
#11 0x00007f42079c6299 in function_call () at /lib64/libpython3.4m.so.1.0
#12 0x00007f420799dea1 in PyObject_Call () at /lib64/libpython3.4m.so.1.0
#13 0x00007f42079b30dd in method_call () at /lib64/libpython3.4m.so.1.0
#14 0x00007f420799dea1 in PyObject_Call () at /lib64/libpython3.4m.so.1.0
#15 0x00007f4207a4b957 in PyEval_CallObjectWithKeywords ()
    at /lib64/libpython3.4m.so.1.0
#16 0x00007f41fffeb630 in _pygi_closure_handle ()
    at /usr/lib64/python3.4/site-packages/gi/_gi.cpython-34m.so
#17 0x00007f41ff3ffb4f in ffi_closure_unix64_inner () at /lib64/libffi.so.6
#18 0x00007f41ff3ffec8 in ffi_closure_unix64 () at /lib64/libffi.so.6
#19 0x00007f41ff64c553 in g_timeout_dispatch () at /lib64/libglib-2.0.so.0
#20 0x00007f41ff64baeb in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#21 0x00007f41ff64be88 in g_main_context_iterate.isra ()
    at /lib64/libglib-2.0.so.0
#22 0x00007f41ff64bf3c in g_main_context_iteration ()
    at /lib64/libglib-2.0.so.0
#23 0x00007f41fef240cc in g_application_run () at /lib64/libgio-2.0.so.0
#24 0x00007f41ff3ffd60 in ffi_call_unix64 () at /lib64/libffi.so.6
#25 0x00007f41ff3ff7d1 in ffi_call () at /lib64/libffi.so.6
---Type <return> to continue, or q <return> to quit---
#26 0x00007f41fffedad4 in pygi_invoke_c_callable ()
    at /usr/lib64/python3.4/site-packages/gi/_gi.cpython-34m.so
#27 0x00007f41fffef3d8 in pygi_function_cache_invoke ()
    at /usr/lib64/python3.4/site-packages/gi/_gi.cpython-34m.so
#28 0x00007f41fffe35ae in _callable_info_call ()
    at /usr/lib64/python3.4/site-packages/gi/_gi.cpython-34m.so
#29 0x00007f420799dea1 in PyObject_Call () at /lib64/libpython3.4m.so.1.0
#30 0x00007f4207a4f96d in PyEval_EvalFrameEx () at /lib64/libpython3.4m.so.1.0
#31 0x00007f4207a5493f in PyEval_EvalCodeEx () at /lib64/libpython3.4m.so.1.0
#32 0x00007f4207a549eb in PyEval_EvalCode () at /lib64/libpython3.4m.so.1.0
#33 0x00007f4207a70bb4 in run_mod () at /lib64/libpython3.4m.so.1.0
#34 0x00007f4207a72e35 in PyRun_FileExFlags () at /lib64/libpython3.4m.so.1.0
#35 0x00007f4207a73e13 in PyRun_SimpleFileExFlags ()
    at /lib64/libpython3.4m.so.1.0
#36 0x00007f4207a89fcc in Py_Main () at /lib64/libpython3.4m.so.1.0
#37 0x0000000000400ad6 in main ()

Here backtrace.

**Comment by SnouF** [comment]
Thank you!
And good continuation for this beautiful and responsive player
PS: Is there a roadmap that we can consult?

**Comment by gnumdk** [comment]
There is no roadmap but one in my head:
- Playlist support
- Search/play songs on youtube and integrate populars one in party mode

**Comment by SnouF** [comment]
Thank you for infos

No management podcasts planned?
Or librefm / lastfm support?

But whether podcasts, librefm / or youtube lastfm personally I propose instead functionalities such as extensions because it is not useful to everyone. What I like about it is lollypop that is lightweight and the interface is "sober".

**Comment by gnumdk** [comment]
I do not plan to add a plugin architecture in lollypop... I wan't the base code to be KISS...
But i plan to add Grilo support and Grilo is plugin based ;)

**Comment by SnouF** [comment]
I did not know giro; it's better!

Good luck for this project ;)
