### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by gnunn1** [gnumdk/lollypop#245]
Lollypop 0.9.42 doesn't play any sound on my laptop, I'm not sure when this started happening but it was definitely working previously in Lollypop but I'm not sure if it broke due to an upgraded Lollypop or some other package. Lollypop seems to think the song is playing as the slider shows the music progressing, but no sound is coming out of the speakers or headphones.

All other applications continue to work fine, if I play a song via totem I hear it as expected. What back-end is Lollypop using to play music?

**Comment by gnumdk** [comment]
Check lollypop volume in sound settings.

**Comment by gnunn1** [comment]
The application volume was 100%, but interestingly I just got back from a business trip and connected my computer to the external speakers. Once I switched the sound applet to the external speakers it worked and switching back to the internal laptop speaker was fine from then on. On business trips I switch constantly between a bluetooth speaker, headphones and HDMI so maybe something got screwed up there.

**Comment by blackjackshellac** [comment]
I had this happen today, volume for the application in Sound Settings was turned all the way down.  This was on 0.9.86 in Fedora 23.

**Comment by gnumdk** [comment]
@blackjackshellac Due to crossfading... Open a new a bug if able to reproduce.

**Comment by gnumdk** [comment]
@blackjackshellac I think it's now fixed

**Comment by blackjackshellac** [comment]
I'll let you know. I haven't been able to reproduce so far.  Thanks.
