### ISSUE TITLE
Suggestion - Random by album

### ISSUE THREAD

**Issue by SnouF** [gnumdk/lollypop#25]
Would it be possible to implement a random mode album?

This mode would play an album at random from the first to the last track.

Implement this function with a 2 modes button seem like a good solution. A simple click switche mode to another, a long-click displays a context menu
- release => random unactived
- down => random by track
- down with another icon => random by album

PS: Is it a bit early to make feature requests? Must expect that the development is a little more advanced

**Comment by gnumdk** [comment]
In fact, it's already available, they are many random modes in lollypop:
- Popular random if you start a track in popular view
- All tracks random if you start a track in all artists view
- Artist random if you start a track in artist view
- Album random if you start playing album from search :-(

So you're right, it's not easy to find and i will add soon an entry in album menu to only play album

Keep in mind lollypop playlist is contextual ;)

**Comment by SnouF** [comment]
I'm not sure we understood we are 

I do not want played at random track of an album but playing an entire album at random. For example

- This mode would randomly album
- Play all tracks of this album in the order
- Once you finish the album takes another album randomly

And if we are understood us I have not manage to use the function :(

**Comment by gnumdk** [comment]
Hmm, ok, i see, will give a look.

**Comment by gnumdk** [comment]
Available in all artist view, please test ;)

**Comment by SnouF** [comment]
To far I used the deb of ppa. I have a problem when running the autogen.sh

<pre>
checking pkg-config is at least Version 0.16 ... yes
./configure: line 13569: syntax error near unexpected token `1.35.9 '
./configure: line 13569: `GOBJECT_INTROSPECTION_REQUIRE (1.35.9) '
</pre>

If I comment line 
<pre>
#GOBJECT_INTROSPECTION_REQUIRE([1.35.9])
</pre>
I can build it

After build (and unistall deb)
I go in "Tous les artistes" and run "Lire l'album" with random button pushed.
lollypop play tracks of this album in random mode but not play other albums

Other think, now when I click on current track playing lollypop crash

Backtrace
<pre>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/view.py", line 201, in _add_albums
    widget.eventbox.get_window().set_cursor(Gdk.Cursor(Gdk.CursorType.HAND1))
AttributeError: 'ArtistWidget' object has no attribute 'eventbox'

(lollypop:18327): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(lollypop:18327): GLib-GObject-CRITICAL **: g_signal_handler_is_connected: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(lollypop:18327): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(lollypop:18327): GLib-GObject-CRITICAL **: g_signal_handler_is_connected: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(lollypop:18327): GLib-GObject-WARNING **: instance with invalid (NULL) class pointer

(lollypop:18327): GLib-GObject-CRITICAL **: g_signal_handler_is_connected: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
</pre>

**Comment by gnumdk** [comment]
I just updated "Play album" label as it wasn't explicit...

Just play a track in All artists view to have "shuffle album" behaviour

**Comment by SnouF** [comment]
Good job!

But I would have a preference for the tracks of the album is played in sequence (the order is important for some albums)

And the best would be to pass to next album (with right click on next, for example). But I do not know if this is the philosophy of the application

**Comment by gnumdk** [comment]
hmm ok :)

**Comment by gnumdk** [comment]
Ok, i revert back my changes, as your suggestion is also true for other shuffle modes...

Will look for a proper solution soon...

**Comment by gnumdk** [comment]
./configure: line 13569: syntax error near unexpected token `1.35.9 '
./configure: line 13569: `GOBJECT_INTROSPECTION_REQUIRE (1.35.9) '

apt-get build-dep lollypop should fix the issue ;)

**Comment by SnouF** [comment]
I have not your ppa in my sources.list ;) so

<pre>
sudo apt-get install debhelper gnome-common gnome-doc-utils gnome-pkg-tools gobject-introspection libgirepository1.0-dev python-gi-dev python3 libglib2.0-dev libgtk-3-dev yelp-tools
</pre>

and autogen.sh work !

For the hazard function by album it's perfect ;)
