### ISSUE TITLE
Default album art is of low quality

### ISSUE THREAD

**Issue by coconutlulz** [gnumdk/lollypop#250]
Lollypop 0.9.42 seems to fetch lower quality album art automatically. If I open the album art selector, four or so images appear immediately (most of which are of poor quality and of which one is the art which Lollypop has automatically assigned to the album) but after a couple of seconds, options of higher quality appear. It's a bit annoying as it means I have to manually do this for every album.

I presume this is due to the order in which Lollypop selects album art providers. I would like the opportunity to look into this issue myself, either by defaulting to the service(s) which provide(s) higher quality album art, or by allowing user configuration.

**Comment by gnumdk** [comment]
Lower quality covers are images presents in your album folder.
