### ISSUE TITLE
HiDPI artwork large and blurry.

### ISSUE THREAD

**Issue by alexskc** [gnumdk/lollypop#252]
Seems to be caused by commit 92da7b1b94758f361bb909bb656ee9818f3078e3

Before:
![before](https://cloud.githubusercontent.com/assets/6933425/9514537/2aa2b4fa-4c9b-11e5-83ab-25c20a85c001.png)

After:
![after](https://cloud.githubusercontent.com/assets/6933425/9514547/3d4c02fa-4c9b-11e5-967e-ca28f9d15c60.png)

**Comment by gnumdk** [comment]
Covers are not large, they are at wanted size (previously buggy in HiDPI)

I revert back commit as i do not understand why cairo do blurry painting.
