### ISSUE TITLE
Foreign characters in album/artist fields can mess up album artwork alignment

### ISSUE THREAD

**Issue by alexskc** [gnumdk/lollypop#253]
As can be seen here with Japanese characters. The album artwork for ベストかまってちゃん is slightly higher than the other album artwork. 

![unaligned](https://cloud.githubusercontent.com/assets/6933425/9514621/f69f0ba8-4c9b-11e5-9976-43fe26522e7e.png)

Fonts in use: Roboto Regular for Western, and M+ 2c for Japanese.

**Comment by gnumdk** [comment]
Send me a file by email.

**Comment by gnumdk** [comment]
How do you get to configure different fonts for this view?

**Comment by alexskc** [comment]
I have my fonts simply set globally, the standard way, ie in /etc/fonts.

**Comment by gnumdk** [comment]
Don't know how to do that

**Comment by alexskc** [comment]
Well, in there, there should be a file titled \*\*-non-latin.conf or something similar. There, you can put preferred fonts higher up, which will get loaded unless some specific characters can't be found, in which case it'll fall back to the next \<family\>Font Name\<\/family\> on the list. It *should* also have comments categorizing by language, eg \<!-- Korean --\>

That's my understanding, at least.

**Comment by gnumdk** [comment]
Yes, but what is your conf?

**Comment by alexskc** [comment]
https://gist.github.com/alexskc/715841b826302a3538b3

**Comment by gnumdk** [comment]
Ok, it works :)
