### ISSUE TITLE
Lollypop wont start

### ISSUE THREAD

**Issue by NEOhidra** [gnumdk/lollypop#255]
Using Fedora 22 and Lollypop 0.9.10_03042015git. Today it just wont start because of:

> File doesn't exist:  
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/application.py", line 119, in do_startup
    Objects.player.restore_state()
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 530, in restore_state
    self.set_albums(track_id, Navigation.ALL, Navigation.ALL)
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 430, in set_albums
    self.context.position = tracks.index(track_id)
ValueError: 760 is not in list

Reinstallation isnt helping.

Didnt know where to ask for help thats why i created this issue.

**Comment by region51** [comment]
*@NEOhidra i use current version 0.9.42 from russianfedora repository and I have no such problem*
```
[maxim@ip195-41 ~]$ su -
Пароль: 
[root@ip195-41 ~]# dnf info lollypop
Last metadata expiration check performed 3:17:53 ago on Fri Aug 28 12:43:53 2015.
Установленные пакеты
Имя         : lollypop
Архитектура : noarch
Эпоха       : 0
Версия      : 0.9.42
Релиз       : 1.fc22.R
Размер      : 1.3 M
Репозиторий : @System
Из репозито : russianfedora-free-updates
Краткое опи : Music player for GNOME
URL         : http://gnumdk.github.io/lollypop/
Лицензия    : GPLv3+
Описание    : Lollypop is a new GNOME music playing application.
```

**Comment by NEOhidra** [comment]
@region51 indeed version 0.9.42 works just fine. Thank you!
