### ISSUE TITLE
Music updater continue to run for quite a long time after exit

### ISSUE THREAD

**Issue by kelvan** [gnumdk/lollypop#263]
Using f8b67cf

When quitting lollypop right after starting it, it continues to indexing my Music for about a minute.
And then it dies with a segfault (no python errors shown [debug mode])
Segfault happens often also without indexing in progress.

**Comment by gnumdk** [comment]
Can't reproduce "indexing my Music for about a minute"

**Comment by gnumdk** [comment]
>When quitting lollypop right after starting it

And when not quitting, does it scan music for about one minute?

**Comment by kelvan** [comment]
Yes, it just don't stop the scan process when quitting, not a problem with a small library, but with a lot of music it produces much I/O after gui disappeared.

**Comment by gnumdk** [comment]
The question is more about: "Why lollypop always hangs on scan"

Because, lollypop stop scan when quitting, seems that gstreamer is failing on some files...

**Comment by gnumdk** [comment]
Can you show me lollypop -d output

**Comment by gnumdk** [comment]
ping?

**Comment by kelvan** [comment]
sorry, wasn't home a while, can't reproduce on my laptop (small library), I'll try to reproduce in the afternoon.

**Comment by kelvan** [comment]
I'm not able to reproduce on desktop with latest git version.
Just segfault at close:
[1]    22933 segmentation fault (core dumped)  lollypop -d

**Comment by gnumdk** [comment]
Ok, i close this one...

Segfault comes from python/glib/gtk...
