### ISSUE TITLE
Player crashes when deleting a playlist

### ISSUE THREAD

**Issue by bakaschwarz** [gnumdk/lollypop#264]
The program closes with a sementation fault when deleting a playlist.
Im using version 0.9.42-1ppa1ubuntu1.

**Comment by sowizz** [comment]
Can confirm. Same package version.

**Comment by gnumdk** [comment]
Any other logs? Not happening here... What Ubuntu version?

**Comment by bakaschwarz** [comment]
Version is Elementary OS 0.3.1 Freya (64-bit) based on Ubuntu 14.04
As for error output, there is just this:

    > lollypop 
    LastFM::_populate_loved_tracks: User not found
    [1]    14485 segmentation fault (core dumped)  lollypop

Is there a way to get more output?
And to be more specific: When i click on the small trashcan, it opens the confirm message like normal, but when i try to confirm it, it does not anything. When i click again, it crashes.

**Comment by gnumdk** [comment]
can you run lollypop with gdb (install libgtk-3-0-dbg and libglib2.0-0-dbg)
and when it segfault, run backtrace in gdb.

Paste output here.

**Comment by sowizz** [comment]
Would you mind providing more detailed instruction or linking to one? 
I run gdb /usr/bin/lollypop and got this message:

"/usr/bin/lollypop": not in executable format: File format not recognized

**Comment by bakaschwarz** [comment]
Same here
