### ISSUE TITLE
Crashes as soon as preferences is clicked - Manjaro 

### ISSUE THREAD

**Issue by NuggetyNanna** [gnumdk/lollypop#266]
Works fine, but every time I try and open preferences it crashes, no error message is given.

This is the output of uname -a:
Linux manjaro 4.2.0-1-MANJARO #1 SMP PREEMPT Fri Sep 4 18:38:20 UTC 2015 x86_64 GNU/Linux

**Comment by gnumdk** [comment]
No error? No segfault?

**Comment by NuggetyNanna** [comment]
Sorry, don't think it was lollypop. Had a few other packages to update and was fixed.
