### ISSUE TITLE
Player repeat album

### ISSUE THREAD

**Issue by eonpatapon** [gnumdk/lollypop#268]
Using master, when I play an album from the random list or popular list the album gets repeated. Usually it was playing the next in the list when it was finished.

**Comment by gnumdk** [comment]
Here it works. 

Clicking on album cover only play album, it's wanted.

**Comment by eonpatapon** [comment]
Yep but when the album is finished what does it do ?

Before it was playing the next album in the list

**Comment by gnumdk** [comment]
No, before it was showing the cover downloader.

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/commit/c47391db15644a12b1c1a4ea5dc29466ad6f56f1

**Comment by gnumdk** [comment]
And so the album repeat ;)

**Comment by eonpatapon** [comment]
Actually not talking about that. Click to play is fine as well as the cover downloader. I'm just saying that sometimes once the album I've clicked on (I have enable the click to play setting) has finished playing the player does not play the next album in the list but repeat the same album.

**Comment by eonpatapon** [comment]
Hum I didn't understand the commit.

**Comment by gnumdk** [comment]
The click to play setting always starts album in repeat. Not sure if it's good :-/

Do you think it's bad?

**Comment by eonpatapon** [comment]
I'm pretty sure it didn't before that's why I have opened this issue :)

Personally I don't like it to repeat the album. I would prefer if it plays the next in the list

**Comment by gnumdk** [comment]
I don't use this option, so ...
