### ISSUE TITLE
Support sync with Android

### ISSUE THREAD

**Issue by gigitux** [gnumdk/lollypop#270]
I would like sync my music between Android smartphone and PC with Lollypop.

Thanks for your great work !

**Comment by gnumdk** [comment]
Lollypop already support android sync

**Comment by gnumdk** [comment]
gvfs-mtp and nautilus are needed

**Comment by gigitux** [comment]
I mean a copy of all library music on smartphon with lollypop.
Not only playlist

**Comment by gigitux** [comment]
Great :-D

**Comment by pciavald** [comment]
I've installed the `gvfs-mtp` package but my smartphone (in MTP mode) still doesn't show up when I plug it, is there something else to do ?

**Comment by gnumdk** [comment]
Yes, use GNOME :p If phone is not mounted by KDE...
