### ISSUE TITLE
Request: add album to queue on search

### ISSUE THREAD

**Issue by underr** [gnumdk/lollypop#272]
When searching for an album, you can only add it to a playlist or play it immediately. An option to add it to the playing queue would be very useful.

**Comment by gnumdk** [comment]
No, the second button is for queue ;)

**Comment by underr** [comment]
Oh, thanks. Sorry for the dumb issue.

**Comment by p3732** [comment]
Maybe switching the two icons would give a more consistent behaviour. Or maybe using the icon under Playlist -> Never Played for the "add to playlist" action.

**Comment by gnumdk** [comment]
@p3732 Done
