### ISSUE TITLE
"Play albums on click" setting ignored

### ISSUE THREAD

**Issue by kelvan** [gnumdk/lollypop#273]
Using 6eed391eee

##### Steps to reproduce

* "Play album on click" is disabled
* Click on "All artists" -> some artist (not compilation)
* Click some album cover

##### Suspected behaviour

* Album shown on bottom of window
* possible to change cover there

##### Actual behaviour

* Plays album
* Not sure how to change cover

**Comment by gnumdk** [comment]
It's wanted, play on click is for album view now.
