### ISSUE TITLE
Shuffle all songs

### ISSUE THREAD

**Issue by prescott66** [gnumdk/lollypop#279]
I really miss quick/easy way to shuffle all songs in my music database.
In Clementine player is quick playlist named Intelligent playlist, so it plays randomly songs, but that is not needed.
Just to create "Shuffle songs" in left panel, like is there "Shuffle albums".

Cherry pick will be ability to select genre :smile: 

EDIT: maybe this can be do, but it is too much chaotic for me :disappointed:

**Comment by gnumdk** [comment]
Just put lollypop in shuffle by tracks and play:
- From All artists for shuffle all
- From genre for shuffle by genre

**Comment by prescott66** [comment]
Sorry. I must spend more time with Lollypop :smile:
