### ISSUE TITLE
Media player indicator (gnome extension) display rating

### ISSUE THREAD

**Issue by SnouF** [gnumdk/lollypop#28]
I use https://extensions.gnome.org/extension/55/media-player-indicator/

This extension displays rating (with 5 stars) but lollipop not support rating.

It's a bug of media player indicator or lollypop ?

**Comment by gnumdk** [comment]
From media-player-indicator:
Warning: Ratings are not part of the MPRIS specification thus specific code must be written for each player to set or get the current track rating.

**Comment by Rom1Linux** [comment]
Hello, thanks for the good work on this soft.
I just ask about somes good fonctions if is possible to include in the next released:
- continue the last song after close and open
- What commande line i write to do play/pause in my terminal ? like Banshee -- play
that to add a commande line shortcut keyboard to Xfce.
Thanks in advance for that.
