### ISSUE TITLE
Incorrect grouping of "compilations" albums

### ISSUE THREAD

**Issue by monreal** [gnumdk/lollypop#283]
I have multiple "Greatest Hits" albums for example. They do not show up in the album browser but I can find the songs using search. If I play any of the songs and press the song name I get this:

![greatesthits](https://cloud.githubusercontent.com/assets/54005/10140267/f5244dc2-6606-11e5-80f8-0275ea5fb830.jpg)

I also noticed these albums are grouped as one "Greatest Hits" compilation under "Compilations". There is also a compilation of the two albums named "Awake" (of Dream Theater and Godsmack) which are also missing from the album view as well as the artists browser.

I assume this is a bug but if the behavior is intended please provide an option to turn it off.

**Comment by gnumdk** [comment]
It's not a bug, it's by design. ( like clementine and amarok).

It's a compilation so it goes in compilations.

Option already exists...

**Comment by gnumdk** [comment]
Will give a look if its easy to make this option working for artist view too

**Comment by gnumdk** [comment]
Adding an option to add this in artist view would break all lollypop optimizations.

You can set album artist tag if you want a track to belong to an artist.

**Comment by monreal** [comment]
I really do not understand this "feature". The albums "Awake" by Dream Theater and "Awake" by Godsmack do not have anything in common besides the name so why treat them as a compilation? 

Same for all those "Greatest Hits" albums, really.

**Comment by gnumdk** [comment]
It's a compilation because your tracks are badly tagged. They are missing the album artist tag...

**Comment by gnumdk** [comment]
I will need to add some informations in lollypop help.

Here for exemple, i've an album with album artist as "Ludwig von 88" and different artist tags, here the feature:
![capture du 2015-09-28 18-49-06](https://cloud.githubusercontent.com/assets/3918824/10142232/adb34942-6611-11e5-85ea-bb8985f80055.png)

**Comment by monreal** [comment]
Personally I do not see the need for albumartist if albumartist equals artist. But as adding the tag is easy enough I just did it.

However I do not think many users will have "perfect" tags (perfect in your definition) and for those lollypop is probably the only player which breaks in a very unexpected way.

**Comment by gnumdk** [comment]
Lollypop act like clementine and amarok.

**Comment by gnumdk** [comment]
From amarok documentation: Tracks without an album artist are placed in a compilation.
