### ISSUE TITLE
where Russian translation ???

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#285]
v 0.9.50 where Russian translation ???

**Comment by gnumdk** [comment]
Here it's po/ru.po

**Comment by region51** [comment]
@gnumdk lollypop-0.9.50.tar.xz no po/ru.po

**Comment by region51** [comment]
@gnumdk lollypop-0.9.50.tar.xz
```
[maxim@ip194-22 locale]$ ls
ca  cs  de  en_IE  es  fi  fr  ga  he  hu  it  nl  pl  pt_BR  sk  sr  sr@latin  sv  tr  tr_TR  uk
[maxim@ip194-22 help]$ ls
C  ca  cs  de  es  fi  fr  he  it  nl  pl  pt_BR  ru  sk  sr  sv  uk
```

**Comment by kostich** [comment]
It seems that the [translation is there](https://github.com/gnumdk/lollypop/blob/master/po/ru.po) but that the [LINGUAS file](https://github.com/gnumdk/lollypop/blob/master/po/LINGUAS) is missing the information that the Russian translation is available.

I've forked the repo, defined Russian as translated, compiled and tested it. It uses Russian translation now. I've created a [pull request](https://github.com/gnumdk/lollypop/pull/290).
