### ISSUE TITLE
Add context menu item for opening folder

### ISSUE THREAD

**Issue by MadcapJake** [gnumdk/lollypop#287]
Personally, I wish that lollypop had an id3 tag editor, but I understand why it's not included.  However, without a tag editor, it would be a nice to at least have a context menu option allowing me to open a selected album's folder so that I can quickly launch a dedicated tag editor from that folder.  In large libraries using a tag editor over the whole library is incredibly slow (especially on an HDD) and opening nautilus and navigating to an album is also quite a hassle. So having the ability to just quickly dive into a folder would be very convenient!

**Comment by gnumdk** [comment]
It's already available!

**Comment by MadcapJake** [comment]
Haha, sweet! Sorry for the issue!  FYI, the text reads `Modify informations` but it works perfectly with puddletag!

**Comment by gnumdk** [comment]
You need to tell puddletag to update modification time, lollypop is using this information ;)

**Comment by kehugter** [comment]
> It's already available!

Could you specify where? I don't seem to find it in any menu.

**Comment by gnumdk** [comment]
In album menu, you need a tag editor installed...

**Comment by kehugter** [comment]
No chances of adding it without a tag editor?

**Comment by gnumdk** [comment]
Just put nautilus in dconf key: Tag-editor
