### ISSUE TITLE
Use 'album artist' tag instead of 'performer'

### ISSUE THREAD

**Issue by mikelpr** [gnumdk/lollypop#29]
otherwise this happens with properly tagged files from musicbrainz
![screenshot from 2015-01-12 12 30 44](https://cloud.githubusercontent.com/assets/4985438/5708771/8edd38ae-9a59-11e4-9f27-c01e27478a21.png)
makes a huge mess in the sidebar

even if I hadn't tagged them with musicbrainz, this would still happen as I have many DJ sets where the artist tag is used for the true artist and the album artist tag is used for the mixer

my suggestion for files which don't have an album artist tag should fallback to artist then, as the performer tag is used for detailed information (well, at least on musicbrainz. still the artist tag is better supported most of the time)

**Comment by gnumdk** [comment]
TPE2: «The 'Original artist(s)/performer(s)' frame is intended for the performer(s) of the original recording, if for example the music in the file should be a cover of a previously released song.»

**Comment by gnumdk** [comment]
And i've got many files tagged with musicbrainz and performer contain only original artist name...

**Comment by mikelpr** [comment]
chill, it was just a suggestion. I have like 99% of my library tagged with musicbrainz via kid3 and as you can see in the screenshot it's very cluttered so either kid3 is doing something wrong or musicbrainz is using the field incorrectly idk
perhaps make it changeable?

**Comment by mikelpr** [comment]
also Original Artist seems to be another field
![screenshot from 2015-01-14 17 57 13](https://cloud.githubusercontent.com/assets/4985438/5750216/395ba5fe-9c17-11e4-945c-0b6445f030bb.png)
![screenshot from 2015-01-14 17 59 50](https://cloud.githubusercontent.com/assets/4985438/5750213/344ecf64-9c17-11e4-8cfd-56a2fafade5e.png)

**Comment by gnumdk** [comment]
OK, performer may be different in flac, will give a look... But in my mp3: performer == artist album

And my previous response is id3tag documentation.

**Comment by gnumdk** [comment]
Can you send one file from this album with Google Drive or another one cloud service?

**Comment by gnumdk** [comment]
Ok, got it, mutagen doesn't use same key with mp3 and ogg/flac :-(

Will give a look.

**Comment by gnumdk** [comment]
Can you test with last git?

**Comment by gnumdk** [comment]
To force db update:
sqlite3 -cmd "update tracks set mtime=0" ~/.local/share/lollypop/lollypop.db

**Comment by mikelpr** [comment]
sorry I hadn't been getting notifications on this and I just checked my gmail's updates tab lol I'm going to try and let you know

**Comment by gnumdk** [comment]
ping?

**Comment by mikelpr** [comment]
pong, it looks good now :-) unfortunately I'm getting core dumps after the program loads. I only managed to see my collection for two seconds lol

**Comment by gnumdk** [comment]
Close this bug, open a new one for coredumps
