### ISSUE TITLE
Bug - Can't open window again after hiding it.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [gnumdk/lollypop#291]
Hello

I've been quiet for a while (that's good!), but with the new version I've found that I can no longer open Lollypop when I've closed it and it's running in the background. I can still use MPRIS2 to manage the currently playing track, but there is no way to get the window back. Running Lollypop in the command line just exits again.

I'm currently running 0.9.50.

Thanks in advance

**Comment by titovroman** [comment]
I can verify it. Running the same version of Lollypop on Archlinux.

**Comment by gnumdk** [comment]
Fix in stable branch
