### ISSUE TITLE
TypeError: argument rect: Expected Gdk.Rectangle, but got gi.repository.cairo.RectangleInt

### ISSUE THREAD

**Issue by SnouF** [gnumdk/lollypop#292]
When I scroll on navigation bar (on left) lollypop crash

<pre>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/selectionlist.py", line 420, in _on_scroll
    self._popover.set_pointing_to(r)
TypeError: argument rect: Expected Gdk.Rectangle, but got gi.repository.cairo.RectangleInt
</pre>

OS : debian unstable
Version : 0.9.51-1ppa1ubuntu1

**Comment by gnumdk** [comment]
Broken gnome installation, debian bug due to not updated python gobject
