### ISSUE TITLE
Radio thumbnails appear and disappear randomly

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#295]
Lollypop 0.9.50.

Radio thumbnails are quite funky this release. The appear and dissappear randomly, from the favored radio stations. In my radio view, all of the stations currently have a blank, white thumbnail.

I did have Lollypop compiled from master (removed Lollypop via dnf, compiled from master, sudo installed it, after doing my work I sudo uninstall'd it and reinstalled Lollypop via dnf), so that *may* have something with this problem.

Anyone else experiencing this?

**Comment by gnumdk** [comment]
What is your.local/share/lollypop/playlists content?

**Comment by gnumdk** [comment]
Radios, not playlists

**Comment by kostich** [comment]
The content are:
```
[marko@skynet ~] $ ls .local/share/lollypop/radios/
ABC Classic (France).m3u  Радио Београд 202 104.0 (Community).m3u
ABC Classic (France).png  Радио Београд 202 104.0 (Community).png
Омиљене песме.m3u
```

Радио Београд 202 means Radio Belgrade 202 and Омиљене песме.m3u means Favorite songs.m3u.

It seems that the thumnails are there (.png) but they aren't used 98% of the time. Should I nuke ~/.config/lollypop, ~/.cache/lollypop and ~/.local/share/lollypop and then observer if this happens again?

**Comment by gnumdk** [comment]
You can nuke  ~/.cache/lollypop

**Comment by kostich** [comment]
Thumbnails now appear properly. Thanks.

**Comment by gnumdk** [comment]
Updating collection clear cache by default ;)

**Comment by kostich** [comment]
Really? That's quite useful. Does Lollypop update music collection after the update?
