### ISSUE TITLE
Why two Loved tracks?

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#296]
![2015-10-04 23-08-05](https://cloud.githubusercontent.com/assets/13280183/10269987/6c4ac2f6-6aed-11e5-9bb4-bb2ef85532a0.png)
![2015-10-04 23-08-01](https://cloud.githubusercontent.com/assets/13280183/10269989/7939a68a-6aed-11e5-86d0-83b07385cf34.png)
*Loved tracks=Любимые композиции*
*Любимые композиции=Loved tracks*

**Comment by gnumdk** [comment]
Because you run lollypop with an english locale? Remove it safely ;)

Will not happen again with next release (playlists in sqlite db)

**Comment by region51** [comment]
@gnumdk Thx, i reinstalled lollypop
![2015-10-05 12-03-11](https://cloud.githubusercontent.com/assets/13280183/10276635/57d4bd7e-6b59-11e5-875e-a7038222d518.png)
