### ISSUE TITLE
Shuffle tracks from artist don't work

### ISSUE THREAD

**Issue by gigitux** [gnumdk/lollypop#298]
"Shuffle tracks from artist" doesn't work anymore on lollypop 0.9.52

**Comment by region51** [comment]
*@gigitux Fedora 22, lollypop-0.9.52 everything is working*

**Comment by gigitux** [comment]
@region51 On arch, i have this problem :/

**Comment by gnumdk** [comment]
ArchLinux: here it works. Can you record a video session to help me guess what is hapenning?

**Comment by gigitux** [comment]
Here the video
https://www.dropbox.com/s/8uoh0fqi110jz0v/lollypop%20bug.webm?dl=0

**Comment by gnumdk** [comment]
OK, seems to be broken in popular view.

**Comment by gnumdk** [comment]
In fact, it never worked in popular view :)

Fixed.

**Comment by gigitux** [comment]
Awesome ! :D

Thanks

**Comment by gnumdk** [comment]
Merged in stable, will release soon.
