### ISSUE TITLE
String in Wikipedia tab, in author view not appearing for translating in Transifex

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#299]
Lollypop 0.9.52.

When you click on the thumbnail of the album (right from the forward button) and when you select Wikipedia tab, if there is no article about the author on the Wikipedia, a string "No information for this artist..." will appear. This string does not appear to be translatable on Transifex (at least, it's not appearing for translation when I want to translate to Serbian).

![untranslated-string](https://cloud.githubusercontent.com/assets/4953862/10290811/884a09d0-6ba6-11e5-8e85-399f9c29506d.png)

The string *does* exist in the pot file.

**Comment by gnumdk** [comment]
Can you test with last git?

**Comment by kostich** [comment]
Translated string is used in latest master (0.9.60).

**Comment by kostich** [comment]
Fixed in 0.9.60.
