### ISSUE TITLE
No choice default application / No play if default is set

### ISSUE THREAD

**Issue by MCommander** [gnumdk/lollypop#30]
Hi,

use lollypop 0.8.5 with arch linux. For me it's not possible to choose lollypop as default application in gnome 3.14.2. After editing lollypop.desktop it shown up but any .mp3 did not start.

Best Regards

MCommander

**Comment by gnumdk** [comment]
Lollypop only play music from it database as Gnome Music and isn't designed to play externals mp3...

**Comment by gnumdk** [comment]
In fact, it's now fixed ;)
