### ISSUE TITLE
Question - Opening audio URL's.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [gnumdk/lollypop#300]
Hello

I sometimes use `mpsyt` to send YouTube audio URL's to Lollypop. This used to work before Lollypop 0.9.50, but now it seems to be broken (Lollypop just crashes). I don't know if this was something that was officially supported or just happened to work, which is why I added the 'Question' label.

Thanks in advance

**Comment by gnumdk** [comment]
Just happened to work but what is crash output?

**Comment by hotoiledgoblinsack** [comment]
I see you already managed to fix it, thanks. For the record, there was no crash output (just the standard output from starting Lollypop, which then closed).
