### ISSUE TITLE
Wikia can't search for lyrics in albums with various artists

### ISSUE THREAD

**Issue by cristobaltapia** [gnumdk/lollypop#301]
When playing a song from a compilation, and trying to get the lyrics with the Wikia plugin, Lollypop passes the name of the artist as "Various Artists". Of course Wikia can't find that song under that interpreter. So, for compilations, Lollypop should pass the name of the interpreter of the song instead of the interpreter of the album. I hope the description is understandable :P

**Comment by gnumdk** [comment]
Lollypop doesn't handle compilations like this, you need to remove this "Variout artists" album tag and you will have a real compilation.

See this:

![capture du 2015-09-28 18-49-06](https://cloud.githubusercontent.com/assets/3918824/10321559/ae6454b2-6c79-11e5-870a-ac632d6b62a7.png)

Here, album artist is "Ludwig Von 88" and searching for lyrics without this album artist will fail.

Please update your tags, lollypop works like Clementine and Amarok to handle compilations.

**Comment by cristobaltapia** [comment]
Ok, thanks. Now it works, but I think I found something strange:
When clicking on the album cover on the panel bar, the songs of the album should appear in the popover (that's the name right?), but I see nothing.
![bildschirmfoto von 2015-10-06 22-56-13](https://cloud.githubusercontent.com/assets/7276493/10322358/9da01e82-6c7d-11e5-975e-59b941597c91.png)

**Comment by gnumdk** [comment]
Can confirm the bug ;)

**Comment by gnumdk** [comment]
the last one ;)
