### ISSUE TITLE
can't sync playlist on android if lollypop folder on device is empty

### ISSUE THREAD

**Issue by evilegidiux** [gnumdk/lollypop#304]
As a connect my android device (lgg2), it appears in lollypop  and an empty "lollypop" folder is created on the device. The problem is that if i don't put something in this folder, in the sync list on the app no playlist  is showed. If i put something on the lollypop folder on the device (even an empty, random folder), than everything works as it should. Is this wanted or is a bug?  Gnome 3.18 on Archilinux

**Comment by gnumdk** [comment]
Lollypop 0.9.52?

**Comment by gnumdk** [comment]
If you can confirm, i will give a look at 0.9.52 to release a bugfix release.

**Comment by evilegidiux** [comment]
Yes, version is 0.9.52. I Also built it from current git, but same problem

**Comment by gnumdk** [comment]
ok, going to look

**Comment by gnumdk** [comment]
Will release 0.9.60 soon.
