### ISSUE TITLE
updating music error

### ISSUE THREAD

**Issue by ahloiscreamo** [gnumdk/lollypop#305]
after i click "update your music", it scans my music until finished but crash after that.
This would only happen if i try to update my music directory.

**Comment by gnumdk** [comment]
paste lollypop -d output

**Comment by lesthack** [comment]
Hi,

I've the same problem.
...
/mnt/backups/Music/Helios/Helios - Ayres/folder.jpg not detected as a music file
/mnt/backups/Music/Helios/Helios - Unomia/Helios - Unomia.jpg not detected as a music file
/mnt/backups/Music/Helios/Helios - Caesura/cover.jpg not detected as a music file
/mnt/backups/Music/Binarpilot - You Can't Stop Da Funk -- Jamendo - MP3 VBR 192k - 2006.03.19 [www.jamendo.com]/License.txt not detected as a music file
/mnt/backups/Music/Binarpilot - You Can't Stop Da Funk -- Jamendo - MP3 VBR 192k - 2006.03.19 [www.jamendo.com]/[cover] Binarpilot - You Can't Stop Da Funk.jpg not detected as a music file
/mnt/backups/Music/Binarpilot - You Can't Stop Da Funk -- Jamendo - MP3 VBR 192k - 2006.03.19 [www.jamendo.com]/Readme - www.jamendo.com .txt not detected as a music file
[1]    13740 segmentation fault (core dumped)  lollypop -d

And crash the App.

**Comment by gnumdk** [comment]
I just change debug message. Can you run lollypop -d from git?

It should show us what file make gstreamer segfault.

**Comment by lesthack** [comment]
Thank you.

Yes, the file is this: https://drive.google.com/open?id=0B8jEFrUIOdy2NTNZZUphLV9rSXc

May serve.

**Comment by gnumdk** [comment]
Here, it works without segfault...

**Comment by gnumdk** [comment]
I close this bug:
- This is not a lollypop bug as lollypop can't segfault (python)
- This seems to be a bug due to your distribution/gstreamer version
