### ISSUE TITLE
Albums with equal artist and title but different years are considered the same album

### ISSUE THREAD

**Issue by jnj** [gnumdk/lollypop#307]
Here is an example:
Killing Joke released a self-titled album in 1980. They released another self-titled album in 2003. The two albums are completely different with distinct sets of songs, but Lollypop will show only one entry for the album "Killing Joke" with the union of both albums' songs under it. One idea is to take year into account when determining album uniqueness.

**Comment by gnumdk** [comment]
It's a known bug i was too lazy to fix (as i have no albums like this).

It's time for fix :)

**Comment by gnumdk** [comment]
No I need to fix my tags, I hate you :p
