### ISSUE TITLE
TypeError: unorderable types: NoneType() > int()

### ISSUE THREAD

**Issue by BPaden** [gnumdk/lollypop#308]
This is a crash that invariably happens with both the latest release, and git. If I try to play a radio, it will play just long enough for my ears to register a sound, and then it will crash.

Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: Traceback (most recent call last):
Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 219, in _on_current_changed
Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: self._update_metadata()
Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 183, in _update_metadata
Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: Lp.player.current_track.get_popularity() / 5
Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: File "/usr/lib/python3.5/site-packages/lollypop/objects.py", line 78, in get_popularity
Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: avg_popularity = self.db.get_avg_popularity()
Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: File "/usr/lib/python3.5/site-packages/lollypop/database_tracks.py", line 435, in get_avg_popularity
Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: if v and v[0] > 5:
Oct 11 19:25:25 arch-tower0 lollypop.desktop[15448]: TypeError: unorderable types: NoneType() > int()

**Comment by gnumdk** [comment]
Is it possible you do not have any track in your collection? :)

**Comment by BPaden** [comment]
Yeah, I just let people on the Internet tell me what to listen to. 😅
