### ISSUE TITLE
Huge album artwork on HiDPI

### ISSUE THREAD

**Issue by alexskc** [gnumdk/lollypop#309]
![huge](https://cloud.githubusercontent.com/assets/6933425/10433908/280e59ca-7116-11e5-9d9a-6641f57e29b9.png)

Caused by commit ab7ba5f092ce2c768c2aa982d238be5de91c4ff5

**Comment by gnumdk** [comment]
Ok, I revert this commit ;) I do not have the same behaviour on a none HiDPI screen when testing ;)

**Comment by gnumdk** [comment]
Can you test current git... I'm sure you will get blurry covers again... And this make me sad :(

**Comment by gnumdk** [comment]
Don't mind, I revert this code too... Seem's to be impossible to deal with HiDPI without cairo.Surface :(
