### ISSUE TITLE
Feature request send music android

### ISSUE THREAD

**Issue by gnurichard** [gnumdk/lollypop#31]
Would be great to endure the lollypop to send music from the menu , directly to an android terminal , as do Rhytmbox and banshee

**Comment by gnumdk** [comment]
Send file or sound?

**Comment by gnurichard** [comment]
I was thinking about the file, it would be great to use lollypop to export my files to my phone android

**Comment by gnumdk** [comment]
What are the benefits of using lollypop instead of nautilus?

**Comment by gnurichard** [comment]
Well, in my case, I have a huge collection of music, with full metadata (the file name does not always match the name of the song, but the media player gives me the correct name, it made complicated find a song from the file manager) and my experience is much more comfortable be managing the songs on the music player, because I can be looking for my music from a faster and more efficiently mode , and even i can have a play list previously made to import quickly the music to my android terminal(the creation of  playlists also be a very desirable function in my opinion)
previously I have come to use other media players like Amarok, Banshee Rhytmbox  to do it. but I really love lollypop and I would love to use it to manage my music and to be able to export my android terminal

**Comment by gnumdk** [comment]
Will no be part of lollypop 0.9 because of:
https://bugzilla.gnome.org/show_bug.cgi?id=744690

Will implement this later...

**Comment by gnumdk** [comment]
mtp sync is available in git ;)
