### ISSUE TITLE
Fedora DNF-installed pylast not detected.

### ISSUE THREAD

**Issue by stkAnon** [gnumdk/lollypop#312]
After installing "pylast" from the Fedora repositories, running Lollypop from terminal still returns:

```
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
```

and the last.fm tab in preferences is still greyed out.

**Comment by gnumdk** [comment]
You should install pylast for python3. And please post this kind of stuff to Fedora forums, it's a bug report tool ;)
