### ISSUE TITLE
Clicking and dragging window title bar while maximized "breaks" it (Cinnamon Desktop)

### ISSUE THREAD

**Issue by stkAnon** [gnumdk/lollypop#313]
If the Lollypop window is unmaximized by clicking and dragging its title bar, it ends up in a sort of semi-maximized state where it can be moved around but can't be easily resized.

This seems to be caused by the `_GTK_FRAME_EXTENTS(CARDINAL)`, `_NET_WM_OPAQUE_REGION(CARDINAL)`, and maybe `WM_NORMAL_HINTS(WM_SIZE_HINTS)` X server properties not being reset when a window is unmaximized in this way.

Running xprop on a properly unmaximized window returns the following (trimmed to the relevant values):
```
_NET_WM_OPAQUE_REGION(CARDINAL) = 33, 23, 1374, 7, 26, 30, 1388, 731
_GTK_FRAME_EXTENTS(CARDINAL) = 26, 26, 23, 29
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 1085 by 159
		program specified base size: 0 by 0
		window gravity: NorthWest
```

Meanwhile, a "broken" window returns:
```
_NET_WM_OPAQUE_REGION(CARDINAL) = 7, 0, 1426, 7, 0, 7, 1440, 783
_GTK_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 1033 by 107
		program specified base size: 0 by 0
		window gravity: NorthWest
```

...which is a lot more similar to a fully maximized window:
```
_NET_WM_OPAQUE_REGION(CARDINAL) = 7, 0, 1906, 7, 0, 7, 1920, 1047
_GTK_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 1153 by 107
		program specified base size: 0 by 0
		window gravity: NorthWest
```

BTW, thanks to the developers for making this program. It seems like a great light-weight and easy to use app for listening to music libraries. I just started using it today and can't wait for it to become even more polished and stable ^^

**Comment by gnumdk** [comment]
What is your WM? Lollypop doesn't handle this, it's GTK stuff

**Comment by gnumdk** [comment]
Ok, Cinnamon... I have to close this as lollypop doesn't do anything with this stuff, it just create a GtkApplicationWindow.

So, it can be:
- A GTK bug
- A Cinnamon bug
