### ISSUE TITLE
Crash on first start

### ISSUE THREAD

**Issue by florian0** [gnumdk/lollypop#315]
When i run lollypop the first time, it fails with the following error:
```
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 50, in <module>
    app = Application()
  File "/usr/lib64/python3.4/site-packages/lollypop/application.py", line 108, in __init__
    Lp.playlists = Playlists()
  File "/usr/lib64/python3.4/site-packages/lollypop/playlists.py", line 70, in __init__
    None)
GLib.Error: g-io-error-quark: No such file or directory (1)
```
This seems to be related to the `.local/share/lollypop/playlists.db` missing on first start.

Tested on version 0.9.52
Gnome 3.16; Python 3.4.3;

**Comment by gnumdk** [comment]
0.9.52 doesn't use playlists.db... Impossible.

**Comment by gnumdk** [comment]
Ok, this is current git as playlists objects doesn't exist in 0.9.52.

**Comment by florian0** [comment]
> 0.9.52 doesn't use playlists.db... Impossible.

I got confused by the comment:
> # We import playlists from lollypop < 0.9.60
and double checked that i downloaded the latest release and not the master.

See https://github.com/gnumdk/lollypop/blob/0.9.52/src/playlists.py
