### ISSUE TITLE
Play stalls to buffer

### ISSUE THREAD

**Issue by SudoMakeCake** [gnumdk/lollypop#317]
Hi

Using Lollypop 0.9.52, playing music from USB drive on another laptop over wifi. On both on Debian Jessie with Openbox, with all the latest updates.

0.9.49 (and below) : When I finally* managed to get it to play a song, the play back was continuously without any breaks. */ It was very hard to just to press play and hear some music, this have been fixed in 0.9.52. 

0.9.52 : When pressed play, the music starts but pauses for 1-2sec, every 15-20sec, to buffer the track. I think more pauses and shorter between them, when the track is at a high bit rate, I have not yet checked out that theory.

VLC and GMusicBrowser just plays the music from the same location without pauses.

Streaming radio, say from Somafm.com, there is no buffering. 

Let me know if you need a log file and how to get a log file.

Many thanks for a great music play.

**Comment by gnumdk** [comment]
This looks more like a gstreamer issue...

**Comment by SudoMakeCake** [comment]
And that means? Doesn't GMusicBrowser use that too? Do you have an idea how to fix it?

**Comment by gnumdk** [comment]
gst-play-1.0 your file...

Does it works?

**Comment by SudoMakeCake** [comment]
Can you explain more?

**Comment by SudoMakeCake** [comment]
Can you explain more?

**Comment by SudoMakeCake** [comment]
Oops, first time on Github, how do I unclose this?

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/commit/35e6cba781be5b3f061e82e9e5f4fa3d42469c54

Can you test with last git?

**Comment by gnumdk** [comment]
Going to sleep, see you tomorrow ;)

**Comment by SudoMakeCake** [comment]
Never got a pull from Github to work, so installed with apt-get.

**Comment by gnumdk** [comment]
$ sudo apt-get build-dep lollypop
$ git clone https://github.com/gnumdk/lollypop.git
$ cd lollypop
$ ./autogen.sh
$ make
$ sudo make install

**Comment by SudoMakeCake** [comment]
Ah never seen or known about the "sudo apt-get build-dep lollypop" before. That made the make happen.

Lollypop has now been playing now for about 10-15min minutes solid without any pauses to buffer. 

Many thanks.

**Comment by SudoMakeCake** [comment]
HA! Just as I posted this, there were three pauses on the trod :) Lets see how it behaves over the next hours/days.
