### ISSUE TITLE
Lollypop crashes after updating music

### ISSUE THREAD

**Issue by mcmirande** [gnumdk/lollypop#319]
Hello, I'm new here and don't know if this is the appropriate place for this.

I like lollypop very much and have no doubts that it will be my "official" music player (I'm using mpd now), but I have a problem just after updating music library. It just crashes. When I execute it from the terminal, I receive the following message "GLib.Error: gst-core-error-quark: A la instalación de GStreamer le falta un complemento. (12)" (GStreamer installation is missing some complement).
The same problem appeared in the two computers I have (one with Ubuntu and the other one with Manjaro).

I hope you can fix it (or indicate to me how overcome this crash) because I really like your program.

Thanks a lot for your help.
Marcos.

**Comment by gnumdk** [comment]
Can you post here the full log:
$ lollypop -d

**Comment by mcmirande** [comment]
Hello!
The log is huge because there are a lot of covers as .jpg files that can't be read as music (logically).
I paste a sample of them and the end of the log:

Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Bill Evans - 2003 Getting Sentimental/._13 But Beautiful.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Bill Evans - 2003 Getting Sentimental/._14 I love you.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Don Cherry - 1973 Relativity Suite /__MACOSX/._01 Tantra.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Don Cherry - 1973 Relativity Suite /__MACOSX/._02 Mali Doussn'Gouni.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Don Cherry - 1973 Relativity Suite /__MACOSX/._03 Desireless.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Don Cherry - 1973 Relativity Suite /__MACOSX/._04 The Queen Of Tung Ting Lake.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Don Cherry - 1973 Relativity Suite /__MACOSX/._05 Trans-Love Airways.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Don Cherry - 1973 Relativity Suite /__MACOSX/._06 Infinite Gentleness.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Don Cherry - 1973 Relativity Suite /__MACOSX/._07 March Of The Hobbits.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ebenezer Obey - 1973 And His Miliki Sound/EbenezerObeyMiliki_Side1.mp3, gst-stream-error-quark: El flujo no contiene datos. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ebenezer Obey - 1980' A Christmas Special By The King of Juju/NiyiAdeodokun_EsanKo.mp3, gst-core-error-quark: A la instalación de GStreamer le falta un complemento. (12)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._01 Sound Museum.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._02 Monsieur Allard.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._03 City Living.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._04 What Reason.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._05 Home Grown.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._06 Stopwatch.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._07 Women Of The Veil.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._08 P.P. (Picolo Pesos).mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._09 Biosphere.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._10 Yesterday, Today, & Tomorrow.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._11 European Echoes.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._12 What A Friend We Have In Jesus [Variation].mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._13 Mob Job.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Ornette Coleman - 1996 Sound Museum - Hidden Man/__MACOSX/._14 Macho Woman.mp3, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Stevie Ray Vaughan - 1989 In Step/00. Stevie Ray Vaughan And Double - In Step.pls, gst-stream-error-quark: This appears to be a text file (5)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Tomasz Stańko - 1975 Balladyna/__MACOSX/._01 First Song.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Tomasz Stańko - 1975 Balladyna/__MACOSX/._02 Tale.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Tomasz Stańko - 1975 Balladyna/__MACOSX/._03 Num.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Tomasz Stańko - 1975 Balladyna/__MACOSX/._04 Duet.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Tomasz Stańko - 1975 Balladyna/__MACOSX/._05 Balladyna.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Tomasz Stańko - 1975 Balladyna/__MACOSX/._06 Last Song.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error scanning: /media/marcos/TOSHIBA EXT1/Musica/Tomasz Stańko - 1975 Balladyna/__MACOSX/._07 Nenaliina.m4a, gst-stream-error-quark: No se pudo determinar el tipo de flujo. (4)
Error playing: file:///media/marcos/TOSHIBA%20EXT1/Musica/Ebenezer%20Obey%20-%201980'%20A%20Christmas%20Special%20By%20The%20King%20of%20Juju/NiyiAdeodokun_EsanKo.mp3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/toolbar.py", line 94, in _on_current_changed
    self._toolbar_infos.on_current_changed(player)
  File "/usr/lib/python3/dist-packages/lollypop/toolbar_infos.py", line 78, in on_current_changed
    False)
  File "/usr/lib/python3/dist-packages/lollypop/art_album.py", line 125, in get_cover_for_uri
    pixbuf = self.pixbuf_from_tags(GLib.filename_from_uri(uri)[0], size)
  File "/usr/lib/python3/dist-packages/lollypop/art_album.py", line 257, in pixbuf_from_tags
    infos = self.get_infos(filepath)
  File "/usr/lib/python3/dist-packages/lollypop/tagreader.py", line 50, in get_infos
    infos = self._tagreader.discover_uri(uri)
GLib.Error: gst-core-error-quark: A la instalación de GStreamer le falta un complemento. (12)

**Comment by gnumdk** [comment]
Ok, don't know what is happening, you are missing gstreamer tag reader plugin... What distro are you using?

**Comment by mcmirande** [comment]
The same happens with Manjaro and Ubuntu.

I'm using Quod Libet associated to Lollypop in order to tag songs. I
installed all the gstreamer files, but it doesn't change
 things...

Thanks for your help. Marcos.

2015-10-16 11:39 GMT-03:00 Cédric Bellegarde <notifications@github.com>:

> Ok, don't know what is happening, you are missing gstreamer tag reader
> plugin... What distro are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gnumdk/lollypop/issues/319#issuecomment-148734936>.
>



-- 
Juan Marcos Mirande
Fundación Miguel Lillo - CONICET
Miguel Lillo 251
(4000) San Miguel de Tucumán
Argentina

**Comment by mcmirande** [comment]
Hello Cedric

Evidently the problem is with some of my music folders, because I reduced
them to a few and everything works good. I'll inspect where is the problem
and let you know. I guess it could be fixed, or at least, documented, to
prevent problems in other users.

I have a small suggestion for the program. I think would be great to have,
among the options in the left side of the screen, a "currently playing"
line, or something like that, with the right side changing according to the
album that is sounding.

Well, I'll write you again as soon I discover which files are causing the
problem.

Cheers, Marcos.

2015-10-16 11:42 GMT-03:00 Marcos Mirande <mcmirande@gmail.com>:

> The same happens with Manjaro and Ubuntu.
>
> I'm using Quod Libet associated to Lollypop in order to tag songs. I
> installed all the gstreamer files, but it doesn't change
>  things...
>
> Thanks for your help. Marcos.
>
> 2015-10-16 11:39 GMT-03:00 Cédric Bellegarde <notifications@github.com>:
>
>> Ok, don't know what is happening, you are missing gstreamer tag reader
>> plugin... What distro are you using?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gnumdk/lollypop/issues/319#issuecomment-148734936>.
>>
>
>
>
> --
> Juan Marcos Mirande
> Fundación Miguel Lillo - CONICET
> Miguel Lillo 251
> (4000) San Miguel de Tucumán
> Argentina
>



-- 
Juan Marcos Mirande
Fundación Miguel Lillo - CONICET
Miguel Lillo 251
(4000) San Miguel de Tucumán
Argentina

**Comment by mcmirande** [comment]
Hello Cédric.

After an "artisanal debugging", I found that a file I had in one of the
directories made Lollypop crash. It apparently is a corrupted mp3 file (it
has only 1.4 Kb).
I send it to you, as probably you could find some way to overcome this
problem with other users.

Thanks, Marcos.

2015-10-16 18:07 GMT-03:00 Marcos Mirande <mcmirande@gmail.com>:

> Hello Cedric
>
> Evidently the problem is with some of my music folders, because I reduced
> them to a few and everything works good. I'll inspect where is the problem
> and let you know. I guess it could be fixed, or at least, documented, to
> prevent problems in other users.
>
> I have a small suggestion for the program. I think would be great to have,
> among the options in the left side of the screen, a "currently playing"
> line, or something like that, with the right side changing according to the
> album that is sounding.
>
> Well, I'll write you again as soon I discover which files are causing the
> problem.
>
> Cheers, Marcos.
>
> 2015-10-16 11:42 GMT-03:00 Marcos Mirande <mcmirande@gmail.com>:
>
>> The same happens with Manjaro and Ubuntu.
>>
>> I'm using Quod Libet associated to Lollypop in order to tag songs. I
>> installed all the gstreamer files, but it doesn't change
>>  things...
>>
>> Thanks for your help. Marcos.
>>
>> 2015-10-16 11:39 GMT-03:00 Cédric Bellegarde <notifications@github.com>:
>>
>>> Ok, don't know what is happening, you are missing gstreamer tag reader
>>> plugin... What distro are you using?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/gnumdk/lollypop/issues/319#issuecomment-148734936>.
>>>
>>
>>
>>
>> --
>> Juan Marcos Mirande
>> Fundación Miguel Lillo - CONICET
>> Miguel Lillo 251
>> (4000) San Miguel de Tucumán
>> Argentina
>>
>
>
>
> --
> Juan Marcos Mirande
> Fundación Miguel Lillo - CONICET
> Miguel Lillo 251
> (4000) San Miguel de Tucumán
> Argentina
>



-- 
Juan Marcos Mirande
Fundación Miguel Lillo - CONICET
Miguel Lillo 251
(4000) San Miguel de Tucumán
Argentina

**Comment by gnumdk** [comment]
I can't do anything, report this bug to gstreamer at bugs.gnome.org.

Regards,
