### ISSUE TITLE
App closes when selecting a song to play

### ISSUE THREAD

**Issue by mydegeneration** [gnumdk/lollypop#32]
Hey I'm not sure what is happening but since I updated just now whenever I select a song to play the app closes. This is the error message I get from the terminal:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/mpris.py", line 177, in _on_current_changed
    self.PropertiesChanged(self.MPRIS_PLAYER_IFACE, properties, [])
  File "/usr/lib/python3.4/site-packages/dbus/decorators.py", line 314, in emit_signal
    message.append(signature=signature, *args)
TypeError: Don't know which D-Bus type to use to encode type "NoneType"

**Comment by gnumdk** [comment]
Can you send me ~/.local/share/lollypop/lollypop.db by gdrive/wetransfer/... ?

**Comment by gnumdk** [comment]
And distribution, lollypop version :)

**Comment by gnumdk** [comment]
And test with last git: https://github.com/gnumdk/lollypop/commit/1e4bdf1789e9e98fb3b853df17def79f914cabde
