### ISSUE TITLE
Crash when clicking a radio station on the toolbar

### ISSUE THREAD

**Issue by kolle86** [gnumdk/lollypop#320]
When playing a radio station, lollypop crashes when clicking on the radio logo or stationname in the lollypop toolbar. 
System: Fedora 23
Lollypop-version: latest 0.9.52

Log:
Player::_on_stream_start(): http://1live-diggi.akacast.akamaistream.net/7/965/119435/v1/gnl.akacast.akamaistream.net/1live-diggi
Player::_on_bus_message_tag(): http://1live-diggi.akacast.akamaistream.net/7/965/119435/v1/gnl.akacast.akamaistream.net/1live-diggi
Player::_on_bus_message_tag(): http://1live-diggi.akacast.akamaistream.net/7/965/119435/v1/gnl.akacast.akamaistream.net/1live-diggi
Player::_on_bus_message_tag(): http://1live-diggi.akacast.akamaistream.net/7/965/119435/v1/gnl.akacast.akamaistream.net/1live-diggi
Player::_on_bus_message_tag(): http://1live-diggi.akacast.akamaistream.net/7/965/119435/v1/gnl.akacast.akamaistream.net/1live-diggi
Player::_on_bus_message_tag(): http://1live-diggi.akacast.akamaistream.net/7/965/119435/v1/gnl.akacast.akamaistream.net/1live-diggi
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/toolbar_infos.py", line 139, in _on_infobox_clicked
    self._pop_tunein = TuneinPopover()
TypeError: __init__() missing 1 required positional argument: 'manager'

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/316
