### ISSUE TITLE
Lollypop shows huge Album covers in a Wayland session of Gnome

### ISSUE THREAD

**Issue by cristobaltapia** [gnumdk/lollypop#321]
So, I don't know if this is a Lollypop or a gnome-wayland issue, but I post it here first. This is how Lollypop looks under the Wayland session of Gnome 3.18:
![bildschirmfoto von 2015-10-17 12-19-07](https://cloud.githubusercontent.com/assets/7276493/10558246/95ff2b88-74c9-11e5-8f13-3fb8fa8ccbef.png)

**Comment by gnumdk** [comment]
Dual screen?

**Comment by cristobaltapia** [comment]
Nop. Just a HDPI screen.

**Comment by gnumdk** [comment]
BTW i'm going to remove code calculating cover size base on screen size. It fails with BROADWAY GDK backend.

So I close even if it's not fixed yet.
