### ISSUE TITLE
Centos7 repo

### ISSUE THREAD

**Issue by mudlee** [gnumdk/lollypop#327]
Hey! I'd like to use lollypop more than anything on my main machine which is a centos7 based install. I've tried fedora repos, but it didn't work :(

**Comment by region51** [comment]
@mudlee 
*lollypop BR gtk+-3.0 >= 3.12*
*centos7 = 3.8.8*

**Comment by mudlee** [comment]
I'm sorry? It means it can't be installed on centos? if I build it from git maybe?

**Comment by region51** [comment]
@mudlee 
>It means it can't be installed on centos?

*yes*

>if I build it from git maybe?

*It does not work*

**Comment by region51** [comment]
configure.ac 
>PKG_CHECK_MODULES([GTK], [gtk+-3.0 >= 3.12])

**Comment by mudlee** [comment]
I see. That's sad. I hope centos will upgrade gtk soon and I'll come back. Thank you for your time!
