### ISSUE TITLE
invalid property name in application.css

### ISSUE THREAD

**Issue by clicksaswat** [gnumdk/lollypop#328]
I'm getting this error when opening lollypop

Traceback (most recent call last):
  File "/usr/local/bin/lollypop", line 47, in <module>
    app = Application()
  File "/usr/local/lib/python3.4/site-packages/lollypop/application.py", line 81, in __init__
    cssProvider.load_from_file(cssProviderFile)
GLib.Error: gtk-css-provider-error-quark: application.css:46:18'outline-radius' is not a valid property name (3)

what's the issue?

**Comment by gnumdk** [comment]
What distro?

**Comment by gnumdk** [comment]
https://forum.ubuntu-fr.org/viewtopic.php?id=1860091

Seems Ubuntu 14.04: Not supported.
