### ISSUE TITLE
Big Album Covers

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#329]
*Fedora 22*
*lollypop-0.9.52 good, well, OK, fine, okay, nicely*
![h_1443718816_1793055_761c34f047](https://cloud.githubusercontent.com/assets/13280183/10618932/774564a0-777b-11e5-9aae-31372c2b57a0.png)

*lollypop-0.9.60 nightmare*
![2015-10-20 22-36-08](https://cloud.githubusercontent.com/assets/13280183/10618942/857296a6-777b-11e5-926a-9dcd6952d3df.png)

**Comment by gnumdk** [comment]
Hi dpi?

**Comment by region51** [comment]
*I did in widgets_artist.py*
```
200*scale,
```
![2015-10-21 12-10-01](https://cloud.githubusercontent.com/assets/13280183/10632382/c7ca9172-77ec-11e5-9b3d-0370f04a504d.png)
*Now is good*
