### ISSUE TITLE
Not finding installed 'wikipedia' module

### ISSUE THREAD

**Issue by RedHatter** [gnumdk/lollypop#330]
When I start Lollypop it spits out the following error.

    No module named 'wikipedia'
    Advanced artist informations disabled
    $ sudo pip3 install wikipedia
    Namespace WebKit2 not available for version 4.0
    WebKit support disabled

I ran the command (had to install python3-pip first) but nothing changed. If I run `sudo pip3 install wikipedia` again it outputs

    Requirement already satisfied (use --upgrade to upgrade): wikipedia in /usr/local/lib/python3.5/dist-packages

so it did install.

Any ideas?

**Comment by gnumdk** [comment]
Please see this with your Distro, error is about web kit I think.
