### ISSUE TITLE
Favorited radio stations weren't updated properly after migrating to 0.9.60.

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#333]
I've had 4 favorited radio stations in 0.9.52. Now there is only one in 0.9.60. The .m3u files describing the radio stations are still in the ~/.local/share/lollypop/radios/ directory.

**Comment by gnumdk** [comment]
Can you remove ~/.local/share/lollypop.radios.db and paste output when running lollypop again?

**Comment by kostich** [comment]
Done that. It repopulated radios database properly and I can see all of my radios now. Nothing was outputed in the terminal.

Shouldn't Lollypop do this automatically on every update?

**Comment by gnumdk** [comment]
No, only for 0.9.60

**Comment by gnumdk** [comment]
No, only for 0.9.60
