### ISSUE TITLE
Glitch when seeking before track has loaded

### ISSUE THREAD

**Issue by stp242** [gnumdk/lollypop#334]
If you seek before the track has fully loaded, this will happen:

![test_opt](https://cloud.githubusercontent.com/assets/15237908/10648966/efe355d8-7830-11e5-8185-bb50ed1cf33b.gif)

**Comment by gnumdk** [comment]
"Before the trck has fully loaded"?

**Comment by stp242** [comment]
Well, that's what I was assuming. If I waited a little longer before seeking, I couldn't reproduce it at all.

But I checked again now, and it seems to happen regardless of how long you wait before seeking. It comes up eventually if you just seek randomly for a while.

Can you reproduce?

**Comment by gnumdk** [comment]
OK, I see what is happning

**Comment by gnumdk** [comment]
Can you send me an exemple FLAC file for testing?
My email is in lollypop about dialog.

**Comment by gnumdk** [comment]
And test with last git master ;)

**Comment by stp242** [comment]
Hmm, still produces that glitch using git master.

I sent you an email with a file so you can try it out.

**Comment by gnumdk** [comment]
Can't reproduce with your file but I know how to fix this. This happen in master with cantata.

When seeking gstreamer go in pause and return 0 as position.

**Comment by gnumdk** [comment]
Can you test with git master?

**Comment by stp242** [comment]
That fixed it.

Thanks! :smiley:
