### ISSUE TITLE
Import from CD

### ISSUE THREAD

**Issue by RedHatter** [gnumdk/lollypop#335]
It would be useful if Lollypop could import music from CDs into my library. Currently I have to import using Rhythmbox, I would like to be able to use Lollypop exclusively.

**Comment by gnumdk** [comment]
No, i really don't want such feature in Lollypop, there is dedicated tools for that.

**Comment by kostich** [comment]
@RedHatter, there is already a dedicated GNOME tool for that. You should check out [Sound Juicer](https://wiki.gnome.org/Apps/SoundJuicer).
