### ISSUE TITLE
Failed to play radio by click cover from favorite radio, 0.9.60

### ISSUE THREAD

**Issue by sunng87** [gnumdk/lollypop#336]
I got some issue for my radios after upgrading from previous version. Then I manually removed everything under `.local/share/lollypop/radios/` and `radios.db`. I tried re-add my radios from tuneln index, and it seems worked. I can find my radio stations via sqlite. 

The current issue is when I click cover from favorite radio view, nothing happened, no console output. But if I click radio item from tuneIn index, it just plays.

I tried to list `.local/share/lollypop/radios/` and there are just a few cover pngs, no m3u any more. Since the stream urls are in sqlite, so I think this is right behavior?

**Comment by gnumdk** [comment]
Here it works, can you paste this from radios.db:
sqlite> select * from radios;

**Comment by sunng87** [comment]
Here's mine:

```
sqlite> select * from radios;
1|南京体育广播 104.3 (Sports Talk & News)|mms://live.njgb.com/fm1043|2
2|南京经济广播私家车 98.1 (Automotive)|mms://live.njgb.com/fm981|1
3|南京新闻广播 106.9 (News)|mms://live.njgb.com/fm1069|2
4|北京新闻广播 100.6 (Chinese Talk)|mms://alive.rbc.cn/fm1006|0
5|北京长书广播 104.3 (Literature)|mms://alive.rbc.cn/cfm1043|0
6|北京故事广播 603 (Chinese Talk)|mms://alive.rbc.cn/am603|0
```

**Comment by gnumdk** [comment]
does this works: totem mms://live.njgb.com/fm1043 ?

**Comment by gnumdk** [comment]
In fact, the bug was in tunein popover not extracting playlists:
https://github.com/gnumdk/lollypop/commit/767a6ebc6328be754bf7b17d981b708fe63219b3

So now, it should not works anymore...

Question is: why totemplparser fails on this urls... It shoulds just go in fallback mode.

**Comment by sunng87** [comment]
I think this may be related to #208 you fixed previously.
