### ISSUE TITLE
The radio does not work

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#346]
*Fedora 22, lollypop-0.9.61 the radio does not work*
*He writes permanently -> Restart lollypop after installing codecs*

**Comment by region51** [comment]
Video https://drive.google.com/open?id=0B3_iqoCZRY-EYmtrbDRqYm5KMk0

**Comment by region51** [comment]
*lollypop-0.9.61 a nightmare, no longer runs*

```
[maxim@localhost ~]$ lollypop
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 50, in <module>
    app = Application()
  File "/usr/lib/python3.4/site-packages/lollypop/application.py", line 128, in __init__
    self.register(None)
GLib.Error: g-io-error-quark: Время ожидания истекло (24)

```

**Comment by gnumdk** [comment]
Already fixed.
#345

**Comment by region51** [comment]
*@gnumdk I do not use git source, please do 0.9.62
Radio is very necessary.*

**Comment by region51** [comment]
*@gnumdk thanks for 0.9.62*

**Comment by kostich** [comment]
Hi @region51, one small suggestion. You should prefix lollypop command with LANG (something like LANG=en_US.UTF-8 lollypop) when giving debug output so that the debug info is in English. That will ease the debugging process for @gnumdk. :)

**Comment by region51** [comment]
*@kostich understandably :ok_hand:*
