### ISSUE TITLE
Bug with (probably) .m4a files

### ISSUE THREAD

**Issue by kogli** [gnumdk/lollypop#354]
This is what happens with some of my albums:
![snimek z 2015-11-02 21-43-50](https://cloud.githubusercontent.com/assets/7883957/10893766/d6231f6a-81aa-11e5-9bee-fa3979506d0e.png)

The songs are separated in a completely nonsense way, also, the year is different and really weird with each song, even though I double-checked the tags. This issue seems to only appear with m4a files.

**Comment by gnumdk** [comment]
Can you send me files by email? (gdrive, etc).

My email in about dialog.

**Comment by gnumdk** [comment]
Try to open the files with puddletag... You may have multiple tags frames in files...

**Comment by kogli** [comment]
There you go, I sent you the files. I found no issues in puddletag or with any other music player I tried.
