### ISSUE TITLE
Cursor position messed up

### ISSUE THREAD

**Issue by pradyunsg** [gnumdk/lollypop#356]
Occasionally, Lollypop decides that my cursor is not where Gnome thinks it is.

![screenshot from 2015-11-07 18-14-36](https://cloud.githubusercontent.com/assets/3275593/11015209/7a39ceae-857b-11e5-8759-62568b5c7413.png)

This issue seems to have carried over from multiple updates of (Ubuntu, Gnome-Shell and) Lollypop.
I'm not able to consistently reproduce it but it is happening pretty often. And obviously, it's very irritating. All other applications have never shown this issue, which makes me suspect this is Lollypop specific.

Currently, I'm on Ubuntu 15.10 running the latest lollypop from the ppa and the gnome-shell in the official-repository (3.16?).

**Comment by gnumdk** [comment]
I do not understand your issue. Please give me more informations on what is happening.

**Comment by pradyunsg** [comment]
![gohuyjnezgif com-gif-maker](https://cloud.githubusercontent.com/assets/3275593/11016181/ff014450-859e-11e5-8e4b-357e29a5f383.gif)

Here's a GIF of me moving around the application. It's 5x speed. (ignore the lagging and workspace  switching)

There's an offset between the mouse cursor location and the location that reacts to a mouse actions. That's what I'm referring to. All mouse events seem to be offset by some amount. This makes the application very hard to use.

Also, to re-iterate, no other application has shown this issue for me till date.

It is also visible in the image on the first-post (OP), the cursor is above the "Motion" album art, whereas the Sidebar item "Jason Mraz" is highlighted as if it is hovered on.

PS: I hope the GIF helped. I put in too much time in figuring how to record it...

**Comment by gnumdk** [comment]
Ok, strange but I'm (quite) sure it's not a Lollypop bug as Lollypop doesn't handle mouse cursor mouvement (GTK).

Can you try to guess when this happen? Next popover?

**Comment by pradyunsg** [comment]
I'm know that. I agree it's not Lollypop and GTK but I think Lollypop is doing something other apps aren't doing... Something that's causing this.

I'm still trying to figure out what it is and how it is triggered...

**Comment by gnumdk** [comment]
What is you GTK theme?

**Comment by pradyunsg** [comment]
Vertex theme https://github.com/horst3180/Vertex-theme and Arc theme https://github.com/horst3180/Arc-theme. I'm testing now to see if it happens with Ambience.

**Comment by pradyunsg** [comment]
Ok.

I have just managed to replicate this on RhythmBox with coverart-browser plugin running Adwaita and Default shell theme. Now I'm pretty sure it's coming from the grid-layout (`gtk.FlowBox`).

**Comment by gnumdk** [comment]
Ok, report this to Gtk devs... Never seen this bug here...

**Comment by pradyunsg** [comment]
Sure! :)
