### ISSUE TITLE
Feature request: Last.fm scrobbling 

### ISSUE THREAD

**Issue by lllvvv** [gnumdk/lollypop#36]
It really is just that: I'd really love if there was a way to submit tracks to last.fm - no need for deeper integration. It's really what has been keeping from using lollypop as my main music player.

**Comment by aquatix** [comment]
+1 Just for the scrobbling itself

**Comment by gnumdk** [comment]
I don't want this in lollypop because i'm sure it's not a music player job when we have MPRIS...

We should have a MPRIS scrobbler application...  I let this feature request open... If someone can do the job (A MPRIS daemon sending played songs to last.fm or libre.fm)...

**Comment by bil-elmoussaoui** [comment]
+1

**Comment by te-x** [comment]
What do I need to do in order to has last.fm scrobbling? In the preferences it says it requires "gi secret" but I have no idea what that is. I'm running fedora

**Comment by cwilli34** [comment]
I too would also like to know what gi secret is and how to get last.fm scrobbling working.

**Comment by region51** [comment]
"gi secret" Fedora 22
```
pip3 install pylast
pip3 install wikipedia
```
![2015-10-23 12-00-31](https://cloud.githubusercontent.com/assets/13280183/10688544/b5621856-797d-11e5-9877-978a0e39b266.png)

**Comment by cwilli34** [comment]
Oh, I had installed both those packages, and killed/restarted the program, and it didn't appear to work.  It took a system reboot, and all is fine now.  Thanks!
