### ISSUE TITLE
Random playlist

### ISSUE THREAD

**Issue by MichaelTiebesl** [gnumdk/lollypop#365]
How can i play songs from the random playlist?
When i go to playlist and then random and click on one of the songs from that list, nothing happens.

Random albums works fine.

I use Arch Gnome. Lollypop is version 0.9.70.

**Comment by gnumdk** [comment]
>nothing happens.

Do not play the song?

Can you do a screencast?

**Comment by Bhav97** [comment]
Can confirm 
https://www.youtube.com/watch?v=mAF62G5zGUM
It shuffles next track if a song is playing
Nothing happens if no song is playing

**Comment by MichaelTiebesl** [comment]
@Bhav97 Thanks for the upload. Yes same to me what you are showing.

**Comment by gnumdk** [comment]
I was trying with the random options... :)

**Comment by gnumdk** [comment]
All static playlists are broken

**Comment by MichaelTiebesl** [comment]
Thanks, it works again.
