### ISSUE TITLE
Adding Music

### ISSUE THREAD

**Issue by abusefreewill** [gnumdk/lollypop#366]
When I try to add music most of the music gets imported but it seems to randomly gets stuck so that not all the music gets added.  

Is there a size limit or something? My library is about 17000 items or 160GB. I've had this problem on various ubuntu based systems.

**Comment by bookletchoir** [comment]
Can reproduce, when i tried to add ~250GB of music from external HDD and left it there for 30 minutes, it just stuck there: can play music, can do whatever but the new music doesnt seem to be added to the library. The db files in `~.local/share/lollypop/` stays the same size as well.

**Comment by gnumdk** [comment]
lollypop -d

**Comment by abusefreewill** [comment]
Ahh, thanks. Although I don't know why it worked in debug mode. I seem to have added everything now.
