### ISSUE TITLE
Add Lyrics, plug-ins ?

### ISSUE THREAD

**Issue by Salamandar** [gnumdk/lollypop#367]
I love the lyrics inside the main window in GMusicBrowser. Is it a planned feature ?

Moreover, it would be great to have a "plugin" system to add such feature ;)

**Comment by MichaelTiebesl** [comment]
@Salamandar There is an Lyrics option and a very good one also.
I have Arch so i had to install python-wikipedia to get it.
It is when i click on the album picture what is playing, then there are a few options. For lyrics it is Wikia.

**Comment by gnumdk** [comment]
Your need python webkit bindings.

**Comment by Salamandar** [comment]
Yes I saw it but :
* This is a pop-up, it can't stay opened all the time
* It searches the lyrics on the web. GMusicBrowser searched the lyrics and then saved them inside the musics' metadatas :) Now I can have the lyrics offline.
