### ISSUE TITLE
"All albums" is slow  and laggy to appear

### ISSUE THREAD

**Issue by Salamandar** [gnumdk/lollypop#369]
When selecting "all albums" or some artist, the ScrollView content size is not requested all at once.
When loading a list with several hundreds of albums, the whole interface is laggy as long as the list is not fully loaded.
Shouldn't be more appropriate to calculate the content size and *then* to load it ?
(And maybe load the cover images after loading the size and widgets ?)

**Comment by gnumdk** [comment]
No lag here...

**Comment by Salamandar** [comment]
Well try to open a drop-down menu while the album list is "loading"…

**Comment by gnumdk** [comment]
No issue, menu open smoothly.

**Comment by gnumdk** [comment]
Quite sure issue comes from broken Graphic drivers while loading a huge GtkFlowBox/GtkListBox.

Can you tell me for how many tracks you see the issue?

**Comment by ff-** [comment]
+1 on this, with 6000+ tracks. (And they would be 10k, if it wasn't for #378 ).

Maybe a fix would be to render only the albums which are currently in the view (like you would do in infinite scrolling videogames).

**Comment by Salamandar** [comment]
Yup me too, I got 12k+ songs. Dunno how many albums, but maybe a thousand.
Yeah, that would be a good idea. In GMusicBrowser it's the case but it's not pretty. Maybe render the albums which are currently in the view, plus some more up and down from the view. Hope I am clear enough. :)

**Comment by gnumdk** [comment]
16k+ songs and no issue here. 

Lollypop use GLib main loop to load albums, so if you scroll or click a button, lollypop stop loading while doing UI stuff...

# apt-get install python3-pip
# pip3 install pycallgraph

In lollypop options, activate "Remember state"

Go to all artists/albums view and quit lollypop.

Then run:
$ LOLLYPOP_TRACE=1 lollypop

On last Ubuntu:
LOLLYPOP_TRACE=1 /usr/bin/python3.5 lollypop

Quit lollypop and past here lollypop.png file

**Comment by gnumdk** [comment]
@Salamandar ?

**Comment by Salamandar** [comment]
Sorry hadnt much time this week. I'll do it this evening !

**Comment by Salamandar** [comment]
Hmmmmmmm if I scroll or click a button, lollypop continues to load albums.
But here is the trace :)
![lollypop](https://cloud.githubusercontent.com/assets/6552989/11574506/55208efa-9a0c-11e5-90f2-ccf0fbe1c83d.png)

**Comment by gnumdk** [comment]
@Salamandar It stops loading to let Gtk do scrolling but it's not human visible ;)

Bad, your trace is missing lollypop function calls :( What distro?

**Comment by Salamandar** [comment]
Manjaro Linux. And the package is built from source from the git repo.

**Comment by gnumdk** [comment]
Strange, it works on ArchLinux, Fedora and Ubuntu :-(

**Comment by gnumdk** [comment]
@Salamandar ping?

**Comment by Salamandar** [comment]
Sorry. Big projects this month. 
Well, I may have done 

    export LOLLYPOP_TRACE=1
    lollypop

But here is the trace with 

    LOLLYPOP_TRACE=1 lollypop

![lollypop](https://cloud.githubusercontent.com/assets/6552989/11768865/3015e030-a1da-11e5-8577-db909ee2db54.png)

**Comment by gnumdk** [comment]
Missing lollypop fonction cals...

**Comment by Salamandar** [comment]
How could function calls be missing ? And which ones ? :p

**Comment by Salamandar** [comment]
By the way it REALLY would be better to first, allocate the size in the view, THEN load the album covers.
Because right now, you can't click on "all albums" and scroll right after to the very end of the list. It has to load. And you have to wait.

**Comment by gnumdk** [comment]
It shoulds look like this:
![lollypop](https://cloud.githubusercontent.com/assets/3918824/11769028/8a327af2-a1de-11e5-930c-46b1c50a15ef.png)

**Comment by Salamandar** [comment]
And I don't have the whole square on the right ? Hum. I'll try to reinstall lollypop from the git repo.

**Comment by gnumdk** [comment]
The issue isn't in lollypop but in your distro... Strange as it's an arch...

**Comment by Salamandar** [comment]
Oh. What do you mean ?
BTW here is the whole result of lollypop :

    /usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
    g_type = info.get_g_type()
    /usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
    g_type = info.get_g_type()
    /usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
    g_type = info.get_g_type()
    ArtDownloader::_get_album_art_lastfm: Album not found 
    ArtDownloader::_get_album_art_lastfm: Album not found

**Comment by gnumdk** [comment]
That pycallgraph doesn't work in Manjaro...

**Comment by Salamandar** [comment]
Hum, strange. Maybe some libs just weren't compiled with debug symbols ?

**Comment by gnumdk** [comment]
>By the way it REALLY would be better to first, allocate the size in the view, THEN load the album 
>covers.
This is not acceptable for me, here loading an GtkFlowBox with empty GtkImage with 1042 albums:
- is slow
- hangs lollypop

And i can't set GtkFlowBox height because it will not show albums at the end of the view until it's loaded.

**Comment by gnumdk** [comment]
Seems i've found a solution ;)

**Comment by gnumdk** [comment]
@Salamandar Have you tested current git? Is it ok?

**Comment by Salamandar** [comment]
I didn't, but going to tonight !
