### ISSUE TITLE
Header doesn't redraw properly when changing height.

### ISSUE THREAD

**Issue by alexskc** [gnumdk/lollypop#37]
Clicking on a song with a Japanese title, for example, will cause the header to get thicker, but it'll glitch out when it does so, like this: http://i.imgur.com/LXmKQdW.png
This is easily fixed by alt-tabbing out of the program, upon which it looks normal: http://i.imgur.com/cXnOHyu.png
Clicking back to a song with only roman characters will cause it to glitch out again: http://i.imgur.com/V04XECO.png
Until you alt-tab out of the program: http://i.imgur.com/8njFE4b.png

**Comment by gnumdk** [comment]
Seems to be a gtk bug...  Will look what is happening.

**Comment by gnumdk** [comment]
Can't reproduce here, can you send me a track with Japaneses title  to my email via drive/dropbox/... ?

**Comment by gnumdk** [comment]
Ok, tested with a Japanese title, no bug here... What is your Gtk Version?

**Comment by alexskc** [comment]
GTK 3.14.9, though I recall it being the same with earlier versions.

**Comment by gnumdk** [comment]
Strange, ArchLinux? What font? What size? Send me the file ;)

**Comment by alexskc** [comment]
Yep, Arch Linux.
Roboto Light,10
Works with any file. Here's a random example: https://a.pomf.se/plqgbb.mp3
Quick recording of it happening in action: https://a.pomf.se/rmdmbg.webm

It probably is a GTK issue.
