### ISSUE TITLE
No volume control

### ISSUE THREAD

**Issue by sirdeiu** [gnumdk/lollypop#370]
Missing volume control functionality both with keyboard shortcuts and interface interaction.
Otherwise **great** player, maybe should push for inclusion with Gnome.

**Comment by Rombusevil** [comment]
I use Laine extension for that. You can also adjust the volume of each aplication with the gnome sound settings.

**Comment by gnumdk** [comment]
Won't fix, not a feature needed IMO and firm a GNOME hig pov.
