### ISSUE TITLE
Allow sorting artists by ARTISTSORTORDER tag

### ISSUE THREAD

**Issue by unaszplodrmann** [gnumdk/lollypop#371]
At long last, I've found a music player that I actually like, other than foobar2000. I can't believe how quickly it scans and searches my 160GB of MP3s. Thank you! 

Would you please consider providing the option to sort artists by the ARTISTSORTORDER tag for those of us who've used MusicBrainz to tag our files?

**Comment by gnumdk** [comment]
What is the issue? What value of ARTISTSORORDER do you have in your tags?

**Comment by gnumdk** [comment]
ping?

**Comment by unaszplodrmann** [comment]
Apologies -- thanks for the ping.

Here's some sample ID3v4 fields from a file in my library. MusicBrainz populates TSO2 (as per iTunes tagging) and also TSOP:

Artist = David Sylvian
  | - Tag 'TPE1' (14 bytes):
  |     002e: 03 44 61 76 69 64 20 53 79 6c 76 69 61 6e       [.David Sylvian]

  | AlbumArtistSortOrder = Sylvian, David
  | - Tag 'TSO2' (15 bytes):
  |     168e: 03 53 79 6c 76 69 61 6e 2c 20 44 61 76 69 64    [.Sylvian, David]

  | PerformerSortOrder = Sylvian, David
  | - Tag 'TSOP' (15 bytes):
  |     8393: 03 53 79 6c 76 69 61 6e 2c 20 44 61 76 69 64    [.Sylvian, David]

MusicBrainz writes 'artistsort' and 'albumartistsort' into Vorbis comments, too.

Would you consider adding the option to list artists in the left hand pane according to the sort order value in the tags?

**Comment by unaszplodrmann** [comment]
MusicBrainz tag mappings: https://picard.musicbrainz.org/docs/mappings/
