### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by uommo** [gnumdk/lollypop#373]
With enabled option "Continue playback when close" lollypop sends desktop notifications (when window is closed) even if they are turned off in gnome settings. Issue occurs on fedora 23 with gnome desktop, lollypop installed from copr repo. 

Great player, btw! Thanks! Perfectly fits gnome desktop. Good luck!

**Comment by gnumdk** [comment]
Can't reproduce here on Ubuntu 15.10 and ArchLinux.

Btw, the bug can't be in Lollypop as this is handled by Gnome Shell...

**Comment by uommo** [comment]
Hmm... Strange thing - an hour ago I built Lollypop from git (earlier I was using one from copr), checked dconf-editor and found there (org > gnome > Lollypop) parameter "disable-notification" which was unchecked. I've checked it, re-logon to gnome-shell and now it seems fine.

**Comment by simonbcn** [comment]
Same problem. To me the problem appears after Gnome shutdown the monitor to save energy. 
I have disabled "disable-notification" in dconf-editor and I hope now it works. I don't know if it's a bug the Lollypop or Gnome. There is a bug opened in Gnome related to this: https://bugzilla.gnome.org/show_bug.cgi?id=752881
