### ISSUE TITLE
Support for synchronized lyrics?

### ISSUE THREAD

**Issue by lanzorg** [gnumdk/lollypop#375]
Is it possible to add synchronized lyrics support inside lollypop?
Something like the CU LRC Lyrics Kodi addon.

Preview:
![CU LRC Lyrics in action](http://i.imgur.com/5E9w3hu.jpg)

Github:
https://github.com/ronie/script.cu.lrclyrics/

**Comment by gnumdk** [comment]
No, this kind of software are illegal. Lyrics websites disallow you to extract lyrics from their webpage.

I don't want lollypop to do this.
