### ISSUE TITLE
ShufflePlayer class crash without Rhytmbox installed

### ISSUE THREAD

**Issue by xnand** [gnumdk/lollypop#376]
Hi. First thing, i want to compliment for this awesome player, that took the place of rhytmbox on my arch desktop. But this generated a problem. When in Lollypop i press on shuffle or party mode, it crashes. The traceback is as follows:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/player_shuffle.py", line 157, in _set_shuffle
    self._rgvolume.props.album_mode = 0
AttributeError: 'NoneType' object has no attribute 'props'

So i looked in the source code and, not fining any rgvolume, i searched it on google, and found it under some rhytmbox results. Then i reinstalled rhytmbox, and now Lollypop doesn't crash anymore. Maybe i removed some dependency while removing rhytmbox?

**Comment by gnumdk** [comment]
Broken distro... Will add a check.
