### ISSUE TITLE
compilation tag on  m4a had no effect.

### ISSUE THREAD

**Issue by lmouillart** [gnumdk/lollypop#377]
Hi,
I have files from the same album with a compilation tag on it. In Lollypop thoses files are splitted by date in many fake albums, also with wrong tracknumber used on it.
Expected behavior is to have 1 album for all tracks in the same compilation (maybe more if they are more than 1 CD).

You cloud find here sample music files https://goo.gl/ossFRf

![capture du 2015-11-29 02-26-17](https://cloud.githubusercontent.com/assets/13631955/11454897/a6c5bd3a-9641-11e5-955b-31f656e01ee2.png)

**Comment by gnumdk** [comment]
Albums with different years are different albums: https://github.com/gnumdk/lollypop/issues/307

"Arno - Le best of" release date is 2000. You can specify a special TDOR (original track year) tag but lollypop will ignore it (only shows year for albums).

By the way, lollypop do not use compilation tag as it's not supported by all formats.

Like Amarok and Clementine, a compilation is: an album with same name, same year where "album artist" tag is empty.

**Comment by garymartynuk** [comment]
It seems this fix could break more than it fixes.  I understand the above original post is a problem.  However it seems there are far more albums with tracks from different years (all those "best of..." albums).  From just about any source I've used (Amazon, iTunes etc) they all encode the Year field with the track year not the album year.  This seems to follow the outlined guidelines on ID3.org where TYER is the year of recording, not the year of release.  This change breaks something like 50 albums in my collection, the previous configuration where the year field was not a part of the album splitting would not break a single one.

http://id3.org/id3v2.3.0

I can work around it, but it seems I will need to actually reduce the accuracy of my tags to get Lollypop to list my albums correctly.   This is not a problem in Banshee, WMP, Google Music, Gnome Music etc.  Any chance of reconsidering this fix?
