### ISSUE TITLE
Crash while indexing BIG library

### ISSUE THREAD

**Issue by ff-** [gnumdk/lollypop#378]
The program crashes (segfault) while trying to index my _big_ library (90GB, 10k+ files). It crashes at ~70% of the indexing (like at the P letter).

**Comment by alexskc** [comment]
I don't think this a problem with the size of the library. Mine is 120GB and 20k files, and Lollypop indexes it fine.

**Comment by Salamandar** [comment]
I got a 12k+ library and I don't have any crashes (but some related to gstreamer because of some strange audio formats).

**Comment by ff-** [comment]
Yep, I had the feeling that the sheer number of files wasn't the cause of the crash, in fact right now I'm trying to find any "strange" character that may lead to the crash.
Could you please suggest any way to get a meaningful stacktrace?

**Comment by gnumdk** [comment]
lollypop -d

**Comment by ff-** [comment]
@gnumdk thanks! I changed some files in the library and cannot longer replicate the bug - now the library gets scanned :) 
Closing.
