### ISSUE TITLE
Enhancement suggestions

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#380]
Thanks for that beautiful and awesome music player with a great integration with GNOME.
Now, I use Lollypop instead of Clementine!
I installed latest version from [Copr Fedora repository](https://copr.fedoraproject.org/coprs/gnumdk/lollypop/).

I have some suggestions to enhance the software:
* Display Lollypop in a down mode:

![gnome_down app](https://cloud.githubusercontent.com/assets/4758871/9339885/cf515ce6-45ec-11e5-80a5-2d1306b4466f.png)

* Display album cover in the GNOME notification:

![capture d ecran de 2015-11-30 15-46-49](https://cloud.githubusercontent.com/assets/4758871/11474671/ca1ebb04-9779-11e5-8eeb-5b04303a36fa.png)

* Display Lollypop logo in the audio GNOME configuration:

![song_music_players](https://cloud.githubusercontent.com/assets/4758871/11474726/1abb9bd6-977a-11e5-8a43-4896b48f04e7.png)

**Comment by gnumdk** [comment]
- Systray is dead, applications should not use this anymore, install gnome shell mpris extension
- Gnome doesn't support custom image in notifications anymore (from client point of view)
- Hey, you are right! Where is my logo??? :)

**Comment by gnumdk** [comment]
Icon is also bad with gnome music.

Bug is in Gnome mixer showing icon for python-3.4 :-/ It should look at application name through dbus.

**Comment by M5oul** [comment]
Thanks for artwork in notification :+1:

**Comment by gnumdk** [comment]
Yes, was a really hard fix: one line :)

**Comment by gnumdk** [comment]
Was not a bug in gnome mixer, I was not using the good method :)
