### ISSUE TITLE
Fullscreen mode is broken on Fedora 23

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#381]
I've tried to use Fullscreen mode when playing a radio station but it is broken on Fedora 23. It doesn't matter if the item played is a radio station or a song. There wasn't anything usefull in the terminal output. Lollypop 0.9.70.

![2015-11-30 16-49-09](https://cloud.githubusercontent.com/assets/4953862/11476384/b8adeed6-9782-11e5-8c5c-22ec7c187451.png)

**Comment by region51** [comment]
I confirm
![2015-11-30 19-20-24](https://cloud.githubusercontent.com/assets/13280183/11477120/86903afc-9797-11e5-91cd-a5afbf55eed2.png)

**Comment by region51** [comment]
![2015-11-30 19-24-07](https://cloud.githubusercontent.com/assets/13280183/11477237/21170560-9798-11e5-9397-d3db4900628f.png)

**Comment by region51** [comment]
and a very, very big album cover
