### ISSUE TITLE
The autoconfigure script does not check for the presence of libtotem-plparser

### ISSUE THREAD

**Issue by teromene** [gnumdk/lollypop#382]
While compiling from sources, the autoconfigure script does not require you to install libtotem-plparser, but lollypop will not start if it is not installed.

The error message is then :
```ValueError: Namespace TotemPlParser not available```

**Comment by gnumdk** [comment]
I don't know how to check for a python introspection module.

Checking for libtotem-plparser will not work on Ubuntu for exemple.

**Comment by teromene** [comment]
My mistake, the package that makes lollypop work is gir1.2-totem-plparser-1.0

**Comment by gnumdk** [comment]
Ubuntu/Debian separates gir packages but GNOME doesn't seem to offer a way to check for this.

So just add a check for totem-plparser
