### ISSUE TITLE
Add support for podcasts

### ISSUE THREAD

**Issue by satabin** [gnumdk/lollypop#384]
Podcast subscription should be possible in lollypop.

The basic actions that are needed as first support are:
 - [ ] Feed management
   - [ ] Subscription
   - [ ] Unsubscription
   - [ ] Information
   - [ ] Rating
   - [ ] Automatic download
 - [ ] Episode management
   - [ ] Information (duration, author, title, summary, ...)
   - [ ] Status (downloaded, played, …)
   - [ ] Download
   - [ ] Play
   - [ ] Rate
   - [ ] Delete local content

Lollypop should check for new episodes in subscribed feeds (when starting? regularly?)

Am I missing something important?

**Comment by alexskc** [comment]
Please, no. Lollypop is a music app. It's used for playing music. You shouldn't go to the music app to play podcasts, you go to the podcasts app.

Maybe I'm getting a bit political here, but in my mind, all-in-one "media apps" are a cancer, and I don't want to see Lollypop become one.

**Comment by bil-elmoussaoui** [comment]
Just use Vocal.

**Comment by MichaelTiebesl** [comment]
I fully agree with @alexskc. This is 1 of the reason i use Lollypop now.

**Comment by gnumdk** [comment]
After reading the description, I have to be agree, way too complicated for feet lollypop HIM.

As I say on DLFP, use vocal.

**Comment by satabin** [comment]
OK
