### ISSUE TITLE
Queue and Search open above the window in wayland

### ISSUE THREAD

**Issue by toirdgh** [gnumdk/lollypop#385]
Using lollypop in wayland, the Queue and Search will open above the window instead of below the window.

**Comment by fredoche** [comment]
Same issue here (fedora 23 with COPR)

**Comment by gnumdk** [comment]
Why below?

**Comment by fredoche** [comment]
It currently looks like this on wayland.
![lollypop](https://cloud.githubusercontent.com/assets/143735/11560424/a182c250-99c0-11e5-9b94-9c4aaaecfb90.png).

**Comment by gnumdk** [comment]
This is a bug in GTK. But as Nautilus force popover direction, i will do the same.
