### ISSUE TITLE
no translation RU

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#389]
0.9.72 -> Preferences=Preferences???
![2015-12-03 18-25-30](https://cloud.githubusercontent.com/assets/13280183/11564695/91dfe744-99eb-11e5-88b0-6d7baa6090cd.png)
0.9.62 -> Preferences=Настройки
![1igxnib](https://cloud.githubusercontent.com/assets/13280183/11564724/b139382a-99eb-11e5-8f95-09bf4b1eb4f1.png)

**Comment by gnumdk** [comment]
Same for all languages :-(

**Comment by region51** [comment]
Understandably, must be corrected in the next version.
PS. I'm sorry for my bad english.
