### ISSUE TITLE
DatabaseTracks::add:  'utf-8' codec can't encode character […]  surrogates not allowed

### ISSUE THREAD

**Issue by Sidosido** [gnumdk/lollypop#39]
Hey there. I guess this is not a direct lollypop bug, but : 
- it prevents from starting.
- I have no clue to clean up the guilty files.

```
DatabaseTracks::add:  'utf-8' codec can't encode character '\udc82' in position 5: surrogates not allowed
DatabaseTracks::add:  'utf-8' codec can't encode character '\udc88' in position 11: surrogates not allowed
DatabaseTracks::add:  'utf-8' codec can't encode character '\udc8a' in position 12: surrogates not allowed
Unhandled exception in thread started by <bound method CollectionScanner._scan of <CollectionScanner object at 0xb525f3ec (lollypop+collectionscanner+CollectionScanner at 0x9dd8b00)>>
Traceback (most recent call last):
  File "/usr/local/xstow/lollypop/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 127, in _scan
    self._add2db(filepath, mtime, tag, sql)
  File "/usr/local/xstow/lollypop/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 274, in _add2db
    Objects.albums.set_path(album_id, path, sql)
  File "/usr/local/xstow/lollypop/lib/python3.4/site-packages/lollypop/database_albums.py", line 60, in set_path
    sql.execute("UPDATE albums SET path=? WHERE rowid=?", (path, album_id))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc0' in position 76: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/xstow/lollypop/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 140, in _scan
    print(filepath)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc0' in position 76: surrogates not allowed
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1296, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.4/threading.py", line 1019, in _delete
    del _active[get_ident()]
KeyError: -1313957056
```

**Comment by gnumdk** [comment]
Sorry, i only support UTF-8 locales...
If you really don't want to make your system UTF-8, juste start lollypop with:
[bash $] LANG=en_US.UTF-8 lollypop

**Comment by Sidosido** [comment]
Well, there's a mess with a few files, but this system is actually UTF-8.
And I can add my whole music tree to mocp, cmus or audacious (maybe those messy files don't come up in the playlist, but I can play every other ones).
Oh well…

**Comment by gnumdk** [comment]
Can you do this in   bash
echo $LANG

**Comment by Sidosido** [comment]
I can!
```
~$ echo $LANG
fr_FR.UTF-8
```

**Comment by gnumdk** [comment]
http://www.scarfboy.com/coding/unicode-tool%3Fs%3DPLUS-MINUS%2520SIGN?s=U%2BDCC0

Here the broken character...

**Comment by Sidosido** [comment]
There are at least 4 broken characters : \udc82, \udc88, \udc8a and \udcc0.

The point is not you or Lollypop to correct my files, the point is that an audio player loads audio files. If it can't, it should keep on with the other audio files, imho (and maybe tell the user where to correct things).

**Comment by gnumdk** [comment]
If you can send me a broken encoding file...

**Comment by Sidosido** [comment]
Works now as it should !
Bad encoded files are being ignored and don't appear in the collection, but are logged in the terminal. Wonderful.

Great piece of software, btw ^_^

**Comment by gnumdk** [comment]
http://linuxfr.org/forums/programmation-python/posts/python-et-l-unicode
