### ISSUE TITLE
Hide song progress bar when the radio is played

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#390]
When the radio station is played, a song progress bar is disabled and sits it in the interface, unused. This song progress bar also obstructs the labels displaying the radio name and radio URL/current radio song name (as shown on the picture bellow).

![2015-12-03 20-43-20](https://cloud.githubusercontent.com/assets/4953862/11572501/efe50566-9a01-11e5-8dff-191c06a3ce2a.png)

Can Lollypop hide song progress bar and expand labels containing the radio name, radio URL/current radio song name to that space when a radio station is played? Then when a song is played again, the song progress bar should be restored and labels readjusted as they are currently.

Thanks for reading my suggestion!

**Comment by gnumdk** [comment]
This is wanted. The label is truncated anyway.
There is a tooltip to get non truncated string.
