### ISSUE TITLE
Last.FM log in does not work

### ISSUE THREAD

**Issue by asyncial** [gnumdk/lollypop#394]
Hey, I have a problem to log into Last.FM with Lollypop. Although I installed the required dependencies (libsecret + python-pylast), it just shows a small sad face next to the connect button.
Thanks for your work, asyncial

**Comment by gnumdk** [comment]
What pylast version?

**Comment by region51** [comment]
Fedora 23, python3-pylast-1.4.2 everything is working
![2015-12-08 16-50-51](https://cloud.githubusercontent.com/assets/13280183/11657201/f9dc9ffc-9dcb-11e5-9443-f3dcdf2f6c2d.png)

**Comment by gnumdk** [comment]
Archlinux, working ;)
python-pylast 1.4.2-1

**Comment by gnumdk** [comment]
@asyncial ping?

**Comment by asyncial** [comment]
On my machine runs Arch Linux with python-pylast 1.4.2-1 as well. Still doesn't work.

![screenshot-20151211-200354](https://cloud.githubusercontent.com/assets/14057192/11752969/e6e76eee-a042-11e5-9b25-ea95f989bb48.png)

**Comment by gnumdk** [comment]
Any error on command line?

**Comment by asyncial** [comment]
After trying to log in, it throws: 
>Settings::_update_lastfm_settings(): g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)

**Comment by gnumdk** [comment]
You are missing some gnome services... You need gnome keyring!
