### ISSUE TITLE
tiny issue

### ISSUE THREAD

**Issue by thundersqueak** [gnumdk/lollypop#40]
First of all let me say i'm loving lollypop!.The issue i have is when in dark variant in gnome when i click on party mode 1 time or more the dark theme is turned off until further presses.

**Comment by gnumdk** [comment]
Strange, doesn't happen here :(

**Comment by gnumdk** [comment]
What distrib?

**Comment by gnumdk** [comment]
The dark mode was buggy in 0.9.0 but if you use gnome global option, just activate dark mode in lollypop, it should work.

**Comment by thundersqueak** [comment]
Thanks Cedric,then i will wait till my repos update to latest version.

**Comment by gnumdk** [comment]
Just activate dark mode in lollypop settings
