### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by Saphyel** [gnumdk/lollypop#400]
Show the lyrics of the song

**Comment by gnumdk** [comment]
Already available, install webkit for python.

**Comment by i90rr** [comment]
Hi,
I installed what I believe is the correct library - more info below - and restarted Lollypop but I'm clueless on how to make it show the lyrics of the currently playing song.

***Sysinfo***
Lollypop: 0.9.77
OS: Fedora 23
PyWebKitGtk info:
Name        : pywebkitgtk
Arch        : x86_64
Epoch       : 0
Version     : 1.1.8
Release     : 10.fc23
Size        : 237 k
Repo        : @System
From repo   : fedora
Summary     : Python Bindings for WebKit-gtk
URL         : http://code.google.com/p/pywebkitgtk/
License     : LGPLv2+
Description : The purpose of pywebkitgtk is to bring an alternative web engine to
            : Python/GTK+ application developers who might need a web browser engine for
            : their next application or developers wishing to have a better browser engine
            : that they can access to using the Python programming language.

What I am doing wrong?
