### ISSUE TITLE
Improve compilation detection

### ISSUE THREAD

**Issue by rolf1304** [gnumdk/lollypop#402]
I like it that Lollypop automagically detects "compilations", albums with various artists.

However, the detection is off. It seems to me that right now it just checks if the there's one album name with multiple artists in the database. This means that for example, the albums *Live* by Built to Spill and the *Live* by Alison Krauss and Union Station are treated as one compilation album.

As a solution, I propose that Lollypop should check that the albums reside in different directories before assuming they're a compilation.

/ Edit: Another possible solution is to check if there are double track numbers for the album (so there are two track no. 1's or two track no. 2's, etc.)

**Comment by gnumdk** [comment]
Just set album artist tag to prevent compilation detection.
