### ISSUE TITLE
Needs a volume control

### ISSUE THREAD

**Issue by sbtypo3** [gnumdk/lollypop#404]
This is what I miss when using lollypop (or gnome music for that matter). I don't want to have to adjust my main volume just because a song plays loudly.

**Comment by alexskc** [comment]
The OS can adjust the volume of individual applications. Why do you need the app to do it?

**Comment by sbtypo3** [comment]
but rhythm box has it's own volume. I can set the playback volume with it... that's what lollypop needs

**Comment by Rombusevil** [comment]
You can change the volume of any sound source individually in gnome (go to sound settings -> applications). You can also try gnome extensions like "Laine" for quick access.

**Comment by gnumdk** [comment]
Invalid: GNOME HIG.
rhythmbox doesn't respect GNOME HIG.

You can use gnome shell MPRIS client

**Comment by sbtypo3** [comment]
Can you point out where in the HIG it says that you shouldn't offer a
volume control???? And that is not a reason to invalidate the bug. Why
should I go in to some obscure settings panel just to adjust the volume of
a song???

Cédric Bellegarde <notifications@github.com> schrieb am Di., 29. Dez. 2015
um 10:05 Uhr:

**Comment by gnumdk** [comment]
New GNOME applications doesn't offer a volume slider. Rythmbox doesn't follow gnome3 look and feel.

**Comment by gnumdk** [comment]
And IMO, setting volume in app is a confusing concept.
