### ISSUE TITLE
Allow id3 tag editing inside lollypop

### ISSUE THREAD

**Issue by william-c-martin-iii** [gnumdk/lollypop#405]
Are there any plans to allow the editing of id3 tags for mp3s from inside Lollypop without having to use a separate dedicated app? 

For example, when I go a particular artist and notice a few songs are being displayed as a separate album entirely because the album title isn't consistently capitalized, it would be much easier to edit it on the spot from inside lollypop, rather than use an external program dedicated to id3 tag editing, where the individual songs have to be looked up there separately.

**Comment by gnumdk** [comment]
Easy tag allow you to tag many songs at once.
Not planned, out of scope.

**Comment by william-c-martin-iii** [comment]
I think I was unclear with my question. The issue I am bringing up is having to use something like Easy Tag in the first place instead of doing it right inside lollipop.

This is the user flow with the current version of lollipop:

1) While in lollipop, notice a song has incorrect id3 info
2) Open Easy Tag
3) Search for the particular artist, album, and song title inside Easy Tag (even though it's already pulled up in lollipop)
4) Correct the id3 tag and save
5) Go back to lollipop and have it update music, resulting in the current playing song to stop
6) Press play again after the update
7) Refresh the view to reflect the id3 change

If id3 editing was integrated into lollipop, it would be simplified to just:

1) While in lollipop, notice a song has incorrect id3 info
2) Right click the song and edit the id3 tag on the fly

**Comment by gnumdk** [comment]
Lollypop already allow you to launch tag editor from album menu. This only works well if all albums have a dedicated folder.

But I will not include a tagging software in lollypop, it's a too complicated task.

**Comment by cjsiglin** [comment]
There are many standalone Python libraries; eyed3 and id3reader. It would be fairly simple to extend these libraries with a UI. However, if this is out of scope of the project I will not pursue it's integration. The project looks great in all other aspects.

**Comment by william-c-martin-iii** [comment]
Ah, I see, it's the little menu icon in the album view, with the option "Modify informations" that launches an external tag editor. Perfect! I did not notice that feature until now when you mentioned it, nor did I ever even notice the little menu icon until now.

Thank you for the response. I guess the only other feedback I have to add is:

1) Consider making the menu icon more noticeable in the album view (maybe by making it a 3D button icon consistent with the key/search/party mode/shuffle icons at the top right of lollypop). 

2) Change "Modify Informations" to something more.. expected, such as "Edit ID3 Tags" or "Open Tag Editor", or something else more obvious as to what the feature actually does.

**Comment by gnumdk** [comment]
I think that for a non geek user, "modify informations" is better than "Edit tags" ;)
Same as Itunes.
