### ISSUE TITLE
Pointer on the seeker bar is too large

### ISSUE THREAD

**Issue by anaturinbor** [gnumdk/lollypop#408]
On Elementary OS Freya the circle on the top bar is too big. Not really a problem but it might be better to reduce the size a little bit.

![screenshot from 2016-01-02 01 47 16](https://cloud.githubusercontent.com/assets/10692755/12072643/df058c2c-b0f2-11e5-9722-aac175b7ead6.png)

**Comment by gnumdk** [comment]
Theme issue, change your Gtk theme.

**Comment by gnumdk** [comment]
I think your issue is fixed in 0.9.80.

Issue was: "Headerbar is too small" ;)
