### ISSUE TITLE
Playback stops when updating music

### ISSUE THREAD

**Issue by william-c-martin-iii** [gnumdk/lollypop#409]
When the "Udpate music" option is run either automatically or from the lollypop menu, music playback stops. I would prefer to leave the auto update feature on, but it constantly halts the music I have playing. Is this expected behavior? I wasn't able to find any issues logged for this, so I'm wondering if this is specific to me.

When running "$ lollypop -d" in the terminal, I did not see anything unexpected in the log. It shows the "Player::_on_stream_start():" event from me playing a song, immediately followed by "various/paths/to/mp3s detected as a music file" lines from me manually launching the music updater, and the way to the end of the log.

**Comment by cjsiglin** [comment]
I am running Fedora 22 and updating music does not disrupt playback.

**Comment by gnumdk** [comment]
Here it doesn't stop playback :-/

**Comment by gnumdk** [comment]
What distro?

**Comment by william-c-martin-iii** [comment]
Ok, so this really is a problem unique to me then. I'm on Arch. Perhaps this bug will be my excuse to finally get my hands into some Python code :smile:

**Comment by william-c-martin-iii** [comment]
I installed a barebones Arch setup under Virtual Box, enough for it to connect to the internet, install lollypop, and play sound. Under this setup, music play back is not affected when running the music updater. So this must be something specific to my system, rather than distro-related.

I will try reinstalling lollypop & any dependencies.

**Comment by william-c-martin-iii** [comment]
I also loaded my entire library in the Arch VM setup, and it still continues playing whilst updating. So that rules out something weird in my music library as the cause.

**Comment by william-c-martin-iii** [comment]
Reinstall of lollypop did not fix the issue. However, I noticed after uninstalling lollypop, all the meta/cache/db files were still around. On the second reinstall attempt, I removed those files as well, and then installed a fresh copy of lollypop, which forced it to rebuild the library from scratch. This time, the issue is fixed, and playback does not halt whilst updating.
