### ISSUE TITLE
Allow multiselection of Genres (or other list items like Albums)

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#410]
I've noticed there is no possibility to select multiple Genres nor it is possible to select multiple artists, to appear in the right list/album flow. Would be great if you would fix this. Especially usefull when you want to browse similar Genres at once or for shuffle-playing songs/albums of several picked Genres. This is easily done in Rhythmbox or iTunes with Ctrl+Click on n multiple list items. Thank you.

**Comment by gnumdk** [comment]
Looks like a good idea but hard to implement has what to do if user click Playlists and Rock?

**Comment by corebots** [comment]
The first 6 left-panel items(Popular, Recent, Playlists, ..., All Artists) could be 'immune' to a multiselection - clicking them with <ctrl> would prevent or cancel an attempt to select multiple list items. A multiselection would only be possible with regular list items like Genres, Artists...

**Comment by gnumdk** [comment]
Work in progress, will give you informations on how to test soon ;)
![capture du 2016-01-13 15-44-19](https://cloud.githubusercontent.com/assets/3918824/12297277/b3450f90-ba0c-11e5-84f8-1daadc7464ac.png)

**Comment by MadcapJake** [comment]
:+1: Can't wait to use this!

**Comment by gnumdk** [comment]
Merged.
Please test as current master is full of bugs :)

**Comment by corebots** [comment]
;) yes it works! thank you a bunch! I'll report if i run into issues.

**Comment by corebots** [comment]
well it seemed ok untill I've removed my database and started to populate the library from scratch; now i get:

$ lollypop 
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Player::restore_state(): track missing
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/container.py", line 350, in _add_artist
    if self._list_one.get_selected_id() in genre_ids:
AttributeError: 'SelectionList' object has no attribute 'get_selected_id'

*did work fine with v. 0.9.76 :/ now keeps crashing over and over when i try to re-update the library.

**Comment by gnumdk** [comment]
@corebots Should be fixed.

**Comment by corebots** [comment]
yess :) big thank you!!! 

just FYI, after a successful database update, lollypop still keeps notifying me: "additional codecs required - find in software" and in software no codecs are found. everytime the notification appears loollypop stops playback and i have to hit play again. just as I've mentioned in bug #269 (gstreamer1-libav-1.6.2-1.fc23.x86_64) but this is not a big deal. just so you know.

**Comment by corebots** [comment]
oh, I'm affraid i was too fast; lollypop has just crashed after I've clicked on an album. here the full terminal output:

$ lollypop 
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Player::restore_state(): track missing

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed
** Message: PackageKit: xid = 0
** Message: PackageKit: desktop_id = lollypop.desktop
** Message: PackageKit: Codec nice name: text/html decoder
** Message: PackageKit: structure: gstreamer1(decoder-text/html)()(64bit)
** Message: PackageKit: xid = 0
** Message: PackageKit: desktop_id = lollypop.desktop
** Message: PackageKit: Codec nice name: text/html decoder
** Message: PackageKit: structure: gstreamer1(decoder-text/html)()(64bit)

(lollypop:31912): GStreamer-CRITICAL **: gst_date_time_new: assertion '(month > 0 && month <= 12) || month == -1' failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/view.py", line 107, in _on_cover_changed
    widget.update_cover(album_id)
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album.py", line 59, in update_cover
    if self._cover is None:
AttributeError: 'AlbumSimpleWidget' object has no attribute '_cover'

**Comment by gnumdk** [comment]
Fixed while working on #422 ;)
