### ISSUE TITLE
Tracks deleted when synchronising playlists to Android over MTP

### ISSUE THREAD

**Issue by IxianPixel** [gnumdk/lollypop#412]
I originally thought it simply wasn't syncing because it appeared it didn't copy anything. After monitoring it closly, the required files are copied to the device, but once it's copied everything, it then deletes everything it just synced. 

I have a custom rom on my phone so I tried a Nexus 7 with stock Android and it does the same thing. Doesn't seem to matter what playlist you select to sync. I ran Lollypop in debug mode and it doesn't seem to complain about anything.

I'm running Arch Linux with Lollypop 0.9.75.

**Comment by gnumdk** [comment]
All sync or by playlist?

**Comment by IxianPixel** [comment]
Its by playlist. I don't really have the space on my phone to sync all albums. I can setup a test library if necessary.

**Comment by pcolby** [comment]
Just fyi, I appear to be having the same issue on Ubuntu 15.10 with Google Nexus 5.
