### ISSUE TITLE
Fast Forward Button

### ISSUE THREAD

**Issue by MichaelTiebesl** [gnumdk/lollypop#415]
Hi there, Can somebody explain me what i can do with the forward button?
When i click on it nothing happens.
I'm using Gnome - Arch (Lollypop - 0.9.75)

![lollypop](https://cloud.githubusercontent.com/assets/10792019/12219948/c2998ece-b793-11e5-9f53-a22462b79c95.png)

**Comment by MadcapJake** [comment]
That's for party mode, it changes the next track to be played.

**Comment by gnumdk** [comment]
Will remove it in random mode

**Comment by MichaelTiebesl** [comment]
Thanks

**Comment by gnumdk** [comment]
Here the button works also in shuffle mode.
