### ISSUE TITLE
MTP sync should have an option to convert music to lossy format before syncing

### ISSUE THREAD

**Issue by tuankiet65** [gnumdk/lollypop#418]
By far the sync feature is the thing I love most about Lollypop as I don't have to manually copy them to my phone anymore. But a problem is that most of my music is lossless, and lossless takes up a lot of space, which is a problem when syncing to my phone. If I remembered correctly, Windows Media Player allows you to convert your music file to a lossy and lighter format (MP3/WMA). I would like MTP sync to  convert my music to a lossy format (Vorbis/MP3…) before synching to my phone (obviously that would be an option to choose) so that it takes up less space than storing the lossless version.

**Comment by gnumdk** [comment]
Good idea? Someone to do the job? Should not be that hard:
- Add an option in sync view (may be time to rework view)
- Add  in sync_mtp.py near self._retry(src_track.copy ...) a condition with self._retry(convert_to_mp3)  and add a convert_to_mp3 function.

**Comment by tuankiet65** [comment]
This thing use GStreamer right? If so I might try it myself (disclaimer: don't expect anything :'( )

**Comment by tuankiet65** [comment]
This is weird (source file on the left, converted and synced file on the right, look at the time):
![screenshot from 2016-01-21 22-36-11](https://cloud.githubusercontent.com/assets/1905496/12484997/68fa0ca4-c08f-11e5-907d-de129651b56d.png)

The bitrate is not important though, although it says 31kbps it is still encoded with LAME Q4:
![screenshot from 2016-01-21 22-37-26](https://cloud.githubusercontent.com/assets/1905496/12485053/9314a3f0-c08f-11e5-8a85-f14e188705e3.png)

**Comment by gnumdk** [comment]
Here converting ogg -> mp3 works, files are not perfect (time slider jumping)...

**Comment by gnumdk** [comment]
Just play with this pipeline:
"filesrc location=plop.flac ! decodebin ! audioconvert ! lamemp3enc !id3v2mux !filesink location=plap.mp3"
http://docs.gstreamer.com/display/GstSDK/gst-launch
And check if you find a working one ;)

**Comment by tuankiet65** [comment]
gst-launch works unfortunately :'( I also tried building the pipeline manually in Python (direct call to Gst, not _convert_to_mp3 and it also works)
```
tuankiet65@ArchLinux:[/media/Entertainment/Shiki - Cristierra [FLAC] [CRTS0013-0014] (2010)/Disc 01][Thu Jan 21 11:26 PM]$ gst-launch-1.0 filesrc location="01. Angelic layer.flac" ! decodebin ! audioconvert ! lamemp3enc quality=0  ! id3v2mux ! filesink location="abc.mp3"Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:08.217198212
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
tuankiet65@ArchLinux:[/media/Entertainment/Shiki - Cristierra [FLAC] [CRTS0013-0014] (2010)/Disc 01][Thu Jan 21 11:26 PM]$ mpv abc.mp3
Playing: abc.mp3
[ffmpeg/demuxer] mp3: Estimating duration from bitrate, this may be inaccurate
 (+) Video --vid=1 [P] (mjpeg)
 (+) Audio --aid=1 (mp3)
File tags:
 Artist: SHIKI
 Album: Cristierra Disc 01
 Title: Angelic layer
 Track: 1/10
Displaying attached picture. Use --no-audio-display to prevent this.
AO: [pulse] 44100Hz stereo 2ch s16
VO: [opengl] 600x600 yuv444p
AV: 00:00:02 / 00:05:47 (0%) //should not be perfectly match, just roughly


Exiting... (Quit)
tuankiet65@ArchLinux:[/media/Entertainment/Shiki - Cristierra [FLAC] [CRTS0013-0014] (2010)/Disc 01][Thu Jan 21 11:26 PM]$ mpv 01*
Playing: 01. Angelic layer.flac
 (+) Video --vid=1 [P] (mjpeg)
 (+) Audio --aid=1 (flac)
File tags:
 Artist: SHIKI
 Album: Cristierra Disc 01
 Title: Angelic layer
 Track: 1
Displaying attached picture. Use --no-audio-display to prevent this.
AO: [pulse] 44100Hz stereo 2ch s16
VO: [opengl] 600x600 yuv444p
AV: 00:00:01 / 00:05:18 (0%)
```

I suspected that the wait for encoding to finish part is buggy so I poked around for a while but to no avail.

**Comment by gnumdk** [comment]
Ok, will look at this.

**Comment by gnumdk** [comment]
Bad, here my gstreamer doesn't want to decode flac :-(
$ LANG=C gst-launch-1.0 filesrc location="test.flac" ! decodebin ! audioconvert ! lamemp3enc quality=0  ! id3v2mux ! filesink location="abc.mp3"
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstFlacParse:flacparse0: GStreamer encountered a general stream error.
Additional debug info:
gstbaseparse.c(3457): gst_base_parse_loop (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstFlacParse:flacparse0:
streaming stopped, reason not-negotiated
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by tuankiet65** [comment]
I suspected that this part is wrong:
```python
status = Gst.State.PLAYING
while status == Gst.State.PLAYING:
    status = pipeline.get_state(Gst.CLOCK_TIME_NONE)
    sleep(1)
```
as pipeline.get_state() return value is not GstState but is actually a tuple of multiple GstState:
```
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gst
sys:1: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
>>> Gst.init(None)
[]
>>> pipe=Gst.parse_launch('filesrc location="01. Angelic layer.flac" ! decodebin ! audioconvert ! lamemp3enc quality=0  ! id3v2mux ! filesink location="abc.mp3"')
>>> pipe
<Pipeline object at 0x7fc221451948 (GstPipeline at 0x1d32150)>
>>> pipe.set_state(Gst.State.PLAYING)
<enum GST_STATE_CHANGE_ASYNC of type GstStateChangeReturn>
>>> pipe.get_state(Gst.CLOCK_TIME_NONE)
(<enum GST_STATE_CHANGE_SUCCESS of type GstStateChangeReturn>, <enum GST_STATE_PLAYING of type GstState>, <enum GST_STATE_VOID_PENDING of type GstState>)
>>> Gst.State.PLAYING==pipe.get_state(Gst.CLOCK_TIME_NONE)
False
```
So I think that the current execution flow is like this:
* Pipeline is created and state set to PLAYING
* As status == Gst.State.PLAYING is False, no wait will be executed, Lollypop will copy the incomplete MP3 file to the device instead

**Comment by gnumdk** [comment]
Should be better, just need to close pipeline I think.

**Comment by gnumdk** [comment]
Is it working?

**Comment by tuankiet65** [comment]
The converted MP3s are correct and playing normally now,  but I got trouble
with MTP "could not send object"

**Comment by gnumdk** [comment]
>MTP "could not send object"

Happen when you try to reupload a previously deleted file. Happen with nautilus too...

**Comment by tuankiet65** [comment]
libmtp sucks I think?
