### ISSUE TITLE
Can we get cross fading?

### ISSUE THREAD

**Issue by superscript18** [gnumdk/lollypop#419]
There are some of my playlists that I really like to play with crossfading.  Is adding that as an option somewhere on your Lollypop roadmap?  Would a PR be appreciated?

Thanks and keep up the good work!

**Comment by bil-elmoussaoui** [comment]
+1

**Comment by gnumdk** [comment]
PR ?

**Comment by superscript18** [comment]
@gnumdk PR is still coming.  Just wanted to make sure it would be a welcome addition first. :-)

**Comment by gnumdk** [comment]
@superscript18 I don't understand PR ;)

**Comment by alexskc** [comment]
Pull Request, I think.

**Comment by gnumdk** [comment]
Ok for a Pull Request ;)

But keep in mind that this should not break "gapless playing" or I will reject the request.

**Comment by gnumdk** [comment]
You can add an option to enable crossfading (Mix tracks may be a good string) in UI.

Use good defaults for fading and an option in dconf but nothing in UI.

**Comment by gnumdk** [comment]
Any news on this ? Some code visible on github? :) I'm doing some tests on my side...

**Comment by gnumdk** [comment]
https://github.com/mopidy/mopidy/issues/450#issuecomment-17884071

**Comment by gnumdk** [comment]
Going to close this one with my workaround, seems to be working, testers are welcome.

**Comment by superscript18** [comment]
Awesome, man!  Gotta <3 active open source projects!
