### ISSUE TITLE
OpenSuse Package missing dep

### ISSUE THREAD

**Issue by nerbrume** [gnumdk/lollypop#42]
Hello,

Not sure this issue belongs to here, but the package for openSuse 13.2 available at : https://build.opensuse.org/package/show?project=home%3Agnumdk31&package=lollypop
is missing a dependency to python3-cairo (I had to install python3-cairo "by hand").
After that, everything seems to be running fine.

**Comment by gnumdk** [comment]
Fixed, thanks ;)
