### ISSUE TITLE
Use GOA/POA

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#420]
Gnome online accounts now ships an api for Last.Fm the same as for Pantheon online accounts;
It's would be good to manage my online accounts in one place 
https://bugzilla.gnome.org/show_bug.cgi?id=728621
Gnome musics have implemented the new API for the 3.20 release! 
Thanks

**Comment by gnumdk** [comment]
Where is the API?
Seems to be an auth API, lollypop needs full lastfm API.

**Comment by bil-elmoussaoui** [comment]
Sorry, i meant an auth API

**Comment by gnumdk** [comment]
Ok, pylast accept an auth token so should work. https://groups.google.com/forum/#!topic/pylast/8jr36NXi6gs

You will have to wait GNOME 3.20 to be out as I do not have this API on my system ;)

**Comment by gnumdk** [comment]
Working in git ;)
