### ISSUE TITLE
Any plans on integrating streaming services?

### ISSUE THREAD

**Issue by stunningpotato** [gnumdk/lollypop#421]
As far as I know Spotify, Deezer etc. all provide an API for non-official clients.

Because the official clients tend to be not as good, having them integrated in Lollypop would be a really cool feature...

**Comment by gnumdk** [comment]
No, use a dedicated client. Out of lollypop scope.

**Comment by gnumdk** [comment]
No, use a dedicated client. Out of lollypop scope.

**Comment by nmschulte-aviture** [comment]
@gnumdk, would you mind clarifying the scope of lollypop then?  As an outsider glancing at the project, my thoughts were: if this integrates with e.g. Spotify, then I'm sold.  Google's Play Music, with the ability to upload your own content and seamlessly manipulate it and streaming content alike, is the feature I'm after.

TOMAHAWK looks interesting, but then I wonder what Lollypop's goals are to begin with.

Thanks!

**Comment by gnumdk** [comment]
Scope: Local music playback

**Comment by gnumdk** [comment]
On more arg, Tomahawk use a deprecated API to play songs and will stop working soon... Don't have time to do "reverse engenering" on Java Android API.

**Comment by nmschulte-aviture** [comment]
I assume you meant "one more arg"?  I'm not looking to debate anything, if that's so.  That's sad news for TOMAHAWK, if I understand you correctly.  Basically, you're telling us there won't be a good solution to our need soon; not in Lollypop for sure, and not in TOMAHAWK.

Thanks for the reply; much appreciated.

**Comment by AndydeCleyre** [comment]
@nmschulte-aviture and @stunningpotato You may want to check out [Clementine](https://github.com/clementine-player/Clementine) and the whole [Mopidy](https://www.mopidy.com/) universe.
