### ISSUE TITLE
Non-square album artwork is stretched.

### ISSUE THREAD

**Issue by alexskc** [gnumdk/lollypop#422]
This can look very awkward on albums that came in a DVD-shaped case, for example.
![awkward](https://cloud.githubusercontent.com/assets/6933425/12379430/c469fa32-bd5a-11e5-9ebb-8a75c7992000.png)

For comparison, this is what the same artwork looks like in gnome-music:
![volumes](https://cloud.githubusercontent.com/assets/6933425/12379428/b8f43924-bd5a-11e5-8ab6-1945ebc64b82.png)

**Comment by gnumdk** [comment]
Will fix this as a disabled option as here it breaks all my covers (not really square due to bad scanning)

**Comment by gnumdk** [comment]
You need to clean cache (update db)
