### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by animosa** [gnumdk/lollypop#425]
Issue:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/container.py", line 687, in _on_list_one_selected
    if selected_ids[0] == Type.PLAYLISTS:
IndexError: list index out of range

Reproducing:

Start lollypop, instantly start typing a search; before it updates indices, it throws this error then crashes.

Version: 0.9.80

This is not present in version 0.9.75 using,

    def _on_list_one_selected(self, selection_list, selected_id):
        """
            Update view based on selected object
            @param list as SelectionList
            @param selected id as int
        """
        if selected_id == Type.PLAYLISTS:
            self._list_two.clear()
            self._list_two.show()
            if not self._list_two.will_be_selected():
                self._update_view_playlists(None)
            self._setup_list_playlists(False)
        elif Type.DEVICES - 999 < selected_id < Type.DEVICES:
            self._list_two.hide()
            if not self._list_two.will_be_selected():
                self._update_view_device(selected_id)
        elif selected_id in [Type.POPULARS,
                             Type.RECENTS,
                             Type.RANDOMS]:
            self._list_two.hide()
            self._update_view_albums(selected_id)
        elif selected_id == Type.RADIOS:
            self._list_two.hide()
            self._update_view_radios()
        elif selection_list.is_marked_as_artists():
            self._list_two.hide()
            if selected_id == Type.ALL:
                self._update_view_albums(selected_id)
            elif selected_id == Type.COMPILATIONS:
                self._update_view_albums(None, True)
            else:
                self._update_view_artists(selected_id, None)
        else:
            self._list_two.clear()
            self._setup_list_artists(self._list_two, selected_id, False)
            self._list_two.show()
            if not self._list_two.will_be_selected():
                self._update_view_albums(selected_id, False)

However, it does raise the assertions.

**Comment by animosa** [comment]
Sorry, I didn't realize the difference between stable and master. Closing!

**Comment by gnumdk** [comment]
You can report bugs for master ;) 
#410
