### ISSUE TITLE
song duplicates

### ISSUE THREAD

**Issue by sevachka** [gnumdk/lollypop#426]
Hello,
all of sudden I got song duplicates in every album. Happend after a Music-Library update. I tried to re-update the library, I have re-installed the application, deleted all the DB-files... still it is indexing every song twice...

**Comment by sevachka** [comment]
never mind...after three library updates all of sudden it was back to normal... sorry! And again: THANK YOU for this music player. Love it! Where is the paypal-beer-button? :+1:

**Comment by gnumdk** [comment]
A paypal beer button, it's an idea ;)

**Comment by gnumdk** [comment]
https://www.paypal.me/lollypopgnome

**Comment by gnumdk** [comment]
Added in bottom ;) http://gnumdk.github.io/lollypop-web/

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/commit/59a4ff7f87d7005aac707a3b2a38aa7d780f3038

**Comment by sevachka** [comment]
ah, sorry. Didn´t realize you answered to this thread. Beer was just drafted! ;)
