### ISSUE TITLE
Compile error: syntax error near unexpected token `disable-static

### ISSUE THREAD

**Issue by blade1989** [gnumdk/lollypop#428]
When running `./autogen.sh`, I get the following error:

    checking whether gcc understands -c and -o together... (cached) yes
    checking dependency style of gcc... (cached) none
    ./configure: line 5430: syntax error near unexpected token `disable-static'
    ./configure: line 5430: `LT_INIT(disable-static)'
    + exit 1

**Comment by gnumdk** [comment]
Please ask on your distribution forum...

BTW, what distro?

**Comment by blade1989** [comment]
Ubuntu - 14.04 - Trusty Tahr

**Comment by gnumdk** [comment]
Not compatible. Wait for next LTS

**Comment by coconutlulz** [comment]
This occurs on Debian unstable (completely up-to-date).

`checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) none
./configure: line 5445: syntax error near unexpected token `disable-static'
./configure: line 5445: `LT_INIT(disable-static)'
+ exit 1`

Linux 4.3.0-1-amd64 #1 SMP Debian 4.3.3-5 (2016-01-04) x86_64 GNU/Linux
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.15

**Comment by gnumdk** [comment]
#apt-get build-dep lollypop
