### ISSUE TITLE
Tags issue

### ISSUE THREAD

**Issue by zes** [gnumdk/lollypop#429]
Hi,

When I import all my mp3s in Lollypop I notice something ; for example : 

there is an audio track which appears in Drum'n'Bass and Drum & Bass genres ; I check the mp3 tags with ExFalso & Kid3 and the tags seems proper : no multi genres and no v1 tags (I don't understand where this Drum & Bass tag is !!!)

Anyone have the same problem ?

Thanks

**Comment by animosa** [comment]
Inconsistencies in v2 tags is where you need to look; that's where it can be sorted incorrectly. What I usually do is remove the v2 tags, then click copy 'from tag 1' again so it eliminates all the extra junk. I have noticed sometimes with the date being  2007 in one album track, and null in another, it will sort them in seperate albums. Maybe adding specific checks for &, 'n', capitalization, etc could be beneficial.

**Comment by gnumdk** [comment]
Try with puddletag

**Comment by zes** [comment]
Found it : 

there are APEv2 tags on the mp3 files ;)
I removed them with puddle tag.

Thank you.
