### ISSUE TITLE
Crash when trying to play a large album

### ISSUE THREAD

**Issue by hospx** [gnumdk/lollypop#43]
Hi
First, thanks for lollypop, it's a great replacement of gnome-music.
Since the 0.9 version, I'am unable to read a large album (~ 500 songs). When I try to, it crashes with this error in the terminal : 
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/view_widgets.py", line 224, in _on_activated
    self._limit_to_artist)
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 397, in set_albums
    self._context.position = tracks.index(track_id)
ValueError: 12112 is not in list
```
With the previous versions of lollypop, I never had this issue.

**Comment by gnumdk** [comment]
Please send me ~/.local/share/lollypop/lollypop.db by mail... (About dialog for my email)

**Comment by gnumdk** [comment]
In fact, i think i understand what the bug is :)

**Comment by gnumdk** [comment]
I'm quite sure in the view, you have more tracks than the album really have. So, the player crash... Should be fixed in git, can you test?

**Comment by hospx** [comment]
It works with the git vesion, thanks !
