### ISSUE TITLE
[enhancement] playlist tag

### ISSUE THREAD

**Issue by zes** [gnumdk/lollypop#430]
Hi,

it will be cool if we can make playlist folders for better playlist organization.

Thx.

**Comment by gnumdk** [comment]
I rename this as I do not want folders ;)

**Comment by gnumdk** [comment]
After some reflection, I don't want a folder view.

So, maybe allow you to add playlists to a group and group them in the view (with separators) ?

**Comment by zes** [comment]
I don't understand "group them in the view".
But the "group" idea seems to be good.

**Comment by gnumdk** [comment]
-------------------
Playlist1                           => group1
Playlist4
Playlist9
--------------------
Playlist2                           => group2
Playlist11
--------------------
Playlist0                           => group3

**Comment by gnumdk** [comment]
For my understanding, what is the issue you have with current flat view?

**Comment by zes** [comment]
I listen a lot of music and I need a playlist for each week of each years : 

2015
 -> W01
 -> W02
 ...
 -> W52
------------------------------
2014
 -> W01
 -> W02
 ...
 -> W52

With the current view I have to do a lot of scrolling :P 
So, if I understand, your group view (with separator) will not fix my problem.

**Comment by gnumdk** [comment]
Maybe Lollypop isn't the good tool. I build it around this main need: "Stop creating playlist just for playback because it was a waste of time for me in my previous player: Amarok".

**Comment by gnumdk** [comment]
Will add a tagging feature and a way to filter by tags.

**Comment by gnumdk** [comment]
And why do you not name playlist like:
- 2015-W01
- 2015-W02
And just use the "Type ahead" feature?

I tried adding filtering but IMO it bloat the UI.

**Comment by animosa** [comment]
Could just turn party mode on.  Why new playlist for everyday? Bit excessive..

**Comment by zes** [comment]
Hi,

yes indeed, the "type ahead" can make the job ; I didn't notice that feature. Additionally, no need to code.
But, maybe, a feature to order playlist in descending order or order them as we want in the flat view.

@animosa : yes, a playlist for everyday will be excessive and party mode is a random play.

Anyway, I can understand that the playlist feature is not the main objective and need of Lollypop. I just report you features I would be able to use.

And thank you for your disponibility and your software.
