### ISSUE TITLE
Slow window wake-up clicking on notification

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#433]
When clicking on GNOME notification about Lollypop changing song, it make lag my computer during a while before display lollypop. This happen, with lollypop playing music with a closed window.

**Comment by gnumdk** [comment]
What distro? Don't happen here on ArchLinux.

**Comment by M5oul** [comment]
On Fedora 23.

**Comment by gnumdk** [comment]
I think it's an issue with your Gnome Shell (of Fedora one).

Run dbus-monitor to see what is happening on click.

**Comment by gnumdk** [comment]
Working as expected on Ubuntu too.

**Comment by gnumdk** [comment]
Ping?

**Comment by M5oul** [comment]
I does not happen anymore with 0.9.86.
