### ISSUE TITLE
Shortcut window

### ISSUE THREAD

**Issue by julianrichen** [gnumdk/lollypop#435]
GNOME is starting to implement a shorcut window, here is an example in GNOME builder:
![](http://i.imgur.com/cJi5eUe.png)
![](http://i.imgur.com/HfcwVFh.png)

It would be nice if Lollypop also supported this, I can't seem to find the documentation page on it.

It also might not be available until 3.20.

**Comment by julianrichen** [comment]
The shortcut window is actually called "Help Overlay", or it's the tentative name. I was browsing some other docs that linked to this page:
https://wiki.gnome.org/Design/OS/HelpOverlay

An an example they provide is the builder ui:
https://git.gnome.org/browse/gnome-builder/tree/data/ui/ide-shortcuts-window.ui

**Comment by bil-elmoussaoui** [comment]
Any news on this? :+1:

**Comment by gnumdk** [comment]
Need to take some time on this by looking at Gnome Music code. After 0.9.99 ;)

**Comment by gnumdk** [comment]
Ok, not Gnome Music as Gnome Music 3.20 seems exactly the same as 3.18

**Comment by julianrichen** [comment]
I think that was the only core GNOME software not shipped with the shortcut window, here is a list of them:
https://youtu.be/JU2f_jkPRq4?t=59s

**Comment by gnumdk** [comment]
Do you know a python app with this? :) Will save my time...

**Comment by julianrichen** [comment]
I assumed gnome-videos and gnome-calendar would be python but I guess I'm wrong.

I don't know if they have the shortcut window but these are python:
https://github.com/GNOME/gnome-tweak-tool
https://github.com/GNOME/pitivi

I would check but I'm not on my gnome machine.

**Comment by gnumdk** [comment]
No, dont do, they do not have shortcut window ;)

**Comment by gnumdk** [comment]
Will dig into Gnome Builder C code...

**Comment by gnunn1** [comment]
I've done this in terminix, all it involves is creating a glade ui file and loading it with Builder. Unfortunately I don't think Glade supports the new Shortcut widgets so it requires creating it by hand, at least that's the way I did it.

**Comment by gnumdk** [comment]
@gnunn1 Thanks for info, will give a look ;)

**Comment by julianrichen** [comment]
@gnumdk Thank you for implementing the shortcut window, I'm glade your figured it out :)

I did notice that window does not center relative to lollypop's main window:
![Not centered](http://i.imgur.com/gIzcwcr.png)

I'm not sure how it's getting that window position because it's not centered to the monitor either. It also seems to be acting as a independent window (I can move it around) but I can't click on any of areas of lollypop till I close it. Normally with that behavior it also darkens the the main window to indicate you need to close the shortcut window first.

**Comment by blackjackshellac** [comment]
When I click on "Keyboard Shortcuts" I'm getting the help window, not this nice shortcuts window.  this is on master.  Is this dependent on the next gtk version?

**Comment by gnumdk** [comment]
@blackjackshellac Because you need GTK 3.20

**Comment by gnumdk** [comment]
@julianrichen Fixed... But looks bad as it's placed after showed here :-( Happend with others GNOME apps too...

**Comment by gnumdk** [comment]
>Also should the shortcut section be removed from the Help window?
No as GTK < 3.20 needs shorctuts section in help.
