### ISSUE TITLE
No window snapping

### ISSUE THREAD

**Issue by julianrichen** [gnumdk/lollypop#436]
I'm not sure if this is intentional but I did not see any bug reports about it. I can't seem to snap the Lollypop window, here is a video of the issue:
https://www.youtube.com/watch?v=AVg0ZmaTqzg

Minimize & Maximize work.

Distro: Debian Sid
Gnome: 3.18
Lollypop: Latest master (7bf2ae8)

**Comment by gnumdk** [comment]
Fix by https://github.com/gnumdk/lollypop/commit/bd9dc44da73062c4cd8b6c056b987af8291859ac

**Comment by gnumdk** [comment]
I revert back this one as it's buggy... And not really a bug as this problem exist in:
- Gnome Boxes
- Gnome Music
- Geary
- ...

**Comment by julianrichen** [comment]
That's a shame, hopefully they fix the buggy nature upstream

Thank you for looking into it.

**Comment by gnumdk** [comment]
The issue in more in snapping... If toolbar content is > than screen/2, it fails...

**Comment by julianrichen** [comment]
Oh, I see.

Would it be possible to fix that by hiding the buttons on the right in a sub button, like a hamburger menu if space does not exists? Or would it break the design to much in your opinion?

Would you also consider adding snapping back when GNOME adds resizable snapping windows?

If not I understand, I just like the option.

**Comment by gnumdk** [comment]
Finnaly, it's fixed! :)
Will not work on screens with width < 1400
