### ISSUE TITLE
Expanding cover art in GNOME panel breaks text

### ISSUE THREAD

**Issue by julianrichen** [gnumdk/lollypop#437]
In the GNOME panel if you click the cover art of the currently playing song it expands to ~80% the width of the panel and breaks the text.

![](http://i.imgur.com/owBOztE.png)

It might be better to expand the cover art to 100% and hide the text, or move the text below the cover art.

Distro: Debian Sid
Gnome: 3.18
Lollypop: Latest master (7bf2ae8)

**Comment by gnumdk** [comment]
Not lollypop, report to extension author.
