### ISSUE TITLE
Custom plugins

### ISSUE THREAD

**Issue by KeizerDev** [gnumdk/lollypop#439]
I've created a plugin I'm using like everyday for Rhytmbox to just stream everysong from the internet using some music sources. You can find it here, https://github.com/KeizerDev/Rhythmbox-Pleer. 

Now, I finally want to switch from music player but is it possible to create plugins for it? If so it would be the most coolest music player ever! :smiley:

**Comment by gnumdk** [comment]
Lollypop doesn't support plugins and isn't designed for cloud playback.

**Comment by gnumdk** [comment]
One more:
The use of the service for downloading programs which receive links to files without the user visiting the download page is prohibited.
