### ISSUE TITLE
wrong SettingsDialog

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#440]
lollypop-0.9.81
"Appearance" --> "Configure lollypop behaviour" ???
![2016-02-02 22-07-04](https://cloud.githubusercontent.com/assets/13280183/12760828/6e87d642-c9f9-11e5-879a-934fb6339093.png)

and no Popover "Behaviour" and Last.fm
![2016-02-02 22-07-23](https://cloud.githubusercontent.com/assets/13280183/12760920/efe395f0-c9f9-11e5-8141-39bc6a6b6516.png)

Sorry for my bad English

**Comment by gnumdk** [comment]
Here it works :-(

**Comment by region51** [comment]
tab "Appearance" wrong Popover 
tab "Behaviour" no Popover but must be "Behaviour"="Configure lollypop behaviour"

**Comment by gnumdk** [comment]
Ok, tooltip, not popover :)
