### ISSUE TITLE
sort artist

### ISSUE THREAD

**Issue by MichaelTiebesl** [gnumdk/lollypop#441]
Is it possible to have the artist sorted with starting The?
I saw already the suggestion to have the artist not sorted with The.
See #3 

Like The Beatles show up as The Beatles and not Beatles The?

Thanks

**Comment by gnumdk** [comment]
What are the tags?

**Comment by MichaelTiebesl** [comment]
I tag my music with Picard from MusicBrainz. I have ogg files with Vobis tags (ID3v2 version 2.4)

**Comment by gnumdk** [comment]
Show me the tags...

**Comment by MichaelTiebesl** [comment]
In which way i can show my tags in a proper way as you want? Is it just a copy how it shows in Picard?

**Comment by gnumdk** [comment]
Yes

**Comment by MichaelTiebesl** [comment]
These fields are what i tag in Picard:

![picard](https://cloud.githubusercontent.com/assets/10792019/12814562/d4c0a42a-cb7a-11e5-967d-942ec9dfe9cd.png)

**Comment by gnumdk** [comment]
I need the values.

**Comment by julianrichen** [comment]
@MichaelTiebesl you can use `ogginfo` to get the raw tag data about your ogg files. Should be under a section that say user defined info.

`id3v2` for mp3
`flac` for flac

**Comment by MichaelTiebesl** [comment]
I hope this is better:

![schermafdruk van 2016-02-05 06-29-34](https://cloud.githubusercontent.com/assets/10792019/12831952/142e8166-cbd2-11e5-8531-450b85278cbf.png)

@julianrichen sorry couldn't found what you mention

**Comment by gnumdk** [comment]
Why 2PAC? we are talking about beatles, the...

**Comment by animosa** [comment]
In my playlist, mine shows up as the The Beatles. Also have The B Foundation, The Black Keys, The Black Angels, all proper.

**Comment by MichaelTiebesl** [comment]
Here is The Beatles

![schermafdruk van 2016-02-06 05-57-32](https://cloud.githubusercontent.com/assets/10792019/12860410/4aefaf2a-cc97-11e5-88cb-f92115ee3431.png)

**Comment by gnumdk** [comment]
So issue is having "The Beatle" ordered in "B" artists?

**Comment by MichaelTiebesl** [comment]
Yes i have that.

![schermafdruk van 2016-02-07 05-26-17](https://cloud.githubusercontent.com/assets/10792019/12869472/b4748082-cd5b-11e5-9794-b38c584ff228.png)

**Comment by gnumdk** [comment]
Yes, it's a wanted feature, lollypop forces this behaviour for people with badly tagged music.
As a workaround, you can add a "Sort artist name" with "Beatles, The".

**Comment by gnumdk** [comment]
http://musicbrainz.org/doc/Style/Artist/Sort_Name

**Comment by MichaelTiebesl** [comment]
I don't get it with the workaround. If i add a sort name tag then The Beatles still shows up in the B section as what i have show above. So if i add a sort name nothing will change for me.  Anyway thanks for your time. I see it is not in my hands to make The Beatles shows up in the T section.

**Comment by gnumdk** [comment]
Ok, so there is a bug.

**Comment by gnumdk** [comment]
Here it work:
![capture du 2016-02-07 19-03-59](https://cloud.githubusercontent.com/assets/3918824/12874121/d6876618-cdcd-11e5-8890-9ddb6040616e.png)

**Comment by gnumdk** [comment]
But removing the sortorder tag doesn't works :-(

**Comment by gnumdk** [comment]
Puddletag example:
![capture du 2016-02-07 19-13-20](https://cloud.githubusercontent.com/assets/3918824/12874172/d6767aaa-cdce-11e5-87b2-44b289130f7f.png)

**Comment by gnumdk** [comment]
Close this
