### ISSUE TITLE
Many artists "Unknown" after first run

### ISSUE THREAD

**Issue by mjog** [gnumdk/lollypop#442]
I just ran Lollypop for the first time and many tracks were imported under artist "Unknown" in the side bar, even though the tracks are tagged with an artist and Lollypop shows the correct artist name for the track listings for such albums.

I didn't use the RB importer.

**Comment by gnumdk** [comment]
It's a bug, will be fixed today with 0.9.83:https://github.com/gnumdk/lollypop/commit/516e0722f5473b6cda36d518dccbbb61c9571cba

**Comment by gnumdk** [comment]
You will need to do this:
$ rm -f ~/.local/share/lollypop/lollypop.db

**Comment by gnumdk** [comment]
Released!

**Comment by mjog** [comment]
Fixed! Thanks!
