### ISSUE TITLE
Warnings while storing an album cover if a folder is read-only

### ISSUE THREAD

**Issue by hipnoizz** [gnumdk/lollypop#444]
My music folder is a read-only mounted network share. When clicking on some album Lollypop produces hundreds of warnings like this:

```
ArtDownloader::_get_album_art_spotify: g-io-error-quark: Błąd HTTP: Gone (0)
Art::save_album_artwork(): g-file-error-quark: Failed to open '/home/hipnoizz/Muzyka/Aesop Rock/(2001) Labor Days/cover.jpg' for writing: System plików wyłącznie do odczytu (8)
```

Usually it ends in a segmentation fault. 'System plików wyłącznie do odczytu' means 'file system is read only'.

It would be better to store covers in ~/.cache/lollypop or something like that. I'm not sure where Banshee or Totem store covers.

Lollypop 0.9.82 on Ubuntu 15.10.

**Comment by hipnoizz** [comment]
Additional info below.

a) When starting the app lollypop displays on console:
```
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Namespace WebKit2 not available
WebKit support disabled
```
b) Segmentation fault occurs on application close. I mean that Lollypop does not crash by itself but closing a window usually produces a fault.

**Comment by gnumdk** [comment]
Lollypop already store covers in cache. But by default, it store original size covers in album folder.

Not an issue here. Just warnings. Segfault is in Python/Gio.

**Comment by hipnoizz** [comment]
Two things.

a) No cover is set automatically nor I can't choose a cover when right-clicking on an album. I can see some images presented but clicking on one does set it as an album cover. I looked in ~/.cache/lollypop and it contains only some symbolic JPGs and few radio logos.
b) Lollypop produces 5-10 such warnings per second when run from terminal. It's a bit excessive...

**Comment by gnumdk** [comment]
Having re access is needed if you want lollypop to works. What is your setup? Google music fuse ?

**Comment by hipnoizz** [comment]
It's a read-only mounted via sshfs folder from my local server. It took a lot of time to rip all those CDs so the folder is protected from accidental modification. Be it my mistake or an error in whatever music player I use. I haven't had any issues with such setup while using Rhythmbox, Banshee, Kodi or Foobar. I'm a bit surprised that Lollypop requires a write access to my music collection, it that's the case...

**Comment by hipnoizz** [comment]
It also appears that above warnings makes Lollypop leak memory. Below is dump from top command:

```
                       VIRT     RES    SHR
32470 hipnoizz  20   0 1238160  74220  42552 S   0,3  0,9   0:01.05 lollypop (1)                                                                           
32470 hipnoizz  20   0 1238292  74220  42552 S   3,3  0,9   0:01.15 lollypop                                                                           
32470 hipnoizz  20   0 1238292  74220  42552 S   6,0  0,9   0:01.33 lollypop                                                                           
32470 hipnoizz  20   0 1238292  74220  42552 S   0,3  0,9   0:01.34 lollypop                                                                           
32470 hipnoizz  20   0 1238292  74220  42552 S   4,0  0,9   0:01.46 lollypop                                                                           
32470 hipnoizz  20   0 1238292  74220  42552 S   6,0  0,9   0:01.64 lollypop                                                                           
32470 hipnoizz  20   0 1247696  76236  42772 S  20,3  0,9   0:02.25 lollypop (2)                                                                           
32470 hipnoizz  20   0 1247696  76944  42768 S  25,6  0,9   0:03.02 lollypop                                                                           
32470 hipnoizz  20   0 1247696  77712  42768 S  15,9  1,0   0:03.50 lollypop                                                                           
32470 hipnoizz  20   0 1247696  78352  42768 S  14,6  1,0   0:03.94 lollypop                                                                           
32470 hipnoizz  20   0 1247696  79316  42768 S  16,6  1,0   0:04.44 lollypop                                                                           
32470 hipnoizz  20   0 1247696  80084  42768 S  18,6  1,0   0:05.00 lollypop                                                                           
32470 hipnoizz  20   0 1247696  80792  42768 S  16,3  1,0   0:05.49 lollypop                                                                           
32470 hipnoizz  20   0 1247696  81496  42768 S  15,6  1,0   0:05.96 lollypop                                                                           
32470 hipnoizz  20   0 1247696  82200  42768 R  15,3  1,0   0:06.42 lollypop                                                                           
32470 hipnoizz  20   0 1247696  82840  42768 S  14,9  1,0   0:06.87 lollypop                                                                           
32470 hipnoizz  20   0 1247696  83480  42768 S  13,9  1,0   0:07.29 lollypop                                                                           
32470 hipnoizz  20   0 1247696  84184  42768 S  13,6  1,0   0:07.70 lollypop                                                                           
32470 hipnoizz  20   0 1247696  85088  42768 S  14,9  1,0   0:08.15 lollypop                                                                           
32470 hipnoizz  20   0 1247696  85856  42768 R  17,3  1,1   0:08.67 lollypop                                                                           
32470 hipnoizz  20   0 1247696  86520  42768 S  14,6  1,1   0:09.11 lollypop                                                                           
32470 hipnoizz  20   0 1247696  87160  42768 S  14,3  1,1   0:09.54 lollypop                                                                           
32470 hipnoizz  20   0 1247696  89384  42928 S  29,9  1,1   0:10.44 lollypop                                                                           
32470 hipnoizz  20   0 1247696  88524  42932 S   9,6  1,1   0:10.73 lollypop (3)                                                                          
32470 hipnoizz  20   0 1239500  88508  42932 S   0,3  1,1   0:10.74 lollypop                                                                           
32470 hipnoizz  20   0 1239500  88508  42932 S   0,3  1,1   0:10.75 lollypop 
```

(1) 'Compilation' element is selected in the sidebar. RES stays more or less constant.
(2) Some artist is selected in the sidebar. RES starts growing. Lollypop spits warning as below 5-10 times per second.
```
ArtDownloader::_get_album_art_spotify: g-io-error-quark: Błąd HTTP: Gone (0)
Art::save_album_artwork(): g-file-error-quark: Failed to open '/home/hipnoizz/Muzyka/His Hero Is Gone/(1997) Monuments to Thieves/cover.jpg' for writing: System plików wyłącznie do odczytu (8)
```
(3) 'Compilation' element is selected again. RES stops growing.

I know that measuring a process memory usage is a tricky business. Still, yesterday evening I noticed my browser killing its tabs and when I looked at Lollypop it managed to allocate 4-5 GB of memory. I think that a burn rate is about 10-15 MB/s...

Additional note: Playing music isn't needed to observe above memory leaks.

Tested under 0.9.83.

**Comment by hipnoizz** [comment]
And when above warning is produced and I click on 'Radio' element in the sidebar Lollypop crashes:
```
ArtDownloader::_get_album_art_spotify: g-io-error-quark: Błąd HTTP: Gone (0)
Art::save_album_artwork(): g-file-error-quark: Failed to open '/home/hipnoizz/Muzyka/Dazzling Killmen/(1994) Face of Collapse/cover.jpg' for writing: System plików wyłącznie do odczytu (8)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/view.py", line 108, in _on_cover_changed
    widget.update_cover(album_id)
TypeError: update_cover() takes 1 positional argument but 2 were given
[1]    2192 segmentation fault (core dumped)  lollypop
```
I have one radio added to favourites. If there are no favourites then Lollypop doesn't crash.

**Comment by hipnoizz** [comment]
Ping?

Are you willing to support read-only music folders? Should I separate those three problems (a) excessive cover downloading and console flooding, b) memory leaks, c) crash when switching to radio) to distinct issues?

**Comment by hipnoizz** [comment]
@gnumdk Ping again.

a) Tested latest version and memory leaks are still present.
b) Are you willing to support read-only music folders in regards to album arts?

**Comment by gnumdk** [comment]
@hipnoizz Your issue is fixed in git.

**Comment by gnumdk** [comment]
Funny issue number: 444 for readonly ;)

**Comment by blackjackshellac** [comment]
Awesome coincidence, it must be destiny :)

Here's the kind of reason why I share my music 444 chez nous,

[apple-stole-my-music-no-seriously](https://blog.vellumatlanta.com/2016/05/04/apple-stole-my-music-no-seriously/)

Obviously the comment is not meant to apply to your fine music player, but sh*t happens and 
I like to control adding, removing and tagging on a read-write share because I have Lus3rs (kids, girlfriend, etc) that I want to prevent from damaging the audio data files.

Just my $0.02 worth.

**Comment by hipnoizz** [comment]
Awesome, thx. Tested 104 and it looks great - covers are downloaded and it seems that memory leaks disappeared.
