### ISSUE TITLE
Overlay 'Play' icon on album

### ISSUE THREAD

**Issue by hipnoizz** [gnumdk/lollypop#445]
It would be good to add some better visual cue that clicking an album icon (cover) starts playing songs from this album. My proposal would be a big overlay 'Play' icon on mouse over.

**Comment by bil-elmoussaoui** [comment]
+1

**Comment by gnumdk** [comment]
Will readd hand mouse cursor (was here in previous releases). I really dislike ugly overlay like in some media players ;)

**Comment by hipnoizz** [comment]
Arhhg, I wholeheartedly disagree (about overlay icon) ;-). But it's your child and I like it a lot anyway. Thx.

**Comment by gnumdk** [comment]
Was wrong, this will only appear if option is enabled, will add this.

And this will come with a new cool feature.
