### ISSUE TITLE
Ability to play all albums of given artist

### ISSUE THREAD

**Issue by hipnoizz** [gnumdk/lollypop#447]
Maybe I'm missing something but I could not find a way to play all albums of given artist. Maybe double click on artist name in the sidebar? It is not very discoverable, but e.g. Banshee works that way.

**Comment by gnumdk** [comment]
Go in artist view and click on first track?

For shuffle, activate "Shuffle artist tracks"

**Comment by hipnoizz** [comment]
Hmm, yeah. It took me a while to get how Lollypop plays music and how various shuffle modes work. I think that one thing you don't support is 'play albums of a given artist in a random order but in the context of a given album randomize tracks as well'. But maybe I'm missing something. Anyway this particular way of playback isn't important to me.

Too accustomed to Rhytmbox/Banshee/Vox/iTunes/whatever.

Thx a lot. I suppose that this one can be closed. I think I will open another issue - when you switch to the album context some shuffle modes makes no sense but that's another story. I need to verify this one anyway since I do not want to open another not-really-needed issue.

**Comment by hipnoizz** [comment]
After further thinking - I suppose that you also can't ask Lollypop to play music like this 'play albums of a given artist chronologically but in the context of a given album randomize tracks'. Lollypop basically mixes two things:
- what should be played - single track? single album? all albums of given artist? all albums?
- how it should be played - mostly about shuffling (or not) and looping.
No big deal for me personally but it can be a bit confusing.
