### ISSUE TITLE
"Modify informations" should be "Modify information"

### ISSUE THREAD

**Issue by kmf** [gnumdk/lollypop#448]
![screenshot from 2016-02-06 12-57-08](https://cloud.githubusercontent.com/assets/78700/12866270/44d4d996-ccd1-11e5-8062-02adbf626579.png)

**Comment by gnumdk** [comment]
Why?

**Comment by bil-elmoussaoui** [comment]
because information is an uncountable noun

**Comment by gnumdk** [comment]
Ok, not in French, my bad :)
