### ISSUE TITLE
Lollypop sound volume doesn't follow system sound volume

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#450]
Fedora 23, Lollypop 0.98.3.

Since the upgrade from 0.97.9, Lollypop doesn't follow system volume setting. Instead, it's always much lower than it and I have to go to the Gnome Control Center > Sound > Programs and increase volume there.

EDIT: 
To reproduce, start playing a song in Lollypop and decrease system volume to half via the Gnome Shell slider in upper right corner.
Exit Lollypop.
Start it again and start playing a song.

Nothing will be heard because Lollypop's volume is to low in Gnome Control Center > Sound > Programs section.

**Comment by pepewu** [comment]
Same problems here (updated Fedora 23, Lollypop 0.98.3):
1. Start Lollypop, start playing, volume is very low
2. Open Sound Control, Lollypop is at 13%, increase to 50%
3. Restart Lollypop, it goes back to 13%

1. Start Lollypop, start playing, volume is at 13% (should be 50%)
2. Restart Lolypop, volume goes down to 0%
3. Start Sound Control, set Lollypop to 50%
4. Restart Lollypop, it goes to 13%
5. Restart again and it is at 0%

**Comment by julianrichen** [comment]
Same, Debian Sid, Lollypop 0.98.3.

It varies between 10%~20% and sometimes start at 0%.

He recently changed some of the code to respect pulseaudio settings in #432.

**Comment by kostich** [comment]
Excellent! Can we expect a bugfix build (0.9.83-2) in COPR or will this fix be part of the next release?

**Comment by gnumdk** [comment]
Will release 0.9.84, just need to fix last bugs ;)

**Comment by kostich** [comment]
That's great to hear! Can't wait. :)
