### ISSUE TITLE
If a song is currently playing party mode does not work

### ISSUE THREAD

**Issue by julianrichen** [gnumdk/lollypop#451]
If you are playing a song you selected from the album view and you go to the party shuffle mode the next button on the shuffle pop-over does not work. If you pause the current song then click snuffle button + next it starts the current song again:
https://www.youtube.com/watch?v=o2FSyElZL-Q

I'm not sure if this is intentional but i feel if you click party mode it should start shuffling from the current song onwards until you unselected it.

On another note the pop-over seems to be a little to far to the left.

Distro: Debian Sid
Gnome: 3.18
Lollypop: ~~0.9.81~~ 0.9.83

**Comment by gnumdk** [comment]
Don't see what is not working, if you go in party mode, lollypop chooses music for you.

**Comment by julianrichen** [comment]
If you click the next button (double right arrow) in the party mode section shouldn't it start playing the next song? Or is it just indicating that the song in the pop-over will play after the current one?

**Comment by gnumdk** [comment]
> just indicating that the song in the pop-over will play after the current one?

**Comment by julianrichen** [comment]
I think I miss understood what that button did, I see what you are saying now.
