### ISSUE TITLE
All albums view - album artworks broken

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#452]
When selectint the all albums view, the artworks/thumbnails aren't displayed properly - cropped form right side. This isn't happening when viewing particular genres (well, only on one genre is the same, other are ok). see screenshot. Latest lollypop from Git - 0.9.83. This happens regardless of setting the thumbnail size smaller or larger in the menu.
![schermafdruk van 2016-02-07 14-29-24](https://cloud.githubusercontent.com/assets/12252430/12872584/3adbc6bc-cda7-11e5-9ec3-2e413eedb76b.png)

**Comment by corebots** [comment]
could be related: the very first album item format istn't sqare but a cassette scan (screenshot). both in all-albums and int the one affected genre, this not-square album cover is the first item in the album-list:
![schermafdruk van 2016-02-07 15-30-10](https://cloud.githubusercontent.com/assets/12252430/12872894/f12eafbc-cdaf-11e5-88dc-eb6c09427b94.png)

**Comment by gnumdk** [comment]
Yes, there is a bug due to:https://github.com/gnumdk/lollypop/issues/422

**Comment by corebots** [comment]
thank you! fixed.
