### ISSUE TITLE
click on song play, after listening to radio, doesn't work

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#453]
on latest lollypop from git, 0.9.83, after I listen to a radio station in lollypop, and then I try to switch to a song/album, clicking on it has no effect. the radio keeps playing and song doesn't start. only way to play a song from the library is to restart lollypop.

**Comment by gnumdk** [comment]
Are you sure you are using the last git? :)

**Comment by gnumdk** [comment]
I close as I've seen this bug yesterday after a stupid commit but reverted since ;)

**Comment by corebots** [comment]
yes I've cloned and buit from git right now but the bug remains. after radio listening, click on regular song has no effect :( please reopen

**Comment by gnumdk** [comment]
Can't reproduce :(

**Comment by gnumdk** [comment]
https://www.youtube.com/watch?v=66ync2iMQ-g&feature=youtu.be

**Comment by corebots** [comment]
Short screencast from my situation: https://www.dropbox.com/s/c60s3uano844ema/Schermfilm%20van%2002-08-2016%2011%3A44%3A49%20AM.webm?dl=0

strange. I've also tried to add a new radio, but issue remains by me.

**Comment by gnumdk** [comment]
Try to play with lollypop options.

**Comment by gnumdk** [comment]
Got it, crossfading ;)

**Comment by corebots** [comment]
Yess, you're right :)

**Comment by corebots** [comment]
I can confirm it works from latest git ;)
