### ISSUE TITLE
albums split by song year

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#454]
some albums may contain songs which were recorded in different years, thus not all songs of an album necessarily have the same year - tag. these albums are split/divided into two albums in the lollypop database, even though they are released under one album. makes double thumbnails to appear in the album view. Could you please make lollypop display songs with the same album-name-tag as one album instead of displaying an album cover separately for every year? I've noticed some albums are divided even if the year tag is the same and I can't find a reason why. (if this is the wished behavior for any reasons than sorry for reporting this). see screenshots for comparison.
![schermafdruk van 2016-02-07 14-41-10](https://cloud.githubusercontent.com/assets/12252430/12872669/db2fbce4-cda8-11e5-9f26-15e3fff8ad0d.png)
![schermafdruk van 2016-02-07 14-41-01](https://cloud.githubusercontent.com/assets/12252430/12872670/db2fdff8-cda8-11e5-8832-4319e630ff8c.png)
![schermafdruk van 2016-02-07 14-40-46](https://cloud.githubusercontent.com/assets/12252430/12872671/db37c36c-cda8-11e5-9e15-6a2fb1dbad19.png)

thanks for looking into this!

**Comment by gnumdk** [comment]
Wanted: https://github.com/gnumdk/lollypop/issues/307

**Comment by gnumdk** [comment]
The year tag is about album year.

There is an ORIGYEAR tag but lollypop ignore it.

**Comment by gnumdk** [comment]
For the album with same year, can you send me your lollypop database?
~/.local/share/lollypop/lollypop.db by email (see about dialog)

**Comment by gnumdk** [comment]
Your albums from Laura Marling are separated because:
- Some tracks have an album artist
- Some don't

**Comment by corebots** [comment]
correct. it was the album artist i haven't noticed. thanks!
