### ISSUE TITLE
multi-selection behavior 

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#455]
I'm enjoying the newly implemented multi-selection feature, thank you! However, I've noticed the following: when you have multiple genres selected, and albums from the resulting list too. when the last song of an album is played, lollypop automatically jumps to the next albom to continue playing, but it picks the next album from the total list of albums in the selected genres - and not from the selected albums only. difficult to explain. steps to reproduce: select two genres, then select two albums, one belonging to the first genre, the second one beloging to the second genre. play the last song of the first selected album > playing doesn't continue within the selected(and displayed) list of albums, but rather continues with the next album in the chronological list of total albums selected with the initial genre selection. I think, logically, the playing and auto-jumping to the next album should happen within the final and displayed album selection. Please have a look at this. if necessary, I'll try to clarify the issue more precisely :P

**Comment by gnumdk** [comment]
Here it works, are you sure "Shuffle albums" is not on?

**Comment by gnumdk** [comment]
Here event with the "Shuffle albums" it works.

**Comment by gnumdk** [comment]
Ok, I understand your issue ;)

**Comment by gnumdk** [comment]
No, I do not understand, here it really seems to work.

**Comment by corebots** [comment]
hmm, strange, now I can't reproduce it anymore. However, I didn't mean shuffle mode, but regular playing. I've updated lollypop in the meantime so that might have resolved it... Anyway, now it seams to be working as expected, I'll report back if i notice it again. sorry
