### ISSUE TITLE
Lollypop increases system volume to the max

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#457]
After starting up Lollypop and clicking on a song to play, Lollypop will increase system volume to the max. For this bug to happen, you need to enable "Mix songs" option. If the "Mix songs" is disabled, this bug does not occur.

Fedora 23. Lollypop 0.9.84.

**Comment by gnumdk** [comment]
Fuck :)

**Comment by kostich** [comment]
Haha. That's those unexpected cases. :D

**Comment by kostich** [comment]
You are going to start hating me. :D 
Found another way to trigger this.

- Set system volume to half.
- Make sure that the crossfading is on.
- Open Lollypop, play a song for a few seconds and pause it.
- Close Lollypop.
- Open Lollypop again and click either next song or previous song button.
- Observe how Lollypop increases system volume.

**Comment by gnumdk** [comment]
Will release 0.9.86 next week-end, so do not start by next track until :)
