### ISSUE TITLE
Option to disable notifications

### ISSUE THREAD

**Issue by zv0n** [gnumdk/lollypop#458]
It would be great if lollypop had an option to disable notifications (the ones that inform user of a track change) as they can be a bit distracting

**Comment by gnumdk** [comment]
Already exist in dconf-editor. Will not add an option in ui.

**Comment by zv0n** [comment]
Oh, didn't know that, thanks for the info and sorry for the useless issue

**Comment by klingtnet** [comment]
In Gnome 3 you can modifiy notification settings for specific applications with the `Notifications` dialog in `gnome-control-center`:

![notifications_lollypop](https://cloud.githubusercontent.com/assets/1538057/13728989/c21bd9f8-e929-11e5-8242-3b43d364d5de.png)
