### ISSUE TITLE
Crash with existing music (lower case) folder on MTP device

### ISSUE THREAD

**Issue by neckcen** [gnumdk/lollypop#459]
Lollypop crashes when selecting my phone's SD card if a folder named "music" (lower case m) exists. Renaming the folder to "Music" (upper case M) fixes it.

Exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/view_device.py", line 154, in _on_memory_combo_changed
    self._device_widget.set_uri(uri)
  File "/usr/lib/python3/dist-packages/lollypop/widgets_device.py", line 106, in set_uri
    d.make_directory_with_parents(None)
GLib.Error: g-io-error-quark: libmtp error:  Could not send object info. (0)
```

**Comment by coconutlulz** [comment]
I can't reproduce the error with version 0.9.77.

Procedure (with Sansa Clip+):
- Connected as MTP device.
- Created directory 'music' in root of SD card.
- Opened Lollypop.
- Selected 'SanDisk Sansa Clip+' from device menu (left).
- Changed 'Internal Memory' to 'External uSD Card'. This caused Lollypop to create a new directory called 'Music' in the SD card root, containing a directory called 'lollypop'. It didn't seem to even notice the 'music' directory, which remained untouched and empty.

Could you provide:
- Lollypop version.
- libmtp version.
- Phone model/OS version.

**Comment by neckcen** [comment]
Upon digging a bit more the issue appears to be caused by the fact my external SD is using FAT32 as file system:

> Case-insensitive, case-preserving (cicp) file-systems: This is the file-system generally used on Windows; FAT32 is an example of such a file-system. Although existing files can be opened using any case, the exact case used to create the file is preserved and available for programs to query. Two files that differ only by case is not allowed.
> http://doc.bazaar.canonical.com/developers/case-insensitive-file-systems.html

Trying to create a "Music" directory through nautilus also fails if "music" exists (but does not crash).
