### ISSUE TITLE
Last.fm not working on Fedora 23

### ISSUE THREAD

**Issue by EliasJorgensen** [gnumdk/lollypop#461]
I installed Lollypop from [copr](https://copr.fedorainfracloud.org/coprs/gnumdk/lollypop/) and followed the instructions to enable Last.fm.
However, after i have rebooted, the login form is still disabled.

**Comment by region51** [comment]
Fedora 23, lollypop-0.9.85 [link](http://koji.russianfedora.pro/koji/packageinfo?packageID=150), python3-pylast-1.4.2

![2016-02-12 12-57-20](https://cloud.githubusercontent.com/assets/13280183/13003726/5916a400-d188-11e5-82fa-2b74508aa1f5.png)
everything is working

**Comment by gnumdk** [comment]
pip3 install pylast

**Comment by region51** [comment]
@gnumdk not pip3 install pylast

dnf install python3-pylast
https://apps.fedoraproject.org/packages/python3-pylast

**Comment by gnumdk** [comment]
better :)
