### ISSUE TITLE
Playlist import/export?

### ISSUE THREAD

**Issue by stkAnon** [gnumdk/lollypop#462]
Maybe I just missed something but there doesn't seem to be any way to either import or export playlists to a plain text file. I have some playlists with ~100 songs each that I made in quod libet, and don't want to recreate all of them by hand to get them into lollipop.

Also, playlist export would be pretty useful for manually syncing other devices or applications.

**Comment by gnumdk** [comment]
Duplicated bug report

**Comment by bear454** [comment]
Can you link to the "original" bug report ?

**Comment by gnumdk** [comment]
#144
