### ISSUE TITLE
Right click causes TypeError

### ISSUE THREAD

**Issue by magpie240** [gnumdk/lollypop#463]
I see this was an issue before but it still affects me.
`TypeError: argument rect: Expected Gdk.Rectangle, but got gi.repository.cairo.RectangleInt`
It gets thrown whenever I right-click an album cover or track name. Gtk is 3.18.7, glib is 2.46.2.

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/292

**Comment by gnumdk** [comment]
I had this issue and be sure your installation is broken.

BTW, the issue is in python gobject.
