### ISSUE TITLE
Read embedded cover art first!

### ISSUE THREAD

**Issue by zin07** [gnumdk/lollypop#470]
Lollypop should read the embedded artwork first and if none present look at the internet sources. Currently it doesn't read the embedded artwork. This is a simple must have for any modern music player.

**Comment by gnumdk** [comment]
It does.

**Comment by gnumdk** [comment]
Your gstreamer installation may be broken.

**Comment by gnumdk** [comment]
Or you have an cover.jpg in your album folder.

**Comment by zin07** [comment]
Not sure gstreamer is the problem as banshee displays the cover art from the id3 on all my albums. Also why would the presence of a cover.jpg be an issue?

**Comment by gnumdk** [comment]
Because it will read the cover.jpg first.

To be sure, send me a file by email (about dialog in lollypop for my email)
