### ISSUE TITLE
Seeker bar not in the middle anymore?

### ISSUE THREAD

**Issue by anaturinbor** [gnumdk/lollypop#472]
I was wondering why you purposefully moved the seeker bar so that it’s not in the middle of the player anymore?

![screenshot from 2016-02-16 03 57 49](https://cloud.githubusercontent.com/assets/10692755/13065099/9518382a-d461-11e5-81f6-b5d62b68fdec.png)

It looked better before.
![df058c2c-b0f2-11e5-9722-aac175b7ead6](https://cloud.githubusercontent.com/assets/10692755/13065110/b8569fc0-d461-11e5-8c87-7a8411352d53.png)

**Comment by gnumdk** [comment]
Wanted.
