### ISSUE TITLE
Next song bubble contains an GtkImage without an image

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#473]
See the picture bellow:

![2016-02-16 19-23-59](https://cloud.githubusercontent.com/assets/4953862/13086384/4689d36c-d4e3-11e5-8671-692e03034e77.png)

When clicking on it, the "next song bubble" dissappears. Like it's an button for closing this bubble.

Fedora 23, master (revision b5702e9c26e564d7d48dfc578b6db9b89832ded7).

**Comment by region51** [comment]
I confirm
![2016-02-16 21-46-43](https://cloud.githubusercontent.com/assets/13280183/13087078/4396c6b0-d4f7-11e5-80a6-71b4ddc87e26.png)

**Comment by gnumdk** [comment]
Strange :(
