### ISSUE TITLE
Program broken after last update

### ISSUE THREAD

**Issue by anaturinbor** [gnumdk/lollypop#474]
Hi, Lollypop won’t play anything after the last update two hours ago. Clicking on a track does nothing, nor does clicking the play button in the top left. This is on Elementary OS.

It was working fine before this update and other music programs are working fine.

Edit: clicking on “party mode” starts a random track but I can’t do anything from the browser.

**Comment by gnumdk** [comment]
No error message on command line?

**Comment by anaturinbor** [comment]
I get this when running from terminal:

> No module named 'pylast'
>     - Scrobbler disabled
>     - Auto cover download disabled
>     - Artist informations disabled
> $ sudo pip3 install pylast
> No module named 'wikipedia'
> Advanced artist informations disabled
> $ sudo pip3 install wikipedia
> Namespace WebKit2 not available
> WebKit support disabled

Sometimes I get this error.

> ** (lollypop:7261): CRITICAL **: Unable to determine array length for 0x7f33580053c0

I just tried it on Ubuntu 15.04 and the same thing happened.

To clarify, clicking on an album cover starts playing that album and I can navigate then from the buttons on the top left. But clicking on a specific track in an album does nothing.

**Comment by gnumdk** [comment]
Ok, I know what is happening... Will revert Ubuntu package now!

**Comment by gnumdk** [comment]
And will stop supporting Ubuntu 14.04/Debian stable with 0.9.85 as it's just a GTK issue. Just hope fixed in GTK 3.16.

**Comment by gnumdk** [comment]
Anyone with Ubuntu 15.10 ???

**Comment by gnumdk** [comment]
You can downgrade from here:
https://github.com/gnumdk/lollypop/releases/tag/0.9.85

**Comment by gnumdk** [comment]
Cool, it works with Ubuntu 15.10...

Sorry for elementary users, can't fix GTK 3.14 bugs...

**Comment by pawelad** [comment]
Could you maybe mention in the README that `0.9.85` is the last supported version in Ubuntu 14.04 / elementary 0.3 ? Had to look a *lot* for this info.

**Comment by gnumdk** [comment]
Fixed, Lollypop 0.9.90 will work on Elementary OS
