### ISSUE TITLE
Party mode: light gtk theme

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#475]
Fedora 23, lollypop-0.9.86
press "Party mode" 
![2016-02-16 22-37-45](https://cloud.githubusercontent.com/assets/13280183/13088684/4d424d5e-d4fe-11e5-8526-ea1329ebe1c3.png)
and automatically turns on dark gtk theme
![2016-02-16 22-37-53](https://cloud.githubusercontent.com/assets/13280183/13088711/6f4cc366-d4fe-11e5-959c-e60fcaa38f6a.png)
???
Sorry for my bad English

**Comment by gnumdk** [comment]
It's wanted and like this since first release.
