### ISSUE TITLE
Prefences pop-over has extra border on inside of window (also allow escape key)

### ISSUE THREAD

**Issue by julianrichen** [gnumdk/lollypop#476]
The preferences pop-over has an extra lighter border (~ .75% on normal border) on the inside of the window. This includes below the top bar and around the edges of the window. Effects both light/dark themes. Other gtk3 apps are not like this. Here is a side comparisons of Nautilus (left) and Lollypop (right)
![](http://i.imgur.com/DP7VHBf.png)

Probably need to zoom in to see it. It's subtle but creates this shrunken effect on the dark theme. It's more noticeable on the dark theme because the background shadow intensifies it. I guess it has always been there because I recompiled 0.9.83 and it was the same.

Also if you could add a shortcut for escape on the preference window that would be very nice. The About pop-over in Lollypop and other pop-over windows in other applications allow the escape key to close the pop-over instead of clicking the close button.

Distro: Debian Sid
Gnome: 3.18
Lollypop: 0.9.83, 0.9.86

**Comment by gnumdk** [comment]
Reopen if not fixed ;)

**Comment by julianrichen** [comment]
The issue was open for 6 minutes... the speed at which you commit bug fixes is scary.

Thank you for the fix :) Is it still possible to close the pop-over with escape key?
