### ISSUE TITLE
Left click don't Work

### ISSUE THREAD

**Issue by dlanileonardo** [gnumdk/lollypop#478]
When click in music, playlist or album nothing occurred (after update to 0.9.86).

OS: Ubuntu 15.04
Version: 0.9.86

**Comment by gnumdk** [comment]
Vivid/Trusty aren't supported anymore. (Due to buggy GTK):
please downgrade: https://github.com/gnumdk/lollypop/releases/tag/0.9.85

BTW, vivid is unsupported even by Ubuntu!
