### ISSUE TITLE
not saved position

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#479]
Press "Popular albums" or "All albums", Close / Open player
![2016-02-17 17-22-21](https://cloud.githubusercontent.com/assets/13280183/13112258/169ce7b2-d59b-11e5-8dd3-31edbac1701e.png)
not saved position
![2016-02-17 17-22-31](https://cloud.githubusercontent.com/assets/13280183/13112554/3253563e-d59c-11e5-8302-8babe059ea60.png)
???
Sorry for my bad English

**Comment by gnumdk** [comment]
Yes, position is not saved anymore...
Here the isssue, when hidden, Gtk.Paned doesn't update it position and so lollypop was saving a wrong position in gsettings.

I disabled this until i find a solution.

**Comment by gnumdk** [comment]
5c5bd8779cf1db4491b7f73dfec257b7715ca4b7

**Comment by region51** [comment]
nightmare
![2016-02-17 18-35-37](https://cloud.githubusercontent.com/assets/13280183/13114663/8c745dbc-d5a5-11e5-9c3a-30318bcbb90f.png)
It Got Worse
