### ISSUE TITLE
When playing an album it will keep looping forever

### ISSUE THREAD

**Issue by ficoos** [gnumdk/lollypop#481]
When playing an album\playlist by clicking it will loop the selected album forever. I would expect lollypop would just stop playing once the album\playlist are done.

**Comment by gnumdk** [comment]
Lollypop repeat by default. Right click on title to temporaly change behaviour.

**Comment by ficoos** [comment]
Why isn't it just part of the repeat button, putting it in the right click menu is quite odd. Also, it seems like an odd default behavior. Why would you want to loop an album? Why would you want to loop the currently selected album once the queue is finished playing? There is currently no way to put two albums in the queue and then have it stop playing.

**Comment by gnumdk** [comment]
There is no repeat button...
