### ISSUE TITLE
Missing dependencies in Fedora

### ISSUE THREAD

**Issue by kivengh** [gnumdk/lollypop#482]
Lollypop not starting on Fedora 23 with your copr repo. Please add python3-pylast and totem-pl-parser as dependencies.
[lollypop-spec-patch.txt](https://github.com/gnumdk/lollypop/files/136163/lollypop-spec-patch.txt)

**Comment by region51** [comment]
>totem-pl-parser as dependencies.

Lollypop is a new GNOME music playing application.
it is not necessary, it is already installed

**Comment by kivengh** [comment]
Thanks for the link. On a Fedora 23 with KDE, there is no totem-pl-parser, so I can"t lauch lollypop.

**Comment by region51** [comment]
@kivengh 
lollypop
>A music player for GNOME

**Comment by gnumdk** [comment]
pylast isn't needed.

**Comment by gnumdk** [comment]
@kivengh Fedora/KDE and Fedora/GNOME use the same package repository, so totem-pl-parser is here...

**Comment by kivengh** [comment]
Yes, but I installed lollypop from Fedora copr and it crashed because totem-pl-parser was not present on my system.
I suggested to add as dependencies to auto install this package with lollypop when it's not present

**Comment by gnumdk** [comment]
Yes, it will be done for next release (tomorrow), that's why this issue is always open ;)

**Comment by gnumdk** [comment]
As we have a KDE user, a screenshot of lollypop under KDE? For the fun...

/me was a KDE dev/user some  years ago ;)

**Comment by kivengh** [comment]
Sure :smile: 
![bureau 1_027](https://cloud.githubusercontent.com/assets/2587835/13150443/1d4d1f66-d666-11e5-8ac2-8b5a8793dd46.png)

**Comment by gnumdk** [comment]
Hmm, no GTK theme for oxygen replacement, sad :-(

**Comment by kivengh** [comment]
Actually this the breeze theme. 😊 I can perhaps configure gtk theme in Plasma 5.

-------- Message d'origine --------De : Cédric Bellegarde <notifications@github.com> Date : 18/02/2016  17:53  (GMT+01:00) À : gnumdk/lollypop <lollypop@noreply.github.com> Cc : kivengh <kevin@famillecousin.fr> Objet : Re: [lollypop] Missing dependencies in Fedora (#482) 
Hmm, no GTK theme for oxygen replacement, sad :-(

**Comment by julianrichen** [comment]
@gnumdk Out of curiosity why is the above using headerbars? You mentioned on [WOGUE 2 weeks ago](https://plus.google.com/+WorldofGnomeOrg/posts/SUkD6215iRd) about using the headerbar argument in gtk grid to make [nautilus](https://plus.google.com/109637860626261571611/posts/2qvoZ3Gkuub) look better in Ubuntu. Since you already did the same thing in Lollypop why is the header bar being used here? Shouldn't environments that prefer not using headerbars automatically show a top bar then the headerbar under it to fit in better? Or was it simply not compiled that way?

**Comment by gnumdk** [comment]
It's an option in dconf and detection code is disabled but you're right, need some work.

**Comment by blackjackshellac** [comment]
not sure if this belongs here, but on Fedora 23 I couldn't get lollypop to configure from run without setting PKG_CONFIG_PATH, from config.log,

```
$PKG_CONFIG --exists --print-errors "gtk+-3.0 >= 3.16"
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
Package 'x11', required by 'egl', not found
configure:13697: $? = 1
configure:13711: $PKG_CONFIG --exists --print-errors "gtk+-3.0 >= 3.16"
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
Package 'x11', required by 'egl', not found
configure:13714: $? = 1
configure:13728: result: no
Package 'x11', required by 'egl', not found
configure:13744: error: Package requirements (gtk+-3.0 >= 3.16) were not met:

Package 'x11', required by 'egl', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTK_CFLAGS
and GTK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

```

Setting the environment variable solves this,

```
$ git clone https://github.com/gnumdk/lollypop.git
$ cd lollypop
$ PKG_CONFIG_PATH=/usr/lib/pkgconfig ./autogen.sh
$ ...
```

**Comment by region51** [comment]
@blackjackshellac dnf install gtk3-devel???

**Comment by blackjackshellac** [comment]
Of course, immediately after posting this I discovered that I had libX11-devel.i686 installed instead of libX11-devel.x86_64 so pkgconfig was searching in /usr/lib64/pkgconfig not /usr/lib/pkgconfig.    Installing libX11-devel.x86-64 fixed the problem.  Sorry for the noise.

**Comment by kidwm** [comment]
@gnumdk BTW, will copr build be fixed in next version?
