### ISSUE TITLE
Handle touch screens

### ISSUE THREAD

**Issue by gnumdk** [gnumdk/lollypop#488]
Some items aren't availables on a touch screen:
- Right click menu on toolbar
- Reopen mix popover in settings
- ...

Idea: allow user to simulate right click with a long press event.

Targeted after 0.9.90.

**Comment by gnumdk** [comment]
Gtk provides Gtk.GestureLongPress, already present in toolbar_infos.py but doesn't work.
```
# Gesture for touchscreen
gesture = Gtk.GestureLongPress.new(self._labels_event)
gesture.set_propagation_phase(Gtk.PropagationPhase.CAPTURE)
gesture.connect('pressed', self._on_title_pressed)
```

self._labels_event is a Gtk.EventBox.

Help welcome ;)

**Comment by bil-elmoussaoui** [comment]
I have a touch screen, i will try the code later and push a fix if i find one :)

**Comment by gnumdk** [comment]
Finally handle this by hand. And report issue to Gtk.
