### ISSUE TITLE
Old album covers are not deleted/replaced

### ISSUE THREAD

**Issue by MineyMe** [gnumdk/lollypop#49]
Hello

I was correcting some album covers using Lollypop and found out that the old file (cover.jpg) is left intact when it is replaced: Lollypop instead creates a new Folder.jpg file, which leads me to wonder:

  * Is this intended behavior? Other music players might wrongly pick up the old cover file instead (depending on the order they search for files in).
  * Would it be possible to specify the name of the file to use somewhere? I have cover.jpg as name everywhere now, whilst Lollypop will be creating Folder.jpg files. This is in itself not such a big a deal, since most music players search for all of them anyway.

Thanks in advance

**Comment by gnumdk** [comment]
>Is this intended behavior?
Yes, i do not want to alter user filesystem...

I will add an option to change the default string.
