### ISSUE TITLE
Playlists Don't Work on LG4

### ISSUE THREAD

**Issue by wunderdojo** [gnumdk/lollypop#491]
Don't know if this affects other Android devices but if I create a playlist in Lollypop and sync it to my LG4 the files are copied (into Music/lollypop/tracks) and the playlist is as well (Music/lollypop/playlist.m3u). The playlist shows in the LG4 music app but has 0 songs. The songs are accessible though if I go to the Recently Added playlist or just to the music library.

**Comment by gnumdk** [comment]
What application? Was working with my One plus One and Google Music.

With my Ubuntu Phone and Music, it does not work but it's Ubuntu fault.

**Comment by wunderdojo** [comment]
Computer is Ubuntu 15.10 running latest release of Lollypop. I create
playlist and then sync it to the LG4. Tried it with the default Music app
(v 4.70.9). Got it working using Rocket Player, the only catch being that
after updating a playlist I have to rescan the device for Rocket Player to
pick up the changes.

I tried Google Play Music but that doesn't seem to pick up the playlists at
all.

*Jamie Currie*
------------------
CEO, wunderdojo
949-734-0758
Located in sunny Southern California
GMT / UTC - 7 hours

On Fri, Feb 26, 2016 at 1:44 PM, Cédric Bellegarde <notifications@github.com

**Comment by gnumdk** [comment]
So it's a bug in apps.

**Comment by wunderdojo** [comment]
I wouldn't consider it a bug in apps considering I've only found one app that (mostly) works with it. What player do you use? I'm happy to switch to something else if there's one that works well with it.

**Comment by gnumdk** [comment]
It doesn't work on my ubuntu phone, BTW playlist format is OK as it works with some players.

Can't do anything as there is no bug.

**Comment by wunderdojo** [comment]
Can you tell me what one of the players it works with is? I've tried 4 or 5 so far and only found one that works, though not fully.
