### ISSUE TITLE
export (and import) playlists as .m3u

### ISSUE THREAD

**Issue by elcarretero** [gnumdk/lollypop#495]
The only thing on lollypop that I really miss is that the program yet isn't able to handle .m3u playlists.
With that feature lollypop would be definitively on of the coolest music players :)
Regards

**Comment by gnumdk** [comment]
Import is not possible due to oldest lollypop bug...
Don't want to include this as this will make lollypop segfault with some .m3u files...

**Comment by gnumdk** [comment]
Just a question, why do you need m3u files?

**Comment by gnumdk** [comment]
Hmm, m3u import seems to be fixed upstreame in GNOME 3.20... But Ubuntu 16.04 LTS will feature GNOME 3.18, not sure what to do about import :-(

**Comment by elcarretero** [comment]
oh ok I roughly understand the problem :/ but it might be possible to implement a m3u export function? that would be already a cool thing! 
And refering to your question about the .m3u, I just think that it is one of the most common formats :)
Regards

**Comment by gnumdk** [comment]
Yes, but why do you need a m3u file? :)

**Comment by elcarretero** [comment]
It would be useful to be able to copy/move the playlist for example to another computer and/or to be able to open it with another Program

**Comment by elcarretero** [comment]
or to a smartphone :)

**Comment by gnumdk** [comment]
Copy/move to another computer: ~/.local/share/lollypop/playlists.db

Export as m3u:
https://github.com/gnumdk/lollypop/wiki
