### ISSUE TITLE
Crashes on Fedora 23: "sqlite3.OperationalError: no such column: duration"

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/lollypop#496]
Hi!

On Fedora 23, I've installed lollypop 0.9.87 using the copr repo:
```
$ sudo dnf copr enable gnumdk/lollypop 
$ sudo dnf install lollypop
```

I've noticed a few messages of the app asking for some python libs, so I installed them:
```
$ sudo dnf install python3-pylast
$ sudo pip3 install wikipedia
```

Then I've (re)started the app, trying to click on many things of the UI, and then select an artist to see its albums, and then the app crashes. Every time. Here is the output I have after clicking on a single artist:
```
$ lollypop 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/view_artist_albums.py", line 53, in populate
    self._add_albums(albums)
  File "/usr/lib/python3.4/site-packages/lollypop/view_artist_albums.py", line 75, in _add_albums
    size_group)
  File "/usr/lib/python3.4/site-packages/lollypop/widgets_album.py", line 308, in __init__
    duration = Lp().albums.get_duration(album_id, genre_ids)
  File "/usr/lib/python3.4/site-packages/lollypop/database_albums.py", line 699, in get_duration
    WHERE album_id=?", (album_id,))
sqlite3.OperationalError: no such column: duration

```

Should I reset the database? Or do I miss dependencies?

Thanks in advance! Lollypop seems to be really nice.

**Comment by gnumdk** [comment]
Do you have used lollypop on this computer in the past?

**Comment by Gwend4l** [comment]
Oh, now that you say it, maybe I did try lollypop a long time ago... So I've removed `~/.local/share/lollypop`, and now everything seems to be working. Sorry for the useless ticket, I'll keep you updated if I find other problems :). Btw I really like how Lollypop is "album-oriented", nice job.

**Comment by gnumdk** [comment]
More to come in next release with full control on "album playlist"
