### ISSUE TITLE
Crash: "AttributeError: 'PlaylistWidget' object has no attribute 'update_cover'"

### ISSUE THREAD

**Issue by Gwend4l** [gnumdk/lollypop#497]
So, following my useless #496 bug report, this time I successfully managed to play music and properly use lollypop, but I still encounter crashes in some cases that are hard to identify. It always happens when doing some UI interaction, such as right of left click on some item of the left pane.

Here is the output of my last crash:
```
$ lollypop
ArtDownloader::_get_album_art_lastfm: Album not found
Wikipedia::get_page_infos(): Page id "tony les" does not match any pages. Try another id!
Error loading module '/usr/lib/mozilla/plugins/nppdf.so': /usr/lib/mozilla/plugins/nppdf.so: mauvaise classe ELF : ELFCLASS32
Error scanning plugin /usr/lib/mozilla/plugins/nppdf.so, /usr/libexec/webkit2gtk-4.0/WebKitPluginProcess returned 256 exit status
Error loading module '/usr/lib/mozilla/plugins/nppdf.so': /usr/lib/mozilla/plugins/nppdf.so: mauvaise classe ELF : ELFCLASS32
Error scanning plugin /usr/lib/mozilla/plugins/nppdf.so, /usr/libexec/webkit2gtk-4.0/WebKitPluginProcess returned 256 exit status
ArtDownloader::_get_album_art_lastfm: Album not found
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/view.py", line 124, in _on_cover_changed
    widget.update_cover(album_id)
AttributeError: 'PlaylistWidget' object has no attribute 'update_cover'
```

(Note that the webkit/mozilla errors must be linked to the fact that I have played with the integrated web browser, when clicking on the current track at the top. But despite the error messages, it worked very well in the application, and is not related to the crash.)

**Comment by gnumdk** [comment]
Is this 0.9.87?

**Comment by gnumdk** [comment]
Ok, I know, lollypop was downloading covers while you were lookings at playlists :)

**Comment by Gwend4l** [comment]
Yes, 0.9.87! Great that you found out, thanks :)
