### ISSUE TITLE
Crash on manually retrieving album art for specific album

### ISSUE THREAD

**Issue by adimit** [gnumdk/lollypop#499]
Hi,

Lollypop crashes when I try to manually retrieve album art for the release *"Iron and Wine & Ben Bridwell — Sing into My Mouth"* (so far, only this one seems to cause the issue.)
I right-click on the missing album cover in the album overview, then right-click again in the pop up to manually select an album cover. This works fine for all other releases. Python gives me the following exception:

~~~
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/widgets_album.py", line 554, in _on_cover_press_event
    popover.populate()
  File "/usr/lib/python3.4/site-packages/lollypop/pop_covers.py", line 77, in populate
    ArtSize.MONSTER)
GLib.Error: gdk-pixbuf-error-quark: Error interpreting JPEG image file (Application transferred too few scanlines) (0)
~~~

This error is 100% reproducible on my fresh Fedora 23 installation.

Please tell me if and how I can provide more debugging information! Thanks for making lollypop, I *really* enjoy the app!

**Comment by adimit** [comment]
Lollypop version is 0.9.87 from the Fedora copr.

**Comment by gnumdk** [comment]
Nothing more, will add a fix.

**Comment by gnumdk** [comment]
Fixed
