### ISSUE TITLE
Correct info about number of albums

### ISSUE THREAD

**Issue by MichaelTiebesl** [gnumdk/lollypop#501]
I found out that the number of albums and from artists are different then from another music player.
Does Lollypop count an album with 2 discs as 2 albums for example?

![cantata](https://cloud.githubusercontent.com/assets/10792019/13559994/2c8fbab8-e455-11e5-85f5-0b9fcfe05ffc.png)
![rhythmbox](https://cloud.githubusercontent.com/assets/10792019/13559998/2d8f5644-e455-11e5-8b24-38a4e1fa9d06.png)
![lollypop](https://cloud.githubusercontent.com/assets/10792019/13560003/34b878ce-e455-11e5-886e-75dd601bd2ea.png)

**Comment by gnumdk** [comment]
Do you have splitted albums in views?

**Comment by MichaelTiebesl** [comment]
Sorry , i don't know what you mean by splitted albums in views? I thought the info is based on the files i have saved in my music folder.

**Comment by gnumdk** [comment]
Send my ~/.local/share/lollypop/lollypop.db by email/dropbox/...

**Comment by gnumdk** [comment]
No the infos are based on tags:
- same album artist => same album
- no album artist , same artist => same album
- else: compilations or splitted albums

**Comment by MichaelTiebesl** [comment]
The link to see your email address in the about dialog from Lollypop is for me not working. I can't see another option to have your email address.

**Comment by gnumdk** [comment]
cedric.bellegarde àrobaz adishatz dot org

**Comment by MichaelTiebesl** [comment]
Is that an email address?

**Comment by region51** [comment]
@MichaelTiebesl cedric.bellegarde@adishatz.org

**Comment by MichaelTiebesl** [comment]
@region51 thanks that look better.
