### ISSUE TITLE
Updating album art while in playlist causes crash

### ISSUE THREAD

**Issue by blackjackshellac** [gnumdk/lollypop#502]
I can consistently crash lollypop by opening a playlist and then attempting to set any album art while it is playing.

- open playlist
- play something
- open genre from left menu
- right click on album
- right click on art work to open selection dialog
- click on image
- boom

Traceback is below.

This is on fedora in lollypop 0.9.87

```
Name        : lollypop
Version     : 0.9.87
Release     : 1
Architecture: noarch
Install Date: Fri 19 Feb 2016 02:00:05 AM EST
Group       : Unspecified
Size        : 2007356
License     : (GPLv3+)
Signature   : RSA/SHA1, Wed 17 Feb 2016 06:47:33 AM EST, Key ID 46fe509e0acb8044
Source RPM  : lollypop-0.9.87-1.src.rpm
Build Date  : Wed 17 Feb 2016 06:47:23 AM EST
Build Host  : copr-builder-19084701.novalocal
Relocations : (not relocatable)
Vendor      : Fedora Project COPR (gnumdk/lollypop)
URL         : https://github.com/gnumdk/lollypop
Summary     : GNOME music playing application
Description :
Lollypop is a new GNOME music playing application


``````
$ lollypop 
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/view.py", line 124, in _on_cover_changed
    widget.update_cover(album_id)
AttributeError: 'PlaylistWidget' object has no attribute 'update_cover'

```

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/497

**Comment by blackjackshellac** [comment]
Damn.  Okay, well after strugging to have master build on Fedora 23, I can verify it's fixed in master now if it's any consolation for my repeated cockups :)  Many thanks.
