### ISSUE TITLE
Problem about music library

### ISSUE THREAD

**Issue by ItachiUchiha91** [gnumdk/lollypop#503]
Hi! I have two problems about my music library:
i) I have 4 albums named 'Greatest Hits' (but different artists in each one), so lollypop create two different albums in 'Compilation', I think it creates two albums and not four because two albums are pubblishied in 2004 and the other two in 2009. I tried to add a tag 'album artist', but it doesn't work. Can't I put these albums in their respective artists field and not in 'compilations'?

![schermata da 2016-03-08 11-08-18](https://cloud.githubusercontent.com/assets/17726762/13607013/a205ffc4-e54e-11e5-9d40-e184e7751bb2.png)

ii) I have a problem with two albums ("Blackbird" and "Goodbye Lullaby" (tags on the image below)). I don't know why lollypop creates two different albums despite the song in them have exactly the same tag (except for the track tag).

![schermata da 2016-03-08 11-08-39](https://cloud.githubusercontent.com/assets/17726762/13607021/ab5937d0-e54e-11e5-8f26-3480ca6cc08d.png)

Here the tags of the songs:
![schermata da 2016-03-08 16-17-00](https://cloud.githubusercontent.com/assets/17726762/13607027/af81d9ca-e54e-11e5-9a87-2fbbbd5cfc9a.png)

Sorry for my bad english.

**Comment by gnumdk** [comment]
Send me albums via email (about dialog) and dropbox/google drive/....

**Comment by gnumdk** [comment]
And I don't see any "album artist" tag in you screenshots.

**Comment by ItachiUchiha91** [comment]
Yes...I made many try. I've just resolved the problem about 'Greatest Hits' albums using easytag. When I used puddletag I had created the tag 'album artist' , while writing the tag 'albumartist' (as easytag does) it's work.
I send the albums about the other problem at "yournickatgmail!com", is it right?

**Comment by gnumdk** [comment]
Not a problem, year is about "Album" release date, if you want to tag track release date, there is an "original release date" tag but lollypop doesn't use it.

**Comment by gnumdk** [comment]
https://db.tt/aFyGo9u4 => You have an APE tag with 2006 as year, use puddletag to remove it

**Comment by ItachiUchiha91** [comment]
Perfect, solved! Remains the 'mysterious' problem xD

**Comment by gnumdk** [comment]
Yes, just an issue in tags, gstreamer see an "album artist" tag for some files.

I fixed this by:
- Remove all tags in puddle tag
- Retag file with easytag.

**Comment by ItachiUchiha91** [comment]
Thank you so much!
