### ISSUE TITLE
Unused localised string in the UI

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#504]
Fedora 23, revision 025fca49c8fb5fee627f5b54aebaa38625b57229.

Translated string for 'Remove' isn't used in the UI.

![unlocalised-string](https://cloud.githubusercontent.com/assets/4953862/13727316/190568a6-e8ee-11e5-86b2-671932e4846a.png)

**Comment by gnumdk** [comment]
It is used, but github will be synced with transifex before release.

**Comment by gnumdk** [comment]
msgfmt yourfile.po
mv message.mo /usr/local/share/locales/yourlang/LC_MESSAGES/lollypop.mo

**Comment by kostich** [comment]
Got it!

**Comment by region51** [comment]
@gnumdk 
>It is used, but github will be synced with transifex before release.

lollypop-0.9.90 no translation
lollypop-0.9.91 no translation

?????????????????????????????????????????????????????????

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/tree/stable/po

As you can see, I updated two days ago but transifex client skip ru :(

Will force update for next release.
