### ISSUE TITLE
Don't give priority reading APE tags when ID3v2 are available

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#505]
Should be possible as Rhythmbox managed to do this. This would work around all issues with music showing up with wrong tags even though the average tag editor doesn't show anything wrong with the files, without having to manually get rid of the APE tags in the affected files. I don't know if it also affects ID3v1 tags, but in any case, for MP3 files priority should be given to ID3v2 (or higher).

**Comment by gnumdk** [comment]
http://brej.org/blog/?p=143

Are you sure for rhythmbox?

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=362876

**Comment by gnumdk** [comment]
Seems rhythmbox only remove APE tags... Not sure I wan't to modify your files ;)

**Comment by gnumdk** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=200507

**Comment by d9h02f** [comment]
Well, Lollypop seems to be oriented towards people who don't care about technical details and just want things to work, so I think this is an exceptional case where modifying the files would be beneficial. The only thing Lollypop would do with the files would be to get rid of the APE tags so the music shows up the way the user expects it to. In case you disagree, I think the FAQ/help/wiki/... could have a question and answer about music files showing up with wrong tags and what to do about it. I think you could put the information from brej.org there (not just link because who knows when the site disappears), thanks for that link btw.

**Comment by gnumdk** [comment]
Do you have such a file? Can you send me one by email because I already removed APE tags from my collection and can't find a way to add somes...

**Comment by d9h02f** [comment]
Ok, mail sent.

**Comment by gnumdk** [comment]
Thanks

**Comment by gnumdk** [comment]
Here lollypop doesn't read the APE tag... ;)

**Comment by gnumdk** [comment]
Can you test with current master?

Lollypop was adding tags from all frames(id3, ape)... My wrong understanding of Gstreamer API.

Seems Gstreamer use ID3 tag first.

**Comment by d9h02f** [comment]
Ah, I didn't check before but I was using 0.9.87. I will test the current master asap.

**Comment by d9h02f** [comment]
make complains about a missing package, which I do have installed, so I'll just wait for the next release.

**Comment by gnumdk** [comment]
What package? What Distro?

**Comment by blackjackshellac** [comment]
Might be a long shot, but I had a package dependency issue on fedora 23 that turned out to be due to having the i686 devel package installed instead of the x86_64.  After adding the x86_64 package configure ran without issue.  Just a thought.

```
$ rpm -q libX11-devel
libX11-devel-1.6.3-2.fc23.i686
libX11-devel-1.6.3-2.fc23.x86_64
```

**Comment by d9h02f** [comment]
`checking for gobject-introspection... configure: error: gobject-introspection-1.0 is not installed`
It seems the installed version is 1.44.0, so I don't know why it doesn't work. openSUSE

**Comment by gnumdk** [comment]
zypper si -d  lollypop

**Comment by d9h02f** [comment]
Oh wow, sorry, didn't notice it wasn't the -devel package. I'll try again.

**Comment by gnumdk** [comment]
Now you have git, what about this one?

**Comment by d9h02f** [comment]
Seems to work now, thanks.
