### ISSUE TITLE
Debian 8 unable to click listviews

### ISSUE THREAD

**Issue by tyranny29** [gnumdk/lollypop#506]
I am not able to double click any items from listview to play.

I can press party mode and it will play a track.. but not from listview.

When I hit party mode, it reverts to dark theme.

This is strange issue, I have all dependencies.

I checked debug, no errors. Any advise?

**Comment by gnumdk** [comment]
Lollypop isn't compatible with Debian 8/Ubuntu 14.04/Elementary OS.
http://gnumdk.github.io/lollypop-web/

Last available version for Debian is 0.9.85.

**Comment by tyranny29** [comment]
Ok yeah I see, I compiled 0.75 no issues. Thanks!

**Comment by gnumdk** [comment]
I 'm trying to make 0.9.90 (next) working on EOS/Debian stable with no success (broken widget in GTK 3.14)

**Comment by tyranny29** [comment]
hopefully you can get it squared away eventually, maybe GTK will release a patch. i will keep updated on the progress! excellent player.

**Comment by gnumdk** [comment]
Fixed, Lollypop 0.9.90 will work on Debian stable ;)
