### ISSUE TITLE
Split or collaboration albums are treated as compilations

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#510]
On these albums I have double/triple artist tags and double/triple albumartist tags (one for each artist). It doesn't make a lot of sense to me to have these under compilations, because that makes it sound like it's a compilation of a bunch of different songs, although it's actually just two or three artists who made an album together. I want to be able to find the album under the listing for each artist and not under a listing like "artist 1 and artist 2 and artist 3", so merging the (album)artist tags again is not really an option.

**Comment by gnumdk** [comment]
Duplicated: #507
