### ISSUE TITLE
Embedded cover art for WMA not displayed

### ISSUE THREAD

**Issue by alan12345678** [gnumdk/lollypop#512]
I can play WMA files okay. And an album of WMA displays the correct art, since it sorts to the "folder.jpg" cover art I ensure is there. But where there are individual single WMA files in the library, and the cover art is simply 'embedded' in the one file, the player falls back to displaying some random picture. I've tried deleting from the local cache, but then it simply picks a different random image to use.

I note that if I browse to the offending files in Nautilus they display perfectly okay, so this is just the player.

**Comment by gnumdk** [comment]
Lollypop cover search order:
1) cover.jpg in folder
2) track embedded artwork
3) .jpg in folder
4) itunes/spotify/lastfm

**Comment by alan12345678** [comment]
Allow me to expand:

my music library is on an external disc. It has been run through my Windows laptop for many years without any problems. I have a number of tagging tools to both examine and edit my file tags, and my library has been meticulously curated over the years.

Since moving to Linux on a second machine, I admit there is a learning curve, but I can confirm that my files are correctly tagged and there is NOT ONE single file in my library which does not have EMBEDDED album/track art or a jpg or png album image file.

The search order quoted above is irrelevant to my problem, as there is no need to search externally for art.

My problem should be easily reproducible. Take a music file in WMA (Windows Media Audio) format and ensure that the track/album artwork is *attached* (WMA doesn't strictly speaking use tags).

Browse to the location where the music file is located using an "icon view" for your file explorer. You will see that the file appears as an icon with the cover art attached. Note that this is NOT a single file living within a folder and which folder has an image file for the artwork. This is simply a single music file with embedded artwork.

Now, open Lollypop and go to the file's location. You will see that the track view defaults to the white image reserved for when artwork is missing.

All other music formats that I have in my library (mp3, mp4, m4a, flac) are correctly displayed, including single discrete tracks which have only the artwork embedded and not within an album folder. It is only on all WMA files which are not inside an album that the problem occurs

**Comment by gnumdk** [comment]
Send me an exemple file by email

**Comment by alan12345678** [comment]
sorry to be dim, but where do I find your email?

**Comment by alan12345678** [comment]
unless it's this one! Sorry for being dim.
 
*alan ansell figurative painting Itzac France*
He would be a poet who could impress the winds and streams into his
service, to speak for him.
- Henry David Thoreau
 
 
----- Original message -----

**Comment by gnumdk** [comment]
It's this one!

**Comment by alan12345678** [comment]
did the attached file arrive? The mail seems to have deleted itself! This is to say that in fact I was wrong in one of my earlier assertions. The lack of proper display on single tracks also seems to apply to MP4 and not simply WMA. Can attach examples as appropriate.

**Comment by gnumdk** [comment]
Are you sure your gstreamer installation is OK ?

**Comment by alan12345678** [comment]
I'm not aware that I have any kind of problem with it. Everything plays
perfectly, it's just the album art within the player.
 
What should I be checking in gstreamer? Not sure what you'd want me
to diagnose.
 
 
----- Original message -----

**Comment by gnumdk** [comment]
Send me a wma and a mp4 file with something like dropbox by email.

**Comment by alan12345678** [comment]
will do so if you still wish after this following update:

decided to test where the error with album art might be coming from. So I manually created the missing art (.jpg) for one specific track, and labelled it following Lollypop convention, and copied and pasted it into the cache folder. Started up Lollypop and Bingo! it displays perfectly.

So the issue would seem to be related to the fact that it doesn't retrieve that information via the server.

I'm using Subsonic. Seemed simple enough to set up. Can't be that, can it?

**Comment by gnumdk** [comment]
Yes, because I do not understand what subsonic is doing here :)

**Comment by alan12345678** [comment]
you should have a couple of links to two files. Let me know if they don't show up.

Not sure if it's part of the same problem, but my only remaining niggle is that dia-critics show up very last in the artist listings... so both Á  and É for example show up right at the bottom, as opposed to somewhere in the alphabetical listing (African and French singers respectively)

**Comment by gnumdk** [comment]
By email, you can't post this in github

**Comment by alan12345678** [comment]
so how do I share these files then? I can attach them here in this message box if you don't mind...

**Comment by gnumdk** [comment]
cedric.bellegarde@adishatz.org

**Comment by gnumdk** [comment]
You are missing gstreamer ugly

**Comment by alan12345678** [comment]
nope. I've got them all installed - did that whole thing with enabling DVDs, all media types etc. Just checked again. Have all relevant repos enabled - as far as I can tell.

Could it be anything to do with mount type/permissions? Thought I'd done it right. It mounts automatically.

**Comment by gnumdk** [comment]
Found the issue for the m4a file.

For you repo, gstreamer ugly 1.0, not 0.10!

**Comment by alan12345678** [comment]
very helpful! Thanks v much :0)
 
they don't make it easy do they??? Took me an hour!
 
Superb player - loving it to bits :0)
 
*alan ansell figurative painting Itzac France*
He would be a poet who could impress the winds and streams into his
service, to speak for him.
- Henry David Thoreau
 
 
----- Original message -----
