### ISSUE TITLE
the question of tooltip

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#514]
![2016-03-20 14-20-05](https://cloud.githubusercontent.com/assets/13280183/13904133/669889d6-eea7-11e5-967d-5e17529fb67c.png)
![2016-03-20 14-20-08](https://cloud.githubusercontent.com/assets/13280183/13904135/6a91205c-eea7-11e5-94b1-3e62b52f9adc.png)
![2016-03-20 14-20-10](https://cloud.githubusercontent.com/assets/13280183/13904136/6d4e18f4-eea7-11e5-8965-27061f399171.png)

no tooltips Playlists, Radios,All artists
maybe just remove tooltips  Popular albums, Recently added albums, Random albums ?
Sorry for my bad English.

**Comment by d9h02f** [comment]
I think this just happens because there is not enough space on the screen to show the full description. If you drag the sidebar to make it wider so the full descriptions show on the screen (so without ...), you shouldn't see the tooltips anymore.

**Comment by region51** [comment]
>If you drag the sidebar to make it wider so the full descriptions show on the screen (so without ...), you shouldn't see the tooltips anymore.

:+1:

**Comment by gnumdk** [comment]
The tooltip position is strange but lollypop doesn't handle tooltip position.
