### ISSUE TITLE
Use composer and performer tags as 'artists' when artist/albumartist is not available

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#515]
Classical music generally doesn't have artist or albumartist, but composer and performer tags, so right now it shows up as 'unknown' in the list of artists. This would fix that problem.

**Comment by gnumdk** [comment]
Please send me a file as exemple by email.

**Comment by d9h02f** [comment]
Done.

**Comment by gnumdk** [comment]
performer as album artist and composer as artist?
