### ISSUE TITLE
view pause problem

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#516]
lollypop-0.9.90

play
![2016-03-21 15-27-47](https://cloud.githubusercontent.com/assets/13280183/13918657/c7718014-ef79-11e5-9035-2fb7a4d41310.png)
pause ???
![2016-03-21 15-27-50](https://cloud.githubusercontent.com/assets/13280183/13918659/cd218b44-ef79-11e5-9c14-3d0dfde93f2b.png)
Sorry for my bad English.

**Comment by gnumdk** [comment]
Wanted

**Comment by region51** [comment]
@gnumdk 
>Wanted

what's this?
This is an error or no?

**Comment by region51** [comment]
@gnumdk fullscreen normal
![2016-03-21 23-09-26](https://cloud.githubusercontent.com/assets/13280183/13932654/246e405a-efba-11e5-8cc1-0c3760d63544.png)

**Comment by gnumdk** [comment]
That's not normal

**Comment by gnumdk** [comment]
Removed as seems to be confusing.

**Comment by region51** [comment]
@gnumdk lollypop-0.9.91 This is an error or no?
![2016-03-21 15-27-50](https://cloud.githubusercontent.com/assets/13280183/13918659/cd218b44-ef79-11e5-9c14-3d0dfde93f2b.png)
it looks silly

**Comment by gnumdk** [comment]
In master, not in stable.
