### ISSUE TITLE
Problem in albums cover size

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#519]
Steps to Reproduce:
Preferences + press show genres

Actual Results: 
Albums cover size does not work.
![2016-03-21 22-31-32](https://cloud.githubusercontent.com/assets/13280183/13931507/b5932cb8-efb4-11e5-846c-9b59d3598f4c.png)

**Comment by region51** [comment]
@gnumdk does not work
lollypop-0.9.90
lollypop-0.9.91
video https://www.dropbox.com/s/8airddtrf045lub/lollypop.mkv?dl=0

**Comment by gnumdk** [comment]
Fixed in master, not in stable...
Maybe for 0.9.92
