### ISSUE TITLE
Question: Multiple genre tags

### ISSUE THREAD

**Issue by MineyMe** [gnumdk/lollypop#52]
Hello

I have some tracks that contain multiple genres, I was wondering if there is a specific format (i.e. delimiter) that Lollypop requires to place these correctly? I have some genre tags containing slashes (which could arguably be seen as one genre), some containing comma's and some containing semi-colons, but all of them are picked up as one genre. It would be neat if a track having the genre string 'Game; Soundtrack' could be located under genre 'Game' as well as under 'Soundtrack'.

Thanks in advance

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/tree/multitags

100% buggy :)

**Comment by gnumdk** [comment]
Merged in master:
- Multi genres
- Multi artists
