### ISSUE TITLE
Problem in fullscreen

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#520]
Fedora 23, lollypop-0.9.90
does not work press next track
![2016-03-21 23-11-48](https://cloud.githubusercontent.com/assets/13280183/13932714/90dd61b2-efba-11e5-83ba-6e42f18b5dcc.png)

**Comment by gnumdk** [comment]
Here it works, are you in party mode or shuffle?

**Comment by gnumdk** [comment]
It's the same widget than not in fullscreen, so the bug should be present also in non fullscreen

**Comment by gnumdk** [comment]
Are you sure you have more than on track in playback?

**Comment by region51** [comment]
oops, everything is working.
