### ISSUE TITLE
Install on debian

### ISSUE THREAD

**Issue by gwendy12** [gnumdk/lollypop#522]
I can't install lollypop. I ran the command ./autogen.sh but I receive this error:

./configure: line 5433: syntax error near unexpected token `disable-static'
./configure: line 5433: `LT_INIT(disable-static)'
+ exit 1

And then i use make there is no makefile found.
What I need to do to fix it??
Thanks

**Comment by gnumdk** [comment]
Already explained, searching in previous bug reports
