### ISSUE TITLE
Requisites to compile (change to project documentation)

### ISSUE THREAD

**Issue by waldirbertazzijr** [gnumdk/lollypop#525]
Hi gnumdk,
I love lollypop. I'm reading your code so I can help you.
In a clean ubuntu gnome 15.10 install, after trying to compile lollypop for the first time I had to install the packages:
- libglib2.0-dev
- libgirepository1.0-dev

Then it compiled with no errors.
Shouldn't then be added to documentation?

**Comment by gnumdk** [comment]
I can't add documentation for every distro out.

But you can add page here: https://github.com/gnumdk/lollypop/wiki, no?
