### ISSUE TITLE
Information request: development and debugging.

### ISSUE THREAD

**Issue by coconutlulz** [gnumdk/lollypop#527]
Dear Cédric,

How do you develop and debug Lollypop? I've tried setting up an environment for convenient debugging, but I've run into some problems.

- The main 'lollypop' script requires files to be present in /usr/local, so that when a source file is updated, you have to make install again w/ root privileges? Doesn't sound ideal, so I tried...

- A virtualenv. It installs fine (after some tweaking), but Python cannot access the system GNOME settings via gio.

I don't want to go and hack all of your code just to get this working, so, how do you do it? :+1: 

Sorry for making clutter; GitHub got rid of its private message feature. In future, I can contact you on Twitter or something if you prefer.

BTW, I will add your response to your wiki.

**Comment by gnumdk** [comment]
I do make install as root (:

**Comment by gnumdk** [comment]
$ ./autogen.sh --prefix=/home/gnumdk/lollypop
$ make
$ make install
$ /home/user/lollypop/bin/lollypop
