### ISSUE TITLE
Some embedded album art in OGG files replaced with incorrect downloaded art, or ignored if there is no online art 

### ISSUE THREAD

**Issue by steve-d-mottram** [gnumdk/lollypop#530]
For OGG files, I noticed that some of the album art is missing or incorrect, even though I have ensured that all files in my collection have embedded art, which displays fine in Nautilus. The ones where no album art is shown are rare files, where my guess is there is no online art. OGG files with album names similar to other ones download or show the wrong art, even though the correct art is embedded.

**Comment by steve-d-mottram** [comment]
This is for Lollypop 0.9.91 from the Ubuntu PPA on Ubuntu GNOME 16.04 Beta

**Comment by gnumdk** [comment]
Send me a file by email.

**Comment by steve-d-mottram** [comment]
Will do - at work at the moment, but will send examples ASAP. Thanks for looking into it.

**Comment by gnumdk** [comment]
Works for me. Can't compare with nautilus as I have now preview in nautilus.

But easytag show same covers as Lollypop.

So the issue may be a broken gstreamer (Old ubuntu?)
