### ISSUE TITLE
Queue in playlists

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#531]
It would be great to be able to see and change the queue in more detail in the Playlists section. A long queue becomes difficult to manage in the small queue popup, especially when you want to move some tracks around.

**Comment by gnumdk** [comment]
Will not add queue in playlist because queue is not a playlist.
But you are write, should be easier to add track to a default playlist.

**Comment by gnumdk** [comment]
One more, lollypop is about albums, designed for album playback. 
Playlists are presents to enable user to set track list for later usage (phone sync, specific party, ...)
For others usages, you may use another player ;)
