### ISSUE TITLE
Unable to build from git

### ISSUE THREAD

**Issue by alan12345678** [gnumdk/lollypop#532]
Having too many issues now with the player so thought I'd try building my own copy. Following your instructions, have all dependencies (as far as I can tell) but autogen fails  with:

checking pkg-config is at least version 0.16... yes
./configure: line 13287: YELP_HELP_INIT: command not found
./configure: line 13288: syntax error near unexpected token `1.35.9'
./configure: line 13288: `GOBJECT_INTROSPECTION_REQUIRE(1.35.9)'

Is it me? Am I missing something? I have gobject-introspection-1.46.0-1. Should I delete my entire linux installation and start again??

Was loving the player until a recent update has completely screwed up the track/artist listings in the main panel... Can't currently build my own copy. Disappointing.

**Comment by gnumdk** [comment]
What distro? What is the issue with listings?

**Comment by alan12345678** [comment]
I'm on Fedora 23, 4.6 kernel.
 
The issue with the listings is probably best explained if I attach some
screen grabs, because it's all to do with how the current installed
version of Lollypop now seems to add a LOT of unnecessary information
about the artist per track when in fact the album artist and track
artist are mostly the same except where there might be a "featuring"
artist. This is difficult to explain verbally in terms of how the layout
gets too cluttered, so I'll edit up some grabs that hopefully explain
things more clearly, and attach them in another message :0)
*alan ansell figurative painting Itzac France*
He would be a poet who could impress the winds and streams into his
service, to speak for him.
- Henry David Thoreau
 
 
----- Original message -----

**Comment by blackjackshellac** [comment]
I had a very similar issue in Fedora 23 and found the information i needed in config.log

**Comment by alan12345678** [comment]
Hopefully the clips explain better

![01_lp_artist_good](https://cloud.githubusercontent.com/assets/17928308/14032044/95967ea2-f210-11e5-9df0-54779bdc0edb.jpg)
![02_lp_artist_notsogood](https://cloud.githubusercontent.com/assets/17928308/14032046/9663d8a2-f210-11e5-94a4-bbea9a0145dc.jpg)
![03_lp_artist_bad](https://cloud.githubusercontent.com/assets/17928308/14032048/981b0c24-f210-11e5-87bb-2caf7e7255e8.jpg)

@blackjackshellac: would you be prepared to enlighten me further? Obviously going to take a look at my config, but what was it you did that helped?

**Comment by gnumdk** [comment]
dnf build-dep lollypop or something like this

**Comment by gnumdk** [comment]
Send me tags for every screenshot, hard to guess what is happening... Or files via dropbox, my email in github...

**Comment by gnumdk** [comment]
Will only populate artist label for compilations and else put artist in tooltip

**Comment by gnumdk** [comment]
For frank sinatra, I guess you have something like this:
album artist: Frank Sinatra
artist: Franke Sinata, other artist

, isn't artist separator, it's ';'

**Comment by alan12345678** [comment]
Thanks again. Happy to help by sending files etc. but before I do, suppose I ought to clarify, just in case we're slightly at cross purposes here. Apologies for slightly long post ;0)

I'm not trying to insist that I "must" have this or that feature, or that the player "ought to" behave in this or that way, but in trying to migrate from Windows and leave it behind forever (yay!) by proving to myself that I can learn Linux and control, troubleshoot my apps etc. I do need to explore how possible it is to modify or control apps and the way they display their information. Otherwise what's the point in having an open system like Linux?

With regard to this music player and layout, tags etc: I really appreciate that you take the time to look into this and try to help. But my existing player (foobar2000) is in most respects the most utterly sublime thing because it is designed to allow the user to write the simplest of scripts to control it. As such I can VERY easily edit a little local file which controls every aspect of its visual style; thus I can specify font styles, sizes, colours etc. and can define which tags it reads, what order it displays their information, how and where on the screen it renders that information etc. So the player behaviour ends up laying out precisely controlled track/artist/album information. For this reason my music library has, over many years, developed this very 'refined' set of tags, which often includes composer information, original release dates, media type, multiple cover art (when different releases have it).

I realize I cannot have this player under Linux (refuse to use wine etc.) and that yours is different. However, I do not really understand why there is a need to insist on such rigid protocols regarding separation of tags, naming of tracks/albums or why or whether I should/should not separate my artists using "," or ";" or "|" or "&" etc. Surely it should be up to me the user, not the designer of the program, who may have entirely arbitrary reasons (or no particular reasons) for enforcing certain styles? Not trying to be unkind here, just askin'

So while I will say again that I deeply appreciate your willingness to engage in these issues and try to find solutions, I feel that perhaps were there simply menu options or tools available - by means of maybe check boxes? - or some other similar device that allows me the user of MY files to shape the way they are displayed, none of this need take up your time as "issues".

Let me finish by explaining the problem with classical music under current tag conditions. As before, I have to now use "album artist" in order to have all work by a particular composer group together. Thus the idea that the "album artist" might in fact have been the person or people performing said work has to be given up, otherwise I cannot find, e.g. "Mahler" and then look for "9th Symphony", because instead it would appear as "Karajan, Herbert von & etc". In such things as opera the list of contributing artists can be quite long. Equally, track titles tend to be the opening lines of a particular stanza. When applied to the Wagner example as per the photos, you can appreciate that what the display panel currently attempts to show (there is no screen big enough!" would be something like this:

Artist: Wagner
Album: Tristan und Isolde

Disc1
Track 5: Den als Tantris unerkant ich entlassen [Wagner, Seigfried Jerusalem, Matti Salminen, Berlin Philharmonic Orchestra, Berlin State Opera Chorus - Daniel Barenboim]
Tracj 6: etc.

When in fact, in this case, it should be perfectly possible (and sensible imo) to have:

Artist: Wagner
Album: Tristan und Isolde
Arists: Seigfried Jerusaleml, Matti Salminen, Berlin State Opera conducted by Barenboim 

Disc1
Track 5: Den als Tantris unerkant ich entlassen
Track 6: Auf! Auf!
etc.

I'm not convinced it must remain out of my control how the player displays whichever information I choose to add to my tags.

**Comment by gnumdk** [comment]
Closing this one as text is in tooltip now.
But you should set this in tags:
- album artist: Frank Sinatra
- artist: Frank Sinatra; Billy May

**Comment by gnumdk** [comment]
One more: #515

**Comment by gnumdk** [comment]
And I confirm this on Fedora:
dnf builddep lollypop

**Comment by alan12345678** [comment]
sure, could do.
 
But I have experimented extensively. I took one album and continually
added/removed tags, edited names, artists, titles, etc. and each time
"update library" for Lollypop to see the changes.
 
I would even be prepared to completely re-edit my entire library (three
days!) IF I were assured of some consistent, predictable behaviour.
Presently I cannot find this. I have this mixture, as shown in the
photos, of when everything is entirely smooth and predictable, and when
it is unpredictable because in the case of collaboration or a second or
featured artist, it displays BOTH the album artist, AND the
artist+second artist.
 
Thus for a track "Frank Sinatra featuring Nancy Sinatra" it will display
[Frank Sinatra, Frank Sinatra featuring Nancy Sinatra] after EACH track
title. This is not only redundant, but it fills up the display with
unnecessary information.
 
It will do this whether or not I add/remove tags under available
categories. It will do this whether or not I have the extended tags for
"albumartistsort" or "artistsort" added or not.
 
Small thing in the grand scheme of things I realise. Still a very nice
player, but very frustrating to not have finer grained control
 
:)
 
*alan ansell figurative painting Itzac France*
He would be a poet who could impress the winds and streams into his
service, to speak for him.
- Henry David Thoreau
 
 
----- Original message -----

**Comment by alan12345678** [comment]
thanks! That worked :0)
 
Will leave you in peace.
 
*alan ansell figurative painting Itzac France*
He would be a poet who could impress the winds and streams into his
service, to speak for him.
- Henry David Thoreau
 
 
----- Original message -----
