### ISSUE TITLE
Restore queue on restart

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#533]
Right now the queue is lost when you restart Lollypop, it would be better if it were saved somewhere so it can be restored.

**Comment by gnumdk** [comment]
Use playlists...

**Comment by d9h02f** [comment]
But then what's the point of having a queue at all?

**Comment by gnumdk** [comment]
Queue is about temporaly bypass current playlist like amarok/clementine/ryhotbox...
