### ISSUE TITLE
Setting window is so big

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#537]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

-Gtk Version: 3.19.92
-Linux distribution: Arch with Gnome

-Describe your bug here: 
I think that the settings windows can be resized from this
![capture du 2016-03-27 13-04-56](https://cloud.githubusercontent.com/assets/7660997/14065111/c8bbb9b0-f41c-11e5-88b7-3153120aa8f5.png)
to this
![capture du 2016-03-27 13-08-59](https://cloud.githubusercontent.com/assets/7660997/14065122/1633b8be-f41d-11e5-9684-9433ebd51ef5.png)

**Comment by gnumdk** [comment]
Will not change height, that the same in nautilus, more height for more content available in all tabs.
