### ISSUE TITLE
Lollypop isn't designed to work without an unicode locale. 

### ISSUE THREAD

**Issue by navjotjsingh** [gnumdk/lollypop#539]
-Gtk Version: 3.16.7/2.24.28
-Linux distribution: Ubuntu 15.10

Describe your bug here: 
As soon as I try to launch Lollypop, I get the error:
Lollypop isn't designed to work without an unicode locale. Please fix your system.

How to fix this?

**Comment by gnumdk** [comment]
You can't, python restriction.

**Comment by gnumdk** [comment]
See how to switch to Unicode on an Ubuntu Forum.
