### ISSUE TITLE
Add cover from a file

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#540]
For some albums, cover can't be found on the net.
It would be great to have possibility to add album covers from a local image.

**Comment by gnumdk** [comment]
Just put the cover in album directory.

**Comment by M5oul** [comment]
Ok. Thanks.

**Comment by gnumdk** [comment]
Do you really think a file dialog is needed?

**Comment by gnumdk** [comment]
Was easy ;)

**Comment by M5oul** [comment]
Thanks, that's a great feature :smile_cat: 
Sorry, I don't get notifications for issues I posted on this repository.
I don't want to get informed about all of what is happening on this repository, but only my issues.
Do you know if it's possible?

**Comment by gnumdk** [comment]
No, don't know...
