### ISSUE TITLE
Help with this (small) error please

### ISSUE THREAD

**Issue by alan12345678** [gnumdk/lollypop#541]
Knowing a fair bit more about Linux than I did when first used your wonderful player, just ran it from terminal and got the following output. I'm not interested in Wikipedia, but from the below - I see there's a couple of things there I definitely need to address.

Please note: after a number of other systemwide problems, I wiped and reinstalled my entire Fedora installation. I then added the copr repo and downloaded that package and installed lollypop. Have made NO other changes. But I get this error. Note, I just ran "sudo dnf install pylast" - which it did. After reboot, message still present.

>>

No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia

** (lollypop:3097): CRITICAL **: totem_pl_parser_parse_with_base_async: assertion 'strstr (uri, "://") != NULL' failed

<<

**Comment by gnumdk** [comment]
dnf search pylast

**Comment by region51** [comment]
@alan12345678 sudo dnf install python3-pylast

**Comment by region51** [comment]
@alan12345678 python3-wikipedia http://koji.russianfedora.pro/koji/packageinfo?packageID=178
