### ISSUE TITLE
add tooltip for radio

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#543]
little enhancement for lollypop
![screenshot from 2016-04-02 14-46-32](https://cloud.githubusercontent.com/assets/13280183/14226163/5219b97c-f8e2-11e5-9419-59120d3cb815.png)
New radio?
![screenshot from 2016-04-02 14-46-39](https://cloud.githubusercontent.com/assets/13280183/14226164/5720c564-f8e2-11e5-801f-b6132aac7138.png)
can be added tooltip "Add a new radio station"

**Comment by gnumdk** [comment]
Tooltip are for truncated strings or button without strings...

**Comment by region51** [comment]
@gnumdk 
>Tooltips are for truncated strings or buttons without strings...

hmmm
![screenshot from 2016-04-03 18-10-37](https://cloud.githubusercontent.com/assets/13280183/14233113/c8e54f40-f9c7-11e5-9c38-b4644f95c6fa.png)

**Comment by gnumdk** [comment]
Same in nautilus, will not add a tooltip if does not add information...
