### ISSUE TITLE
Untranslated tooltip

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#544]
-Lollypop version: master, commit e70489e3eecd25595888519cb6f2f5cd580e3757.
-Gtk Version: 3.18.9
-Linux distribution: Fedora 23

Found one tooltip which isn't translated or the translation isn't used.

![tooltip](https://cloud.githubusercontent.com/assets/4953862/14244982/94c07fc2-fa5e-11e5-9159-f32b3b7b30c8.png)

**Comment by gnumdk** [comment]
Transifex is updated just before release ;)

**Comment by gnumdk** [comment]
Done ;)

**Comment by kostich** [comment]
Ah, so you pull new strings from Transifex before the releas? Sorry for the noise then... :)

**Comment by gnumdk** [comment]
Is it ok now?

I'm trying to catch last bugs before releasing... (today I hope)

**Comment by kostich** [comment]
I've listened songs today and it worked. Just tried radio stations and it seems that there's an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/view.py", line 79, in _disable_overlays
    widget.set_overlay(False)
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album.py", line 163, in set_overlay
    self._artwork_button.hide()
AttributeError: 'RadioWidget' object has no attribute '_artwork_button'
```
You can trigger it by starting to play a radio station, hover a couple of times over the "cover image" of the radio, and then try to pause the radio station by clicking on the pause, in the headerbar. As soon as your mouse cursor leaves the radio cover image and enters the proximity of the headerbar widget, Lollypop crashes.

I am unable to reproduce it reliably sadly, so I can't open a proper bug report. :(

Also, one more thing. Maybe you should create a list of things for checking before releasing a new build. Something like "check if radios work, check if random playing works, check if full screen works etc". :)
