### ISSUE TITLE
Crashing while playing or viewing radio streams on 0.9.92

### ISSUE THREAD

**Issue by uzvermode** [gnumdk/lollypop#545]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

-Lollypop version:```0.9.92-1ppa1ubuntu1.1```
-Gtk Version:```3.18.9-1ubuntu3```
-Linux distribution: Ubuntu 16.04, latest updates

-Describe your bug here:
Application crash after few seconds of playing radio stream or just mouseover radio artwork with console output:
```Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/view.py", line 79, in _disable_overlays
    widget.set_overlay(False)
  File "/usr/lib/python3/dist-packages/lollypop/widgets_album.py", line 163, in set_overlay
    self._artwork_button.hide()
AttributeError: 'RadioWidget' object has no attribute '_artwork_button'```

**Comment by region51** [comment]
press Search in Tunein
```
[maxim@localhost ~]$ lollypop
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/view.py", line 79, in _disable_overlays
    widget.set_overlay(False)
  File "/usr/lib/python3.4/site-packages/lollypop/widgets_album.py", line 163, in set_overlay
    self._artwork_button.hide()
AttributeError: 'RadioWidget' object has no attribute '_artwork_button'

```

**Comment by region51** [comment]
https://github.com/gnumdk/lollypop/issues/544#issuecomment-205273112

**Comment by gnumdk** [comment]
Will release 0.9.93 today.
