### ISSUE TITLE
Restore state on startup

### ISSUE THREAD

**Issue by blackjackshellac** [gnumdk/lollypop#547]
-Lollypop version: git master, commit f8884fc8aa1015ff284c52da5ecef85393d83192
-Gtk Version: gtk3-3.18.9-1.fc23.x86_64
-Linux distribution: Fedora 23

-Describe your bug here:

Restore state on startup doesn't restore the play state, or the current location in the track playing.  It would seem to me that the state of playback and song location should be restored after restarting.

**Comment by gnumdk** [comment]
Will not restore position, who need this ?

For state, I need user feedback, as I will not add another option.

**Comment by d9h02f** [comment]
Why remember the song it's on when it doesn't remember the position in the song? For things like mixtapes, it's definitely nice if you don't have to remember where you were. Of course for short songs it isn't necessary, but only remembering the position if the song is over xx minutes long is probably not a good idea either.

As for the state, I don't think that's a good idea, because you have to remember what you were listening to if you don't want to wake up your neighbours in the morning with loud music starting to play as soon as you open up Lollypop.

**Comment by blackjackshellac** [comment]
I was also thinking of podcasts/audiobooks where returning to the position you left off after a reboot/whatever would be nice.  As it stands I have to record the position and then slide back to where I was, something that is easy to forget to do.  I can live with clicking play after restarting :)

**Comment by kostich** [comment]
+1 for remmembering song position. I think Winamp used this and as d9h02f said, it's usefull when listening to a longer song. I also do not want Lollypop remmembering state/automatically starting to play songs when opened.

**Comment by gnumdk** [comment]
Ok:
- No state restore
- Will add a GtkScale marker for position but will not restore it by default

**Comment by gnumdk** [comment]
On more, restore state is buggy in stable :(

**Comment by blackjackshellac** [comment]
Excellent, cheers, merci bien, grazie.

**Comment by blackjackshellac** [comment]
The restore position on restart feature seems to be broken.  You said above that you would "not restore it by default", but I couldn't find an option to enable it in preferences or dconf-editor.

**Comment by gnumdk** [comment]
Restore state in options.

**Comment by gnumdk** [comment]
And the option only add a maker in slider.

**Comment by blackjackshellac** [comment]
Okay, I misunderstood, at one point it did restore position on restart.  But I don't see a marker (on Fedora 23 with gtk 3.18.9-1).
![screenshot from 2016-05-18 10-13-44](https://cloud.githubusercontent.com/assets/825403/15361884/60564ab4-1ce1-11e6-8538-abcbe999cf5e.png)

**Comment by gnumdk** [comment]
It only save position in current playing stream on quit.

**Comment by region51** [comment]
_@blackjackshellac F23, Restore state on startup_
![screenshot from 2016-05-18 17-31-08](https://cloud.githubusercontent.com/assets/13280183/15362667/aefa9bce-1d1e-11e6-904a-372986fe9c96.png)

**Comment by blackjackshellac** [comment]
Strange, I'm not seeing it. (top image

* Before restart ![screenshot from 2016-05-18 10-49-51](https://cloud.githubusercontent.com/assets/825403/15363401/9f39bb8a-1ce6-11e6-8579-10692df62b47.png)

* After restart ![screenshot from 2016-05-18 10-50-05](https://cloud.githubusercontent.com/assets/825403/15363402/9f39ed58-1ce6-11e6-9072-881f08a227c4.png)

Don't see anything particularly interesting in the log either,

```
$ lollypop 
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

```

**Comment by region51** [comment]
_@blackjackshellac check with Adwaita gtk._

**Comment by blackjackshellac** [comment]
I switched back to Adwaita for GTK+ (in tweak tool).  Still no luck.

By your postscript, you mean to quit without pausing?

**Comment by region51** [comment]
_YES_

**Comment by blackjackshellac** [comment]
Yes, those were the two issues.  The arc theme apparently doesn't have that little niblink marker.  Also, I was usually pausing before quitting.  After switching back to Adwaita and NOT pausing before quitting I see the marker.  Seems that it should support either paused or play state.
