### ISSUE TITLE
Idea: List genre next to album

### ISSUE THREAD

**Issue by MineyMe** [gnumdk/lollypop#55]
Hello

This is not really a future request but more of an idea (that could turn into a feature). Would it be a good idea to list the genre(s) of an album somewhere around the album itself? This would not only be informational but these genres could also be clickable, which simply activates the genre view and then navigates to the genre, listing all other albums using the same genre. It would serve a bit as a "I'm listening to an album right now and am in the mood for more of the same genre".

**Comment by gnumdk** [comment]
Sorry don't like this one...

When you display an album, lollypop is already displaying artists from genre, it will only be ok when listing all artist.... (not in a genre context)

And i don't want to bloat ui with to many informations ;)

regards,
