### ISSUE TITLE
no tooltip for update

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#550]
-Describe your bug here:
![screenshot from 2016-04-06 16-41-43](https://cloud.githubusercontent.com/assets/13280183/14318762/17e33a48-fc17-11e5-94f9-c9d25c0c8a43.png)

**Comment by gnumdk** [comment]
Yes, need to  be fixed, many release I miss this one

**Comment by region51** [comment]
@gnumdk also
![screenshot from 2016-04-06 16-53-13](https://cloud.githubusercontent.com/assets/13280183/14319071/6abf3086-fc18-11e5-8665-868ff1f3c404.png)

**Comment by region51** [comment]
@gnumdk also
![screenshot from 2016-04-06 18-17-31](https://cloud.githubusercontent.com/assets/13280183/14322033/26bcb37a-fc24-11e5-884a-c0b5634dad68.png)

**Comment by gnumdk** [comment]
You will not see all tooltips due to a GTK bug... No tooltip for buttons in a Gtk.Overlay :-(
