### ISSUE TITLE
Stopped working after I restarted my system

### ISSUE THREAD

**Issue by deyyard** [gnumdk/lollypop#553]
Even through it apparently have no support for freya, i was using the version 0.9.92 here and it was working great, but, after i updated to 0.9.94 and restarted my system it opens and this screen shows:

http://i.imgur.com/s4HOwVw.png

How can I fix it? I've already tried to install 0.9.92 but it didn't worked (english isn't my native language sorry)

**Comment by gnumdk** [comment]
What is terminal output?

**Comment by gnumdk** [comment]
Elementary OS is supported ;)

**Comment by alex-kovac** [comment]
hi! (and XL thanks for amazing work!)
I have a similar problem. Lollypop worked nicely on 0.9.92. 0.9.94 initially worked nicely yesterday, too. This morning, no luck. Clicking on the icon does not start Lollypop. Reinstalling did not help. This is Terminal output after running Lollypop command in Terminal.
```
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 25, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3/dist-packages/lollypop/application.py", line 40, in <module>
    from lollypop.window import Window
  File "/usr/lib/python3/dist-packages/lollypop/window.py", line 15, in <module>
    from lollypop.container import Container
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 22, in <module>
    from lollypop.view_artist import ArtistView
  File "/usr/lib/python3/dist-packages/lollypop/view_artist.py", line 18, in <module>
    from lollypop.pop_info import InfoPopover
  File "/usr/lib/python3/dist-packages/lollypop/pop_info.py", line 21, in <module>
    from lollypop.widgets_web import OpenLink
  File "/usr/lib/python3/dist-packages/lollypop/widgets_web.py", line 14, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 79, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available
```

Lollypop v0.9.94
Elementary OS v0.3.2 Freya

If I can provide any other info, please let me know.

**Comment by gnumdk** [comment]
@alex-kovac #554

**Comment by deyyard** [comment]
How I see the terminal output?

**Comment by gnumdk** [comment]
Run lollypop in gnome-terminal

**Comment by alex-kovac** [comment]
Thanks for the reply! I tried the proposed solutions, unfortunately ended up in similar waters like #562

**Comment by gnumdk** [comment]
@deyyard ?

**Comment by gnumdk** [comment]
@deyyard Ok, as a workaround:
$ rm -f ~/.local/share/lollypop/lollypop.db

Don't know why upgrade failed... If you have more informations, reopen

**Comment by alex-kovac** [comment]
The latest 0.9.95 works for me! @gnumdk thanks for the work. ninja intercontinental work. Enjoy Paris.
