### ISSUE TITLE
Change artwork or Append?

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#555]
-Describe your bug here:
lollypop-0.9.91/92 Change artwork
![0 9 91 and 0 9 92](https://cloud.githubusercontent.com/assets/13280183/14354427/f1dc3ae6-fce5-11e5-887f-1f82e4ddc330.png)

lollypop-0.9.94 Append
![0 9 94](https://cloud.githubusercontent.com/assets/13280183/14354438/f756e570-fce5-11e5-977a-de043cc41275.png)

What is right?

**Comment by gnumdk** [comment]
None :)
