### ISSUE TITLE
Lollypop freezes when right-click on context menu

### ISSUE THREAD

**Issue by rCarto** [gnumdk/lollypop#557]
-Lollypop version: 0.9.94
-Gtk Version: 3.16.7-0ubuntu3
-Linux distribution: Ubuntu 15.10

-Describe your bug here:
Lollypop freezes when I right click on the album-context menu.
![capture d ecran_2016-04-08_09-58-31](https://cloud.githubusercontent.com/assets/3041254/14377659/450962b2-fd71-11e5-8e33-9f8e95b80ff9.png)

**Comment by gnumdk** [comment]
So my hack is not working :(
