### ISSUE TITLE
Commas in track title

### ISSUE THREAD

**Issue by pepewu** [gnumdk/lollypop#558]
-Lollypop version: 0.9.94
-Gtk Version: 3.18.9
-Linux distribution: Fedora 23, x86_64

-Describe your bug here: After opening a file from the file browser (double click or 'open with' in Nautilus) the track title on top bar gets commas after each character. The same track opened directly from Lollypop library is fine.
![screenshot from 2016-04-08](https://cloud.githubusercontent.com/assets/3642414/14396761/b983c9ee-fdd9-11e5-8016-22f434e53ae4.png)

**Comment by blackjackshellac** [comment]
Can confirm same with master

**Comment by region51** [comment]
I have this very same problem Fedora 23, lollypop-0.9.94 http://i.imgur.com/BTuFt0G.png

**Comment by d9h02f** [comment]
This also happens when a new addition to the library automatically starts playing as soon as it's been added, even when you're listening to something else already, which is probably a different bug.
