### ISSUE TITLE
If main window is closed, exiting fullscreen mode always closes Lollypop

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#559]
Even when "Continue playback when closed" is enabled, Lollypop gets closed when you close the fullscreen mode when you closed the main window before. I think it should keep playing, and maybe open the main window again.

**Comment by gnumdk** [comment]
What Wm?

**Comment by d9h02f** [comment]
Just GDM, standard GNOME installation. GNOME 3.16, so maybe it's a bug fixed in 3.18/3.20 already.
