### ISSUE TITLE
Idea: Internet radio support

### ISSUE THREAD

**Issue by MineyMe** [gnumdk/lollypop#56]
Hello

It would be neat if somehow Lollypop could play internet radio (i.e. if you know the hostname or address of the stream). You could even have an 'Internet Radio' entry in the left sidebar and allow adding URL's (and potentially a title) here (or in the settings dialog), Lollypop could always set the genre/album to "Internet Radio".

I thought about what you mentioned earlier about that Lollypop is designed to only use files from your music library. Perhaps this could be solved by having files (of a custom format?) that represent the radio stations, much like Winamp's PLS/M3U format:

```
[playlist]
numberofentries=1
File1=http://somesite.com:80/radio
Title1=Name of radio station
Length1=-1
Version=2
```
This way you could have a directory that contained a bunch of these files, each for a different radio station. Although of course a GUI option is much more user friendly.

Hope this gives you some idea's :)

**Comment by gnumdk** [comment]
#38
