### ISSUE TITLE
Lollypop cant start - Ubuntu - Elementary Freya

### ISSUE THREAD

**Issue by Matvyenko** [gnumdk/lollypop#562]
-Lollypop version: 0.9.94
-Gtk Version: 3.14.15-0ubuntu1~14.04~ricotz1
-Linux distribution: Elementary Os Freya 0.32

================================================

-Describe your bug here: Lollypop cant start.

- #553 similar bug

- The reference given by @gnumdk  to @alex-kovac was for Ubuntu 15.04 fixes does not work on my system. 

- Solution provided in #552 not available for Freya 0.32

- Installing gir1.2-webkit-3.0 does not fixes the issue.

- Installing gir1.2-webkit2-3.0 does not fixes the issue.

- Cant Install sudo apt-get install gir1.2-webkit2-4.0 - Not available for my current version

_If you have a Ubuntu distro >14.04 you could try any of these:
(DOES NOT WORK WITH ELEMENTARY)_

 sudo apt-get install gir1.2-webkit-3.0

 sudo apt-get install gir1.2-webkit2-3.0 

 sudo apt-get install gir1.2-webkit2-4.0

================================================

-Terminal output:

matvyenko@matvyenko-note:~$ lollypop
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 25, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3/dist-packages/lollypop/application.py", line 40, in <module>
    from lollypop.window import Window
  File "/usr/lib/python3/dist-packages/lollypop/window.py", line 15, in <module>
    from lollypop.container import Container
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 22, in <module>
    from lollypop.view_artist import ArtistView
  File "/usr/lib/python3/dist-packages/lollypop/view_artist.py", line 18, in <module>
    from lollypop.pop_info import InfoPopover
  File "/usr/lib/python3/dist-packages/lollypop/pop_info.py", line 21, in <module>
    from lollypop.widgets_web import OpenLink
  File "/usr/lib/python3/dist-packages/lollypop/widgets_web.py", line 14, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 79, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available

================================================

**Comment by pawelad** [comment]
Let me just leave it here - https://github.com/gnumdk/lollypop/issues/552#issuecomment-207587382

**Comment by gnumdk** [comment]
Already fixed in git

**Comment by gnumdk** [comment]
Will release a fix tomorrow I hope... Leaving Angers City to Paris this night for 3 days so a little busy now... Sorry EOS users ;)
