### ISSUE TITLE
Lollypop doesn't play music on gnome 3.20

### ISSUE THREAD

**Issue by ksolsim** [gnumdk/lollypop#563]
-Lollypop version: 0.9.91
-Gtk Version: 3.20.2
-Linux distribution: Arch Linux

-Describe your bug here:
If I launch lollypop and click play on a song it doesn't work (no sound). If I run lollipop from a terminal I get only this when I start the application:

(lollypop:18556): Gtk-WARNING **: Theme parsing error: application.css:5:27: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(lollypop:18556): Gtk-WARNING **: Theme parsing error: application.css:185:18: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(lollypop:18556): Gtk-WARNING **: Theme parsing error: application.css:192:18: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(lollypop:18556): Gtk-WARNING **: Theme parsing error: application.css:199:18: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

**Comment by gnumdk** [comment]
$ pacman -S gst-libav

**Comment by ksolsim** [comment]
thanks, works.
