### ISSUE TITLE
no name/icon in appmenu after fullscreen

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#566]
-Lollypop version: 0.9.95
-Gtk Version: 3.18.9
-Linux distribution: Fedora 23
-GNOME Shell:
```
[maxim@ip194-13 ~]$ gnome-shell --version
GNOME Shell 3.18.4
```
-Describe your bug here: no name/icon in appmenu after fullscreen
![screenshot from 2016-04-12 13-15-33](https://cloud.githubusercontent.com/assets/13280183/14457090/f54a192c-00b0-11e6-9d2c-14cb5eb5bac0.png)
Toggle fullscreen mode/Exit fullscreen mode
![screenshot from 2016-04-12 13-15-38](https://cloud.githubusercontent.com/assets/13280183/14457123/108e110c-00b1-11e6-895d-6f631b60d49a.png)

**Comment by gnumdk** [comment]
Gnome shell bug, will fix it.

**Comment by region51** [comment]
@gnumdk in lollypop-0.9.94 all is well

**Comment by gnumdk** [comment]
I know, but it's a gnome shell bug.

**Comment by region51** [comment]
@gnumdk :+1: works for me
