### ISSUE TITLE
add radio crash

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#569]
-Lollypop version: 0.9.95
-Gtk Version: 3.18.9
-Linux distribution: Fedora 23

-Describe your bug here: add new radio crash
```
[maxim@ip194-13 ~]$ lollypop
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/view_radios.py", line 180, in _on_radios_changed
    name = widget.get_name()
AttributeError: 'NoneType' object has no attribute 'get_name'

```

**Comment by gnumdk** [comment]
You should use git master if you really want me to release a stable version with radios  (I do not listen to radios)

**Comment by hussyy** [comment]
fixed here for you gnumdk! https://github.com/gnumdk/lollypop/pull/570/commits/8d99e8e30560e54d45d9a8dbfce89decfc07afcc

**Comment by region51** [comment]
>You should use git master if you really want me to release a stable version with radios (I do not listen to radios)

I always use release https://github.com/gnumdk/lollypop/releases
http://koji.russianfedora.pro/koji/packageinfo?packageID=150
