### ISSUE TITLE
Lollypop crashes on queue toggle

### ISSUE THREAD

**Issue by ngquerol** [gnumdk/lollypop#57]
Hi !

I installed Lollypop through AUR, version 0.9.5. Every time I click on the "Queue" widget, it opens a popover, and when I click again on the widget or somewhere else, Lollypop crashes with the following trace:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/queue.py", line 110, in do_hide
    Objects.player.disconnect_by_func(self._on_current_changed)
TypeError: nothing connected to <bound method QueueWidget._on_current_changed of <QueueWidget object at 0x7fbe100de5a0 (lollypop+queue+QueueWidget at 0x7fbe23522dc0)>>
```

Hope everything's clear, let me know if not.

**Comment by gnumdk** [comment]
Fixed in master...
Will release 0.9.10 soon (next week).

**Comment by gnumdk** [comment]
$ yaourt lollypop-git ;)
