### ISSUE TITLE
Genre case sensitivity

### ISSUE THREAD

**Issue by blackjackshellac** [gnumdk/lollypop#572]
-Lollypop version:master e835e2df83535bd3ea4d09ba1bd8817db63453c1
-Gtk Version: gtk3-3.18.9-1.fc23.x86_64
-Linux distribution: Fedora 23

-Describe your bug here:

When the "Show genres" preference is selected, "Jazz" and "jazz" are shown in separate list entries.  This doesn't seem to be the case with the Artists list (but that may just be because they are more consistently tagged, the exception being diacritical variants like Bjork & Björk.)  Should genre tags really be considered case sensitively?

**Comment by gnumdk** [comment]
I know no player using non case sensitive tagging.

It's hard because it will force me to set "jazz" tag as "Jazz" but what is user really want it as "jazz"?
