### ISSUE TITLE
Gnome - Lock screen notification / controls for lollypop

### ISSUE THREAD

**Issue by kaldoran** [gnumdk/lollypop#573]
-Lollypop version: 0.9.91
-Gtk Version: 3.20.2-1
-Linux distribution: gnome 3.20
Linux localhost 4.4.5-1-ARCH 1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux

Since  GNOME Shell 3.6, lock screen include notification, some music player add control on this same lock screen [like a notification].
I would love to knwo if you are going to to this to, would love this feature.

Thanks

**Comment by gnumdk** [comment]
Should be working since last release

**Comment by kaldoran** [comment]
I've got the notification when i switch for a new song (and screen is locked),  but i've got no control panel. ( To play next song i lock the screen and use my keyboard shortcut )

**Comment by kaldoran** [comment]
So, i've update to version 0.9.95, and they do not work :/
Is there something special to add ? Or something to do to activate them ?

Thanks

**Comment by gnumdk** [comment]
From my testing, this feature doesn't exist anymore in GNOME even with Music and Rhythmbox.

**Comment by gnumdk** [comment]
Reopen if you know how to make this working with music
