### ISSUE TITLE
Artist and Album Artist

### ISSUE THREAD

**Issue by pawelad** [gnumdk/lollypop#574]
Did you dropped suport for `Artist`/`Album Artist` separation? I remember that it worked great in previous versions, it was rendered great in the UI - album shows under `Album Artist` but `Artist` is shown above each track and value from `Artist` is scrobbled.
Now I don't see track's `Artist` anywhere (if it's different then its `Album Artist`), and incorrect `Ablum Artist` value is now scrobbled - is that on purpose?

**Comment by gnumdk** [comment]
No, can you show me examples?

**Comment by pawelad** [comment]
![zrzut ekranu z 2016-04-13 22 59 33](https://cloud.githubusercontent.com/assets/7062874/14509315/ed64c54c-01cb-11e6-806c-65f7852ca531.png)
![zrzut ekranu z 2016-04-13 22 59 06](https://cloud.githubusercontent.com/assets/7062874/14509314/ed48cfb8-01cb-11e6-8559-1b52091b2a55.png)

**Comment by gnumdk** [comment]
Oh yes it's wanted, information is in a tooltip when hovering a track.
Showing this when having tracks with many artists was ugly else.

**Comment by gnumdk** [comment]
In your example, it's a compilation, album artist should be empty and inthis case artist will be shown.

**Comment by gnumdk** [comment]
Will restore previous behaviour when having only one artist.

**Comment by pawelad** [comment]
I actually really liked the way you previously showed it : ) Now there's no info about it in the main album view, but I get your point.

What about scrobbling though? I now noticed that it changes to proper artist after the track is done (don't know if that's because your code or is last.fm correcting it), so that's not a big problem, but the 'Now playing' is probably a little bug.
