### ISSUE TITLE
Mini mode

### ISSUE THREAD

**Issue by hypothesist** [gnumdk/lollypop#576]
Would be really amazing if you could implement a mini-mode like in iTunes or something.

**Comment by region51** [comment]
Ctrl + m for Mini player
![screenshot from 2016-04-16 19-11-46](https://cloud.githubusercontent.com/assets/13280183/14582194/1575c3d2-0407-11e6-816d-aabb5f28deda.png)

**Comment by hypothesist** [comment]
Thanks!

**Comment by gnumdk** [comment]
@hypothesist Or just resize window
