### ISSUE TITLE
Mini player view

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#577]
-Lollypop version: 0.9.86 >= 

-Describe your bug here:
normal view
![screenshot from 2016-04-16 19-21-55](https://cloud.githubusercontent.com/assets/13280183/14582272/44b73a3e-0409-11e6-9710-8184d66b90a2.png)
broken right click view
![screenshot from 2016-04-16 19-22-10](https://cloud.githubusercontent.com/assets/13280183/14582280/5e3660a2-0409-11e6-9618-2b1081456eca.png)

**Comment by gnumdk** [comment]
This is an Xorg bug... Will not happend on wayland. Can't fix it.

**Comment by gnumdk** [comment]
https://www.youtube.com/watch?v=eiQQJ-swnh8

**Comment by region51** [comment]
@gnumdk OK.
