### ISSUE TITLE
MTP sync, album artist regression (#468)

### ISSUE THREAD

**Issue by neckcen** [gnumdk/lollypop#579]
e814f262104efd94e3c629ba510cf7f9cfbe1615 reverted changes introduced with #468. Not sure if it is intended.

(Sorry for opening a new issue, but it seems old one won't notify)

**Comment by gnumdk** [comment]
Should be fixed in 0.9.96 to be released very soon.

**Comment by neckcen** [comment]
Lightning fast as usual, thanks!

**Comment by rCarto** [comment]
I still have multiple folder (one by artist) in compilation sync. (lollypop v0.9.203)

**Comment by gnumdk** [comment]
Open a new feature request, not handled by lollypop...
