### ISSUE TITLE
Last.fm scrobbling stopped working

### ISSUE THREAD

**Issue by lvcivs** [gnumdk/lollypop#580]
Scrobbling to last.fm stopped working for me. My last recorded "scrobble" was on 5. April, after that it just stopped. I don't see the menu list item "Last.fm" anymore in the preferences.

-Lollypop version: 0.9.97 (installed from PPA https://launchpad.net/~gnumdk/+archive/ubuntu/lollypop )
-Linux distribution: Xubuntu 15.10 wily (Xfce Desktop)

**Comment by gnumdk** [comment]
Strange, seems lollypop detect you are using Gnome Online Accounts :-(

**Comment by gnumdk** [comment]
Can you execute this in python3 command line:

`
from gi.repository import Goa

c = Goa.Client.new_sync()
for proxy in c.get_accounts():
   print(proxy.get_account().props.provider_name)
`

**Comment by lvcivs** [comment]
```
:~$ python3
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
>>> from gi.repository import Goa
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2158, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 144, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Goa, introspection typelib not found
```

I don't have gnome-online-accounts or libgoa-* packets installed.

**Comment by gnumdk** [comment]
What is lollypop saying when launched from command line?

**Comment by lvcivs** [comment]
```
:~$ lollypop 
Namespace Goa not available
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Namespace WebKit2 not available
WebKit support disabled
```

**Comment by gnumdk** [comment]
One more release tomorrow as it's an important bug ;)

**Comment by lvcivs** [comment]
Thank you for the fast fix!

Lollypop is a great program, btw :)
