### ISSUE TITLE
Player not working

### ISSUE THREAD

**Issue by rohanprasad** [gnumdk/lollypop#581]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

-Lollypop version: 0.9.97
-Gtk Version: libgtk-3-0:amd64, libgtk2.0-0:amd64 
-Linux distribution: elementary OS 0.3.2 Freya (64-bit)

-Describe your bug here: The music player doesnt plays any music. Opening file opens the player but music is not loaded. It also cannot find any music files on my system. On running via command line the following output is received:

Namespace Secret not available
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
Namespace WebKit2 not available
WebKit support disabled

** (lollypop:22888): CRITICAL **: totem_pl_parser_parse_with_base_async: assertion 'strstr (uri, "://") != NULL' failed

**Comment by gnumdk** [comment]
http://packages.ubuntu.com/fr/trusty/gstreamer1.0-libav

**Comment by rohanprasad** [comment]
I have the latest version of gstreamer1.0-libav

It still doesn't works. The error is same.

**Comment by gnumdk** [comment]
Strange, here working on EOS Freya on my test laptop.

**Comment by gnumdk** [comment]
Does it works with Gnome Music?

**Comment by gnumdk** [comment]
Maybe this one on Ubuntu: http://packages.ubuntu.com/trusty/libs/gstreamer1.0-fluendo-mp3

**Comment by rohanprasad** [comment]
Just found out it is also not working using gnome-music. The following error occors:

** (gnome-music:4005): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-4sL3LoFHuJ: Connection refused

(gnome-music:4005): GLib-GIO-CRITICAL **: This application can not open files.

**Comment by rohanprasad** [comment]
Thank you,
But gstreamer1.0-fluendo-mp3 is also already installed. Problem still not resolved.

**Comment by rohanprasad** [comment]
After installing banshee I can run some music files but not the others and I'll look into it. But I am still receiving this error:

** (lollypop:12994): CRITICAL **: Unable to determine array length for 0x7facfc0823f0
AlbumArt::pixbuf_from_tags(): Unrecognized image file format

(lollypop:12994): Gtk-WARNING **: GtkOverlay does not have a property called index

(lollypop:12994): Gtk-WARNING **: GtkOverlay does not have a property called index

** (lollypop:12994): CRITICAL **: Unable to determine array length for 0x7fad180be850
AlbumArt::pixbuf_from_tags(): Unrecognized image file format

** (lollypop:12994): CRITICAL **: Unable to determine array length for 0x7fad14079bf0
AlbumArt::pixbuf_from_tags(): Unrecognized image file format

** (lollypop:12994): CRITICAL **: Unable to determine array length for 0x7fad1819d4b0
AlbumArt::pixbuf_from_tags(): Unrecognized image file format

** (lollypop:12994): CRITICAL **: Unable to determine array length for 0x7face8076bf0
AlbumArt::pixbuf_from_tags(): Unrecognized image file format

** (lollypop:12994): CRITICAL **: Unable to determine array length for 0x7face40807f0
AlbumArt::pixbuf_from_tags(): Unrecognized image file format


Any idea how to resolve this?

**Comment by gnumdk** [comment]
No, ask on ubuntu forum

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/512

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/392
