### ISSUE TITLE
Support mpd

### ISSUE THREAD

**Issue by Anachron** [gnumdk/lollypop#583]
Is it possible to provide mpd support? 

This way I could bind my beets library via mpd to Lollypop to make use of both my favorite programs.

Basically Lollypop wouldnt need to use its own Library and query mpd instead. 

The advantage is here that mpd is not locally bound and beets will already have tagged all music automatically.

**Comment by gnumdk** [comment]
No sorry, not lollypop purpose. And mpd protocol really sucks.
