### ISSUE TITLE
Playlist: Random Track causes crash

### ISSUE THREAD

**Issue by kc135pirate** [gnumdk/lollypop#584]
-Lollypop version: 0.9.98
-Gtk Version: 3.20.3-1
-Linux distribution: Arch

-Describe your bug here: Whenever i select random track from the playlist menu, lollypop crashes.

**Comment by gnumdk** [comment]
Please post output by running lollypop from command line.

**Comment by kc135pirate** [comment]
tankrtoad@Arch ~> lollypop 

(lollypop:17238): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x23bc980 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:17238): Gtk-WARNING **: Allocating size to lollypop+selectionlist+SelectionList 0x23d85a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_playlist.py", line 206, in _add_tracks
    track.album.id != previous_album_id)
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_track.py", line 261, in __init__
    Row.__init__(self, rowid, num)
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_track.py", line 50, in __init__
    self._title_label = Gtk.Label.new(self._track.formated_name())
  File "/usr/lib/python3.5/site-packages/lollypop/objects.py", line 235, in formated_name
    if album_artist_ids[0] == Type.COMPILATIONS:
IndexError: list index out of range
tankrtoad@Arch ~>

**Comment by gnumdk** [comment]
Please send me this file by email:
~/.local/share/lollypop/lollypop.db

**Comment by gnumdk** [comment]
And give me a track exemple making lollypop quit.

**Comment by gnumdk** [comment]
Fixed by https://github.com/gnumdk/lollypop/commit/1c6adf51df8bd9590a129c43c7edac8e7d2ae9bd
