### ISSUE TITLE
Crash when trying to raise window

### ISSUE THREAD

**Issue by ariasuni** [gnumdk/lollypop#585]
- Lollypop version: 0.9.98
- Gtk Version: 3.20.3
- Linux distribution: Arch Linux

In Plasma, there’s a MPRIS plasmoid with a button to raise the window of the active music player. When I clic on it, the application immediately crash with the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 59, in on_method_call
    result = getattr(self, method_name)(*args)
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 175, in Raise
    self._app.do_activate()
TypeError: Gio.Application.activate() takes exactly 1 argument (0 given)
```

**Comment by gnumdk** [comment]
Should be fixed by https://github.com/gnumdk/lollypop/commit/1c21a799b64fa1b49940b5a299d04c3dcc6c413c

**Comment by ariasuni** [comment]
Doesn’t crash anymore :)
