### ISSUE TITLE
Japanese artists sorting is inconsistent (hiraganas seems ignored)

### ISSUE THREAD

**Issue by ariasuni** [gnumdk/lollypop#586]
- Lollypop version: 0.9.98
- Gtk Version: 3.20.3
-Linux distribution: Arch Linux

What I understand to this point:

- a few hiraganas seems ignored, so that `みなとP` is sorted at P (but kanjis seems not ignored, so `鬱P` seems correctly sorted).
- `まらしぃ` is sorted even before digits, but `ちょむ工房` is at the end (my guess it that only the two last characters i.e. kanjis are taken into account but not hiraganas)
- not sure it’s related because it seems logical (even if weird at first glance), but `ばんぶー,keisei` is sorted just after `keisei`

**Comment by gnumdk** [comment]
Lollypop is using python strcoll function. So bug not in lollypop.
May be related:
https://www.google.fr/search?q=strcoll++hiraganas&ie=utf-8&oe=utf-8&gws_rd=cr&ei=YsUdV8KEKsKQaKznibAD
