### ISSUE TITLE
Radio Not working

### ISSUE THREAD

**Issue by vendforce** [gnumdk/lollypop#587]
-Lollypop version: 0.9.98
-Gtk Version: 3.20
-Linux distribution: arch

Radio is not working when I click play it does nothing , I've used lollypop since it came out and the radio has always worked , after an update it has stopped working

**Comment by gnumdk** [comment]
Please paste terminal output.

**Comment by vendforce** [comment]
I've tried to use lollypop --debug but nothing happens , lollypop opens and the terminal prompt finishes closes and no ouptut in terminal

**Comment by gnumdk** [comment]
You need to close lollypop before

**Comment by vendforce** [comment]
Huh ?? I closed lollypop and then opened terminal and did lollypop --debug and still nothing lollypop just opens and no output

**Comment by region51** [comment]
-_Lollypop version: 0.9.98_
-_Gtk Version: 3.18.9_
-_Linux distribution: Fedora 23_

all is well
```
[maxim@localhost ~]$ lollypop --debug
Player::_on_stream_start(): http://ice1.somafm.com/groovesalad-128-mp3
Toolbar::_on_current_changed
Player::_on_bus_message_tag(): http://ice1.somafm.com/groovesalad-128-mp3
Toolbar::_on_current_changed
Player::_on_bus_message_tag(): http://ice1.somafm.com/groovesalad-128-mp3
Toolbar::_on_current_changed
Player::_on_bus_message_tag(): http://ice1.somafm.com/groovesalad-128-mp3
Toolbar::_on_current_changed
Player::_on_bus_message_tag(): http://ice1.somafm.com/groovesalad-128-mp3
Toolbar::_on_current_changed
Player::_on_bus_message_tag(): http://ice1.somafm.com/groovesalad-128-mp3
Toolbar::_on_current_changed
Player::_on_bus_message_tag(): http://ice1.somafm.com/groovesalad-128-mp3
Toolbar::_on_current_changed
```

**Comment by vendforce** [comment]
Hmm strange ... I cant get the prompt to stay open

**Comment by vendforce** [comment]
Ok so I removed lollypop and install lollypop-git from the aur and now the debug is working

Error playing: http://stream.bts.ie:8081/stream
Toolbar::_on_current_changed
Error playing: http://stream.bts.ie:8081/stream
Toolbar::_on_current_changed
Error playing: http://nodec.gocaster.net/98
Toolbar::_on_current_changed
Error playing: http://nodec.gocaster.net/98
Toolbar::_on_current_changed
Error playing: http://nodec.gocaster.net/98
Toolbar::_on_current_changed

**Comment by gnumdk** [comment]
You have a codec issue. Here it works.

# pacman -S gst-libav

**Comment by vendforce** [comment]
Thats the problem .. thanks !!!!!
