### ISSUE TITLE
Need info about function

### ISSUE THREAD

**Issue by prescott66** [gnumdk/lollypop#588]
I just need to know, what this function from settings do: "Hide track own artists".
I need some explanation to proper translation of this string.
Thank you!

**Comment by KeizerDev** [comment]
I think you can leave that open for now, if you look at other translations(https://github.com/gnumdk/lollypop/search?utf8=%E2%9C%93&q=Hide+track+own+artists) they are also open.

**Comment by gnumdk** [comment]
It hide artist tag when different from album artist...

**Comment by gnumdk** [comment]
Example::
![1](https://cloud.githubusercontent.com/assets/3918824/14811760/e6ca1a98-0b99-11e6-9ac6-f95f72d1866e.png)
![2](https://cloud.githubusercontent.com/assets/3918824/14811761/e6e6000a-0b99-11e6-8772-a01e6d2e3ca2.png)

**Comment by gnumdk** [comment]
Usefull for people listening for classical with many artists set.

**Comment by gnumdk** [comment]
If you have a better english string proposal, tell me ;)

**Comment by d9h02f** [comment]
I don't think "Cacher les artistes propres au morceau" can really be translated literally, maybe "Hide track artist if different from album artist". "Cacher l'artiste du morceau si différent de l'artiste de l'album", or something like that. Or reverse the setting, so it's "Show track artist if different from album artist", on by default.

**Comment by gnumdk** [comment]
I don't want to reverse the setting as I use switch... And I want all switchs to be off by default.

**Comment by gnumdk** [comment]
Finally remove the option... Was not happy with this.

**Comment by prescott66** [comment]
So this issue can be closed
