### ISSUE TITLE
Empty tracklists or album lists

### ISSUE THREAD

**Issue by postblue** [gnumdk/lollypop#590]
- Lollypop version: 0.9.98
- Gtk Version: 3.20.3
- Linux distribution: Arch Linux

- Some album trracklists and/or artists album lists are empty (besides, amazing mediaplayer!).

![capture d ecran de 2016-04-26 04-49-16](https://cloud.githubusercontent.com/assets/696539/14805234/4450c778-0b6a-11e6-9cca-33e246241575.png)
![capture d ecran de 2016-04-26 04-46-53](https://cloud.githubusercontent.com/assets/696539/14805233/444c4efa-0b6a-11e6-8165-8bab8c64b6d6.png)

**Comment by gnumdk** [comment]
Missing genre tag, fixed in git, can you test from aur?

**Comment by gnumdk** [comment]
rm -f ~/.local/share/lollypop/lollypop.db

**Comment by postblue** [comment]
Yes, it's working now! But the artist name's font size changed a bit too, is it intended?

![capture d ecran de 2016-04-26 11-15-14](https://cloud.githubusercontent.com/assets/696539/14813057/3cac8d14-0ba0-11e6-9615-2865c5a07ba6.png)

**Comment by gnumdk** [comment]
Yes... Look at options -> Artist photo
