### ISSUE TITLE
Track lists overlays are empty

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#591]
#### Env
- Lollypop versions: 0.9.96 and 0.9.98
- GTK version: [1.2.10?](https://apps.fedoraproject.org/packages/gtk+)
- GNU/Linux distribution: Fedora 23

#### Bug
Since Lollypop 0.9.96 upgrade, when I add an albums from Bandcamp, their track list overlay are empty. Album from other sources don't have this problem like the AC/DC one.

This bug is still present in 0.9.98 update.

You could reproduce it with this [free price album](https://weneedtutorials.bandcamp.com/).

![capture d ecran de 2016-04-24 22-14-50](https://cloud.githubusercontent.com/assets/4758871/14823050/54f6e1c2-0bd1-11e6-9e55-22dfe826c09f.png)

#### Logs
I tried to produce interesting logs when clicking on this album:

```fish
lollypop -d
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
ArtDownloader::_get_album_art_spotify: g-io-error-quark: Erreur HTTP : Bad Request (0)
```

I am not sure if their are. Tell me if you need more information.

**Comment by gnumdk** [comment]
Look at closed bug before reporting ;)
https://github.com/gnumdk/lollypop/issues/590
