### ISSUE TITLE
Rss Feed

### ISSUE THREAD

**Issue by vendforce** [gnumdk/lollypop#592]
-Lollypop version: 0.98
-Gtk Version: 3.20
-Linux distribution: Arch

Do you have any plans to add an rss feed for the likes of radio pod casts , while searching for a radio station via country etc the station is listed but I want to be able listen to a section or podcast from that station and not just listen to the live radio

Also how can I add a radio form tunein radio http://tunein.com/search/?query=comedy

**Comment by gnumdk** [comment]
the search radio popover is tunein

**Comment by gnumdk** [comment]
Do not plan to add support for podcast, already discussed, most user don't want it.

But, may add search from tunein in search popover if available via API

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/384
