### ISSUE TITLE
Error checking own artist

### ISSUE THREAD

**Issue by anonimo1w** [gnumdk/lollypop#593]
-Lollypop version: 0.9.98
-Gtk Version: 
-Linux distribution: Fedora 23

When I sync around the ~/Music folder, some albums of one artist (stylized and saved in any fields related to artist as "NAME") is always misread as "Name" in the artist field of id3tag.
I have downloaded the id3tags from MusicBrainz, then checked on ex falso and on kid3 and all songs is tagged in the same way, all of them have "NAME" in everything related to artist/performer, but is some songs the artist tag is read as "Name" for some odd reason. Not sure if this is the default, but the id3tag V1 have the information from the V2. So, is possible to be using any other tag?

**Comment by gnumdk** [comment]
Look at your tag frames with puddletag.

**Comment by anonimo1w** [comment]
Thanks, I take a look and.. well, to fix this part of the problem i had to remove all tags (tried to remove each of the possible tags individually.. strangely, didn't work lol) but, yeah, you were right and it was a problem with the tags, so thanks :)

But... this move created another problem. When I go check the artist albums, don't show anything just a blank space. Also, although I can find all of the artist's albums on "All albums" option, the popovers show nothing, just another blank space. What it could be? Tried to start with lollypop -d but didn't show anything unusual (basically, showed the song playing in the moment and was just that..) Should I go with another flag?

**Comment by gnumdk** [comment]
Reset your database:
$ rm -f ~/.local/share/lollypop/lollypop.db
