### ISSUE TITLE
Some tracks are not parsed 

### ISSUE THREAD

**Issue by anthonytex** [gnumdk/lollypop#594]
-Lollypop version: 0.9.98
-Gtk Version:  3.20.3-1
-Linux distribution: Archlinux

-Describe your bug here:
First, this music player is awesome so thanks for your hard work.

Some tracks of my collection, or better some albums (a few) are not correctly imported i don't know if it's my bad or not: my collection was completely tagged by musicbrainz picard.
Whats happen: in my album view i can see the album name but with no cover (not the embedded cover i mean) and if i click on it no songs are present.
More if i click "play" in this "phantom" album lollypop just crash.
If i search with the global search a title of a song in this album i can find it and also play it: also here no album cover

[song.zip](https://github.com/gnumdk/lollypop/files/238773/song.zip)
pw= song

I've attach an example of track that has this problem.
Thank you

**Comment by gnumdk** [comment]
Your tags are really strange ;)

**Comment by anthonytex** [comment]
Thanks for fixing it;) And yes ahah i don't really know the rules behind musicbrainz catalog: the first time that i've push some album informations to them they reject them and send me a mail with "no no no please read the rules". I use this system because programs like kodi or better its scraper "wants" the hash of musicbrainz's release to find and add it to library and cross-linking each artist.

**Comment by anthonytex** [comment]
Sorry again @gnumdk i've build and compiled lollypop and now all album covers are present and plays fine but on some albums i get this 
![screen](https://cloud.githubusercontent.com/assets/11034661/14863807/84fae2c4-0cb7-11e6-960a-0e5750bfa80b.jpg)
Tracks of those albums are in ".flac" :) may you help again? thanks

**Comment by anthonytex** [comment]
[song.zip](https://github.com/gnumdk/lollypop/files/239184/song.zip)
Here is an example song same pw=song Thank you 
PS i don't know if you receive my message because this issue is closed ...

**Comment by gnumdk** [comment]
Here it works...

**Comment by gnumdk** [comment]
The track doesn't have a genre and so I'm quite sure you are not using last git as this is fixed. #591 #590

**Comment by gnumdk** [comment]
Hmm, ok, just remove ~/.local/share/lollypop/lollypop.db

**Comment by anthonytex** [comment]
Yes my bad, really sorry don't thought to rebuild the database: now it's all ok sorry and keep this great work :+1: :)
