### ISSUE TITLE
0.9.98: error reading tags

### ISSUE THREAD

**Issue by drakkar1969** [gnumdk/lollypop#595]
-Lollypop version: 0.9.98
-Gtk Version: 3.16.7
-Linux distribution: Ubuntu 15.10

-Describe your bug here:
Lollypop not reading tags properly: album/artist names are picked up, but when you click on album cover (or artist name in eft sidebar) no track listing appears.
Was happening only to music newly added to library; deleted and rebuilt library, now happening with all albums

Thanks!

**Comment by gnumdk** [comment]
Already reported 4 times and fixed :p
