### ISSUE TITLE
Allow actions on artists (Add, Play)

### ISSUE THREAD

**Issue by hypothesist** [gnumdk/lollypop#597]
I'd like to shuffle all songs between exactly two different artists. Since that is not outright possible, I decided to create a playlist with both of them's songs. But it is not (?) possible to add an artists entire library to a playlist directly, but the feature is available for albums. Just thought it would a nice feature to have, adds consistency too.

**Comment by gnumdk** [comment]
>Since that is not outright possible

You can add albums to current playlist by using the + button on albums. Will add something for artists...

**Comment by hypothesist** [comment]
Yeah, I know about the + feature on albums. Just thought it would be amazing to have a similar feature for artists.
