### ISSUE TITLE
floating artist title 

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#598]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

-Lollypop version: 0.9.99
-Gtk Version: gtk3-3.18.9-1.fc23.x86_64
-Linux distribution: F23

-Describe your bug here:

i see this type of shadow :( 

![screenshot from 2016-04-29 01-33-21](https://cloud.githubusercontent.com/assets/12252430/14905031/569787ec-0dad-11e6-9b8b-299e2bed4500.png)

**Comment by gnumdk** [comment]
Not 0.9.99... It's current git and I'm working on this part :p

**Comment by gnumdk** [comment]
Ok, it's an issue with Gtk < 3.20, that's why it's working on ArchLinux.
Removing shadows for old Gtk versions ;)

**Comment by corebots** [comment]
thanks for looking into this!

**Comment by corebots** [comment]
looks good now :)
