### ISSUE TITLE
Crash on artist name click

### ISSUE THREAD

**Issue by drakkar1969** [gnumdk/lollypop#599]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

-Lollypop version: 0.9.99
-Gtk Version: 3.16.7
-Linux distribution: Ubuntu 15.10

-Describe your bug here:
Clicking on artist name in left sidebar crashes app

**Comment by gnumdk** [comment]
That's all? No logs?

**Comment by gnumdk** [comment]
AttributeError: 'Overlay' object has no attribute 'set_overlay_pass_through'
