### ISSUE TITLE
MPRIS "Volume" support not working properly with media-player-indicator extension

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/lollypop#60]
I'm using media player indicator extension, in the advanced settings we can enable volume slider ; and The volume bar change does not affect lollypop. Audacious and Rhythmbox work.

Please install to test:
https://extensions.gnome.org/extension/55/media-player-indicator/

**Comment by gnumdk** [comment]
Audacious and Rhythmbox handle volume in their ui, not lollypop...
Quite sure it's the same with gnome-music...

**Comment by fastrizwaan** [comment]
gnome-music's volume slider is working, but lollypop's not.
