### ISSUE TITLE
How does album rating work in Lollipop?

### ISSUE THREAD

**Issue by bill-c-martin** [gnumdk/lollypop#600]
I have two questions:

1. Why do some albums sometimes have some default rating that I never set in the first place?
2. Is there a way to backup ratings & the library itself (for example is it stored in some XML or something in the user home directory)?

I apologize if this is the incorrect place to ask this, if so, let me know the correct place. I could not find anything about album rating anywhere.

**Comment by gnumdk** [comment]
Album rating works this way:
- User play a track, album get +1
- Use play another track, other album get +1
- Album rating is calculated based on all albums rate

So if you stop to listen to an album, rate will decrease.

Library is here: ~/.local/share/lollypop/lollypop.db
When removing a track, lollypop backup informations here: ~/.local/share/lollypop/lollypop.db

When reseting db in about dialog, lollypop backup all tracks, reset db and then import all tracks with backuped rate/listen time/...

**Comment by bill-c-martin** [comment]
That is an interesting rating system! And it can be overridden with a manual setting of the rating stars. Thanks for the quick response
