### ISSUE TITLE
Graphical bugs

### ISSUE THREAD

**Issue by ItachiUchiha91** [gnumdk/lollypop#601]
**UPDATE 2: Solved updating the db file.**

**UPDATE: The spaces are caused because in these places should be an album, but it is invisible...in fact if you click in the place where should be the cover the album starts**

Yesterday I noted that in several albums lollypop leaves more space than normal (specially if the album is the last of an artist and one case in which the album is not the last)  (see the screen below)
-Space between two albums
![between two albums](https://cloud.githubusercontent.com/assets/17726762/14934401/efbf7e50-0eae-11e6-98a1-cc20014a4af8.png)

-In the last album of an artist (this happens more frequently)
![in the last album of an artist (more frequently)](https://cloud.githubusercontent.com/assets/17726762/14934407/02afe374-0eaf-11e6-8a0f-04f9f00c78af.png)

-Finally, if I search a track, when I try to select it pressing the down arrow, lollypop doesn't highlight the selected track
(if I press enter starts the second track, but isn't highlighted)
![schermata da 2016-04-30 08-49-54](https://cloud.githubusercontent.com/assets/17726762/14934459/b94d698e-0eb0-11e6-8c17-d86a37da8284.png)

PS I appreciate the artist artwork, but in some artists it takes the cover of one album, in others a photo of the artist (in this case there are problems with artists that aren't famous enough)...Doesn't should be better if it takes the cover of the last album of that artist in the library? (I think that is what itunes does)

**Comment by gnumdk** [comment]
>it takes the cover of one album
It takes artwork from lastfm/wikipedia/spotify. It never takes albums cover (but spotify sometimes use a random album cover)

**Comment by gnumdk** [comment]
Send me ~/.local/share/lollypop/lollypop.db by email

**Comment by ItachiUchiha91** [comment]
mail send at cedric.*@a*i*h*t*.org

**Comment by gnumdk** [comment]
Space bug is due to #590 #591 I think.
