### ISSUE TITLE
Bug with some artist details

### ISSUE THREAD

**Issue by jzobrist** [gnumdk/lollypop#602]
-Lollypop version: 0.99.100
-Gtk Version: 3.20.3-3
-Linux distribution: Archlinux

-Describe your bug here:

Hi there, I have issues with some artists details.
For some I can only see albums, not song details, for others I can't see anything (the blank space should show an album.

 Here's a screenshot : 
![screenshot from 2016-04-30 13-49-29](https://cloud.githubusercontent.com/assets/1950581/14935683/8c4ed592-0eda-11e6-9e02-4e6f7785eed3.png)

If I click on an album it plays well. I have another type of issue pretty similar but in another view, so I paste screenshot in this same bug report : 

**album preview with lollypop covering full screen :**
![screenshot from 2016-04-30 13-54-50](https://cloud.githubusercontent.com/assets/1950581/14935730/5b5074f4-0edb-11e6-8362-42f01943fd9b.png)

**album preview with lollypop sized :**
![screenshot from 2016-04-30 13-54-58](https://cloud.githubusercontent.com/assets/1950581/14935742/c07088f6-0edb-11e6-9e00-1270606cc446.png)

Notice that some artist details are correctly rendered : album + tracks. Don't hesitate to ask me for more information.

**Comment by jzobrist** [comment]
OK, just saved and moved my lollypop.db away and launch lollypop to do a new update from scratch and I have no more graphical issues.
Don't really explain the graphical issue with fullscreen/halfscreen.
I played a bit with lollypop.db and sqlite and didn't saw anything wrong (just played with albums, artists and album_artists and tracks).
I can share you my saved lollypop.db if you're interested with it.
Regards.

**Comment by gnumdk** [comment]
#601 #590 #591
