### ISSUE TITLE
option to delete files

### ISSUE THREAD

**Issue by somas95** [gnumdk/lollypop#605]
-Lollypop version:0.9.98
-Gtk Version:3.20
-Linux distribution:Arch

-Describe your bug here:

Sometimes is useful to have an option to delete selected track from the disk, or to go to the file directory if you don't like the possibility of delete files from Lollypop itself.
That could be possible? Thanks from Lollypop, and sorry for my bad English

**Comment by gnumdk** [comment]
No, lollypop is not a file manager.

**Comment by gnumdk** [comment]
BTW:
$ dconf write /org/gnome/Lollypop/tag-editor "'nautilus'"

Will set nautilus as tageditor and so allow you to launch nautilus from album menu.

**Comment by somas95** [comment]
Good idea, I find out that in easyTag I can delete files as well. It's not an immediate option but it works
Thanks
