### ISSUE TITLE
Add support for unusual coverart aspect ratio

### ISSUE THREAD

**Issue by anonimo1w** [gnumdk/lollypop#609]
-Lollypop version: 0.9.100
-Gtk Version: ??
-Linux distribution: Fedora 23

Some albums have a different aspect ratio, 
e.g.: 
> https://en.wikipedia.org/wiki/A_Walk_in_the_Park
> https://en.wikipedia.org/wiki/Magazine_%28EP%29
> https://en.wikipedia.org/wiki/Toi_et_Moi_%28Namie_Amuro_song%29

When they are showed either on All albums or Artist's album, they are "fixed" to a squared aspect ratio. Is possible to have their original aspect ratio?

**Comment by gnumdk** [comment]
They are not fixed to a squared aspect ratio...

**Comment by gnumdk** [comment]
Tested, there is a bug :-(

**Comment by gnumdk** [comment]
Issue is in cover downloader. Will not happend if you set cover by hand and then update collection.
Will fix it for next release
