### ISSUE TITLE
MPRIS "stop" support not working properly with media-player-indicator extension

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/lollypop#61]
While playing a song if we "stop" it using media-player-indicator, the Play button becomes "Paused" instead of ">" (click to play) ;

How to reproduce:
1. launch lollypop
2. start playing a song
3. in the system menu's media-player-indicator, click stop
4. the play button, whose icon was 'paused' (II) remains paused

5. now, when we try to play by clicking on Pause (II) it won't start playing unless we click twice on play/pause button.

Please install to test:
https://extensions.gnome.org/extension/55/media-player-indicator/

**Comment by gnumdk** [comment]
I really don't have this behaviour, it's buggy but not what you describes... Can you test with git and confirm?

**Comment by fastrizwaan** [comment]
with latest git it is working as expected, thanks a lot.
