### ISSUE TITLE
Crash while album list loading

### ISSUE THREAD

**Issue by kelvan** [gnumdk/lollypop#611]
-Lollypop version: 581e855
-Gtk Version: 3.20.3
-Linux distribution: Arch Linux

Did some browsing through "All albums" (large collection) and added few covers
Switching to Compilation view caused crash, couldn't reproduce.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/view.py", line 165, in lazy_loading
    self._lazy_queue.remove(widget)
ValueError: list.remove(x): x not in list
```

**Comment by gnumdk** [comment]
Not sure will be really fixed but this behaviour was wrong...
Reopen if you get it again with current git
