### ISSUE TITLE
Add support for MusicBrainz DISCSUBTITLE tag

### ISSUE THREAD

**Issue by apastuszak** [gnumdk/lollypop#613]
-Lollypop version: 0.9.100
-Gtk Version:
-Linux distribution: Arch Linux

-Describe your bug here:
Enhancement request

Multi Disc albums tagged with MusicBrainz Picard have a custom field called DISCSUBTITLE.  It would be nice if Lollypop could display this info next to the Disc number.

So for example the, boxed set "Dire Straits: The Complete Studio Albums" now has the first disc say "Disc 1."  It would be nice if it said "Disc 1: Communique," for example.

**Comment by gnumdk** [comment]
Send me an exemple as email. (just one file from each disc)

**Comment by gnumdk** [comment]
With screenshot ;)

![disclabel](https://cloud.githubusercontent.com/assets/3918824/15026233/b8cad740-123d-11e6-9951-5ab82dd597fc.png)

**Comment by apastuszak** [comment]
Oh that is awesome!  I hope it was easy to do.

**Comment by gnumdk** [comment]
Was easy ;)
