### ISSUE TITLE
Buttons don't disappear

### ISSUE THREAD

**Issue by gnunn1** [gnumdk/lollypop#614]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

-Lollypop version: 0.9.103.0
-Gtk Version: 3.20
-Linux distribution: Arch Linux

-Describe your bug here:

Very, very minor issue, the album buttons that appear over an album don't disappear automatically with these steps:

* Hold mouse over album, buttons appear (nice animation BTW!)
* Right click album so context popover appears
* Click on different album, context menu disappears
* Buttons appear on new album but still show over old album

**Comment by region51** [comment]
I confirm ^^^, distr F23.
