### ISSUE TITLE
tooltip( Mix songs)

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#615]
-Lollypop version: 0.9.104
-Gtk Version: 3.18.9
-Linux distribution: Fedora 23

-Describe your bug here: Mix songs --> tooltip =  Long press to show options
![screenshot from 2016-05-07 14-36-48](https://cloud.githubusercontent.com/assets/13280183/15091907/814f183c-1461-11e6-882d-4dae6b25ba8a.png)
what for?
Long press here does not work.

**Comment by region51** [comment]
here long press working
![screenshot from 2016-05-07 14-46-15](https://cloud.githubusercontent.com/assets/13280183/15091925/7c41b204-1462-11e6-994f-330c2336a606.png)

**Comment by gnumdk** [comment]
The option needs to be on for long press to work.

**Comment by region51** [comment]
>The option needs to be on for long press to work.

It does not work for me

**Comment by gnumdk** [comment]
Option off and popover closed...

**Comment by region51** [comment]
I do not understand.
I don't speak English :-1: 
@kostich hi, you work long press (Mix songs) on Fedora?

**Comment by kostich** [comment]
Hi @region51.

On lastest master (878a95ceabf4d25c31164acfee890567c41f24c6), it seems that it does work.
The data is reloaded automatically when the next song starts playing.
https://drive.google.com/file/d/0B6GA4n0KFvmeQmIwRWZNMkZEN2c/view

**Comment by region51** [comment]
@kostich No, I mean it
![814f183c-1461-11e6-882d-4dae6b25ba8a](https://cloud.githubusercontent.com/assets/13280183/15097780/7143e2ae-1530-11e6-99c0-0bc0360cd787.png)

**Comment by kostich** [comment]
Yea, the tooltip is misleading. It only works when the toggle is on "ON". It also works like that on my Fedora. You can't long press and receive a popover while the toggle is "OFF". @gnumdk, is that the desired behaviour of Lollypop? It's a bit confusing.

**Comment by region51** [comment]
>Yea, the tooltip is misleading.

:+1:

**Comment by blackjackshellac** [comment]
Is it possible to have two tooltips based on the switch state?  When off, "Click to mix", when on, "Long click to show mixing options".

**Comment by kostich** [comment]
@blackjackshellac, it is possible. Code would look something like:

`if not mix_songs_button.get_active():  # the button isn't toggled on
    mix_songs_button.set_tooltip_text(_('Enables the song mixing.'))
elif mix_songs_button.get_active():  # returns True if button is toggled
    mix_songs_button.set_tooltip_text(_('Long press to show options'))`

Granted, I've used simillar Python code for GtkToggleButton, It would probably work for GtkSwitch.
