### ISSUE TITLE
Album overlay sometimes does not disappear

### ISSUE THREAD

**Issue by hipnoizz** [gnumdk/lollypop#616]
-Lollypop version: 0.9.104
-Gtk Version: 3.18.9
-Linux distribution: Ubuntu 16.04

Album overlay (buttons allowing to play the album, enqueue the album etc.) sometimes does not disappear when mouse cursor is moved elsewhere. The best way to reproduce it is as follow:
- move the cursor over an album to make overlay appear,
- make sure that cursor is over an album cover (do not hover over the buttons),
- wait a second or two,
- move the cursor to the right, over the list of songs for the album.
It's 100% sure way to reproduce it but it works quite often.

See an attached screenshot showing overlays for 3 albums present at the same time.

![zrzut ekranu z 2016-05-08 11-22-07](https://cloud.githubusercontent.com/assets/1545320/15097202/61e74024-1514-11e6-96df-594986fef663.png)

**Comment by gnumdk** [comment]
Does it happen in "all artists" view?

**Comment by hipnoizz** [comment]
I do not see 'all artists' in a sidebar. In views like 'all albums', 'popular albums' etc. this issue does not happen but these views does not display list of songs.

**Comment by gnumdk** [comment]
Can't reproduce here on:
- ArchLinux + Gnome 3.20
- Ubuntu 16.04 + Gnome 3.18

**Comment by hipnoizz** [comment]
I uploaded a short move showing the issue - https://dl.dropboxusercontent.com/u/24881831/lollypop_overlay.webm.

**Comment by gnumdk** [comment]
Do not happen here... What graphic drivers?

**Comment by hipnoizz** [comment]
Mesa, radeon (open source).

Do you think that this is something 'debugable'? (graphics issues can be tricky to reproduce under debugger) I'm not into Python development TBH but I happen to have PyCharm installed and I was able to so run Lollypop from sources before so I could give a shot..

**Comment by gnumdk** [comment]
Yes, will be helpfull ;)
widgets_album.py line 276: on_leave_notify(self, widget, event)

Replace with this code:
```
    def _on_leave_notify(self, widget, event):
        """
            Hide overlay buttons
            @param widget as Gtk.Widget
            @param event es Gdk.Event
        """
        # We are going to check if event happend in a child
        (x, y) = self._overlay.translate_coordinates(widget, 0, 0)
        allocation = self._overlay.get_allocation()
        print(x, y, event.x, event.y, allocation.width, allocation.height)
        if event.x < x or\
           event.x > x + allocation.width or\
           event.y < y or\
           event.y > y + allocation.height:
            self._cover.set_opacity(1)
            # Remove enter notify timeout
            if self._timeout_id is not None:
                GLib.source_remove(self._timeout_id)
                self._timeout_id = None
            if self._show_overlay:
                self.show_overlay(False)
```

**Comment by gnumdk** [comment]
And then try to reproduce this without overlaying buttons (will provide unwanted debug messages)

**Comment by gnumdk** [comment]
Sure it's linked to this code:
https://github.com/gnumdk/lollypop/commit/e3e22a86717323e9c8e7b9994953b2a8231ac613

In the past, i've seen some leave events telling me that position was in widget... (so totally stupid). As I was not able to reproduce, I finnaly clean the code...
