### ISSUE TITLE
Shortcut to add to loved tracks

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#617]
It would be great to be able to add a track to loved tracks with a shortcut, especially in fullscreen mode. Maybe with just one button, like 'L'.

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/commit/0cce536d2d86395d6e2f54d3abdf092b6f70fa36

**Comment by d9h02f** [comment]
Thanks!
