### ISSUE TITLE
Please enable playback on startup of lollypop, select a song or playlist on startup

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/lollypop#62]
When we launch lollypop, it is not possible to play (buttons are disabled) due to no song selected. I think we should have the "all albums" selected for playback or previously played playlist.

This (error no file selected) behaviour is crashing lollypop using media-player-indicator in fedora21 nvidia drivers, and in gnome-boxes, it does nothing.

**Comment by gnumdk** [comment]
Will fix the mpris bug... And enhance "remember state" option later...

**Comment by gnumdk** [comment]
Here, it doesn't crash if not file selected, have you tested with git version?

**Comment by fastrizwaan** [comment]
on stock fedora 21 it is not crashing, but it crashes on my system which has nvidia drivers and freetype infinality patches. that's why i'm curious. anyways here's the output of my lollypop after the crash:

> [rizvan@localhost .build]$ lollypop
>Error playing:  None
>Traceback (most recent call last):
>  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 711, in _on_bus_error
>    self.next(True)
>  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 263, in next
>    self._shuffle_next(force, sql)
>  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 655, in _shuffle_next
>    track_id = self._get_random(sql)
>  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 676, in _get_random
>    key=lambda *args: random.random()):
>TypeError: 'NoneType' object is not iterable

**Comment by fastrizwaan** [comment]
Ok found the problem, enabling the "shuffle" causes the crash when no song is selected (on the first launch)
