### ISSUE TITLE
(suggestion) Artist name is too large compared to the rest of the interface

### ISSUE THREAD

**Issue by anaturinbor** [gnumdk/lollypop#620]
As you can see artist name is huge and feels out of place... I’m just suggesting that you revert it to the old size or make it smaller.

![screenshot from 2016-05-12 01-12-11](https://cloud.githubusercontent.com/assets/10692755/15198265/fe1ae6ae-17de-11e6-992a-0f20f6fc2153.png)

**Comment by gnumdk** [comment]
No way :p

**Comment by gnumdk** [comment]
Should look better now ;)
