### ISSUE TITLE
Rorganize side-panel entries

### ISSUE THREAD

**Issue by AlexT84** [gnumdk/lollypop#622]
Hi,

I think that
/ Popular Albums / Recently Added Albums / Random Albums /
(I've personally translated the entries from Italian)
should go under / Playlists /, since they are dynamic playlists.
This will simplify the side-bar too.

Thanks, Lollypop is getting quickly THERE.

**Comment by gnumdk** [comment]
No, there are not playlist, playlist is about tracks, this about albums.
