### ISSUE TITLE
webradio issue

### ISSUE THREAD

**Issue by AlexT84** [gnumdk/lollypop#623]
Hello,

If I use the webradio search box in Lollypop and I search for RadioFragola, I get this vocal message: http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3

I'm pretty sure it's not your app fault, but can you help us find out what's wrong here?
Which is the database/infrastructure your application is relying upon for getting the stream addresses?
The stream from tunein page http://tunein.com/radio/Radio-Fragola-1045-s16219/ works..
We stream with aac+ from our server.

Cheers, thank you in advance

**Comment by gnumdk** [comment]
I'm using tunein "radiotime.com API"... You need to add stream by hand.

**Comment by gnumdk** [comment]
http://radiofragola.updatemyip.eu:8000
