### ISSUE TITLE
Feature request: Lyric viewer

### ISSUE THREAD

**Issue by arashm** [gnumdk/lollypop#624]
Lollypop is a great player but lacks a decent lyric viewer. There are number of APIs around providing option for viewing lyrics:

Musicxmatch: https://developer.musixmatch.com/ (used by Spotify)
chartlyrics: http://www.chartlyrics.com/api.aspx
CajunLyrics: http://www.cajunlyrics.com/?page=api
LoloLyrics: http://api.lololyrics.com/

There might be many others. Thanks for your effort.

**Comment by d9h02f** [comment]
It's already there, click on the artist/song in the headerbar to open up a popup with Albums/Last.fm/Lyrics/Search.

**Comment by gnumdk** [comment]
Musicxmatch is not free.

Others API just give link to web page.

Lollypop support lyrics by adding python3 webkit support.
