### ISSUE TITLE
PPA updates?

### ISSUE THREAD

**Issue by wicam** [gnumdk/lollypop#625]
Will you continue to update the PPA with the latest version of the program or should I just build from source?

**Comment by gnumdk** [comment]
Oh I miss to copy package :) BTW, you can use any package, they are all the same...

**Comment by anaturinbor** [comment]
PPA isn't getting updated again. Just wanted to let you know.

**Comment by gnumdk** [comment]
Here. It's up to date.

**Comment by anaturinbor** [comment]
This PPA? https://launchpad.net/~gnumdk/+archive/ubuntu/lollypop

It says last update was 4 weeks ago.

**Comment by gnumdk** [comment]
Last release was 4 weeks ago...
