### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Zebouski** [gnumdk/lollypop#627]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

-Lollypop version: 0.9.105-1
-Gtk Version: 3.20.4-2
-Linux distribution: Arch Linux

-Describe your bug here: Lollypop crashes on launch. Not sure what else to say other than the log when ran from terminal. I can't tell if this is a lollypop bug or python.

```
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
```

**Comment by gnumdk** [comment]
You are missing something, terminal output does not show any crash or segfault...

**Comment by gnumdk** [comment]
ping?

**Comment by gnumdk** [comment]
Reopen if more info...
