### ISSUE TITLE
Crash with radio

### ISSUE THREAD

**Issue by Matthieu34** [gnumdk/lollypop#628]
-Lollypop version: 0.9.106
-Linux distribution: Debian Jessie
Thank you for the software and the work.
I have two things with the radio : 
First, when i'm looking for a radio, i can't use all the keyboards.
For example, the "n", the "c" and the space bar don't work.
But if i am doing the same search in my music, that's work fine.
Second, when i try to ear a radio, lollypop just freeze. I tried a lollypop -d, but nothing appear, it's just a freeze.
Because of my english : 

Avant tout merci pour le logiciel.

Donc, quand je cherche une radio, le clavier est incomplet, les touches "n", "c" et la barre d'espace ne fonctionne pas par exemple.
Si je fais la même recherche dans ma musique, le clavier fonctionne normalement.

Ensuite, lorsque je clique sur une radio, lollypop freeze complètement (du coup, -d ne donne rien).

Encore merci

**Comment by gnumdk** [comment]
Si lollypop freeze, c'est que le bug est dans gstreamer.

Regards si tu as le paquet https://packages.debian.org/fr/jessie/gstreamer1.0-libav

**Comment by Matthieu34** [comment]
Merci pour ta réponse.
J'ai bien ce paquet d'installé.
Au cas où, je l'ai réinstaller, le freeze est toujours présent.

**Comment by gnumdk** [comment]
Il faut vraiment que tu regardes au niveau de tes codecs gstreamer. Ici sur Elementary OS avec la même pile (GTK 3.14), cela fonctionne sans problème...

Je ferme vu que dans tous les cas, je ne peux rien faire.
