### ISSUE TITLE
Question: Save artwork in files

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#629]
lollypop-0.9.106 https://github.com/gnumdk/lollypop/releases/tag/0.9.106
>Option to store covers in tags (needs kid3)

![screenshot from 2016-05-14 11-50-43](https://cloud.githubusercontent.com/assets/13280183/15267418/66b5c250-19ca-11e6-895d-057d3b4c2ec9.png)
I cannot understand how it works?

**Comment by gnumdk** [comment]
It save artwork to file when selecting a cover...

**Comment by region51** [comment]
@gnumdk ??? show how

**Comment by gnumdk** [comment]
It's automatic, nothing to show.

**Comment by gnumdk** [comment]
When changing artwork with lollypop

**Comment by region51** [comment]
hmmm, incomprehensible function

**Comment by gnumdk** [comment]
It exists in most media player, see #197
