### ISSUE TITLE
Hebrew translation (no so familiar with transifex)

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#63]
I just translated this application to Hebrew, and I don't know how to uplade it
in Transifex.

How can I do it?

**Comment by gnumdk** [comment]
Thanks for your work ;)

**Comment by yoseforb** [comment]
If I translated you project thas is out of GNOME, it mean something ;-)
It looks like the LINGUAS needs reordering (aphabetical).

**Comment by gnumdk** [comment]
Reordered LINGUAS, is order important? Why? :)

**Comment by yoseforb** [comment]
In every LINGUAS file I see this comment at the top (I don't know how much it important, it just convenient):
# please keep this list sorted alphabetically

**Comment by gnumdk** [comment]
ok, thanks for information ;)

**Comment by yoseforb** [comment]
I wonder why you ends any sentence with wink, I imagine this like an unwanted spasm ;-)
