### ISSUE TITLE
Some Features Request

### ISSUE THREAD

**Issue by anonimo1w** [gnumdk/lollypop#630]
-Lollypop version: 0.9.105
-Gtk Version:
-Linux distribution: Fedora 23

Is inconsistent where is the play button, in some places (in artist folder, for example) is in the center now, in albums folder (all albums, recently added albums..) is a small icon in the left-bottom counter. Maybe change to both as a big play icon? Also, the artist's image could work as a play button (if possible and if wanted).

In the Album folder, if possible, put indicators, like the ones on artist folder (the year indicator), and show the gender of the album, showing a different gender on the songs that has.

If possible, put a artist's image and album's image in different sliders. 

And, also, Many Thanks for the great player :D

**Comment by gnumdk** [comment]
>Maybe change to both as a big play icon? Also, the artist's image could work as a play button (if possible >and if wanted).
No in album view, it's small to let user click album.

>Also, the artist's image could work as a play button
No, play button in cover is for album, not artist.

For indicators, don't want to clutter interface with too much information.
