### ISSUE TITLE
no zip decoder codec found error on library scan

### ISSUE THREAD

**Issue by gcolson** [gnumdk/lollypop#631]
-Lollypop version: 0.9.106
-Gtk Version: 3.18.9-1ubuntu3
-Linux distribution: Ubuntu Studio 16.04

-Describe your bug here:
À chaque fois que la librairie musicale est analysée (à chaque démarrage entre autre), l'erreur suivante apparaît et stoppe la lecture en cours : 
```Python (v3.5) nécessite d'installer un greffon pour lire les fichiers multimédias du type suivant : application/zip decoder```
J'imagine que cela est dû à la présence d'archives dans le dossier Musique. Serait-il possible d'ignorer ces fichiers pour éviter cette erreur ?

**Comment by gnumdk** [comment]
Lollypop ignore déjà les fichiers non audio.... Très bizarre... Que dit nautilus à propos du type de fichier?

**Comment by gcolson** [comment]
Je ne sais pas ce que dit nautilus. J'ai en effet pas mal de fichiers .zip dans mon dossier musique (ça semble être ça qui pose problème).
En lançant le programme de puis la console l'erreur est la suivante : 
```AlbumArt::pixbuf_from_tags(): gst-core-error-quark: Il manque un greffon dans votre installation de GStreamer. (12)```

**Comment by gnumdk** [comment]
Fait propriétés sur un fichier depuis nautilus pour avoir le type de fichier du zip.

**Comment by gcolson** [comment]
C'est toutes des `archive zip (application/zip)`

**Comment by gnumdk** [comment]
Peux tu lancer:
$ lollypop -d

Scanne la bibliothèque et donne moi la sortie sur le terminal (qui peut être longue)...

**Comment by gnumdk** [comment]
Cela n'arrive pas ici sous Ubuntu 16.04 standard...

**Comment by gnumdk** [comment]
Dans python3:

>>> from gi.repository import Gio
>>> f = Gio.File.new_for_path("/home/bellegardec/Musique/vte3.zip")
>>> info = f.query_info('standard::content-type', Gio.FileQueryInfoFlags.NONE)
>>> info.get_content_type()
'application/zip'

Chez toi, tu devrais avoir audio à la place de application/zip sinon, il faut vraiment que je regarde mieux le code...

**Comment by gcolson** [comment]
Yop, si je tape les commandes que tu as donné avec un .zip dans mon dossier Musique j'ai bien 'application/zip' comme toi.
Pour la sortie du terminal, c'est vraiment long, y'a toutes les lignes des imports qui marchent, et lorsque l'erreur arrive j'ai la même ligne que ce que j'ai copié plus haut.

En soi c'est peut-être juste un problème de greffon chez moi...

**Comment by gnumdk** [comment]
Envoie moi le log complet par mail.

**Comment by gnumdk** [comment]
Non, ce n'est pas un problème de greffon, j'ai besoin de savoir ce que fait lollypop avant l'erreur... Mais comme il peut y avoir un décalage entre le log ayant provoqué l'erreur et le message que tu vois, il me faut les logs complets...

**Comment by gnumdk** [comment]
/home/gregoire/Musique/VicDub Experience/samples/le roi et l'oiseau/le_roi_et_loiseau_data/e00/d00/e00002dd.au, gst-stream-error-quark: Le format du flux n’est pas correct.

C'est quoi le type de ce fichier dans nautilus?

**Comment by gnumdk** [comment]
Ok, il s'agit de ce fichier, c'est la seul erreur de ce type et ce n'est que sur cette erreur que lollypop demande à packagekit d'installer un codec...
Error scanning: /home/gregoire/Musique/Mike Mainieri/Northern Lights live à Vaux Jazz 19-03-2010/1 - 'R' is for Riddle.ogg, gst-core-error-quark: Il manque un greffon dans votre installation de GStreamer. (12)

Ce fichier doit être corrompu, non?

**Comment by gnumdk** [comment]
Ou alors tu n'as aucun codec pour lire quoi que ce soit avec gstreamer.
http://packages.ubuntu.com/fr/xenial/ubuntu-restricted-addons

Quoi qu'il en soit je ferme ce bug parce que le problème de détection du type de fichier est dans gstreamer.

**Comment by gcolson** [comment]
Yep, merci beaucoup en effet, l'erreur venait bien de ce fichier !
