### ISSUE TITLE
Collection not updated after a tag editing

### ISSUE THREAD

**Issue by c0r0nel** [gnumdk/lollypop#632]
-Lollypop version: 0.9.106-r4 (using aur package lollypop-git)
-Gtk Version: 3.20.4-2
-Linux distribution: Archlinux

I've a huge mp3/flac collection (about 380GB)  in the most of cases the id3 tags are fine but in others they have errors or for example the same artist in upper and lower case across the different songs of a same album. Things like that provoque that the same album appear several times with the songs distributed. And the same occurs with the Artist name in the left bar. I have things like:
"Black Keys"
"The Black Keys"
"the black keys" 
and so on.. but on disk I only have a folder called "The Black Keys" with several sub folders with albums inside. 
To try to fix this mess I'm using the link that lollypop provides to easytag. I carefully found the differences and fix them but when i came back to lollypop the errors remains there even restarting the app to force a refresh.Only worked in some albums but in the most of cases my changes on tags are ignored.
There's a way to force a refresh only of those albums that were edited with easy tag?

Thanks and sorry for my english

**Comment by gnumdk** [comment]
Your files contain multiple tags frame and gstreamer may read only APE instead of id3tag.

Remove invalid frames with puddletag... Strange because here on ArchLinux, Easytag remove invalid frames since last release...

**Comment by gnumdk** [comment]
Using kid3 seems better to clean tags. It shows frames in a nice way.
