### ISSUE TITLE
Namespace Notify not available.

### ISSUE THREAD

**Issue by Nilpferdschaf** [gnumdk/lollypop#634]
-Lollypop version: commit 72d90ea / 0.9.107
-Gtk Version: 3.14.5
-Linux distribution: Debian (Jessie)

-Describe your bug here:
I just installed the most recent version, but it just crashes instantly on launch. The Terminal prints out:
Traceback (most recent call last):
  File "/usr/local/bin/lollypop", line 25, in <module>
    from lollypop.application import Application
  File "/usr/local/lib/python3.4/site-packages/lollypop/application.py", line 16, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 100, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available

So it seems I'm missing some dependency here, but the installation went perfectly fine and I used the exact commands given in the README.md file. I tried installing libnotify, but that didn't help.

**Comment by gnumdk** [comment]
I have not idea how to check gi dependancies (and so Gnome Music project)...
https://packages.debian.org/fr/sid/gir1.2-notify-0.7
