### ISSUE TITLE
ReplayGain support

### ISSUE THREAD

**Issue by apastuszak** [gnumdk/lollypop#635]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

-Lollypop version: 0.9.0105
-Gtk Version: latest
-Linux distribution: Arch Linux

-Describe your bug here: 

It would be great if Lollypop had ReplayGain support.

**Comment by gnumdk** [comment]
Lollypop already had replaygain support by default...
