### ISSUE TITLE
Order albums by Artist has a few issues

### ISSUE THREAD

**Issue by MrAmnesiac** [gnumdk/lollypop#636]
Hi, first of all I should say I really like your software, thank you for all your work.

-Lollypop version: 0.9.105
-Gtk Version: 3.20.4-2
-Linux distribution: Arch Linux

-Describe your bug here:
I have "Order Albums by Artist" in the preferences, but there are still a number of occasions in which that doesn't work, even tho my library is perfectly organized with beets,
![image](https://cloud.githubusercontent.com/assets/19335590/15399024/e028efc4-1ddd-11e6-972e-5bf4f77efd09.png)
See Thom Yorke, Burial and Flying Lotus
![image](https://cloud.githubusercontent.com/assets/19335590/15399146/6fdc64fc-1dde-11e6-9aec-8036bff02a68.png)
as you can see the problem presists on the artist sidebar
![image](https://cloud.githubusercontent.com/assets/19335590/15399310/0d26b32a-1ddf-11e6-9dca-ce6d91bf67b3.png)
Here's another example with Bjork and Radiohead.
![image](https://cloud.githubusercontent.com/assets/19335590/15399356/3e40141a-1ddf-11e6-91bb-9a47d4abf2bd.png)

It happens with a lot of artists. I've tried reseting the db, deleting the config files and stuff, but nothing solved it.
I hope I've made the issue clear.

**Comment by gnumdk** [comment]
What is the view?

**Comment by gnumdk** [comment]
And send me ~/.local/share/lollypop/lollypop.db by email.

**Comment by gnumdk** [comment]
You tags are totally broken...

**Comment by gnumdk** [comment]
Show me radiohead and burial tags with kid3.

**Comment by MrAmnesiac** [comment]
I never used kid3, hope this is enough:
![screenshot from 2016-05-20 14-28-42](https://cloud.githubusercontent.com/assets/19335590/15429473/043edcf0-1e99-11e6-8cec-096dca18c94e.png)
![screenshot from 2016-05-20 14-35-55](https://cloud.githubusercontent.com/assets/19335590/15429475/04449226-1e99-11e6-9433-639c3e087b8a.png)
![screenshot from 2016-05-20 14-36-51](https://cloud.githubusercontent.com/assets/19335590/15429474/04408eec-1e99-11e6-96ec-047865af6f4c.png)

Do you see any problem with the screenshots above?

I also took a look at ~/.local/share/lollypop/lollypop.db, Radiohead's sortname is "Flaming Lips, The", very weird.

**Comment by gnumdk** [comment]
Ok, I know how to fix this... Was quite sure something bad could happen when writing this code :)

**Comment by MrAmnesiac** [comment]
I'm glad, thanks for your work.

**Comment by gnumdk** [comment]
Can you show me radiohead tags from this album (sort tags)

**Comment by MrAmnesiac** [comment]
~/Music/Lossy/Flaming Lips, The/The Flaming Lips - (2005) LateNightTales_ The Flaming Lips/17 - Radiohead - Pyramid Song.opus
               album: LateNightTales: The Flaming Lips
         **albumartist:** The Flaming Lips
    albumartist_sort: Flaming Lips, The
              **artist:** Radiohead
         artist_sort: Radiohead
![screenshot from 2016-05-20 15-43-06](https://cloud.githubusercontent.com/assets/19335590/15431397/94adb506-1ea1-11e6-94f2-631e006ede59.png)

**Comment by gnumdk** [comment]
Do not trash your db with rm, just reset it in about dialog, Lollypop will import stats ;)

**Comment by MrAmnesiac** [comment]
Ok, thanks!
