### ISSUE TITLE
MTP sync: use .lollypop file for settings (feature request)

### ISSUE THREAD

**Issue by neckcen** [gnumdk/lollypop#637]
Not all MTP devices run android and therefore `Music/lollypop` might not be the best location to store files. It would be convenient to be able to specify the path using a `.lollypop` file placed at the root of the device. Technically it could also be used to store other settings although I can't think of any right now.

**Comment by gnumdk** [comment]
Not sure about .lollypop file, seems really to geeky IMO.

Have you exemple of MTP device not storing music in Music?

**Comment by neckcen** [comment]
I found that some linux audio players recognize a `.is_audio_player` file on devices. Possibly a better way to do it than reinvent the wheel? See:
https://wiki.gnome.org/Apps/Banshee/CommonQuestions/IsAudioPlayerFile

My use case is a sony waterproof walkman which uses `Music` but only supports 2 levels (i.e. `Music/album/file.mp3`). It has no screen and so folders are considered albums for the skip function. Upon checking, it does not sync through MTP. I was pretty sure it was an option... my apologies.

**Comment by gnumdk** [comment]
is_audio_player is an HAL specs... And HAL is dead on Linux since years ;)

**Comment by gnumdk** [comment]
And it will not fix your issue... I create a Music/lollypop folder to allow user to put music on his device without conflict with lollypop sync.

**Comment by gnumdk** [comment]
For people who care, Lollypop sync directly in Music folder but put an "unsync" folder that will be excluded
