### ISSUE TITLE
Support for genre separators

### ISSUE THREAD

**Issue by MrAmnesiac** [gnumdk/lollypop#639]
Hello again, this time I come with a suggestion.

-Lollypop version: 0.9.105
-Gtk Version: 3.20.5
-Linux distribution: Arch Linux

Here's a screenshot of my genre view on Lollypop
![screenshot from 2016-05-20 20-32-22](https://cloud.githubusercontent.com/assets/19335590/15439913/6e7d97f6-1eca-11e6-88bf-fd4bbff35084.png)

It'd be cool if Lollypop could detect genre separators (the most commons being , ; and / ) 
and instead of having 
Genre1, Genre2, Genre3
Genre3, Genre4, Genre2
it could automatically break it into indivudual genres, and opening it would show all of the albums / artists that have that genre.
Genre1
Genre2
...

**Comment by gnumdk** [comment]
Lollypop already support genres/artist separation:
- with ; but it's really a hack
- with multiple tags value (possible to add two genre tags with kids3 for example)

; is a hack and I don't want to add more separators as «,» could be wanted by user: «Samba, forro, pagode» for example.

**Comment by gnumdk** [comment]
Mp3 seems to define / as standat but not sure how to deal with AC/DC in this case

**Comment by MrAmnesiac** [comment]
>Lollypop already support genres/artist separation:
with ; but it's really a hack

I didn't know that, good news!
Thanks!
