### ISSUE TITLE
Make lollypop show discs in albums

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#64]
I have some albums thas they separated to some discs.
I wants to see in one column the songs from disc 1 and the
others songs from disc 2 in the other column. also, I wants to
see each disc numbered seperated.

Right now the order is - first song is the first song from disc 1, the second song
is the first song from the disc 2 and so on.

**Comment by gnumdk** [comment]
It was a bug, tracks should be ordered by disc...

Just reset your database in dconf-editor org/Gnome/Lollypop/db-version

**Comment by gnumdk** [comment]
I will separate albums in next release ;)

**Comment by yoseforb** [comment]
It is possible to separate the discs? I mean, each disc by it self, but still as one album?
I have some albums with 3 disc, and I wants to see where each disc start and ends.

**Comment by gnumdk** [comment]
Yes, i plan to add a  section by disc ;)

**Comment by gnumdk** [comment]
Fixed in git
