### ISSUE TITLE
YELP_HELP_INIT: command not found

### ISSUE THREAD

**Issue by tnga** [gnumdk/lollypop#640]
-Lollypop version: lastest on master
-Gtk Version: 3.14
-Linux distribution: ubuntu 14.04

-Describe your bug here: I get these errors when run `./autogen.sh`

```
./configure: line 5041: YELP_HELP_INIT: command not found
checking for gobject-introspection... configure: error: gobject-introspection-1.0 is not installed
+ exit 1
```

*installed `gobject-introspection` version: `1.42.0`*

**Comment by region51** [comment]
>installed gobject-introspection version: 1.42.0

libgirepository1.0-dev

**Comment by tnga** [comment]
sometime i forget that it's a manual compilation :smile: . Thank, it's done after some other lib dependency installation.
