### ISSUE TITLE
Gtk - segmentation fault

### ISSUE THREAD

**Issue by tnga** [gnumdk/lollypop#641]
-Lollypop version: lastest in master
-Gtk Version: 3.14
-Linux distribution: ubuntu 14.04

-Describe your bug here: after a successful compilation, when launch the player and select on of side-panel items (popular album, artist, ...), it crash after this occurred error.
```
(lollypop:18008): Gtk-WARNING **: GtkOverlay does not have a property called index
(lollypop:18008): Gtk-WARNING **: GtkOverlay does not have a property called index
segmentation fault
```

**Comment by gnumdk** [comment]
Segfault is in GNOME stack, not in lollypop.

GTK 3.14 is broken, but here on Ubuntu 15.04, it works without segfaulting.

Please upgrade to Ubuntu 16.04.
