### ISSUE TITLE
No Last.fm support

### ISSUE THREAD

**Issue by michaltrzcinski** [gnumdk/lollypop#643]
Hi,

Last.fm tab in Preferences disappears and support is not working. Debug shows nothing.

Arch Linux
lollypop 0.9.107
python-pylast 1.4.2

```
$ python3
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Goa', '1.0')
>>> from gi.repository import Goa
>>> c = Goa.Client.new_sync()
>>> for proxy in c.get_accounts():
...    print(proxy.get_account().props.provider_name)
... 
Pocket
Facebook
Last.fm
Google
>>> 

```

Missing something?

**Comment by gnumdk** [comment]
Here it works... ArchLinux too
http://www.last.fm/fr/user/lollypop_gnome

**Comment by gnumdk** [comment]
Are you sure lastfm is enabled in GOA?

**Comment by michaltrzcinski** [comment]
Yes, it is enabled. Scrabbling from Gnome Music doesn't work too, but...
I have removed and add Last.fm account again and it is working now.

Additional question: Do you know why Lollypop is not on GOA Last.fm list? It is only Gnome Music on it.

**Comment by gnumdk** [comment]
I think "Music" is not for Gnome Music but for what is enabled...

Look at google account (printer, mail, contact, ...)
