### ISSUE TITLE
Show time for streams as well?

### ISSUE THREAD

**Issue by Gert-dev** [gnumdk/lollypop#647]
-Lollypop version: 0.9.107
-Gtk Version: 3.20.6
-Linux distribution: Arch

Would it be possible to show the playing time (counter) for streams (e.g. radio's) as well? I understand that some streams (such as YouTube video's) might have a specific duration and others may be infinite (such as radio's), but it would even be handy if a plain counter is shown that is not tied to the stream at all (if it could be tied to the stream, that would be even better, if it is feasible).

The use case for this is simply knowing how long you've been listening to the radio or, if you're listening to a YouTube video, knowing how far you're into the video.

Thanks in advance

**Comment by gnumdk** [comment]
Yes, you're right, will change this.

**Comment by Gert-dev** [comment]
Thanks!
