### ISSUE TITLE
Album art not updated when set via ID3 tags

### ISSUE THREAD

**Issue by michael-rapp** [gnumdk/lollypop#649]
Sometimes Lollypop downloads the wrong album art for a specific album. In such case I download the image by myself and add it to the MP3 files by using ID3 tags. Lollypop then correctly detects that the files have been edited and starts to update its database. However, even after updating the database has finished, the old album art is still displayed in Lollypop. 

I think images, which have been set via tags should have priority over those that have been downloaded by Lollypop. And I guess this is the normal behavior when adding music files to the database for the first time, right?

Maybe a workaround for this issue would be to delete the image, which has been downloaded by Lollypop, manually. Where are these images stored?

-Lollypop version: 0.9.107
-Gtk Version: 3.20.6
-Linux distribution: Arch Linux

**Comment by gnumdk** [comment]
Here lollypop priority
- cover.jpg in album folder
- image in tags
- any image in album folder

**Comment by michael-rapp** [comment]
Ok, there was a cover.jpg file with the wrong album art in the album folder. I deleted it, but the image specified in the tags is still not showing up. Restarting Lollypop and manually updating its database didn't help. Did Lollypop create the cover.jpg file when it downloaded the album art or where does it put downloaded images?

**Comment by michael-rapp** [comment]
After some time the correct image magically showed up. Thanks for the hint about the covers.jpg file. It did the trick. I would still like to know where the downloaded images are saved, though.

**Comment by gnumdk** [comment]
Updating collection delete cover cache...

**Comment by michael-rapp** [comment]
Alright. Maybe updating the collection lasted longer than I expected. Nevermind.
