### ISSUE TITLE
Show 'Stop after this track/album' when 'Continue playback' is disabled

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#652]
- [ ] Currently it's only shown if 'Continue playback' is enabled, but it's also useful if you're in the middle of a long queue or playlist that you are only going to listen to once, and I don't think it would have any negative impact on the UI.
- [ ] A keyboard shortcut for this could be useful as well - Quod Libet uses Shift+Space for 'Stop after this track', maybe Ctrl+Space for 'Stop after this album'? But this isn't very important.
- [ ] Also, maybe renaming 'Continue playback' (continuer la lecture) to 'Continuous playback' (lecture continue) would make it more clear what it's supposed to do, because 'Continue playback' is ambiguous.

**Comment by gnumdk** [comment]
![652](https://cloud.githubusercontent.com/assets/3918824/15854677/77e3b872-2cab-11e6-8063-2981355c02a9.png)

**Comment by gnumdk** [comment]
Cool, current git is broken as I miss to add a file in git... And I have no access to this computer :-1:
