### ISSUE TITLE
Don't vertical wrap long playlists

### ISSUE THREAD

**Issue by hypothesist** [gnumdk/lollypop#655]
I have a really long playlist (basically all the albums of two artists put together). But I find that the last album on the left half is wrapped - the first few tracks are on the bottom of the left side, the rest are on the top of the right side.

I don't know if this is the intended feature but this feels unintuitive to me at least.

**Comment by gnumdk** [comment]
Screenshot ?

**Comment by hypothesist** [comment]
[Left-side bottom](https://i.imgur.com/Wz021HY.png)

[Right-side top](https://i.imgur.com/ROY09Hr.png)

**Comment by gnumdk** [comment]
Ok, yes it's wanted, you can resize lollypop windows if you wan all tracks in one column.
