### ISSUE TITLE
Tracks overlay is blank for some albums

### ISSUE THREAD

**Issue by rahul-raturi** [gnumdk/lollypop#657]
**System Info:**
Arch Linux 4.6.2-1-ARCH
Gnome 3.20.2

**Issue:**
As described in title. The overlay displayed when clicking on an album is blank for some albums, but works fine for others. I'm not sure whether this is a locale problem or not, so need some help identifying that. Unicode locale is installed in my system. Contents of `/etc/locale.conf` are:

    LANG=en_us.UTF-8

**Screenshots:**

1. Blank overlay:

![screenshot from 2016-06-15 21-41-29](https://cloud.githubusercontent.com/assets/7776696/16088733/1d6343a8-3346-11e6-9948-9198a347aa39.png)

2. Working overlay:

![screenshot from 2016-06-15 21-41-39](https://cloud.githubusercontent.com/assets/7776696/16088760/37e11eee-3346-11e6-9406-dd8c0d713381.png)

**Comment by gnumdk** [comment]
#590

**Comment by rahul-raturi** [comment]
Right, thanks. Got it working.
