### ISSUE TITLE
Playback mode doesn't revert to previous mode after 'Stop after this album'

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#658]
If you have the playback mode set to 'Do not repeat', and change it to 'Stop after this album' or 'Stop after this track', once the playback stops, the playback mode is set to 'Continuous playback'. It should go back to 'Do not repeat'.

**Comment by gnumdk** [comment]
No, it's wanted, you have an option if you want lollypop to not repeat by default.
