### ISSUE TITLE
No support for Transcoding to synced devices (MTP)

### ISSUE THREAD

**Issue by pwhelan** [gnumdk/lollypop#659]
-Lollypop version: git
-Linux distribution: arch

-Describe your bug here:

Unable to set transcoding settings for MTP devices (so syncing creates an OGG/MP3 file).

**Comment by gnumdk** [comment]
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-ugly-plugins/html/gst-plugins-ugly-plugins-lamemp3enc.html

You need this plugin (gst ugly)
