### ISSUE TITLE
Queue and search interference

### ISSUE THREAD

**Issue by p3732** [gnumdk/lollypop#664]
-Lollypop version: 0.9.110
-Gtk Version: 3.20.6-1
-Linux distribution: Arch

When playing a track from the search, the queue list switches to a list of search results. When adding an album or a song to the queue nothing happens and the search results keep playing.
Suggestion: Drop search playlist and go back to regular queue playing.

**Comment by gnumdk** [comment]
Can't reproduce here... Adding song to the queue make "current playlist widget" switch to queue. And next plays the queue.

**Comment by gnumdk** [comment]
@p3732 Post a video showing your issue...

**Comment by p3732** [comment]
@gnumdk there you go: https://raw.githubusercontent.com/p3732/various/master/Screencast%20from%2021.06.2016%2001%3A09%3A51.webm

**Comment by gnumdk** [comment]
Ok! It's not the queue but current album playlist, you are right, lollypop should stop playing "search playlist"
