### ISSUE TITLE
Debug shows no errors, but lollypop refuses to play media

### ISSUE THREAD

**Issue by ioangogo** [gnumdk/lollypop#665]
-Lollypop version: 0.9.110
-Gtk Version: 3.20-1
-Linux distribution: Antergos

On the current version on lollypop, the player is refusing to play the media files and will just have the progress bar a 0:00 all of the time, but the debug output - as far as i know - is showing that the program has loaded the music. 
```
BinPlayer::_load_track(): file:///home/ioan/Music/Avicii/I_Could_Be_the_One_(Avicii_vs__Nicky_Romero)/B00B6B1PKQ_(disc_1)_01_-_I_Could_Be_the_One_(Nicktim_Radio_Edit)_%5BAvicii_vs__Nicky_Romero%5D.mp3
Player::_on_stream_start(): file:///home/ioan/Music/Avicii/I_Could_Be_the_One_(Avicii_vs__Nicky_Romero)/B00B6B1PKQ_(disc_1)_01_-_I_Could_Be_the_One_(Nicktim_Radio_Edit)_%5BAvicii_vs__Nicky_Romero%5D.mp3
Toolbar::_on_current_changed
```
I have tested a file in MPV(checking that the file is working) and also in totem(checking gstreamer) and both play fine in those program.

**Comment by gnumdk** [comment]
/me dreams of a day when users know how to use their Linux distro :p
gst-libav ;)

**Comment by ioangogo** [comment]
That libary is installed on this system due to me having corebird installed

**Comment by ioangogo** [comment]
And has worked under it due to corebird being the first app on this system

**Comment by ioangogo** [comment]
The response was unclear and unneededly sarcastic.

**Comment by gnumdk** [comment]
Response is sarcastic because I'm bored about searching for gstreamer mp3 support for each linux distro ;)

**Comment by gnumdk** [comment]
$ mv ~/.local/share/lollypop/lollypop.db ~/lollypop.db

And run lollypop again, is it able to scan files?

**Comment by ioangogo** [comment]
Yes, it is able to scan files. Playing issue persists

**Comment by gnumdk** [comment]
Send me a file by email.

**Comment by gnumdk** [comment]
Works here on ArchLinux so looks like an issue with Antergos...

**Comment by gnumdk** [comment]
Try with a new user, should help you see if it's a problem with your account or with your distro.

**Comment by ioangogo** [comment]
New user has no issues. Old User has issues still

**Comment by gnumdk** [comment]
Ok... Look at your logs:
journalctl -f

**Comment by ioangogo** [comment]
Hmm, nothing about the files, one issue that shows in debug is in there

```
usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

```

**Comment by ioangogo** [comment]
Ok, that was odd, it has now fixed it self with no obvious cause, all that had happened was that my wifi went down, and when it came up every thing worked, im not sure if it was caused by pulseaudio(If it was, loging out and in will have fixed it)
