### ISSUE TITLE
The artist artwork at the list artists in the side is cut off and shown the wrong side in RTL

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#667]
-Lollypop version: last git master
-Gtk Version: 3.21.2.35.g1dbbe7f-1
-Linux distribution: ArchLinux

The artist artwork at the list artists in the side is cut off and shown the wrong
side in RTL.

The artist artwork had to be before the title, from the right to the title.
It also sould not be cut off...

See the screenshost.
![lolltpop-ltr](https://cloud.githubusercontent.com/assets/2222697/16340702/3bbf51c8-3a32-11e6-98a7-f936ecfc599b.png)
![lollypop-rtl](https://cloud.githubusercontent.com/assets/2222697/16340704/3bca6f2c-3a32-11e6-82e5-8b34824f62f7.png)

**Comment by gnumdk** [comment]
How can I make lollypop RTL? Don't remember...

**Comment by yoseforb** [comment]
env LANG=he_IL.UTF-8 lollypop
