### ISSUE TITLE
API for lollypop

### ISSUE THREAD

**Issue by jamesddube** [gnumdk/lollypop#668]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate
- Cloud playback

-Lollypop version:
-Gtk Version:
-Linux distribution:

-Describe your bug here:

Will there be an API available for developers to add functionality like plugins etc? Even for just basic functions like play ,pause , next ...

**Comment by gnumdk** [comment]
No, no plugins API. For basic functions, you can just use MPRIS.

**Comment by jamesddube** [comment]
Thanks will look it up, havent used that before. Any links, examples would be helpful. Thanks again
