### ISSUE TITLE
Missing dependencies in ubuntu ppa

### ISSUE THREAD

**Issue by knepp** [gnumdk/lollypop#669]
Hi! Lollypop is awesome, thank you! 
There is one problem - I've installed minimal ubuntu gnome from mini iso and now I cant listen any radios - lollypop says "cant connect to tunein". I've tried to install some webkit packages, still cant connect. Please tell what I need to install to make radio work. I would be great if these packages will be in a recommends/suggestions. 

(ubuntu 16.04)

**Comment by gnumdk** [comment]
http://packages.ubuntu.com/fr/xenial/ubuntu-restricted-addons

**Comment by knepp** [comment]
Nope. I even try to install it with recommends, still cant connect.

**Comment by knepp** [comment]
good luck closing issues before even understanding it, lol.

**Comment by d9h02f** [comment]
Don't complain about missing packages when you're using a distribution which is missing a lot of packages on purpose.

**Comment by gnumdk** [comment]
And more, this is a bug tracker, not a distribution forum...
