### ISSUE TITLE
lollypop crashes when file doesn't exist (e.g., file exists in other partition / drive)

### ISSUE THREAD

**Issue by fastrizwaan** [gnumdk/lollypop#67]
File doesn't exist:  /run/media/rizvan/save/New/Torrents/Atif Aslam Hit Songs-320Kbps songs/48 - Atif Aslam (Mashup).mp3

I have music in other disk parition/removable drives, lollypop crashes when the partition is not mounted and when we try to play the non-existentt file in the playlist. Thanks.

you could test this issue with mp3/ogg playback from a removable media, after removing it :)

**Comment by gnumdk** [comment]
Lollypop 0.9.5?

**Comment by fastrizwaan** [comment]
0.9.10
