### ISSUE TITLE
DB not updated after a tag editing or deleting folder

### ISSUE THREAD

**Issue by dov29** [gnumdk/lollypop#670]
-Lollypop version: 0.9.110
-Gtk Version: apt-cache policy libgtk2.0-0 libgtk-3-0
-Linux distribution: Ubuntu 15.10 x64

-Describe your bug here:

Hi,

First, thanks for this app that I love the approach. 

When I edit tag or in this case delete a folder, the music collection is not updated.
Below the result of debug when music is updating and get not terminated.

Tanks or your help.

Cheers,

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/lollypop/collectionscanner.py", line 203, in _scan
    self._del_from_db(filepath)
  File "/usr/lib/python3/dist-packages/lollypop/collectionscanner.py", line 313, in _del_from_db
    ltime, mtime, album_popularity)
  File "/usr/lib/python3/dist-packages/lollypop/database_history.py", line 85, in add
    ltime, mtime, album_popularity))
sqlite3.IntegrityError: NOT NULL constraint failed: history.ltime

**Comment by gnumdk** [comment]
Please send me by email this files found in ~/.local/share/lollypop
- lollypop.db
- history.db

And an example of deleted track.

**Comment by dov29** [comment]
Thanks for your quick reply, here the files
[lollypop-db.zip](https://github.com/gnumdk/lollypop/files/339116/lollypop-db.zip)

Originally I had 1 artist (2 albums) in two different folders named : "A.S.M (A State of Mind)" with the  "Crown Yard" album inside and "A.S.M (A State Of Mind)" with the "Cosmic Flavour" album, I retag artist tag with kid3 to A.S.M (A State of Mind) and consolidated to 1 folder so I have one folder "A.S.M (A State of Mind") with the 2 albums inside. The music collection was already not updated at this stage then I totally move out the folder from my music folder to see what happens and the issue still occurs.

**Comment by gnumdk** [comment]
Fixed in current master.
Quick fix for you:
$ sqlite ~/.local/share/lollypop/lollypop.db
sqlite> update tracks set ltime=0 where ltime is null

**Comment by dov29** [comment]
Great ! Long life to Lollypop ! :)
