### ISSUE TITLE
Artist artwork in artist folder?

### ISSUE THREAD

**Issue by Gert-dev** [gnumdk/lollypop#671]
Hello

I just noticed the new artist artwork, which is really neat! I was wondering if, much like album art have a `cover.jpg` or `cover.png` file in the album folder, there was a possibility to place the artist cover art in the artist folder under something like `artist.jpg`. For example:

```
- Band A
  - Album 1
    - cover.jpg
  - Album 2
    - cover.png
  - artist.jpg
```

Most of the other music players seem to have somewhat converged around the `cover.jpg` name for album cover art, I'm not sure if a comparable version exists for artist artwork. In any case, it would be neat to have this stored along with the actual music as this would allow it to be synced and managed along with music and album covers onto other devices (perhaps in the future other media players might then also read and show it). 

Thanks in advance and keep up the great work!

**Comment by gnumdk** [comment]
Impossible to implement IMO.

How lollypop can guess that parent directory is artist directory?

In my collection, I have this:
```
|_ Funk
    |_ Maceo Parker
        |_ Album1
        |_ Album 2
    |_ Beastie Boys - Album
```

Here Maceo Parker is artist directory but Funk is not.

BTW, you can just do this:
```
 $ mv ~/.cache/lollypop_info ~/Music/Artists
 $ ln -s ~/Music/Artists ~/.cache/lollypop_info
```

**Comment by Gert-dev** [comment]
Thanks for your response. I thought of your argument while I was writing this issue, but doesn't the same apply to the current situation? You have a `cover.jpg` file in the album folder, but in theory you could also have a single large folder with all your music in it.

For example, most of my music is laid out as in my original post, but I also have another folder that just contains some unrelated music files. If I select an album cover for one of these files (doesn't matter which), Lollypop stores the cover.jpg along with the album and suddenly all of the unrelated tracks share the same cover. (This is expected behavior as Lollypop can indeed impossibly fully automatically detect this.) An alternative solution could be to have a switch (or, as some other media players do, have a field you can place the format of the folder structure, e.g. "%artist/%album", but I assume this is not so simple to implement.

**Comment by gnumdk** [comment]
In fact, lollypop should not use cover.jpg when a directory contains many albums. Not sure if it works as wanted.

**Comment by Gert-dev** [comment]
I think it works as intended... at least I have all my album covers in the album folders and it works so I guess it does ;-).

I see that lollypop_info contains multiple sizes of the same image, does it indeed exclusively contain the artist art (curious as I would like to prevent any other cache images from getting symlinked and synchronized)?
