### ISSUE TITLE
Why "Resetting database" button is not located in Settings window?

### ISSUE THREAD

**Issue by AnDroidEL** [gnumdk/lollypop#672]
The "Resetting database" button is located in the About window. Why not place it in the Settings window? It's a little weird. It could be located in there.

![captura de tela de 2016-07-05 18-01-28-edited](https://cloud.githubusercontent.com/assets/9509498/16603422/4b2bf792-42f2-11e6-878e-e2a5c57de86c.png)

**Comment by gnumdk** [comment]
Because it's not a setting.

And DB stats are in about dialog so reset button is near them... And I don't want a normal user to use this... It's just a way to allow users to reset their db when facing a bug... (without loosing metadata)

**Comment by gnumdk** [comment]
Finnaly changed my mind on this ;)
