### ISSUE TITLE
Missing appmenu ...

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#674]
-Lollypop version: lollypop-0.9.111-1.fc24.R.noarch
-Gtk Version: gtk3-3.20.6-1.fc24.x86_64
-Linux distribution: F24

-Describe your bug here: Missing Update music, Fullsreen, Preferences, Keyboard Shortcuts, Help, About
![screenshot from 2016-07-06 22-29-38](https://cloud.githubusercontent.com/assets/13280183/16631754/64752534-43c9-11e6-883e-3b06455273d9.png)

**Comment by region51** [comment]
hmmm
![screenshot from 2016-07-06 22-45-19](https://cloud.githubusercontent.com/assets/13280183/16632141/640c0534-43cb-11e6-8379-21506c969d8f.png)

**Comment by gnumdk** [comment]
This happen sometimes when launching from bash... Don't found why
