### ISSUE TITLE
No album art pop up notification

### ISSUE THREAD

**Issue by MichaelTiebesl** [gnumdk/lollypop#676]
-Lollypop version: 0.9.111
-Gtk Version: 3.18
-Linux distribution: Solus 1.2

-Describe your bug here: I don't have an album art showing in the notification pop up.
I also see in System Setting with the Notification panel that Lollypop isn't showing (picture2).
I use Arc as theming. I'm not sure if this is an Lollypop issue or a Solus issue but i have to start somewhere :)

Thanks

![menu1](https://cloud.githubusercontent.com/assets/10792019/16643117/2a50ba78-4444-11e6-8e8b-013a0564ccca.png)

![menu](https://cloud.githubusercontent.com/assets/10792019/16643121/2f643f94-4444-11e6-8a67-ee3abd803fbd.png)

**Comment by gnumdk** [comment]
Here work on ArchLinux and Ubuntu...

**Comment by gnumdk** [comment]
Ok, tested, same issue, seems Solus notifications do not handle path to files... (Only icon names)

**Comment by Justinzobel** [comment]
@gnumdk is there a solution to this? Is a commit going to be made in order to address this?

**Comment by gnumdk** [comment]
No, the issue is in Budgie... Works here with Unity and Gnome Shell...

**Comment by MichaelTiebesl** [comment]
@gnumdk thanks for the update. I will ask on the Solus forum for any suggestion.

**Comment by ikeydoherty** [comment]
I don't use Lollypop personally but I can look into it. I'll see what notification path you're using.
Note that we *do* handle image paths, which is why Rhythmbox works fine.

**Comment by ikeydoherty** [comment]
So if you're using libnotify, you should actually be using the `image-path` field in the hints table that is passed in the notification, reserving the use of the `icon` field specifically for freedesktop-compliant icon theme specifications.

I've made an exception for this because I've observed that the Notify gir bindings support the (ab)use of this concept, even though `image-path` is clearly documented and used by Rhythmbox, VLC and others.

**Comment by gnumdk** [comment]
@ikeydoherty I do this because Gnome Shell does not use the 'image-path' in notifications...

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/72

**Comment by ikeydoherty** [comment]
So GNOME Shell is abusing it and causing a knock-on-effect? Yay..
