### ISSUE TITLE
Add the ability to sync albums

### ISSUE THREAD

**Issue by liamnoone** [gnumdk/lollypop#677]
Currently the only syncing option is playlists. This seems very odd as it's stated that this is a music player centered around albums!

The way around this that I know about is to add the albums to a syncing playlist, which isn't really ideal, or to sync everything.

**Comment by gnumdk** [comment]
>which isn't really ideal
Why?

How do you see this feature workflow?

**Comment by blackjackshellac** [comment]
One comment I'd like to add, which applies to the ability to create album playlists for syncing or otherwise, is that one cannot easily remove an album from a playlist.  Once an album is added to a playlist one must go through the tracks one by one to remove.  But maybe this is just a fundamental limitation of playlists.

**Comment by gnumdk** [comment]
@blackjackshellac You are wrong: https://www.youtube.com/watch?v=x1o4gcDI1Es

**Comment by blackjackshellac** [comment]
Ah, I was attempting to remove the album from the playlist proper.  Mea culpa.  Carry on.

**Comment by liamnoone** [comment]
>>which isn't really ideal
>Why?

>How do you see this feature workflow?

I don't see it being ideal to create a dedicated syncing playlist which is unnecessary extra steps when you aren't interested in using playlists originally.

If, for example, a user doesn't use playlists in their normal music listening workflow, or wants to sync one and it isn't in a playlist (or appropriate playlist) yet and begins in the syncing view.

The steps are:
1) Change to Playlists UI
2) Create a new playlist (Skippable if you simply want to add to an existing one)
3) Go to view with albums listed
4) Add the albums to the playlist
5) Switch back to syncing UI
6) Select your playlist and sync

This is a lot of steps just to sync an album in my opinion! Whereas I'd picture the albums list to be accessible from the syncing workflow, be it a separate tab that you switch between in the main list, or listed in the same list (possibly add a right pane or bottom pane), or there may be a switch in the widget that's in the upper right of the view already.

The view listing albums could be tweaked to also handle albums, or otherwise use the same UX (list with checkboxes)

**Comment by gnumdk** [comment]
![albums](https://cloud.githubusercontent.com/assets/3918824/17059859/7cf8ebbc-5027-11e6-90c4-799903fed235.png)

**Comment by liamnoone** [comment]
This is fantastic, thank you so much! I'm a big fan of Lollypop; it fits very nicely within GNOME3 (and looks good in Unity, too) and this was the only thing I felt was lacking.

I haven't gotten a chance to try the feature out, but I certainly will when I get the chance! :)
