### ISSUE TITLE
Playback is stopped when updating music

### ISSUE THREAD

**Issue by goetzc** [gnumdk/lollypop#678]
-Lollypop version: 0.9.112-1
-Gtk Version: 3.20.6-1
-Linux distribution: Arch Linux

-Describe your bug here:
Whenever there is a change in the music folder, tags or file names change, Lollypop stops playback and a "Your music is updating" notification appears.

**Comment by gnumdk** [comment]
#511 ?

**Comment by goetzc** [comment]
The symptom are the same, but the solution doesn't work, as I have that package installed, and also these:

gst-libav 1.8.2-1
gst-plugins-bad 1.8.2-2
gst-plugins-base 1.8.2-1
gst-plugins-base-libs 1.8.2-1
gst-plugins-good 1.8.2-1
gst-plugins-ugly 1.8.2-1
gst-python 1.8.2-1
gstreamer 1.8.2-1

**Comment by gnumdk** [comment]
Nothing in terminal output?

**Comment by gnumdk** [comment]
Run lollypop -d and paste output here

**Comment by goetzc** [comment]
Sure:

```bash
$ lollypop -d
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

(lollypop:7439): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x33b08b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Lastfm::_connect(): Authentication Failed - You do not have permissions to access the service
ArtDownloader::_get_album_art_lastfm: Album not found [Luciano Supervielle & Bajofondo Tango Club/Supervielle]
/home/goetz/Music/.directory not detected as a music file
/home/goetz/Music/Rock/ABBA/ABBA GOLD - Greatest Hits/Notes.nfo not detected as a music file
ArtDownloader::_get_album_art_lastfm: Album not found [Gypsy Kings/Roots The Essential]
/home/goetz/Music/Classical/Bach, Johann Sebastian (1685-1750)/BWV 964ffdv Original & Bearbeitung (Robert Hill, harpsichord)/BWV 964ffdv Original & Transkription.txt not detected as a music file
ArtDownloader::_get_album_art_lastfm: Album not found [Gypsy Kings/i Volare !]
Error scanning: /home/goetz/Music/Rock/Frank Zappa/1981 Tinsel Town Rebellion/Frank Zappa - 1981 Tinsel Town Rebellion - 05 - I Ain t Got No Heart.mp3, gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
BinPlayer::_load_track(): file:///home/goetz/Music/Rock/Frank%20Zappa/1974%20Apostrophe/Frank%20Zappa%20-%201974%20Apostrophe%20-%2002%20-%20Nanook%20Rubs%20It.mp3
Toolbar::_on_current_changed
AlbumArt::pixbuf_from_tags(): gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
ArtDownloader::_get_album_art_lastfm: Album not found [Wagner/Wagner Classical Overtures]
ArtDownloader::_get_album_art_lastfm: Album not found [Träume - Unserer Heimat/Träume - Unserer Heimat]
ArtDownloader::_get_album_art_lastfm: Album not found [Chopin, Frédéric/Nocturnes (Ashenazy)]
ArtDownloader::_get_album_art_lastfm: Album not found [Chopin, Frédéric/Nocturnes (Ashenazy)]
ArtDownloader::_get_album_art_lastfm: Album not found [Strauss, Johann II/Waltzes & Polkas]
ArtDownloader::_get_album_art_spotify: g-io-error-quark: HTTP Error: Bad Request (0) [/Clásicos Inolvidables - 05. Recuerdos de Rusia]
```

I grep'ed out hundreds of "jpg not detected as a music file".

**Comment by gnumdk** [comment]
>Error scanning: /home/goetz/Music/Rock/Frank Zappa/1981 Tinsel Town Rebellion/Frank Zappa - 1981 Tinsel Town Rebellion - 05 - I Ain t Got No Heart.mp3

Here the error, this file is broken or your gstreamer installation is broken...

**Comment by goetzc** [comment]
GStreamer installation should be OK, I will take a look at the file. 

But if the music playback stops (every time some track is added or meta-data updated) if there is a broken file in the library, it gives the user a bad experience. Maybe there is a way to ignore such files from scanning in the future.

**Comment by mancvso** [comment]
From a user that is constantly downloading music to my Library it seems to be the reason my playback stops. Maybe a try/catch block and just skip the song.

The other thing to consider is that it seems to be a DB issue rather than a file/IO issue, because good songs stops too when the library gets updated (in my case, several times a day).

**Comment by gnumdk** [comment]
The issue here is that gstreamer think it is missing a plugin and so lollypop tell packagekit to install a package. To do this, I need to make gstreamer play the file... Will do some testing...
