### ISSUE TITLE
Crashing at switching songs

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#679]
-Lollypop version: 0.9.112
-Gtk Version: 3.20.2
-Linux distribution: Fedora 24

At switching songs (automatically), Lollypop sometimes quits with the following console output. This is reproducable when I play songs from Die Toten Hosen – don't know why other songs work with far less problems...

I also don't know what this „sudo pip3 xyz“ is about...

$ lollypop
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia

(lollypop:12308): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x55ef361a1990 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gtk-WARNING **: Allocating size to GtkGrid 0x55ef35ae7b10 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gtk-WARNING **: Allocating size to GtkViewport 0x55ef35cc4c50 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gtk-WARNING **: Allocating size to lollypop+widgets_album+AlbumDetailedWidget 0x55ef35e252d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gtk-WARNING **: Allocating size to lollypop+widgets_album+AlbumDetailedWidget 0x55ef35cdc910 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gtk-WARNING **: Allocating size to lollypop+widgets_album+AlbumDetailedWidget 0x55ef35a4ecf0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gtk-WARNING **: Allocating size to lollypop+widgets_album+AlbumDetailedWidget 0x55ef35e25410 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gtk-WARNING **: Allocating size to lollypop+widgets_album+AlbumDetailedWidget 0x55ef35cdce10 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gtk-WARNING **: Allocating size to GtkGrid 0x55ef369b0560 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gtk-WARNING **: Allocating size to lollypop+widgets_album+AlbumDetailedWidget 0x55ef35e252d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:12308): Gdk-WARNING **: lollypop: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

**Comment by gnumdk** [comment]
Do you have python coredumps with coredumpctl command?

**Comment by fb87** [comment]
Never used python, can you explain to me what to do?

**Comment by gnumdk** [comment]
```
# coredumpctl |grep python
jeu. 2016-05-12 13:03:15 CEST   1830  1000  1000  11   /usr/bin/python3.5
jeu. 2016-05-12 13:03:28 CEST   1843  1000  1000  11   /usr/bin/python3.5
jeu. 2016-05-12 13:03:33 CEST   1856  1000  1000  11   /usr/bin/python3.5
lun. 2016-06-06 13:34:10 CEST  14431  1000  1000   5   /usr/bin/python3.5
mar. 2016-06-28 10:52:00 CEST  12720  1000  1000   5   /usr/bin/python3.5
mer. 2016-06-29 10:58:43 CEST  26365  1000  1000  11   /usr/bin/python3.5
jeu. 2016-07-07 11:02:03 CEST  10763  1000  1000  11   /usr/bin/python3.5

# coredumpctl gdb 10763
```

And paste output here

**Comment by fb87** [comment]
I don't have coredumpctl available, but `/var/lib/systemd/coredump/` is empty and `systemctl | grep python` doesn't return anything.

**Comment by gnumdk** [comment]
>when I play songs from Die Toten Hosen

Send me this by email.

**Comment by mancvso** [comment]
I don't know if this is the same issue, but sometimes, when a song ends it just keeps in silence until I press "Play" or "Next" (even with Party mode enabled). It just don't advance to the next song WITHOUT crashing or whatsoever.

The only output I get from console is
```
ArtDownloader::_get_album_art_spotify: g-io-error-quark: Error HTTP: Bad Request (0) [/If It Were You, We'd Never Leave]
ArtDownloader::_get_album_art_lastfm: Album not found [/If It Were You, We'd Never Leave]

(lollypop:16124): Gtk-WARNING **: GtkOverlay does not have a property called index

(lollypop:16124): Gtk-WARNING **: GtkOverlay does not have a property called index
```

**Comment by gnumdk** [comment]
@mancvso I'm aware of this issue, happen time to time for me too... But happen also with others Gstreamer players for me...

**Comment by gnumdk** [comment]
@fb87 ping?

**Comment by fb87** [comment]
Well this now happens with random songs, as I wrote before, I don't get any dumps...

**Comment by gnumdk** [comment]
@fb87 Send me  Die Toten Hosen by email ;)

**Comment by gnumdk** [comment]
Can't reproduce here on ArchLinux, Ubuntu and Fedora...

Looks like a driver issue... Check if it happen with wayland...

BTW, not a bug in lollypop.

**Comment by Gabreta** [comment]
I just upgraded to 3.22 gtk (testing version)
and I have given accounts of some things, it seems that this warning appears on some occasions:
(lollypop:6176): Gtk-WARNING **: Allocating size to lollypop+selectionlist+SelectionList 0x7f04ec00ca50 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

And it seems that lollypop has many problems with python-cairo-git (At the time I could not even open the program), after testing satisfactorily with python-cairo

the test result remains the same:
BinPlayer::_load_track(): https://www.youtube.com/watch?v=7nDBhfp9qak
youtube-dl failed to get video uri

unfortunately still not able to find the error, if it's just me or anything else missing
