### ISSUE TITLE
lollypop : Depends: python3-mutagen but it is not installable

### ISSUE THREAD

**Issue by michaldaniel** [gnumdk/lollypop#68]
lollypop : Depends: python3-mutagen but it is not installable
when installing from https://launchpad.net/~gnumdk/+archive/ubuntu/lollypop

Tried installing from source but got missing gobject-introspection-1.0 running configure and installation of gobject-introspection package did not resolve it, would still prefer to use ppa.

OS: elementary OS freya beta 3 - Ubuntu 14.04 derivative

**Comment by gnumdk** [comment]
You need to add the ppa... Please follow instruction on launchpad... python-mutagen is available here...

**Comment by michaldaniel** [comment]
I am aware of both facts. Yet the dependency is not met.

**Comment by michaldaniel** [comment]
I insist you look into this. And trust me I know how to handle my repos python3-mutagen is not available from ppa:gnumdk/lollypop or any other source on "elementary OS" 0.3 (freya) and kernel 3.16.0-33-generic

**Comment by gnumdk** [comment]
Should be ok...

**Comment by michaldaniel** [comment]
mutagen 4 hours 20 minutes ago
Successfully built

Those two new builds resolved the issue. 

If you only have time what was the problem? I am quite insterested in how packageing works and when I see three identical entries like mutagen 1.26-1ppa3ubuntu3 I can only wonder why so many are needed.
