### ISSUE TITLE
Crashes due to Seg Fault on viewing All Albums [KDE Neon 5.7]

### ISSUE THREAD

**Issue by tarungavara** [gnumdk/lollypop#680]
Bug: Crashes when clicked on any of the album options in the top-left like All Albums etc. Also, I can't see the icons for some elements but I know that is due to GTK support. The crash seems to be caused by a Seg Fault. See Log below.

OS: KDE Neon 5.7
Kernel: 4.6

Log: This information was there in my terminal when I launched it and it crashed -

No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Namespace WebKit2 not available
WebKit support disabled
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Lastfm::_on_password_lookup(): g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
ArtDownloader::_get_album_art_spotify: g-io-error-quark: The specified location is not supported (15) [Yoshihisa Hirano and Hideki Taniuchi/Death note anime Soundtrack]
ArtDownloader::_get_album_art_itunes: g-io-error-quark: The specified location is not supported (15) [Yoshihisa Hirano and Hideki Taniuchi/Death note anime Soundtrack]
Segmentation fault (core dumped)

**Comment by gnumdk** [comment]
Do you have python3 dumps with coredumpctl command?

**Comment by gnumdk** [comment]
```
# coredumpctl |grep python
jeu. 2016-05-12 13:03:15 CEST   1830  1000  1000  11   /usr/bin/python3.5
jeu. 2016-05-12 13:03:28 CEST   1843  1000  1000  11   /usr/bin/python3.5
jeu. 2016-05-12 13:03:33 CEST   1856  1000  1000  11   /usr/bin/python3.5
lun. 2016-06-06 13:34:10 CEST  14431  1000  1000   5   /usr/bin/python3.5
mar. 2016-06-28 10:52:00 CEST  12720  1000  1000   5   /usr/bin/python3.5
mer. 2016-06-29 10:58:43 CEST  26365  1000  1000  11   /usr/bin/python3.5
jeu. 2016-07-07 11:02:03 CEST  10763  1000  1000  11   /usr/bin/python3.5

# coredumpctl gdb 10763
```

And paste output here

**Comment by tarungavara** [comment]
Sorry for the late reply.  
I have been testing out where the error might have been and I think it may have to do something with Lollypop automatically searching for Album Art for songs which doesn't have one.

Info you asked:
# coredumpctl |grep python
Wed 2016-07-13 12:51:20 IST    6533  1000  1000  11 * /usr/bin/python3.5
Wed 2016-07-13 13:02:08 IST    6765  1000  1000  11 * /usr/bin/python3.5
Wed 2016-07-13 13:02:18 IST    6803  1000  1000  11 * /usr/bin/python3.5
 
#coredumpctl gdb 10763
No match found.

Observation: 
1. If I select some songs folder with album art intact, then I am able to access all those options in the right-top pane like "All Albums" with the only exception of playlists.
Error Message in terminal:

No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Namespace WebKit2 not available
WebKit support disabled
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Lastfm::_on_password_lookup(): g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Settings::_update_lastfm_settings(): g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 696, in _on_list_one_selected
    self._update_view_playlists()
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 630, in _update_view_playlists
    view = PlaylistsManageView(Type.NONE, [], [], False)
  File "/usr/lib/python3/dist-packages/lollypop/view_playlists.py", line 221, in __init__
    is_album)
  File "/usr/lib/python3/dist-packages/lollypop/widgets_playlist.py", line 469, in __init__
    0)
GLib.Error: gtk-icon-theme-error-quark: Icon 'list-remove-symbolic' not present in theme breeze (0)


2. If I select some songs folder containing some songs without album art, then it crashes for all options in the right-top pane.
Error message in terminal:

No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Namespace WebKit2 not available
WebKit support disabled
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Lastfm::_on_password_lookup(): g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
ArtDownloader::_get_album_art_spotify: g-io-error-quark: The specified location is not supported (15) [Yoshihisa Hirano and Hideki Taniuchi/Death note anime Soundtrack]
ArtDownloader::_get_album_art_itunes: g-io-error-quark: The specified location is not supported (15) [Yoshihisa Hirano and Hideki Taniuchi/Death note anime Soundtrack]
Segmentation fault (core dumped)

**Comment by gnumdk** [comment]
Wed 2016-07-13 13:02:18 IST 6803 1000 1000 11 * /usr/bin/python3.5

So 
# coredumpctl gdb 6803

**Comment by tarungavara** [comment]
I just got this error message along with the regular stuff in the terminal. I'm unable to replicate it though.

**ERROR: Caught a segmentation fault while loading plugin file:
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.**

![screenshot_20160713_131750](https://cloud.githubusercontent.com/assets/18230127/16795676/5ad53220-48fc-11e6-8195-0624668ff9de.png)

Icons aren't visible either.

**Comment by gnumdk** [comment]
Your GTK icon theme is broken...

**Comment by tarungavara** [comment]
About the command stuff you asked:

[6803.txt](https://github.com/gnumdk/lollypop/files/360932/6803.txt)

**Comment by gnumdk** [comment]
https://fedoraproject.org/wiki/StackTraces
 dnf debuginfo-install python3 should do the job...

**Comment by gnumdk** [comment]
Please install:
http://packages.ubuntu.com/fr/trusty/python3-dbg
And repaste coredumpctl output

**Comment by tarungavara** [comment]
[Issue-680-cdmpctl-withpy3dbg.txt](https://github.com/gnumdk/lollypop/files/360954/Issue-680-cdmpctl-withpy3dbg.txt)

**Comment by gnumdk** [comment]
Symbols missing :-/ Maybee they are needed on crash...

**Comment by tarungavara** [comment]
But the main issue is the "All Albums" view. And it works properly when I select those folders of music that have album art with them. Also, For a folder which doesnt have album art, even if I click on the folder itself (left-down panel), it crashes in the same way. I think its got to do something with the album art. Does Lollypop check for Album Art and if not found, attempt to download it or something?

Issues like no icons are okay for now, atleast we have the tooltip. Playlist crash isnt an issue, for I dont want playlists, been searching for a good looking album based player like Lollypop. I'm using Amarok for now, but I dont like it for its playlist centric UI.

**Comment by gnumdk** [comment]
Playlist crash if fixed ;)

But, can you switch to Adwaita icon them and see if bug exists ?

**Comment by tarungavara** [comment]
I'm sorry, I have no idea about GTK and Qt but isn't KDE Neon using Plasma 5 and has Qt-something and Adwaita is a GTK theme? I can't install it on KDE, right? I'm a CS student and am fairly new to the Linux world.

**Comment by gnumdk** [comment]
# apt-get install adwaita-icon-theme

**Comment by tarungavara** [comment]
No, doesn't work for KDE. The theme is installed but I can't select it anywhere.

**Comment by gnumdk** [comment]
Installed KDE Neon, can reproduce but no idea what is happening:
- The bug is in KDE Neon
- KDE Neon GTK installation is totally broken...
