### ISSUE TITLE
Album containing tracks from different years gets split into multiple parts

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#681]
-Lollypop version: 0.9.112
-Gtk Version: 3.20.2
-Linux distribution: Fedora 24

I have some best-of collections with the original release years per song, but these albums sadly get torn apart.

**Comment by Tvrdoglavi** [comment]
I had the same issue and had to change years to match in order to avoid the problem. Lollypop is very aggressive at splitting albums over minor things.

**Comment by gnumdk** [comment]
#454

**Comment by gnumdk** [comment]
>original release years per song

Wrong, this is a dedicated tag (ORIGYEAR) not used by Lollypop.

Default year tag is about album release.
