### ISSUE TITLE
Crashes when songs of the currently playing album were edited

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#682]
-Lollypop version: 0.9.112
-Gtk Version: 3.20.2
-Linux distribution: Fedora 24

Currently I correct all song file names and meta data and sometimes when I let play an album which gets edited at the same time, Lollypop crashes. But I'm not sure if it's due to the file names being changed or due to meta data change (and thus getting sorted again by Lollypop while being queued already).

**Comment by gnumdk** [comment]
Please provide lollypop output from command line or journalctl...

**Comment by fb87** [comment]
Here it is:
http://pastebin.com/hgCEgnhf

**Comment by gnumdk** [comment]
```
# coredumpctl |grep python
jeu. 2016-05-12 13:03:15 CEST   1830  1000  1000  11   /usr/bin/python3.5
jeu. 2016-05-12 13:03:28 CEST   1843  1000  1000  11   /usr/bin/python3.5
jeu. 2016-05-12 13:03:33 CEST   1856  1000  1000  11   /usr/bin/python3.5
lun. 2016-06-06 13:34:10 CEST  14431  1000  1000   5   /usr/bin/python3.5
mar. 2016-06-28 10:52:00 CEST  12720  1000  1000   5   /usr/bin/python3.5
mer. 2016-06-29 10:58:43 CEST  26365  1000  1000  11   /usr/bin/python3.5
jeu. 2016-07-07 11:02:03 CEST  10763  1000  1000  11   /usr/bin/python3.5

# coredumpctl gdb 10763
```

And paste output here

**Comment by fb87** [comment]
„No coredumps found“, sorry.

**Comment by gnumdk** [comment]
On Fedora??? Really strange...
BTW, if you can give me a backtrace:
- I will close this bug report as segfault can't be in lollypop (pure python)
- I can't tell you where report the bug

Regards,
