### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by yogurt1** [gnumdk/lollypop#683]
What about Flatpak repo and bundle?

**Comment by gnumdk** [comment]
Just Do It ;) Flatpak segfault here on ArchLinux, so I can't test.

**Comment by yogurt1** [comment]
@gnumdk, look files in my repo: [yogurt1/lollypop-flatpak](https://github.com/yogurt1/lollypop-flatpak)

**Comment by gnumdk** [comment]
Will give a look, thanks

**Comment by yogurt1** [comment]
@gnumdk, my build works. Pull my repo and run make install. One bad - no locales :(

**Comment by gnumdk** [comment]
/bin/sh: line 1:  1187 Illegal instruction     (core dumped) CPPFLAGS="" CFLAGS="-g -O2 -fno-strict-aliasing" LDFLAGS="-L/app/lib " CC="gcc" PKG_CONFIG="/usr/bin/pkg-config" DLLTOOL="false" /usr/bin/g-ir-scanner --quiet --add-include-path=. --namespace=GMime --nsversion=2.6 --libtool="../doltlibtool" --include=GObject-2.0 --include=Gio-2.0 --pkg-export=gmime-2.6 --library=libgmime-2.6.la --c-include="gmime/gmime.h" --accept-unprefixed --symbol-prefix "gmime_" --symbol-prefix "g_mime_" --cflags-begin -I.. -I.. -I../util -I../util -DG_LOG_DOMAIN=\"gmime\" -D_LARGEFILE64_SOURCE -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include --cflags-end gmime.h gmime-certificate.h gmime-charset.h gmime-content-type.h gmime-crypto-context.h gmime-data-wrapper.h gmime-disposition.h gmime-encodings.h gmime-error.h gmime-filter.h gmime-filter-basic.h gmime-filter-best.h gmime-filter-charset.h gmime-filter-crlf.h gmime-filter-enriched.h gmime-filter-from.h gmime-filter-gzip.h gmime-filter-html.h gmime-filter-md5.h gmime-filter-strip.h gmime-filter-windows.h gmime-filter-yenc.h gmime-gpg-context.h gmime-header.h gmime-iconv.h gmime-iconv-utils.h gmime-message.h gmime-message-part.h gmime-message-partial.h gmime-multipart.h gmime-multipart-encrypted.h gmime-multipart-signed.h gmime-object.h gmime-param.h gmime-parser.h gmime-part.h gmime-part-iter.h gmime-pkcs7-context.h gmime-signature.h gmime-stream.h gmime-stream-buffer.h gmime-stream-cat.h gmime-stream-file.h gmime-stream-filter.h gmime-stream-fs.h gmime-stream-gio.h gmime-stream-mem.h gmime-stream-mmap.h gmime-stream-null.h gmime-stream-pipe.h gmime-utils.h gmime-version.h internet-address.h gmime.c gmime-certificate.c gmime-charset.c gmime-common.c gmime-content-type.c gmime-crypto-context.c gmime-data-wrapper.c gmime-disposition.c gmime-encodings.c gmime-events.c gmime-filter.c gmime-filter-basic.c gmime-filter-best.c gmime-filter-charset.c gmime-filter-crlf.c gmime-filter-enriched.c gmime-filter-from.c gmime-filter-gzip.c gmime-filter-html.c gmime-filter-md5.c gmime-filter-strip.c gmime-filter-windows.c gmime-filter-yenc.c gmime-gpg-context.c gmime-header.c gmime-iconv.c gmime-iconv-utils.c gmime-message.c gmime-message-part.c gmime-message-partial.c gmime-multipart.c gmime-multipart-encrypted.c gmime-multipart-signed.c gmime-object.c gmime-param.c gmime-parse-utils.c gmime-parser.c gmime-part.c gmime-part-iter.c gmime-pkcs7-context.c gmime-signature.c gmime-stream.c gmime-stream-buffer.c gmime-stream-cat.c gmime-stream-file.c gmime-stream-filter.c gmime-stream-fs.c gmime-stream-gio.c gmime-stream-mem.c gmime-stream-mmap.c gmime-stream-null.c gmime-stream-pipe.c gmime-utils.c internet-address.c libgmime-2.6.la --output GMime-2.6.gir
/usr/share/gobject-introspection-1.0/Makefile.introspection:155: recipe for target 'GMime-2.6.gir' failed

**Comment by gnumdk** [comment]
Same issue today, always segfaulting :-1:

**Comment by gnumdk** [comment]
@yogurt1 Does it build for you?

**Comment by alex285** [comment]
@gnumdk It builds here fine. Also Arch. The only thing i changed from original Flatpak build, was the SDK version to 3.22, because I dont have 3.20 installed.

**Comment by gnumdk** [comment]
@alex285 Strange :-(

**Comment by bil-elmoussaoui** [comment]
I've tried to build the package today, and i run to some other issues than the ones you've mentioned @gnumdk 
```bash
Building module lollypop in /home/bilal/lollypop-flatpak/.flatpak-builder/build/lollypop-1
========================================================================
Clonage dans '/home/bilal/lollypop-flatpak/.flatpak-builder/build/lollypop-1'...
fait.
Déjà sur 'master'
Votre branche est à jour avec 'origin/master'.
fatal: Path '.gitmodules' does not exist in 'master'
Cloning into './po'...
fatal: unable to access 'https://github.com/gnumdk/lollypop-po.git/': Couldn't resolve host 'github.com'
Cloning into './help'...
fatal: unable to access 'https://github.com/gnumdk/lollypop-help.git/': Couldn't resolve host 'github.com'
+ aclocal --install
aclocal: installing 'm4/gsettings.m4' from '/usr/share/aclocal/gsettings.m4'
aclocal: installing 'm4/intltool.m4' from '/usr/share/aclocal/intltool.m4'
aclocal: installing 'm4/introspection.m4' from '/usr/share/aclocal/introspection.m4'
aclocal: installing 'm4/nls.m4' from '/usr/share/aclocal/nls.m4'
aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
aclocal: installing 'm4/yelp.m4' from '/usr/share/aclocal/yelp.m4'
+ glib-gettextize --force --copy
Creating po/ subdirectory
Copying file po/Makefile.in.in

Please add the files
  codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
  progtest.m4
from the /usr/share/aclocal directory to your autoconf macro directory
or directly to your aclocal.m4 file.
You will also need config.guess and config.sub, which you can get from
ftp://ftp.gnu.org/pub/gnu/config/.

+ intltoolize --force --copy --automake
+ autoreconf --verbose --force --install -Wno-portability
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force --warnings=no-portability -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force --warnings=no-portability
autoreconf: running: /usr/bin/autoheader --force --warnings=no-portability
autoreconf: running: automake --add-missing --copy --force-missing --warnings=no-portability
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.
configure.ac:10: installing './install-sh'
configure.ac:10: installing './missing'
Makefile.am: installing './INSTALL'
configure.ac:33: error: required file 'help/Makefile.in' not found
Makefile.am:9: error: required directory ./help does not exist
src/Makefile.am:3: installing './py-compile'
autoreconf: automake failed with exit status: 1
+ exit 1
Error: module lollypop: module lollypop: Le processus fils s'est terminé avec le code 1
make: *** [Makefile:28: org.gnumdk.Lollypop] Error 1

```

**Comment by gnumdk** [comment]
fatal: unable to access 'https://github.com/gnumdk/lollypop-po.git/': Couldn't resolve host 'github.com'
Cloning into './help'...
fatal: unable to access 'https://github.com/gnumdk/lollypop-help.git/': Couldn't resolve host 'github.com'

**Comment by bil-elmoussaoui** [comment]
A new issue here 
```bash
configure.ac:33: error: required file 'help/Makefile.in' not found
Makefile.am:9: error: required directory ./help does not exist
src/Makefile.am:3: installing './py-compile'
autoreconf: automake failed with exit status: 1
```

**Comment by gnumdk** [comment]
Same issue, help missing because git clone failed

**Comment by gnumdk** [comment]
@yogurt1 Thanks for your help!
