### ISSUE TITLE
txt/html decoder?!

### ISSUE THREAD

**Issue by ferranroig** [gnumdk/lollypop#684]
-Lollypop version: 0.9.112
-Gtk Version: dpkg -s libgtk-3-0|grep '^Version'
-Linux distribution: Ubuntu 16.04 LTS 64-bit

-Describe your bug here:
When I start Lollypop and after updating music, it always crashes because Python try to install txt/html decoder.

**Comment by gnumdk** [comment]
Can you paste console output?

**Comment by ferranroig** [comment]
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
ArtDownloader::_get_album_art_spotify: g-io-error-quark: Error HTTP: Bad Request (0) [/Música Tranquila]
ArtDownloader::_get_album_art_lastfm: Album not found [/Música Tranquila]
AlbumArt::pixbuf_from_tags(): gst-core-error-quark: La vostra instal·lació del GStreamer manca un connector. (12)
AlbumArt::pixbuf_from_tags(): gst-core-error-quark: La vostra instal·lació del GStreamer manca un connector. (12)
/usr/lib/python3/dist-packages/sessioninstaller/core.py:47: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst
/usr/lib/python3/dist-packages/sessioninstaller/core.py:48: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
CRITICAL:Could not find any packages to operate on

**Comment by gnumdk** [comment]
There is no crash here...

**Comment by ferranroig** [comment]
Ups!! The error is in Catalan. It means "GStreamer need a connector (12)" Lollypop or Python (I don't know) try to install without success, then Lollypop closes.

**Comment by gnumdk** [comment]
So Ubuntu packagekit seems broken.

# apt-get install ubuntu-restricted-addons

**Comment by ferranroig** [comment]
ubuntu-restricted-addons is already the newest version

**Comment by ferranroig** [comment]
Now Lollypop don't crashes but stops. It change the played file and the playlist. See attached files. It happens aolways when has finished the music update, the blue line at the bottom reached the end. 
![lollypop2](https://cloud.githubusercontent.com/assets/6608027/17147773/7b62e57e-5364-11e6-85ec-bdcbe74c3252.png)
![lollypop1](https://cloud.githubusercontent.com/assets/6608027/17147774/7b6bef66-5364-11e6-86dd-c4cc01548608.png)

**Comment by gnumdk** [comment]
It's fixed in git...

To fix with stable, you need to find what plugin is need for gstreamer to play Amaral/Estrella...

**Comment by gnumdk** [comment]
This can also be broken files... (not playing at all)

**Comment by ferranroig** [comment]
I can't see the entire name but could be an error indexing questions marks? Inside this folder there are a song named **¿Que sera?** 
I've had similar error with an artist named **Caïm Riba**

**Comment by ferranroig** [comment]
Maybe lyrics files txt? or album.nfo file?

**Comment by ferranroig** [comment]
Finally I've found the broken files!!! 
I think you must improve this error messages because it's confusing.

**Comment by gnumdk** [comment]
Sorry, but the message comes from gstreamer, not lollypop...
