### ISSUE TITLE
no cover radio (no add)

### ISSUE THREAD

**Issue by region51** [gnumdk/lollypop#685]
-Lollypop version: lollypop-0.9.112-1.fc24.R.noarch
-Gtk Version: gtk3-3.20.6-1.fc24.x86_64
-Linux distribution: F24

-Describe your bug here: 
no add
![screenshot from 2016-07-16 16-50-22](https://cloud.githubusercontent.com/assets/13280183/16895184/27ab31ac-4b76-11e6-8c0c-6442a4a82fa4.png)
add
![screenshot from 2016-07-16 16-51-05](https://cloud.githubusercontent.com/assets/13280183/16895185/3145cad8-4b76-11e6-96e0-24425a04cb30.png)

**Comment by gnumdk** [comment]
Please describe your bug report, or I will be forced to close this as invalid.

**Comment by region51** [comment]
radios+play radio+ctrl-m =
![screenshot from 2016-07-16 16-50-22](https://cloud.githubusercontent.com/assets/13280183/16895184/27ab31ac-4b76-11e6-8c0c-6442a4a82fa4.png)
