### ISSUE TITLE
Disable notification

### ISSUE THREAD

**Issue by MichaelTiebesl** [gnumdk/lollypop#686]
-Lollypop version: 0.9.112
-Gtk Version: 3.18 
-Linux distribution: Solus 1.2

Is it possible somewhere, to disable the pop up notification what is showing 'next song'? 

![schermafdruk van 2016-07-20 14-10-16](https://cloud.githubusercontent.com/assets/10792019/16976863/c6c3e1f6-4e84-11e6-93cf-026a72105a66.png)

**Comment by gnumdk** [comment]
No option for this... Why would you want to disable it?

**Comment by MichaelTiebesl** [comment]
I don't use it further and not interested what the next song is. No big deal for me, just a question. Was the option there then i would be nice.
