### ISSUE TITLE
Is the use of 'Year' in ID3 tag incorrect?

### ISSUE THREAD

**Issue by garymartynuk** [gnumdk/lollypop#687]
-Lollypop version: 0.9.112
-Gtk Version: 3.18.9
-Linux distribution: Linux Mint Cinnamon

-Describe your bug here:

I've looked through the old issues and found out why Lollypop splits albums with different 'year' tags into separate albums.  I saw someone had a rare instance of a group releasing 2 albums with the same title and they were getting mixed up.  So quite get that using year would sort that out.  

But I think it breaks far more than it fixes from just about any source I've used (Amazon, iTunes etc) they all encode the Year field with the track year not the album year. This also seems to follow the outlined guidelines on ID3.org (unless I am misreading it, which may indeed be possible) but it seems to imply the year is for the year of recording, not the year of release.   [http://id3.org/id3v2.3.0]
The current approach breaks something like 50 albums in my collection, the previous configuration where the year field was not a part of the album splitting would not break a single one.

I can work around it by resetting the year in my carefully honed collection of tags, but it seems I will probably be reducing the accuracy of my tags to get Lollypop to list my albums correctly. 

This is not a problem in Banshee, WMP, Google Music, iTunes etc all of which I have used without this issue over the years.  

Is there any chance that you could reverse this change and I would imagine fix a lot more problems than the current approach?

**Comment by gnumdk** [comment]
4.2.1   TORY    [#TORY Original release year]

For me, the tag for year of recording is this one...

Too many people reporting this bug, I think I will revert this back...

Sorry @jnj
