### ISSUE TITLE
[Feature request] Warning before playback if volume is 100%

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#688]
The title says it all, basically. I almost lost my hearing ability today when I started playing random songs on Lollypop, while using the headset. It would be nice for Lollypop to show a simple dialog when your volume is 100%.

I'm not quite sure how would you present this in the UI. Maybe a simple dialog in which you can confirm, deny or confirm but lower sound volume to 75%, 50%, 25%, etc.

**Comment by gnumdk** [comment]
Just disable stupid default flat volumes:

«flat-volumes scales the device-volume with the volume of the "loudest" application. For example, raising the VoIP call volume will raise the hardware volume and adjust the music-player volume so it stays where it was, without having to lower the volume of the music-player manually. Defaults to yes upstream, but to no within Arch.
Note: The default behavior upstream can sometimes be confusing and some applications, unaware of this feature, can set their volume to 100% at startup, potentially blowing your speakers or your ears. This is why Arch defaults to the classic (ALSA) behavior by setting this to no.»
