### ISSUE TITLE
Artwork in files disabled

### ISSUE THREAD

**Issue by dov29** [gnumdk/lollypop#689]
-Lollypop version: 0.9.110
-Gtk Version: apt-cache policy libgtk2.0-0 libgtk-3-0
-Linux distribution: Ubuntu 15.10 x64

Hi there,

Save artwork in files option is disabled, what I have to do to enable it.
![screenshot from 2016-07-31 12-15-55](https://cloud.githubusercontent.com/assets/18277497/17274716/25c20c0e-5719-11e6-8920-1aa6af622552.png)

Thanks,

**Comment by p3732** [comment]
The hover text should explain it. You need to install kid3-cli.

**Comment by region51** [comment]
>what I have to do to enable it.

![screenshot from 2016-07-31 14-54-21](https://cloud.githubusercontent.com/assets/13280183/17276326/e1369968-572e-11e6-865e-cc8cb6b136d3.png)

**Comment by dov29** [comment]
Oh yeah sorry for that, I got it !

Thks,
