### ISSUE TITLE
Download only one file for artist covers?

### ISSUE THREAD

**Issue by Gert-dev** [gnumdk/lollypop#690]
Hello

[In a previous ticket](https://github.com/gnumdk/lollypop/issues/671) you gave me the neat idea of symlinking my `~/.cache/lollypop_info` folder so I could synchronize it with other computers. I however just noticed that Lollypop seems to include the size in pixels (?) in the filename. This means that if another computer is using a different cover size, he is getting different filenames and thus updating them there does not update it on other computers unless they happen to share the same size.

I was wondering if it is possible to download the largest necessary version (i.e. if artist covers are on their maximum size in the settings) of the artist cover to another folder than the `lollypop_info` and the cache then simply contains smaller cropped versions of that same image. This way, the former folder could then be synchronized properly between different computers whilst the latter is only used for caching, with the filenames still depending on the size selected from the settings.

Thanks in advance

**Comment by gnumdk** [comment]
Will move largest covers to ~/.local/share/lollypop/infos
