### ISSUE TITLE
Unable to play songs from the search results

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#691]
-Lollypop version: revision a3c8012360a0e6922fde989067e33cf3ec61b67f
-Gtk Version: 3.20
-Linux distribution: Fedora 24

When I try to play a song from the search, Lollypop crashes with:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/lollypop/pop_search.py", line 435, in _on_row_activated
    if Lp().player.is_party() or Lp().player.locked or Lp().player.queued:
AttributeError: 'Player' object has no attribute 'queued'

**Comment by gnumdk** [comment]
Flying to espagna, will fix it from the beach ;)

**Comment by kostich** [comment]
Take your time buddy, I'm not in a hurry. Have fun and relax first so you can hack on the Lollypop comfortably until the next vacation. :)

**Comment by gnumdk** [comment]
Was just a revert ;) Nothing to hack on.
