### ISSUE TITLE
Lagging with Huge Archive

### ISSUE THREAD

**Issue by JustPerfection** [gnumdk/lollypop#692]
Hi,
I have over 2TB music including FLAC, MP3, ... Added all files to the Lollypop, Update progress completed and then Disabled Auto Update from preferences but i have some issues:
1. "all albums" scrolling can being super laggy. how can i fix this? can i fix this with preferences>save artwork in files? is Lollypop saving artwork files inside cache folder or it will save artwork files inside each album folder? all of my albums have cover art. saving inside each folder can be really messy!
2. many of my albums have standard ALBUMARTIST tag. I don't know exactly how Lollypop group albums but I need "all albums" tab and "Artist List" group albums by album artist and album.

My System:
CPU: i7 920
RAM: 6GB DRR3
Disk Drive: three 1TB WD Green, OS running on separate Drive (SSD)
OS: Ubuntu 16.04

Thanks.

**Comment by gnumdk** [comment]
No lollypop is saving cache in .cache directory.
Lag with many covers is a GTK issue.
For album artist, it is what lollypop does...

Ps: Can you test lag with wayland, will report this to GTK devs one day or just do it and paste link here.
