### ISSUE TITLE
Lollypop scrobbles to last.fm only when you listen to a whole duration of a track

### ISSUE THREAD

**Issue by mckbsky** [gnumdk/lollypop#693]
-Lollypop version: 0.9.112
-Gtk Version: 3.20
-Linux distribution: Manjaro Gnome 16.06

According to last.fm scrobble api (http://www.last.fm/api/scrobbling) 

> A track should only be scrobbled when the following conditions have been met:
> The track must be longer than 30 seconds.
> And the track has been played for at least half its duration, or for 4 minutes (whichever occurs earlier.)

Right now lollypop respects 30 second minimum length but scrobbles only when you listen to a whole duration of a track.

**Comment by gnumdk** [comment]
Will fix it.
