### ISSUE TITLE
Restore state on startup not working as expected

### ISSUE THREAD

**Issue by brainiac05** [gnumdk/lollypop#694]
-Lollypop: 0.9.112
-Gtk Version:3.20
-Linux distribution:Arch

The option "Restore state on startup" should resume playing at the position where left of. Instead just sets a marker and neither resumes playback nor starts at the marked location when manually starting playback. One of those optio

**Comment by gnumdk** [comment]
Not wanted, see previous discussion in previous issues...

**Comment by jdamboeck** [comment]
At least an option to resume from the saved position on play would be great.
