### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by pepewu** [gnumdk/lollypop#695]
-Lollypop version: 0.9.112
-Gtk Version: 3.20.2
-Linux distribution: Fedora 24 x86_64

-Describe your bug here:
Few days ago my player started to crash randomly. For some artists it crashes when I click his name on sidelist (while loading albums list); it also crashes when I try to open the artist popup (next to play/pasue buttons on top bar). So I reseted the database and now it crashes while reindexing. I have this crash report below. Can I have some hint if this is lollypop error, or something is broken in my system for some reason?
![screenshot from 2016-08-09 22-50-34](https://cloud.githubusercontent.com/assets/3642414/17533667/22252026-5e86-11e6-910e-93db78674fcf.png)

**Comment by gnumdk** [comment]
Please paste backtrace using coredumpctl command.
Google for command usage ;)

**Comment by pepewu** [comment]
It's disabled on Fedora by default, I managed to get this:

2016-08-11 22:02:00 CEST   2059  1000  1000   6 * /usr/bin/python3.5
[root@localhost pepewu]# coredumpctl gdb 2059
           PID: 2059 (python3)
           UID: 1000 (pepewu)
           GID: 1000 (pepewu)
        Signal: 6 (ABRT)
     Timestamp: 2016-08-11 22:01:59 CEST (29s ago)
  Command Line: python3 /usr/bin/lollypop
    Executable: /usr/bin/python3.5
 Control Group: /
         Slice: -.slice
       Boot ID: f6823f6ac86d4d12bd7e1bd5c119e653
    Machine ID: 9c8fa0bee5cd432fb70ae50e7c567cec
      Hostname: localhost.localdomain
      Coredump: /var/lib/systemd/coredump/core.python3.1000.f6823f6ac86d4d12bd7e1bd5c119e653.2059.1470945719000000000000.lz4
       Message: Process 2059 (python3) of user 1000 dumped core.
                
                Stack trace of thread 2166:
                #0  0x00007f1d746ec6f5 raise (libc.so.6)
                #1  0x00007f1d746ee2fa abort (libc.so.6)
                #2  0x00007f1d3906e14b init_context_defaults (libavcodec.so.57)
                #3  0x00007f1d3906e1a6 avcodec_alloc_context3 (libavcodec.so.57)
                #4  0x00007f1d3a839080 gst_ffmpeg_cfg_install_property (libgstlibav.so)
                #5  0x00007f1d3a82f38e gst_ffmpegvidenc_class_init (libgstlibav.so)
                #6  0x00007f1d6cddca4a g_type_class_ref (libgobject-2.0.so.0)
                #7  0x00007f1d5e5d5e74 gst_element_register (libgstreamer-1.0.so.0)
                #8  0x00007f1d3a82fb1c gst_ffmpegvidenc_register (libgstlibav.so)
                #9  0x00007f1d3a822100 plugin_init (libgstlibav.so)
                #10 0x00007f1d5e5f7727 gst_plugin_register_func (libgstreamer-1.0.so.0)
                #11 0x00007f1d5e5f9676 _priv_gst_plugin_load_file_for_registry (libgstreamer-1.0.so.0)
                #12 0x00007f1d5e5fa37a gst_plugin_load_by_name (libgstreamer-1.0.so.0)
                #13 0x00007f1d5e5facfe gst_plugin_feature_load (libgstreamer-1.0.so.0)
                #14 0x00007f1d5e620a83 gst_type_find_factory_call_function (libgstreamer-1.0.so.0)
                #15 0x00007f1d5d488381 gst_type_find_helper_get_range (libgstbase-1.0.so.0)
                #16 0x00007f1d5d6c207a gst_tag_demux_element_find (libgsttag-1.0.so.0)
                #17 0x00007f1d5d6c315d gst_tag_demux_element_loop (libgsttag-1.0.so.0)
                #18 0x00007f1d5e61c0f1 gst_task_func (libgstreamer-1.0.so.0)
                #19 0x00007f1d6cb0f735 g_thread_pool_thread_proxy (libglib-2.0.so.0)
                #20 0x00007f1d6cb0ed38 g_thread_proxy (libglib-2.0.so.0)
                #21 0x00007f1d751925ca start_thread (libpthread.so.0)
                #22 0x00007f1d747baead __clone (libc.so.6)
                
                Stack trace of thread 2069:
                #0  0x00007f1d747af32d poll (libc.so.6)
                #1  0x00007f1d6cae8a46 g_main_context_iterate.isra.29 (libglib-2.0.so.0)
                #2  0x00007f1d6cae8dd2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f1d6c3f0f76 gdbus_shared_thread_func (libgio-2.0.so.0)
                #4  0x00007f1d6cb0ed38 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f1d751925ca start_thread (libpthread.so.0)
                #6  0x00007f1d747baead __clone (libc.so.6)
                
                Stack trace of thread 2167:
                #0  0x00007f1d747b4ff9 syscall (libc.so.6)
                #1  0x00007f1d6cb2cdca g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007f1d6cabd489 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0)
                #3  0x00007f1d6cb0f70a g_thread_pool_thread_proxy (libglib-2.0.so.0)
                #4  0x00007f1d6cb0ed38 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f1d751925ca start_thread (libpthread.so.0)
                #6  0x00007f1d747baead __clone (libc.so.6)
                
                Stack trace of thread 2094:
                #0  0x00007f1d747af3f1 ppoll (libc.so.6)
                #1  0x00007f1d5e5feb00 gst_poll_wait (libgstreamer-1.0.so.0)
                #2  0x00007f1d5e5bb884 gst_bus_timed_pop_filtered (libgstreamer-1.0.so.0)
                #3  0x00007f1d5dddb552 start_discovering (libgstpbutils-1.0.so.0)
                #4  0x00007f1d5ddde809 gst_discoverer_discover_uri (libgstpbutils-1.0.so.0)
                #5  0x00007f1d6c89cc58 ffi_call_unix64 (libffi.so.6)
                #6  0x00007f1d6c89c6ba ffi_call (libffi.so.6)
                #7  0x00007f1d6d460f4c pygi_invoke_c_callable (_gi.cpython-35m-x86_64-linux-gnu.so)
                #8  0x00007f1d6d462a1a pygi_function_cache_invoke (_gi.cpython-35m-x86_64-linux-gnu.so)
                #9  0x00007f1d6d456619 _callable_info_call (_gi.cpython-35m-x86_64-linux-gnu.so)
                #10 0x00007f1d7540cc27 PyObject_Call (libpython3.5m.so.1.0)
                #11 0x00007f1d754c763e PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #12 0x00007f1d754cacfb PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #13 0x00007f1d754cc713 _PyEval_EvalCodeWithName (libpython3.5m.so.1.0)
                #14 0x00007f1d754cc7f3 PyEval_EvalCodeEx (libpython3.5m.so.1.0)
                #15 0x00007f1d75437505 function_call (libpython3.5m.so.1.0)
                #16 0x00007f1d7540cc27 PyObject_Call (libpython3.5m.so.1.0)
                #17 0x00007f1d754c71a0 PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #18 0x00007f1d754cacfb PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #19 0x00007f1d754cacfb PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #20 0x00007f1d754cc713 _PyEval_EvalCodeWithName (libpython3.5m.so.1.0)
                #21 0x00007f1d754cc7f3 PyEval_EvalCodeEx (libpython3.5m.so.1.0)
                #22 0x00007f1d75437418 function_call (libpython3.5m.so.1.0)
                #23 0x00007f1d7540cc27 PyObject_Call (libpython3.5m.so.1.0)
                #24 0x00007f1d75423664 method_call (libpython3.5m.so.1.0)
                #25 0x00007f1d7540cc27 PyObject_Call (libpython3.5m.so.1.0)
                #26 0x00007f1d754c3047 PyEval_CallObjectWithKeywords (libpython3.5m.so.1.0)
                #27 0x00007f1d75506e72 t_bootstrap (libpython3.5m.so.1.0)
                #28 0x00007f1d751925ca start_thread (libpthread.so.0)
                #29 0x00007f1d747baead __clone (libc.so.6)
                
                Stack trace of thread 2168:
                #0  0x00007f1d747b4ff9 syscall (libc.so.6)
                #1  0x00007f1d6cb2cdca g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007f1d6cabd489 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0)
                #3  0x00007f1d6cb0f70a g_thread_pool_thread_proxy (libglib-2.0.so.0)
                #4  0x00007f1d6cb0ed38 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f1d751925ca start_thread (libpthread.so.0)
                #6  0x00007f1d747baead __clone (libc.so.6)
                
                Stack trace of thread 2165:
                #0  0x00007f1d747b4ff9 syscall (libc.so.6)
                #1  0x00007f1d6cb2ccaf g_cond_wait (libglib-2.0.so.0)
                #2  0x00007f1d5e61c2dd gst_task_func (libgstreamer-1.0.so.0)
                #3  0x00007f1d6cb0f735 g_thread_pool_thread_proxy (libglib-2.0.so.0)
                #4  0x00007f1d6cb0ed38 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f1d751925ca start_thread (libpthread.so.0)
                #6  0x00007f1d747baead __clone (libc.so.6)
                
                Stack trace of thread 2059:
                #0  0x00007f1d747af32d poll (libc.so.6)
                #1  0x00007f1d6cae8a46 g_main_context_iterate.isra.29 (libglib-2.0.so.0)
                #2  0x00007f1d6cae8b5c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f1d6c3ba58d g_application_run (libgio-2.0.so.0)
                #4  0x00007f1d6c89cc58 ffi_call_unix64 (libffi.so.6)
                #5  0x00007f1d6c89c6ba ffi_call (libffi.so.6)
                #6  0x00007f1d6d460f4c pygi_invoke_c_callable (_gi.cpython-35m-x86_64-linux-gnu.so)
                #7  0x00007f1d6d462a1a pygi_function_cache_invoke (_gi.cpython-35m-x86_64-linux-gnu.so)
                #8  0x00007f1d6d456619 _callable_info_call (_gi.cpython-35m-x86_64-linux-gnu.so)
                #9  0x00007f1d7540cc27 PyObject_Call (libpython3.5m.so.1.0)
                #10 0x00007f1d754c763e PyEval_EvalFrameEx (libpython3.5m.so.1.0)
                #11 0x00007f1d754cc713 _PyEval_EvalCodeWithName (libpython3.5m.so.1.0)
                #12 0x00007f1d754cc7f3 PyEval_EvalCodeEx (libpython3.5m.so.1.0)
                #13 0x00007f1d754cc81b PyEval_EvalCode (libpython3.5m.so.1.0)
                #14 0x00007f1d754ebd44 run_mod (libpython3.5m.so.1.0)
                #15 0x00007f1d754ee2e5 PyRun_FileExFlags (libpython3.5m.so.1.0)
                #16 0x00007f1d754ee455 PyRun_SimpleFileExFlags (libpython3.5m.so.1.0)
                #17 0x00007f1d75504e4c Py_Main (libpython3.5m.so.1.0)
                #18 0x00005568c6286b70 main (python3.5)
                #19 0x00007f1d746d8731 __libc_start_main (libc.so.6)
                #20 0x00005568c6286c19 _start (python3.5)
                
                Stack trace of thread 2067:
                #0  0x00007f1d747af32d poll (libc.so.6)
                #1  0x00007f1d6cae8a46 g_main_context_iterate.isra.29 (libglib-2.0.so.0)
                #2  0x00007f1d6cae8b5c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f1d5ca33fad dconf_gdbus_worker_thread (libdconfsettings.so)
                #4  0x00007f1d6cb0ed38 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f1d751925ca start_thread (libpthread.so.0)
                #6  0x00007f1d747baead __clone (libc.so.6)
                
                Stack trace of thread 2068:
                #0  0x00007f1d747af32d poll (libc.so.6)
                #1  0x00007f1d6cae8a46 g_main_context_iterate.isra.29 (libglib-2.0.so.0)
                #2  0x00007f1d6cae8b5c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f1d6cae8ba1 glib_worker_main (libglib-2.0.so.0)
                #4  0x00007f1d6cb0ed38 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f1d751925ca start_thread (libpthread.so.0)
                #6  0x00007f1d747baead __clone (libc.so.6)

GNU gdb (GDB) Fedora 7.11.1-75.fc24
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.5...Reading symbols from /usr/bin/python3.5...(no debugging symbols found)...done.
(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 2166]
[New LWP 2069]
[New LWP 2167]
[New LWP 2094]
[New LWP 2168]
[New LWP 2165]
[New LWP 2059]
[New LWP 2067]
[New LWP 2068]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `python3 /usr/bin/lollypop'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1d746ec6f5 in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f1d4daf2700 (LWP 2166))]
Missing separate debuginfos, use: dnf debuginfo-install python3-3.5.1-12.fc24.x86_64

**Comment by gnumdk** [comment]
Perfect, the issue is in Gstreamer... Report this to Fedora... Can't reproduce on ArchLinux...

**Comment by gnumdk** [comment]
Not a fedora issue, comes from libavcodec so it's a RPM Fusion packages issue...
