### ISSUE TITLE
Unresolvable gstreamer dependency

### ISSUE THREAD

**Issue by jelabarre59** [gnumdk/lollypop#696]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate
- Cloud playback

-Lollypop version: 0.9.112-1ppa1ubuntu1.1
-Gtk Version: 3.18.9
-Linux distribution: Linux Mint 18

-Describe your bug here:
Starting the application (every time), it comes up with the error:
===================================
Python (v3.5) requires to install plugins to play media files of the following type: audio/x-midi-event decoder
gstreamer1.0-plugins-bad (i386)
===================================

This is a 64-bit system, gstreamer1.0-plugins-bad:amd64 is already installed.
The application is unable to install the i386 version because of unresolvable dependencies.  I have tried installing it with apt-get, but the list of sub-dependencies grew unmanagably large in short order.  Essentially, you would end up installing a 32-bit package of nearly everything on the system by the time you resolved the dependencies.

**Comment by gnumdk** [comment]
Already fixed in git
