### ISSUE TITLE
Sort files by file name if track number is not present in the tags

### ISSUE THREAD

**Issue by FreddieChopin** [gnumdk/lollypop#697]
-Lollypop version: 0.9.110
-Gtk Version: 3.20.6
-Linux distribution: Arch Linux

-Describe your bug here:
In some cases files from albums don't have track number in the tags, but this information can be found in the filename - the files are named  01-artist-song, 02-artist-song, 03-artist-song, ...

Now Lollypop will display such album with a random order (I really have no idea what affects it, but it's not name [obviously], modification/access time, size or inode number - it's the same order as given by `ls -laf`). In some cases (so called "scene releases") fixing the tags is out of the question, so the only option left is to sort by filename. In such releases there's usually a m3u playlist with proper order, but I guess using filenames would be more general and easier to implement.

**Comment by gnumdk** [comment]
Just reset database in about dialog and lollypop will take this in account.

**Comment by FreddieChopin** [comment]
Works as expected! Thanks!

**Comment by julianrichen** [comment]
@gnumdk Another popular way to name files without metadata is `album.track <other stuff>`, ex:
1.01 Artist - Song 01
1.02 Artist - Song 02
1.03 Artist - Song 03
2.01 Artist - Track 01
2.02 Artist - Track 02
2.03 Artist - Track 03
etc...

I don't know how complex you want the parser to be but I know a fair amount of people use this method.
