### ISSUE TITLE
Track transition isn't „atomic“

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#698]
-Lollypop version: 0.9.112
-Gtk Version: 3.20.2
-Linux distribution: Fedora 24

In the top bar of the screenshot below you can see that the track „The Light“ isn't finished, while the menu popup (of „The Light“) already displays the next track „One Day Remains“ as being currently played. This is surely not a big issue, but would be nice if being resolved as this maybe prevents other errors, when there are two conflicting states occurring in parallel.

![disturbed - the light - lollypop_012](https://cloud.githubusercontent.com/assets/10520767/17644477/06135f74-6188-11e6-8ea7-88a15c8d1681.png)

**Comment by gnumdk** [comment]
Do you have a way to reproduce, here it works as expected...

**Comment by fb87** [comment]
Just clicked stop and recognized this issue by accident.

**Comment by gnumdk** [comment]
Ok ;)

**Comment by gnumdk** [comment]
No issue in fact. Widgets update are based on track start. As you pause just before start, widget did not receive message yet... But internal state is good.
