### ISSUE TITLE
Crash on restoring state

### ISSUE THREAD

**Issue by Rombusevil** [gnumdk/lollypop#699]
-Lollypop version: stable branch
-Gtk Version: 3.20.7-1
-Linux distribution: Debian Stretch/Sid

When opening lollypop I can see the screen for a while and then it crashes. This is what I get on the console:

> No module named 'wikipedia'
> Advanced artist informations disabled
> $ sudo pip3 install wikipedia
> 
> (lollypop:29217): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1705:22: Not a valid image
> 
> (lollypop:29217): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1705:22: Not a valid image
> Player::restore_state(): track missing
> Abortado

**Comment by gnumdk** [comment]
This is a segfault somewhere is Gtk/Gnome stack (from Debian SID) but not in lollypop (lollypop is written in python). Look at coredumpctl (disabled on Debian I guess) to get full backtrace and report but to Debian.
