### ISSUE TITLE
I can't run lollypop with LC_ALL=C

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#70]
When I wants to see the interfact in LTR (English), I tried it by run
the app with LANG=C or LC_ALL=C.
Lollypop crach when I run it with LC_ALL=C:
$ LC_ALL=C lollypop 
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Unhandled exception in thread started by <bound method CollectionScanner._scan of <CollectionScanner object at 0x7ff5bc0f6f30 (lollypop+collectionscanner+CollectionScanner at 0x7ff5cce18c40)>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 152, in _scan
    for root, dirs, files in os.walk(path):
  File "/usr/lib/python3.4/os.py", line 361, in walk
    names = listdir(top)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-20: ordinal not in range(128)
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1296, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.4/threading.py", line 1019, in _delete
    del _active[get_ident()]
KeyError: 140693221693184

It important for cases I wants to see if some arrows (hamm) are revert, or some spacing or margin
or wrong in RTL.

**Comment by gnumdk** [comment]
Supporting non unicode locales with python3 is a pain... I tried, it makes code hard to read and doesn't works...

Python without an unicode locale doesn't support unicode strings, you need to converts strings to bytes...
Glib wants unicode strings...

So, if you want english:
LANG=en_US.UTF-8 lollypop

If someone have a working idea on how to deal with this without making the code full of bytes/strings convertions...
