### ISSUE TITLE
Last.FM issues

### ISSUE THREAD

**Issue by killkrt** [gnumdk/lollypop#701]
-Lollypop version: 0.9.112
-Gtk Version: 3.20.9-1, 2.24.30+95+g876b5f7-1
-Linux distribution: Arch Linux

-Describe your bug here:
When I try to connect my Last.FM profile I get almost always a little icon showing a sad face, and in the console I get the following errors:

```
LastFM::_populate_loved_tracks: Operation failed - Most likely the backend service failed. Please try again.
Lastfm::scrobble(): Operation failed - Most likely the backend service failed. Please try again.
Lastfm::scrobble(): Invalid parameters - Your request is missing a required parameter
Lastfm::scrobble(): Invalid parameters - Your request is missing a required parameter
```
I've installed all packages requested for Last.FM integration:
`kid3-qt, libsecret, python-pylast, gnome-keyring`

**Comment by gnumdk** [comment]
Same issue here... Gnome Accounts fails to connect... Without Gnome Accounts, Lollypop fails.
Seems lastfm is broken...

**Comment by gnumdk** [comment]
Working again

**Comment by killkrt** [comment]
Yeah, I confirm... It is working again!

Thank you.
