### ISSUE TITLE
Search should be 'smarter'

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#704]
If I type only 'solo', the search finds Nils Frahm's album 'Solo', alongside all other albums, artists and tracks which have 'solo' in their name. If I type 'nils frahm', it also finds Nils Frahm - Solo, this time alongside all albums, artists and tracks with 'nils frahm' in their name. If I type 'nils frahm solo' or 'solo nils frahm', it finds nothing.
Additionally, if I type only 'frahm nils', it also finds nothing.

The search should be able to find something by looking for the different search terms in multiple tags at the same time.

Also, the search should be able to find artists/albums/tracks with accents even when you don't type the accents, for example if you search 'royksopp' it should find everything by Röyksopp, or 'francois couperin' should find François Couperin.

**Comment by gnumdk** [comment]
Not sure what to do about accents...

Sqlite does not support collation on "like"... So I can only duplicate all text entries in database with a "non accent version" but it sucks :-1:

**Comment by d9h02f** [comment]
@gnumdk First commit of 'Smarter search' doesn't seem to work anymore, 'frahm nils' or 'nils frahm solo doesn't find anything anymore.

**Comment by gnumdk** [comment]
I know, need more work with web search enabled... Will give a look.

**Comment by gnumdk** [comment]
Done
