### ISSUE TITLE
Bit-Perfect Playback

### ISSUE THREAD

**Issue by JustPerfection** [gnumdk/lollypop#705]
Please add bit-prefect playback to the settings. We need it for high end playback.

**Comment by gnumdk** [comment]
What is bit-perfect playback?

**Comment by gnumdk** [comment]
Ok, found... https://ubuntuforums.org/showthread.php?t=1939711

Nothing to do with Lollypop... Configure pulseaudio or switch to OSS/Alsa...

**Comment by JustPerfection** [comment]
pulseaudio can not play bit-perfect. it will manipulate audio (up sample or down sample). System bit-perfect configuration isn't the only thing we need for bit-perfect playback. The player must have ALSA and bit-perfect output device to select. Players Like DeaDBeeF can play bit-perfect with this setting. you can find it in Edit -> Preferences -> Sound

For ALSA and mpd configuration:
https://lacocina.nl/audiophile-mpd

Thanks.

**Comment by gnumdk** [comment]
No, you can use alsa configuration file to select your bit-perfect output device.

Will not add such option, too confusing...

http://www.head-fi.org/t/700447/guide-newb-guide-to-bit-perfect-linux-audio
