### ISSUE TITLE
Feature request: Deactivation of notification pop-ups

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#706]
Is it possible that the notification does change it's status (for displaying the currently playing song when it changes) but doesn't pop up? This behaviour is very annoying and distracting to me. If not, can you please provide a setting for deactivating notifications completely?

**Comment by gnumdk** [comment]
Already exists in dconf: disable-notifications

**Comment by blackjackshellac** [comment]
You can disable notifications or fine tune the settings per application in gnome settings (also somewhat confusingly known as gnome-control-center) notifications.

**Comment by fb87** [comment]
Thanks, haven't found Lollypop in dconf at first (search just searches keys, not the program tree...). But I can't find the settings @blackjackshellac is talking about, sorry.

**Comment by fbruetting** [comment]
Now, with 0.9.244 per Flatpak, there is no `disable-notifications`. Just `infoswitch` of which I don't know the available options (and if it’s the successor, at all). How can I achieve this now? (⇒ I’d like to deactivate the track switching notifications, but I still want other errors like „missing GStreamer plugin“ to pop up!)
