### ISSUE TITLE
Feature request: More prominent displaying of the ratings

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#707]
I think it would be nice if
a) the rating of the currently played track could be displayed (and edited) in the title bar, and
b) the ratings of all songs could be displayed (but better not edited) in the album overview and the album-popup.
For people not using ratings, an activation setting would be useful, too. :)

**Comment by gnumdk** [comment]
I really think this is a bad idea. It will clutter the interface.

So I refused...

**Comment by fb87** [comment]
And if you position the stars in the popup, which appears when you click on the current track?

**Comment by gnumdk** [comment]
Ok, you give me an idea... I can put it in the tooltip... Just hope it will be not to annoying to have tooltip all the time...

**Comment by gnumdk** [comment]
Lollypop users, feel free to give your feeling about this.

**Comment by fb87** [comment]
Thanks! :)

**Comment by gnumdk** [comment]
@fb87 In fact, it already exists on right click ;)

**Comment by fb87** [comment]
How shout someone recognize that? xD

**Comment by fb87** [comment]
Problem is: That doesn't work. I cannot click the stars nor the heart.

**Comment by gnumdk** [comment]
Strange, here it works... Distro?

**Comment by gnumdk** [comment]
Can you make a screencast, here it works (ArchLinux/Ubuntu)

**Comment by fb87** [comment]
Ok, funny thing. Now it somehow works halfway. A few days ago neither of the controls reacted, now the heart works, but not the fourth star, as you see in the gif:
![peek 2016-09-07 20-38](https://cloud.githubusercontent.com/assets/10520767/18324172/643d9328-753b-11e6-8b39-b0e010258809.gif)

**Comment by fb87** [comment]
Hi Cédric, what do you think about placing rating (stars) in between the title and the duration, if there's as much space as on my screenshod (UHD display)? Since you first rejected because of cluttering the UI, maybe at this resolution it's ok?

![in flames - pinball map - lollypop_006](https://cloud.githubusercontent.com/assets/10520767/19251932/2731ad36-8f42-11e6-9fa7-809dc6c0eeef.png)
