### ISSUE TITLE
Gapless playblack

### ISSUE THREAD

**Issue by aitbw** [gnumdk/lollypop#708]
Hello!

First of all, let me thank you for the great work you've done with Lollypop. It's the first music player I've used in Linux I feel comfortable using. <3

That said, it would be nice if gapless playback could be added, especially for concept albums like Pink Floyd's _The Dark Side of the Moon_ or live albums like Adele's _Live At The Royal Albert Hall_. Current playback, while it's barely perceptible, bugs me a little bit with the aforementioned albums.

**Lollypop version**: 0.9.112
**GTK version**: 3.20.9-1
**Linux distro**: Manjaro Linux

Keep up the good work, man!

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=620323

It's a gstreamer issue... First, it's an mpeg issue... Gapless playback with mp3/4 is a hack.

If you really want gapless playback, use ogg vorbis or flac.
