### ISSUE TITLE
Unicode locale error while running lollypop music player

### ISSUE THREAD

**Issue by jugrajsingh** [gnumdk/lollypop#709]
Unable to run
Player continue showing same error
Installed using PPA
Already referred to this post [http://elementaryos.stackexchange.com/questions/1312/unicode-locale-error-while-running-lollypop-music-player](http://elementaryos.stackexchange.com/questions/1312/unicode-locale-error-while-running-lollypop-music-player) Didn't Help
Using ubtuntu 16.04
![Error](https://cloud.githubusercontent.com/assets/7789490/18202739/b601b7bc-712f-11e6-92a9-76d8ba713122.png)

**Comment by gnumdk** [comment]
echo $LANG

**Comment by gnumdk** [comment]
ping?

**Comment by jugrajsingh** [comment]
On Sep 3, 2016 10:40 PM, "Cédric Bellegarde" <notifications@github.com>
wrote:
>
> ping?
>
> —
Got it working just now
I just update my system and reconfigure the locale
At last a restart required.
Done thanks :)

--

Jugraj Singh

git :- https://github.com/jugrajsingh
blog :- ezecodes.wordpress.com

"Do not open a door unless you are ready to walk through it"
