### ISSUE TITLE
Recently Added not Working Properly

### ISSUE THREAD

**Issue by Tvrdoglavi** [gnumdk/lollypop#718]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate
- Cloud playback

-Lollypop version:0.9.113
-Gtk Version:
-Linux distribution: Ubuntu Gnome 16.04

-Describe your bug here:

Recently added seems to work for a while but then it starts showing music that I had on my system for years as recently added and music that was added as recently as a few days is not shown any more.
I looks like Lollypop is sorting this by the date that Lollypop found the files instead of when they were created or added to the hard drive.

**Comment by gnumdk** [comment]
Lollypop does this:
- If this is a new album, it use current date
- On first scan, it uses the tracks mtime. (And as you report that your db have been destroyed...)

**Comment by Tvrdoglavi** [comment]
Not sure what mtime is, but since Lollypop keeps wiping my DB almost every time I reboot, it's pretty annoying and really a bug. Is it possible to use "Date Created"  or "Last Modified" for recently added?

**Comment by gnumdk** [comment]
No because mtime is not a good choice for recently added... That's why lollypop only use this on first scan

**Comment by gnumdk** [comment]
I fixed something in the code that may be related with your issue.

Will be in 0.9.200... But you will need to remove:
~/.local/share/lollypop/history.db
