### ISSUE TITLE
Database wipe after reboot

### ISSUE THREAD

**Issue by Tvrdoglavi** [gnumdk/lollypop#719]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate
- Cloud playback

-Lollypop version: 0.9.113
-Gtk Version:
-Linux distribution: Ubuntu Gnome 16.04

-Describe your bug here:
I keep my music on a secondary hard drive. The hard drive is set to mount automatically.
When I reboot my system and start Lollypop, Lollypop can not find the hard drive and trying to play music doesn't work even though it shows all of the music, including album covers.
When I go to Files and open the secondary hard drive and then restart Lollypop, its database is wiped and it starts and update that takes a long time. If I remember to open the secondary hard drive, in a file explorer, after a reboot, Lollypop doesn't have that problem.

**Comment by gnumdk** [comment]
Is "Auto update music" on? If yes, it's not a bug...

**Comment by Tvrdoglavi** [comment]
Auto update is on, but the main bug is that it doesn't see the mounted hard drive. Also, it should not wipe the entire DB without a warning.
