### ISSUE TITLE
Show the album's cover as the icon in the message bubble instead of lollypop's icon

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#72]

**Comment by gnumdk** [comment]
Sorry, lollypop already show cover... But Gnome 3.16 doesn't support images in notifications...

**Comment by yoseforb** [comment]
Do you mean it is a bug in gnome-shell?

**Comment by yoseforb** [comment]
I just entered a bug for this:
https://bugzilla.gnome.org/show_bug.cgi?id=747427

**Comment by yoseforb** [comment]
Hmm, what do you think on the idea to change the lollypop's icon every song?

**Comment by ianbrunelli** [comment]
Xnoise displays the album cover on the notifications. No controls, though.

They're probably passing the cover as app icon.

![captura de tela de 2015-04-06 23-31-17](https://cloud.githubusercontent.com/assets/5755892/7016123/100b84b0-dcb5-11e4-9751-e1c8f6be5f52.png)

**Comment by gnumdk** [comment]
Strange, i'm not passing application icon, just lollypop desktop file and gnome shell get icon from here...

**Comment by gnumdk** [comment]
Xnoise doesn't use libnotify... I can't do nothing here as it's a GNOME shell/notify-osd issue

Works as expected with Elementary

**Comment by gnumdk** [comment]
Finaly fixed this one, was really simple :-(
