### ISSUE TITLE
Navigate to Artist

### ISSUE THREAD

**Issue by Tvrdoglavi** [gnumdk/lollypop#720]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate
- Cloud playback

-Lollypop version: 0.9.113
-Gtk Version:
-Linux distribution: Ubuntu Gnome 16.04

-Describe your bug here:
This is more of a feature request but I don't see any other way to make a suggestion.

When you click on an artist's name in the top bar, it opens up a panel with options (album, last fm, etc..). No I like to use the Random Album sorting options but sometimes I see an artist's album appear and decide that I would like to listen to a different album from this artist. 
It would be great if the same kind of popup would be added if an artist's name was clicked in the album view. Or to add another button the the album picture that could be called "More from this Artist" that would take you to this artist's albums directly.

**Comment by gnumdk** [comment]
Tested and refused... Sorry, looks really bad as this BIG popover can't be placed properly...

**Comment by Tvrdoglavi** [comment]
How about just taking you to artist's album view? Just like clicking on the artist name in the list on the left.

**Comment by gnumdk** [comment]
Yes, I'm thinking about this but will only add this in album menu, don't want to add one more overlay button and clicking on artist is really an unwanted behaviour.
