### ISSUE TITLE
Starting Lollypop in "small" mode does not immediately display the current playing track

### ISSUE THREAD

**Issue by Gert-dev** [gnumdk/lollypop#723]
-Lollypop version: 0.9.113
-Gtk Version: 3.20
-Linux distribution: Arch Linux

I noticed a minor visual problem: if you resize Lollypop down to the "small" size, the currently playing track and artist will move to the bottom of the window. However, if you then quit Lollypop and start it again, it remembers the old (small) size, but playing a track does not (immediately) show the bottom bar again until you resize the window.

Thanks

**Comment by gnumdk** [comment]
It should not remember the small size, what is your window manager?

**Comment by Gert-dev** [comment]
I'm using GNOME shell (mutter). Strange, I thought remembering the window size was actually a feature? I open Lollypop, make the window a lot smaller by resizing it, close Lollypop via the GNOME application menu, start it again and it uses the same size as when it quit before.

**Comment by gnumdk** [comment]
Ok, I understand, your not really in mini mode on start (you can't start a track in mini mode).
