### ISSUE TITLE
Clear queue button crashes app

### ISSUE THREAD

**Issue by slugger7** [gnumdk/lollypop#724]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate

-Lollypop version:
-Gtk Version:
-Linux distribution:

-Describe your bug here:

When clicking the clear queue button in the queue dropdown the application crashes.

**Comment by gnumdk** [comment]
Not here, please provide console output.

**Comment by slugger7** [comment]
slugger@slugger-X550JX:~$ lollypop
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Downloader::_get_album_art_lastfm: Album not found [/Unknown]
Downloader::_get_album_art_spotify: g-io-error-quark: HTTP Error: Bad Request (0) [/Unknown]
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/01 Come Talk to Me.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/02 Steam.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/03 Across the River.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/04 Slow Marimbas.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/05 Shaking the Tree.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/06 Red Rain.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/07 Blood of Eden.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/08 Kiss That Frog.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/09 Washing of the Water.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 1/10 Solsbury Hill.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 2/01 Digging in the Dirt.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 2/02 Sledgehammer.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 2/03 Secret World.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 2/04 Don't Give Up.wma
gst-stream-error-quark: The stream is encrypted and decryption is not supported. (12) /home/slugger/Music/Music/P/Peter Gabriel/Secret World Live Disc 2/05 In Your Eyes.wma
gst-stream-error-quark: Could not detect type of contents (4) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/Avalanche.mp3
gst-stream-error-quark: Could not detect type of contents (4) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/Blasphemy.mp3
gst-stream-error-quark: Could not detect type of contents (4) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/Doomed.mp3
gst-stream-error-quark: No valid frames found before end of stream (5) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/Drown (New).mp3
gst-stream-error-quark: Could not detect type of contents (4) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/Follow You.mp3
gst-stream-error-quark: Could not detect type of contents (4) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/Happy Song.mp3
gst-stream-error-quark: No valid frames found before end of stream (5) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/Oh No.mp3
gst-stream-error-quark: Could not detect type of contents (4) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/Run.mp3
gst-stream-error-quark: GStreamer encountered a general stream error. (1) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/Throne.mp3
gst-stream-error-quark: Could not detect type of contents (4) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/True Friends.mp3
gst-stream-error-quark: Could not detect type of contents (4) /home/slugger/Music/Music/B/Bring Me The Horizon/That's The Spirit/What You Need.mp3
gst-stream-error-quark: This appears to be a text file (5) /home/slugger/Music/Music/B/Bullet For My Valentine/Bullet For My Valentine - Temper Temper [2013-Album] Mp3 CBR 320Kbps NimitMak SilverRG/Playlist.pls
gst-stream-error-quark: No valid frames found before end of stream (5) /home/slugger/Music/Music/E/Electric Light Orchestra/1983 - Electric Light Orchestra - Secret Messages/Electric Light Orchestra - Secret Messages - 11 - Rock & Roll Is King.flac
gst-stream-error-quark: No data in file (4) /home/slugger/Music/Music/F/From Atlantis/From_Atlantis-Echoes_And_Answers-www.mrtzcmp3.net.mp3
gst-stream-error-quark: This appears to be a text file (5) /home/slugger/Music/Music/M/Motionless In White/[2011] - Infamous (Delux Edition)/Playlist.pls
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/pop_albums.py", line 465, in __on_clear_clicked
    GLib.idle_add(self._clear, True)
AttributeError: 'AlbumsView' object has no attribute '_clear'
slugger@slugger-X550JX:~$
