### ISSUE TITLE
expandable artistview

### ISSUE THREAD

**Issue by medicap** [gnumdk/lollypop#727]
http://imgur.com/a/oQeRY

for featured artists i think it would look good with an expandable listview, ex.

http://www.dmitry-kazakov.de/ada/gtk_unit_selection.gif

but still display the albums track in order rather than split by composer.

**Comment by gnumdk** [comment]
This artists should never be shown in this list...
Your tags are just broken...
#574

**Comment by medicap** [comment]
i don't believe so, these are reading from composer settings for some reason.
