### ISSUE TITLE
MP3 sorted by composer, OGG sorted by artist/albumartist

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#728]
I have albums by the artist Helios, some are in MP3 and some are in OGG. They all have artist tag 'Helios', albumartist 'Helios' and composer 'Keith Kenniff'. Lollypop shows the OGG albums under Helios and the MP3 albums under Keith Kenniff. They should all show up under Helios, the artist/albumartist. I think they should also show up under Keith Kenniff, because I have other albums by Keith Kenniff as artist/albumartist or composer and this makes it easy to find them in one place.

Could be related to #515 and #507.

**Comment by gnumdk** [comment]
Send me a ogg file by email because I don't see... Lollypop only use composer when album artist is empty.

**Comment by gnumdk** [comment]
Is this a recent issue?

**Comment by gnumdk** [comment]
#717

**Comment by d9h02f** [comment]
It worked fine before, but I just noticed it could be an issue with the tags. Easytag says there is no albumartist on the MP3 files although everything else reads the album artist tag just fine and it worked fine on Lollypop before. I don't know how to check which version of ID3v2 the tags are written in, but adding the albumartist tag again in Easytag fixes it.

That said, with the fixed albumartist they don't show up under the composer (I don't know if they did that before), but I think it would be good to have it show up there too.

**Comment by gnumdk** [comment]
Ok, so fixed in git ;)

**Comment by gnumdk** [comment]
Will release soon a bugfix release

**Comment by d9h02f** [comment]
Ah, just saw your comment, I'll test the next release asap.

**Comment by d9h02f** [comment]
Ok, it works again.
