### ISSUE TITLE
"Clear artwork" deletes files permanently instead of moving to trash

### ISSUE THREAD

**Issue by buha** [gnumdk/lollypop#730]
I just managed to lose the artwork from a very rare CD because of this software. 

There is this big brush symbol button next to artwork that I wanted to test, and apparently it deletes image files.

Please, fix this destructive behavior.

**Comment by gnumdk** [comment]
There is a confirmation button telling you it is going to clear artwork...

**Comment by buha** [comment]
Perfect, thanks!
As for the files, I use `ext4`(journaling) and managed to recover using `extundelete`.
