### ISSUE TITLE
Show and hide the albuminfo with transition by GtkStack

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#74]
I tried do it by myself, but it dosn't works for me :-/
Probably I put only the AlbumDetailedWidget in stack instead
of lollypop+view_widgets+AlbumDetailedWidget (what it is?!).

**Comment by gnumdk** [comment]
Show me a diff, i don't understand what you are trying to do...

**Comment by yoseforb** [comment]
OK, I understand the problem. I think I wants to put the stack into a revealer, so will be
animation when show/hide the album detailed and not just when you switch from one
album to another.

**Comment by yoseforb** [comment]
OK, I have a works patch :-)

**Comment by yoseforb** [comment]
How can I merge your commits to my fork?

**Comment by gnumdk** [comment]
https://bugs.launchpad.net/noise/+bug/1334498
