### ISSUE TITLE
Albums incorrectly marked as compilations

### ISSUE THREAD

**Issue by mckbsky** [gnumdk/lollypop#740]
-Lollypop version: 0.9.204
-Gtk Version: 3.20
-Linux distribution: Manjaro

If you have two albums in your library with the same name but with different artist/genre tag, both of them are marked as compilations. This was working as intended with older version of lollypop but i had reset my library which probably triggered this bug.

**Comment by gnumdk** [comment]
Send me album by email/google drive/...

**Comment by mckbsky** [comment]
https://drive.google.com/file/d/0Bz2G9DSqe6skS2NBZkI3TGVFd00/view

**Comment by gnumdk** [comment]
You need to set an album artist, not a bug.
