### ISSUE TITLE
Enable/disable "smart" artist sorting in preferences

### ISSUE THREAD

**Issue by nanawel** [gnumdk/lollypop#742]
Lollypop sorts artists by their name and attempts to determine if it contains lastname and firstname. In this case, lastname is used in the sort order.

But it frequently fails unfortunately and makes the list quite difficult to browse, so it could be a huge help to be able to disable this feature in the preference dialog.

**Comment by gnumdk** [comment]
Lollypop doesn't sort by lastname... Check your tags with kid3, you have a sort tag.

**Comment by nanawel** [comment]
You're perfectly right! I did not know about this tag, sorry.
But in that case, would it be possible to choose the "artist" tag to sort by?

**Comment by gnumdk** [comment]
Just set what you want in sort tag

**Comment by nanawel** [comment]
Err... that's not that simple. My music is automatically tagged with Picard/MusicBrainz, and I don't want to edit thousands of files manuallly to change the sort tag.
It was just a suggestion that could have make me love your app even more, but it's already very cool don't worry :)

**Comment by d9h02f** [comment]
Just select all your music files and remove the artistsort tags in one go. You can probably set Picard to not write sort tags at all, too.

**Comment by nanawel** [comment]
> Just select all your music files and remove the artistsort tags in one go. You can probably set Picard to not write sort tags at all, too.

Thanks I'll try that.
