### ISSUE TITLE
Enhancement; switching between genre show or not

### ISSUE THREAD

**Issue by kronstadt21** [gnumdk/lollypop#743]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate

-Lollypop version:
-Gtk Version:
-Linux distribution:

-Describe your bug here:

First of all I have to credit you for creating the best musicplayer for linux since the sadly missed beatbox. One thing that bugs me is the cumbersome way that toggles the genre view. I think that option should be readily availible in the main ui. maybe as an option in the upper left sidepanel. If you think that to be an bad design choice a keyboard shortcut ctrl+g could do the trick.

Best regards,
Göran

**Comment by blackjackshellac** [comment]
My $0.02: I would love to see the artist/genre list scroll independently of the main menu (Popular albums, Recently added ..., ...).  A single toggle in that fixed menu to switch the list between album and genre list would be great.

**Comment by gnumdk** [comment]
@blackjackshellac IMO, this will make the scroll view too small...

**Comment by gnumdk** [comment]
Maybe an overlay to scroll fast to top like we often see on the web?

**Comment by blackjackshellac** [comment]
Yes, indeed the reason I suggested it was that I find it difficult to scroll back to the top of that view.

**Comment by kronstadt21** [comment]
Come to think of it, the partymode works as genre view, if only it didn't switch to the dark theme...

**Comment by gnumdk** [comment]
@blackjackshellac Done
