### ISSUE TITLE
"Stop after this album" doesn't work anymore

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#744]
"Stop after this track" still works.

**Comment by gnumdk** [comment]
Here it works.

**Comment by d9h02f** [comment]
I can consistently reproduce inside a playlist, when I click to start playing a song then select "Stop after this album", Lollypop only stops playing at the end of the playlist.

Logs don't seem to show anything, on "Breathe" I selected "Stop after this album", but after "Ethyr" it didn't stop and it started playing the next album:
```
Toolbar::_on_current_changed
BinPlayer::_load_track(): file:///run/media/d9h02f/Files/Music/H%C3%86LOS/Earth%20Not%20Above/03%20-%20Breathe.ogg
Player::_on_stream_start(): file:///run/media/d9h02f/Files/Music/H%C3%86LOS/Earth%20Not%20Above/03%20-%20Breathe.ogg
Toolbar::_on_current_changed
Player::__on_stream_about_to_finish(): <__gi__.GstPlayBin object at 0x7fad42004dc8 (GstPlayBin at 0x557aeef49810)>
BinPlayer::_load_track(): file:///run/media/d9h02f/Files/Music/H%C3%86LOS/Earth%20Not%20Above/04%20-%20Ethyr.ogg
Player::_on_stream_start(): file:///run/media/d9h02f/Files/Music/H%C3%86LOS/Earth%20Not%20Above/04%20-%20Ethyr.ogg
Toolbar::_on_current_changed
Player::__on_stream_about_to_finish(): <__gi__.GstPlayBin object at 0x7fad42004dc8 (GstPlayBin at 0x557aeef49810)>
BinPlayer::_load_track(): file:///run/media/d9h02f/Files/Music/H%C3%86LOS/Full%20Circle/01%20-%20Intro_Spectrum.ogg
Player::_on_stream_start(): file:///run/media/d9h02f/Files/Music/H%C3%86LOS/Full%20Circle/01%20-%20Intro_Spectrum.ogg
Toolbar::_on_current_changed
Player::__on_stream_about_to_finish(): <__gi__.GstPlayBin object at 0x7fad42004dc8 (GstPlayBin at 0x557aeef49810)>
BinPlayer::_load_track(): file:///run/media/d9h02f/Files/Music/H%C3%86LOS/Full%20Circle/02%20-%20Pray.ogg
Player::_on_stream_start(): file:///run/media/d9h02f/Files/Music/H%C3%86LOS/Full%20Circle/02%20-%20Pray.ogg
Toolbar::_on_current_changed
```

**Comment by gnumdk** [comment]
Stop after the album works when playing albums, not playlist... Just use "Do not repeat"

**Comment by d9h02f** [comment]
Oh, I see, but "Do not repeat" only stops at the end of a playlist. I think it should be possible to create a playlist of albums, and stop after the currently playing album in the playlist has finished.

**Comment by gnumdk** [comment]
Sorry, IMO this doesn't make sense. But I need to remove option from menu when  in playlist playback.

**Comment by gnumdk** [comment]
BTW I hope you are not using playlists to play albums :p

**Comment by d9h02f** [comment]
Only for things I haven't listened to yet so it's easy to keep track of. That's why I'd use the option to stop in the middle of the playlist, because I don't want to listen to everything in one go, but I also want to make sure I listened to the whole album before stopping.
