### ISSUE TITLE
Crash when right-clicking the currently playing song on low resolutions

### ISSUE THREAD

**Issue by Gert-dev** [gnumdk/lollypop#747]
Hello

Since the version that included YouTube support, I'm experiencing a crash when right-clicking the currently playing song in the bottom bar (which is only visible on low resolutions or when making the window smaller).

The backtrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/miniplayer.py", line 69, in _on_button_press
    PopToolbarMenu(Lp().player.current_track.id))
  File "/usr/lib/python3.5/site-packages/lollypop/pop_menu.py", line 523, in __init__
    if track.year != track.album.year:
AttributeError: 'int' object has no attribute 'year'
```

Thanks in advance

**Comment by gnumdk** [comment]
You are not using last version...

**Comment by Gert-dev** [comment]
Is 0.9.204 not the latest version? ;-)

**Comment by gnumdk** [comment]
#738
