### ISSUE TITLE
Translation contexts for string

### ISSUE THREAD

**Issue by prescott66** [gnumdk/lollypop#748]
Please add translation contexts for this string:

#: ../src/pop_radio.py:83 ../src/pop_tunein.py:222 ../src/view_artist.py:315
#: ../data/ArtistView.ui.h:3
msgid "Add"

...for proper translation :wink: 

dev wiki: https://wiki.gnome.org/TranslationProject/DevGuidelines/Translation%20contexts

**Comment by gnumdk** [comment]
Add is "add", it's used in many lollypop parts... So no context.

**Comment by prescott66** [comment]
Add is "add" only in english...
Example translations ofnword "add" in slovak:

Tooltip: "Pridá"
Button label: "Pridať"
Dialog/window title: "Pridanie"

Not all languages are "primitive" like english ;-)

**Comment by gnumdk** [comment]
Same in french so I don't understand what to add

**Comment by gnumdk** [comment]
From Google translate, "Pridá" is not "Add" but "Added"
Seems to be "Pridat'" => infinitif

**Comment by prescott66** [comment]
you cant trust google translate....added=pridaný/-á/-ý/-é
ok.forget about it.

**Comment by gnumdk** [comment]
Yes, I understand that added =pridaný/-á/-ý/-é.
It's the same in French: ajouté, ajoutée, ajoutés, ajoutées

But here, it's add in the sense: "To add"

**Comment by prescott66** [comment]
yes, you should understand me, because french is gramatically similar to slovak...
i just want to say, that it is different to translate string for gtk label, dialog title or tooltip... so i recommend to disambiguate this string.
