### ISSUE TITLE
Support id3 tag for lyrics

### ISSUE THREAD

**Issue by Jehan** [gnumdk/lollypop#749]
-Lollypop version: 0.9.204
-Gtk Version: 2.24.31-1.fc24
-Linux distribution: Fedora 24

I would like to propose the possibility to write lyrics oneself, rather than always having a web search to search and select lyrics. Well the lyrics search feature should stay there too, but then you will have the choice to search or use your own data.

As a second feature proposal, I'd like to be able to write random notes. Well I wrote a single feature request because I would not mind if there is only a single "notes" feature in which you can also write lyrics. Better would still to have 2 separate features for semantic reasons: one for lyrics, and one for generic note-taking.

**Comment by gnumdk** [comment]
Will refused support for note taking, not lollypop purpose.

Will add support for id3 tag for lyrics.

**Comment by gnumdk** [comment]
Help wanted. Can't get lyrics tag from gstreamer tag discover :-( Is it in id3v2-frame?

>>> tags.to_string()
'taglist, album=(string)"Dimanche\\ \\303\\240\\ Bamako", artist=(string)"Amadou\\ \\&\\ Mariam", title=(string)"m\\\'bif\\303\\251", track-number=(uint)1, genre=(string)Afrobeat, replaygain-album-peak=(double)0.57194699999999998, replaygain-track-gain=(double)-1.119140625, replaygain-track-peak=(double)0.465301513671875, replaygain-album-gain=(double)-0.908203125, private-id3v2-frame=(sample){ 54585858000000270000007265706c61796761696e5f7265666572656e63655f6c6f75646e6573730038392e3020644200:None:R3N0U2VnbWVudCwgZmxhZ3M9KEdzdFNlZ21lbnRGbGFncylHU1RfU0VHTUVOVF9GTEFHX05PTkUsIHJhdGU9KGRvdWJsZSkxLCBhcHBsaWVkLXJhdGU9KGRvdWJsZSkxLCBmb3JtYXQ9KEdzdEZvcm1hdClHU1RfRk9STUFUX1RJTUUsIGJhc2U9KGd1aW50NjQpMCwgb2Zmc2V0PShndWludDY0KTAsIHN0YXJ0PShndWludDY0KTAsIHN0b3A9KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTUsIHRpbWU9KGd1aW50NjQpMCwgcG9zaXRpb249KGd1aW50NjQpMCwgZHVyYXRpb249KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTU7AA__:None, 54585858000000180000004d50334741494e5f4d494e4d4158003134322c31393200:None:R3N0U2VnbWVudCwgZmxhZ3M9KEdzdFNlZ21lbnRGbGFncylHU1RfU0VHTUVOVF9GTEFHX05PTkUsIHJhdGU9KGRvdWJsZSkxLCBhcHBsaWVkLXJhdGU9KGRvdWJsZSkxLCBmb3JtYXQ9KEdzdEZvcm1hdClHU1RfRk9STUFUX1RJTUUsIGJhc2U9KGd1aW50NjQpMCwgb2Zmc2V0PShndWludDY0KTAsIHN0YXJ0PShndWludDY0KTAsIHN0b3A9KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTUsIHRpbWU9KGd1aW50NjQpMCwgcG9zaXRpb249KGd1aW50NjQpMCwgZHVyYXRpb249KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTU7AA__:None, 55534c540000000d000000656e67006c696e7578667200:None:R3N0U2VnbWVudCwgZmxhZ3M9KEdzdFNlZ21lbnRGbGFncylHU1RfU0VHTUVOVF9GTEFHX05PTkUsIHJhdGU9KGRvdWJsZSkxLCBhcHBsaWVkLXJhdGU9KGRvdWJsZSkxLCBmb3JtYXQ9KEdzdEZvcm1hdClHU1RfRk9STUFUX1RJTUUsIGJhc2U9KGd1aW50NjQpMCwgb2Zmc2V0PShndWludDY0KTAsIHN0YXJ0PShndWludDY0KTAsIHN0b3A9KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTUsIHRpbWU9KGd1aW50NjQpMCwgcG9zaXRpb249KGd1aW50NjQpMCwgZHVyYXRpb249KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTU7AA__:None, 545858580000000a0000030057696e646f777300:None:R3N0U2VnbWVudCwgZmxhZ3M9KEdzdFNlZ21lbnRGbGFncylHU1RfU0VHTUVOVF9GTEFHX05PTkUsIHJhdGU9KGRvdWJsZSkxLCBhcHBsaWVkLXJhdGU9KGRvdWJsZSkxLCBmb3JtYXQ9KEdzdEZvcm1hdClHU1RfRk9STUFUX1RJTUUsIGJhc2U9KGd1aW50NjQpMCwgb2Zmc2V0PShndWludDY0KTAsIHN0YXJ0PShndWludDY0KTAsIHN0b3A9KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTUsIHRpbWU9KGd1aW50NjQpMCwgcG9zaXRpb249KGd1aW50NjQpMCwgZHVyYXRpb249KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTU7AA__:None, 545858580000001e0000004d50334741494e5f414c42554d5f4d494e4d4158003133382c32303100:None:R3N0U2VnbWVudCwgZmxhZ3M9KEdzdFNlZ21lbnRGbGFncylHU1RfU0VHTUVOVF9GTEFHX05PTkUsIHJhdGU9KGRvdWJsZSkxLCBhcHBsaWVkLXJhdGU9KGRvdWJsZSkxLCBmb3JtYXQ9KEdzdEZvcm1hdClHU1RfRk9STUFUX1RJTUUsIGJhc2U9KGd1aW50NjQpMCwgb2Zmc2V0PShndWludDY0KTAsIHN0YXJ0PShndWludDY0KTAsIHN0b3A9KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTUsIHRpbWU9KGd1aW50NjQpMCwgcG9zaXRpb249KGd1aW50NjQpMCwgZHVyYXRpb249KGd1aW50NjQpMTg0NDY3NDQwNzM3MDk1NTE2MTU7AA__:None }, duration=(guint64)133224000000, container-format=(string)"ID3\\ tag", has-crc=(boolean)false, channel-mode=(string)joint-stereo, audio-codec=(string)"MPEG-1\\ Layer\\ 3\\ \\(MP3\\)", nominal-bitrate=(uint)128000, bitrate=(uint)128012;'

**Comment by Jehan** [comment]
Hi,

> Will refused support for note taking, not lollypop purpose.

I understand you want to keep it simple and don't want to add non-standardized features. What about the "Comment" ID3 tag? http://help.mp3tag.de/main_tags.html
I guess the equivalent in WMA would be "Description" (same page), as well as on Ogg Vorbis: https://www.xiph.org/vorbis/doc/v-comment.html

**Comment by gnumdk** [comment]
>What about the "Comment" ID3 tag?
Not lollypop purpose to show such information.

**Comment by Jehan** [comment]
Hmmm… ok.

**Comment by somas95** [comment]
It isn't working for me
If I ffprobe [the mp3 file] I can view the lyrics in the lyric's tag, but Lollypop only shows the web lyrics search

System
Arch, 64 bits, GNOME 3.22
Lollypop:0.9.217

**Comment by gnumdk** [comment]
@somas95  Send me file by email

**Comment by gnumdk** [comment]
@somas95 Seems to be an issue in Gstreamer not reading tag frame.

Resetting tags with puddle tag and settings again and it  works.

Please report bug to gstreamer, should be cool if fixed :)
