### ISSUE TITLE
Add custom youtube URL

### ISSUE THREAD

**Issue by lightningblaze** [gnumdk/lollypop#752]
There should be an option to search by YouTube URL or add a custom YouTube URL to your music library, as not every song I search with web search on appears.|
I feel like if you could do that, then give an option to manually enter the URL, Artist, Album, Album Art, etc.
If this is not possible currently I understand, I just feel like it might help for some of the things lollypop can't find details on and as such doesn't seem to include in the default web search.

**Comment by gnumdk** [comment]
The default web search is spotify search. Not sure such feature will fit in Lollypop UI.

BTW, it's easy to make a small bash script doing the same thing.

**Comment by gnumdk** [comment]
usage: lollypop-cli youtube artist album track uri
Allow user to add youtube tracks not available in search

usage: lollypop-cli export-playlists
Export playlists to m3u format in current directory
