### ISSUE TITLE
Mini mode locked when resuming Lollypop from sound menu (Ubuntu)

### ISSUE THREAD

**Issue by xou816** [gnumdk/lollypop#753]
Lollypop version: 0.9.203, 0.9.205 (probably 0.9.204 as well)
Gtk Version: 3.18
Linux distribution: Ubuntu 16.04

If in mini mode, closing Lollypop to "tray" and opening it back again from the sound menu locks it into mini mode, ie resizing the window/using the keyboard shortcut won't switch back Lollypop to normal mode.
No errors in terminal output.

**Comment by xou816** [comment]
Does not affect Lollypop 0.9.203 in Gnome Shell (Gtk: 3.20, Distribution: Arch). Gnome Shell instead spawns what seems to be a new window for Lollypop when clicking the music notification from the notifications menu, thus Lollypop appears in normal mode.

**Comment by gnumdk** [comment]
Buggy compiz, will give a look.

**Comment by xou816** [comment]
Cool, thanks for your work! :) It's not a crippling bug anyway.
