### ISSUE TITLE
Online radio crash

### ISSUE THREAD

**Issue by Ste74** [gnumdk/lollypop#754]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate

-Lollypop version: 0.9.203
-Gtk Version:3.20
-Linux distribution:Manjaro 

-Describe your bug here:

Hi , when open online radio lollypop crash : 

> [stefano@ste74 ~]$ lollypop -d
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
TuneinPopover::_download_images: g-io-error-quark: Not Found (1)
TuneinPopover::_download_images: g-io-error-quark: Not Found (1)
Player::_on_stream_start(): http://icecast.unitedradio.it/Radio105.mp3
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 385, in __on_current_changed
    self.__update_metadata()
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 343, in __update_metadata
    Lp().player.current_track.duration * 1000000)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
[stefano@ste74 ~]$

**Comment by gnumdk** [comment]
Already fixed in last version.

**Comment by Ste74** [comment]
Ok thank you :smile:
