### ISSUE TITLE
Web Song Issues

### ISSUE THREAD

**Issue by lightningblaze** [gnumdk/lollypop#755]
-Lollypop version: Both 0.9.203 and .205
-Gtk Version: I have both 2 and 3
-Linux distribution: Arch Linux

-Describe your bug here:
I can search songs on the web with web search, and click add... But for some reason, they wont appear in my library.
What happened:
Basically, It worked perfectly on both my laptop and desktop at first, both could play local and web songs fine. Then, my desktop stopped being able to play any web songs, so i restarted, and after that I couldn't even add new ones. I could search for web songs and press add, but it wouldn't appear. My local songs work perfectly fine and my laptop on the same network also works. I also tried adding my own google API, it clearly showed activity going through it for searches on googles API dashboard, but it still had the same issues.

I should also mention that I have tried Uninstalling, Deleting .local/share/lollypop and /usr/share/glib-2.0/schemas/org.gnome.Lollypop.gschema.xml, then rebooting, and the issue still happened

**Comment by gnumdk** [comment]
Any output when running lollypop -d ?

**Comment by gnumdk** [comment]
@Gabreta 
youtube-dl -g -f bestaudio  https://www.youtube.com/watch?v=6lq8HexYL1o

What is the output?

**Comment by Gabreta** [comment]
thanks for answering, the output is as follows:
https://r16---sn-ja5gvjv-cvbk.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gir=yes&gcr=co&ms=au&ei=1CfoV-GCNsO_-gW5uqzQBg&mv=m&pl=22&mt=1474831754&clen=4389069&key=yt6&mn=sn-ja5gvjv-cvbk&mm=31&id=o-AI3WTeiJrdr5qCEV4_ptSS5S1yKSuD52odGu2mZIbks5&dur=273.001&source=youtube&keepalive=yes&ip=186.82.62.162&requiressl=yes&itag=251&lmt=1449781092901285&ipbits=0&initcwndbps=693750&expire=1474853940&upn=Nv-2kmA9Sr0&mime=audio%2Fwebm&signature=45BC9E51786DFE683E8370345D82FCDC4DACE564.C491AAFC81121F3D8F9835AC81F148AE3DD793FC&ratebypass=yes

**Comment by gnumdk** [comment]
Strange, something is broken with youtube-dl on your computer :-(

**Comment by lightningblaze** [comment]
I press the add on the search with -d and it gives:
ItunesCharts::__get_album(): 1150155422
ItunesCharts::__get_album() g-io-error-quark: HTTP Error: Bad Request (0)

Running the youtube-dl command given just shows absolutely nothing

**Comment by gnumdk** [comment]
Yes, broken IPV6 setup, no reason to force ipv4...

**Comment by gnumdk** [comment]
@Gabreta and you?

**Comment by Gabreta** [comment]
No,I haven't been able to solve :/

**Comment by gnumdk** [comment]
Does youtube-dl really download video without -g?

**Comment by Gabreta** [comment]
yes,  it does both the video and audio ...
...video:youtube-dl <url>
youtube] 7lC1lRz5Z_s: Downloading webpage
[youtube] 7lC1lRz5Z_s: Downloading video info webpage
[youtube] 7lC1lRz5Z_s: Extracting video information
[youtube] 7lC1lRz5Z_s: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Wolfgang Amadeus Mozart - Symphony No. 25 in G minor-7lC1lRz5Z_s.f135.mp4
[download] 100% of 7.60MiB in 00:13
[download] Destination: Wolfgang Amadeus Mozart - Symphony No. 25 in G minor-7lC1lRz5Z_s.f251.webm
[download] 100% of 7.60MiB in 00:14
[ffmpeg] Merging formats into "Wolfgang Amadeus Mozart - Symphony No. 25 in G minor-7lC1lRz5Z_s.mkv"
Deleting original file Wolfgang Amadeus Mozart - Symphony No. 25 in G minor-7lC1lRz5Z_s.f135.mp4 (pass -k to keep)
Deleting original file Wolfgang Amadeus Mozart - Symphony No. 25 in G minor-7lC1lRz5Z_s.f251.webm (pass -k to keep)
..audio youtube-dl -x <url>
[youtube] 7lC1lRz5Z_s: Downloading webpage
[youtube] 7lC1lRz5Z_s: Downloading video info webpage
[youtube] 7lC1lRz5Z_s: Extracting video information
[youtube] 7lC1lRz5Z_s: Downloading MPD manifest
[download] Destination: Wolfgang Amadeus Mozart - Symphony No. 25 in G minor-7lC1lRz5Z_s.webm
[download] 100% of 7.60MiB in 00:13
[ffmpeg] Destination: Wolfgang Amadeus Mozart - Symphony No. 25 in G minor-7lC1lRz5Z_s.opus
Deleting original file Wolfgang Amadeus Mozart - Symphony No. 25 in G minor-7lC1lRz5Z_s.webm (pass -k to keep)

**Comment by gnumdk** [comment]
And with youtube-dl -g, if you open the url in firefox, does it work?

**Comment by Gabreta** [comment]
Yes, I can hear the song on the url firefox youtube-dl -g gives me

**Comment by gnumdk** [comment]
@Gabreta Sure you are missing gstreamer plugins...
