### ISSUE TITLE
Web Song Issues

### ISSUE THREAD

**Issue by Gabreta** [gnumdk/lollypop#757]
-Lollypop version: 0.9.205
-Gtk Version: 3.20.2
-Linux distribution: Arch Linux

-Describe your bug here: (sorry, my native language is Spanish)
This does not play any song on web
by clicking on a song console appears in the following:
BinPlayer::_load_track(): https://www.youtube.com/watch?v=6lq8HexYL1o
after a while, which is kept charging, appears:
youtube-dl failed to get video uri
----
Appears always to load, then display an error uri, I've revizado dependencies and not missing me any
within advisories when making lollipop --debug:
ItunesCharts::__get_album(): 396449861
Exception in thread Thread-92:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/lollypop/art_album.py", line 359, in __save_artwork_tags
    path = GLib.filename_from_uri(uri)[0]
GLib.GError: g_convert_error: El URI «https://www.youtube.com/watch?v=ldyleHRj_PE» no es una URI absoluta utilizando el esquema «file» (4)

**Comment by gnumdk** [comment]
#755

**Comment by gnumdk** [comment]
What is really strange is that you are using ArchLinux like me... :-/

**Comment by gnumdk** [comment]
Can you save this as youtube.py and run python youtube.py? Then paste output here

`from gi.repository import GLib, Gio
argv = ["youtube-dl", "-g", "-f", "bestaudio", "https://www.youtube.com/watch?v=ldyleHRj_PE", None]

def set_gv_uri(io, condition):
    print(io, io.readline())

(s, pid, i, o, err) = GLib.spawn_async_with_pipes(
                           None, argv, None,
                           GLib.SpawnFlags.SEARCH_PATH |
                           GLib.SpawnFlags.DO_NOT_REAP_CHILD, None)
io = GLib.IOChannel(o)
io.add_watch(GLib.IO_IN | GLib.IO_HUP,
             set_gv_uri,
             priority=GLib.PRIORITY_HIGH)
l = GLib.MainLoop()
l.run()`

**Comment by Gabreta** [comment]
thanks for helping me, and keep me patience :D
It takes a bit but ...
<GLib.IOChannel object at 0x7fc881886a08 (GIOChannel at 0x1a3b0f0)> https://r10---sn-ja5gvjv-cvbk.googlevideo.com/videoplayback?id=95dca5787463fcf1&itag=251&source=youtube&requiressl=yes&pl=22&mn=sn-ja5gvjv-cvbk&mm=31&ms=au&mv=m&initcwndbps=773750&ratebypass=yes&mime=audio/webm&gir=yes&clen=1385520&lmt=1410680186149231&dur=78.021&mt=1475186946&key=dg_yt0&signature=0D5D4F3740CB8BAC2F6EBDD3AFE745A4099D3EB5.06B145F396B25C00D19B7E347E224817E5829DF4&upn=rKwc3iCc108&ip=186.82.62.162&ipbits=0&expire=1475208832&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mn,mm,ms,mv,initcwndbps,ratebypass,mime,gir,clen,lmt,dur

....after that wait like 15 minutes and never finish

**Comment by gnumdk** [comment]
Normal.
What is strange is that this code is working and lollypop is not :(

**Comment by gnumdk** [comment]
Any proxy?

**Comment by Gabreta** [comment]
no, I haven't restriction on the network(firewall and others...)

**Comment by gnumdk** [comment]
Yes, warning from the first comment were fixed in last version ;)

**Comment by gnumdk** [comment]
![song](https://cloud.githubusercontent.com/assets/3918824/19016194/8b2a0b5c-8813-11e6-8d82-e5f129487582.png)

**Comment by gnumdk** [comment]
Can you test with lollypop-git?

**Comment by Gabreta** [comment]
I just upgraded to 3.22 gtk (testing version)
and I have given accounts of some things, it seems that this warning appears on some occasions:
(lollypop:6176): Gtk-WARNING **: Allocating size to lollypop+selectionlist+SelectionList 0x7f04ec00ca50 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

And it seems that lollypop has many problems with python-cairo-git (At the time I could not even open the program), after testing satisfactorily with python-cairo

the test result remains the same:
BinPlayer::_load_track(): https://www.youtube.com/watch?v=7nDBhfp9qak
youtube-dl failed to get video uri

unfortunately still not able to find the error, if it's just me or anything else missing

**Comment by Gabreta** [comment]
![capt1](https://cloud.githubusercontent.com/assets/8386330/19018519/faa8c96c-8829-11e6-8f35-271a256fc780.png)

**Comment by gnumdk** [comment]
Did you test with lollypop-git?

Seems you have some network error: [Errno 110] => TIMEOUT
Any idea?

**Comment by gnumdk** [comment]
Can you contact me by email?

**Comment by gnumdk** [comment]
Please update lollypop-git, you will get error message from youtube-dl...

**Comment by Gabreta** [comment]
Yes, : ') 
BinPlayer::__youtube_dl_lookup: ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by URLError(TimeoutError(110, 'Connection timed out'),))

and, the error of [Errno]
also appears that when using last.fm
I had not noticed, but always appear when you use last.fm

**Comment by gnumdk** [comment]
So you have an issue in your computer... But not in lollypop...

URLError(TimeoutError(110, 'Connection timed out'),)) is youtube-dl output...

**Comment by gnumdk** [comment]
Look at your GNOME proxy settings... Lollypop force youtube-dl proxy settings...
