### ISSUE TITLE
Added the Unicode.ui file to the POTFILES.in

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#76]
So I will be able to translate the strings in this file.

Also, please put the right ends line characters, it look like all the file in one line.

**Comment by gnumdk** [comment]
Will be available in master soon...

Be aware that for french, i need to only put ASCII chars in translation as it seem's that gettext fails to display utf8 strings on a non utf8 system...

So, not sure it will works for you...

**Comment by yoseforb** [comment]
Why I not see the 2 new strings in the transifex page? It take a time to be updated?
