### ISSUE TITLE
Random Track not working with Favourite Songs playlists

### ISSUE THREAD

**Issue by C3realGuy** [gnumdk/lollypop#763]
-Lollypop version: 0.9.206
-Gtk Version: gtk3 3.20.9-1
-Linux distribution: Arch

-Describe your bug here:

Playing random songs by album/track does not work for favourite songs playlists if you change the random mode while you already started playing this "playlist". So if you change the random mode and "start" the playlist new by clicking on a track it works. But not if you change it while listening to that playlist. Hope this is clear enough.

Besides this this player is exactly what I looked for since years. Thanks for this awesome and beautiful player. Just switched to gnome3 and it rocks with lollypop.

**Comment by C3realGuy** [comment]
@gnumdk Thanks, fixed for random song but still the same for random album. Do you want a new issue for this?

**Comment by gnumdk** [comment]
@C3realGuy It works for random albums... I think you don't get this:
- When you click on the play icon, lollypop only add one album so shuffle is on album
- When you click on the play all icon, lollypop shuffle on all albums
