### ISSUE TITLE
Albums with same name are hidden

### ISSUE THREAD

**Issue by aidanhodge** [gnumdk/lollypop#764]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate

-Lollypop version:
-Gtk Version:
-Linux distribution:

-Describe your bug here:
I've got two albums called greatest hits, one by Social Distortion, and one by the Eagles, and neither of them show up in the list of albums. They can't be searched either. In the music tab of preferences, it appears as if Lollipop has correctly detected that I have 1845 songs, but the number of artists and number of albums are off.

**Comment by gnumdk** [comment]
Send me .local/share/lollypop.db by email

**Comment by aidanhodge** [comment]
Here it is:

**Comment by gnumdk** [comment]
Nothing here ;) By email to my email adresse (in my profil)

**Comment by aidanhodge** [comment]
I fixed it by copying all of the names in artist over to album artist in the tags. They still didn't show up in compilations before though, I don't know if you'd consider that an issue.

**Comment by gnumdk** [comment]
Do you have always have some broken files?

**Comment by aidanhodge** [comment]
Everything seems to work alright now that I edited the tags.

**Comment by gnumdk** [comment]
Can't reproduce, here, it go in Compilations...
