### ISSUE TITLE
Inline search conflicts with shortcuts

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#765]
When I want to search inline for "Nick Cave" and start typing "nick cave", Lollypop interprets the "n" as the shortcut to start the next track, and looks for "ick cave". Same with other shortcuts like "l" or "v".

**Comment by gnumdk** [comment]
GNOME 3.22? I know :-(

**Comment by gnumdk** [comment]
For me it's fixed by:
https://github.com/gnumdk/lollypop/commit/fadf83cc51fc9492a46182574241ff1df9feee94

Are you using 0.9.206?

**Comment by d9h02f** [comment]
Oh, I missed that. It's fixed in 0.9.206.
