### ISSUE TITLE
Playlist Option's sub-menu - no way to recover it if dragged under left panel

### ISSUE THREAD

**Issue by asqwerth** [gnumdk/lollypop#766]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate

-Lollypop version: 0.9.206
-Gtk Version: 3.20
-Linux distribution: Apricity (Arch)

-Describe your bug here: The submenu (the one with "play random tracks") for the Playlists Option usually slides out when I click on it.  I dragged/slid the submenu back manually with my mouse so it was completely covered by the left panel and found I could not recover it.  Now when I click on Playlists, I just get a blank space on the right where I can create a new playlist.  If I try to make a new playlist, a top bar appears in the blank space with the words "loved tracks" but clicking on the "Back" arrow does not bring back the submenu.

 If I drag on the left panel, I just make it bigger.  I can't drag the submenu out again.  I have tried Preferences, ESC and right-clicking on every part of the Lollypop interface but can't get it back.

**Comment by gnumdk** [comment]
I'm able to get it but it's not easy, really not

**Comment by gnumdk** [comment]
dconf-editor and edit  paned-list-width
