### ISSUE TITLE
No way to view album queue anymore

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#767]
It seems there's no way to view what's in the queue anymore. I mean the queue that's created when you're playing an album and you use the '+' icon to add another album. Using "Insert as next" works and shows the next tracks in 'Playing playlists', but with '+' nothing shows up there.

**Comment by gnumdk** [comment]
Here it works as expected...

**Comment by d9h02f** [comment]
Strange, I can consistently reproduce by clicking Play on an album cover and clicking + on a different album cover. The albums will play after each other as they should, but I can't see which albums are playing anywhere. If I click + on a track, it gets added as the next track and shows up in the queue as it should.

I noticed when I click on Playing playlists after clicking + on an album cover, it shows 'Search' with the button to split/unsplit the view, but nothing else is there. If I click on Playing playlists after clicking on + on a specific track, it shows 'Queue' with the button to Clear queue, and the track I added is there.

**Comment by d9h02f** [comment]
Playing from search results does work as expected, and shows the playing albums under 'Search' after clicking 'Playing playlists'.

**Comment by gnumdk** [comment]
> but I can't see which albums are playing anywhere. 

What do you see in the popover?

**Comment by gnumdk** [comment]
https://youtu.be/GVTus5zXjgA

**Comment by d9h02f** [comment]
Nothing:
![](https://a.pomf.cat/ujxasq.png)

If I start playing something from the search results, it works, but when I click + to add a new album, it immediately starts playing that album and the popover still shows the search results.

**Comment by gnumdk** [comment]
Here, the popover show playlists...

**Comment by gnumdk** [comment]
Ok, got it... Temps fix, disable "Remember state" for one shot. Lollypop is blocked on playlists...

**Comment by gnumdk** [comment]
Seems it never worked ;)

**Comment by jnj** [comment]
As an aside, I really don't grasp the intention or usage of these multiple ways of queuing tracks. Is there some reason for having a notion of a queued album versus just queuing up the tracks that it contains? Everything would be so much simpler if there were just a play queue that contains tracks. If you want to append an entire album to it, then Lollypop could just put that album's tracks into the queue. Maybe I am missing something.

**Comment by gnumdk** [comment]
Yes, you are missing that there is NO album queue...

There are album playlists or track playlists and queue to bypass this playlists.

**Comment by jnj** [comment]
Okay. How do I see those playlists? They are not in the playlists section. It seems like the button to view the queue seems to be modal, in that you'll see the playlists if no tracks are queued. Is that right?

**Comment by gnumdk** [comment]
If you play a track playlist (from playlist menu), you see  playlist view
If you play an album, you will see album view
If you add something to the queue, you will see queue view (while queue not empty)
