### ISSUE TITLE
Crash after "add in playlist" on search toolbar

### ISSUE THREAD

**Issue by russose** [gnumdk/lollypop#768]
Hi,

-Lollypop version: 0.9.206
-Gtk Version: 3
-Linux distribution: Archlinux

-Describe your bug here:
If I search a string, and push the icon "add top to the playlist", Lollypop crash with this message:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/pop_search.py", line 179, in _on_playlist_clicked
    not self.__is_track)
AttributeError: 'SearchRow' object has no attribute '_SearchRow__is_track'

However, great app! Congratulation.
Salvatore

**Comment by russose** [comment]
bah ça c'est du rapide!!! 7-4=3mins pour réagir, bravo!

**Comment by gnumdk** [comment]
J'étais en train de bosser sur Lollypop ;)
