### ISSUE TITLE
Lollypop don't like when I remove a music folder when a list is reading

### ISSUE THREAD

**Issue by JulienNicolas37** [gnumdk/lollypop#770]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate

-Lollypop version: 0.9.206
-Gtk Version: libgtk-3-0:amd64 or libgtk2.0-0:amd64
-Linux distribution: Gnome Ubuntu 16.04

-Describe your bug here:
I try "shuffle list" and start to heard the first track. Then I see that the album "Génération Club Dorothée" was in that list T_T
I decided to move this album from my music folder to a "blind test" folder but don't want to stop the music.
As soon as the software re-sync the music, it crashed. It smell like NPE ;)

Merci d'avance Cédric :)

Julien.

**Comment by JulienNicolas37** [comment]
I just see "If you really need a player designed around playlists, Lollypop is a bad choice ;)" but I think my issue is still important because of the crash generated :)

**Comment by gnumdk** [comment]
Please send crash information...

**Comment by gnumdk** [comment]
Not happening here...

**Comment by JulienNicolas37** [comment]
Sorry, I don't save the error report from Ubuntu and now impossible to reproduce as well... You can close this issue, I'll come back with a report if it's happen again.
Thanks again for your help.
Julien.

**Comment by gnumdk** [comment]
You can get crash by looking at journalctl, not sure if it works on Ubuntu...

**Comment by JulienNicolas37** [comment]
Unfortunately, journalctl on Ubuntu don't keep boot -1... I just set it to keep bigger log... I try and retry what I did but Lollylop don't crash and displayed an error message. I just have to switch to another list and come back to have a clean list (without the removed album).
