### ISSUE TITLE
Your Gstreamer installation is missing a plug-in

### ISSUE THREAD

**Issue by skullscream** [gnumdk/lollypop#771]
-Lollypop version: 0.9.203
-Gtk Version: (don't know how to see it on manjaro)
-Linux distribution: manjaro net install running gnome 3.20.4

-Describe your bug here:
shows "Your Gstreamer installation is missing a plug-in" every time I run the program and try to play a song. I installed "gstreamer-1.8.3-1" from arch's packages but still the same thing. When I run it via terminal it says this "gst-core-error-quark: Your GStreamer installation is missing a plug-in."

I see this has already been posted here https://github.com/gnumdk/lollypop/issues/359 but I don't see how it's solved.

**Comment by gnumdk** [comment]
gst-libav

**Comment by gnumdk** [comment]
Please ask on ArchLinux forum for this kind of questions...

**Comment by skullscream** [comment]
Sorry and thanks. :)
