### ISSUE TITLE
Ratings lost after moving music files

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#775]
After dividing my music into subcategories inside the music folder, all files reside one level further down in the file system tree.

• I lost all per-song ratings, even after setting the music directory to one subcategory (for every relative path to be the same as before) and having everything undone afterwards.
• Somehow album ratings are set, but I don't know why. Btw: Are these average ratings of all contained songs or are these set fixed?
• Aren't the ratings written into the ID3 tags?

**Comment by gnumdk** [comment]
ratting should have been restored... Here it works, I do this every day for testing...

**Comment by gnumdk** [comment]
Not saved in tags...

**Comment by gnumdk** [comment]
Ok, do not works in this case... As file rating is saved at end of scan...

**Comment by gnumdk** [comment]
Reset your database and lollypop will restore rate...

**Comment by fb87** [comment]
Can you save the ratings into the tags? When I downloaded my songs from Google Music, they contained ratings.

**Comment by gnumdk** [comment]
No, rating is dynamic in lollypop, don't want to modify user files every time a track is played...
On more, as rating is dynamic, rating is calculated based on other tracks...

**Comment by fb87** [comment]
A file should only be modified if i manually set a rating. Why is there a need for modifying it every time it is being played?

As I'm using my songs also in my car and on my phone, it would be nice if these players could also adopt the ratings i set in Lollypop. When you save the ratings only in your DB, this information is lost. :(

Problem with your implementation still is: When someone accidentally sets the music folder to a folder which contains no music, all ratings are lost. Same is true if I reinstall my system and restore my Lollypop data before filling my Music folder with music, or setting it appropriately. Or if I got my music on an external drive, I never can save ratings because they get trashed every time I unplug my drive.

**Comment by gnumdk** [comment]
>Problem with your implementation still is: When someone accidentally sets the music folder to a folder 
>which contains no music, all ratings are lost. 
No rating is saved in a backup db

> Or if I got my music on an external drive, I never can save ratings because they get trashed every time I 
>unplug my drive.
No rating is saved in a backup db

**Comment by gnumdk** [comment]
>Why is there a need for modifying it every time it is being played?

 Because every time you play a track, album/track rating is changed by lollypop

**Comment by fb87** [comment]
Ah – I didn't mean rating as number of how much a song got played, but in form of 1-5 stars!

**Comment by gnumdk** [comment]
Lollypop calculate rating (1-5 stars) using "how much a song got played"

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/600

**Comment by gnumdk** [comment]
Here, google music doesn't add rate to files...

**Comment by gnumdk** [comment]
Ok, done some testing, saving playback count to tags is not working as kid3-cli is doing bad things (play count is limited to 255 and should not. This is the only way to restore stat in lollypop...

I can add an option to lollypop-cli to sync stars with tags if you want...

**Comment by fb87** [comment]
I think saving playback-count doesn't make a lot of sense and it's not a problem to me, if these stats get lost. But it would be very nice, if the manual star-rating could be automatically written to the files!

**Comment by fb87** [comment]
Thanks a lot! In which version will this be included? Are already set ratings saved, when upgrading to this version, too, or does this just apply to new set ratings?
