### ISSUE TITLE
Crash after starting

### ISSUE THREAD

**Issue by captnc** [gnumdk/lollypop#779]
Hi,

-Lollypop version: 0.9.210
-Gtk Version: 3.20.9
-Linux distribution: Ubuntu 16.10 (new install)

-Describe your bug here: Lollypop launches and crash after half a second.
~$ lollypop
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/mpris.py", line 68, in on_method_call
    variant = GLib.Variant(out_args, result)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 243, in __new__
    (v, rest_format, _) = creator._create(format_string, [value])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 132, in _create
    return self._create_tuple(format, args)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 167, in _create_tuple
    (v, format, _) = self._create(format, args[0][i:])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 126, in _create
    v = constructor(args[0])
TypeError: Argument 0 does not allow None as a value

Thanks!

**Comment by gnumdk** [comment]
Can you test git?

**Comment by captnc** [comment]
Tkx,

same behavior but with these errors
Namespace Secret not available
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/lollypop/mpris.py", line 68, in on_method_call
    variant = GLib.Variant(out_args, result)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 243, in __new__
    (v, rest_format, _) = creator._create(format_string, [value])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 132, in _create
    return self._create_tuple(format, args)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 167, in _create_tuple
    (v, format, _) = self._create(format, args[0][i:])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 126, in _create
    v = constructor(args[0])
TypeError: Argument 0 does not allow None as a value

**Comment by gnumdk** [comment]
Ubuntu with Unity? Does Gnome Music run?

**Comment by gnumdk** [comment]
Tmp fix: gsettings set org.gnome.Lollypop disable-mpris true

**Comment by captnc** [comment]
Yes with Unity. I just install gnome-music and it run fine.
Your tmp fix work well thanks!

**Comment by gnumdk** [comment]
gsettings set org.gnome.Lollypop disable-mpris false 
When you update to 0.9.211 (released today)

**Comment by captnc** [comment]
ok thanks!

**Comment by kronstadt21** [comment]
Updated to 0.9.211 and enabled mpris with same result, crashes with the same output:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/mpris.py", line 68, in on_method_call
    variant = GLib.Variant(out_args, result)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 243, in __new__
    (v, rest_format, _) = creator._create(format_string, [value])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 132, in _create
    return self._create_tuple(format, args)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 167, in _create_tuple
    (v, format, _) = self._create(format, args[0][i:])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 126, in _create
    v = constructor(args[0])
TypeError: Argument 0 does not allow None as a value

**Comment by gnumdk** [comment]
@kronstadt21 Ubuntu?

**Comment by kronstadt21** [comment]
Yes Ubuntu 16.10, works fine when disabling mpris as you suggested.

**Comment by gnumdk** [comment]
Don't understand why it works with Gnome Music, I use their code :-/

**Comment by kronstadt21** [comment]
Just checked to see if mpris is working with Audacious and Gnome Music, it does. I'm just speculating here but the fact that Gnome Music works could that in any way be dependant on its use of tracker?

**Comment by gnumdk** [comment]
Installed Ubuntu 16.10... No crash :-/

**Comment by kronstadt21** [comment]
Strange...

**Comment by gnumdk** [comment]
Are you sure it's Unity version?

**Comment by kronstadt21** [comment]
Unity version?

**Comment by gnumdk** [comment]
Ubuntu 16.10, not Gnome Ubuntu or Kubuntu or ...

**Comment by kronstadt21** [comment]
Oh yes its standard Ubuntu.

**Comment by gnumdk** [comment]
Here, sound menu seems not working with lollypop BTW :-/

**Comment by gnumdk** [comment]
@kronstadt21 Install or update? (16.10)

**Comment by kronstadt21** [comment]
It's an update. I've been rumaging through my installed packages with synaptic to see if i can spot any odd package.

**Comment by gnumdk** [comment]
Does it happend even if you don't play anything?

**Comment by kronstadt21** [comment]
Checked lollypop in synaptic and it states that it's in conflict with lollypop. So I'll try a complete removal and reinstall.

**Comment by gnumdk** [comment]
Here MPRIS support is broken with GNOME Music too... So issue is in Ubuntu sound indicator...

**Comment by gnumdk** [comment]
But don't understand why I can't reproduce the crash...

**Comment by kronstadt21** [comment]
Well a reinstall didn't solve anything...

**Comment by gnumdk** [comment]
launch this in a terminal:
dbus-monitor > /tmp/dbus_log

Launch lollypop and let it crash

Ctrl + C in terminal and past  /tmp/dbus_log file

**Comment by kronstadt21** [comment]
Here you go!
[dbus_log.txt](https://github.com/gnumdk/lollypop/files/531268/dbus_log.txt)

**Comment by gnumdk** [comment]
Can you test with a fresh user?

**Comment by gnumdk** [comment]
And you miss this one: "Does it happend even if you don't play anything?"

**Comment by gnumdk** [comment]
Can you test with current git too and paste output here (It should not crash anymore but I want to know debug message)

**Comment by kronstadt21** [comment]
OK. Ran a guest-session. And well it crashes before I get a chance to play anything...
[dbus_log.txt](https://github.com/gnumdk/lollypop/files/531307/dbus_log.txt)

**Comment by kronstadt21** [comment]
Just tested with git. It Works, Yayy!

Terminal output:
Player::restore_state(): track missing

(lollypop:22592): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x55d24fabc660 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
MPRISServer::on_method_call: Argument 0 does not allow None as a value org.freedesktop.DBus.Properties Get ['org.mpris.MediaPlayer2.Playlists', 'PlaylistCount']

Do you want a dbus_log?

**Comment by gnumdk** [comment]
Got MPRIS working on Ubuntu for 5 minutes and then no MPRIS again...WTF?

**Comment by kronstadt21** [comment]
Well 5 minutes is an improvement isn't it... sort of. Still crashes with the same output after the recent update. BTW with mpris enabled I can launch lollypop from soundmenu.

**Comment by gnumdk** [comment]
Still crashes?

**Comment by kronstadt21** [comment]
Yeah.

**Comment by gnumdk** [comment]
Output?

**Comment by gnumdk** [comment]
@captnc And you?

**Comment by kronstadt21** [comment]
Output is same as before;

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/mpris.py", line 68, in on_method_call
    variant = GLib.Variant(out_args, result)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 243, in __new__
    (v, rest_format, _) = creator._create(format_string, [value])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 132, in _create
    return self._create_tuple(format, args)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 167, in _create_tuple
    (v, format, _) = self._create(format, args[0][i:])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 126, in _create
    v = constructor(args[0])
TypeError: Argument 0 does not allow None as a value

And a dbus-log
[dbus_log2.txt](https://github.com/gnumdk/lollypop/files/532103/dbus_log2.txt)

**Comment by gnumdk** [comment]
Are you sure you are using git version? Looks like not...

**Comment by kronstadt21** [comment]
Your right, this is output from git version

MPRISServer::on_method_call: ('org.mpris.MediaPlayer2.Lollypop', 'This object does not implement the org.mpris.MediaPlayer2.Playlists interface') org.freedesktop.DBus.Properties GetAll ['org.mpris.MediaPlayer2.Playlists']

(lollypop:1220): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x56077d6b6660 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
MPRISServer::on_method_call: Argument 0 does not allow None as a value org.freedesktop.DBus.Properties Get ['org.mpris.MediaPlayer2.Playlists', 'PlaylistCount']

I can control lollypop from sound-indicator and song data is presented so mpris is working. But there is no song info when I launch lollypop. Song-info does not load on pressing play/pause. Song-info gets populated when I press skip forward/backward.

**Comment by captnc** [comment]
hi! git version (and mpris) seems work fine for me

**Comment by gnumdk** [comment]
@kronstadt21 Does it work better with last git?

**Comment by kronstadt21** [comment]
Yes it does. Sound-indicator is loaded with current track info on startup, so everything seems to work. Output:

MPRISServer::on_method_call: Argument 0 does not allow None as a value org.freedesktop.DBus.Properties Get ['org.mpris.MediaPlayer2.Playlists', 'PlaylistCount']

(lollypop:29776): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x55f3bc874690 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

**Comment by gnumdk** [comment]
Package building, you can remove git version:
$ sudo make uninstall

**Comment by captnc** [comment]
Thanks!
