### ISSUE TITLE
Mark with some border the played album

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#78]
I wants to see the current played song's album marked (by the border or
something like this).

Also, I would like for over's style for the albums (see in gnome-music there
is an over style. when you moved the cursor over some album).

**Comment by gnumdk** [comment]
Will give a look.

**Comment by gnumdk** [comment]
For the hover album effect, don't see this in gnome-music, are you using 3.16?

**Comment by yoseforb** [comment]
I'm using 3.16 and I see it.
The effect look like album cover lighter (brighter).
