### ISSUE TITLE
No MPRIS control widget in "Media" section of the day/time widget

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#780]
-Lollypop version: master db571c61c5375b5380c16f6bf6f0f0c92edef805
-Gtk Version: 3.20
-Linux distribution: Fedora 24

I can't control Lollypop via the MPRIS widget addet in Gnome 3.20, which appears in the "Media" section when you click on day/time section, in Gnome Shell top bar (the widget in the middle). No widget appears as if Lollypop doesn't expose MPRIS capabilities now.

**Comment by gnumdk** [comment]
Related to #779

**Comment by kostich** [comment]
If it's any help, last commit where MPRIS control widget worked as intended was 1081d899fe78c92f1fca7481ede9ac216c4b7c44 while the first commit where it dissapears is 00771f03c40d5b6ac846f82e5c0aafcecf47130a.

**Comment by gnumdk** [comment]
@kostich Is it fixed with last commit revert?

**Comment by kostich** [comment]
It is fixed now. Thanks!
