### ISSUE TITLE
Random tracks playlist show youtube results even without internet and web search disabled

### ISSUE THREAD

**Issue by somas95** [gnumdk/lollypop#781]
-Lollypop version:0.9.211
-Gtk Version:2.22
-Linux distribution:ArchLinux

-Describe your bug here:
With web search disabled, even without internet, the random tracks smart playlist tries to reproduce youtube songs. As the internet connection is off, when arrives to an web song lollypop stops, making that smart playlist unusable. Even with internet is too annoying that behavior, as the playlist tries to reproduce random songs from youtube, songs that I don't want to listen. 
I imagine that that is not the expected behavior, and if it is, an option to disable the web search in smart playlists would be great received.

Sorry for my bad English, my native language is Spanish

**Comment by gnumdk** [comment]
Will be fixed friday/saturday in 0.9.213 ;)

**Comment by somas95** [comment]
I compiled and works like a charm :p 
lollypop-git in arch's aur is amazing
Thanks for all!
