### ISSUE TITLE
Wrongs thumbnails?

### ISSUE THREAD

**Issue by ouafnico** [gnumdk/lollypop#784]
Hi,

Using 0.9.211, I see after scanning my library, a lot of albums have the same picture, of one album.

Anyway to correct this? I can provide anything you need.

Thanks
![capture d ecran de 2016-10-19 21-58-08](https://cloud.githubusercontent.com/assets/807350/19535247/308a2cc6-9647-11e6-8daf-821ecb6f085e.png)

**Comment by gnumdk** [comment]
Send me ~/.local/share/lollypop/lollypop.db by email.

**Comment by ouafnico** [comment]
Done :)

**Comment by gnumdk** [comment]
J'attends toujours ton mail ;)

**Comment by ouafnico** [comment]
Hello

Je viens de le reproduire.

Tu peux récupérer le dossier de test ici :

https://drive.google.com/open?id=0B8oXN2sgf2clWF8xd3lvajhPc3c

**Comment by gnumdk** [comment]
Ok, c'est bon, je reproduis ;)

**Comment by ouafnico** [comment]
good ;)

dis moi, j'arrive vraiment pas à comprendre, le mode random ça 
fonctionne comment ?

si je mets "mélanger par morceaux" sur "tous les artistes", et que je 
fais play, j'ai une chanson qui se lance (au bout de plusieurs 
secondes), et y'a qu'elle qui tourne en boucle :p

**Comment by d9h02f** [comment]
"Mode soirée" ne fonctionne pas? Je crois que c'est ça le mode random que tu cherches.

**Comment by ouafnico** [comment]
ah...

je t'avoue que je pensais pas que c'était le mode soirée le random.

ça fonctionne :)

merci
