### ISSUE TITLE
Can't Load Music Library

### ISSUE THREAD

**Issue by dabfalcon** [gnumdk/lollypop#787]
-Lollypop version: 0.9.75
-Gtk Version: Both 3.20.6-2 & 2.24.30-1.1
-Linux distribution: Deepin Linux 15.3

-Describe your bug here: Lollypop is unable to load the music library. I'm absolutely sure its pointing to the correct place and have tried making other locations with music in it to no avail. I've succeeded on another Deepin 15.3 installation (after facing the same problem and reinstalling it (maybe)). I'm not sure what causes it.

Perhaps the screenshot holds a clue into solving the bug.

Many thanks

![deepinscreenshot20161023190608](https://cloud.githubusercontent.com/assets/9454931/19625007/da359bca-9953-11e6-91c3-071c67799bcb.png)

**Comment by gnumdk** [comment]
Have you gstreamer libav installed?

**Comment by dabfalcon** [comment]
Yes 'gstreamer1.0-libav' is installed

**Comment by gnumdk** [comment]
$ lollypop -d

and paste output here

**Comment by dabfalcon** [comment]
Thanks for the help.
"gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)"
Also worth noting my repos have 'gstreamer0.10-plugins-base', '...-bad', '...-good' and '...-ugly'.

Installing blindly didn't work. Do you know what I need to install to get past this error? If that works I'll let the Deepin team know they should include this when downloading Lollypop.

It could also be that the plugin is installed but under a different name. Anyhow, you'd know volumes more than me. Thanks again.

**Comment by d9h02f** [comment]
gstreamer0.10 and gstreamer1.0 are two different things. Normally you can just remove all gstreamer0.10 packages because at this point nothing needs it anymore. Just look for all the same packages but for gstreamer1.0.

**Comment by dabfalcon** [comment]
Cheers Captain. I blindly installed the right gstreamer1.0 plugin and it works. I'll let Linux Deepin team know. If you know exactly what plug in was missing, that might save me some time. In any case, thanks d9h02f and gnumdk.
