### ISSUE TITLE
Beautify paths

### ISSUE THREAD

**Issue by alex285** [gnumdk/lollypop#789]
When you double click an audio file

![](http://i.imgur.com/ih5EkRL.png)

**Comment by gnumdk** [comment]
Your installation is broken, Lollypop should show tags...
Close this bug report as invalid as header with important informations has been deleted.

**Comment by alex285** [comment]
I can reproduce with the 2 AUR packages
0.9.211 and 0.9.213-git

**Comment by gnumdk** [comment]
So you are using archlinux :p
Is gst-libav installed?

**Comment by alex285** [comment]
Because it was a path issue I didn't thought the distro would had meaning, sorry!
Yes: gst-libav-1.9.90+2+g108b08c-1

**Comment by gnumdk** [comment]
And the file is tagged?

**Comment by alex285** [comment]
nop, it is just a download from youtube
it gives that back
Downloader::_get_album_art_lastfm: Album not found [/Unknown]
Downloader::_get_album_art_spotify: g-io-error-quark: HTTP Error: Bad Request (0) [/Unknown]
