### ISSUE TITLE
Put the bottom album detailed widget in a paned

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#79]
I not sure how to do this. I just wants to be able to expand and unexpand the
album detailed widget, like in paned.

**Comment by gnumdk** [comment]
Good idea!

**Comment by gnumdk** [comment]
But Paned and Revealer aren't compatible...

**Comment by yoseforb** [comment]
Why not? What the problem to put the Revealer in the Paned?

**Comment by gnumdk** [comment]
From my test, revealer do nothing when inside a paned...
