### ISSUE TITLE
Support network mounts

### ISSUE THREAD

**Issue by Jehan** [gnumdk/lollypop#790]
-Lollypop version: 0.9.213
-Gtk Version: 3.20.9-1.fc24
-Linux distribution: Fedora 24

I have a few network mounts, some are webdav (davs://), some are SSH (sftp://). They should show on any application which supports loading from the network. For instance, I can open (and save) a file from one of these mounts on GIMP, etc.
Unfortunately they don't show on Lollypop. Added support would be appreciated.

**Comment by gnumdk** [comment]
Fixed in uris branch.
Please test it and report issues here. Many changes in code but was really needed (this part always sucked), thank you ;)
