### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcbf' in position 73: surrogates not allowed

### ISSUE THREAD

**Issue by StefanescuCristian** [gnumdk/lollypop#792]
-Lollypop version: 0.9.213-1ppa1ubuntu1.1
-Gtk Version: 3.18.1.2
-Linux distribution: Ubuntu 16.04.1

-Describe your bug here:

I don't know if this is a Python or Lollypop bug.
I'm trying to set up the music library in Lollypop, but  it never gets populated. I've started Lollypop with -d switch and after it starts, it throws the following error in the console:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/lollypop/collectionscanner.py", line 152, in __scan
    paths)
  File "/usr/lib/python3/dist-packages/lollypop/collectionscanner.py", line 105, in __get_objects_for_paths
    uri = GLib.filename_to_uri(path)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcbf' in position 73: surrogates not allowed
```

I think that a filename has a strange character in it and the scanner doesn't know how to read it.
I don't know exactly what file and I don't know how to see which one causes the crash.

**Comment by gnumdk** [comment]
run lollypop -d on command line

**Comment by gnumdk** [comment]
http://unicode.scarfboy.com/?s=U%2Bdcbf

**Comment by gnumdk** [comment]
You can add:
print(path) at line 104 of /usr/lib/python3/dist-packages/lollypop/collectionscanner.py

And you will get filename...

Should be fixed with uris lollypop branch (do not use python anymore to walk into directories).

Will merge it soon.

**Comment by StefanescuCristian** [comment]
Thank you for the answer.

I guess you can close the issue.

**Comment by gnumdk** [comment]
You get it?
