### ISSUE TITLE
Switch to dark theme

### ISSUE THREAD

**Issue by agrml** [gnumdk/lollypop#793]
-Lollypop version: 0.9.213
-Gtk Version: libgtk-3-0: 3.18.9-1ubuntu3.1
-Linux distribution: Ubuntu 16.04 x86-64 (Unity, Compiz)

Switch to dark theme does not results in something visible.

**Comment by gnumdk** [comment]
Ubuntu default theme doesn't support dark theme

**Comment by MakisH** [comment]
Please mention the dark theme in the features list (I really liked the photos) and also mention that it is not compatible Ubuntu. I was worried that something was wrong with my system until I found this issue.
