### ISSUE TITLE
Crash on change cover

### ISSUE THREAD

**Issue by Matthieu34** [gnumdk/lollypop#794]
-Lollypop version: Last git
-Gtk Version: 3.14
-Linux distribution: Debian Jessie

Bonjour,

Lorsque j'utilise le bouton pour modifier une pochette, il ne se passe rien, juste l'icône se transforme en moins et si je recommence en plus.
Le bouton pour modifier la pochette ouvre une fenêtre qui se referme une fraction de seconde après.
Si je "m'énerve" un peu sur ces boutons lollypop crash complètement.

Dans un terminal ça donne :
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album.py", line 299, in _on_artwork_press_event
    popover = CoversPopover(self._album)
  File "/usr/local/lib/python3.4/site-packages/lollypop/pop_artwork.py", line 68, in __init__
    self._widget = ArtworkSearch(album.artist_ids[0],
IndexError: list index out of range
Erreur de segmentation

Encore merci !

**Comment by gnumdk** [comment]
Sur tous les albums?

**Comment by gnumdk** [comment]
>'utilise le bouton pour modifier une pochette, il ne se passe rien, juste l'icône se transforme en moins 
>et si je recommence en plus.

C'est le bouton pour ajouter l'album à la liste de lecture ça

>Si je "m'énerve" un peu sur ces boutons lollypop crash complètement.

Oui, j'ai la même chose...

**Comment by gnumdk** [comment]
J'ai testé sur debian stable, je n'ai pas ton problème, quand je clique sur le bouton, j'ai un popover avec les pochettes...

**Comment by gnumdk** [comment]
Fait moi un screencast

**Comment by Matthieu34** [comment]
Bonjour,

Alors voilà un screencast (en zip car github n'aime pas webm)
[Capture d'écran vidéo de 29-10-2016 08:43:51.webm.zip](https://github.com/gnumdk/lollypop/files/559795/Capture.d.ecran.video.de.29-10-2016.08.43.51.webm.zip)

Donc comme ça le montre, si je clique sur "modifier la pochette" un pop s'ouvre et se referme tout de suite.
Si je clique sur "ajouter", ça se transforme en - puis + sans qu'il ne se passe rien.
Si je retourne sur modifier la pochette, j'ai un crash avec cette erreur (après une compilation incluant le dernier commit) :
(lollypop:1776): Gtk-WARNING **: GtkOverlay does not have a property called index

(lollypop:1776): Gtk-WARNING **: GtkOverlay does not have a property called index
ViewContainer::__delayedclean_view(): <AlbumsView object at 0x7f4f5a41dd80 (lollypop+view_albums+AlbumsView at 0x2b06270)>
ViewContainer::__delayedclean_view(): <ArtistView object at 0x7f4f539942d0 (lollypop+view_artist+ArtistView at 0x30aea50)>

(lollypop:1776): Gtk-CRITICAL **: gtk_popover_set_relative_to: assertion 'GTK_IS_POPOVER (popover)' failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album.py", line 301, in _on_artwork_press_event
    popover.connect('closed', self._on_pop_cover_closed)
TypeError: object at 0x7f4f5a430d80 of type CoversPopover is not initialized

Et du coup j'ai penser que le bouton ajouter avait un soucis car ne fonctionnant pas avec les listes de lectures, j'en avait aucune. Du coup j'en ai créé une de test et ça n'a rien changé.

Voilà, merci.

**Comment by gnumdk** [comment]
Le [+] [-] ajoute un album à la liste des albums en cours de lecture...

Pour la pochette, pour moi c'est un bug de GTK 3.14... Sur mon VirtualBox avec Debian Jessie, ça fonctionne mais c'est peut être un problème avec ton driver Xorg. En tout cas, pour moi GTK 3.14 est vraiment très buggé donc je ne peux pas faire grand chose...

De ton côté, passer en testing ;)

**Comment by Matthieu34** [comment]
En tout cas après une nouvelle compilation ça fonctionne parfaitement....
Merci pour tout !
(Et non, en aucun cas je passerais à testing vu mes besoins)
