### ISSUE TITLE
Should not be able to add a web album to collection if already exists

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#797]
Web content gets inserted ("CD 1"), although I have the album locally ("CD 0"). Would be nice if you could provide an option to disable web content entirely in addition to the internet switch for the search function. Would be useful for poor connections or metered wifi, too.

![auswahl_012](https://cloud.githubusercontent.com/assets/10520767/19838360/dfabe0bc-9ecd-11e6-8557-45cebfe0a305.png)

**Comment by gnumdk** [comment]
Why did you add an album you already have? BTW, there is a bug, should not be possible...

**Comment by fb87** [comment]
I bought it and copied it in my music folder, even a restart doesn't fix this. But it still would be nice if there could be a global switch for web content, because music of artists gets added, with no respect of me liking it or not.

**Comment by gnumdk** [comment]
No music gets added. Music in "charts" will never be played by Lollypop except if you play it explicitly.

**Comment by fb87** [comment]
Ok, that's interesting, because some albums were added without me ever having used charts…

**Comment by gnumdk** [comment]
Do this albums are also local albums?

**Comment by fb87** [comment]
All albums are local, with my afore mentioned case being the only exception.

![joe bonamassa - lonesome whistle blues - lollypop_013](https://cloud.githubusercontent.com/assets/10520767/19839444/0a74205c-9ee2-11e6-9436-bb03d5c1137c.png)

**Comment by gnumdk** [comment]
Can you send me ~/.local/lollypop/lollypop.db?

And tell me by email albums added by lollypop...

**Comment by gnumdk** [comment]
Ok, able to reproduce your issue...

**Comment by fb87** [comment]
Chart albums are also inserted the same way into the popup, which appears at clicking on the current song in the title bar.

**Comment by gnumdk** [comment]
Easy fix for you, remove album from album menu, then update collection.

**Comment by gnumdk** [comment]
Will add a fix for current song in title bar, need some work.

**Comment by fb87** [comment]
I deleted the audio files, waited for a sync and placed them back. Same state as before.

I don't know how to remove an album from the album menu, the only option I see when pressing the hamburger menu is „save in collection“.

**Comment by gnumdk** [comment]
Save it, then delete it

**Comment by gnumdk** [comment]
> provide an option to disable web content

Just added an option that will disable any network access in lollypop.
