### ISSUE TITLE
Emulating stop by pressing previous track first time

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#798]
What do you think about this? This is like almost every audio device I use(d) behaves. This way one can repeat a song by pressing „previous track“ and further presses of „previous track“ then play previous tracks. Currently, I have to press „previous, next“ or „next, previous“ for repeating, which is a bit cumbersome.

**Comment by gnumdk** [comment]
This is the most stupid behaviour from audio device... You have many other way to repeat a track in lollypop.

**Comment by gnumdk** [comment]
If you want to auto repeat a track:
Maj + click on track ;)

**Comment by fb87** [comment]
Yeah, of course I can switch to Lollypop every time and do it manually by mouse. But most of the time, I do something else in a different application and control music playback via the fn keys of my keyboard - therefore it would be useful.
