### ISSUE TITLE
Allow sorts albums by album's name

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#80]
Right now, the albums sorts by the arist's name (and than by year release).
I wants the option (in the settings dialog for example) to order albums by albums's name.

The point is thas in the sidebar I have albums sorts by arist name…

**Comment by gnumdk** [comment]
Sorry, i don't find consistent to order albums by name and don't want to add an option for this...

And in the sidebar, you have artist name, not "albums sorted by artist name" ;)

**Comment by yoseforb** [comment]
The first albums in the flow box view is the first arist's albums in the sidebar.
The last albums in the flow box view is the last arist's albums in the sidebar…

So I got the same order twice.
