### ISSUE TITLE
Update search results when online-switch is toggled

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#800]
When the switch is toggled, the whole view gets re-rendered (which is a bit unnecessary), but it would be useful if the search results would be updated, too. So for "offline to online" an additional online search should be started, where as for "online to offline" the online results could just be filtered out, without starting a new search.

**Comment by gnumdk** [comment]
>which is a bit unnecessary
It is necessary.i

**Comment by fb87** [comment]
Ok, seemed unnecessary at least to me, thanks! :)
