### ISSUE TITLE
hidpi not working on album cover

### ISSUE THREAD

**Issue by alex285** [gnumdk/lollypop#801]
-Lollypop version:
0.9.213
-Gtk Version:
3.22
-Linux distribution:
Arch Linux

-Describe your bug here:
See screenshot!

![](http://i.imgur.com/dUSdeMG.png)

**Comment by alex285** [comment]
On second test I noticed this isn't always reproducable. Maybe close it?

**Comment by gnumdk** [comment]
[gnumdk@arch ~]$ ls .local/share/lollypop/info/Metallica_*.jpg
.local/share/lollypop/info/Metallica_lastfm.jpg
.local/share/lollypop/info/Metallica_spotify.jpg
.local/share/lollypop/info/Metallica_wikipedia.jpg

Send me this files ;)

**Comment by gnumdk** [comment]
Hmm, what is not reproducable? It works with some artists or it works randomly with metallica?

**Comment by alex285** [comment]
@gnumdk Okay I can reproduce. 
When I change the scaling to "2" from inspector, the album is not updating correctly, but if I go to another album and back, it works.

Same, if I change the scaling from "2" to "1", the image again is not updating, but it gets fixed when you change album and back.
