### ISSUE TITLE
Using the main pane for searches

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#804]
I thought it maybe would be nice if the search function acts like the nautilus search. So if you type in something, the current shown album overview (e.g. when "All artists" is selected) would be filtered by the typed text. Then you would have the results displayed not only in a small list, but structured per album (maybe even artist selectable/filterable) in the whole main pane. What do you think about this approach?

**Comment by gnumdk** [comment]
Will give a look but not sure Gtk.FlowBox can handle this... If ok, will only be available via a shortcut.

**Comment by gnumdk** [comment]
Will not be in next stable release... You will have to wait for 0.9.215

**Comment by gnumdk** [comment]
Filtering enabled in radios and playlists too ;)

**Comment by fb87** [comment]
Thanks a lot!
