### ISSUE TITLE
Main menu disappears when reopen the window after close 

### ISSUE THREAD

**Issue by simonbcn** [gnumdk/lollypop#805]
Lollypop git version 0.9.214.r8.g2bcbcef-1 (installed from [AUR package](https://aur.archlinux.org/packages/lollypop-git/))
GNOME Shell 3.22.1 (Wayland)
Arch Linux 64 bits
gtk3 3.22.2

I have activated "_Continue playing when close_".

I open Lollypop and the main menu is the correct:
![captura de pantalla de 2016-11-07 19-17-49](https://cloud.githubusercontent.com/assets/428231/20070322/44482f96-a520-11e6-8841-a21585fb2909.png)

I play music and I close the window. Lollypop is playing in background. I open Lollypop again and the main menu now is this:
![captura de pantalla de 2016-11-07 19-18-33](https://cloud.githubusercontent.com/assets/428231/20070346/6740339a-a520-11e6-9da1-ae340635b85d.png)

Moreover when I press "_Salir_" (_Exit_) in this reduced main menu, Lollypop doesn't exit, only close the window but it still remains in background.

**Comment by gnumdk** [comment]
Wayland startup notification support is broken... Can fix anything
https://github.com/gnumdk/lollypop/issues/648
https://bugzilla.gnome.org/show_bug.cgi?id=752258
Nautilus is broken too due to thiis bug

**Comment by gnumdk** [comment]
Ok, found a solution, don't know why it works now but it works...

**Comment by simonbcn** [comment]
It doesn't work. 

I open Lollypop, I close the main window with button `x`.
_Result_: Lollypop remains in background although it isn't playing anything.

I open Lollypop again.
_Result_: now there are 2 instances of Lollypop: one in background (_unable to restore_) and the new opened.

**Comment by simonbcn** [comment]
That gnome bug is fixed: https://bugzilla.gnome.org/show_bug.cgi?id=746435
In that bug explains the right way to do this.

**Comment by simonbcn** [comment]
Maybe it would be a good idea to ask for help on the Gnome bug thread, due to lack of documentation about it.

**Comment by gnumdk** [comment]
Not related to this bug... Startup notification works in master

**Comment by gnumdk** [comment]
Here the related bug: https://bugzilla.redhat.com/show_bug.cgi?id=1376471

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=768531

**Comment by gnumdk** [comment]
Not related too... But I'm sure it's not a lollypop issue... I need to report upstream...

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=774130

**Comment by simonbcn** [comment]
This problem is still present. 
lollypop git version: 0.9.223.r126.g27249cd7-1 (_compiled now_).

**Comment by gnumdk** [comment]
The problem is not in Lollypop, go to gnome bugs...

**Comment by gnumdk** [comment]
But here bug is not present...
