### ISSUE TITLE
Close with x button only close the window but the application remains in background

### ISSUE THREAD

**Issue by simonbcn** [gnumdk/lollypop#808]
Lollypop git version
GNOME Shell 3.22.1 (Wayland)
Arch Linux 64 bits
gtk3 3.22.3

I have activated "_Continue playing when close_".

When I close the main window with button `x`, Lollypop remains in background although it isn't playing anything. It should close the application.

**Comment by gnumdk** [comment]
Make sense

**Comment by simonbcn** [comment]
```
Arch Linux 
GNOME Shell 3.22.3
lollypop-git 0.9.230.r9.g18ed4e90-1 (installed form AUR)
```
It doesn't work again. But now it doesn't work even I select "_Exit_" in main menu.
