### ISSUE TITLE
Database update will fail if it encounters an unreadable file

### ISSUE THREAD

**Issue by jnj** [gnumdk/lollypop#812]
-Lollypop version: 0.9.214
-Describe your bug here:

CollectionScanner should skip files that don't have a sensible modification time. Perhaps even remove them from the database.

To reproduce:

chmod -x a directory that exists under your music collection that has previously been indexed by lollypop.
Run lollypop later; the db update will fail when it tries to determine last mod time of the files in the no-longer-readable directory.

The relevant line is in collectionscanner.py: 
`mtime = int(info.get_attribute_as_string('time::modified'))`

That ends up doing `int(None)`.

**Comment by gnumdk** [comment]
CollectionScanner::__get_objects_for_uris(): g-io-error-quark: Error opening directory '/home/gnumdk/Musique/Collection/Afrobeat/Amadou & Mariam/Dimanche à Bamako': Permission denied (14)

Seems already fixed by #802
