### ISSUE TITLE
Strange meta data info

### ISSUE THREAD

**Issue by opennomad** [gnumdk/lollypop#813]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop

WONTFIX:
- Showing bitrate

-Lollypop version: 0.9.214-1ppa
-Gtk Version: 2.24.30-4ubuntu2
-Linux distribution: Ubuntu 16.10

-Describe your bug here:

Meta data for songs in album doesn't match what it actually is. For example I have an album where I can see the mp3 artist tags are set to 'The Ting Tings', but in the display it lists all kinds of other stuff.

![image](https://cloud.githubusercontent.com/assets/4350520/20197205/76c3049a-a75b-11e6-8615-0ead37966895.png)
 
```
$ eyeD3 01\ -\ Great\ DJ.mp3                                            

01 - Great DJ.mp3       [ 5.87 MB ]
-------------------------------------------------------------------------------
Time: 03:22     MPEG1, Layer III        [ ~240 kb/s @ 44100 Hz - Joint stereo ]
-------------------------------------------------------------------------------
ID3 v2.3:
title: Great DJ         artist: The Ting Tings
album: We Started Nothing               year: None
boo
track: 1/10             genre: Alternative Rock (id None)
disc: 1/1
Comment: [Description: ] [Lang: eng]
Amazon.com Song ID: 206895966

UserTextFrame: [Description: Tagging time]
2010-03-15T21:01:14

FRONT_COVER Image: [Size: 66166 bytes] [Type: image/jpeg]
Description:

```

**Comment by gnumdk** [comment]
Send me album by email

**Comment by opennomad** [comment]
Done. i also see lots of other albums with either no artist or very very wrong artist info.

**Comment by gnumdk** [comment]
Can you try to reset db in settings?

**Comment by opennomad** [comment]
tried twice. same result

**Comment by gnumdk** [comment]
Strange, here all is ok with your "The thing things" album.

**Comment by opennomad** [comment]
ok. so I tried a 3rd time with no result and then blew away the `~/.local/share/lollypop` directory. Now everything looks to be correct from a quick spot check.

**Comment by gnumdk** [comment]
Don't understand what happened :-( Reopen if happen again.
