### ISSUE TITLE
Add radio?

### ISSUE THREAD

**Issue by orschiro** [gnumdk/lollypop#814]
Dear all, 

What a fantastic player!

Has become my new favourite player on Ubuntu 16.10. :-)

One question:

I love the web radio [SWR3](http://www.swr3.de/wraps/musik/webradio/aplayer/index.php?format=mp3&channel=0&). Can I somehow add it to Lollypop?

Thanks!

-Robert

**Comment by gnumdk** [comment]
You need the url but github is not a forum :p

**Comment by orschiro** [comment]
I am sorry for that! Problem is solved thanks to your hint. :-)
