### ISSUE TITLE
Sidebar glitch in Ubuntu 16.10

### ISSUE THREAD

**Issue by orschiro** [gnumdk/lollypop#816]
Dear all, 

Is someone affected by the same glitch using Ubuntu 16.10?

![lollypop](https://cloud.githubusercontent.com/assets/170947/20226767/b158f5e4-a849-11e6-8122-623a222041ac.gif)

**Comment by gnumdk** [comment]
GTK issue...

**Comment by gnumdk** [comment]
GTK_DEBUG=no-css-cache lollypop

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=763517

**Comment by orschiro** [comment]
Thanks for the bug tracker link, Cedric!

So, the solution is to wait until this is fixed upstream?

**Comment by gnumdk** [comment]
Can't see this bug anymore here on Fedora 25.

**Comment by gnumdk** [comment]
GTK_DEBUG=no-css-cache lollypop should allow you to bypass the bug, no?

**Comment by orschiro** [comment]
Not on Ubuntu 16.10, I am afraid. The glitch still exists.

orschiro@x230:~$ GTK_DEBUG=no-css-cache lollypop

(lollypop:27898): Gtk-WARNING **: Allocating size to lollypop+window+Window
0x55f44a956640 without calling gtk_widget_get_preferred_width/height(). How
does the code know the size to allocate?
ItunesCharts::__get_ids: g-io-error-quark: HTTP Error: Bad Request (0)


On Sat, Nov 12, 2016 at 1:41 PM, Cédric Bellegarde <notifications@github.com
