### ISSUE TITLE
Continue with radio after pausing

### ISSUE THREAD

**Issue by orschiro** [gnumdk/lollypop#820]
Dear @gnumdk,

1. I start to play a radio station. 
2. I press my pause hotkey button on my keyboard
3. I press my resume hotkey button on my keyboard
4. Lollypop resumes for a few seconds with cached content and then stops
5. I need to restart the radio from step 1.

Can Lollypop automatically resume after pausing?

Thanks!

-Robert

**Comment by gnumdk** [comment]
Yes, I need to stop on pause for radio and not pause... Will give a fix.

**Comment by orschiro** [comment]
Wow, that was quick. Amazing! :-)
