### ISSUE TITLE
Option not to repeat gone

### ISSUE THREAD

**Issue by Tvrdoglavi** [gnumdk/lollypop#823]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:
-Lollypop version: 0.9.216
-Gtk Version:
-Linux distribution: Ubuntu Gnome 16.10

-Describe your bug here:

The option not to repeat what is playing is gone. Playing an album now repeats it endlessly and prevents the system from going to sleep. Please bring back the option not to repeat back, or remove the repeat from default setup.

**Comment by gnumdk** [comment]
In headerbar -> right click on current track

**Comment by Tvrdoglavi** [comment]
That is such a cruel way to hide it. I've probably spent 30 minutes looking for it before giving up and using another app to listen to my night time music. That option needs to be intuitive and obvious, and hiding it in such a way is a terrible idea.

**Comment by blackjackshellac** [comment]
I have to agree that that functionality is a little obfuscated.  It would seem more intuitive to find those playback menu entries in a separate section of the shuffle drop-down.  Note also that if the shuffle drop-down is down, right clicking on the song title displays the wrong menu.  This also applies to the Party Mode, Search and Queue drop-downs.

**Comment by gnumdk** [comment]
>This also applies to the Party Mode, Search and Queue drop-downs.
Gtk issue.

**Comment by gnumdk** [comment]
@Tvrdoglavi Fixed too

**Comment by Tvrdoglavi** [comment]
Thanks!

**Comment by Tvrdoglavi** [comment]
It is now much easier to find the option not to repeat. I just don't understand why repeating would be the default behavior, it's undesirable in most cases. Can't we have the option back for setting the default to not repeat anything.

**Comment by gnumdk** [comment]
Option is here, open your eyes!
