### ISSUE TITLE
'Open Player' not working for Lollypop music palyer in Linux Mint 18

### ISSUE THREAD

**Issue by momit-rahman** [gnumdk/lollypop#825]
-Lollypop version: 0.9.217
-Gtk Version: I am not sure
-Linux distribution: Linux Mint 18 (x64)

-This can be a bug
In Linux Mint 18 sound applet give directly access to change track and maximize (open player) or close the player. Lollypop can do everything  except it cant open player from sound applet. This problem/bug happing from many previous versions. I am giving a screen shoot to describe better. ![screenshot from 2016-11-21 15-37-07](https://cloud.githubusercontent.com/assets/11898284/20477638/bae54fe0-b000-11e6-8754-d07b3fd07b55.png)
In this image beside the close (x) button the up arrow is open player button.

**I am a fan of lollypop music player and extremely sorry if my English goes bad**.

**Comment by gnumdk** [comment]
Raising Lollypop window works with GNOME shell applet and Unity 7 applet so the bug is not in Lollypop for me.

Report this to applet dev.

**Comment by momit-rahman** [comment]
Thanks for your reply. Ok then i will try to discuss with applet dev team.
