### ISSUE TITLE
Please add volume slider

### ISSUE THREAD

**Issue by dlnsk** [gnumdk/lollypop#826]
-Lollypop version: 0.9.217
-Linux distribution: Mint 16

**Please add volume slider.**
My case:
When I listen podcasts or some learning video in the room where people talk loud I put on my headphones and start Lolypop with background music but I need make music a bit quieter otherwise I don't hear podcasts...

**Comment by gnumdk** [comment]
Already exists... Right click on progress bar or shortcut...

**Comment by dlnsk** [comment]
Sorry, but this is very strange UI feature... I don't know any app with something like this, so user haven't possibility to gain this experience. I think it will be very useful to add small button next to progress bar.

In additional:
right click works only just on progress bar, a bit higher or below and it doesn't switch,
I didn't find shortcut in Help.

**Comment by gnumdk** [comment]
Shortcut is in shortcut window but your distro is too old...
Right click is just here for convenience, if this is really that bad, will remove the feature...

**Comment by gnumdk** [comment]
Alt + v

**Comment by gnumdk** [comment]
And I need to update documentation/help :-/

**Comment by dlnsk** [comment]
> Shortcut is in shortcut window but your distro is too old...
Yes. I told about Shortcut window. Now it is 0.9.220. I think it the latest.

> Right click is just here for convenience, if this is really that bad, will remove the feature...
It is not bad, but nothing in interface tell user that this feature is. Nobody do right clicks on every element in window just to check will occur something special or not.
So, in this reason I offer to add small toggle button to display this feature availability.

**Comment by gnumdk** [comment]
>Yes. I told about Shortcut window. Now it is 0.9.220. I think it the latest.
No you were talking about help. Shortcut window is not available in Mint.
