### ISSUE TITLE
Playing only 1 CD of Multi CD Album

### ISSUE THREAD

**Issue by Tvrdoglavi** [gnumdk/lollypop#827]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:
-Lollypop version:
-Gtk Version:
-Linux distribution:

-Describe your bug here:
So I picked up the new Metallica album and it has 3 CD's. I only wanted to listen to 2 of the 3 CD's and I don't see any way to do that in Lollypop. Lollypop groups multi CD albums and treats them as a single unit. I see no way to play only one of the CD's.

**Comment by gnumdk** [comment]
Fixed, but only for queue..., don't want to bloat interface with more buttons... Click on disc label ;)
