### ISSUE TITLE
MTP device does not sync

### ISSUE THREAD

**Issue by rCarto** [gnumdk/lollypop#828]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:
-Lollypop version: 0.9.218
-Gtk Version:
-Linux distribution: ubuntu15.10 

-Describe your bug here:

Folders and files are copied to the device and then deleted when syncing. Only an `unsync` folder and the `*.m3u` are left on the music folder.

**Comment by gnumdk** [comment]
Will release a bugfix release today with some more debug in MTP sync.

Once 0.9.219 installed, run:
$ lollypop -d

Sync one album and paste output here:
