### ISSUE TITLE
Translators credits

### ISSUE THREAD

**Issue by prescott66** [gnumdk/lollypop#83]
In About window there is no info about translators, in credits.

**Comment by gnumdk** [comment]
Yeah, need to fix this :)

**Comment by gnumdk** [comment]
You will be able to put your name as soon transifex update pot file

**Comment by d9h02f** [comment]
For some reason I can only see your name in the translation credits, at least on the Dutch translation.

**Comment by gnumdk** [comment]
https://www.transifex.com/gnumdk/lollypop/translate/#nl/lollypop/45969386?q=bellegarde

Already reported on transifex.

**Comment by d9h02f** [comment]
Ah, thanks!
