### ISSUE TITLE
The application should have a notification tray/area icon/applet so it can be reopened when playing while closed.

### ISSUE THREAD

**Issue by Dark-Witcher** [gnumdk/lollypop#832]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:
-Lollypop version:0.9.220
-Gtk Version: GTK3
-Linux distribution: Linux Mint 18 Mate.

-Describe your bug here:
I don't know if it is a bug per say, but if I close the application while playing I don't get a notification icon, for fast relaunch. If there currently isn't such an option, I think that one should be added.

**Comment by gnumdk** [comment]
Application in GNOME do not have a systray icon. Don't see how clicking a 22x22 icon is faster than clicking application icon in dock.

**Comment by tuankiet65** [comment]
@Dark-Witcher Lollypop is MPRIS compatible so you can install [this extension (gnome-shell-extensions-mediaplayer)](https://extensions.gnome.org/extension/55/media-player-indicator/) and get a indicator on the systray like this:

When closed:
![screenshot from 2016-11-25 15-35-12](https://cloud.githubusercontent.com/assets/1905496/20619035/ce18c4bc-b324-11e6-99b1-1cfd1ff4f801.png)

When expanded:
![screenshot from 2016-11-25 15-35-19](https://cloud.githubusercontent.com/assets/1905496/20619036/ce1d6f30-b324-11e6-8388-d7450293f716.png)
