### ISSUE TITLE
charts album added to my collection and the removed

### ISSUE THREAD

**Issue by meadowlands** [gnumdk/lollypop#833]
are they blacklisted in any way?
because they never come back in charts, maybe i'm just unlucky, or there's a way to clear this setting?
(i can search them anyway)
great feature btw!

**Comment by gnumdk** [comment]
Can you send me ~/.local/share/lollypop/lollypop.db by email and tell me some albums you are thinking about.

**Comment by gnumdk** [comment]
Ok, tested on my collection doesn't happen, but you need to wait I think, this may take some times to came back and depends on itunes charts.
