### ISSUE TITLE
Almost completely missing Ukrainian help

### ISSUE THREAD

**Issue by chpii** [gnumdk/lollypop#834]
-Lollypop version: 0.9.220
-Gtk Version: 3.22.4-1
-Linux distribution: Arch Linux x86_64 (mirror is 100% synced, system fully upgraded and rebooted)

-Describe your bug here:
-- 100% translated in Transifex.
-- Built from latest [AUR PKGBUILD](https://aur.archlinux.org/packages/lollypop-git/) in empty directory so everything was pulled from web as it is.
-- Installed properly with pacman -U, even removed Lollypop beforehand with -Rscn just to be extra sure.
-- ? Changes to Transifex help resource does not in any way reflect what is generated/pulled.
-- ? One word is being translated, but source is not help resource from Transifex.

![2016-11-26 18-23-18](https://cloud.githubusercontent.com/assets/7461424/20641694/6e1df52c-b406-11e6-8748-78219ea75117.png)

**Comment by gnumdk** [comment]
uk help was not translated on last release...
