### ISSUE TITLE
Track-length-propotional popularity for albums

### ISSUE THREAD

**Issue by adimit** [gnumdk/lollypop#837]
This is a feture request. Current version is `0.9.220`

-Describe your bug here:

Album popularity is currently directly proportional to the amount of tracks on the album (see [`set_more_popular`](https://github.com/gnumdk/lollypop/blob/08cedeff74daca13dd51827d33f32df3187b7d3e/src/database_albums.py#L213) and [`__on_stream_about_to_finish`](https://github.com/gnumdk/lollypop/blob/969d4604832d41231595979c1468d05113f367a3/src/player_bin.py#L600)). An album with few long tracks will therefore be disadvantaged over an album with many short tracks. In my collection, this means that, e.g. [Mariner](https://www.discogs.com/Cult-Of-Luna-Julie-Christmas-Mariner/master/984270) will rank below [Frank's Wild Years](https://www.discogs.com/Tom-Waits-Franks-Wild-Years/master/13929) at even album play counts, because the latter has a lot more tracks.

I propose to make the impact of individual tracks on album popularity to be dependent on either

* the track's length
* 1/n, where n is the amount of tracks on the album which is currently being listened to

The first option would equalize albums of equal length and different track numbers. Short albums, however, would be ranked down. So if I play an LP 5 times and an EP 5 times, the LP would be ranked higher.

The second option would equalize different length albums, as well as albums with different length tracks on them. Thus album popularity is a direct measure of how often you've played the full album (Just how track popularity is a measure of how often you've played the full track, regardless of track length.)

I am not proposing to change the way popularity ratings are computed for individual tracks.

I'd be willing to provide a patch for either option, depending on people's preference, as I think both would vastly improve the "Popular Albums" section, which, at the present, is all but useless for me.

**Comment by gnumdk** [comment]
Don't want neither option1 neither option2 :-/

**Comment by gnumdk** [comment]
But I see your issue.
