### ISSUE TITLE
 Artist bio and lyrics aren't visible

### ISSUE THREAD

**Issue by merloki** [gnumdk/lollypop#838]
-Lollypop version: 0.9.221
-Gtk Version: 3.14
-Linux distribution: Debian 8

-Describe your bug here:

I installed python3-pip and pylast, and I build Lollypop from git.

But the artist bio and the lyrics aren't visible anywhere.

**Comment by gnumdk** [comment]
Just use my Ubuntu ppa... Can't do support for every distro.

ps: click on current artist to get what you are searching for
