### ISSUE TITLE
Adding to playlist shuts down app

### ISSUE THREAD

**Issue by leighss** [gnumdk/lollypop#840]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:
-Lollypop version: 0.9.221
-Gtk Version: 3.18.9-1ubuntu3, 2.24.30-1ubuntu
-Linux distribution: Xubuntu

-Describe your bug here: Try to add album or track to playlist (via arrow, playlist, select playlist) and app shuts down.
Otherwise my best find of the year :+1:

**Comment by gnumdk** [comment]
Paste output here
