### ISSUE TITLE
Vertical alignment in mini mode

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#842]
Can you please consider the status bar for the alignment of the cover? Thanks!

// Also some snapping functionality could be nice if this is possible, then we could avoid the background spots while not having to resize with that precision. :)

![opeth - bleak - lollypop_002](https://cloud.githubusercontent.com/assets/10520767/20870674/523f24fc-ba8c-11e6-9273-67f161e773ec.png)

**Comment by gnumdk** [comment]
The bottom bar is transparent so cover is aligned.

**Comment by gnumdk** [comment]
Will make background same color as bottom bar.
