### ISSUE TITLE
Localization for string "Repetition" isn't used by the program

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#843]
-Lollypop version: master, revision d67bd012933f74eb285dc864c38e51edd14cb437.
-Gtk Version: 3.22
-Linux distribution: Fedora 25, Wayland session.

The string "Repetition" isn't shown in my native language [although it's translated on Transifex](https://www.transifex.com/gnumdk/lollypop/viewstrings/#sr/lollypop/101327813?q=Repet).

![repetition](https://cloud.githubusercontent.com/assets/4953862/20934906/1c4560c6-bbdd-11e6-8a15-96bb55ea21fd.png)

**Comment by gnumdk** [comment]
String are synced only before release... So you need to wait 0.9.223.

**Comment by kostich** [comment]
Ah, ok. For some reason I thought that I translated this string long time ago and thought that it's a bug in the software.

**Comment by gnumdk** [comment]
@kostich In fact, strings are not translated on transifex...  And I wan to release 0.9.223 in some hours :-/

**Comment by gnumdk** [comment]
My bad for last message, your native language is not ru :)

**Comment by gnumdk** [comment]
And this string is in sr.po et sr@latin.po of 0.9.222 :-/

**Comment by gnumdk** [comment]
![sr](https://cloud.githubusercontent.com/assets/3918824/21040599/4632747c-bde6-11e6-983a-26631337168f.png)
And here it works...

**Comment by kostich** [comment]
It seems that something was royally borked on my end. Did `sudo make uninstall`, nuked the my copy of Lollypop source, recloned, remaked it and it now also displays proper strings. Maybe .mo's weren't generated properly?

Thanks for retesting!

**Comment by gnumdk** [comment]
po/ and help/ directories need to be pulled one by one ;)

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop-po
