### ISSUE TITLE
Issue #819 reappeared in latest version

### ISSUE THREAD

**Issue by ragundo** [gnumdk/lollypop#845]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:
-Lollypop version: 0.9.223
-Gtk Version:
-Linux distribution: Ubuntu 16.10

-Describe your bug here:
After updating to last lollypop version, it's not possible to get the edit tags menu. I was able to do it in the last two previous versions after fixing #819 

Additionally, why don't you set up a Patreon?. I love this program, and I will love to support your fantastic work. It's the best linux music player by far.

**Comment by Abogical** [comment]
> Additionally, why don't you set up a Patreon?. I love this program

Bountysource Salt is the right site for this, it's like Patreon but specialized for github projects like these. Also I love this program as well :)

**Comment by gnumdk** [comment]
apt-get install lollypop-portal

Need to fix deps for next release.
