### ISSUE TITLE
lollypop Crash when try to play music

### ISSUE THREAD

**Issue by pdefert** [gnumdk/lollypop#847]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:
-Lollypop version: 0.9.210
-Gtk Version: GTK 3 and GTK 2
-Linux distribution: ubuntu 16.04

-Describe your bug here:

This monday 12/12/16 lollypop won't play some music (mp3 or webradio)

Last Friday , lollypop was working well

when i click on play the application crash with this error

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/lollypop/mpris.py", line 68, in on_method_call
    variant = GLib.Variant(out_args, result)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 242, in __new__
    (v, rest_format, _) = creator._create(format_string, [value])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 131, in _create
    return self._create_tuple(format, args)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 166, in _create_tuple
    (v, format, _) = self._create(format, args[0][i:])
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 125, in _create
    v = constructor(args[0])
TypeError: Argument 0 does not allow None as a value

the packages were updated today:

/var/log/dpkg.log:2016-12-12 10:55:59 status installed libc6:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:55:59 status installed libc6:i386 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:55:59 status installed libc-bin:amd64 2.23-0ubuntu4
/var/log/dpkg.log:2016-12-12 10:55:59 status installed man-db:amd64 2.7.5-1
/var/log/dpkg.log:2016-12-12 10:56:01 status installed click-apparmor:amd64 0.3.13.1
/var/log/dpkg.log:2016-12-12 10:56:01 status installed libc-bin:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:01 status installed man-db:amd64 2.7.5-1
/var/log/dpkg.log:2016-12-12 10:56:02 status installed apparmor-easyprof:all 2.10.95-0ubuntu2.5
/var/log/dpkg.log:2016-12-12 10:56:02 status installed click:amd64 0.4.43+16.04.20160203-0ubuntu2
/var/log/dpkg.log:2016-12-12 10:56:02 status installed gir1.2-click-0.4:amd64 0.4.43+16.04.20160203-0ubuntu2
/var/log/dpkg.log:2016-12-12 10:56:02 status installed python3-apparmor-click:all 0.3.13.1
/var/log/dpkg.log:2016-12-12 10:56:02 status installed python3-click-package:amd64 0.4.43+16.04.20160203-0ubuntu2
/var/log/dpkg.log:2016-12-12 10:56:03 status installed kodi-bin:amd64 15.2+dfsg1-3ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:03 status installed libcec3:amd64 3.0.1+dfsg2-9build1
/var/log/dpkg.log:2016-12-12 10:56:03 status installed libcec-platform1v5:amd64 1.0.10+dfsg1-8
/var/log/dpkg.log:2016-12-12 10:56:03 status installed libfstrcmp0:amd64 0.7.D001-1.1
/var/log/dpkg.log:2016-12-12 10:56:03 status installed libhdhomerun2:amd64 20150826-2
/var/log/dpkg.log:2016-12-12 10:56:03 status installed man-db:amd64 2.7.5-1
/var/log/dpkg.log:2016-12-12 10:56:08 status installed libc-bin:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:08 status installed libc-bin:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:08 status installed libiptcdata0:amd64 1.0.4-4ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:08 status installed shared-mime-info:amd64 1.5-2ubuntu0.1
/var/log/dpkg.log:2016-12-12 10:56:09 status installed libc-bin:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:09 status installed libjs-iscroll:all 5.1.3+dfsg1-1
/var/log/dpkg.log:2016-12-12 10:56:09 status installed libmicrohttpd10:amd64 0.9.44+dfsg-1ubuntu2
/var/log/dpkg.log:2016-12-12 10:56:09 status installed libnfs8:amd64 1.9.8-1
/var/log/dpkg.log:2016-12-12 10:56:09 status installed python3-apparmor:amd64 2.10.95-0ubuntu2.5
/var/log/dpkg.log:2016-12-12 10:56:09 status installed python3-libapparmor:amd64 2.10.95-0ubuntu2.5
/var/log/dpkg.log:2016-12-12 10:56:11 status installed man-db:amd64 2.7.5-1
/var/log/dpkg.log:2016-12-12 10:56:11 status installed man-db:amd64 2.7.5-1
/var/log/dpkg.log:2016-12-12 10:56:11 status installed ubuntu-core-launcher:amd64 1.0.43-0ubuntu1~16.04.1
/var/log/dpkg.log:2016-12-12 10:56:12 status installed multiarch-support:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:30 status installed libc-bin:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:30 status installed menu:amd64 2.1.47ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:30 status installed systemd:amd64 229-4ubuntu12
/var/log/dpkg.log:2016-12-12 10:56:30 status installed ureadahead:amd64 0.100.0-19
/var/log/dpkg.log:2016-12-12 10:56:32 status installed man-db:amd64 2.7.5-1
/var/log/dpkg.log:2016-12-12 10:56:36 status installed bamfdaemon:amd64 0.5.3~bzr0+16.04.20160824-0ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:36 status installed desktop-file-utils:amd64 0.22-1ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:36 status installed gnome-menus:amd64 3.13.3-6ubuntu3.1
/var/log/dpkg.log:2016-12-12 10:56:36 status installed hicolor-icon-theme:all 0.15-0ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:36 status installed libc6-dbg:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:36 status installed libc6-dev:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:36 status installed libc6-i386:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:36 status installed libc-dev-bin:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:36 status installed mime-support:all 3.59ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:36 status installed shared-mime-info:amd64 1.5-2ubuntu0.1
/var/log/dpkg.log:2016-12-12 10:56:48 status installed libtracker-sparql-1.0-0:amd64 1.8.1-0ubuntu1~xenial2
/var/log/dpkg.log:2016-12-12 10:56:48 status installed locales:all 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:49 status installed libprocps4:amd64 2:3.3.10-4ubuntu2.3
/var/log/dpkg.log:2016-12-12 10:56:49 status installed snapd:amd64 2.17.1ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:50 status installed procps:amd64 2:3.3.10-4ubuntu2.3
/var/log/dpkg.log:2016-12-12 10:56:50 status installed python3-apport:all 2.20.1-0ubuntu2.2
/var/log/dpkg.log:2016-12-12 10:56:50 status installed python3-distupgrade:all 1:16.04.19
/var/log/dpkg.log:2016-12-12 10:56:50 status installed python3-problem-report:all 2.20.1-0ubuntu2.2
/var/log/dpkg.log:2016-12-12 10:56:50 status installed ubuntu-release-upgrader-core:all 1:16.04.19
/var/log/dpkg.log:2016-12-12 10:56:50 status installed ubuntu-release-upgrader-gtk:all 1:16.04.19
/var/log/dpkg.log:2016-12-12 10:56:51 status installed apport:all 2.20.1-0ubuntu2.2
/var/log/dpkg.log:2016-12-12 10:56:51 status installed apport-gtk:all 2.20.1-0ubuntu2.2
/var/log/dpkg.log:2016-12-12 10:56:51 status installed light-themes:all 16.10+16.10.20161024-0ubuntu1~ubuntu16.04.1
/var/log/dpkg.log:2016-12-12 10:56:51 status installed neofetch:all 2.0.2-1ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:51 status installed oxideqt-codecs:amd64 1.19.4-0ubuntu0.16.04.1
/var/log/dpkg.log:2016-12-12 10:56:51 status installed python3-virtualenv:all 15.0.1+ds-3ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:51 status installed suru-icon-theme:all 16.10+16.10.20161024-0ubuntu1~ubuntu16.04.1
/var/log/dpkg.log:2016-12-12 10:56:51 status installed ubuntu-artwork:all 1:16.10+16.10.20161024-0ubuntu1~ubuntu16.04.1
/var/log/dpkg.log:2016-12-12 10:56:51 status installed ubuntu-mobile-icons:all 16.10+16.10.20161024-0ubuntu1~ubuntu16.04.1
/var/log/dpkg.log:2016-12-12 10:56:51 status installed ubuntu-mono:all 16.10+16.10.20161024-0ubuntu1~ubuntu16.04.1
/var/log/dpkg.log:2016-12-12 10:56:51 status installed virtualenv:all 15.0.1+ds-3ubuntu1
/var/log/dpkg.log:2016-12-12 10:56:51 status installed xserver-xorg-video-intel:amd64 2:2.99.917+git20160325-1ubuntu1.2
/var/log/dpkg.log:2016-12-12 10:56:52 status installed libc-bin:amd64 2.23-0ubuntu5
/var/log/dpkg.log:2016-12-12 10:56:52 status installed liboxideqtcore0:amd64 1.19.4-0ubuntu0.16.04.1
/var/log/dpkg.log:2016-12-12 10:56:52 status installed liboxideqt-qmlplugin:amd64 1.19.4-0ubuntu0.16.04.1
/var/log/dpkg.log:2016-12-12 10:56:52 status installed liboxideqtquick0:amd64 1.19.4-0ubuntu0.16.04.1
/var/log/dpkg.log:2016-12-12 10:56:52 status installed menu:amd64 2.1.47ubuntu1

**Comment by gnumdk** [comment]
Please update lollypop!

**Comment by gnumdk** [comment]
#779
