### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'Popover'

### ISSUE THREAD

**Issue by cabernet138** [gnumdk/lollypop#85]
Hello,
When trying to run on my ubuntu box which is "more or less" 14.10...
I used the PPA=ppa:gnumdk/lollypop

Ok, this is probably not a clean install but, at least,  it shows that some dep is not clearly stated...

python3-gi is  3.14.0-1

Cheers

**Comment by gnumdk** [comment]
Issue in your installation... Gtk should be at least 3.12!

**Comment by cabernet138** [comment]
Yep, you're right, but a deb package should detect that and abort the installation.

Now, after "compiling" lollypop, installing (in /usr/local), I now have : 

AttributeError: type object 'GtkIconLookupFlags' has no attribute 'DIR_LTR'

By the way, why don't you propose the debian/  directory in the git repository ? This way, every "cloner" may be sure to have the correct dependencies...

Cheers

**Comment by gnumdk** [comment]
Ok, it get it... Don't test this merge request:
https://github.com/gnumdk/lollypop/pull/66

Will fix next package (gtk version check) and i delete utopic package as it will not work.
Sorry for that...
