### ISSUE TITLE
Don't JPEGize PNG cover art

### ISSUE THREAD

**Issue by palob** [gnumdk/lollypop#850]
If you've got high quality PNG (or SVG or high quality JPG) cover art it will still be rendered and scaled as low-quality JPGs, causing ugly compression artifacts. Is there a way to avoid this?

**Comment by gnumdk** [comment]
example?

**Comment by gnumdk** [comment]
Ok, I understand your issue. I can make "jpg cache quality" available as a dconf option? (90% is current default).

**Comment by palob** [comment]
Thanks, will this retain PNGs?

Example PNGs (scaled down)
![cover2](https://cloud.githubusercontent.com/assets/7050624/21194670/03740066-c231-11e6-8c6b-527d63a76dc9.png)
![cover1](https://cloud.githubusercontent.com/assets/7050624/21194779/7aa1fa26-c231-11e6-82a3-be3e9ab7ef91.png)

Thumbnails in ``~/.cache/lollypop`` are rendered as JPG.
![cache3](https://cloud.githubusercontent.com/assets/7050624/21194815/a08db3b0-c231-11e6-963b-e888dd7bac7d.png)
![cache0](https://cloud.githubusercontent.com/assets/7050624/21194818/a34dde72-c231-11e6-92ff-58e8e7931f27.png)

**Comment by gnumdk** [comment]
>Will this retain PNGs?
No, will always use jpg file as cache, but with 100% quality, you will not see the difference. BTW, album view loading will be slower.

**Comment by palob** [comment]
Just in case I'm missing something, running ``gsettings set org.gnome.Lollypop cover-quality <value>`` is the only way to change quality (which is OK for me)?

**Comment by gnumdk** [comment]
Yes
