### ISSUE TITLE
[Feature Request]  Adding internet search service

### ISSUE THREAD

**Issue by Eeveel** [gnumdk/lollypop#851]
Hi,
Is it possible to adding some search internet service like Spotify, Soundcloud, Subsonic, Owncloud, etc.. like the one integrate in Clementine player?

Thanks for your player, I love it! It match so nice with Gnome environment!

**Comment by gnumdk** [comment]
Spotify is already integrated in Lollypop. More to come when I get time...

**Comment by gnumdk** [comment]
Itunes search provider justs land in current master.

**Comment by Eeveel** [comment]
Thanks for your time and hard work!

**Comment by bil-elmoussaoui** [comment]
@gnumdk Btw, you forgot to make the web search sensitive even if youtube-dl is not installed if the user has Itunes search enabled :+1:

**Comment by gnumdk** [comment]
No, you need youtube-dl even with itunes, it's just a search provider, not a listening provider ;)
