### ISSUE TITLE
Interface enhancements

### ISSUE THREAD

**Issue by second-story** [gnumdk/lollypop#855]
* Lollypop version: 0.9.223
* Gtk Version: 3.14
* Linux distribution: Debian 8.6 (Jessie / stable)

I've been very happy with Lollypop and I think it's miles ahead of the other music players I've used.  There are a few interface and design choices I struggled with, though.  They are:

* ## The hamburger icon as the "Playing albums" icon 
    I understand the idea behind using the hamburger icon here, where the lines represent listed albums.  I was very confused at first, though, because I expected the hamburger icon to represent a settings or options menu (more on that later).  
    
    I feel that a specialized icon would more strongly convey an association to "Playing albums."  Here are examples I found while searching for playlist icons.  Dot and dash variants came up frequently.  
    
    ![audio-stack-big-128](https://cloud.githubusercontent.com/assets/24594605/21242528/6121ff66-c2da-11e6-9663-48e638aed577.png)  -----   ![playlist0](https://cloud.githubusercontent.com/assets/24594605/21242789/96ea75fa-c2db-11e6-9834-1cfb5002b78a.png)  -----   ![free-black-cloud-playlist-md](https://cloud.githubusercontent.com/assets/24594605/21242794/9c541cb2-c2db-11e6-9072-039e68eb5499.png)  -----   ![playlist-128](https://cloud.githubusercontent.com/assets/24594605/21242797/a2bdd7e6-c2db-11e6-90df-cea7ffbff715.png)

* ## A missing settings / options icon
    I came to accept that Lollypop had no settings, help, about, etcetera until I learned how to access them by chance from a youtube review.  I would've never guessed that Lollypop's settings are only accessible (on Gnome 3.14 anyway) by clicking the program's name in the top panel.  Many other programs simply list "Quit" when this is done, which is why I didn't think to do this.
    
    If a new icon is used for playlists, I think that using the hamburger icon for settings and options would be a huge user experience boost.

* ## Seemingly unnecessary interactions
    When any album is clicked, the popover shows the artist, the album, the album year, and an arrow that expands to either "Playlists" or "Add to queue."  ~~~Also, when clicking "Playing albums," a U-turn icon appears at the top with the hover "Go to current track," but clicking this icon does nothing at all.~~~ EDIT: I played around with "Go to current track" some more and saw how it's supposed to work.  Sorry for my hasty recommendation.
    
    Unless more options will be added later, I suggest removing the arrow icon for the album popover.  Currently, it only reveals two other icons, so removing it and leaving "Playlists" and "Add to queue" always visible won't clutter the interface.  ~~~I'd also suggest either closing the "Playing albums" list when "Go to current track" is clicked, or doing something else that makes that button's purpose more clear.~~~
    
Thank you for this program and all the work you've put into it.  People on other operating systems don't know what they're missing.

**Comment by gnumdk** [comment]
Issue1: It's a debian issue, too old Adwaita icon theme

Issue2: GNOME is designed like this!

Issue3: There is much more icons available with lollypop-portal+kid3/puddletag/... installed
