### ISSUE TITLE
Option to Disable Album Auto-Rate

### ISSUE THREAD

**Issue by halbw** [gnumdk/lollypop#857]
-Lollypop version: 0.9.223
-Gtk Version: 3.18.9-1ubun  /  2.24.30-1ubu
-Linux distribution: Ubuntu 16.04 LTS

-Describe your bug here: Some of my favourite albums automatically get 1 - 2 star ratings with the auto rating system. Some may like this feature but giving the option to opt-in or opt-out of it would be much appreciated.

**Comment by gnumdk** [comment]
How your favourite albums get 1-2 star ?
All my favourite album are 5 stars.

**Comment by anaturinbor** [comment]
This whole time I thought it's a bug, not an intentional feature, that albums get auto-rated...

**Comment by gnumdk** [comment]
More you listen to an album, more it get rated... This doesn't work if you don't listen to your favorite albums...

**Comment by halbw** [comment]
Thank you gnumdk.

**Comment by halbw** [comment]
My favourite albums I've been listening to long before Lollypop. I might go back and listen to a song but spend most of my trying new music. 

Regardless, the automatic system is amazing for the 'Popular Albums' tab.

If I wasn't clear, the problem lies with displaying a generated rating to a user. All albums 'display rating' should be 'unrated' until the user manually decides how quality they think the album is. I think its safe to say most people want to use emotion to decide how good an album is and not have this choice taken away from them.

**Comment by gnumdk** [comment]
>Regardless, the automatic system is amazing for the 'Popular Albums' tab.

Now, the popular albums is only populated with rating system, so you will see in popular view albums your marked manually as popular...

Not sure I want to separate rating from popularity, as for me, rating is useless if not automatic.

**Comment by halbw** [comment]
Don't separate them if you don't want to. I think we both have valid points and its difficult to get the best of both worlds.

Default behaviour: As is.

Manual rating behaviour: As is except auto ratings are fully transparent. Manual ratings are of course visible. That way nerds like me can fuss over how much an album deserves without being told by Lollypop but still have 'Popular Albums' ect.

What do you think?
