### ISSUE TITLE
Alphabet next to interpret list

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#858]
I thought it would be useful if an vertical alphabet could be displayed on the right side of the artist list (temporarily while mouse-overing?), like in these mobile phone's contacts apps – there the alphabet appears as soon as the list as scrolled. Would be nice especially for larger music libraries – what do you think?

**Comment by gnumdk** [comment]
It already exists, but doesn't appear if your list is small.

**Comment by fb87** [comment]
There's just the first letter appearing, but no alphabet to quickly jump to a specific letter.

![](http://www.trickyways.com/wp-content/uploads/2010/11/iphone-contacts-group.png)

**Comment by gnumdk** [comment]
Don't know how to do this.... Can't put it on the left side... And on the right side, conflict with overlay scrollbar.

**Comment by gnumdk** [comment]
One more, after some testing, can't put every char in the world in this list... Sad because was a good idea...

And as selection list is sorted by tags, you can have string starting by "T" at top!

**Comment by bil-elmoussaoui** [comment]
It's shouldn't be that complicated, just create a list of the the first char of each artist name/album name and show it on the left as the suggested design...

**Comment by fb87** [comment]
Could you create an alphabet with the standard letters of the set language, map similar characters to their root letters (â => a, etc.) and make everything else not appear, or maybe show this under „other“. Or maybe you could make this availiable just for latin-based languages, so you should reach at least >95% of all users. ;)

**Comment by wolfv** [comment]
Maybe using https://pypi.python.org/pypi/Unidecode one could get a close approximation in latin letters for everything that's not covered with those 26 chars.

**Comment by fb87** [comment]
The alphabet maybe could also be placed right above the artists list, spread over some few lines, or maybe even at the bottom (like the Inkscape colorbar), if it's too complicated, placing it on the right side of the list [maybe there (on the right side, like the iPhone screenshot) it could be placed with some little space on the on the right side of the alphabet, so that the scroll bar could be displayed without overlapping the alphabet].

**Comment by gnumdk** [comment]
>The alphabet maybe could also be placed right above the artists list
Conflicts with pan drag & drop handle.

**Comment by gnumdk** [comment]
>It's shouldn't be that complicated, just create a list of the the first char of each artist name/album name and 
>show it on the left as the suggested design...

As i sayed, you will have this:
A
B
T
C
D
E
F
...

List is sorted by sqlite for performance reasons, if I start to check it manually, I will kill Lollypop.

**Comment by fb87** [comment]
Ok, but can't you just sort the output of SQlite while keeping the correct links? You just need to implement a jump to the first artist with the selected letter, can't this be done by the GTK-list-functions? I have no time to look at the code, but I don't understand why SQlite is involved for scrolling the artists list…

**Comment by gnumdk** [comment]
Just test current master and tell me... I really dislike this feature currently 👎

**Comment by fb87** [comment]
Gosh… autotools… But I try.

**Comment by gnumdk** [comment]
You need to scroll...

**Comment by gnumdk** [comment]
![fastscroll](https://cloud.githubusercontent.com/assets/3918824/21396449/98f481c8-c7a0-11e6-905d-c1fb5829ad7b.png)
Here the result, but when window is smaller, it overlaps with list icons :-1:

**Comment by gnumdk** [comment]
Ok, found a solution :)

**Comment by fb87** [comment]
Ok, yesterday it didn't show up if artist images weren't displayed – with the new pull it works fine. I like it a lot, bit thanks for your really wonderful work! But as you see in the image below, the alphabet should always scroll, so that the current selection is either in the visible area or alternatively maybe centered vertically.

![aerosmith - full circle - lollypop_001](https://cloud.githubusercontent.com/assets/10520767/21445272/3bf524ce-c8b7-11e6-809d-ad63a307f71e.png)

Btw: What do you think of the selection list above the artist list, to stay permanent and just the artist list being scrollable (only if the window is large enough)? It feels somehow strange that the selection list above is scrolling with the artist list.

**Comment by gnumdk** [comment]
>the alphabet should always scroll, so that the current selection is either in the visible area

Not possible and will not works...

> or alternatively maybe centered vertically.

Will not works...

The alphabet is scrollable BTW.

**Comment by gnumdk** [comment]
>Not possible and will not works...

Was possible :)

**Comment by fb87** [comment]
Great! Thanks!

If you could manage it being vertical centered, too, it would be absolutely perfect!
