### ISSUE TITLE
Use originaldate/originalyear tag for album year if it exists

### ISSUE THREAD

**Issue by dotreloaded** [gnumdk/lollypop#859]
I synced some of my albums up with the musicbrainz db. The albums now have an originaldate tag of the date the album first came out, as well as a date and/or year tag of the year this release of the album came out.

Lollypop currently uses the date or year tag and ignores the originaldate tag. This messes up the chronological order when you click on the current track to get a list of an artist's albums. Request is to use originaldate for this if it exists. Year will need to be parsed from originaldate value. There is also an originalyear tag that musicbrainz uses that should also be looked for.

This shouldn't be used for compilations/anthologies though, because I've seen the originaldate/originalyear tags for those kinds of releases used to mark when a song, rather than an album, originally came out and so they can have all kinds of different values.

**Comment by gnumdk** [comment]
Don't understand your issue. Original date is about "when the track was released" and IMO is not about album release date... Year tag is about album release date.

**Comment by gnumdk** [comment]
https://www.quora.com/Can-date-ID3-tags-be-used-to-distinguish-between-date-of-album-release-date-of-recording-and-date-of-composition

**Comment by dotreloaded** [comment]
Musicbrainz documents originaldate being about original album release date.

https://picard.musicbrainz.org/docs/tags/ 

Here's an example of what I'm talking about using album Daft Punk - Discovery which originally came out in 2001. I used [beets](https://github.com/beetbox/beets) to do the sync. Before sync, it had the tag `year = 2001`. It synced with [this release group](http://musicbrainz.org/release/8343b377-ea18-4d64-b5f6-ffaf55d8f55b) that came out in 2005. Now the album has the tags `year = 2005`, `date = 2005`, and `originaldate =  2001-02-26`. Lollypop shows the album with the year 2005 but should be 2001.
