### ISSUE TITLE
Hovering on a currently playing song starts the preview for that song, causing the same track to be played simultaneously

### ISSUE THREAD

**Issue by tuankiet65** [gnumdk/lollypop#862]
-Lollypop version: 532704e
-Gtk Version: gtk2 2.24.31, gtk3 3.22.5
-Linux distribution: Arch Linux

When hovering on a current playing song, the preview should not be played. However the current behavior is that the preview plays anyway, so there'll be two tracks of the same song playing simultaneously.

Video demonstrating the issue: https://my.mixtape.moe/cwpsss.mp4 (first mouse event is click on the song entry, second is hover on the same entry)

**Comment by gnumdk** [comment]
Not a bug... Preview is about listening in another output, not the same
