### ISSUE TITLE
Deleting automatically rated stars

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#866]
• Lollypop version: 0.9.223
• Gtk Version: 3.22.2
• Linux distribution: Fedora 25

When automatic rating is deleted, the automated ratings should be removed (or at least not be shown anymore), so that we know what we've rated manually and what was rated automatically and needs to be re-rated.

**Comment by gnumdk** [comment]
This implies clearing all stats...

**Comment by gnumdk** [comment]
Ok, I think I will removed previous commit and restoring default behaviour (auto rate albums).

And will add a favorite album section in Lollypop.

**Comment by fb87** [comment]
So you don't distinct between user set rating and auto rating?

**Comment by gnumdk** [comment]
>ok to clear all stats (to me)

But not for normal users who will kill its stats by clicking on an unclear option.

>it would affect my rating if my girlfriend plays her songs while staying…

Give her another account

>I like stars for selecting the songs I copy to my mobile 

Lollypop will not help you with that, tracker maybe? And "Loved albums" do the same...

**Comment by gnumdk** [comment]
>I'm in party mode in 99% of all time, so all ratings would average to 2,5 stars over time
No, because I'm sure even in party mode you skip tracks that will not be rated.

**Comment by fb87** [comment]
A second account would be really cumbersome and thus not practical – so would you PLEEEASE leave the option for deactivating auto ratings? 😀

I thought another solution would maybe be, to ask the user at deactivating auto rating, to delete the stats or leave them …?

The problem in general is, that user-editable ratings are also automatically done by the program, which is really confusing in my opinion – because every user is accustomed to set all ratings by his/herself and it is somewhat irritating that the system modifies data, what is also modifyable by the user.

I like the option for auto rating, but a better distinction between auto ratings and user ratings would really benefit the program. I suppose internally two ratings for every song – one auto-set and one user-settable:
• With the auto rating option deactivated, the display of auto ratings should disappear (but ratings could still be done internally) and just user ratings should be shown as stars.
• With auto rating option active, all auto ratings should be shown as e.g. 50% transparent (or grey) stars. If user ratings were set for a song, the auto ratings should not be shown, but instead the user-set ratings either fully intransparent (or with another color, e.g. slightly blueish).

This approach would benefit the distinction between auto-set and user-set ratings, and doesn't confuse users anymore, since at first rating, the visual and functional distinction of both ratings is clear.

**Comment by fb87** [comment]
Since you deleted the switch for deactivating auto rating – is there an option for self-rating music without ratings getting messed up by auto-rating, rendering the ability of self-rating absolutely pointless?

**Comment by gnumdk** [comment]
Hello, are you using trunk? Lollypop now handles auto-rating (black stars) and user rating(gtk theme selected color stars). In populars view, user tracks/albums with rating >=4 are show first.

**Comment by fb87** [comment]
Ah, now I pulled and recognized it, perfect! Very much thanks!!

**Comment by fb87** [comment]
The manually set ratings do get written to the file tags, I guess, while the automatic ratings don't?

**Comment by gnumdk** [comment]
Yes. I will add reading from tags on first scan letter.

**Comment by fb87** [comment]
Sorry, one further question: I use the Gnome extension [Media Player Indicator](https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer), but doing ratings there results in auto-rating-style ratings instead of marked-up-stylish manual ratings. Can this be solved by Lollypop or should I open a bug report there?

**Comment by gnumdk** [comment]
Need to be fixed in lollypop, I will.

**Comment by gnumdk** [comment]
Done

**Comment by fb87** [comment]
Great, thanks!
