### ISSUE TITLE
Progress bar in loudness diagram style

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#867]
Another complex but really nice feature request:

Could you make the progress bar like the VU diagram of [Roon](https://roonlabs.com/) or Soundcloud?
This would not only look incredible, but also eases finding significant spots in audio tracks. 😁

![auswahl_001](https://cloud.githubusercontent.com/assets/10520767/21375736/f35aac26-c72f-11e6-932d-ae8f8113f128.png)

**Comment by gnumdk** [comment]
Will look out of place in Lollypop headerbar...
Will either slow down scanning either slow down loading.
It's an important feature in a mixing software, not in lollypop.
So...
