### ISSUE TITLE
Lollypop not adding new albums to collection

### ISSUE THREAD

**Issue by fernando0010** [gnumdk/lollypop#872]
• Lollypop version: 0.9.223
-Gtk Version: 3.14.5+4 / 2.24.25-3+deb8u1
-Linux distribution: debian jessie

New albums aren't added to the collection, debug show this error: 

> CollectionScanner::__scan() add() missing 2 required positional arguments: 'album_popularity' and 'album_rate'

Tried to re-scan the collection, remove the folder from database and add it again but it doesn't seem to fix it.

Thanks and congratulations on lollypop, it's a wonderful player.

**Comment by gnumdk** [comment]
Please close if fixed by last commit.

**Comment by fernando0010** [comment]
Fixed, thanks
