### ISSUE TITLE
librefm login not working

### ISSUE THREAD

**Issue by temrix** [gnumdk/lollypop#873]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.223
• Gtk Version: 3.20.9-1ubuntu2
• Linux distribution: Ubuntu 16.10

The login from Lollypop into librefm does not work. My credentials are correct and do work with the website. Maybe there was a change with their API recently.
I have double-checked with version 0.9.220 (where it was working a week before) and it was the same. There is no debug error. How can I provide further information?

**Comment by gnumdk** [comment]
pylast.MalformedResponseError: Malformed response from Last.fm. Underlying error: no element found: line 1, column 0

Error from pylast (or libre.fm api is broken). Report to https://github.com/pylast/pylast/issues
