### ISSUE TITLE
Last.fm authentication problems

### ISSUE THREAD

**Issue by anonimo1w** [gnumdk/lollypop#874]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.99.223
• Gtk Version: 2.24.31/3.20.9
• Linux distribution: 4.8.15-200 - Fedora 24

I'm trying to sync with my last.fm account but it always returns this error on debug
> Lastfm::__connect(): Authentication Failed - You do not have permissions to access the service

I have all the dependencies installed but still have this error, although i can connect on webpage and on rhythmbox.. =/

**Comment by gnumdk** [comment]
Are you sure your password is ok? I can reproduce this message by entering a wrong password...

**Comment by gnumdk** [comment]
Seems Fedora pylast package is not up to date...
Please update to 1.6.0 or use my flatpak package... (I need to add a flatpak repo, I know).

**Comment by anonimo1w** [comment]
Yes, my password is correct (although i'm not sure if this would work, I tried typing and copying/paste the same password used to login) 

Thought about the pylast version (which was, in fact, obsolete).. after the update i tried and didn't work..

Tried with the flatpak version too and the same error was returned..

**Comment by gnumdk** [comment]
Can you try with a new account? If doesn't work, send me login/passwd by email.

**Comment by anonimo1w** [comment]
Fixed (finally!!)
Tried creating a new account as you suggested and it did work, but as I wanted my old account I tried to change the password and... fixed. Maybe it was the new security pattern, followed it when changing my password.

Thanks for the help :)

**Comment by gnumdk** [comment]
#1106
