### ISSUE TITLE
Questions about search and charts

### ISSUE THREAD

**Issue by anonimo1w** [gnumdk/lollypop#875]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.99.223
• Gtk Version: 2.24.31/3.20.9
• Linux distribution: 4.8.15-200 - Fedora 24

If possible, change how search is shown so is easier to select between music, albums or artists. (as nautilus or as a check box in the popup already used)

Also, is it possible to show/(un)check the provider of the web search? Seems that you search on iTunes and Spotify too right? is it possible to sync/login with any of those ? (not sure about their APIs)

The last question is about how charts is organized, if would be possible to categorize in a way resembling the playlists organization (Maybe categorize as Billboard Top 100 USA/Brazil/France/Japan... Gaon charts.. for example..)

**Comment by gnumdk** [comment]
>If possible, change how search is shown so is easier to select between music, albums or artists.

Search has been improved seen last release, will not add checkbox.

>Also, is it possible to show/(un)check the provider of the web search?

Yes, in next release

>The last question is about how charts is organized
Charts are based on your music and your locale.

If you want more charts, just point me to an API and open a new issue: "Support XXX as chart provider".

**Comment by anonimo1w** [comment]
Now.. I read again here and just realized that.. I didn't explained exactly well what as intended by my comment in the first and last points.. (Although the different explanations may lead to same answers, may be better to explain in a clearer way)
 
1st - Although is shown what you're getting (if song or album) it can be hard to find what you want sometimes (when too much songs and albums appear together for example). 
The suggestion would be to have in search something akin to nautilus, so if someone want to sort (albums first then songs or the reverse, or just want one of those), want to select by genre (of song or album) or year or even just the songs that someone was the "feat.", for example, it could be achieved (if any of these is possible).

![img](https://csorianognome.files.wordpress.com/2016/02/search5.png)


Last - While I was debugging (had some kind of one time error while searching a album, if anything appears i'll open a new issue..) noticed the link to the iTunes rss chart, it was downloading/updating the Jazz Top Albums. 
Instead of what i said, i meant to suggest to organize these charts, Top 40 (Jazz/R&B/Rock/Pop/K-Pop..) Albums for example, in a mode resembling how playlists is organized and (also) indicating the source. So, as example:
Top 40 Jazz Albums (iTunes icon)
Top xx Genre Albums (iTunes icon)
...
Weekly top [by country] (spotify icon)
Playlist generated (spotify icon)
