### ISSUE TITLE
Party mode: Current song isn't queued into the song history

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#877]
[master]

When running a song X in party mode, switching to the previous track Y and per "next" back to song X again doesn't work, since the "next random song" (shown in the party mode popup) is played instead. Just fully played or skipped songs are added to the song history, but also songs which ran for some short time should be made available again per history instead of being skipped in this case.

**Comment by gnumdk** [comment]
Related to #864 fix I guess...
