### ISSUE TITLE
Preferences not saved between sessions

### ISSUE THREAD

**Issue by dotreloaded** [gnumdk/lollypop#879]
• Lollypop version: 0.9.223
• Gtk Version: 3.22.5
• Linux distribution: Arch Linux

When I close and reopen lollypop, the preferences I changed aren't carried over. Does lollypop save a config file?

**Comment by gnumdk** [comment]
Broken GNOME, can't do anything. Lollypop use dconf... See with ArchLinux forum.

**Comment by gnumdk** [comment]
https://bbs.archlinux.org/viewtopic.php?id=165485
