### ISSUE TITLE
Web-Radio

### ISSUE THREAD

**Issue by thidau** [gnumdk/lollypop#88]
Hi,
Thanks for your grett work on lollypop.
It would be great to have a web radio feature to listen to FIP and FranceInter with mp3 stream. It's the only thing missing for me and unfortunately I need to keep rhythmbox in parallel for now.
thanks
Thierry

**Comment by gnumdk** [comment]
Will be next major feature.

**Comment by gnumdk** [comment]
Duplicate #38
