### ISSUE TITLE
Artist information of various artists albums

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#881]
[master]

I have several compilations of many various artists, but I only see the track artist of a song if I play it. Would you mind providing some information in a way that one can easily overview which song is of whom? Maybe an additional (toggable?) column if there's plenty space remaining, like in full screen?

![elvis presley - don t be cruel - lollypop_001](https://cloud.githubusercontent.com/assets/10520767/21567377/ffbda58a-ceab-11e6-8b56-070afba9c597.png)

**Comment by dotreloaded** [comment]
What theme is that?

**Comment by fb87** [comment]
[Adapta](https://github.com/adapta-project/adapta-gtk-theme)

**Comment by gnumdk** [comment]
1) Lollypop already handles artist tag, seems your files doesn't have an arist tag
2) Setting an album artist to V.A is stupid, a compilation should not have album artist tag.
![compilations](https://cloud.githubusercontent.com/assets/3918824/21569762/20d7eabe-cec0-11e6-9503-e6c7e36d233d.png)

**Comment by gnumdk** [comment]
Ok, you files have an artist tag :) Can you test with Adwaita (to be sure) ?

**Comment by gnumdk** [comment]
Ok, tested with Adapta, working here... Can you send me a file by email.

**Comment by fb87** [comment]
I see – I nedded to remove the album artist for it showing up in compilations – then track artists are shown (since artist tags are provided, as you see in the top bar of my screenshot). But they don't get shown outside of the compilations category.

For real compilations this works fine, but some albums from specific artists feature other artists on several tracks, like you see in this second screenshot. This information is of interest, if you want to play „the track of Eminem with Lil Wayne, but you don't know the name of the song“. But sadly this gets hidden. Maybe you could show additional info by taking the track artist, substract the album artist and display the remaining part?

![auswahl_001](https://cloud.githubusercontent.com/assets/10520767/21570199/2806a7ae-cec4-11e6-9311-2b49924c3122.png)

**Comment by gnumdk** [comment]
But Lollypop already handles that, send me a file, should works!
![artists](https://cloud.githubusercontent.com/assets/3918824/21570519/02a7f938-cec7-11e6-8e84-7b80b1102b9c.png)

**Comment by fb87** [comment]
Oh ok

**Comment by gnumdk** [comment]
I hope i didn't break anything, can't understand original code and comment 👎

**Comment by fb87** [comment]
Very nice!
Do you think it's a good idea to remove the album artist if the track artist if
• the track artist string begins with the album artist and
• no comma follws [", artist2 & artist3" looks awkward, whereas "feat. artist2 & artist3" looks good]
(and strip the remaining whitespace)?
