### ISSUE TITLE
Handling soundtracks like compilations

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#882]
Just a suggestion: What do you think about handling Soundtracks (genre-tag == soundtrack) (optionally) like compilations (as an additional category, but with a similar behaviour like compilations)?

I own some soundtracks, which are either of various artists and sorted under compilations – or of the same artist and thus sorted along with my normal music. I mostly hear rock, metal and house music, and to me, soundtrack artists sorted in between my main music feels somewhat irritating, since I often look for a specific artist of my main music – but I never look for a soundtrack artist.

Further, it provides access to all soundtracks without having to create a genre filter (which would feel somewhat wrongly to mee, since soundtrack actually isn't a real genre).

**Comment by gnumdk** [comment]
No sorry, will not.
 This can't work since genre tag is not fixed but a free string (since id3v1 is dead).
