### ISSUE TITLE
Wrong MPRIS rating export?

### ISSUE THREAD

**Issue by fb87** [gnumdk/lollypop#883]
Hi Cédric, I run the Gnome extension „media player indicator“ which showed me a rating of „12“ at one song and „9“ at another one. Could it be, that this is not the star rating, but the play count?

**Comment by gnumdk** [comment]
How do you see rating like this? It show star rating... But only internal popularity.

**Comment by fb87** [comment]
In the extension one can show internal variables (like trackRating) in the tray text. Thanks, I'll try.

**Comment by fb87** [comment]
Could you please add an MPRIS updating signal after the song's metadata gets changed? [eonpatapon/gnome-shell-extensions-mediaplayer#303]

**Comment by fbruetting** [comment]
I still have a track where a rating of 8 is exported…

**Comment by JasonLG1979** [comment]
>I still have a track where a rating of 8 is exported…

MPRIS2 spec says xesam:userRating should be a float between 0.0 and 1.0.
https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#index22h4

But not one single app I've ever seen actually follows that part of the spec. Everyone seems to use an int value 0 - 5. (MPRISv1 spec I believe?) And every client I've ever seen expects a 0 - 5 value. So basically the rating should never be over 5.

**Comment by fbruetting** [comment]
Sometimes still ratings >5 are exported. At the moment a song is shown with a rating of 6 in Media Player Indicator.

**Comment by JasonLG1979** [comment]
> At the moment a song is shown with a rating of 6 in Media Player Indicator.

That's not even possible. At most 5 stars will be displayed in the ratings.
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/widget.js#L310-L325

**Comment by JasonLG1979** [comment]
@gnumdk What is the rating scheme in Lollypop. Meaning what is the max rating and what not?

**Comment by fbruetting** [comment]
Setting the ratings works perfectly (except for clearing the rating). Showing rating also works in general, but sometimes I get these numbers larger 5…
