### ISSUE TITLE
Handle multiple genres tags

### ISSUE THREAD

**Issue by risq** [gnumdk/lollypop#884]
• Lollypop version: 0.9.223
• Gtk Version: 3.22.4-1
• Linux distribution: Debian testing (stretch)

Hi,

Would it be possible to handle comma-separated "genre" tag as multiple genres ?
I use [beets LastGenre plugin](http://beets.readthedocs.io/en/latest/plugins/lastgenre.html) to fetch up to 3 genres by album, but Lollypop handle them as a single entry :

![screenshot from 2017-01-02 15-32-03](https://cloud.githubusercontent.com/assets/5665322/21591001/a7620da2-d100-11e6-8bd6-ae6ac69bf6da.png)

Thanks !

**Comment by gnumdk** [comment]
Lollypop already handle genre separator:
- Multiple genre frames in APE tags
- ; separator

Using , as separator is unwanted for me as it can be a valid genre name...

**Comment by risq** [comment]
Great, I didn't know about the `;` separator, thanks.
