### ISSUE TITLE
Unconsistent album assignment

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#885]
I own the album „Chronik I“ of abum artist „Selfmade Records“. This album contains some tracks from several track artists. If I play one track of „Kollegah“, this track and the whole album is assigned to Kollegah instead of Selfmade Records, as can be seen in the title bar (which is correct).

But if I click on it, you see the album got assigned to Kollegah in the popup and all albums of Kollegah show up, instead of all albums of Selfmade Records (if I click on Kollegah on the left pane, the album isn't contained). Second problem is, that just this album is displayed instead of all albums of Selfmade Records.

So the assignation of the list needs to differentiate album and track artists. Both all albums of the album artist and the title artist are of interest here. Maybe this can be solved by implementing a GtkStack which can be switched between the album artist and the track artist?

This could be further improved by splitting (parsing should be not that difficult…?) all track artists. So if there's an album of Selfmade Records, and the current song is of „Kollegah feat. Favorite“, panes for each Selfmade Records / Kollegah / Favorite could be shown. What do you think of this?

// The splitting could even further provide the ability for the artist overview, to display all songs the artist was involved in and not just the main songs.

![kollegah - ein guter tag zum sterben - lollypop_001](https://cloud.githubusercontent.com/assets/10520767/21619002/064ff2c8-d1ee-11e6-9e34-9099a7d15663.png)

**Comment by fbruetting** [comment]
Thanks! Can the list be opened directly at the position of the current album (like linking to specific headings in HTML)?

**Comment by gnumdk** [comment]
There is a button for that (jump button)

**Comment by fbruetting** [comment]
Ah sorry, never recognized! :)
