### ISSUE TITLE
lollypop crashies when selecting songs from file manager

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#886]
as the title says lollypop crashes if i play more than one song from the file manager...if i choose them via lollypop directly there's no problem but if i choose a song from the file manager and another one after it suddenly crashes

(using fedora 25 with latest gtk and latest lollypop)

**Comment by gnumdk** [comment]
Not happening here. Any output?

**Comment by legacychimera247** [comment]
so...here's the output...

`(lollypop:3359): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x5651ede5c2c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
AlbumArt::pixbuf_from_tags(): gst-resource-error-quark: URI «/home/luca247/Musica/Illusioni Sonore - Aria Sporca.mp3» non valido. (3)
 missing an album artist in artists
AlbumArt::pixbuf_from_tags(): gst-resource-error-quark: URI «/home/luca247/Musica/Illusioni Sonore - Aria Sporca.mp3» non valido. (3)
 missing an album artist in artists
Downloader::_get_album_art_lastfm: Album not found [/Unknown]
HTTP Error 400: Bad Request https://api.spotify.com/v1/search?q=&type=artist
Downloader::_get_album_art_spotify: HTTP Error 400: Bad Request [/Unknown]
Downloader::_get_album_art_lastfm: Album not found [/Unknown]
HTTP Error 400: Bad Request https://api.spotify.com/v1/search?q=&type=artist
Downloader::_get_album_art_spotify: HTTP Error 400: Bad Request [/Unknown]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/player_bin.py", line 616, in __on_stream_about_to_finish
    self.current_track.album_id))
ZeroDivisionError: division by zero`

seems that you just need to let the song finish and then lollypop closes itself...this only if the song has been selected via the file manager and not lollypop itself...

**Comment by gnumdk** [comment]
Lol, you use lollypop without any track in db????? WTF ???
BTW, will fix the issue...

**Comment by gnumdk** [comment]
Ok, send me the tracks by email, can't reproduce...

**Comment by legacychimera247** [comment]
that's the song...but anyway it happens with every song selected from nautilus and not just this one

https://jollacommunity.it/cloud/index.php/s/tyMEVMVtneJo1Xi
