### ISSUE TITLE
lollypop crashes if i close and then reopen the lyrics section

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#887]
as the title say i can open the lyrics section while listening to a song but if i close the panel and then reopen it, lollypop it suddenly crashes

(using latest gtk and lollypop on fedora 25)

**Comment by gnumdk** [comment]
Any output? Does not happen here...

**Comment by legacychimera247** [comment]
what do you mean by output?

**Comment by palob** [comment]
What it says when you start Lollypop from a Terminal window by typing ``lollypop``.

**Comment by legacychimera247** [comment]
so...opened through terminal but there aren't to much informations...here's the result

`(lollypop:3012): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x55c7194ba2c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Segmentation fault (core dump created)`

anyway to have this bug i just need to select the lyrics option then close the dialog and reopen it and it crashes with the message "a problem occurred and lollypop closed itself, the problem has been reported" or something like this (if it helps to reproduce)

**Comment by gnumdk** [comment]
So the bug is in Fedora Stack, can't do anything...
