### ISSUE TITLE
Separate section for one hit wonders

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#888]
While Lollypop mainly targets album listeners – what do you think about separating artists, of whom the user owns just very few songs? Since these tracks would not be played very often, I think the artist list would be de-cluttered. Sorting criteria could be: Maximum six songs in total && maximum three songs of the same album/single/EP. This whole section should be deactivatable for users owning just some few songs of several artists.

**Comment by gnumdk** [comment]
Sorry, wontfix, it's just your feeling but:
- Many users (and me will not like this)
- I don't want such option in Lollypop

**Comment by fbruetting** [comment]
Oh, thanks anyway. :)
