### ISSUE TITLE
Superfluos separator in song detail popover

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#889]
Here you see a separator above „next title“ while there's nothing above that could be separated.

![the killers - romeo and juliet - lollypop_003](https://cloud.githubusercontent.com/assets/10520767/21667892/feb2c90e-d2fc-11e6-94de-55e0011901b4.png)

**Comment by gnumdk** [comment]
No, you are just using a broken GTK theme... Adwaita or die ;)

**Comment by fbruetting** [comment]
Oh ok, thanks!

**Comment by tista500** [comment]
@gnumdk,

I'm an author of Adapta gtk theme, then let me know what this mean:
>  Adwaita or die ;)

**Comment by fbruetting** [comment]
🤣
