### ISSUE TITLE
GStreamer bug?

### ISSUE THREAD

**Issue by costil** [gnumdk/lollypop#89]
I upgraded to 0.9.11 from aur and erased .local/share/lollypop/lollypop.db before starting but I get

/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

(lollypop:1387): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(lollypop:1387): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(lollypop:1387): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(lollypop:1387): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
...(repeatedly)
and scanning is stuck in the middle of the library. Any suggestions?

**Comment by gnumdk** [comment]
What file types do you have?

**Comment by costil** [comment]
Mostly mp3 and flac. Some m4a and I just noticed a few wma. I guess .wma isn't supported?

**Comment by gnumdk** [comment]
Can you test with current git:
$ lollypop -d > debug.txt

and paste debug.txt here.

**Comment by costil** [comment]
Finally lollypop.db created but it took almost a day for a 14.000 tracks library. No errors in debug.txt, only about jpegs not detected as music files and a list of added files in the order of:
Adding file: /home/user/Music/Artist/Album/01 song.mp3.
If you want I can paste debug.txt.
I have another problem though. A few albums are split into 2 albums with wrong track numbers and no track length. I checked the tags and are ok, those albums where also fine in the mutagen dependency version.
![loll0911](https://cloud.githubusercontent.com/assets/12015613/7228594/60b5b184-e763-11e4-8d9c-d40550f82f1f.png)

**Comment by gnumdk** [comment]
Can you send me one track by mail? (with empty duration)

**Comment by costil** [comment]
Sure. Check your mail

**Comment by costil** [comment]
Sure. Where?

**Comment by gnumdk** [comment]
My mail is in lollypop about dialog

**Comment by gnumdk** [comment]
Seems to be a gstreamer bug... Here on Debian sid, it works as wanted.

**Comment by gnumdk** [comment]
What is your distribution?

**Comment by costil** [comment]
Arch. 
https://www.archlinux.org/packages/?q=gst
lollypop-git

**Comment by gnumdk** [comment]
The only distribution i can't test :-(

Are you sure you have gst-libav installed?

**Comment by costil** [comment]
Yes.

**Comment by costil** [comment]
I'm gonna downgrade some packages and see

**Comment by costil** [comment]
No solution so far

**Comment by gnumdk** [comment]
Will give a look,  got a arch/xbmc laptop under my tv...

**Comment by gnumdk** [comment]
Does rhythmbox able to read tags?

**Comment by costil** [comment]
Rhythmbox reads tags same as Lollypop, with errors in the same albums. Maybe a problem with the tags or the files. I'll try refresh tags. In Banshee, Audacious or Easytag these albums seem ok though...

**Comment by gnumdk** [comment]
I think your gstreamer installation is broken... Tested on archlinux with your file and it's working.
