### ISSUE TITLE
lollypop crashes on exit

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#891]
when i close lollypop i receive a message that lollypop is crashed...that's not so important since i'm closing the program but i thought to report it...that's the code...

`(lollypop:2030): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x564e46e682c0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/application.py", line 269, in prepare_to_exit
    self.charts.stop()
AttributeError: 'NoneType' object has no attribute 'stop'`

using fedora 25 with latest lollypop and gtk

**Comment by geordieF** [comment]
Don't worry about this, I haven't checked the code but what probably is happening is there is a function which recursively calls `stop()` on everything, and something like an array or a dictionary has had `stop()` called on this, throwing an error. It's just a Gtk-WARNING, so nothing fatal is happening. Most stable apps have a few of these scattered around.

**Comment by bil-elmoussaoui** [comment]
@geordieF what makes you say that? Gtk;Warning has nothing to do with the exception AttributeError ;)

**Comment by geordieF** [comment]
@bil-elmoussaoui your right, I'm just an idiot and not realising that it wasn't a multiline code block :facepalm:
