### ISSUE TITLE
order artist in alphabetical order in devices view

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#893]
lollypop has the ability to sync with mobile devices and while this is good it could be inconvenient when you have lots of albums...would be nice to have at least artist sorted in an alphabetical way so it will be easier to sync devices...

**Comment by gnumdk** [comment]
Can't understand your issue, here albums are sorted alphabetically.

**Comment by gnumdk** [comment]
![mtp](https://cloud.githubusercontent.com/assets/3918824/21743518/10bf1662-d504-11e6-9c3b-15025495a727.png)

**Comment by legacychimera247** [comment]
yes...i mean that if you have tons of albums it might get inconvenient to sync a phone/mobile device that way...would be nice to have a list where to select artist sorted in an alphabetical way and then the alphabetical list for albums...one might get lost with only the album list...

**Comment by legacychimera247** [comment]
yes...i mean that if you have tons of albums it might get inconvenient to sync a phone/mobile device that way...would be nice to have a list where to select artist sorted in an alphabetical way and then the alphabetical list for albums...one might get lost with only the album list...
