### ISSUE TITLE
Loved tracks are lost when tags are updated

### ISSUE THREAD

**Issue by Gert-dev** [gnumdk/lollypop#896]
• Lollypop version: 0.9.223
• Gtk Version: 3.22.6
• Linux distribution: Arch Linux 64-bit

Hello

It appears that the "loved" status of tracks is lost when their tags are updated and the collection is updated. This happens even if seemingly "unimportant" tags are updated such as comment tags or the composer.

I've been updating bulk parts of a collection recently, only to find out that now a lot of my favorites are no longer marked as such. I still have a back-up of the favorites database, so all is not lost. Still, it feels as if this shouldn't be happening as the file itself wasn't renamed, so Lollypop should still be able to see it as the same "file ID". (If the file itself is renamed, I can understand that it's hard to know where the it went and would see that as an acceptable loss of loved status.)

Steps to reproduce for due dilligence:

1. Create a test file with some test tag data so you can find it in your collection.
2. Rescan your collection in Lollypop.
3. Search the file in your collection, mark it as favorite (loved).
4. Update the tags of the test file (via easytag, exfalso, or another tag editor).
5. Rescan your collection in Lollypop.
6. The song will temporarily disappear from your collection and then reappear as it is readded. The loved status is now removed.

Thanks in advance

**Comment by Gert-dev** [comment]
Thanks for applying a fix. Is this fix included in 0.9.224? I can still reproduce the issue with a test file there.

**Comment by gnumdk** [comment]
No, you need 0.9.226

**Comment by Gert-dev** [comment]
👍 will report back if I still experience the issue after updating.
