### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by sandman9988** [gnumdk/lollypop#897]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.223
• Gtk Version: libgtk-3-0:amd 3.20.9-1ubun amd64        
                       libgtk2.0-0:am 2.24.30-4ubu amd64 
• Linux distribution: Ubuntu 16.10

Ehancements:

1. Ability to select Album Artist as default sort order view "All artists".
2. Ability to select newest/oldest album year (on top) as default sort order view "Artist/Album".

General:

1. I assume that "The charts" is a work in progress?

Thank you for this project!

**Comment by gnumdk** [comment]
1. Lollypop only show album artist in "All artist"
2. Sorry, will not.
No, chars is not work in progress.

**Comment by sandman9988** [comment]
Hi,

1. It defaults to Sort Artist not Album Artist field as shown in this screen shot. (My music collection is tagged with Beets and MusicBrainz).

2. I respect your choices as the developer but would like to point out that when you have a large collection from a single artist you have to scroll pages down every time to get to their newest / latest album if the title is something like "Ultimate Sinatra". This album was released in 2015 but in Lollypop I have to scroll 77 albums down to find it in the Artist/Album view (which is alphabetical). For what it's worth it could be a switch in Preferences?

Thank you for your time.

![lollypop_001](https://cloud.githubusercontent.com/assets/25001155/21763719/fa5f762c-d667-11e6-98b5-90ac05e6594b.png)

**Comment by gnumdk** [comment]
What should I see in this screenshot?

**Comment by gnumdk** [comment]
@sandman9988 ping?
