### ISSUE TITLE
Reset database doesn't delete missing albums

### ISSUE THREAD

**Issue by tactualjota** [gnumdk/lollypop#898]
BUG MAY BE REJECTED IF MISSING:
• Lollypop version:  0.9.223-1ppa1ubuntu1.1
• Gtk Version: dpkg -l libgtk2.0-0 libgtk-3-0
• Linux distribution: ubuntu dpkg -l libgtk2.0-0 libgtk-3-0

I've changed my music collection location and did a reset database on lollypop. The update music detects the new location correctly and adds the albums, but there are some albums (that are not in the new collection) that remain in the database and crash the application.

A simple fix is to manually delete the database, but I don't know where it is located. I've tried to look under ~/.config  and did an "apt purge" but the issue still remains.

**Comment by julianrichen** [comment]
https://github.com/gnumdk/lollypop/blob/eb5c40ee2e6c7956af503c6a109cbb846a973a35/src/database.py#L30

Should be:
```
~/.local/share/lollypop
```

**Comment by gnumdk** [comment]
@julianrichen No, reread the code ;)

**Comment by gnumdk** [comment]
@tactualjota Have you removed the previous location from collection? Lollypop ignore empty dirs...

**Comment by tactualjota** [comment]
I did remove the previous location from the collection. But I simple rm -rf ./local/share/lollypop solved the issue and the database populated correctly. Thank you for your help!

**Comment by gnumdk** [comment]
Reopen to check if there is a bug...

**Comment by gnumdk** [comment]
Works here
