### ISSUE TITLE
Manual music changing notification

### ISSUE THREAD

**Issue by Djaler** [gnumdk/lollypop#899]
• Lollypop version: 0.9.223
• Gtk Version: 3.18.9
• Linux distribution: elementary OS Loki

When I controll Lollypop from sound indicator, notification bubble blocking controls. I think notification should not appear when manually changing tracks.

**Comment by CatWhoCode** [comment]
I have the same trouble, and i'll be happy if this proposal will be applied.

**Comment by gnumdk** [comment]
Elementary issue I think...

**Comment by gnumdk** [comment]
Notifications bubble does not appear when changing tracks with MPRIS: tested in GNOME Shell and Unity.
https://github.com/gnumdk/lollypop/blob/master/src/mpris.py#L185

Can you provide a screencast?

**Comment by Djaler** [comment]
> Can you provide a screencast?
https://youtu.be/cTUCVhB157Y

**Comment by Djaler** [comment]
Can you please update package in ubuntu ppa with new fixes?
