### ISSUE TITLE
kid3-cli is not detected on Arch

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#902]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.244
• Gtk Version: 3.22
• Linux distribution: Archlinux with gnome 3.22.2
• kid3-cli version : 3.4.4

Kid3-cli is not detected by Lollypop even if the result of `cd /usr/bin && ls | grep kid3-cli` shows that it exists
![capture du 2017-01-12 05-36-12](https://cloud.githubusercontent.com/assets/7660997/21877107/0a7dc266-d889-11e6-90c5-3d08acc6845a.png)

![capture du 2017-01-12 05-33-35](https://cloud.githubusercontent.com/assets/7660997/21877054/b11f9230-d888-11e6-9e5c-aff6c2f90ad7.png)

**Comment by bil-elmoussaoui** [comment]
Ok by checking the source code it seems that i need lollypop-portal, installed from source and everything works fine! i think this should be included within the package by default ;)
Closing

**Comment by gnumdk** [comment]
Please report bug to archlinux packager ;)

**Comment by bil-elmoussaoui** [comment]
It's already reported ;) thanks!
