### ISSUE TITLE
Use Headerbar with Gtk.Stack instead of Gtk.NoteBook 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/lollypop#903]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:

• Lollypop version: 0.9.244
• Gtk Version: 3.22
• Linux distribution: Archlinux with gnome 3.22.2
How settings look right now
![capture du 2017-01-12 05-39-08](https://cloud.githubusercontent.com/assets/7660997/21877173/83601ea4-d889-11e6-909b-3eeb5cb058e3.png)

How it can look like using Gtk.Stack with Gtk.Headerbar 

![capture du 2017-01-12 05-39-28](https://cloud.githubusercontent.com/assets/7660997/21877172/835d81bc-d889-11e6-87bf-0dee94483247.png)
I know that it does not respect Gnome HIG, but it looks so much better ;) anyway it's up to you to decide, i can create a PR if you wish ;)

**Comment by gnumdk** [comment]
Looks cool, but lollypop does not use header bar on Ubuntu for example... Don't want to maintain two interfaces.
