### ISSUE TITLE
Open app from sound indicator

### ISSUE THREAD

**Issue by Djaler** [gnumdk/lollypop#904]
• Lollypop version: 0.9.223
• Gtk Version: 3.18.9
• Linux distribution: elementary OS Loki

If Lollypop doesn't launched and I click on it's row in sound indicator, it starts. But if it currently launched, I cannot open Lollypop window by pressing on it's row in sound indicator.

**Comment by gnumdk** [comment]
Wanted by feature, Lollypop doesn't raise when already launched (Really dislike this).

But Loki sound indicator is broken, when application is already launched, it should call "Raise" MPRIS function (like does GNOME Shell indicator)

Report upstream.

**Comment by Djaler** [comment]
Hmm, but with Quod Libet player it works.

**Comment by gnumdk** [comment]
Because Quod Libet raises when calling quodlibet command... But Loki indicator is wrong, there is a raise command that should be used.
