### ISSUE TITLE
embed cover art in music files instead of separate jpg

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#906]
it's good we can look the web for album covers but since some players and tag editors embed the cover in the file it would be nice if lollypop could do that too, so 1 we would see the cover art even in the file manager instead of having cover files here and there and 2 i don't have to delete cover files from gallery every time i sync my phone :)

**Comment by bil-elmoussaoui** [comment]
@legacychimera247 You can do that too ;) just install kid3-cli and it will be done by Lollypop ;)

**Comment by gnumdk** [comment]
You need to install kid3-cli and lollypop-portal package.

**Comment by legacychimera247** [comment]
thanks...i wil try :)
