### ISSUE TITLE
Nothing is played

### ISSUE THREAD

**Issue by Djaler** [gnumdk/lollypop#907]
• Lollypop version: 0.9.226
• Gtk Version: 3.18.9
• Linux distribution: elementary OS Loki

I update to 0.9.226 and now see this in my sound indicator.
It's translated as "Music player. Nothing is played"
![2017-01-14 02-11-32](https://cloud.githubusercontent.com/assets/7964583/21948856/d22eab42-d9fe-11e6-994b-d7d1b587fc2f.png)

But controls works well

**Comment by scde** [comment]
Same problem here (0.9.226 (from your ppa) - Ubuntu-Gnome 16.04 with [_Media player indicator_](https://extensions.gnome.org/extension/55/media-player-indicator/)).
The track information does not seem to be broadcast properly. I can't control seeking and there is no media data (artist, track, cover art, etc) displayed in _Media player indicator_ but play/pause/stop/next/prev/volume control works.

**Comment by gnumdk** [comment]
Maybe related to #899
