### ISSUE TITLE
Charts redesign

### ISSUE THREAD

**Issue by anonimo1w** [gnumdk/lollypop#912]
Other day I was debugging and noticed the link to the iTunes rss chart, it was downloading/updating the Jazz Top Albums. 

This could be used to sort the charts? Instead of show all the albums of all the charts (with a aproach resembling "popular albums") maybe it could use the approach of genre (firstly choosing the genre or all albums, then select the artist) or playlists (starting with the choose of a playlist, then choosing a song). Also, showing the icon of the source of playlist at the side of the title. So, as example:

> Top 40 Jazz Albums (iTunes icon)
> Top xx Genre Albums (iTunes icon)
> ...
> Weekly top [by country] (spotify icon)
> Playlist generated (spotify icon)

**Comment by gnumdk** [comment]
You can follow my work in charts branch.

**Comment by gnumdk** [comment]
Backup ~/.local/share/lollypop/lollypop.db before testing ;)

**Comment by anonimo1w** [comment]
The sorting design is quite good, but for now i saw some (possible) issues:
- Some artists are inserted automatically on the "All artists" (previously just the clicked ones would do that). Happens only if i click on one of the charts.
- Not appeared too much albums (the url used on --debug was [that](https://itunes.apple.com/BR/rss/topalbums/limit=40/json) but appeared just 17 albums in 5 or 6 categories) maybe this is somewhat related to the first issue?
- Some albums didn't show  (a album from "Bruno e Marrone", a Sertanejo's duo)
- Some genres didn't show ("Pagode" for example)
- Maybe, on preferences for example, could be possible to select the country someone want.. Truth be said, I don't like too much my country's taste for music :P 

For now this is what spotted my attention. And thanks for implementing this idea ;)

**Comment by gnumdk** [comment]
>Some artists are inserted automatically on the "All artists" (previously just the clicked ones would do that)

Don't understand this one.

**Comment by gnumdk** [comment]
Ok, will work on this later (but soon), Charts really need a separated DB now.

**Comment by anonimo1w** [comment]
> Some artists are inserted automatically on the "All artists" (previously just the clicked ones would do that)

On the last stable version if you click on charts, any album will open it's song list without being added to the db.
If you search on the web for a given album or song it will be added to the db and if the artist is not created yet, it'll be created.

In the [last version i tested](https://github.com/gnumdk/lollypop/tree/71410b38366a00f33dd455af928d14db85bc36b6) and could use the charts, anytime i clicked on it any artists' song there would have the same behavior as if it have been searched.

**Comment by gnumdk** [comment]
>any album will open it's song list without being added to the db.

All albums visibles in Lollypop are in the db, since first release... Please update git, I just merged to master.

**Comment by gnumdk** [comment]
Closing this one at it's done and in master... Open new issue if you find bugs.
