### ISSUE TITLE
Updating huge library is very slow

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#915]
I have a big library (lollypop.db is 14MB) on an external hard drive. When I add a new album to the drive and update the library in Lollypop, it takes several minutes before Lollypop finishes scanning and adds the album. When I do this in https://github.com/quodlibet/quodlibet, it only takes a few seconds.

I don't know the differences between how Lollypop and Quod Libet scan for changes, but it would be great if updating an existing library in Lollypop could be made faster.

**Comment by gnumdk** [comment]
Rescan in quodlibet only update new files, it does not check for modification. 
Rebuild does like Lollypop but here is much slower (and should not as Quodlibet is using mutagen: faster than gstreamer)
