### ISSUE TITLE
not showing music info in sound applet after latest update

### ISSUE THREAD

**Issue by el-gigantor** [gnumdk/lollypop#916]
• Lollypop 0.9.226
• GTK 3.18.9
• Linux Mint 18.1 Cinnamon

Since 0.9.226 update, sound info is no longer showing in sound applet in panel.  was working fine in 0.9.225.  it now show "UNKNOWN TITLE - UNKNOWN ARTIST.  i can control the player with no issues using the applet.

**Comment by el-gigantor** [comment]
not working in CoverGloobus either..

**Comment by gnumdk** [comment]
Duplicate
