### ISSUE TITLE
Lollypop in Ubuntu sound indicator applet

### ISSUE THREAD

**Issue by MakisH** [gnumdk/lollypop#919]
• Lollypop version: 0.9.227

• Gtk Version: 
$ apt-cache policy libgtk2.0-0 libgtk-3-0
libgtk2.0-0:
  Installed: 2.24.30-1ubuntu1
  Candidate: 2.24.30-1ubuntu1
  Version table:
 *** 2.24.30-1ubuntu1 500
        500 http://ftp.uni-stuttgart.de/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
libgtk-3-0:
  Installed: 3.18.9-1ubuntu3.1
  Candidate: 3.18.9-1ubuntu3.1
  Version table:
 *** 3.18.9-1ubuntu3.1 500
        500 http://ftp.uni-stuttgart.de/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.18.9-1ubuntu3 500
        500 http://ftp.uni-stuttgart.de/ubuntu xenial/main amd64 Packages

• Linux distribution: Ubuntu 16.04.1

**BUG DESCRIPTION:** I can't see Lollypop in the Ubuntu sound indicator applet (sound menu). From [#753](https://github.com/gnumdk/lollypop/issues/753) though I understand that I should see it in the sound menu.

**Comment by gnumdk** [comment]
Anything on command line output? Here it works on Ubuntu 16.04...

**Comment by MakisH** [comment]
If I run it from the terminal I get:

`/usr/lib/python3/dist-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3/dist-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3/dist-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Disabling GVFS http module: https://bugzilla.gnome.org/show_bug.cgi?id=775600
`
But normally I should be able to see an entry in the sound menu (up-right, next to the language, wi-fi etc) even without opening it. So, you say it is normally supported?

**Comment by gnumdk** [comment]
Yes, works on my Ubuntu 16.04 laptop.

**Comment by gnumdk** [comment]
Not sure if related.
Can you test git version? Build instruction (Debian) here: https://github.com/gnumdk/lollypop

**Comment by gnumdk** [comment]
Ok, I confirm it's fixed by last commit.

**Comment by MakisH** [comment]
Three observations:
1. I installed it again using the **"add repository" method** for ubuntu on a fresh Ubuntu 16.04 on a Virtual Machine and it had the same problem. I noticed (using the dconf-editor) that the installation didn't add anything in the com.canonical.indicator.sound (interested-media-players).

2.  On my main system, I removed and installed it again **from source, using the `sudo make install`** command. Again, it didn't help, plus it didn't add an entry in the Ubuntu applications menu.

3. In both my main system and the VM, I removed and installed again **from source, using the `sudo checkinstall`** command. **This worked!** After I started Lollypop, I got an entry in the sound menu. I saw that it added the element `'org.gnome.Lollypop.desktop'` in the `interested-media-players`.

Do you confirm the problem? Although I like that it got fixed, I would like to have it installed via the repository, so that I get updates.

**Comment by gnumdk** [comment]
Package has been just updated ;)
