### ISSUE TITLE
Improvement: Ditch libnotify

### ISSUE THREAD

**Issue by JasonLG1979** [gnumdk/lollypop#922]
A shameless plug on my part. But I wrote a stupid simple pure PyGObject asynchronous desktop notification module that would allow you to ditch libnotify. Thought you might want to check it out. We just recently implemented it in Pithos.

https://github.com/JasonLG1979/possibly-useful-scraps/wiki/GioNotify
 https://github.com/JasonLG1979/possibly-useful-scraps/blob/master/GioNotify.py

Edit: Judging by a quick look at your current notification implementation it should vastly simplify things as it's non-blocking, and you wouldn't need to clear and reset your hints at every notification. If you used a image uri or icon name you don't need to set a hint for the image or if you did still use the hint you can clear and/or overwrite specific hints in my module without clearing them all.

**Comment by gnumdk** [comment]
Why should I ditch libnotify? It's part of GNOME...

**Comment by JasonLG1979** [comment]
Becides what I've already mentioned...

**Comment by JasonLG1979** [comment]
Look at the libnotify source code. All the I/O is blocking. Blocking I/O is not your friend.

**Comment by JasonLG1979** [comment]
My module is basically a PyGObject re-implementation of libnotify with non-blocking I/O.

**Comment by gnumdk** [comment]
It's cool but doesn't support update()
Too hard to make libnotify non blocking without breaking API?

**Comment by JasonLG1979** [comment]
You can't make libNotify no-blocking. That's the way it written. Update is a function in libNotify internally it just sends a new notification.

**Comment by JasonLG1979** [comment]
The best you can do with libNotify is send it through a GLib.idle_add

**Comment by JasonLG1979** [comment]
LibNotify is just an shim to the dbus notification interface

**Comment by JasonLG1979** [comment]
> without breaking API?

My module has nothing to do with libnotify except for the fact that it's a replacement for it. You could use my module on a system without libnotify installed. As such I was/am free to define my own API. Much of it is the same as the libnotify bindings because it made sense.

**Comment by JasonLG1979** [comment]
A quick example.
https://gist.github.com/JasonLG1979/8cca915c59e7a1969fd4e8129fc4e285

This does no blocking I/0. Everything is asynchronous.

**Comment by sljunkie** [comment]
From a modern GNOME user perspective (3.20 and 3.22) only MPRIS2 support is enough because the music playback gets integrated in the notification area.

**Comment by JasonLG1979** [comment]
> From a modern GNOME user perspective (3.20 and 3.22) only MPRIS2 support is enough because the music playback gets integrated in the notification area.

Not everyone uses GNOME. And admittedly the value of notifications at song changes is is debatable. MPRIS is not a replacement for notifications. They serve different functions.

**Comment by JasonLG1979** [comment]
In any event if you're going to have notifications at all my module is superior to the libnotify bindings.

**Comment by JasonLG1979** [comment]
Basic overview of abstraction:
libnotify bindings - 
PyGobject(python bindings)
....libnotify(C)
........GDBusProxy(C)
............DBus

GioNotify - 
....PyGobject(python bindings)
........GDBusProxy(C)
............DBus
