### ISSUE TITLE
Clicking on Lollypop in the Ubuntu sound menu doesn't restore the window

### ISSUE THREAD

**Issue by MakisH** [gnumdk/lollypop#923]
• Lollypop version: 0.9.228

• Gtk Version: 
$ apt-cache policy libgtk2.0-0 libgtk-3-0
libgtk2.0-0:
  Installed: 2.24.30-1ubuntu1
  Candidate: 2.24.30-1ubuntu1
  Version table:
 *** 2.24.30-1ubuntu1 500
        500 http://ftp.uni-stuttgart.de/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
libgtk-3-0:
  Installed: 3.18.9-1ubuntu3.1
  Candidate: 3.18.9-1ubuntu3.1
  Version table:
 *** 3.18.9-1ubuntu3.1 500
        500 http://ftp.uni-stuttgart.de/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.18.9-1ubuntu3 500
        500 http://ftp.uni-stuttgart.de/ubuntu xenial/main amd64 Packages

• Linux distribution: Ubuntu 16.04.1

**BUG DESCRIPTION:** In the Ubuntu sound indicator applet (sound menu), clicking Lollypop when it is closed starts it (normal behavior). But when it is already open OR it is closed with the music still playing, clicking on the sound menu entry doesn't restore/focus the window.

The main problem is when it is closed with the music still playing. A workaround would be to pin it to my Unity Launcher, but I would like to avoid it.

An example where this works like this is e.g. Banshee.

**Comment by gnumdk** [comment]
Ubuntu indicator applet should use the MPRIS raise function... Bug is not in lollypop...

**Comment by gnumdk** [comment]
Added a workaround but please report this to Ubuntu devs...
