### ISSUE TITLE
"This appears to be a text file" notification

### ISSUE THREAD

**Issue by michael-rapp** [gnumdk/lollypop#924]
When I update my music library in Lollypop, the notification "This appears to be a text file" pops up. There is no information given, to which file the notification refers to. How can I find out, which file is causing this message to be shown? It is kind of annoying to see this everytime Lollypop starts.

In my opinion this kind of notification can be omitted at all. The error doesn't seem important enough to show a system-wide notification to me. Furthermore, the lack of information, which is currently given, might confuse the user, because there is no hint about what actually went wrong and how to avoid that in the future.

By the way, I tried to disable notifications for Lollypop entirely in Gnome's notification settings, but there is no such entry. I am sure, that it was once there. Is this intended or a bug/configuration issue?

• Lollypop version: 0.9.226
• Gtk Version: 3.22.7
• Linux distribution: Arch

**Comment by gnumdk** [comment]
>Is this intended or a bug/configuration issue?
Here it works...

**Comment by michael-rapp** [comment]
Okay, but you didn't answer how I can find out, what's causing the notification to be shown...!?

**Comment by gnumdk** [comment]
Just update lollypop to current master, it will tell you what file is causing the error.
