### ISSUE TITLE
State isn't saved when shutdown

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#926]
I nearly always use random mode. When I shut down my machine without closing Lollypop explicitly, Lollypop next time starts with the same song as it started (not quit) before. Could you please save the state when SIGTERM is received?

**Comment by gnumdk** [comment]
Doesn't work, SIGTERM is emited but lollypop is killed before properly exiting.

**Comment by fbruetting** [comment]
Thanks for your work!
