### ISSUE TITLE
transfer file to device not working with m4a files

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#928]
as the title says lollypop is not able to sync m4a files to my Jolla device unless i select the convert to mp3 option...this is the terminal output

`MtpSync::_retry(gi.FunctionInfo(copy), (<lio.File object at 0x7f8743137ab0 (GDaemonFile at 0x7f87500146d0)>, <flags G_FILE_COPY_OVERWRITE of type Gio.FileCopyFlags>, None, None)): g-io-error-quark: Errore libtmp:  Could not send object. (0)
mtp://[usb:001,007]/SD%20Card/Music/fear%20factory_demanufacture/1484817222_Disc%201%20-%2001%20-%20Demanufacture.m4a`

other to that i can stop the process only by unplugging my device as exiting sync is not possible and exiting lollypop hang the program
obviously my device support m4a and i have no problems at all with mp3 format...

this using latest lollypop in fedora 25 and latest gtk

**Comment by gnumdk** [comment]
Not a Lollypop bug... Issue is un gvfs... Sorry...

**Comment by legacychimera247** [comment]
so there's no way to fix it?
