### ISSUE TITLE
Unrating not possible by Media Player Indicator

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#930]
If I click the second time on the rating, the song already has, stars get deleted in MPI, but not in Lollypop.

**Comment by gnumdk** [comment]
Bug is in Media Player Indicator I think... It just launch "lollypop" without option when cliking the second time:
method call time=1484894229.647132 sender=:1.221 -> destination=org.gnome.Lollypop serial=18 path=/org/gnome/Lollypop; interface=org.gtk.Application; member=CommandLine
   object path "/org/gtk/Application/CommandLine"
   array [
      array of bytes "/usr/local/bin/lollypop" + \0
   ]
   array [
      dict entry(
         string "cwd"
         variant             array of bytes "/home/gnumdk" + \0
      )
      dict entry(
         string "options"
         variant             array [
            ]
      )
   ]

**Comment by JasonLG1979** [comment]
Nope. @gnumdk ```lollypop --set-rating=0``` has no effect on the rating. Even if it did Lollypop doesn't emit a metada prop changed signal over mpris to let us know the rating has changed anyway...

**Comment by JasonLG1979** [comment]
@gnumdk a better option is a ratings extension to the actual MPRIS interface. It would not have to be complicated at all.

```
        <interface name="org.mpris.MediaPlayer2.ExtensionRatings">
            <method name="SetRating">
                <arg direction="in" name="TrackId" type="o"/>
                <arg direction="in" name="Rating" type="d"/>
            </method>
            <property name="HasRatingExtension" type="b" access="read" />
        </interface>

```

HasRatingExtension would ofc always return true. It's useful for me to tell if the interface exists.The only way to tell if a DBus interface actually exists is to try to get a prop from it. 

According to:
https://lists.freedesktop.org/archives/mpris/2012q4/000054.html

Extending the mpris player object is fine, especially for such a glaring omission as setting ratings.

**Comment by gnumdk** [comment]
lollypop --set-rating=0 is a hack used by Gnome Shell MPRIS extension.

**Comment by JasonLG1979** [comment]
> lollypop --set-rating=0 is a hack used by Gnome Shell MPRIS extension.

It's not a hack. How else would you set the rating to Zero?

**Comment by JasonLG1979** [comment]
A rating of 0 is a legitimate rating value.

**Comment by JasonLG1979** [comment]
@gnumdk I still like the idea of a ratings MPRIS interface. Since it would take a TrackId it's also future proof. So at some point if you add the TrackList interface songs in the TrackList can also be rated, not just the current song.

I implemented a similar ratings interface in Pithos(we have a complete MPRIS implementation that I wrote most of) And you I added support for it in the mediaplayer extension so you can rate song in the current tracklist.

I could put in a PR for the ratings interface and add support for it in the mediaplayer extension if you'd like?

**Comment by JasonLG1979** [comment]
Here's what a tracklist with ratings support with Pithos looks like in the mediaplayer extension.

It's pretty handy. You don't even need to open the main Pithos interface unless you need to change a setting really.

![screenshot from 2017-07-18 01-54-32](https://user-images.githubusercontent.com/6667703/28304220-3fece86c-6b5c-11e7-9c7f-e7d0e322ea4a.png)

**Comment by fbruetting** [comment]
Thanks a lot for reviving this!

**Comment by JasonLG1979** [comment]
This can be closed @gnumdk ratings now work as they should.
