### ISSUE TITLE
Kid3-cli not seen by Lollypop

### ISSUE THREAD

**Issue by Dark-Witcher** [gnumdk/lollypop#933]
BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.228
• Gtk Version: libgtk2 - 2.24.30 libgtk3-3.18.9
• Linux distribution: Linux Mint Cinnamon 18.1 64bit.

I've installed kid3-cli but lollypop doesn't see it.

**Comment by gnumdk** [comment]
You need to install lollypop-portal!
