### ISSUE TITLE
Lollypop isn't giving audio output

### ISSUE THREAD

**Issue by GokulSoumya** [gnumdk/lollypop#935]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.228
• Gtk Version: 2.24.30-1ubuntu1
              and   3.18.9-1ubuntu3.1

• Linux distribution: Lubuntu 16.04 LTS

<Describe your bug here>
Lollypop is not playing music. The progress bar goes on, but I can't hear anything(checked volume and all, though).

Get this message when `lollypop -d` commmand is executed in terminal :

gokul@gokul-laptop:~$ lollypop -d

** (lollypop:2830): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

**Comment by gnumdk** [comment]
Sorry, this is not a forum, go to Ubuntu Forum...
