### ISSUE TITLE
Summon tag edition software from within Lollypop

### ISSUE THREAD

**Issue by mateff** [gnumdk/lollypop#936]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.228
• Gtk Version: 3.18.9-1ubuntu3.1
• Linux distribution: Ubuntu 16.04

Hi Cédric,

The button to edit tags in files seems to have been removed.
I used and loved that function a lot, is it a bug, temporary, intentional ?

I think Lollypop's collection system demands a very organised library,
to me this possibility of summoning external software like ex falso is then a must have.

Thank you a lot for your work!
matef

**Comment by gnumdk** [comment]
You nées lollypop-portal

**Comment by mateff** [comment]
Thank you!

**Comment by JuanCAlpizar** [comment]
@gnumdk I have lollypop-portal installed from github repo and lollypop from Arch AUR package https://aur.archlinux.org/packages/lollypop-git but I don't see the edit tags button, where is it located at? I'm new at lollypop so I may just be missing it
