### ISSUE TITLE
charts on master don't show progress

### ISSUE THREAD

**Issue by anonimo1w** [gnumdk/lollypop#938]
Just cloned the master and tested the charts (firstly Spotify, but maybe apply to the others):
- Spotify while refreshing it charts don't show any new songs (for songs recently fetched appear is needed to click again in spotify icon)
- Maybe is just my pc but took sometime to fetch all songs from Spotify and to start the others.
- Spotify don't show any progress (for example, the number of songs already available/all songs to be available or the loadingBar used while creating/updating the main db)

As a suggestion, consider add the option to change the country used on the services

Also, thanks for the great music player :D

**Comment by gnumdk** [comment]
No updating view is normal, dont' want a jumping ui. Already tested, just sux. No progress bar too, it's a background task that doesn't require user attention.
And no I will not add an option for locale.
