### ISSUE TITLE
lollypop crashing when restoring database

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#939]
i have restored my music database with the restore option in settings, but after the process finished, lollypop crashed and i had to unistall it and delete all the files associated to lollypop to make it start again...this using latest lollypop and fedora 25 gnome with latest gtk...here's the output from terminal

`/usr/lib/python3.5/site-packages/lollypop/lio.py:13: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, Soup
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/application.py", line 186, in do_startup
    self.init()
  File "/usr/lib/python3.5/site-packages/lollypop/application.py", line 150, in init
    self.scanner = CollectionScanner()
  File "/usr/lib/python3.5/site-packages/lollypop/collectionscanner.py", line 52, in __init__
    Lp().albums.update_max_count()
  File "/usr/lib/python3.5/site-packages/lollypop/database_albums.py", line 1081, in update_max_count
    GROUP BY albums.rowid)")
sqlite3.OperationalError: no such table: albums
`

**Comment by gnumdk** [comment]
The output show a corrupted Db... Testing multiple resetting here with no error.
Next time it crash, try to get FIRST crash output from journalctl.
Thanks.
