### ISSUE TITLE
Playing collections dosn't really work

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#94]
When I start playing a song from some colletion, it play the same song again and again,
never go forward to the next song in the collection.

**Comment by gnumdk** [comment]
Sure? :) Was rewritting player so try pull again.

**Comment by yoseforb** [comment]
Just back works for me, next dosn't.
Also trying to back from the first song cause a crash:
File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 82, in prev
    track_id = LinearPlayer.prev(self)
  File "/usr/lib/python3.4/site-packages/lollypop/player_linear.py", line 64, in prev
    pos = self._albums.index(self.current.album_id)
ValueError: 66 is not in list

I pull, of course…

**Comment by gnumdk** [comment]
Here, next is working as expected.
Prev issue fixed.

**Comment by gnumdk** [comment]
Can't reproduce on Ubuntu/Fedora/Debian... Can you give me more informations?
- Shuffle status
- Playing from?

**Comment by yoseforb** [comment]
OK, I found it.
When I start playing some song from some Compilation from the Compilations in the sidebar (below the All albums), the Next button (in the headerbar and in the keyboard) dosn't work at all.

When I start playing some song from some Compilation from 'Recent Albums', the next button in the headerbar and in the keyboard works as expected.

**Comment by gnumdk** [comment]
Ok, i confirm...

**Comment by yoseforb** [comment]
Thanks!
