### ISSUE TITLE
ValueError: Namespace GstAudio not available

### ISSUE THREAD

**Issue by mikeanthonywild** [gnumdk/lollypop#942]
• Lollypop version: Git latest (0.9.229?)
• Gtk Version: 3.14
• Linux distribution: elementary OS 0.3 (based on Ubuntu 14.04)

Not so much a bug, but more of a support request (sorry if this is the wrong place). I'm trying to troubleshoot someone who is building Lollypop - the compile is successful but they get a runtime error of *ValueError: Namespace GstAudio not available*. I suspect they are missing a Gstreamer-related dependency but I'm not sure which one. My best guess is [gir1.2-gst-plugins-base-0.1](gir1.2-gst-plugins-base-0.10).

Any help would be appreciated.

Thanks.

**Comment by gnumdk** [comment]
Sorry, Ubuntu 14.04 is not supported. But build is explained on github page. Works on Debian stable.
