### ISSUE TITLE
Some imported music is listed in the "Recently Added" tab, but not in "All Albums"

### ISSUE THREAD

**Issue by steve80289** [gnumdk/lollypop#943]
• Lollypop version: 0.9.226-1.fc25
• Gtk3 Version: 3.22.7-1.fc25
• Linux distribution: Fedora 25

I am having an issue after trying to import all of my music for the first time. I was playing a song and my computer crashed due to a kernel issue or a impending hardware failure. I am thinking that the music data was not fully imported at this time, but I am not sure. After restarting and opening lollypop, some of my imported music is listed in the "Recently Added" tab, but not in "All Albums". I tried reinstalling the package and resetting the database, but this did not work. Any suggestions?  

Edit: I figured out what may have happened. Because some of the artists had one or two songs that were labeled with other artists, the albums were categorized as a compilation and were not included in the "All Albums" area. Example: While(1<2) by Deadmau5 has one song labeled with another artist. I am not sure why these are not included under "All Albums" though.

**Comment by gnumdk** [comment]
There is an option for that :p Go to settings!
