### ISSUE TITLE
feature request : control keybinds

### ISSUE THREAD

**Issue by eoli3n** [gnumdk/lollypop#945]
Great player !!
I come from mpd, and it would be great to be able to control lollypop with external keybinds

I see that there is a ``lollypop-cli``
I expected something like

```
lollypop-cli [toggle|play|pause|stop|next|prev|mute|unmute]
```

I'm really interresting in ``toggle`` ``prev`` and ``next`` which i keybinded in my i3wm conf with mpd

Something to print the current play would be great too, maybe as

```
lollypop-cli show
```

**Comment by gnumdk** [comment]
Just use MPRIS and dbus-send or directly: https://github.com/swarminglogic/mpris-ctrl/
