### ISSUE TITLE
genre list items overlapping on mous over

### ISSUE THREAD

**Issue by madtel** [gnumdk/lollypop#946]
• Lollypop version: 0.9.229
• Gtk Version: 3.20.9-1ubuntu2
• Linux distribution: Ubuntu 16.10

When passing mouse pointer over genre list the items on the list overlap.
Issue is clearly visible in the screenshot at the following link:
https://postimg.org/image/8nc80pp2n/

**Comment by gnumdk** [comment]
It's a GTK bug, can't fix that. I think it only happend with Ubuntu default theme.

**Comment by madtel** [comment]
ok, thanks :)
