### ISSUE TITLE
supports remote control app

### ISSUE THREAD

**Issue by AndresEGonzalez** [gnumdk/lollypop#949]
Lollypop support remote controls applications??

Here some examples for another music players:
http://askubuntu.com/questions/643571/music-control-with-android-and-ubuntu-desktop

A,

**Comment by gnumdk** [comment]
Lollypop already had MPD support but was too buggy (and MPD protocol just sucks). But maybe Kodi, one day ;)

**Comment by gnumdk** [comment]
https://pypi.python.org/pypi/kodi-json/

**Comment by gnumdk** [comment]
BTW, You should be able to do this with KDE-Connect... But I agree it sucks to install all this KDE stuff on GNOME.

**Comment by gnumdk** [comment]
https://github.com/c0decat/mpris-remote

**Comment by gnumdk** [comment]
Closing. No time to implement and Kodi doesn't seems to provide wanted API.
