### ISSUE TITLE
Crash if lacking permission to browse external storage

### ISSUE THREAD

**Issue by terencode** [gnumdk/lollypop#950]
• Lollypop version: 0.9.229
• Gtk Version: 3.22.7-2
• Linux distribution: Arch Linux

When an external drive (usb key in my case) is connected, it appears on the left navbar as expected but selecting it produces a crash if the user does not have access to it.
Lollypop shoud display an error pop-up indicating that it lacks access to the storage instead.

> GLib.Error: g-io-error-quark: Error opening directory '/media/B528-F1A1/Music': Permission denied (14)

Update: not having the music folder present produces the same behaviour.

**Comment by gnumdk** [comment]
Can't reproduce here...

**Comment by gnumdk** [comment]
Next time, include FULL backtrace...

**Comment by terencode** [comment]
Ok will do next time thanks.
