### ISSUE TITLE
Lyrics view doesn't update if the song changes while it's open

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#951]
• Lollypop version: **0.9.226-1.fc25**
• Gtk Version: **3.22.7**
• Linux distribution: **Fedora 25**

**Steps to reproduce:**
1. Start playing a song
2. Click on its album cover on top to show the pop-down info window
3. Click on the "Lyrics" tab
4. Wait until the song finishes and the next song starts playing

**Expected results:**
The content changes to show the lyrics for the new song that's just started playing

**Actual results:**
The content does not refresh, and the previous song's lyrics remain visible. To refresh them, you need to close and re-open the pop-down info window.

**Comment by gnumdk** [comment]
There is an update button with long click

**Comment by Pointedstick** [comment]
I'm not sure what you mean. I don't see any update button, and clicking-and-holding on any of the visible buttons doesn't produce an update behavior. Can you re-open this issue, since it isn't resolved or rejected?

**Comment by gnumdk** [comment]
There is a reload button in the popover
