### ISSUE TITLE
Let the contextual info pane stay visible, integrated into the main window

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#952]
• Lollypop version: **0.9.226-1.fc25**
• Gtk Version: **3.22.7**
• Linux distribution: **Fedora 25**

Right now you can click on the album art on the top to display a pop-down info window. I'd like to be able to keep this open constantly, perhaps in a pane on the side or bottom, so I can always view the lyrics for the currently-playing song. I like to have the lyrics constantly visible.

**Comment by gnumdk** [comment]
Sorry, don't want this

**Comment by Pointedstick** [comment]
🙁
