### ISSUE TITLE
Frequent crashes on Fedora 25+GNOME 3.22

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#953]
• Lollypop version: **0.9.226-1.fc25**
• Gtk Version: **3.22.7**
• Linux distribution: **Fedora 25**

Since installing Lollypop on my machine an hour ago, I've had two seemingly-identical crashes. The main UI froze up and the program crashed about 10 seconds later. You can download all the debug info (including a coredump) that Fedora collected: http://hommelscitadel.com/wp-content/uploads/2017/lollypop_debug_info.tar.xz

The crash seemed sort of random; I haven't been able to determine what I was doing when it crashed. But I'll update this issue if I figure it out.

**Comment by gnumdk** [comment]
It's an issue in Intel Driver... Can't do anything about this.

**Comment by Pointedstick** [comment]
Who should I report it to, then?

**Comment by blackjackshellac** [comment]
https://bugzilla.redhat.com/ would be a good place to start
