### ISSUE TITLE
Album Sorting by Artist & Compilations 

### ISSUE THREAD

**Issue by wxnerd** [gnumdk/lollypop#954]
• Lollypop version: 0.9.229
• Linux distribution: Linux Mint 18.1

There appears to be an issue with sorting by Artist, and the "Compilations". I am unable to view ALL artist content when viewing the specific artist, if there is a compilation. For example, I am browsing through "Artist 1" folder. I see all of their folders EXCEPT for any that are grouped in "Compilations". Using "Greatest Hits" as an example, ALL my artists with "Greatest Hits" albums are grouped in "Compilations" under ONE album. I cannot view these albums by navigating to the specific artist. 

I've noticed if there are separate artists with the same album title, they get grouped together in "Compilations" as well. They aren't even compilations. 

Please let me know if you'd like screen shots.

**Comment by gnumdk** [comment]
Your tags are broken, missing an album artist tag.

**Comment by wxnerd** [comment]
Ah, ok. You're using "Album Artist" instead of "Artist". That'll do it. Thanks for the clarification.
