### ISSUE TITLE
Add the ability to remove notifications

### ISSUE THREAD

**Issue by almet** [gnumdk/lollypop#956]
Currently, the app always shows notifications. Unless I haven't found the option to disable them, it would be a welcome addition!

Thanks for your work :)

**Comment by gnumdk** [comment]
Dconf editor

**Comment by almet** [comment]
This is a quite short answer, let me elaborate in case other people need a solution here :-1: 
)
In order to disable them, while using gnome I typed "notifications" which bring the notification center, in which I deactivated the notifications of the lollypop application.

Apparently it's possible to also disable them using dconf directly, but from the answer I cannot tell how :-)

Thanks again for your work, keep the fun going :)

**Comment by bil-elmoussaoui** [comment]
@almet Open dconf editor and go to org/gnome/Lollypop and change disable-notification from false to true ;)

**Comment by keeferrourke** [comment]
It would be nice if there was an option in the Lollypop GUI to do this. The aggressive notifications are really annoying, particularly when working.

Perhaps a toggle under Preferences > Behaviour > "Show now playing notifications?"

**Comment by gnumdk** [comment]
Dconf option is for non GNOME users, but lollypop is a GNOME player and GUI exists in gnome control center.

**Comment by almet** [comment]
Yes it exists but I was looking for something inside the player myself. When you know thats outside in gnome control center it makes sense but when you dont you look for the option in the soft without luck :-)
