### ISSUE TITLE
App crash when clicking on album image

### ISSUE THREAD

**Issue by boblaspugna** [gnumdk/lollypop#957]
• Lollypop version: 0.9.229
• Gtk Version: 3.22.7-2
• Linux distribution: archlinux

`File "/usr/lib/python3.6/site-packages/lollypop/view_artist_albums.py", line 268, in __populate
    view = ArtistAlbumsView(self.__track.artist_ids, [])
TypeError: __init__() missing 1 required positional argument: 'art_size'`

Thanks for your work.

**Comment by gnumdk** [comment]
Are you using git master?
