### ISSUE TITLE
radio not working

### ISSUE THREAD

**Issue by buginfo** [gnumdk/lollypop#958]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: arch repo lollypop 0.9.229-1
• Gtk Version: 3.22.7-2
• Linux distribution: arch - gnome shell

radio doesnt seem to work 

/usr/lib/python3.6/site-packages/lollypop/lio.py:13: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, Soup
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
WebYouTube::__get_youtube_id(): 'items'

**Comment by gnumdk** [comment]
Radio is working, ask your distro forum.
