### ISSUE TITLE
Track numbers not fetching for web music albums

### ISSUE THREAD

**Issue by dehen** [gnumdk/lollypop#959]
• Lollypop version: 0.9.228
• Gtk Version: 3.22.6
• Linux distribution: Manjaro
• youtube-dl-2017.1.31 (pip)

Amazing work. I'm new to Lollypop and it's everything I've ever wanted.

Is it supposed to fetch track numbers when it adds an album to your library from a search? It seems to be sorting tracks alphabetically, from what I understand that's the behavior when track number is missing.

For instance:
I search for "Bone Machine"
I "save into collection" the album "Tom Waits - Bone Machine"
It yields the following in my collection:
![image](https://cloud.githubusercontent.com/assets/10331141/22493191/d389b20c-e7eb-11e6-9079-0d6fc94b09d5.png)
Here's the actual track order per my google music:
![image](https://cloud.githubusercontent.com/assets/10331141/22493249/305d44f8-e7ec-11e6-915d-085738fb7c34.png)

Did I miss a step? Or is fetching the track# even intended behaviour?

**Comment by gnumdk** [comment]
Fixed in master, what a stupid bug! I was getting tracknumber from itunes/spotify but saving 0 in db 👎
