### ISSUE TITLE
list-row text-shadow doesn't get removed

### ISSUE THREAD

**Issue by horst3180** [gnumdk/lollypop#96]
Hi, I have a problem with lollypop and my GTK theme (https://github.com/horst3180/Vertex-theme).
The theme applies a text-shadow to selected list-row item. The custom `trackrowplaying` and `trackrow` classes set a different background and text-color, but they don't override any other existing properties like a text-shadow.
See here a screenshot with the custom styleclass removed.
![2](https://cloud.githubusercontent.com/assets/8473629/7332619/086046aa-eb48-11e4-94cd-1553960571ec.png)
And here without modifications.
![1](https://cloud.githubusercontent.com/assets/8473629/7332625/1e5aea1e-eb48-11e4-9c36-25a978919e60.png)
The title of the currently playing track looks blurry, because it still has the text-shadow.

I managed to fix this with the following modifications to `application.css`

    @@ -48,6 +48,7 @@
     .trackrow {
 	    background-color: transparent;
   	    color: inherit;
    +    text-shadow: none;
     }
 
     .trackrow:hover {
    @@ -63,6 +64,7 @@
     .trackrowplaying {
 	    background-color: alpha(#000000, 0.05);
   	    color: inherit;
    +    text-shadow: none;
     }

**Comment by gnumdk** [comment]
Send me a merge request ;)

**Comment by horst3180** [comment]
Okay :)
