### ISSUE TITLE
Web search, add new results below.

### ISSUE THREAD

**Issue by dehen** [gnumdk/lollypop#960]
• Lollypop version: 0.9.228
• Gtk Version: 3.22.6
• Linux distribution: Manjaro
• youtube-dl-2017.1.31 (pip)

This is just a small usability suggestion. I'm not sure if there's a reason for the order search results are put in upon searching (relevance?).

But it may make sense to add any incoming new results append to the bottom of the list rather than adding them in all over the list. If there is meaning to the sort order, maybe just do a final sort once Lollypop is satisfied that all results have come in. 

The reason: If you do a search that is going to have a lot of results, sometimes you're chasing a moving target as you try to click the "save into collection" button. For instance, search for "out come" and then try to download the album "Rancid - Out Come the Wolves." The button will attempt to evade you as you try to press it because new results will still be adding above it if you're too fast.

Not a big deal. Feel free to close without comment if it's not worth your time.

**Comment by gnumdk** [comment]
Sorting when done will provide same jumping ui issue :/
