### ISSUE TITLE
Lollypop doesn't start anymore

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#961]
I have this issue since two days on master, I believe. When I move/delete my old `~/.local/share/lollypop/lollypop.db`, the application starts again. Do you need more input? There's no useful commandline output.

**Comment by gnumdk** [comment]
I need your db

**Comment by gnumdk** [comment]
Corrupted db, can't do anything for that... And don't know what happened...
http://froebe.net/blog/2015/05/27/error-sqlite-database-is-malformed-solved/

**Comment by fbruetting** [comment]
I have localized the problem: My external USB sound card (or maybe the kernel?) sometimes has some problems, in such that the device disappears in the Gnome audio settings or appears twice. After some seconds and restarting Gnome audio settings, everything works again. This happened just now and corrupded my DB. Is it possible for Lollypop do be less error-prone to audio device (connection/driver/etc) crashes?

**Comment by gnumdk** [comment]
If you are able to get some useful message, reopen this bug ;)
