### ISSUE TITLE
VPN 

### ISSUE THREAD

**Issue by buginfo** [gnumdk/lollypop#962]
BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.228
• Gtk Version: 3.22.0
• Linux distribution: arch

I recently had radio playing issues but got them sorted now I have an issue with vpn
when I connect to vpn the radio in lollypop wont play and in debug mode the out put is

list index out of range
list index out of range
list index out of range
list index out of range

**Comment by gnumdk** [comment]
So it's a network issue, here with VPN it works... Does it works with mpv?

**Comment by buginfo** [comment]
Yes its working with mpv , I dont know whats going on with lollypop , the radio was working then it stops playing I tried playing multiple stations that mpv will play but when I try with lolypop it just doesnt play , Ive rebooted etc reinstalled lollypop I cant understand why lollypop radio fails from time to time to play radio !! I keep trying to find the issue and update

**Comment by gnumdk** [comment]
Is gst-libav installed?

**Comment by buginfo** [comment]
Yea I've tried reinstalling gst-libav .  this is such a pain in the arse I love lollypop I use the radio all the time this is what I've done so far 

#### removed lollypop and all traces and rebooted and reinstalled
pacaur -Rdd lollypop
locate lollypop | sed 's/\lollypop.*/lollypop/' | while read line;do rm -rf $line ;done;updatedb
pacaur -Syyu lollypop

I give up it wa working this morning I hav'nt uninstalled anything else I though it was something to do with airvpn because after I installed airvpn from aur and started using it , lollypop hasnt worked since
