### ISSUE TITLE
Add track view

### ISSUE THREAD

**Issue by gsantner** [gnumdk/lollypop#963]
• Lollypop version: 0.9.228
• Gtk Version: 3.22.2
• Linux distribution: Arch

Currently there is no track view.
This means a table containing columns (at least) artist, track, track nr, album, length. (Search/Filterable)
Maybe the random tracks view can be reused in here. To have two options (just a plain list without album icons; and one like random tracks - with the album images) would be great.

**Comment by gnumdk** [comment]
Will not
