### ISSUE TITLE
Feature Request: Blacklisting Some Albums from Playing in Party Mode

### ISSUE THREAD

**Issue by steve80289** [gnumdk/lollypop#964]
Feature Request:

Being able to blacklist certain albums from being played in party mode. This could be beneficial in the sense that sometimes there are OSTs for games that you don't necessarily want to be played with the rest of your music. This could be worked around now by making a playlist with every single non OST album, but this is a PITA, and only small fraction of music albums are likely to be OSTs and additionally, if you add another album into your collection you need to add it to this other playlist as well. It might also be cool to have a temporary blacklist of an album that can vary in time such as the way Pandora has done.

**Comment by gnumdk** [comment]
Right click on party button and and using wanted genre?

**Comment by anonimo1w** [comment]
The only genre perspective leads to a possible problem. If I don't want to play a album or a artist, that wouldn't prevent it to play if I want to play another under the same genre. That leads to a play all or play none situation.

The possibility of select albums or even artists to be blacklisted seems to be a improvement.

**Comment by steve80289** [comment]
I didn't see the genre menu, that is really cool. The unfortunate thing with Genre is that it needs to be correct in the music database that info is getting pulled from. Musicbrainz does a bad job of capturing genre, and genre is a bit difficult to track. Ideally, everyone would put OSTs as "soundtrack" for genre, but they don't. While I am fine with going into the database and changing them manually, most are not.

**Comment by gnumdk** [comment]
Most don't want such feature ;)

**Comment by steve80289** [comment]
I wouldn't say they don't want it. People who have this issue most likely deal with it by skipping the song or album. I believe that if this potential feature were advertised, it would become 'more' popular. Ultimately, it is up to you whether you want to take the time to implement it though.
