### ISSUE TITLE
Tracks with missing album tag unreachable from artist's discography view

### ISSUE THREAD

**Issue by Wallacoloo** [gnumdk/lollypop#965]
BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.229
• Gtk Version: 3.22.7
• Linux distribution: Arch Linux

I have a lot of singles in my collection which lack an "album" tag, however they **do** have artist tags. Despite this, Lollypop clumps all of these tracks with missing album data into one massive, 600+ track album titled "unknown", and none of the songs are reachable via the artist's list.

The following image shows that artist data is correctly extracted for the track "Minty" by Volant; this track is listed under the "unknown" album.

![track-309-unknown](https://cloud.githubusercontent.com/assets/1210751/22776349/2f1e76f6-ee64-11e6-8e47-8406ea50dd4c.png)

The following image shows that this track isn't reachable by clicking on "Volant" in the sidebar (which is not the behavior I expect).

![not-attributed-to-volant](https://cloud.githubusercontent.com/assets/1210751/22776354/32450124-ee64-11e6-8c3c-8759c519de50.png)

If I change the album artist field (previously nonexistent) to match the artist field, the track will now show up under the artist, with album "Unknown" (shown below).

![album-artist-workaround](https://cloud.githubusercontent.com/assets/1210751/22776461/97b5ad6a-ee64-11e6-9460-bad06d447fcd.png)

I think the above should be the default result, even without Album Artist data but only Artist data. It appears to me that there was at one point a patch to address this: d0828f10c2b6c8256b2f6d32f4bde93e4e484b26 but it appears to have been removed at some point.

For reference, here's the original metadata associated with the track:

![metadata](https://cloud.githubusercontent.com/assets/1210751/22776650/5ffd3810-ee65-11e6-962e-8fa83a23f3c0.png)

**Comment by gnumdk** [comment]
No I can't, album artist is needed, otherwise, album is a compilation.

**Comment by Wallacoloo** [comment]
@gnumdk This is a single - it's not part of an album. Even when I download FLACs from Bandcamp, they deliver their singles without album or album artist fields, so it seems pretty standard that "no album tag = not an album/compilation" and that these songs can therefore be catalogued by just the artist tag.

**Comment by gnumdk** [comment]
>they deliver their singles without album or album artist fields,
If they do that, then Bandcamp sucks... But as I have many albums from Bandcamps correctly tagged, I guess issue comes from some artists selling their music as shit.
