### ISSUE TITLE
"stream doesn't contain enough data" 

### ISSUE THREAD

**Issue by brainstormtrooper** [gnumdk/lollypop#966]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.227
• Gtk Version: 3.22(?)
• Linux distribution: opensuse

I have 2 internet radio stations in Lollypop. They worked fine up until recently. The streams work fine in VLC, but no longer in Lollypop - error "stream doesn't contain enough data"... :-(

**Comment by Antonin010** [comment]
I have the same problem.

**Comment by gnumdk** [comment]
It's an issue with gstreamer, not lollypop. You are missing some plugins.
Check with OpenSUSE forum.

**Comment by brainstormtrooper** [comment]
I didn't find anything in the openSuse forums - any idea what gs plugins are needed to stream radio? I think I have the whole lot installed...

**Comment by gnumdk** [comment]
gstreamer 1.0 libav

**Comment by brainstormtrooper** [comment]
I have that installed already... Any other ideas?

**Comment by gnumdk** [comment]
Part stream uri here
