### ISSUE TITLE
Tweak request: id3 tag handling

### ISSUE THREAD

**Issue by mpuyrlbm** [gnumdk/lollypop#967]
• Lollypop version: 0.9.229
• Linux distribution: Ubuntu (XUbuntu variant)

Not exactly sure why this is happening, but Lollypop always handles id3tags the ugliest way possible. 
Firstly, if there are multiple tags of the same origin (like, 2 'Artist' tags, or 'Artist' and 'artist'), Lollypop uses every but the primary one (by primary I mean the first tag in the list, which also is being scrobbled to last.fm and which other players tend to use). To fix this, I had to manually remove all the duplicate tags. 
Secondly, if tracks of a several artists have the same 'Album' tag, Lollypop will assign them to the same page in compilations tab regardless of whether or not they are a part of an actual compilation. For example, I had 3+ artists with 'Untitled' albums, and each of them ended up in a single page. This also happens if an artist has several releases with the same name. Like in the example above, I had an artist with 2 or 3 'Untitled' albums, and each of them was assigned to a single page in the artist tab. Other players handle this by taking into account the 'Year' tag.

Also a feature request to make the scrobbler plugin cache and scrobble tracks at 50% listened mark, not 100%.

**Comment by gnumdk** [comment]
Secondly you need to add an album artist tag

**Comment by gnumdk** [comment]
Don't understand first issue

**Comment by gnumdk** [comment]
For lastfm, it respect lastfm API

**Comment by gnumdk** [comment]
And so, what is first issue?

**Comment by gnumdk** [comment]
No news, closing
