### ISSUE TITLE
Party mode: Adding or removing an album selects a new random "next song"

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#968]
I think a new random song should just be chosen if the current "next song"
• is of the album which gets removed, and
• was chosen randomly.

So choosing the next song manually and removing it's album afterwards should still leave this one song in the queue, but party mode won't play any further songs from this album.

**Comment by gnumdk** [comment]
Adding a song to queue doesn't change when removing album from party list (and BTW as you see the queue view, you do not have access to party albums).

But removing an album from party mode SHOULD remove next song if it's part of this album.

**Comment by fbruetting** [comment]
Well, when running in party mode, clicking on the "+" or "−" icons (which appear at mouse-over of an album) always alters the next song. Or do I understand that wrongly?

**Comment by fbruetting** [comment]
Thanks!
