### ISSUE TITLE
Crash when searching radio

### ISSUE THREAD

**Issue by boblaspugna** [gnumdk/lollypop#969]
• Lollypop version: 0.9.229-1
• Gtk Version:  3.22.8-1
• Linux distribution: archlinux

`ItunesSearch::__get_albums(): No active exception to reraise
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lollypop/pop_tunein.py", line 279, in __set_image
    None)
GLib.Error: gdk-pixbuf-error-quark`

**Comment by gnumdk** [comment]
Will fix it before releasing next new release (this week)

**Comment by gnumdk** [comment]
Any search string to reproduce issue?
