### ISSUE TITLE
Crash : org.gnome.Lollypop does not contain a key named 'artist-artwork'

### ISSUE THREAD

**Issue by kaldoran** [gnumdk/lollypop#970]
• Lollypop version: lollypop-0.9.229-1
• Gtk Version: gtk3 ( I think)
• Linux distribution: 4.9.8-1 Archlinux

Since around a month I can't start lollypop, I was hopping for a correction but since there is none, I open this issue.
Here is the "trace" of the segfault : 
`No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
/usr/lib/python3.6/site-packages/lollypop/lio.py:13: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, Soup
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

(lollypop:6660): Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

(lollypop:6660): GLib-GIO-ERROR **: Settings schema 'org.gnome.Lollypop' does not contain a key named 'artist-artwork'
Trappe pour point d'arrêt et de trace (core dumped)
`

**Comment by kaldoran** [comment]
For information, I've tried to install pylast but thats not resolving the bug.
Also tried to uninstall / reinstall 3 times and does not work too.

Tried also : 

`gsettings set org.gnome.Lollypop artist-artwork false
dconf write /org/gnome/Lollypop/artist-artwork true`

Pastbin of the /usr/share/glib-2.0/schemas/org.gnome.Lollypop.gschema.xml
http://pastebin.com/zSkqsn1t

**Comment by gnumdk** [comment]
Looks like a broken user profile or a conflicting installation, lollypop installed in /use/local for example

**Comment by kaldoran** [comment]
Well after looking for that : 
/home/kaldoran/.cache/lollypop
/home/kaldoran/.local/share/lollypop
/usr/lib/python3.6/site-packages/lollypop
/usr/share/help/C/lollypop
/usr/share/help/ru/lollypop
/usr/share/help/pl/lollypop
/usr/share/help/sk/lollypop
/usr/share/help/he/lollypop
/usr/share/help/nl/lollypop
/usr/share/help/cs/lollypop
/usr/share/help/sv/lollypop
/usr/share/help/sr/lollypop
/usr/share/help/uk/lollypop
/usr/share/help/it/lollypop
/usr/share/help/fi/lollypop
/usr/share/help/es/lollypop
/usr/share/help/fr/lollypop
/usr/share/help/de/lollypop
/usr/share/help/ca/lollypop
/usr/share/help/pt_BR/lollypop
/usr/share/lollypop
/usr/bin/lollypop

I've remove all package those file and reinstall and that still not working :/

**Comment by kaldoran** [comment]
Anyway, i'm going to switch to the lollypop-git package from AUR

**Comment by gnumdk** [comment]
You have wrong schema installed somewhere

**Comment by kaldoran** [comment]
resolved :D 
Removed all thing that contain "lollypop"
`find / -name "*ollypop*" -exec sudo rm {} \;`
Be careful if someone read this for a solution, first check what's going to be rm by removing the exec part.
then `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`

Then reinstall
