### ISSUE TITLE
Gstreamer general error on alac files

### ISSUE THREAD

**Issue by dov29** [gnumdk/lollypop#973]
• Lollypop version: 0.9.229
• Gtk Version: 3.18.9
• Linux distribution: Ubuntu 16.04

Lollypop is unable to play alac songs. I got an error "lollypop encoutered a general stream error". It appeared after some Ubuntu updates, Gstreamer 1.0 plugins are installed and all was working well before.

**Comment by gnumdk** [comment]
No idea, ask Ubuntu forum...
