### ISSUE TITLE
[Feature Request] SoundCloud API support?

### ISSUE THREAD

**Issue by Momoe** [gnumdk/lollypop#975]
Before moving to Linux and discovering Lollypop; through a friend, I was an dedicated user of AIMP and the 3rd party SoundCloud plugin. I was really hoping a similar feature could be implemented into Lollypop. 

Target features: 
    *The ability to input SoundCloud urls into the player to play music
    *Search Panel to find SoundCloud songs
    *Right Click song and favorite song
    *Right click and use the API to generate related music playlists

Here is the link to the SoundCloud pluging and it's GitHub page for the source code http://www.aimp.ru/forum/index.php?topic=49938.0

**Comment by gnumdk** [comment]
Soundcloud refused me an API key... So FUCK them ;)

**Comment by Momoe** [comment]
Awww this makes me sad. T____T
