### ISSUE TITLE
remember which device was synced

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#977]
yesterday i synced my jolla phone with lollypop and then my usb key...i noticed that usb key still had checked all the albums i've synced with my phone and viceversa...would be nice if lollypop could remember which devices synced what so if you mistakenly press sync you will not lose any data...

**Comment by gnumdk** [comment]
Argh, what a fucking valid bug report :-( But hard to fix.
Using playlists as sync? (Ok, not really a fix)

**Comment by legacychimera247** [comment]
thank you for your answer...for the moment begin i will be sure to check what i am syncing so i will not have to do the sync 2 times...it was anyway just a suggestion to avoid losing time when you want to sync an album and you are in a hurry...

**Comment by gnumdk** [comment]
I close this one, can't find a fix (and an UI):
- Allowing to show what is sync on a device
- Allowing to keep sync list internal
