### ISSUE TITLE
Deleted my entire music collection upon syncronizing attempt

### ISSUE THREAD

**Issue by andrew1007** [gnumdk/lollypop#978]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version:
• Gtk Version:
• Linux distribution:

Most recent version, Ubuntu
The only thing I am impressed with right now is how quickly it wiped 60gb of music with no prompt or indication it was doing so. The files were from an external drive (128gb micro sd card).

**Comment by gnumdk** [comment]
No bug here... If you sync a device with lollypop, it syncs...

And now I know it was a bad idea allowing sync to mass storage :-/

**Comment by andrew1007** [comment]
Lollypop syncs it's own collection onto the folder you selected? Is that what you're telling me? I'm quite confused.

**Comment by gnumdk** [comment]
Will add a warning in sync window... Hope you have backups.

**Comment by andrew1007** [comment]
For almost all of it, yes. So it was only an inconvenience as opposed to a crippling problem
