### ISSUE TITLE
Recently added not recent after 0.9.230

### ISSUE THREAD

**Issue by blackjackshellac** [gnumdk/lollypop#979]
BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.230
• Gtk Version: gtk3-3.22.8-1.fc25.x86_64
• Linux distribution: Fedora 25

None of my recently added albums are listed in the recently added section.  Those that are listed were added many years ago.

**Comment by emanuk** [comment]
Same here with Linux Mint 18.1

**Comment by gnumdk** [comment]
Welcome to my first broken db update. Can't do anything, too late ! :-1:

**Comment by gnumdk** [comment]
Will just test it works for newly added album

**Comment by blackjackshellac** [comment]
D'oh!  Shit happens.  If I restore ~/.local/share/lollypop from backup will taht do the trick?

**Comment by gnumdk** [comment]
You can:
- reinstall lollypop 0.9.229
- Restore db backups
- Reset database in settings (will backup all metadata in db.history)
- Install lollypop 0.9.230
- remove lollypop.db
- Launch lollypop, it will scan db and use metadata from history.

Should works and sorry for issue.

**Comment by emanuk** [comment]
How should I proceed to reinstall lollypop 0.9.229 when using the Ubuntu PPA (APT-Sources: http://ppa.launchpad.net/gnumdk/lollypop/ubuntu xenial/main amd64 Packages). Should I uninstall the current lollypop with apt and build it for Linux Mint 18.1 from the source with git? Thanks!

**Comment by emanuk** [comment]
Also I don't have much metadata in Lollypop, so I don't care if I lose the metadata and playlist. What is important for me is to have the new album list. So I guess, if I do `apt remove lollypop --purge`, and delete `/.local/share/lollypop/` I will get again the new albums list fixed?

**Comment by bill-c-martin** [comment]
I never took a DB backup. 

If you don't have a DB backup, it appears the dates in lollypop.db are definitely overwritten for good (and yes: if you add new tracks/albums now, it does work going forward). However, the track ID primary keys are still preserved in the order they were originally added. For example, if I sort the tracks desc by ID in sqlite3, that gives me the accurate "Recently added albums" order.

I am thinking it possible to recover this by writing a script that can run through the tracks by ID and update their corresponding dates to some arbitrary past date +1 second, per track? Then you would be able to sort them by date desc and get the correct "Recently added albums" order.

Although the added dates would not be true, they would at least show as being added in the same order as before (I would think)? 

I will give this a try, and report back if this is a working workaround for those that never took DB backups (shame on us!).

**Comment by bill-c-martin** [comment]
I ended up being able to restore the "Recently added albums" by updating the album dates in the DB to be today's date, minus 1 year, plus the album ID. The album IDs ultimately preserve the order that the albums were added in, in the first place.

```
$ cp /home/$USER/.local/share/lollypop/lollypop.db /home/$USER/.local/share/lollypop/lollypop-backup.db
$ sqlite3 /home/$USER/.local/share/lollypop/lollypop.db
SQLite version 3.18.0 2017-03-28 18:48:43
Enter ".help" for usage hints.
sqlite> update album_genres set mtime = ( strftime('%s', 'now') - (60*60*24*365) + album_id);
sqlite> .quit
```
