### ISSUE TITLE
Inform about music updating

### ISSUE THREAD

**Issue by prescott66** [gnumdk/lollypop#98]
I miss some information when music is updating. When lollypop starts first time, update takes long time. It would by nice, if somewhere in window can be label "Your music is updating..." or something like that....progress bar at the bottom is so thin too.

**Comment by gnumdk** [comment]
Any suggestion for implementation?

Not fan of adding a new label in the ui... Maybe  a notification at startup?

**Comment by gnumdk** [comment]
What do you think?

**Comment by prescott66** [comment]
sorry, i am not developer...i will check in next release :-)

**Comment by gnumdk** [comment]
I can give you help if you want to test current git ;)

**Comment by prescott66** [comment]
commands to build?

**Comment by gnumdk** [comment]
What's your distrib?

**Comment by prescott66** [comment]
Antergos (Arch)

**Comment by gnumdk** [comment]
yaourt lollypop-git

**Comment by gnumdk** [comment]
or another aur helper

**Comment by prescott66** [comment]
:+1:

**Comment by prescott66** [comment]
notification is great!...maybe if can be displayed little bit more time

**Comment by prescott66** [comment]
no, time is ok :) keep that as is
