### ISSUE TITLE
Music collection on SFTP is not working

### ISSUE THREAD

**Issue by gnomelibre** [gnumdk/lollypop#980]
• Lollypop version: 0.9.229
• Gtk Version: 3.22.8
• Linux distribution: Arch Linux / Fedora 24

I can mount my SFTP share with Nautilus and I can add a bookmark. From Nautilus, I can listen music with Audacious or Lollypop if I click on any file. But, in the Lollypop preferences, if I add this network share in addition or in replacement to the Music directory, Lollypop is unable to see my collection. Nothing happen, even if I update music manually.

**Comment by gnumdk** [comment]
Bad, was working, will give a look.

**Comment by gnumdk** [comment]
Here it works...

**Comment by gnumdk** [comment]
![amadou](https://cloud.githubusercontent.com/assets/3918824/23354976/d5d6cb9c-fcd3-11e6-8361-f71dad3c333e.png)
But when I remove sftp share, album is not removed :-1:

**Comment by gnumdk** [comment]
Adding my entire collection as SFTP works too.

**Comment by gnumdk** [comment]
Nothing in logs? With debug?

**Comment by gnomelibre** [comment]
$ lollypop --debug
/usr/lib/python3.5/site-packages/lollypop/lio.py:13: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, Soup
Lastfm::__connect(): Authentication Failed - You do not have permissions to access the service
CollectionScanner::__get_objects_for_uris(): g-io-error-quark: The specified location is not mounted (16)
Inotify::add_monitor(): g-io-error-quark: The specified location is not mounted (16)
Lastfm::__connect(): Authentication Failed - You do not have permissions to access the service

Lollypop should be able to mount the share itself, without having to do it manually in Nautilus. After doing it, I've these messages :

sftp://user@host/home/USER/path/WEB/Spoon%20-%20They%20Want%20My%20Soul%20-%202014%20(WEB%20FLAC) not detected as a music file
sftp://user@host/home/USER/path/WEB/Aerosmith%20-%20Music%20From%20Another%20Dimension!%20-%202012%20(WEB%20-%20FLAC) not detected as a music file
...

In these directories, there are music files in FLAC format, perfectly readable with Audacious or Lollypop, if I open them from the file manager.

**Comment by gnumdk** [comment]
Sorry, Gio does not guess mime type over sftp so files with no extension are not detected as audio/

**Comment by gnomelibre** [comment]
Extensions are present :

Aerosmith - Music From Another Dimension! - 2012 (WEB - FLAC)$ ls -1
01. LUV XXX.flac
02. Oh Yeah.flac
03. Beautiful.flac
04. Tell Me.flac
05. Out Go The Lights.flac
06. Legendary Child.flac
07. What Could Have Been Love.flac
08. Street Jesus.flac
09. Can't Stop Lovin' You.flac
10. Lover Alot.flac
11. We All Fall Down.flac
12. Freedom Fighter.flac
13. Closer.flac
14. Something.flac
15. Another Last Goodbye.flac
folder.jpg

**Comment by gnumdk** [comment]
sftp://user@host/home/USER/path/WEB/Aerosmith%20-%20Music%20From%20Another%20Dimension!%20-%202012%20(WEB%20-%20FLAC)

What is that?

**Comment by gnomelibre** [comment]
The album folder.

I type the command lollypop --debug then I choose the option Update music. Lollypop lists to me all of my folders (each folder corresponding to an album), and for each of them, I've the message « not detected as a music file », as if it perceived the folders not as folders, but as files, without ever checking their contents.

Better French version (ah ah :p)

Je lance lollypop --debug dans un terminal, ensuite dans Lolllypop je fais Mise à jour de la musique. Dans le terminal, il va me lister mes centaines de dossiers en m'indiquant à chaque fois que pour lui ce n'est pas de la musique. Ce qui me fait donc penser qu'il perçoit les dossiers comme étant de simples fichiers (qui ne sont donc pas des fichiers musicaux). Maintenant, s'il pense qu'il s'agit de fichiers et non de dossiers, ça peut expliquer qu'il ne regarde même pas leur contenu, puisque la musique se trouve pourtant bien dans chacun d'entre eux.

**Comment by gnumdk** [comment]
Oui, mais c'est Gio qui les détecte comme cela. Ce qui est bizarre, c'est que j'ai la même version que toi de GNOME... Donc je pencherai pour un problème du coté du serveur SSH. Je vais faire des tests avec d'autres distros.

**Comment by gnomelibre** [comment]
Si ça peut aider, le serveur tourne sous Debian 8 avec OpenSSH 6.7p1

**Comment by gnumdk** [comment]
Ca peut être la différence vu que j'ai testé de ArchLinux vers ArchLinux.

Je regarde avec mon serveurs Debian dès que possible ;)

**Comment by gnumdk** [comment]
Je viens juste de tester avec mon Serveur Debian 8 chez OVH et cela fonctionne aussi :-/

**Comment by gnumdk** [comment]
Tu es sur que tu as le problème sous Arch?

**Comment by gnumdk** [comment]
Ping

**Comment by gnumdk** [comment]
@gnomelibre ????

**Comment by gnomelibre** [comment]
C'est bon, j'ai trouvé. En réalité, ça fonctionne, mais je pense qu'il va clairement falloir revoir la procédure :)

Donc, après avoir fait tout plein de tests avec juste 2-3 albums qui posaient problème sur un compte différent (cette fois-ci, ça fonctionnait bien), puis de nouveau sur le compte problématique avec juste un dossier à la racine contenant quelques albums (là encore, ça fonctionnait bien), j'ai décidé de retenter en mode debug sur le dossier qui posait problème au départ et qui contient plusieurs centaines d'albums (443 pour être précis, représentant 163 Go de données).

Il a donc passé une heure à me sortir des « not detected as a music file » sur tous les dossiers, ensuite j'ai eu droit à plusieurs centaines de « Inotify::add_monitor(): g-io-error-quark: Opération non prise en charge par le moteur (15) ». Et enfin, après une longue pause où il ne se passait rien, il a commencé à m'ajouter les morceaux des nombreux albums. Opération qui dura encore 107 ans.

Le souci, c'est qu'avant de commencer à ajouter les albums et d'avoir enfin de l'activité dans Lollypop, il s'est bien écoulé une bonne heure sans le moindre retour.

**Comment by gnumdk** [comment]
Ok donc il faut que je désactive inotify quand je ne fais pas du file:// ça se tient.
