### ISSUE TITLE
volume higher while hovering cursor

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#981]
just noticed that if i hover the cursor into the song title the song automatically play in a normal volume (at least it seems as the other players to me), if i then click on the song title to play it, it start playing at a much lower volume as stated in another thread...is this wanted or is a bug?

**Comment by gnumdk** [comment]
Replay gain is not activated on preview because preview was not designed to use without headphone but seems some like you find this useful...

Will add it for preview.

**Comment by gnumdk** [comment]
Can't add replay gain on preview... Don't know how to do...
Closing with PULL_RESUEST_NEEDED if someone is able to do that.

BTW, preview is for headphone preview when you are on party ;)
