### ISSUE TITLE
volume can only be changed to multiples of ten

### ISSUE THREAD

**Issue by exap** [gnumdk/lollypop#983]
• Lollypop version: 0.9.229
• Gtk Version: 3.22.8
• Linux distribution: Arch

Why can the volume only be changed to multiples of ten?

Hence it's either too quiet or too loud for me..

**Comment by gnumdk** [comment]
What are you talking about? Lollypop handles volume from 0% to 100%.

**Comment by exap** [comment]
If I drag the volume from 0% to 100%, the volume will be 0%, 10%, 20%, etc (=multiples of ten), but never eg. 23%. I can't set the volume to 23% (only to either 20% or 30%).

I have to use `pavucontrol` for settting the volume to 23%. But this workaround isn't that nice.

**Comment by gnumdk** [comment]
Seems to be an issue due to a recent GTK update.

**Comment by exap** [comment]
Thanks very much :)

Keep up the awesome work
