### ISSUE TITLE
[Enhancement] View folders as albums

### ISSUE THREAD

**Issue by SiebenCorgie** [gnumdk/lollypop#984]
Hi,
it would be nice to view folders as albums. 
I have a lot of converted discs without any ID-tags, but I renamed the folders to the original name of the albums. Most Android music players use the folder name as album name. However Lollypop doesn't.
My Idea would be to have a switch in preferences->Behaviour-> Use folder name as album title, 
as well as a Button "All Albums" At the top left in the main window.

But the placement is just an idea.

-siebencorgie

**Comment by gnumdk** [comment]
No, Lollypop is designed around tags, use VLC. Sorry.

**Comment by SiebenCorgie** [comment]
No problem. Lollypop is still the best music player one can get for Gnome.
