### ISSUE TITLE
Lollypop don't read the folders recursely

### ISSUE THREAD

**Issue by monofluor** [gnumdk/lollypop#986]
• Lollypop version: 0.9.230
• Gtk Version: 3.20.9
• Linux distribution: Ubuntu Gnome 16.10

Lollypop don't read the folders recursely. I have albums in this way:

-Autor
|--- album 1
|--- album 2
|--- album 3

But Lollypop don't show thoose albums

**Comment by gnumdk** [comment]
Lollypop does.

**Comment by monofluor** [comment]
I think something is not working well because lollypop doesn't read a lot of albums that Rhythmbox does.
See the exampe please: 

 the Jamiroquai Folder has 3 subfolders albums and don't appear on lollypop 
 and "Jazz on" appears because doesnt have subfolders. Same thing with dozens of other albums...
.
├── 2007 -  Jazz On
│   ├── 01. Funk off - magic touch.mp3
│   ├── 02. Funk off - follow the white rabbit.mp3
│   ├── 03. Funk off - i wanna get funky now.mp3
│   ├── 04. Funk off - istanbul.mp3
│   ├── 05. Funk off - digital girl.mp3
│   ├── 06. Funk off - io vivo.mp3
│   ├── 07. Funk off - faithful people.mp3
│   ├── 08. Funk off - negombo.mp3
│   ├── 09. Funk off - in touch.mp3
│   ├── 10. Funk off - no what.mp3
│   ├── 11. Funk off - blue pill.mp3
│   ├── 12. Funk off - big dog.mp3
│   ├── 13. Funk off - c'era 1 volta.mp3
│   └── folder.jpg
├── Jamiroquai
│   ├── Jamiroquai - Rock Dust Light Star 2010 [FLAC]
│   │   ├── 01 - Jamiroquai - Rock Dust Light Star.flac
│   │   ├── 02 - Jamiroquai - White Knuckle Ride.flac
│   │   ├── 03 - Jamiroquai - Smoke and Mirrors.flac
│   │   ├── 04 - Jamiroquai - All Good In The Hood.flac
│   │   ├── 05 - Jamiroquai - Hurtin'.flac
│   │   ├── 06 - Jamiroquai - Blue Skies.flac
│   │   ├── 07 - Jamiroquai - Lifeline.flac
│   │   ├── 08 - Jamiroquai - She's A Fast Persuader.flac
│   │   ├── 09 - Jamiroquai - Two Completely Different Things.flac
│   │   ├── 10 - Jamiroquai - Goodbye To My Dancer.flac
│   │   ├── 11 - Jamiroquai - Never Gonna Be Another.flac
│   │   ├── 12 - Jamiroquai - Hey Floyd.flac
│   │   ├── cdart.png
│   │   └── Tracklist.txt
│   └── Jamiroquai - Synkronized 1999 [MP3@320](oan)
│       ├── 01 - Jamiroquai - Canned Heat [Album Version].mp3
│       ├── 02 - Jamiroquai - Planet Home.mp3
│       ├── 03 - Jamiroquai - Black Capricorn Day.mp3
│       ├── 04 - Jamiroquai - Soul Education.mp3
│       ├── 05 - Jamiroquai - Falling.mp3
│       ├── 06 - Jamiroquai - Destitute Illusions.mp3
│       ├── 07 - Jamiroquai - Supersonic.mp3
│       ├── 08 - Jamiroquai - Butterfly.mp3
│       ├── 09 - Jamiroquai - Where Do We Go From Here.mp3
│       ├── 10 - Jamiroquai - King For A Day.mp3
│       ├── 11 - Jamiroquai - Deeper Underground.mp3
│       ├── 1337x.Org.txt
│       ├── cdart.png
│       ├── Demonoid.me.txt
│       ├── folder.jpg
│       └── info 22 - June - 2011.txt

**Comment by julianrichen** [comment]
The example you posted seems to show mp3s working but the flacs are not. Can you confirm witg other albums? Maybe its a metatag issue?

**Comment by gnumdk** [comment]
Maybe they are in compilations because of missing album artist tag

**Comment by monofluor** [comment]
The albums are not in compilation, the artist-album tags are fine and is the same problem if is flac or mp3, confirmed.

Albums that are not subfolders apears correctly in lollypop. And in the opposite direction, if a put a visible album inside a folder it disappear of lollypop. confirmed.

Just in case, could "tracker" process be part of this?

![area de trabajo 2_004](https://cloud.githubusercontent.com/assets/1194452/23488332/c5304fb8-feca-11e6-97bd-cf729f1b3a46.jpg)

![area de trabajo 2_005](https://cloud.githubusercontent.com/assets/1194452/23488338/d33d024a-feca-11e6-89ae-290ea05c78c4.jpg)

**Comment by gnumdk** [comment]
Sens me lollypop.db by email

**Comment by gnumdk** [comment]
Run lollypop -d, update db and paste output

**Comment by gnumdk** [comment]
ping

**Comment by gnumdk** [comment]
@monofluor ???

**Comment by dlnsk** [comment]
Confirm problem.
I added 3 Doors Down's albums but player didn't add them even when I choose Refresh database.
Log displays that it scans folders but doesn't add tracks...


file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/3%20Doors%20Down/Album's/2008%20-%203%20Doors%20Down%20(Best%20Buy%20Exclusive%20Edition)%20-%20(320%20kbps)/Scans%20covers not detected as a music file
file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/3%20Doors%20Down/Album's/2008%20-%203%20Doors%20Down%20(Best%20Buy%20Exclusive%20Edition)%20-%20(320%20kbps)/Scans%20covers not detected as a music file
file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/3%20Doors%20Down/Album's/2011%20-%20Time%20Of%20My%20Life%20(Deluxe%20Edition)%20-%20(320%20kbps)/Scans%20covers not detected as a music file
file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/3%20Doors%20Down/Album's/2011%20-%20Time%20Of%20My%20Life%20(Deluxe%20Edition)%20-%20(320%20kbps)/Scans%20covers not detected as a music file
file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/3%20Doors%20Down/Album's/2011%20-%20Time%20Of%20My%20Life%20(Deluxe%20Edition)%20-%20(320%20kbps)/Scans%20covers not detected as a music file
file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/3%20Doors%20Down/Album's/2011%20-%20Time%20Of%20My%20Life%20(Deluxe%20Edition)%20-%20(320%20kbps)/Scans%20covers not detected as a music file
file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/3%20Doors%20Down/Album's/2011%20-%20Time%20Of%20My%20Life%20(Deluxe%20Edition)%20-%20(320%20kbps)/Scans%20covers not detected as a music file

**Comment by gnumdk** [comment]
@dlnsk Can you send me this albums by dropbox/...

**Comment by dlnsk** [comment]
Yes. I can

**Comment by dlnsk** [comment]
Shared through dropbox

**Comment by gnumdk** [comment]
![works](https://cloud.githubusercontent.com/assets/3918824/24353268/22405b90-12ed-11e7-9b74-ae79b8043d26.png)

**Comment by gnumdk** [comment]
Looks more like a permission issue.

**Comment by dlnsk** [comment]
Nope.
755 for folders and 644 for files. Owner is mine.
Other player plays them well...

**Comment by gnumdk** [comment]
Are you sure your gstreamer setup is ok?

**Comment by dlnsk** [comment]
It seems like I have everything that are need.

$ apt list --installed | grep gstreamer

gir1.2-gstreamer-0.10/xenial,now 0.10.36-1.5ubuntu1 amd64 [установлен]
gir1.2-gstreamer-1.0/xenial-updates,now 1.8.3-1~ubuntu0.1 amd64 [установлен]
gstreamer0.10-alsa/xenial-security,now 0.10.36-2ubuntu0.1 amd64 [установлен]
gstreamer0.10-gconf/xenial-security,now 0.10.31-3+nmu4ubuntu2.16.04.3 amd64 [установлен]
gstreamer0.10-gnomevfs/xenial-security,now 0.10.36-2ubuntu0.1 amd64 [установлен]
gstreamer0.10-nice/xenial,now 0.1.13-0ubuntu2 amd64 [установлен]
gstreamer0.10-plugins-base/xenial-security,now 0.10.36-2ubuntu0.1 i386 [установлен]
gstreamer0.10-plugins-base-apps/xenial-security,now 0.10.36-2ubuntu0.1 amd64 [установлен]
gstreamer0.10-plugins-good/xenial-security,now 0.10.31-3+nmu4ubuntu2.16.04.3 i386 [установлен]
gstreamer0.10-pulseaudio/xenial-security,now 0.10.31-3+nmu4ubuntu2.16.04.3 amd64 [установлен]
gstreamer0.10-tools/xenial,now 0.10.36-1.5ubuntu1 amd64 [установлен]
gstreamer0.10-x/xenial-security,now 0.10.36-2ubuntu0.1 amd64 [установлен]
gstreamer1.0-alsa/xenial-updates,now 1.8.3-1ubuntu0.1 amd64 [установлен]
gstreamer1.0-clutter/xenial,now 2.0.18-1 amd64 [установлен]
gstreamer1.0-doc/xenial-updates,xenial-updates,now 1.8.3-1~ubuntu0.1 all [установлен]
gstreamer1.0-libav/xenial-updates,now 1.8.3-1ubuntu0.2 amd64 [установлен]
gstreamer1.0-nice/xenial,now 0.1.13-0ubuntu2 amd64 [установлен]
gstreamer1.0-plugins-bad/xenial-updates,now 1.8.3-1ubuntu0.2 amd64 [установлен]
gstreamer1.0-plugins-bad-dbg/xenial-updates,now 1.8.3-1ubuntu0.2 amd64 [установлен]
gstreamer1.0-plugins-bad-doc/xenial-updates,xenial-updates,now 1.8.3-1ubuntu0.2 all [установлен]
gstreamer1.0-plugins-bad-faad/xenial-updates,now 1.8.3-1ubuntu0.2 amd64 [установлен, автоматически]
gstreamer1.0-plugins-bad-videoparsers/xenial-updates,now 1.8.3-1ubuntu0.2 amd64 [установлен, автоматически]
gstreamer1.0-plugins-base/xenial-updates,now 1.8.3-1ubuntu0.1 amd64 [установлен]
gstreamer1.0-plugins-base-apps/xenial-updates,now 1.8.3-1ubuntu0.1 amd64 [установлен]
gstreamer1.0-plugins-base-doc/xenial-updates,xenial-updates,now 1.8.3-1ubuntu0.1 all [установлен]
gstreamer1.0-plugins-good/xenial-updates,now 1.8.3-1ubuntu0.3 amd64 [установлен]
gstreamer1.0-plugins-ugly/xenial-updates,now 1.8.3-1ubuntu0.1 amd64 [установлен]
gstreamer1.0-plugins-ugly-amr/xenial-updates,now 1.8.3-1ubuntu0.1 amd64 [установлен, автоматически]
gstreamer1.0-pulseaudio/xenial-updates,now 1.8.3-1ubuntu0.3 amd64 [установлен]
gstreamer1.0-tools/xenial-updates,now 1.8.3-1~ubuntu0.1 amd64 [установлен]
gstreamer1.0-x/xenial-updates,now 1.8.3-1ubuntu0.1 amd64 [установлен]
libgstreamer-plugins-bad1.0-0/xenial-updates,now 1.8.3-1ubuntu0.2 amd64 [установлен, автоматически]
libgstreamer-plugins-base0.10-0/xenial-security,now 0.10.36-2ubuntu0.1 amd64 [установлен]
libgstreamer-plugins-base1.0-0/xenial-updates,now 1.8.3-1ubuntu0.1 amd64 [установлен]
libgstreamer-plugins-good1.0-0/xenial-updates,now 1.8.3-1ubuntu0.3 amd64 [установлен]
libgstreamer0.10-0/xenial,now 0.10.36-1.5ubuntu1 amd64 [установлен]
libgstreamer1.0-0/xenial-updates,now 1.8.3-1~ubuntu0.1 amd64 [установлен]

**Comment by dlnsk** [comment]
Player displays it on every run:
```
CollectionScanner::__scan() 'file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/Scrubs%20OST/OST%20Scrubs%20(Season%20%208)/22%20-%20Sara_Barielles_And_Ingrid_Michaelson_-_Winter_Song.mp3'
```

**Comment by gnumdk** [comment]
Should be ok now, reopen if not fixed.

**Comment by dlnsk** [comment]
Please, create new release.

**Comment by gnumdk** [comment]
No way for you to test master before? Don't want to release if not really fixed.

**Comment by dlnsk** [comment]
Yes it fixed.
It was very new to me. I never make application from sources... ;)
Albumes added successfully.

It output something new in console:

```
CollectionScanner::__scan(mtime): 'file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/Scrubs%20OST/OST%20Scrubs%20(Season%20%208)/22%20-%20Sara_Barielles_And_Ingrid_Michaelson_-_Winter_Song.mp3' file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/Scrubs%20OST/OST%20Scrubs%20(Season%20%208)/22%20-%20Sara_Barielles_And_Ingrid_Michaelson_-_Winter_Song.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/15.%20%D0%9D%D0%B5%D0%BD%D1%83%D0%B6%D0%BD%D0%B0%D1%8F%20%D0%9F%D0%B5%D1%81%D0%B5%D0%BD%D0%BA%D0%B0.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/16.%20%D0%97%D0%B2%D1%91%D0%B7%D0%B4%D0%BE%D1%87%D0%BA%D0%B0.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/17.%20%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F%20%D0%A1%D1%82%D1%80%D0%B5%D0%BB%D0%B0.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/18.%20%D0%9A%20%D0%94%D1%80%D1%83%D0%B3%D1%83.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/19.%20%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%B8%20%D0%9C%D0%B5%D0%BD%D1%8F.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/2003%20-%20%D0%9F%D1%80%D0%B8%D0%BD%D0%BE%D1%81%D1%8F%D1%89%D0%B8%D0%B9%20%D1%83%D0%B4%D0%B0%D1%87%D1%83/15.%20%D0%9D%D0%B5%D0%BD%D1%83%D0%B6%D0%BD%D0%B0%D1%8F%20%D0%9F%D0%B5%D1%81%D0%B5%D0%BD%D0%BA%D0%B0.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/2003%20-%20%D0%9F%D1%80%D0%B8%D0%BD%D0%BE%D1%81%D1%8F%D1%89%D0%B8%D0%B9%20%D1%83%D0%B4%D0%B0%D1%87%D1%83/16.%20%D0%97%D0%B2%D1%91%D0%B7%D0%B4%D0%BE%D1%87%D0%BA%D0%B0.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/2003%20-%20%D0%9F%D1%80%D0%B8%D0%BD%D0%BE%D1%81%D1%8F%D1%89%D0%B8%D0%B9%20%D1%83%D0%B4%D0%B0%D1%87%D1%83/17.%20%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F%20%D0%A1%D1%82%D1%80%D0%B5%D0%BB%D0%B0.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/2003%20-%20%D0%9F%D1%80%D0%B8%D0%BD%D0%BE%D1%81%D1%8F%D1%89%D0%B8%D0%B9%20%D1%83%D0%B4%D0%B0%D1%87%D1%83/18.%20%D0%9A%20%D0%94%D1%80%D1%83%D0%B3%D1%83.mp3
CollectionScanner::__scan(add): gst-stream-error-quark: No data in file (4) file:///home/master/%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/%D0%92%D0%B8%D1%81%D0%BE%D0%BA%D0%BE%D1%81%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D0%B4/2003%20-%20%D0%9F%D1%80%D0%B8%D0%BD%D0%BE%D1%81%D1%8F%D1%89%D0%B8%D0%B9%20%D1%83%D0%B4%D0%B0%D1%87%D1%83/19.%20%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%B8%20%D0%9C%D0%B5%D0%BD%D1%8F.mp3
```

**Comment by gnumdk** [comment]
@dlnsk You should look at file in output, you have empty mp3 files...

**Comment by dlnsk** [comment]
I'm very far from home now. I'll return home on Saturday and check it.
But. I'm sure that tracks will good.

**Comment by monofluor** [comment]
Hi, sorry for the big delay, I was travelling. The fix was ok but just for local files... Using an external hard drive the problem persist.

**Comment by monofluor** [comment]
• Lollypop version: 0.9.240
• Gtk Version: 3.22.11
• Linux distribution: Ubuntu Gnome 17.04

> Run lollypop -d, update db and paste output
I did this: https://ufile.io/9ckbg

lollypop.db; https://ufile.io/izbfl

**Comment by gnumdk** [comment]
And do some missing albums appear in debug output?

**Comment by monofluor** [comment]
Yes, with messages like this:

M%C3%BAsica/Musica/Kevin%20Johansen/KEVIN%20JOHANSEN%20-%202004%20-%20City%20Zen/KEVIN%20CITYZEN%20FRONT.jpg not detected as a music file

The weird thing is: if I setup a new library with the missing albums.... they appears in this new setup.

Let's say if I setup a new library with just this albums (see example below), the albums appears correctly.... If I add all the others albums... the first ones disappear

├── Jamiroquai
│   ├── Jamiroquai - Rock Dust Light Star 2010 [FLAC]
│   │   ├── 01 - Jamiroquai - Rock Dust Light Star.flac
│   │   ├── 02 - Jamiroquai - White Knuckle Ride.flac
│   │   ├── 03 - Jamiroquai - Smoke and Mirrors.flac
│   │   ├── 04 - Jamiroquai - All Good In The Hood.flac
│   │   ├── 05 - Jamiroquai - Hurtin'.flac
│   │   ├── 06 - Jamiroquai - Blue Skies.flac
│   │   ├── 07 - Jamiroquai - Lifeline.flac
│   │   ├── 08 - Jamiroquai - She's A Fast Persuader.flac
│   │   ├── 09 - Jamiroquai - Two Completely Different Things.flac
│   │   ├── 10 - Jamiroquai - Goodbye To My Dancer.flac
│   │   ├── 11 - Jamiroquai - Never Gonna Be Another.flac
│   │   ├── 12 - Jamiroquai - Hey Floyd.flac
│   │   ├── cdart.png
│   │   └── Tracklist.txt
│   └── Jamiroquai - Synkronized 1999 MP3@320
│   ├── 01 - Jamiroquai - Canned Heat [Album Version].mp3
│   ├── 02 - Jamiroquai - Planet Home.mp3
│   ├── 03 - Jamiroquai - Black Capricorn Day.mp3
│   ├── 04 - Jamiroquai - Soul Education.mp3
│   ├── 05 - Jamiroquai - Falling.mp3
│   ├── 06 - Jamiroquai - Destitute Illusions.mp3
│   ├── 07 - Jamiroquai - Supersonic.mp3
│   ├── 08 - Jamiroquai - Butterfly.mp3
│   ├── 09 - Jamiroquai - Where Do We Go From Here.mp3
│   ├── 10 - Jamiroquai - King For A Day.mp3
│   ├── 11 - Jamiroquai - Deeper Underground.mp3
│   ├── 1337x.Org.txt
│   ├── cdart.png
│   ├── Demonoid.me.txt
│   ├── folder.jpg
│   └── info 22 - June - 2011.txt

**Comment by gnumdk** [comment]
Can you provide me a minimal archive allowing me to reproduce the issue?

**Comment by monofluor** [comment]
I don`t know how. With a library with 43 of this albums works well. The problem has to do with large collections

**Comment by gnumdk** [comment]
Please setup lollypop to scan your entire collection, close lollypop, remove lollypop.db, run lollypop -d and send me output by email.

**Comment by gnumdk** [comment]
@monofluor ping?

**Comment by monofluor** [comment]
I sent you the output by email as you requested the past week

**Comment by gnumdk** [comment]
The file blocking the scan: file:///media/pablo/EXTERNO/Media-Center/M%C3%BAsica/cinemateca%20finlandesa/02%20-%20Cuando%20tu%20no%20est%A0s.mp3
