### ISSUE TITLE
Flatpack repository

### ISSUE THREAD

**Issue by Eeveel** [gnumdk/lollypop#987]
Hi!
Is it easily possible for you to add a Flatpack repository that we can easily install with the command
"flatpak install lollypop.flatpakref "
and mostly easily update?

Have a nice day!
Eeveel

**Comment by gnumdk** [comment]
Yes, but don't manage to get it... Help is welcome.

**Comment by nedrichards** [comment]
The Flatpak community is beginning to develop [Flathub](http://flathub.org) as an easy location for developers to host their flatpak repos (if they wish). It's still very early but you can submit your manifest as a PR to https://github.com/flathub/requests help is available at #flatpak on freenode.

**Comment by Barthalion** [comment]
Just to expand what @nedrichards said, the process looks like this currently:

1. Create a pull request against [this repo](https://github.com/flathub/flathub), preferably using `new-pr` branch.
2. Wait for someone to review it.
3. After merging, you get push access to the repository created under Flathub organization.

We can just import modules as well, whatever works for you. Lollypop will be installable either after adding `flathub` remote or by using prepared flatpakref (we will probably generate these automatically at some point, but you can easily do that yourself for now and put on the project website).

Let me know if you have any questions.

**Comment by gnumdk** [comment]
OK, will be my next fix ;)

**Comment by Barthalion** [comment]
Here's a flatpakref that can be used to install Lollypop from Flathub via double click (if GNOME Software is installed) or using `flatpak install url_to_flatpakref`:

```ini
[Flatpak Ref]
Title=Lollypop
Description=Music player for GNOME
Icon=https://github.com/gnumdk/lollypop/blob/master/data/icons/hicolor/256x256/apps/org.gnome.Lollypop.png?raw=true
Name=org.gnome.Lollypop
Branch=stable
Url=http://flathub.org/repo/
IsRuntime=False
GPGKey=mQENBFjpVnsBCACgib1NIXmWfiBCg3dsauP7tsy8YgTU/EZLt1Zl5KGyXflz4RZQC7He6K7c5Oj2zABKT3nnbX9Jtdpj5eobzCHH7p16dz4MNtfWygaKFDcM4p+YBrawwQPAoaCHIDjxt99E4xBqyasrbWI+1rg/ZsisZvmIhdmG1LLBdrqOmrzDeiPWbmXdWooP3OnDOdiWqq8jLSpJJgEWgi89edWEKtAgS0L3bT/nmDrH7M26mXf9wPKMH3ArUaDjDWPWTW9ev4yUCN28I8J4Zq4Z17sAywdnJuf9Ak7Bg95tta4dwDdtr69Aozn2eNaxvR3/AuP0REbLvD2kNw/K13kL1eZunTsrABEBAAG0HUZsYXRodWIgPGZsYXRodWJAZmxhdHBhay5vcmc+iQE5BBMBAgAjBQJY6VZ7AhsDBwsJCAcDAgEGFQgCCQoLBBYCAwECHgECF4AACgkQG7gPiPAVqh4WXwf/XgYD1DKmIZM/TlwykBWbJobqsk/IMuhuMVJsUfRvTTWdrdLx65VQIOYDUUonO8hqzGzo09vX6ALMjnLGAZIVpdzjFxejR9vx5mYyFuIXtYWooups9n8dtOW0JCxeL1YkM4bWWHsz6xiRC78y083nUtv+F3K11pTK7s5VlHPeViz8obDST3sjcDVS34e+BQ/LtzEx10CJC++xvaGood62adOs51YpT4SxOn/bbydlN/vtqoQYYYPcWLFEv+k0J/KGEXiXc7A4txDNADlOUjMhgPwhCOTwntu0in6CyN/j2GpsSHg1CWjapATqrkTInIBkq3tlpwRW43dZNtxTQf4XlbkBDQRY6VZ7AQgA0W0dCNogCNbtE8he6/uG0rB9cvXVfnCuJyxKcT8mixvDpYNYl3uvIxjzHHaimIAyrrU7P/9BqMDMwOECwTpGx4UnvjIzSh54hWJHqyJXBXANDn5/4wtsfjMhWYYn4t8pCFz3ErxQYNavNMlOvhvrlSMC9C1rdDqEvizJy+tg1PWl8eOpX/L2shvWLs57GDH6xkGyUXJ+Mw/Ujivs5pMACfOp3pJAr5jSrmqmhboM6+UYP3eJHLDHscn3u3gUJ7vLReUooURChqbkvSGicrDQiNpaPbLULwxjwXkPTKXa6btztMV4GChsZ5YSH2jodbGyw1dSJ77RCYl4kj+3cI9yZwARAQABiQEfBBgBAgAJBQJY6VZ7AhsMAAoJEBu4D4jwFaoePlMIAJqgnKWNYsuP2RTuqoVlcQ/05833Z6NT+/8UYGolLfj6JhOfESgZoDaoSnXcU8Z1D3oVRsJI4ULbU4WBca1Td3D63wIkvT5tuNclNYgfkeexVjSA7f7oFsQQX1s6+Dp5LaOy5X5rGvz0Lcvy8dz7KQYtQpB+40THp9ABye4dsmPa3cRJYgfdxUr/BJo0/a6Prj8qtapQJ3zEXrtR8ya6pB80b0pviE2D3E/Fq9A7TE2v5SGjBWv5NBQNLLVnZvBauNzt12AnZTsFTuMrx3R/AHO6IODM9s6VPlOeLvaCFtWdOrcVAZZO9D1Lqa6+DwwV+DiOZbNVwvMhD/WED3W4nHw=
RuntimeRepo=https://flathub.org/repo/flathub.flatpakrepo
```

I have also added you to collaborators to the Flathub repo, so you can easily push new releases. Every commit is build automatically so users just need to do `flatpak update` once in a while.

**Comment by Barthalion** [comment]
With all this, I guess the issue can be closed. :) Thanks for this awesome app btw, easily the best music player I had on my laptop for years.
