### ISSUE TITLE
Compilations complications with "Unknown" albums

### ISSUE THREAD

**Issue by p3732** [gnumdk/lollypop#988]
Lollypop version: 0.9.229-1
Gtk Version: 3.22
Linux distribution: Arch

So I noticed three behaviors of Lollypop, which I believe have the same inherent problem, namely treating all songs without an album tag internally as being from the album "Unknown". Now I am aware of #888 , but here are the things bothering me nonetheless:
1. - When you add songs to your library that are not tagged correctly (or at all), they obviously end up under Compilations->Unknown, internally inheriting amounts of play from "Unknown" (probably also ratings but I don't usually use them). When tagging them correctly, they still keep the amount of plays, because Lollypop notices the changed tags and just updates these, not the metadata. While this works fine for normal tag changes it messes things up for songs that fell under the "Unknown" Album category.

2. - If there is more than one song where the year is known but the album name is not, Lollypop creates a separate album called "Unknown" per year, resulting in quite a mess in the compilations section.

3. - (probably closely related to 2.) Not all "Unknown" compilations albums are shown. They show up in lollypop.db, but not under compilations
Here is a screenshot with Lollypop and db side by side:
![screenshot from 2017-03-02 18-27-15](https://cloud.githubusercontent.com/assets/3109792/23519075/f27bfac0-ff75-11e6-8723-7d222109b73e.png)

So, while I get that it's quite a hassle to introduce a single song section, especially with the need for new database tables, I guess that would be the smoothest way to fix these issues (also it might be a solution for WONTFIX #965).
If you are not generally against such "clutter" in your application, but have no intentions do code it yourself, would you accept patches for this? (can't guarantee nothing, but I am interested in it)

Otherwise, a more simple fix for 2. would probably be, to drop dates for songs without an album name, which should also fix 3.
Similarly for 1. it might be sufficient to reset the metadata when the album name was "Unknown" and the album was a compilation.

**Comment by gnumdk** [comment]
Please send me lollypop.db by email.

**Comment by gnumdk** [comment]
Here Unknown Rains is not in compilations (no_album_artist == 0) so it's normal to not see it in compilations.

**Comment by p3732** [comment]
Yes Unknown Rains is not the matter, there are just 8 of the Unknown albums shown, although in the lollypop.db there are about 22 shown (including 3 weird duplicates).
Sent you the db file, it's not the same as on the screenshot, but there are no new Unknown albums since then.

**Comment by p3732** [comment]
Still I don't get what criteria there is used to distinguish between where compilations are sorted. I just removed a comment tag from a song listed as compilation and the update of the db moved it to be listed via artist.

Has there been any update on this between 0.9.229-1 to 0.9.230-1? Should I re-read my library from scratch?

**Comment by gnumdk** [comment]
Send me an album by email/Dropbox or anything else

**Comment by gnumdk** [comment]
And so? Don't see anything wrong with tracks you sent me... Give me a track that is not correctly added to lollypop db.

**Comment by p3732** [comment]
Yes, as I wrote, I got mixed up, by where the albums were sorted into, all songs are in the db. Some are shown under the artist, some are compiled into an unknown album.

**Comment by p3732** [comment]
This concerns only point 3 tough, so what about 1 and 2?

**Comment by gnumdk** [comment]
Wontfix... Adding broken files to an application is always a bad idea... Will not bloat Lollypop code to handle such special cases. The metadata history feature can look bad for your case but it's cool for most user (that don't want to loose metadata just by changing tags)
