### ISSUE TITLE
Play for queue

### ISSUE THREAD

**Issue by anonimo1w** [gnumdk/lollypop#989]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.230
• Gtk Version: 3.20.9
• Linux distribution: Fedora 24

If I add a album or some albums on queue (from the '+' sign on the cover, for example) I can't "play it" directly (by the keyboard button or by the "play" icon on player). 

To play it, I have to play a song before and then skip it.

Also, if I try to play a song from the queue (by clicking on the album and choosing a song) seems that it will change the queue from selected albums to artist's album. Not sure if related.

**Comment by gnumdk** [comment]
Can you make a screencast of second issue, I suppose what you are talking the queue is not the queue

**Comment by anonimo1w** [comment]
Here are the images

![captura de tela de 2017-03-03 14-17-08](https://cloud.githubusercontent.com/assets/2099867/23561437/0213f508-001d-11e7-84fc-8ebf51f52b97.png)
![captura de tela de 2017-03-03 14-17-22](https://cloud.githubusercontent.com/assets/2099867/23561436/0211ceea-001d-11e7-8ee7-4ddaf6a832ae.png)
![captura de tela de 2017-03-03 14-17-41](https://cloud.githubusercontent.com/assets/2099867/23561438/021d8a82-001d-11e7-81e0-aaf3b3efd37f.png)

Identified it in the wrong way. 
From that behaviour, seems that if I add from the first view ("popular albums" right?) It will, in the first track selected, change them to all from popular albums. In the second (choosing a second album and selecting a song) it will pick from the artist. Also, seems that takes a while or another add to update it.

Also, it's not the queue? o_O

**Comment by gnumdk** [comment]
No, it's current playlist, queue is another feature in Lollypop.

**Comment by gnumdk** [comment]
For the first issue, it's wanted, if you want to play it, you click on the play button.

**Comment by gnumdk** [comment]
For second issue, can't reproduce here... Play any album in Populars, go to popover, play another track... Only one album in current playlist.

**Comment by gnumdk** [comment]
"seems that if I add from the first view"
How do you add?

**Comment by gnumdk** [comment]
ping?
