### ISSUE TITLE
Songs listed twice

### ISSUE THREAD

**Issue by rumpelsepp** [gnumdk/lollypop#99]
Hi, I have bought the most recent Nightwish album which includes an instrumental version and a normal version. Lollypop has problems with listing these CDs. Every song appears twice:

![screenshot from 2015-04-27 10-11-13](https://cloud.githubusercontent.com/assets/1961699/7343778/019664d8-ecc6-11e4-95e9-6b7d2e991994.png)

![screenshot from 2015-04-27 10-11-51](https://cloud.githubusercontent.com/assets/1961699/7343779/05d5e3ac-ecc6-11e4-8646-c7355645b524.png)

![screenshot from 2015-04-27 10-12-11](https://cloud.githubusercontent.com/assets/1961699/7343781/0997e9fe-ecc6-11e4-8149-5fa25076cd7e.png)

The folder structure is like this:

```
Nightwish
|
├── Nightwish-Endless_Forms_Most_Beautiful
│   ├── 01.Shudder_Before_the_Beautiful.ogg
│   ├── 02.Weak_Fantasy.ogg
│   ├── 03.Élan.ogg
│   ├── 04.Yours_is_an_Empty_Hope.ogg
│   ├── 05.Our_Decades_in_the_Sun.ogg
│   ├── 06.My_Walden.ogg
│   ├── 07.Endless_Forms_Most_Beautiful.ogg
│   ├── 08.Edema_Ruh.ogg
│   ├── 09.Alpenglow.ogg
│   ├── 10.The_Eyes_of_Sharbat_Gula.ogg
│   └── 11.The_Greatest_Show_on_Earth.ogg
└── Nightwish-Endless_Forms_Most_Beautiful_(Instrumental_Version)
    ├── 01.Shudder_Before_The_Beautiful.ogg
    ├── 02.Weak_Fantasy.ogg
    ├── 03.Élan.ogg
    ├── 04.Yours_Is_An_Empty_Hope.ogg
    ├── 05.Our_Decades_In_The_Sun.ogg
    ├── 06.My_Walden.ogg
    ├── 07.Endless_Forms_Most_Beautiful.ogg
    ├── 08.Edema_Ruh.ogg
    ├── 09.Alpenglow.ogg
    ├── 10.The_Eyes_Of_Sharbat_Gula.ogg
    └── 11.The_Greatest_Show_On_Earth.ogg
```

**Comment by gnumdk** [comment]
Can you send me ~/.local/share/lollypop/lollypop.db by email?

**Comment by rumpelsepp** [comment]
done.

**Comment by gnumdk** [comment]
Not a bug ;)

You have the 2 albums in two different path:
- /home/stefan/Music/Nightwish
- /home/stefan/Music

Or, the bug is about cleaning not existing files...

**Comment by rumpelsepp** [comment]
> Or, the bug is about cleaning not existing files...

Yeah, indeed. I recently moved the album into the Nightwish subdirectory.

**Comment by gnumdk** [comment]
And you updated the music?

**Comment by rumpelsepp** [comment]
> And you updated the music?

Damn! Sorry for the clutter. :)
