### ISSUE TITLE
Online music (youtube) doesn't work

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [gnumdk/lollypop#990]
• Lollypop version: 0.9.230
• Gtk Version: 3.22
• Linux distribution: Ubuntu GNOME 16.10
If I try to listen to any song online, an error pops up as a notification
"WebYouTube::get_uri_content: ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))"
and i have to force close Lollypop.
I have tryed many songs, all of which work perfectly fine in the web browser, but crash Lollypop.
i have tryed it with the default youtube-dl that comes shipped with ubuntu, the pip version, and even the basic file that one can install using instructions from the website.

**Comment by gnumdk** [comment]
The message is from youtube-dl, will update package

**Comment by GNOME-IS-LIFE** [comment]
umm, still no update yet? the problem still occurs :(

**Comment by gnumdk** [comment]
Ubuntu is broken by design, not my fault ;)
Tried by I have an issue with my building env.

**Comment by gnumdk** [comment]
Package is building ;)

**Comment by GNOME-IS-LIFE** [comment]
any idea when it will finish building? (also off topic: lollypop is THE best music player, even without the online functions!)

**Comment by gnumdk** [comment]
Now...

**Comment by GNOME-IS-LIFE** [comment]
still didn't work... no new Lollypop update that I'm currently receiving
