### ISSUE TITLE
Not able to edit mp3 tags of albums and tracks

### ISSUE THREAD

**Issue by BobbyBabes** [gnumdk/lollypop#991]
• _Lollypop version:_ **0.9.230**
• _Gtk Version:_ **gtk3-3.22.9-1-x86_64** (https://www.archlinux.org/packages/extra/x86_64/gtk3/)
• _Linux distribution:_ **Linux LadyLuck 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux**

I started off using Lollypop from v0.9.229, now on v0.9.230, and I was never able to edit mp3 tags. Not for albums. Not for tracks.
I installed `kid3-cli` as per the message in Preferences.
`lollypop-portal` was already installed and running :
```
[BobbyBabes@LadyLuck ~]# ps aux | grep -ie lollypop
BobbyBabes   17469  0.0  0.2 305744 20700 ?        Sl   Mar03   0:00 python3 /usr/share/lollypop-portal/lollypop-portal
BobbyBabes   26445  2.3  1.9 3899036 156492 ?      SLl  02:01   0:35 python3 /usr/bin/lollypop
BobbyBabes   27028  0.0  0.0  10768  2208 pts/0    S+   02:26   0:00 grep -ie lollypop
[BobbyBabes@LadyLuck ~]# 
```

This chap seems to have his `Modificar etiquetas` going : https://github.com/gnumdk/lollypop/issues/819

**Comment by gnumdk** [comment]
You need a GUI tag editor, not kid3 cli!

**Comment by BobbyBabes** [comment]
Then what is the message to install kid3-cli for, that's displayed in `Preferences >> Behaviour >> Save changes to files` ?

**Comment by gnumdk** [comment]
For saving covers/notes to tags.

**Comment by BobbyBabes** [comment]
Just for completeness.
I removed `kid3-cli`. Then installed `kid3` (ther GUI version) which provides `kid3-cli`.
