### ISSUE TITLE
Feature request : only local random tracks

### ISSUE THREAD

**Issue by eoli3n** [gnumdk/lollypop#992]
• Lollypop version: 0.9.230
• Linux distribution: Archlinux 4.9.11-1-ARCH

- Is there a way to trigger off internet music on playlist "random tracks"
or add a new one ``local random tracks``

**Comment by gnumdk** [comment]
Just disable network in Lollypop menu.

**Comment by eoli3n** [comment]
i did, and restarted lollypop, didn't work
