### ISSUE TITLE
GTK Warning and Crash

### ISSUE THREAD

**Issue by chelmzy** [gnumdk/lollypop#993]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.230
• Gtk Version: gtk 3.20.10-1.fc24
• Linux distribution: Fedora 24

<Describe your bug here>
Get these errors when launching the application and it then crashes.

(lollypop:9542): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x55bcf4e0b6f0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:9542): Gtk-WARNING **: Allocating size to lollypop+selectionlist+SelectionList 0x55bcf47c8880 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

List of packages I recently updated:

libbsd                     i686       0.8.3-1.fc24           updates      93 k
 libbsd                     x86_64     0.8.3-1.fc24           updates      87 k
 anki                       noarch     2.0.43-1.fc24          updates     2.4 M
 bind99-libs                x86_64     9.9.9-4.P6.fc24        updates     671 k
 bind99-license             noarch     9.9.9-4.P6.fc24        updates      12 k
 coreutils                  x86_64     8.25-8.fc24            updates     1.1 M
 coreutils-common           x86_64     8.25-8.fc24            updates     1.9 M
 fedora-repos               noarch     24-4                   updates      88 k
 gpgme                      x86_64     1.8.0-10.fc24          updates     196 k
 gtk-vnc2                   x86_64     0.7.0-1.fc24           updates      44 k
 gvnc                       x86_64     0.7.0-1.fc24           updates      96 k
 iw                         x86_64     4.9-1.fc24             updates      79 k
 libICE                     i686       1.0.9-8.fc24           updates      70 k
 libICE                     x86_64     1.0.9-8.fc24           updates      69 k
 libXdmcp                   x86_64     1.1.2-5.fc24           updates      37 k
 libnetfilter_conntrack     x86_64     1.0.6-2.fc24           updates      58 k
 libseccomp                 i686       2.3.2-1.fc24           updates      58 k
 libseccomp                 x86_64     2.3.2-1.fc24           updates      60 k
 libsmbclient               x86_64     2:4.4.10-0.fc24        updates     123 k
 libwbclient                x86_64     2:4.4.10-0.fc24        updates      98 k
 open-vm-tools              x86_64     10.1.5-2.fc24          updates     666 k
 open-vm-tools-desktop      x86_64     10.1.5-2.fc24          updates     159 k
 ostree                     x86_64     2017.2-3.fc24.1        updates     179 k
 ostree-libs                x86_64     2017.2-3.fc24.1        updates     256 k
 oxygen-icon-theme          noarch     1:5.31.0-1.fc24        updates      29 M
 samba-client               x86_64     2:4.4.10-0.fc24        updates     545 k
 samba-client-libs          x86_64     2:4.4.10-0.fc24        updates     4.6 M
 samba-common               noarch     2:4.4.10-0.fc24        updates     189 k
 samba-common-libs          x86_64     2:4.4.10-0.fc24        updates     158 k
 samba-common-tools         x86_64     2:4.4.10-0.fc24        updates     449 k
 samba-libs                 x86_64     2:4.4.10-0.fc24        updates     257 k
 samba-winbind              x86_64     2:4.4.10-0.fc24        updates     486 k
 samba-winbind-clients      x86_64     2:4.4.10-0.fc24        updates     122 k
 samba-winbind-modules      x86_64     2:4.4.1

**Comment by gnumdk** [comment]
As Lollypop is a python program, crash is not in Lollypop. Closing

**Comment by gnumdk** [comment]
Was due to: https://bugzilla.gnome.org/show_bug.cgi?id=731501
