### ISSUE TITLE
option to disable preview on cursor hoovering

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#994]
it would be nice to have an option to disable song previews...sometimes it get confusing when listening to a song and mistakenly moving your cursor and another one song starts together...it's even problematic when you want to rate songs and you can't if your listening something else because the song you want to rate will start over the existing one...

**Comment by gnumdk** [comment]
Option exists and you have activated preview (not default)

**Comment by Pointedstick** [comment]
Where is the option? I can't find it anywhere.

**Comment by gnumdk** [comment]
In behaviour

**Comment by Pointedstick** [comment]
Oh. "Preview tracks on <thing>". Wow, I didn't realize that's what it was for.

For me, the default setting was "Built-in Analog Stereo", instead of "No audio device". Is this intentional?

**Comment by gnumdk** [comment]
No you changed it, check in dconf

**Comment by Pointedstick** [comment]
You're right! Don't remember changing that, weird.
