### ISSUE TITLE
Graphical distortion on KDE when using Breeze style

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#995]
• Lollypop version: 0.9.227-1.2
• Gtk Version: 3.22.8-1.1
• Linux distribution: OpenSUSE Tumbleweed

On KDE Plasma 5.9.2, the genre and artist lists show graphical distortion. If I change the visual style to Adwaita (systemsettings > Application Style > GNOME Application Style (GTK), the problem disappears. And thisdoes not happen on Fedora 25 with GNOME 3.22, which I have on the same machine. Screenshot showing the issue with the Breeze style:

![graphical_distortion](https://cloud.githubusercontent.com/assets/1097249/23685952/0d269c4e-0364-11e7-8c6b-6ff388a7443d.png)

**Comment by gnumdk** [comment]
It's a GTK BUG. Can't do anything

**Comment by Pointedstick** [comment]
OK thanks. I've filed a bug on GTK: https://bugzilla.gnome.org/show_bug.cgi?id=779759

**Comment by gnumdk** [comment]
Bug report already exists somewhere, due to CSS cache broken.
