### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#998]
this is not an issue but just an help request :P 
i don't know how to make the google api key work...i've created new credentials then inserted the custom api key to lollypop but artwork fetcher always says there's no key and it's not giving me any result...any help?

**Comment by gnumdk** [comment]
http://help.dimsemenov.com/kb/wordpress-royalslider-tutorials/wp-how-to-get-youtube-api-key

**Comment by legacychimera247** [comment]
exactly what i've done but was not working...anyway now it's working perfectly :)
